-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=tenant function=permissions
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/tenant/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * permissions
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/tenant/163_enterprise_authorization_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.permissions (
  permission_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code            TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  description     TEXT,
  module_code     TEXT NOT NULL,
  resource_code   TEXT,
  action_code     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_permissions_module ON __TENANT_SCHEMA__.permissions(module_code);

CREATE INDEX IF NOT EXISTS idx_permissions_code ON __TENANT_SCHEMA__.permissions(code);
