-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=tenant function=so
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/tenant/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * roles
--   * so
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/tenant/030_authorization_redesign_tenant.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS so a schema that already has
-- this table (from an older bootstrap) is left untouched.
-- ============================================================================

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.roles (
  role_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role_code VARCHAR(50) NOT NULL UNIQUE,
  name_en TEXT NOT NULL,
  name_ar TEXT,
  description TEXT,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roles_code ON __TENANT_SCHEMA__.roles(role_code);

CREATE INDEX IF NOT EXISTS idx_roles_is_system ON __TENANT_SCHEMA__.roles(is_system) WHERE is_system = TRUE;
