import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const AI_WIDGETS: WidgetManifest[] = [
  {
    id: 'ai.red_team_board',
    key: 'red_team_board',
    title: 'Red Team Board',
    titleAr: 'لوحة الفريق الأحمر',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/ai-ops/red-team-board.widget').then(m => m.RedTeamBoardWidget),
    icon: '🛡️',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'ai.summary',
    key: 'ai_summary',
    title: 'AI Summary',
    titleAr: 'ملخص الذكاء الاصطناعي',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/ai-ops/ai-summary.widget').then(m => m.AISummaryWidget),
    icon: '🤖',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'ai.insights_echart',
    key: 'ai_insights',
    title: 'AI Insights',
    titleAr: 'رؤى الذكاء الاصطناعي',
    category: 'ai',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/ai-insights-echart.component').then(m => m.AiInsightsEchartComponent),
    icon: '🧠',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'ai.one_sentence_truth',
    key: 'one_sentence_truth',
    title: 'One Sentence Truth',
    titleAr: 'حقيقة بجملة واحدة',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/executive/one-sentence-truth.widget').then(m => m.OneSentenceTruthWidget),
    icon: '💡',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'ai.future_you',
    key: 'future_you',
    title: 'Future You',
    titleAr: 'أنت بعد سنة',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/future-you.widget').then(m => m.FutureYouWidget),
    icon: '🔮',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'ai.if_nothing_changes',
    key: 'if_nothing_changes',
    title: 'If Nothing Changes',
    titleAr: 'إذا لم يتغير شيء',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/if-nothing-changes.widget').then(m => m.IfNothingChangesWidget),
    icon: '📉',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'ai.guard_stats',
    key: 'guard_stats',
    title: 'Guard Decisions',
    titleAr: 'قرارات الحماية',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/control/guard-stats.widget').then(m => m.GuardStatsWidget),
    icon: '🛡️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin'],
    schemaVersion: 1,
  },
  {
    id: 'ai.eval_slo',
    key: 'eval_slo',
    title: 'Eval SLO Status',
    titleAr: 'حالة اتفاقيات جودة التقييم',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/ai-ops/eval-slo.widget').then(m => m.EvalSloWidget),
    icon: '📊',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin'],
    schemaVersion: 1,
  },
  {
    id: 'ai.gateway_health',
    key: 'gateway_health',
    title: 'AI Gateway Health',
    titleAr: 'صحة بوابة الذكاء الاصطناعي',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/governance/gateway-health.widget').then(m => m.GatewayHealthWidget),
    icon: '🔌',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin'],
    schemaVersion: 1,
  },
  {
    id: 'ai.llm_usage',
    key: 'llm_usage',
    title: 'LLM Usage & Budget',
    titleAr: 'استخدام وميزانية النماذج اللغوية',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/ai-ops/llm-usage.widget').then(m => m.LlmUsageWidget),
    icon: '💰',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin'],
    schemaVersion: 1,
  },
  {
    id: 'ai.feedback_score',
    key: 'feedback_score',
    title: 'User Feedback Score',
    titleAr: 'درجة ملاحظات المستخدمين',
    category: 'ai',
    engine: 'angular',
    component: () => import('../../../components/ai-ops/feedback-score.widget').then(m => m.FeedbackScoreWidget),
    icon: '⭐',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
];
