-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=compliance scope=public function=grc
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/compliance/db/public/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (6):
--   * grc_architecture_map
--   * grc_audit_universe
--   * grc_framework_dependencies
--   * grc_kri_catalog
--   * grc_maturity_model
--   * grc_risk_domain_coverage
--
-- Source migrations (immutable, 1):
--   * modules/compliance/db/public/migrations/200_seed_ksa_grc_allsectors_catalog.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.grc_audit_universe (
  audit_id              TEXT PRIMARY KEY,
  sector                TEXT,
  audit_area            TEXT NOT NULL,
  frameworks_covered    TEXT,
  audit_type            TEXT,
  auditor               TEXT,
  frequency             TEXT,
  scope_who             TEXT,
  key_evidence_tested   TEXT,
  risk_rating           TEXT,
  est_days              TEXT,
  regulatory_deadline   TEXT,
  framework_verified    TEXT,
  linked_kris           TEXT,
  shahin_ai_priority    TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.grc_kri_catalog (
  kri_id                TEXT PRIMARY KEY,
  sector                TEXT,
  kri_name              TEXT NOT NULL,
  framework_source      TEXT,
  grc_pillar            TEXT,
  risk_domain           TEXT,
  measurement_formula   TEXT,
  threshold_green       TEXT,
  threshold_amber       TEXT,
  threshold_red         TEXT,
  data_source           TEXT,
  owner                 TEXT,
  frequency             TEXT,
  ksa_benchmark         TEXT,
  framework_verified    TEXT,
  regulator_hc_iot      TEXT,
  shahin_ai_tier        TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.grc_maturity_model (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_sector         TEXT NOT NULL UNIQUE,
  level1_initial        TEXT,
  level2_developing     TEXT,
  level3_defined        TEXT,
  level4_managed        TEXT,
  level5_optimising     TEXT,
  typical_ksa_2024      TEXT,
  ghicga_target         TEXT,
  evidence_at_l3        TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.grc_risk_domain_coverage (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  framework_code        TEXT NOT NULL UNIQUE,
  cyber_risk            TEXT,
  privacy_risk          TEXT,
  clinical_safety       TEXT,
  operational_risk      TEXT,
  regulatory_risk       TEXT,
  reputational_risk     TEXT,
  strategic_risk        TEXT,
  supply_chain_risk     TEXT,
  financial_risk        TEXT,
  availability_risk     TEXT,
  cross_border_risk     TEXT,
  coverage_score        TEXT,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.grc_framework_dependencies (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_code           TEXT NOT NULL,
  target_code           TEXT NOT NULL,
  relationship          TEXT,
  notes                 TEXT,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source_code, target_code, relationship)
);

CREATE TABLE IF NOT EXISTS public.grc_architecture_map (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grc_layer             TEXT,
  framework_code        TEXT NOT NULL UNIQUE,
  framework_name        TEXT,
  issuing_authority     TEXT,
  grc_pillar            TEXT,
  compliance_type       TEXT,
  feeds_into            TEXT,
  conflicts_with        TEXT,
  gap_filled            TEXT,
  hc_iot_weight         TEXT,
  priority_tier         TEXT,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
