-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=compliance scope=public function=sod
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/compliance/db/public/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * sod_rules
--   * sod_waivers
--
-- Source migrations (immutable, 2):
--   * modules/compliance/db/public/migrations/131_sod_rules.sql
--   * modules/compliance/db/public/migrations/132_sod_waivers.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS sod_rules (
  policy_id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_code                 VARCHAR(100) NOT NULL,
  role_code_a               VARCHAR(100) NOT NULL,
  role_code_b               VARCHAR(100) NOT NULL,
  conflict_level            VARCHAR(20)  NOT NULL DEFAULT 'warn'
                              CHECK (conflict_level IN ('block','escalate','warn','allow')),
  enforcement               VARCHAR(20)  NOT NULL DEFAULT 'block'
                              CHECK (enforcement IN ('block','warn','log')),
  module_code               VARCHAR(100),
  description               TEXT,
  is_active                 BOOLEAN      NOT NULL DEFAULT TRUE,
  temporary_waiver_allowed  BOOLEAN      NOT NULL DEFAULT FALSE,
  waiver_max_days           INTEGER,
  created_by                VARCHAR(128),
  created_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (rule_code)
);

CREATE INDEX IF NOT EXISTS idx_sod_rules_active_roles
  ON sod_rules (is_active, role_code_a, role_code_b);

CREATE INDEX IF NOT EXISTS idx_sod_rules_module
  ON sod_rules (module_code) WHERE module_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS sod_waivers (
  waiver_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       VARCHAR(64)  NOT NULL,
  rule_code     VARCHAR(100) NOT NULL,
  granted_by    VARCHAR(128) NOT NULL,
  granted_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  expires_at    TIMESTAMPTZ  NOT NULL,
  revoked_at    TIMESTAMPTZ,
  revoked_by    VARCHAR(128),
  revoke_reason TEXT,
  reason        TEXT,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_sod_waivers_active_user
  ON sod_waivers (user_id, rule_code)
  WHERE is_active = TRUE AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sod_waivers_expiry
  ON sod_waivers (expires_at)
  WHERE is_active = TRUE AND revoked_at IS NULL;
