import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const REPORTING_WIDGETS: WidgetManifest[] = [
  // ── Landing Page ──
  {
    id: 'reporting.year_in_grc',
    key: 'year_in_grc',
    title: 'Your Year in GRC',
    titleAr: 'سنتك في GRC',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/executive/year-in-grc.widget').then(m => m.YearInGrcWidget),
    icon: '📅',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.pain_mirror',
    key: 'pain_mirror',
    title: 'Pain Mirror',
    titleAr: 'مرآة الألم',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/pain-mirror.widget').then(m => m.PainMirrorWidget),
    icon: '🪞',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.breaking_the_cycle',
    key: 'breaking_the_cycle',
    title: 'Breaking the Cycle',
    titleAr: 'كسر الدورة',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/breaking-the-cycle.widget').then(m => m.BreakingTheCycleWidget),
    icon: '💥',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  // ── External View ──
  {
    id: 'reporting.board_reality',
    key: 'board_reality',
    title: 'Board Reality',
    titleAr: 'واقع مجلس الإدارة',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/governance/board-reality.widget').then(m => m.BoardRealityWidget),
    icon: '📊',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'reporting.regulator_lens',
    key: 'regulator_lens',
    title: 'Regulator Lens',
    titleAr: 'عين المراجع',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/regulator-lens.widget').then(m => m.RegulatorLensWidget),
    icon: '🧑‍⚖️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'reporting.reputation_impact',
    key: 'reputation_impact',
    title: 'Reputation Impact',
    titleAr: 'أثر السمعة',
    category: 'reporting',
    engine: 'angular',
    component: () => import('../../../components/risk/reputation-impact.widget').then(m => m.ReputationImpactWidget),
    icon: '📡',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  // ── Analytics Charts ──
  {
    id: 'reporting.trend_line',
    key: 'trend_line',
    title: 'Trend Line',
    titleAr: 'خط الاتجاه',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../echart-components/line/trend-line-echart.component').then(m => m.TrendLineEchartComponent),
    icon: '📈',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'reporting.sparkline',
    key: 'sparkline',
    title: 'Sparkline',
    titleAr: 'خط مصغر',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/line/sparkline-echart.component').then(m => m.SparklineEchartComponent),
    icon: '〰️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'risk_manager', 'auditor', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'reporting.remediation_velocity',
    key: 'remediation_velocity',
    title: 'Remediation Velocity',
    titleAr: 'سرعة المعالجة',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/line/remediation-velocity.component').then(m => m.RemediationVelocityComponent),
    icon: '⚡',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.rolling_forecast',
    key: 'rolling_forecast',
    title: 'Rolling Forecast',
    titleAr: 'التنبؤ المتجدد',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/line/rolling-forecast.component').then(m => m.RollingForecastComponent),
    icon: '🔮',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.grc_pulse_river',
    key: 'grc_pulse_river',
    title: 'GRC Pulse River',
    titleAr: 'نهر نبض GRC',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/grc-pulse-river.component').then(m => m.GrcPulseRiverComponent),
    icon: '🌊',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.animated_ranking',
    key: 'animated_ranking',
    title: 'Animated Ranking Race',
    titleAr: 'ترتيب متحرك',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/bar/animated-ranking.component').then(m => m.AnimatedRankingComponent),
    icon: '🏁',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.bullet_chart',
    key: 'bullet_chart',
    title: 'Bullet Chart',
    titleAr: 'مخطط رصاصي',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/bar/bullet-chart.component').then(m => m.BulletChartComponent),
    icon: '🎯',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  // ── Graph / Network ──
  {
    id: 'reporting.chord_diagram',
    key: 'chord_diagram',
    title: 'Chord Diagram',
    titleAr: 'مخطط وتري',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/graph/chord-diagram.component').then(m => m.ChordDiagramComponent),
    icon: '🔗',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.entity_graph',
    key: 'entity_graph',
    title: 'Entity Relationship Graph',
    titleAr: 'شبكة الكيانات',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/graph/entity-graph.component').then(m => m.EntityGraphComponent),
    icon: '🕸️',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.network_graph',
    key: 'network_graph',
    title: 'Network Graph (Enhanced)',
    titleAr: 'شبكة متقدمة',
    category: 'reporting',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/graph/network-graph-enhanced.component').then(m => m.NetworkGraphEnhancedComponent),
    icon: '🌐',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  // ── D3 Premium ──
  {
    id: 'reporting.d3_animated_bar',
    key: 'd3_animated_bar',
    title: 'Animated Bar (D3)',
    titleAr: 'أعمدة متحركة D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/animated-bar-chart.component').then(m => m.AnimatedBarChartComponent),
    icon: '📊',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.d3_animated_donut',
    key: 'd3_animated_donut',
    title: 'Animated Donut (D3)',
    titleAr: 'دائرة متحركة D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/animated-donut-chart.component').then(m => m.AnimatedDonutChartComponent),
    icon: '🍩',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.d3_gauge',
    key: 'd3_gauge',
    title: 'Gauge (D3)',
    titleAr: 'مقياس D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/gauge-chart.component').then(m => m.GaugeChartComponent),
    icon: '🎯',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.d3_progress_ring',
    key: 'd3_progress_ring',
    title: 'Progress Ring (D3)',
    titleAr: 'حلقة تقدم D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/progress-ring-chart.component').then(m => m.ProgressRingChartComponent),
    icon: '⭕',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.d3_radar',
    key: 'd3_radar',
    title: 'Radar (D3)',
    titleAr: 'رادار D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/radar-chart.component').then(m => m.RadarChartComponent),
    icon: '📡',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'reporting.d3_sparkline',
    key: 'd3_sparkline',
    title: 'Sparkline (D3)',
    titleAr: 'خط مصغر D3',
    category: 'reporting',
    engine: 'd3',
    component: () => import('../../../d3-charts/sparkline-chart.component').then(m => m.SparklineChartComponent),
    icon: '〰️',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
];
