/**
 * asset — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition } from './ports/lifecycle.port';

const ASSET_MODULE_STATES = [
  'draft', 'registered', 'classified', 'under_review', 'approved', 'active',
  'review_due', 'under_reclassification', 're_approved', 'decommissioned',
] as const;

const ASSET_MODULE_TRANSITIONS: Record<string, string[]> = {
  draft:                    ['registered'],
  registered:               ['classified'],
  classified:               ['under_review'],
  under_review:             ['approved'],
  approved:                 ['active'],
  active:                   ['review_due', 'decommissioned'],
  review_due:               ['under_reclassification'],
  under_reclassification:   ['re_approved'],
  re_approved:              ['active'],
  decommissioned:           [],
};

registerLifecycleDefinition(
  'asset',
  'asset',
  ASSET_MODULE_STATES,
  ASSET_MODULE_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['decommissioned'],
    transitionPermissions: {
      'draft->registered': 'asset.record.update',
      'registered->classified': 'asset.record.update',
      'classified->under_review': 'asset.classification.review',
      'under_review->approved': 'asset.classification.review',
      'approved->active': 'asset.record.update',
      'active->review_due': 'asset.record.update',
      'review_due->under_reclassification': 'asset.record.update',
      'under_reclassification->re_approved': 'asset.classification.review',
      're_approved->active': 'asset.record.update',
      'active->decommissioned': 'asset.record.update',
    },
  },
);

const ASSET_INVENTORY_STATES = [
  'draft',
  'classified',
  'active',
  'decommissioning',
  'decommissioned',
  'archived',
] as const;

const ASSET_INVENTORY_TRANSITIONS: Record<string, string[]> = {
  draft           : ['classified'],
  classified      : ['active'],
  active          : ['decommissioning'],
  decommissioning : ['decommissioned'],
  decommissioned  : ['archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'asset',
  'asset_inventory',
  ASSET_INVENTORY_STATES,
  ASSET_INVENTORY_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const ASSET_CLASSIFICATIONS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ASSET_CLASSIFICATIONS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'asset',
  'asset_classifications',
  ASSET_CLASSIFICATIONS_STATES,
  ASSET_CLASSIFICATIONS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const ASSET_TYPES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ASSET_TYPES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'asset',
  'asset_types',
  ASSET_TYPES_STATES,
  ASSET_TYPES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const ASSET_LIFECYCLE_EVENTS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ASSET_LIFECYCLE_EVENTS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'asset',
  'asset_lifecycle_events',
  ASSET_LIFECYCLE_EVENTS_STATES,
  ASSET_LIFECYCLE_EVENTS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);
