/**
 * governance-ai — Approval Matrix
 * Aligned to canonical lifecycle states from lifecycle-registration.ts
 * 2 entity types: governance_signal (detected→archived), governance_model (training→retired)
 */

import type { ApprovalRule } from '@dos/types';

export const GOVERNANCE_AI_APPROVAL_MATRIX: ApprovalRule[] = [
  {
    entityType: 'governance_signal',
    fromStatus: 'interpreted',
    toStatus: 'escalated',
    requiredRole: 'governance_ai.operator',
    requiredPermission: 'governance_ai.signal.escalate',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['governance_ai.module_lead', 'governance_ai.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['governance_ai.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'governance_signal',
    fromStatus: 'escalated',
    toStatus: 'resolved',
    requiredRole: 'governance_ai.approver',
    requiredPermission: 'governance_ai.signal.resolve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['governance_ai.module_lead', 'governance_ai.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['governance_ai.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'governance_signal',
    fromStatus: 'any',
    toStatus: 'dismissed',
    requiredRole: 'governance_ai.module_lead',
    requiredPermission: 'governance_ai.signal.dismiss',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['governance_ai.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['governance_ai.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'governance_model',
    fromStatus: 'testing',
    toStatus: 'active',
    requiredRole: 'governance_ai.module_lead',
    requiredPermission: 'governance_ai.model.deploy',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['governance_ai.module_lead', 'governance_ai.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['governance_ai.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'governance_model',
    fromStatus: 'active',
    toStatus: 'retired',
    requiredRole: 'governance_ai.executive_owner',
    requiredPermission: 'governance_ai.model.retire',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['governance_ai.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['governance_ai.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
];
