-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=workflow scope=tenant function=chain
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/workflow/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * workflow_chain_definitions
--
-- Source migrations (immutable, 1):
--   * modules/workflow/db/tenant/migrations/000_extracted_from_000_inline_baseline.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_chain_definitions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chain_code TEXT NOT NULL,
  name TEXT,
  description TEXT,
  definition JSONB DEFAULT '{}',
  status TEXT DEFAULT 'active',
  tenant_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
