-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=workflow scope=tenant function=core
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/workflow/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (14):
--   * above
--   * workflow_ai_notes
--   * workflow_approvals
--   * workflow_chains
--   * workflow_escalations
--   * workflow_event_log
--   * workflow_instances
--   * workflow_kill_switches
--   * workflow_sla_configs
--   * workflow_steps
--   * workflow_template_library
--   * workflow_templates
--   * workflow_transitions
--   * workflows
--
-- Source migrations (immutable, 1):
--   * modules/workflow/db/tenant/migrations/001_workflow_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflows (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  code              TEXT NOT NULL,
  name              TEXT NOT NULL,
  description       TEXT,
  status            TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','deprecated')),
  version           INTEGER NOT NULL DEFAULT 1,
  config            JSONB NOT NULL DEFAULT '{}',
  created_by        UUID NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_instances (
  instance_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  workflow_type     TEXT NOT NULL,
  name              TEXT,
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','in_progress','awaiting_review','completed','cancelled','failed')),
  current_step      TEXT,
  total_steps       INTEGER NOT NULL DEFAULT 0,
  created_by        UUID NOT NULL,
  entity_type       TEXT,
  entity_id         UUID,
  context           JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at      TIMESTAMPTZ,
  cancelled_at      TIMESTAMPTZ,
  cancel_reason     TEXT
);

CREATE TABLE above already makes instance_id the
-- PK (satisfies FK targeting). On a schema where 027's stub pre-exists
-- the CREATE TABLE no-ops;

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_steps (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL,
  step_name         TEXT NOT NULL,
  step_order        INTEGER NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed','skipped','failed')),
  assigned_to       UUID,
  started_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ,
  outcome           TEXT,
  notes             TEXT,
  metadata          JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_transitions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL,
  from_step         TEXT,
  to_step           TEXT NOT NULL,
  from_status       TEXT,
  to_status         TEXT NOT NULL,
  triggered_by      UUID NOT NULL,
  trigger_type      TEXT NOT NULL DEFAULT 'manual' CHECK (trigger_type IN ('manual','automatic','system','ai')),
  notes             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_templates (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  code              TEXT NOT NULL,
  name              TEXT NOT NULL,
  description       TEXT,
  version           INTEGER NOT NULL DEFAULT 1,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  template_config   JSONB NOT NULL DEFAULT '{}',
  steps_config      JSONB NOT NULL DEFAULT '[]',
  sla_config        JSONB NOT NULL DEFAULT '{}',
  created_by        UUID NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, code, version)
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_template_library (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  template_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_templates(id),
  is_published      BOOLEAN NOT NULL DEFAULT FALSE,
  published_at      TIMESTAMPTZ,
  published_by      UUID,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_approvals (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL,
  step_id           UUID REFERENCES __TENANT_SCHEMA__.workflow_steps(id),
  approval_type     TEXT NOT NULL CHECK (approval_type IN ('single','majority','unanimous','sequential')),
  required_approvers JSONB NOT NULL DEFAULT '[]',
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','escalated','expired')),
  decision          TEXT,
  decided_by        UUID,
  decided_at        TIMESTAMPTZ,
  notes             TEXT,
  due_at            TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_sla_configs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  workflow_type     TEXT NOT NULL,
  step_name         TEXT,
  sla_hours         INTEGER NOT NULL,
  warning_hours     INTEGER,
  escalation_hours  INTEGER,
  escalation_to     UUID,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_escalations (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL,
  escalation_type   TEXT NOT NULL CHECK (escalation_type IN ('sla_breach','manual','ai_triggered')),
  escalated_to      UUID NOT NULL,
  escalated_by      UUID,
  reason            TEXT,
  status            TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','resolved')),
  resolved_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_event_log (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL,
  tenant_id         UUID NOT NULL,
  event_type        TEXT NOT NULL,
  payload           JSONB NOT NULL DEFAULT '{}',
  actor_id          UUID,
  correlation_id    UUID,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_chains (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  name              TEXT NOT NULL,
  description       TEXT,
  config            JSONB NOT NULL DEFAULT '{}',
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_by        UUID NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_ai_notes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL,
  note_type         TEXT NOT NULL,
  content           TEXT NOT NULL,
  model_used        TEXT,
  confidence        NUMERIC(5,4),
  created_by        UUID,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_kill_switches (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  workflow_type     TEXT,
  instance_id       UUID,
  is_active         BOOLEAN NOT NULL DEFAULT FALSE,
  reason            TEXT,
  activated_by      UUID,
  activated_at      TIMESTAMPTZ,
  deactivated_at    TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workflow_instances_tenant ON __TENANT_SCHEMA__.workflow_instances(tenant_id);

CREATE INDEX IF NOT EXISTS idx_workflow_instances_status ON __TENANT_SCHEMA__.workflow_instances(status);

CREATE INDEX IF NOT EXISTS idx_workflow_instances_entity ON __TENANT_SCHEMA__.workflow_instances(entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_workflow_steps_instance ON __TENANT_SCHEMA__.workflow_steps(instance_id);

CREATE INDEX IF NOT EXISTS idx_workflow_approvals_instance ON __TENANT_SCHEMA__.workflow_approvals(instance_id);

CREATE INDEX IF NOT EXISTS idx_workflow_event_log_instance ON __TENANT_SCHEMA__.workflow_event_log(instance_id);

CREATE INDEX IF NOT EXISTS idx_workflow_escalations_tenant ON __TENANT_SCHEMA__.workflow_escalations(tenant_id, status);
