-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=workflow scope=tenant function=versions
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/workflow/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (14):
--   * workflow_ai_suggestions
--   * workflow_attachments
--   * workflow_change_log
--   * workflow_comments
--   * workflow_delegation_rules
--   * workflow_external_mappings
--   * workflow_kpis
--   * workflow_metrics
--   * workflow_notifications
--   * workflow_report_snapshots
--   * workflow_settings
--   * workflow_tags
--   * workflow_task_assignments
--   * workflow_versions
--
-- Source migrations (immutable, 1):
--   * modules/workflow/db/tenant/migrations/002_enterprise_expansion.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_versions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  version         INT NOT NULL,
  data            JSONB NOT NULL DEFAULT '{}',
  changed_by      UUID NOT NULL,
  changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_change_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  field_name      TEXT NOT NULL,
  old_value       TEXT,
  new_value       TEXT,
  changed_by      UUID NOT NULL,
  changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  correlation_id  UUID,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_settings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  config_key      TEXT NOT NULL,
  config_value    JSONB NOT NULL DEFAULT '{}',
  scope           TEXT NOT NULL DEFAULT 'tenant',
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, config_key)
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_kpis (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  kpi_code        TEXT NOT NULL,
  name            TEXT NOT NULL,
  current_value   NUMERIC,
  target_value    NUMERIC,
  unit            TEXT,
  period_start    DATE,
  period_end      DATE,
  trend           TEXT,
  computed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_report_snapshots (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  report_type     TEXT NOT NULL,
  title           TEXT NOT NULL,
  parameters      JSONB NOT NULL DEFAULT '{}',
  result_data     JSONB NOT NULL DEFAULT '{}',
  generated_by    UUID NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_ai_suggestions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       UUID,
  suggestion_type TEXT NOT NULL,
  title           TEXT NOT NULL,
  description     TEXT,
  confidence      NUMERIC(5,4),
  model_used      TEXT,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','expired')),
  reviewed_by     UUID,
  reviewed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_external_mappings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       UUID NOT NULL,
  external_system TEXT NOT NULL,
  external_id     TEXT NOT NULL,
  sync_status     TEXT NOT NULL DEFAULT 'synced',
  last_synced_at  TIMESTAMPTZ,
  mapping_config  JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_attachments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       UUID NOT NULL,
  file_name       TEXT NOT NULL,
  file_type       TEXT,
  file_size       BIGINT,
  storage_path    TEXT NOT NULL,
  uploaded_by     UUID NOT NULL,
  uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_comments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       UUID NOT NULL,
  parent_id       UUID,
  content         TEXT NOT NULL,
  author_id       UUID NOT NULL,
  is_internal     BOOLEAN NOT NULL DEFAULT FALSE,
  is_resolved     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_tags (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       UUID NOT NULL,
  tag_key         TEXT NOT NULL,
  tag_value       TEXT,
  created_by      UUID NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_task_assignments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  instance_id     UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  step_id         UUID REFERENCES __TENANT_SCHEMA__.workflow_steps(id),
  assignee_id     UUID NOT NULL,
  assigned_by     UUID NOT NULL,
  assigned_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  due_at          TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  status          TEXT NOT NULL DEFAULT 'assigned',
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_delegation_rules (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL,
  workflow_type   TEXT NOT NULL,
  delegator_id    UUID NOT NULL,
  delegate_id     UUID NOT NULL,
  conditions      JSONB NOT NULL DEFAULT '{}',
  valid_from      DATE,
  valid_to        DATE,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_by      UUID NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_metrics (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id               UUID NOT NULL,
  workflow_type           TEXT NOT NULL,
  period                  TEXT NOT NULL,
  total_instances         INT,
  avg_completion_hours    NUMERIC,
  sla_compliance_rate     NUMERIC(5,2),
  bottleneck_step         TEXT,
  computed_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.workflow_notifications (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL,
  instance_id       UUID NOT NULL REFERENCES __TENANT_SCHEMA__.workflow_instances(instance_id) ON DELETE CASCADE,
  step_id           UUID REFERENCES __TENANT_SCHEMA__.workflow_steps(id),
  notification_type TEXT NOT NULL,
  recipient_id      UUID NOT NULL,
  channel           TEXT,
  sent_at           TIMESTAMPTZ,
  read_at           TIMESTAMPTZ,
  template_code     TEXT,
  payload           JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workflow_versions_entity ON __TENANT_SCHEMA__.workflow_versions(tenant_id, entity_id, entity_type);

CREATE INDEX IF NOT EXISTS idx_workflow_change_log_entity ON __TENANT_SCHEMA__.workflow_change_log(tenant_id, entity_id);

CREATE INDEX IF NOT EXISTS idx_workflow_kpis_tenant ON __TENANT_SCHEMA__.workflow_kpis(tenant_id, kpi_code);

CREATE INDEX IF NOT EXISTS idx_workflow_ai_suggestions_entity ON __TENANT_SCHEMA__.workflow_ai_suggestions(tenant_id, entity_id, status);

CREATE INDEX IF NOT EXISTS idx_workflow_attachments_entity ON __TENANT_SCHEMA__.workflow_attachments(tenant_id, entity_id);

CREATE INDEX IF NOT EXISTS idx_workflow_comments_entity ON __TENANT_SCHEMA__.workflow_comments(tenant_id, entity_id);

CREATE INDEX IF NOT EXISTS idx_workflow_tags_entity ON __TENANT_SCHEMA__.workflow_tags(tenant_id, entity_id);

CREATE INDEX IF NOT EXISTS idx_workflow_task_assignments_instance ON __TENANT_SCHEMA__.workflow_task_assignments(instance_id, status);

CREATE INDEX IF NOT EXISTS idx_workflow_task_assignments_assignee ON __TENANT_SCHEMA__.workflow_task_assignments(tenant_id, assignee_id, status);

CREATE INDEX IF NOT EXISTS idx_workflow_delegation_rules_tenant ON __TENANT_SCHEMA__.workflow_delegation_rules(tenant_id, delegator_id, is_active);

CREATE INDEX IF NOT EXISTS idx_workflow_metrics_tenant ON __TENANT_SCHEMA__.workflow_metrics(tenant_id, workflow_type, period);

CREATE INDEX IF NOT EXISTS idx_workflow_notifications_instance ON __TENANT_SCHEMA__.workflow_notifications(instance_id);

CREATE INDEX IF NOT EXISTS idx_workflow_notifications_recipient ON __TENANT_SCHEMA__.workflow_notifications(tenant_id, recipient_id, sent_at);
