import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const PRIVACY_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'PRIVACY.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'PRIVACY.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'PRIVACY.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'PRIVACY.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'PRIVACY.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'PRIVACY.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'PRIVACY.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'PRIVACY.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'PRIVACY.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  DSR_ANALYTICS_NOT_FOUND: { code: 'PRIVACY.DSR_ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Dsr Analytics not found', messageAr: 'Dsr Analytics غير موجود' },
  DSR_ANALYTICS_ALREADY_EXISTS: { code: 'PRIVACY.DSR_ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dsr Analytics already exists', messageAr: 'Dsr Analytics موجود بالفعل' },
  DSR_ANALYTICS_VALIDATION_FAILED: { code: 'PRIVACY.DSR_ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dsr Analytics validation failed', messageAr: 'فشل التحقق من Dsr Analytics' },
  BREACHES_NOT_FOUND: { code: 'PRIVACY.BREACHES_NOT_FOUND', httpStatus: 404, messageEn: 'Breaches not found', messageAr: 'Breaches غير موجود' },
  BREACHES_ALREADY_EXISTS: { code: 'PRIVACY.BREACHES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Breaches already exists', messageAr: 'Breaches موجود بالفعل' },
  BREACHES_VALIDATION_FAILED: { code: 'PRIVACY.BREACHES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Breaches validation failed', messageAr: 'فشل التحقق من Breaches' },
  CONSENT_STATUS_NOT_FOUND: { code: 'PRIVACY.CONSENT_STATUS_NOT_FOUND', httpStatus: 404, messageEn: 'Consent Status not found', messageAr: 'Consent Status غير موجود' },
  CONSENT_STATUS_ALREADY_EXISTS: { code: 'PRIVACY.CONSENT_STATUS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Consent Status already exists', messageAr: 'Consent Status موجود بالفعل' },
  CONSENT_STATUS_VALIDATION_FAILED: { code: 'PRIVACY.CONSENT_STATUS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Consent Status validation failed', messageAr: 'فشل التحقق من Consent Status' },
  REINDEX_NOT_FOUND: { code: 'PRIVACY.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'PRIVACY.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'PRIVACY.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'PRIVACY.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'PRIVACY.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'PRIVACY.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'PRIVACY.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'PRIVACY.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'PRIVACY.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  SEARCH_NOT_FOUND: { code: 'PRIVACY.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'PRIVACY.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'PRIVACY.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  DASHBOARD_NOT_FOUND: { code: 'PRIVACY.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'PRIVACY.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'PRIVACY.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  TRENDS_NOT_FOUND: { code: 'PRIVACY.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'PRIVACY.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'PRIVACY.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  CROSS_MODULE_NOT_FOUND: { code: 'PRIVACY.CROSS_MODULE_NOT_FOUND', httpStatus: 404, messageEn: 'Cross Module not found', messageAr: 'Cross Module غير موجود' },
  CROSS_MODULE_ALREADY_EXISTS: { code: 'PRIVACY.CROSS_MODULE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Cross Module already exists', messageAr: 'Cross Module موجود بالفعل' },
  CROSS_MODULE_VALIDATION_FAILED: { code: 'PRIVACY.CROSS_MODULE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Cross Module validation failed', messageAr: 'فشل التحقق من Cross Module' },
  EXPORT_NOT_FOUND: { code: 'PRIVACY.EXPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Export not found', messageAr: 'Export غير موجود' },
  EXPORT_ALREADY_EXISTS: { code: 'PRIVACY.EXPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Export already exists', messageAr: 'Export موجود بالفعل' },
  EXPORT_VALIDATION_FAILED: { code: 'PRIVACY.EXPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Export validation failed', messageAr: 'فشل التحقق من Export' },
  DSR_NOT_FOUND: { code: 'PRIVACY.DSR_NOT_FOUND', httpStatus: 404, messageEn: 'Dsr not found', messageAr: 'Dsr غير موجود' },
  DSR_ALREADY_EXISTS: { code: 'PRIVACY.DSR_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dsr already exists', messageAr: 'Dsr موجود بالفعل' },
  DSR_VALIDATION_FAILED: { code: 'PRIVACY.DSR_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dsr validation failed', messageAr: 'فشل التحقق من Dsr' },

  UNAUTHORIZED: { code: 'PRIVACY.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for privacy operation', messageAr: 'صلاحيات غير كافية لعملية privacy' },
  INVALID_STATE_TRANSITION: { code: 'PRIVACY.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'PRIVACY.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'PRIVACY.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'PRIVACY.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'PRIVACY.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type PrivacyErrorCode = keyof typeof PRIVACY_ERROR_CODES;
