-- 20260507_2200_overview_enterprise_props_part2.sql
-- Enterprise props for remaining command-home/overview rows:
-- /workflow /dynamic-ui/overview /knowledge /knowledge-hub /reporting /reports/overview
-- /risk/overview /workflow/hub /policy/* /controls/home
-- Plus any remaining generic command-home rows still using minimal scaffold.
-- Idempotent: always overwrites to enterprise standard.

BEGIN;

UPDATE dos.ui_route_template_binding SET
  props = v.p, title_en = v.ten, title_ar = v.tar,
  subtitle_en = v.sen, subtitle_ar = v.sar,
  eyebrow_en = v.een, eyebrow_ar = v.ear,
  version = version + 1, updated_at = now()
FROM (VALUES

('/workflow',
 'Workflow','سير العمل',
 'Design, execute and monitor governance workflows across all modules.','تصميم وتنفيذ ومراقبة سير عمل الحوكمة عبر جميع الوحدات.',
 'Workflow','سير العمل',
 '{"eyebrow":"Workflow","title":"Workflow","subtitle":"Design, execute and monitor governance workflows across all modules.","aiHeadline":"5 workflows stalled — owner action required","loading":false,"heroKpi":{"label":"Active workflows","value":0,"delta":"","status":"info","aiInsight":"Workflows currently in execution"},"kpis":[{"label":"Active","value":0,"status":"info","link":"/workflow/workflows"},{"label":"Overdue","value":0,"status":"critical","link":"/workflow/workflows"},{"label":"Completed this month","value":0,"status":"success","link":"/workflow/workflows"},{"label":"Templates available","value":0,"status":"info","link":"/workflow/templates"}],"tabs":[{"id":"active","label":"Active","labelAr":"نشط"},{"id":"templates","label":"Templates","labelAr":"القوالب"},{"id":"analytics","label":"Analytics","labelAr":"التحليلات"}],"statusTags":[{"label":"5 stalled","severity":"critical"}],"primaryAction":{"label":"New workflow","labelAr":"سير عمل جديد","route":"/workflow/designer","actionKey":"workflow.create","permission":"workflow.write"},"secondaryActions":[{"label":"View executions","labelAr":"عرض التنفيذات","route":"/workflow/executions","actionKey":"workflow.executions.view"},{"label":"Analytics","labelAr":"التحليلات","route":"/workflow/analytics","actionKey":"workflow.analytics.view"}],"nbaActions":[{"label":"Resolve stalled workflows","labelAr":"حل سير العمل المتوقف","route":"/workflow/workflows","severity":"critical","aiScore":92,"actionKey":"workflow.stalled.resolve","permission":"workflow.write","description":"5 workflows require owner decision to proceed"},{"label":"Review completion rates","labelAr":"مراجعة معدلات الاكتمال","route":"/workflow/analytics","severity":"info","aiScore":68,"actionKey":"workflow.analytics.review","permission":"workflow.read","description":"Cycle time increasing — bottleneck detected"}],"pillars":{"evidence":"Workflow execution engine, template library and analytics.","nextAction":{"label":"Resolve stalled workflows","labelAr":"حل سير العمل المتوقف","route":"/workflow/workflows","permission":"workflow.write"},"whatChanged":"Workflow throughput and bottleneck analysis updated.","whyItMatters":"Stalled workflows block downstream compliance deliverables.","riskOrOpportunity":"5 stalled workflows — risk of missed regulatory deadlines."}}'::jsonb),

('/workflow/hub',
 'Workflow hub','مركز سير العمل',
 'Central hub for all active, pending and completed workflows.','المركز الرئيسي لجميع سير العمل النشطة والمعلقة والمكتملة.',
 'Workflow','سير العمل',
 '{"eyebrow":"Workflow","title":"Workflow hub","subtitle":"Central hub for all active, pending and completed workflows.","aiHeadline":"Your workflow queue has 3 items requiring decision","loading":false,"heroKpi":{"label":"My queue","value":0,"delta":"","status":"info","aiInsight":"Items assigned to you awaiting decision"},"kpis":[{"label":"Active workflows","value":0,"status":"info","link":"/workflow/workflows"},{"label":"Overdue","value":0,"status":"critical","link":"/workflow/workflows"},{"label":"Completed this month","value":0,"status":"success","link":"/workflow/workflows"},{"label":"Templates","value":0,"status":"info","link":"/workflow/templates"}],"tabs":[{"id":"my-queue","label":"My queue","labelAr":"قائمتي"},{"id":"all-workflows","label":"All workflows","labelAr":"جميع سير العمل"},{"id":"templates","label":"Templates","labelAr":"القوالب"}],"statusTags":[{"label":"3 awaiting decision","severity":"warning"}],"primaryAction":{"label":"New workflow","labelAr":"سير عمل جديد","route":"/workflow/designer","actionKey":"workflow.create","permission":"workflow.write"},"secondaryActions":[{"label":"View all","labelAr":"عرض الكل","route":"/workflow/workflows","actionKey":"workflow.all.view"}],"nbaActions":[{"label":"Act on queued items","labelAr":"التصرف بناءً على العناصر المنتظرة","route":"/workflow/workflows","severity":"warning","aiScore":88,"actionKey":"workflow.queue.act","permission":"workflow.write","description":"3 items in your queue awaiting decision"}],"pillars":{"evidence":"Workflow execution and personal queue.","nextAction":{"label":"View my queue","labelAr":"عرض قائمتي","route":"/workflow/workflows"},"whatChanged":"Queue updated from workflow engine.","whyItMatters":"Unprocessed queue items delay downstream tasks.","riskOrOpportunity":"3 queued items — process to avoid workflow expiry."}}'::jsonb),

('/reporting',
 'Reporting','إعداد التقارير',
 'Generate, schedule and distribute governance and compliance reports.','إنشاء وجدولة وتوزيع تقارير الحوكمة والامتثال.',
 'Reporting','إعداد التقارير',
 '{"eyebrow":"Reporting","title":"Reporting","subtitle":"Generate, schedule and distribute governance and compliance reports.","aiHeadline":"Board pack due in 5 days — 2 sections incomplete","loading":false,"heroKpi":{"label":"Reports this month","value":0,"delta":"","status":"info","aiInsight":"Reports generated and distributed"},"kpis":[{"label":"Scheduled reports","value":0,"status":"info","link":"/reports/overview"},{"label":"Overdue","value":0,"status":"critical","link":"/reports/overview"},{"label":"Distributed","value":0,"status":"success","link":"/reports/overview"},{"label":"Draft","value":0,"status":"info","link":"/reports/overview"}],"tabs":[{"id":"reports","label":"Reports","labelAr":"التقارير"},{"id":"scheduled","label":"Scheduled","labelAr":"المجدولة"},{"id":"distributed","label":"Distributed","labelAr":"الموزعة"}],"statusTags":[{"label":"Board pack due soon","severity":"warning"}],"primaryAction":{"label":"Generate report","labelAr":"إنشاء تقرير","route":"/reports/overview","actionKey":"report.generate","permission":"reporting.write"},"secondaryActions":[],"nbaActions":[{"label":"Complete board pack sections","labelAr":"إتمام أقسام حزمة مجلس الإدارة","route":"/reports/overview","severity":"warning","aiScore":91,"actionKey":"report.board-pack.complete","permission":"reporting.write","description":"2 sections of the board pack are incomplete"}],"pillars":{"evidence":"Report generation, scheduling and distribution log.","nextAction":{"label":"Generate report","labelAr":"إنشاء تقرير","route":"/reports/overview","permission":"reporting.write"},"whatChanged":"Report queue and schedule updated.","whyItMatters":"Board-level reporting requires timely, accurate data.","riskOrOpportunity":"Board pack incomplete — governance obligation at risk."}}'::jsonb),

('/reports/overview',
 'Reports','التقارير',
 'Overview of all generated, scheduled and distributed governance reports.','نظرة عامة على جميع تقارير الحوكمة المُنشأة والمجدولة والموزعة.',
 'Reporting','إعداد التقارير',
 '{"eyebrow":"Reporting","title":"Reports","subtitle":"Overview of all generated, scheduled and distributed governance reports.","aiHeadline":"Report library contains 0 reports — start generating","loading":false,"heroKpi":{"label":"Reports generated","value":0,"delta":"","status":"info","aiInsight":"Total report artifacts in library"},"kpis":[{"label":"This month","value":0,"status":"info","link":"/reports/overview"},{"label":"Scheduled","value":0,"status":"info","link":"/reports/overview"},{"label":"Overdue","value":0,"status":"critical","link":"/reports/overview"},{"label":"Recipients","value":0,"status":"info","link":"/reports/overview"}],"tabs":[{"id":"all","label":"All reports","labelAr":"جميع التقارير"},{"id":"scheduled","label":"Scheduled","labelAr":"المجدولة"}],"statusTags":[],"primaryAction":{"label":"New report","labelAr":"تقرير جديد","route":"/reports/overview","actionKey":"report.create","permission":"reporting.write"},"secondaryActions":[],"nbaActions":[],"pillars":{"evidence":"Report generation and distribution log.","nextAction":{"label":"Create first report","labelAr":"إنشاء أول تقرير","route":"/reports/overview","permission":"reporting.write"},"whatChanged":"Report library initialized.","whyItMatters":"Reports provide board-level evidence of governance maturity.","riskOrOpportunity":"Empty report library — stakeholders lack governance visibility."}}'::jsonb),

('/dynamic-ui/overview',
 'Dynamic UI overview','نظرة عامة على واجهة المستخدم الديناميكية',
 'Component registry, route catalog and UI-OS contract status.','سجل المكونات وكتالوج المسارات وحالة عقود واجهة نظام التشغيل.',
 'Dynamic UI','واجهة ديناميكية',
 '{"eyebrow":"Dynamic UI","title":"Dynamic UI overview","subtitle":"Component registry, route catalog and UI-OS contract status.","aiHeadline":"202 routes bound — contract closure at 100%","loading":false,"heroKpi":{"label":"Route coverage","value":"100%","delta":"","status":"success","aiInsight":"All binding rows have dui_route rows"},"kpis":[{"label":"Registered components","value":0,"status":"info","link":"/dynamic-ui/components"},{"label":"Routes bound","value":0,"status":"success","link":"/dynamic-ui/routes"},{"label":"Contracts","value":0,"status":"info","link":"/dynamic-ui/contracts"},{"label":"Pending approval","value":0,"status":"warning","link":"/dynamic-ui/components"}],"tabs":[{"id":"components","label":"Components","labelAr":"المكونات"},{"id":"routes","label":"Routes","labelAr":"المسارات"},{"id":"contracts","label":"Contracts","labelAr":"العقود"}],"statusTags":[{"label":"100% bound","severity":"success"}],"primaryAction":{"label":"View components","labelAr":"عرض المكونات","route":"/dynamic-ui/components","actionKey":"dui.components.view","permission":"platform.admin.access"},"secondaryActions":[{"label":"Route catalog","labelAr":"كتالوج المسارات","route":"/dynamic-ui/routes","actionKey":"dui.routes.view"}],"nbaActions":[],"pillars":{"evidence":"Component registry, route metadata and contract catalog.","nextAction":{"label":"Audit component registry","labelAr":"تدقيق سجل المكونات","route":"/dynamic-ui/components"},"whatChanged":"Route binding completed — 202/202 routes wired.","whyItMatters":"Dynamic UI contract closure ensures zero blank-page navigation.","riskOrOpportunity":"All routes wired — no TEMPLATE_BINDING_NOT_FOUND risk."}}'::jsonb),

('/knowledge',
 'Knowledge','المعرفة',
 'Enterprise knowledge base, guidance articles and governance references.','قاعدة معرفة المؤسسة ومقالات الإرشاد ومراجع الحوكمة.',
 'Knowledge','المعرفة',
 '{"eyebrow":"Knowledge","title":"Knowledge","subtitle":"Enterprise knowledge base, guidance articles and governance references.","aiHeadline":"Knowledge base ready — 0 articles published","loading":false,"heroKpi":{"label":"Articles published","value":0,"delta":"","status":"info","aiInsight":"Published knowledge articles"},"kpis":[{"label":"Published","value":0,"status":"info"},{"label":"Draft","value":0,"status":"info"},{"label":"Recently updated","value":0,"status":"info"},{"label":"Categories","value":0,"status":"info"}],"tabs":[{"id":"articles","label":"Articles","labelAr":"المقالات"},{"id":"categories","label":"Categories","labelAr":"الفئات"}],"statusTags":[],"primaryAction":{"label":"New article","labelAr":"مقالة جديدة","route":"/knowledge","actionKey":"knowledge.create","permission":"knowledge.write"},"secondaryActions":[],"nbaActions":[],"pillars":{"evidence":"Knowledge base article catalog.","nextAction":{"label":"Create first article","labelAr":"إنشاء أول مقالة","route":"/knowledge","permission":"knowledge.write"},"whatChanged":"Knowledge base initialized.","whyItMatters":"Institutional knowledge reduces onboarding time and compliance errors.","riskOrOpportunity":"Empty knowledge base — staff rely on undocumented tribal knowledge."}}'::jsonb),

('/knowledge-hub',
 'Knowledge hub','مركز المعرفة',
 'Central hub for all enterprise knowledge, guidance and policy references.','المركز الرئيسي لجميع معارف المؤسسة والإرشادات ومراجع السياسات.',
 'Knowledge','المعرفة',
 '{"eyebrow":"Knowledge","title":"Knowledge hub","subtitle":"Central hub for all enterprise knowledge, guidance and policy references.","aiHeadline":"Knowledge hub ready","loading":false,"heroKpi":{"label":"Resources","value":0,"delta":"","status":"info","aiInsight":"Total knowledge resources available"},"kpis":[{"label":"Articles","value":0,"status":"info"},{"label":"Policies","value":0,"status":"info"},{"label":"Guidance notes","value":0,"status":"info"},{"label":"Recently added","value":0,"status":"info"}],"tabs":[{"id":"browse","label":"Browse","labelAr":"تصفح"},{"id":"recent","label":"Recent","labelAr":"الأحدث"}],"statusTags":[],"primaryAction":{"label":"Browse knowledge","labelAr":"تصفح المعرفة","route":"/knowledge","actionKey":"knowledge.browse","permission":"knowledge.read"},"secondaryActions":[],"nbaActions":[],"pillars":{"evidence":"Knowledge hub resource catalog.","nextAction":{"label":"Browse articles","labelAr":"تصفح المقالات","route":"/knowledge"},"whatChanged":"Knowledge hub initialized.","whyItMatters":"Accessible knowledge reduces time-to-decision for governance teams.","riskOrOpportunity":"Invest in knowledge base to reduce repeat compliance questions."}}'::jsonb),

('/policy/coverage',
 'Policy coverage','تغطية السياسات',
 'Track policy coverage against frameworks, obligations and organisational scope.','تتبع تغطية السياسات مقابل الأطر والالتزامات والنطاق التنظيمي.',
 'Policy','السياسات',
 '{"eyebrow":"Policy","title":"Policy coverage","subtitle":"Track policy coverage against frameworks, obligations and organisational scope.","aiHeadline":"Coverage gap detected in data protection domain","loading":false,"heroKpi":{"label":"Framework coverage","value":"--","delta":"","status":"info","aiInsight":"Policies mapped to applicable frameworks"},"kpis":[{"label":"Frameworks covered","value":0,"status":"info"},{"label":"Obligations mapped","value":0,"status":"info"},{"label":"Gaps","value":0,"status":"warning"},{"label":"Published policies","value":0,"status":"success"}],"tabs":[{"id":"coverage","label":"Coverage","labelAr":"التغطية"},{"id":"gaps","label":"Gaps","labelAr":"الثغرات"}],"statusTags":[{"label":"Coverage analysis active","severity":"info"}],"primaryAction":{"label":"Map policy","labelAr":"ربط السياسة","route":"/policy/library","actionKey":"policy.map","permission":"policy.write"},"secondaryActions":[],"nbaActions":[{"label":"Close coverage gaps","labelAr":"سد ثغرات التغطية","route":"/policy/library","severity":"warning","aiScore":82,"actionKey":"policy.coverage.close","permission":"policy.write","description":"Coverage gaps identified against applicable frameworks"}],"pillars":{"evidence":"Policy-to-framework mapping and coverage analytics.","nextAction":{"label":"Close gaps","labelAr":"سد الثغرات","route":"/policy/library","permission":"policy.write"},"whatChanged":"Coverage mapping updated after framework change.","whyItMatters":"Policy gaps leave the organisation without governing documents for key obligations.","riskOrOpportunity":"Coverage gaps create regulatory citation risk."}}'::jsonb),

('/policy/drafting',
 'Policy drafting','صياغة السياسات',
 'Collaborative policy authoring, review and approval workspace.','مساحة عمل تأليف ومراجعة واعتماد السياسات بشكل تعاوني.',
 'Policy','السياسات',
 '{"eyebrow":"Policy","title":"Policy drafting","subtitle":"Collaborative policy authoring, review and approval workspace.","aiHeadline":"3 drafts awaiting review","loading":false,"heroKpi":{"label":"Drafts in progress","value":0,"delta":"","status":"info","aiInsight":"Policies currently being authored"},"kpis":[{"label":"In draft","value":0,"status":"info"},{"label":"Awaiting review","value":0,"status":"warning"},{"label":"Awaiting approval","value":0,"status":"info"},{"label":"Returned","value":0,"status":"critical"}],"tabs":[{"id":"my-drafts","label":"My drafts","labelAr":"مسوداتي"},{"id":"in-review","label":"In review","labelAr":"قيد المراجعة"},{"id":"approval","label":"Approval","labelAr":"الاعتماد"}],"statusTags":[{"label":"3 awaiting review","severity":"warning"}],"primaryAction":{"label":"New draft","labelAr":"مسودة جديدة","route":"/policy/drafting","actionKey":"policy.draft.create","permission":"policy.write"},"secondaryActions":[],"nbaActions":[{"label":"Review submitted drafts","labelAr":"مراجعة المسودات المقدمة","route":"/policy/drafting","severity":"warning","aiScore":85,"actionKey":"policy.draft.review","permission":"policy.review","description":"3 drafts are awaiting reviewer action"}],"pillars":{"evidence":"Policy draft registry and review workflow.","nextAction":{"label":"Review drafts","labelAr":"مراجعة المسودات","route":"/policy/drafting","permission":"policy.review"},"whatChanged":"Draft queue updated.","whyItMatters":"Delayed policy reviews stall publication and leave gaps in coverage.","riskOrOpportunity":"3 drafts stalled in review — publication timeline at risk."}}'::jsonb),

('/policy/home',
 'Policy','السياسات',
 'Author, publish and track the lifecycle of governance and compliance policies.','إعداد ونشر وتتبع دورة حياة سياسات الحوكمة والامتثال.',
 'Policy','السياسات',
 '{"eyebrow":"Policy","title":"Policy","subtitle":"Author, publish and track the lifecycle of governance and compliance policies.","aiHeadline":"4 policies due for annual review","loading":false,"heroKpi":{"label":"Published policies","value":0,"delta":"","status":"info","aiInsight":"Active policies in force"},"kpis":[{"label":"Published","value":0,"status":"success","link":"/policy/library"},{"label":"Under review","value":0,"status":"info","link":"/policy/library"},{"label":"Overdue review","value":0,"status":"warning","link":"/policy/library"},{"label":"Drafts","value":0,"status":"info","link":"/policy/drafting"}],"tabs":[{"id":"library","label":"Library","labelAr":"المكتبة"},{"id":"drafting","label":"Drafting","labelAr":"الصياغة"},{"id":"lifecycle","label":"Lifecycle","labelAr":"دورة الحياة"}],"statusTags":[{"label":"4 due for review","severity":"warning"}],"primaryAction":{"label":"New policy","labelAr":"سياسة جديدة","route":"/policy/library","actionKey":"policy.create","permission":"policy.write"},"secondaryActions":[],"nbaActions":[{"label":"Review overdue policies","labelAr":"مراجعة السياسات المتأخرة","route":"/policy/library","severity":"warning","aiScore":85,"actionKey":"policy.review.overdue","permission":"policy.write","description":"4 policies past annual review date"}],"pillars":{"evidence":"Policy library and lifecycle tracker.","nextAction":{"label":"Review policies","labelAr":"مراجعة السياسات","route":"/policy/library","permission":"policy.write"},"whatChanged":"Policy lifecycle status recalculated.","whyItMatters":"Outdated policies create compliance gaps.","riskOrOpportunity":"4 overdue reviews — regulatory citation risk."}}'::jsonb),

('/policy/lifecycle',
 'Policy lifecycle','دورة حياة السياسات',
 'Full visibility into the policy authoring, approval and retirement lifecycle.','رؤية كاملة لدورة حياة تأليف السياسات واعتمادها وإتقاعدها.',
 'Policy','السياسات',
 '{"eyebrow":"Policy","title":"Policy lifecycle","subtitle":"Full visibility into the policy authoring, approval and retirement lifecycle.","aiHeadline":"Lifecycle analytics ready","loading":false,"heroKpi":{"label":"Active policies","value":0,"delta":"","status":"info","aiInsight":"Policies in published or review state"},"kpis":[{"label":"Draft","value":0,"status":"info"},{"label":"In review","value":0,"status":"info"},{"label":"Published","value":0,"status":"success"},{"label":"Retired","value":0,"status":"info"}],"tabs":[{"id":"timeline","label":"Timeline","labelAr":"الجدول الزمني"},{"id":"status","label":"Status","labelAr":"الحالة"}],"statusTags":[],"primaryAction":{"label":"View library","labelAr":"عرض المكتبة","route":"/policy/library","actionKey":"policy.library.view"},"secondaryActions":[],"nbaActions":[],"pillars":{"evidence":"Policy lifecycle stage data.","nextAction":{"label":"View policy library","labelAr":"عرض مكتبة السياسات","route":"/policy/library"},"whatChanged":"Lifecycle stages updated.","whyItMatters":"Full lifecycle visibility prevents orphaned or outdated policies.","riskOrOpportunity":"Track all policies through to retirement to avoid zombie policies."}}'::jsonb),

('/policy/publications',
 'Policy publications','نشر السياسات',
 'Published policy distribution, acknowledgement tracking and version history.','توزيع السياسات المنشورة وتتبع الإقرارات وتاريخ الإصدارات.',
 'Policy','السياسات',
 '{"eyebrow":"Policy","title":"Policy publications","subtitle":"Published policy distribution, acknowledgement tracking and version history.","aiHeadline":"12 acknowledgements pending from staff","loading":false,"heroKpi":{"label":"Acknowledgement rate","value":"--","delta":"","status":"warning","aiInsight":"Staff acknowledgement completion rate"},"kpis":[{"label":"Published versions","value":0,"status":"info"},{"label":"Recipients","value":0,"status":"info"},{"label":"Acknowledged","value":0,"status":"success"},{"label":"Pending","value":0,"status":"warning"}],"tabs":[{"id":"publications","label":"Publications","labelAr":"المنشورات"},{"id":"acknowledgements","label":"Acknowledgements","labelAr":"الإقرارات"}],"statusTags":[{"label":"12 pending acks","severity":"warning"}],"primaryAction":{"label":"Chase acknowledgements","labelAr":"متابعة الإقرارات","route":"/policy/publications","actionKey":"policy.ack.chase","permission":"policy.read"},"secondaryActions":[],"nbaActions":[{"label":"Send acknowledgement reminder","labelAr":"إرسال تذكير بالإقرار","route":"/policy/publications","severity":"warning","aiScore":80,"actionKey":"policy.ack.remind","permission":"policy.write","description":"12 staff have not acknowledged current policies"}],"pillars":{"evidence":"Policy publication and acknowledgement tracking system.","nextAction":{"label":"Chase acknowledgements","labelAr":"متابعة الإقرارات","route":"/policy/publications","permission":"policy.write"},"whatChanged":"Acknowledgement status updated.","whyItMatters":"Unacknowledged policies cannot be enforced in disciplinary proceedings.","riskOrOpportunity":"12 pending acknowledgements — enforceability risk."}}'::jsonb)

) AS v(route,ten,tar,sen,sar,een,ear,p)
WHERE dos.ui_route_template_binding.route = v.route;

-- Final validation: check all command-home rows now have rich props (>4 keys)
DO $$
DECLARE still_minimal integer;
BEGIN
  SELECT COUNT(*) INTO still_minimal
  FROM dos.ui_route_template_binding
  WHERE (archetype = 'command-home' OR template_export = 'module.overview.page')
    AND (SELECT COUNT(*) FROM jsonb_object_keys(props)) <= 3;
  IF still_minimal > 0 THEN
    RAISE WARNING '20260507_2200: % command-home rows still have minimal props (<=3 keys)', still_minimal;
  ELSE
    RAISE NOTICE '20260507_2200 PASS: all command-home/overview rows have enterprise props';
  END IF;
END $$;
COMMIT;
