import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const AUDIT_ERROR_CODES = {
  FINDINGS_NOT_FOUND: { code: 'AUDIT.FINDINGS_NOT_FOUND', httpStatus: 404, messageEn: 'Findings not found', messageAr: 'Findings غير موجود' },
  FINDINGS_ALREADY_EXISTS: { code: 'AUDIT.FINDINGS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Findings already exists', messageAr: 'Findings موجود بالفعل' },
  FINDINGS_VALIDATION_FAILED: { code: 'AUDIT.FINDINGS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Findings validation failed', messageAr: 'فشل التحقق من Findings' },
  TIMELINE_NOT_FOUND: { code: 'AUDIT.TIMELINE_NOT_FOUND', httpStatus: 404, messageEn: 'Timeline not found', messageAr: 'Timeline غير موجود' },
  TIMELINE_ALREADY_EXISTS: { code: 'AUDIT.TIMELINE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Timeline already exists', messageAr: 'Timeline موجود بالفعل' },
  TIMELINE_VALIDATION_FAILED: { code: 'AUDIT.TIMELINE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Timeline validation failed', messageAr: 'فشل التحقق من Timeline' },
  CAPA_NOT_FOUND: { code: 'AUDIT.CAPA_NOT_FOUND', httpStatus: 404, messageEn: 'Capa not found', messageAr: 'Capa غير موجود' },
  CAPA_ALREADY_EXISTS: { code: 'AUDIT.CAPA_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Capa already exists', messageAr: 'Capa موجود بالفعل' },
  CAPA_VALIDATION_FAILED: { code: 'AUDIT.CAPA_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Capa validation failed', messageAr: 'فشل التحقق من Capa' },
  RATE_NOT_FOUND: { code: 'AUDIT.RATE_NOT_FOUND', httpStatus: 404, messageEn: 'Rate not found', messageAr: 'Rate غير موجود' },
  RATE_ALREADY_EXISTS: { code: 'AUDIT.RATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Rate already exists', messageAr: 'Rate موجود بالفعل' },
  RATE_VALIDATION_FAILED: { code: 'AUDIT.RATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Rate validation failed', messageAr: 'فشل التحقق من Rate' },
  EXECUTIVE_SUMMARY_NOT_FOUND: { code: 'AUDIT.EXECUTIVE_SUMMARY_NOT_FOUND', httpStatus: 404, messageEn: 'Executive Summary not found', messageAr: 'Executive Summary غير موجود' },
  EXECUTIVE_SUMMARY_ALREADY_EXISTS: { code: 'AUDIT.EXECUTIVE_SUMMARY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Executive Summary already exists', messageAr: 'Executive Summary موجود بالفعل' },
  EXECUTIVE_SUMMARY_VALIDATION_FAILED: { code: 'AUDIT.EXECUTIVE_SUMMARY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Executive Summary validation failed', messageAr: 'فشل التحقق من Executive Summary' },
  METRICS_NOT_FOUND: { code: 'AUDIT.METRICS_NOT_FOUND', httpStatus: 404, messageEn: 'Metrics not found', messageAr: 'Metrics غير موجود' },
  METRICS_ALREADY_EXISTS: { code: 'AUDIT.METRICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Metrics already exists', messageAr: 'Metrics موجود بالفعل' },
  METRICS_VALIDATION_FAILED: { code: 'AUDIT.METRICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Metrics validation failed', messageAr: 'فشل التحقق من Metrics' },
  BOARD_DASHBOARD_NOT_FOUND: { code: 'AUDIT.BOARD_DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Board Dashboard not found', messageAr: 'Board Dashboard غير موجود' },
  BOARD_DASHBOARD_ALREADY_EXISTS: { code: 'AUDIT.BOARD_DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Board Dashboard already exists', messageAr: 'Board Dashboard موجود بالفعل' },
  BOARD_DASHBOARD_VALIDATION_FAILED: { code: 'AUDIT.BOARD_DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Board Dashboard validation failed', messageAr: 'فشل التحقق من Board Dashboard' },
  SYNC_TO_RISK_NOT_FOUND: { code: 'AUDIT.SYNC_TO_RISK_NOT_FOUND', httpStatus: 404, messageEn: 'Sync To Risk not found', messageAr: 'Sync To Risk غير موجود' },
  SYNC_TO_RISK_ALREADY_EXISTS: { code: 'AUDIT.SYNC_TO_RISK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Sync To Risk already exists', messageAr: 'Sync To Risk موجود بالفعل' },
  SYNC_TO_RISK_VALIDATION_FAILED: { code: 'AUDIT.SYNC_TO_RISK_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Sync To Risk validation failed', messageAr: 'فشل التحقق من Sync To Risk' },
  LINK_COMPLIANCE_NOT_FOUND: { code: 'AUDIT.LINK_COMPLIANCE_NOT_FOUND', httpStatus: 404, messageEn: 'Link Compliance not found', messageAr: 'Link Compliance غير موجود' },
  LINK_COMPLIANCE_ALREADY_EXISTS: { code: 'AUDIT.LINK_COMPLIANCE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Link Compliance already exists', messageAr: 'Link Compliance موجود بالفعل' },
  LINK_COMPLIANCE_VALIDATION_FAILED: { code: 'AUDIT.LINK_COMPLIANCE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Link Compliance validation failed', messageAr: 'فشل التحقق من Link Compliance' },
  STATUS_NOT_FOUND: { code: 'AUDIT.STATUS_NOT_FOUND', httpStatus: 404, messageEn: 'Status not found', messageAr: 'Status غير موجود' },
  STATUS_ALREADY_EXISTS: { code: 'AUDIT.STATUS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Status already exists', messageAr: 'Status موجود بالفعل' },
  STATUS_VALIDATION_FAILED: { code: 'AUDIT.STATUS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Status validation failed', messageAr: 'فشل التحقق من Status' },
  AUDIT_NOT_FOUND: { code: 'AUDIT.AUDIT_NOT_FOUND', httpStatus: 404, messageEn: 'Audit not found', messageAr: 'Audit غير موجود' },
  AUDIT_ALREADY_EXISTS: { code: 'AUDIT.AUDIT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Audit already exists', messageAr: 'Audit موجود بالفعل' },
  AUDIT_VALIDATION_FAILED: { code: 'AUDIT.AUDIT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Audit validation failed', messageAr: 'فشل التحقق من Audit' },
  PENDING_NOT_FOUND: { code: 'AUDIT.PENDING_NOT_FOUND', httpStatus: 404, messageEn: 'Pending not found', messageAr: 'Pending غير موجود' },
  PENDING_ALREADY_EXISTS: { code: 'AUDIT.PENDING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Pending already exists', messageAr: 'Pending موجود بالفعل' },
  PENDING_VALIDATION_FAILED: { code: 'AUDIT.PENDING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Pending validation failed', messageAr: 'فشل التحقق من Pending' },
  OVERDUE_NOT_FOUND: { code: 'AUDIT.OVERDUE_NOT_FOUND', httpStatus: 404, messageEn: 'Overdue not found', messageAr: 'Overdue غير موجود' },
  OVERDUE_ALREADY_EXISTS: { code: 'AUDIT.OVERDUE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overdue already exists', messageAr: 'Overdue موجود بالفعل' },
  OVERDUE_VALIDATION_FAILED: { code: 'AUDIT.OVERDUE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overdue validation failed', messageAr: 'فشل التحقق من Overdue' },
  CONFIG_NOT_FOUND: { code: 'AUDIT.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'AUDIT.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'AUDIT.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'AUDIT.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'AUDIT.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'AUDIT.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },

  UNAUTHORIZED: { code: 'AUDIT.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for audit operation', messageAr: 'صلاحيات غير كافية لعملية audit' },
  INVALID_STATE_TRANSITION: { code: 'AUDIT.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'AUDIT.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'AUDIT.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'AUDIT.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'AUDIT.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type AuditErrorCode = keyof typeof AUDIT_ERROR_CODES;
