-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=compliance scope=tenant function=obligations
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/compliance/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (4):
--   * assessments
--   * entities
--   * obligations
--   * sod_conflict_matrix
--
-- Source migrations (immutable, 1):
--   * modules/compliance/db/tenant/migrations/000_extracted_from_000_inline_baseline.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.obligations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  description TEXT,
  framework_id UUID,
  status TEXT DEFAULT 'active',
  assigned_to UUID,
  owner_user_id UUID,
  tenant_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.sod_conflict_matrix (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role_a TEXT,
  role_b TEXT,
  conflict_type TEXT,
  severity TEXT,
  tenant_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.entities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  entity_type TEXT DEFAULT 'subsidiary',
  status TEXT DEFAULT 'active',
  tenant_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assessment_id TEXT,
  title TEXT,
  framework_id TEXT,
  status TEXT DEFAULT 'draft',
  score NUMERIC DEFAULT 0,
  created_by TEXT DEFAULT 'system',
  tenant_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(assessment_id)
);
