import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const INBOX_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'INBOX.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'INBOX.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'INBOX.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'INBOX.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'INBOX.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'INBOX.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'INBOX.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'INBOX.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'INBOX.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  REINDEX_NOT_FOUND: { code: 'INBOX.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'INBOX.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'INBOX.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  ANALYTICS_NOT_FOUND: { code: 'INBOX.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'INBOX.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'INBOX.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  MAINTENANCE_NOT_FOUND: { code: 'INBOX.MAINTENANCE_NOT_FOUND', httpStatus: 404, messageEn: 'Maintenance not found', messageAr: 'Maintenance غير موجود' },
  MAINTENANCE_ALREADY_EXISTS: { code: 'INBOX.MAINTENANCE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maintenance already exists', messageAr: 'Maintenance موجود بالفعل' },
  MAINTENANCE_VALIDATION_FAILED: { code: 'INBOX.MAINTENANCE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maintenance validation failed', messageAr: 'فشل التحقق من Maintenance' },
  ROUTING_RULES_NOT_FOUND: { code: 'INBOX.ROUTING_RULES_NOT_FOUND', httpStatus: 404, messageEn: 'Routing Rules not found', messageAr: 'Routing Rules غير موجود' },
  ROUTING_RULES_ALREADY_EXISTS: { code: 'INBOX.ROUTING_RULES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Routing Rules already exists', messageAr: 'Routing Rules موجود بالفعل' },
  ROUTING_RULES_VALIDATION_FAILED: { code: 'INBOX.ROUTING_RULES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Routing Rules validation failed', messageAr: 'فشل التحقق من Routing Rules' },
  BROADCASTS_NOT_FOUND: { code: 'INBOX.BROADCASTS_NOT_FOUND', httpStatus: 404, messageEn: 'Broadcasts not found', messageAr: 'Broadcasts غير موجود' },
  BROADCASTS_ALREADY_EXISTS: { code: 'INBOX.BROADCASTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Broadcasts already exists', messageAr: 'Broadcasts موجود بالفعل' },
  BROADCASTS_VALIDATION_FAILED: { code: 'INBOX.BROADCASTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Broadcasts validation failed', messageAr: 'فشل التحقق من Broadcasts' },
  DIGESTS_NOT_FOUND: { code: 'INBOX.DIGESTS_NOT_FOUND', httpStatus: 404, messageEn: 'Digests not found', messageAr: 'Digests غير موجود' },
  DIGESTS_ALREADY_EXISTS: { code: 'INBOX.DIGESTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Digests already exists', messageAr: 'Digests موجود بالفعل' },
  DIGESTS_VALIDATION_FAILED: { code: 'INBOX.DIGESTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Digests validation failed', messageAr: 'فشل التحقق من Digests' },
  DIAGNOSTICS_NOT_FOUND: { code: 'INBOX.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'INBOX.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'INBOX.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  SEARCH_NOT_FOUND: { code: 'INBOX.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'INBOX.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'INBOX.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  UNREAD_COUNT_NOT_FOUND: { code: 'INBOX.UNREAD_COUNT_NOT_FOUND', httpStatus: 404, messageEn: 'Unread Count not found', messageAr: 'Unread Count غير موجود' },
  UNREAD_COUNT_ALREADY_EXISTS: { code: 'INBOX.UNREAD_COUNT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Unread Count already exists', messageAr: 'Unread Count موجود بالفعل' },
  UNREAD_COUNT_VALIDATION_FAILED: { code: 'INBOX.UNREAD_COUNT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Unread Count validation failed', messageAr: 'فشل التحقق من Unread Count' },
  PRIORITY_QUEUE_NOT_FOUND: { code: 'INBOX.PRIORITY_QUEUE_NOT_FOUND', httpStatus: 404, messageEn: 'Priority Queue not found', messageAr: 'Priority Queue غير موجود' },
  PRIORITY_QUEUE_ALREADY_EXISTS: { code: 'INBOX.PRIORITY_QUEUE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Priority Queue already exists', messageAr: 'Priority Queue موجود بالفعل' },
  PRIORITY_QUEUE_VALIDATION_FAILED: { code: 'INBOX.PRIORITY_QUEUE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Priority Queue validation failed', messageAr: 'فشل التحقق من Priority Queue' },
  THREAD_NOT_FOUND: { code: 'INBOX.THREAD_NOT_FOUND', httpStatus: 404, messageEn: 'Thread not found', messageAr: 'Thread غير موجود' },
  THREAD_ALREADY_EXISTS: { code: 'INBOX.THREAD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Thread already exists', messageAr: 'Thread موجود بالفعل' },
  THREAD_VALIDATION_FAILED: { code: 'INBOX.THREAD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Thread validation failed', messageAr: 'فشل التحقق من Thread' },
  DIGEST_NOT_FOUND: { code: 'INBOX.DIGEST_NOT_FOUND', httpStatus: 404, messageEn: 'Digest not found', messageAr: 'Digest غير موجود' },
  DIGEST_ALREADY_EXISTS: { code: 'INBOX.DIGEST_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Digest already exists', messageAr: 'Digest موجود بالفعل' },
  DIGEST_VALIDATION_FAILED: { code: 'INBOX.DIGEST_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Digest validation failed', messageAr: 'فشل التحقق من Digest' },

  UNAUTHORIZED: { code: 'INBOX.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for inbox operation', messageAr: 'صلاحيات غير كافية لعملية inbox' },
  INVALID_STATE_TRANSITION: { code: 'INBOX.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'INBOX.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'INBOX.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'INBOX.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'INBOX.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type InboxErrorCode = keyof typeof INBOX_ERROR_CODES;
