export const SYSTEM_JOB_ACTOR = 'SYSTEM_JOB';
export const SYSTEM_SEEDER_ACTOR = 'SYSTEM_SEEDER';
export const SYSTEM_WEBHOOK_ACTOR = 'SYSTEM_WEBHOOK';
export const SYSTEM_EVENT_PROPAGATOR_ACTOR = 'SYSTEM_EVENT_PROPAGATION';
export const SYSTEM_INVITATION_ACTOR = 'SYSTEM_INVITATION';
export const SYSTEM_TENANT = '00000000-0000-4000-8000-000000000000';
