"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SYSTEM_TENANT = exports.SYSTEM_INVITATION_ACTOR = exports.SYSTEM_EVENT_PROPAGATOR_ACTOR = exports.SYSTEM_WEBHOOK_ACTOR = exports.SYSTEM_SEEDER_ACTOR = exports.SYSTEM_JOB_ACTOR = void 0;
exports.SYSTEM_JOB_ACTOR = 'SYSTEM_JOB';
exports.SYSTEM_SEEDER_ACTOR = 'SYSTEM_SEEDER';
exports.SYSTEM_WEBHOOK_ACTOR = 'SYSTEM_WEBHOOK';
exports.SYSTEM_EVENT_PROPAGATOR_ACTOR = 'SYSTEM_EVENT_PROPAGATION';
exports.SYSTEM_INVITATION_ACTOR = 'SYSTEM_INVITATION';
exports.SYSTEM_TENANT = '00000000-0000-4000-8000-000000000000';
//# sourceMappingURL=index.js.map