import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const EXCEPTION_ERROR_CODES = {
  OVERVIEW_NOT_FOUND: { code: 'EXCEPTION.OVERVIEW_NOT_FOUND', httpStatus: 404, messageEn: 'Overview not found', messageAr: 'Overview غير موجود' },
  OVERVIEW_ALREADY_EXISTS: { code: 'EXCEPTION.OVERVIEW_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overview already exists', messageAr: 'Overview موجود بالفعل' },
  OVERVIEW_VALIDATION_FAILED: { code: 'EXCEPTION.OVERVIEW_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overview validation failed', messageAr: 'فشل التحقق من Overview' },
  STATS_NOT_FOUND: { code: 'EXCEPTION.STATS_NOT_FOUND', httpStatus: 404, messageEn: 'Stats not found', messageAr: 'Stats غير موجود' },
  STATS_ALREADY_EXISTS: { code: 'EXCEPTION.STATS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Stats already exists', messageAr: 'Stats موجود بالفعل' },
  STATS_VALIDATION_FAILED: { code: 'EXCEPTION.STATS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Stats validation failed', messageAr: 'فشل التحقق من Stats' },
  SETTINGS_NOT_FOUND: { code: 'EXCEPTION.SETTINGS_NOT_FOUND', httpStatus: 404, messageEn: 'Settings not found', messageAr: 'Settings غير موجود' },
  SETTINGS_ALREADY_EXISTS: { code: 'EXCEPTION.SETTINGS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Settings already exists', messageAr: 'Settings موجود بالفعل' },
  SETTINGS_VALIDATION_FAILED: { code: 'EXCEPTION.SETTINGS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Settings validation failed', messageAr: 'فشل التحقق من Settings' },
  CONFIG_NOT_FOUND: { code: 'EXCEPTION.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'EXCEPTION.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'EXCEPTION.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'EXCEPTION.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'EXCEPTION.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'EXCEPTION.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'EXCEPTION.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'EXCEPTION.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'EXCEPTION.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  EXPIRY_OVERVIEW_NOT_FOUND: { code: 'EXCEPTION.EXPIRY_OVERVIEW_NOT_FOUND', httpStatus: 404, messageEn: 'Expiry Overview not found', messageAr: 'Expiry Overview غير موجود' },
  EXPIRY_OVERVIEW_ALREADY_EXISTS: { code: 'EXCEPTION.EXPIRY_OVERVIEW_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Expiry Overview already exists', messageAr: 'Expiry Overview موجود بالفعل' },
  EXPIRY_OVERVIEW_VALIDATION_FAILED: { code: 'EXCEPTION.EXPIRY_OVERVIEW_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Expiry Overview validation failed', messageAr: 'فشل التحقق من Expiry Overview' },
  RISK_BREAKDOWN_NOT_FOUND: { code: 'EXCEPTION.RISK_BREAKDOWN_NOT_FOUND', httpStatus: 404, messageEn: 'Risk Breakdown not found', messageAr: 'Risk Breakdown غير موجود' },
  RISK_BREAKDOWN_ALREADY_EXISTS: { code: 'EXCEPTION.RISK_BREAKDOWN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Risk Breakdown already exists', messageAr: 'Risk Breakdown موجود بالفعل' },
  RISK_BREAKDOWN_VALIDATION_FAILED: { code: 'EXCEPTION.RISK_BREAKDOWN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Risk Breakdown validation failed', messageAr: 'فشل التحقق من Risk Breakdown' },
  REINDEX_NOT_FOUND: { code: 'EXCEPTION.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'EXCEPTION.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'EXCEPTION.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'EXCEPTION.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'EXCEPTION.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'EXCEPTION.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'EXCEPTION.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'EXCEPTION.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'EXCEPTION.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  EXPIRING_NOT_FOUND: { code: 'EXCEPTION.EXPIRING_NOT_FOUND', httpStatus: 404, messageEn: 'Expiring not found', messageAr: 'Expiring غير موجود' },
  EXPIRING_ALREADY_EXISTS: { code: 'EXCEPTION.EXPIRING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Expiring already exists', messageAr: 'Expiring موجود بالفعل' },
  EXPIRING_VALIDATION_FAILED: { code: 'EXCEPTION.EXPIRING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Expiring validation failed', messageAr: 'فشل التحقق من Expiring' },
  SEARCH_NOT_FOUND: { code: 'EXCEPTION.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'EXCEPTION.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'EXCEPTION.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  DASHBOARD_NOT_FOUND: { code: 'EXCEPTION.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'EXCEPTION.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'EXCEPTION.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  TRENDS_NOT_FOUND: { code: 'EXCEPTION.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'EXCEPTION.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'EXCEPTION.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },

  UNAUTHORIZED: { code: 'EXCEPTION.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for exception operation', messageAr: 'صلاحيات غير كافية لعملية exception' },
  INVALID_STATE_TRANSITION: { code: 'EXCEPTION.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'EXCEPTION.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'EXCEPTION.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'EXCEPTION.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'EXCEPTION.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type ExceptionErrorCode = keyof typeof EXCEPTION_ERROR_CODES;
