// ============================================================================
// Shahin — Report Renderer Service
// Renders report JSON data as PDF (pdfkit) or Excel (exceljs).
// Supports bilingual EN/AR with RTL layout for Arabic.
// ============================================================================

import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
import { safeQuery } from "@dos/db";

export interface ReportData {
  templateKey: string;
  title: string;
  generatedAt: string;
  tenantId: string;
  language?: "en" | "ar";
  parameters?: Record<string, unknown>;
  sections: ReportSection[];
}

export interface ReportSection {
  title: string;
  description?: string;
  data?: Record<string, unknown>;
  table?: { headers: string[]; rows: (string | number)[][] };
  items?: { label: string; value: string | number }[];
}

// ── PDF Rendering ──

export async function renderReportAsPDF(reportData: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 50, right: 50 },
      info: {
        Title: reportData.title,
        Author: "Shahin-Ai Platform",
        Subject: reportData.templateKey,
        CreationDate: new Date(reportData.generatedAt),
      },
    });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const isRtl = reportData.language === "ar";

    // ── Cover Page ──
    doc.fontSize(28).font("Helvetica-Bold");
    doc.moveDown(6);
    doc.text(reportData.title, { align: "center" });
    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica");
    doc.text(`Generated: ${new Date(reportData.generatedAt).toLocaleDateString()}`, { align: "center" });
    doc.moveDown(0.5);
    doc.text(`Tenant: ${reportData.tenantId}`, { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666666");
    doc.text("Shahin-Ai Platform — Confidential", { align: "center" });
    doc.fillColor("#000000");

    // ── Table of Contents ──
    doc.addPage();
    doc.fontSize(18).font("Helvetica-Bold");
    doc.text("Table of Contents", { align: isRtl ? "right" : "left" });
    doc.moveDown(1);
    doc.fontSize(12).font("Helvetica");
    reportData.sections.forEach((section, i) => {
      doc.text(`${i + 1}. ${section.title}`, { align: isRtl ? "right" : "left" });
      doc.moveDown(0.3);
    });

    // ── Sections ──
    for (const section of reportData.sections) {
      doc.addPage();
      doc.fontSize(16).font("Helvetica-Bold");
      doc.text(section.title, { align: isRtl ? "right" : "left" });
      doc.moveDown(0.5);

      if (section.description) {
        doc.fontSize(10).font("Helvetica").fillColor("#444444");
        doc.text(section.description, { align: isRtl ? "right" : "left" });
        doc.fillColor("#000000");
        doc.moveDown(0.5);
      }

      // Key-value items
      if (section.items && section.items.length > 0) {
        doc.fontSize(10).font("Helvetica");
        for (const item of section.items) {
          doc.font("Helvetica-Bold").text(`${item.label}: `, { continued: true });
          doc.font("Helvetica").text(String(item.value));
          doc.moveDown(0.2);
        }
        doc.moveDown(0.5);
      }

      // Table rendering
      if (section.table && section.table.headers.length > 0) {
        renderPDFTable(doc, section.table);
      }

      // Raw data dump
      if (section.data && !section.table && !section.items) {
        doc.fontSize(9).font("Courier");
        doc.text(JSON.stringify(section.data, null, 2), { align: "left" });
        doc.font("Helvetica");
      }
    }

    // ── Footer ──
    doc.fontSize(8).fillColor("#999999");
    doc.text(
      `Report generated by Shahin-Ai Platform on ${new Date().toISOString()}`,
      50,
      doc.page.height - 40,
      { align: "center", width: doc.page.width - 100 }
    );

    doc.end();
  });
}

function renderPDFTable(
  doc: any,
  table: { headers: string[]; rows: (string | number)[][] }
): void {
  const colCount = table.headers.length;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colWidth = Math.floor(pageWidth / colCount);
  const startX = doc.page.margins.left;

  let y = (doc as Record<string, unknown>).y;

  // Header row
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#ffffff");
  doc.rect(startX, (y as any), pageWidth, 20).fill("#2c3e50");
  doc.fillColor("#ffffff");
  table.headers.forEach((h, i) => {
    doc.text(h, startX + i * colWidth + 4, (y as any) + 5, { width: colWidth - 8, align: "left" });
  });
  (y as any) += 20;

  // Data rows
  doc.fontSize(8).font("Helvetica").fillColor("#000000");
  for (let r = 0; r < Math.min(table.rows.length, 50); r++) {
    if ((y as any) > doc.page.height - 80) {
      doc.addPage();
      y = doc.page.margins.top;
    }
    const bgColor = r % 2 === 0 ? "#f9f9f9" : "#ffffff";
    doc.rect(startX, (y as any), pageWidth, 18).fill(bgColor);
    doc.fillColor("#000000");
    table.rows[r].forEach((cell, i) => {
      doc.text(String(cell), startX + i * colWidth + 4, (y as any) + 4, {
        width: colWidth - 8,
        align: "left",
        lineBreak: false,
      });
    });
    (y as any) += 18;
  }

  if (table.rows.length > 50) {
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor("#999999");
    doc.text(`... and ${table.rows.length - 50} more rows`);
    doc.fillColor("#000000");
  }

  (doc as Record<string, unknown>).y = (y as any) + 10;
}

// ── Excel Rendering ──

export async function renderReportAsExcel(reportData: ReportData): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Shahin-Ai Platform";
  workbook.created = new Date(reportData.generatedAt);

  // Summary sheet
  const summarySheet = workbook.addWorksheet("Summary");
  summarySheet.columns = [
    { header: "Property", key: "property", width: 30 },
    { header: "Value", key: "value", width: 50 },
  ];
  summarySheet.addRow({ property: "Report", value: reportData.title });
  summarySheet.addRow({ property: "Template", value: reportData.templateKey });
  summarySheet.addRow({ property: "Generated", value: reportData.generatedAt });
  summarySheet.addRow({ property: "Tenant", value: reportData.tenantId });
  summarySheet.addRow({ property: "Sections", value: reportData.sections.length });

  // Style header row
  const headerFill: ExcelJS.FillPattern = { type: "pattern", pattern: "solid", fgColor: { argb: "FF2C3E50" } };
  const headerFont: Partial<ExcelJS.Font> = { bold: true, color: { argb: "FFFFFFFF" } };
  summarySheet.getRow(1).eachCell((cell) => {
    cell.fill = headerFill;
    cell.font = headerFont;
  });

  // Section sheets
  for (let i = 0; i < reportData.sections.length; i++) {
    const section = reportData.sections[i];
    const sheetName = `${i + 1}. ${section.title}`.substring(0, 31); // Excel 31-char limit
    const sheet = workbook.addWorksheet(sheetName);

    if (section.table && section.table.headers.length > 0) {
      // Table data
      sheet.columns = section.table.headers.map((h) => ({
        header: h,
        key: h.toLowerCase().replace(/\s+/g, "_"),
        width: 20,
      }));

      for (const row of section.table.rows) {
        const rowData: Record<string, unknown> = {};
        section.table.headers.forEach((h, j) => {
          rowData[h.toLowerCase().replace(/\s+/g, "_")] = row[j];
        });
        sheet.addRow(rowData);
      }

      // Style header
      sheet.getRow(1).eachCell((cell) => {
        cell.fill = headerFill;
        cell.font = headerFont;
      });
    } else if (section.items && section.items.length > 0) {
      // Key-value items
      sheet.columns = [
        { header: "Label", key: "label", width: 30 },
        { header: "Value", key: "value", width: 50 },
      ];
      for (const item of section.items) {
        sheet.addRow({ label: item.label, value: item.value });
      }
      sheet.getRow(1).eachCell((cell) => {
        cell.fill = headerFill;
        cell.font = headerFont;
      });
    } else if (section.data) {
      // Raw data as JSON
      sheet.columns = [
        { header: "Key", key: "key", width: 30 },
        { header: "Value", key: "value", width: 60 },
      ];
      for (const [key, value] of Object.entries(section.data)) {
        sheet.addRow({ key, value: typeof value === "object" ? JSON.stringify(value) : String(value) });
      }
      sheet.getRow(1).eachCell((cell) => {
        cell.fill = headerFill;
        cell.font = headerFont;
      });
    }
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
