import { Router } from 'express';
import { loadModuleRoute, modulesDiagnosticRouter } from '@dos/service-bootstrap';
import policyRouter from './policy.routes';

const governance_governance_adminRouter = loadModuleRoute('governance/governance/core/governance-admin', '../../../modules/governance/dist/governance/routes/governance/core/governance-admin.routes');
const governance_governance_enforcementRouter = loadModuleRoute('governance/governance/core/governance-enforcement', '../../../modules/governance/dist/governance/routes/governance/core/governance-enforcement.routes');
const governance_governance_healthRouter = loadModuleRoute('governance/governance/core/governance-health', '../../../modules/governance/dist/governance/routes/governance/core/governance-health.routes');
const governance_governance_hooksRouter = loadModuleRoute('governance/governance/core/governance-hooks', '../../../modules/governance/dist/governance/routes/governance/core/governance-hooks.routes');
const governance_governanceRouter = loadModuleRoute('governance/governance/core/governance', '../../../modules/governance/dist/governance/routes/governance/core/governance.routes');
const governance_governance_acknowledgementsRouter = loadModuleRoute('governance/governance/governance-acknowledgements', '../../../modules/governance/dist/governance/routes/governance/governance-acknowledgements.routes');
const governance_governance_admin_1Router = loadModuleRoute('governance/governance/governance-admin', '../../../modules/governance/dist/governance/routes/governance/governance-admin.routes');
const governance_governance_aiRouter = loadModuleRoute('governance/governance/governance-ai', '../../../modules/governance/dist/governance/routes/governance/governance-ai.routes');
const governance_governance_board_packsRouter = loadModuleRoute('governance/governance/governance-board-packs', '../../../modules/governance/dist/governance/routes/governance/governance-board-packs.routes');
const governance_governance_chartersRouter = loadModuleRoute('governance/governance/governance-charters', '../../../modules/governance/dist/governance/routes/governance/governance-charters.routes');
const governance_governance_delegationsRouter = loadModuleRoute('governance/governance/governance-delegations', '../../../modules/governance/dist/governance/routes/governance/governance-delegations.routes');
const governance_governance_enforcement_1Router = loadModuleRoute('governance/governance/governance-enforcement', '../../../modules/governance/dist/governance/routes/governance/governance-enforcement.routes');
const governance_governance_executive_summariesRouter = loadModuleRoute('governance/governance/governance-executive-summaries', '../../../modules/governance/dist/governance/routes/governance/governance-executive-summaries.routes');
const governance_governance_health_1Router = loadModuleRoute('governance/governance/governance-health', '../../../modules/governance/dist/governance/routes/governance/governance-health.routes');
const governance_governance_hooks_1Router = loadModuleRoute('governance/governance/governance-hooks', '../../../modules/governance/dist/governance/routes/governance/governance-hooks.routes');
const governance_governance_mandatesRouter = loadModuleRoute('governance/governance/governance-mandates', '../../../modules/governance/dist/governance/routes/governance/governance-mandates.routes');
const governance_governance_objectivesRouter = loadModuleRoute('governance/governance/governance-objectives', '../../../modules/governance/dist/governance/routes/governance/governance-objectives.routes');
const governance_governance_obligationsRouter = loadModuleRoute('governance/governance/governance-obligations', '../../../modules/governance/dist/governance/routes/governance/governance-obligations.routes');
const governance_governance_os_contextRouter = loadModuleRoute('governance/governance/governance-os-context', '../../../modules/governance/dist/governance/routes/governance/governance-os-context.routes');
const governance_governance_os_learningRouter = loadModuleRoute('governance/governance/governance-os-learning', '../../../modules/governance/dist/governance/routes/governance/governance-os-learning.routes');
const governance_governance_osRouter = loadModuleRoute('governance/governance/governance-os', '../../../modules/governance/dist/governance/routes/governance/governance-os.routes');
const governance_governance_raci_templatesRouter = loadModuleRoute('governance/governance/governance-raci-templates', '../../../modules/governance/dist/governance/routes/governance/governance-raci-templates.routes');
const governance_governance_raciRouter = loadModuleRoute('governance/governance/governance-raci', '../../../modules/governance/dist/governance/routes/governance/governance-raci.routes');
const governance_governance_registersRouter = loadModuleRoute('governance/governance/governance-registers', '../../../modules/governance/dist/governance/routes/governance/governance-registers.routes');
const governance_governance_responsibilitiesRouter = loadModuleRoute('governance/governance/governance-responsibilities', '../../../modules/governance/dist/governance/routes/governance/governance-responsibilities.routes');
const governance_governance_reviewsRouter = loadModuleRoute('governance/governance/governance-reviews', '../../../modules/governance/dist/governance/routes/governance/governance-reviews.routes');
const governance_governance_structureRouter = loadModuleRoute('governance/governance/governance-structure', '../../../modules/governance/dist/governance/routes/governance/governance-structure.routes');
const governance_governance_workloadRouter = loadModuleRoute('governance/governance/governance-workload', '../../../modules/governance/dist/governance/routes/governance/governance-workload.routes');
const governance_governance_1Router = loadModuleRoute('governance/governance/governance', '../../../modules/governance/dist/governance/routes/governance/governance.routes');
const governance_governance_ai_1Router = loadModuleRoute('governance/governance/intelligence/governance-ai', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-ai.routes');
const governance_governance_board_packs_1Router = loadModuleRoute('governance/governance/intelligence/governance-board-packs', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-board-packs.routes');
const governance_governance_executive_summaries_1Router = loadModuleRoute('governance/governance/intelligence/governance-executive-summaries', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-executive-summaries.routes');
const governance_governance_os_context_1Router = loadModuleRoute('governance/governance/intelligence/governance-os-context', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-os-context.routes');
const governance_governance_os_learning_1Router = loadModuleRoute('governance/governance/intelligence/governance-os-learning', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-os-learning.routes');
const governance_governance_os_1Router = loadModuleRoute('governance/governance/intelligence/governance-os', '../../../modules/governance/dist/governance/routes/governance/intelligence/governance-os.routes');
const governance_governance_acknowledgements_1Router = loadModuleRoute('governance/governance/operations/governance-acknowledgements', '../../../modules/governance/dist/governance/routes/governance/operations/governance-acknowledgements.routes');
const governance_governance_charters_1Router = loadModuleRoute('governance/governance/operations/governance-charters', '../../../modules/governance/dist/governance/routes/governance/operations/governance-charters.routes');
const governance_governance_mandates_1Router = loadModuleRoute('governance/governance/operations/governance-mandates', '../../../modules/governance/dist/governance/routes/governance/operations/governance-mandates.routes');
const governance_governance_objectives_1Router = loadModuleRoute('governance/governance/operations/governance-objectives', '../../../modules/governance/dist/governance/routes/governance/operations/governance-objectives.routes');
const governance_governance_obligations_1Router = loadModuleRoute('governance/governance/operations/governance-obligations', '../../../modules/governance/dist/governance/routes/governance/operations/governance-obligations.routes');
const governance_governance_reviews_1Router = loadModuleRoute('governance/governance/operations/governance-reviews', '../../../modules/governance/dist/governance/routes/governance/operations/governance-reviews.routes');
const governance_governance_workload_1Router = loadModuleRoute('governance/governance/operations/governance-workload', '../../../modules/governance/dist/governance/routes/governance/operations/governance-workload.routes');
const governance_governance_delegations_1Router = loadModuleRoute('governance/governance/structure/governance-delegations', '../../../modules/governance/dist/governance/routes/governance/structure/governance-delegations.routes');
const governance_governance_raci_templates_1Router = loadModuleRoute('governance/governance/structure/governance-raci-templates', '../../../modules/governance/dist/governance/routes/governance/structure/governance-raci-templates.routes');
const governance_governance_raci_1Router = loadModuleRoute('governance/governance/structure/governance-raci', '../../../modules/governance/dist/governance/routes/governance/structure/governance-raci.routes');
const governance_governance_registers_1Router = loadModuleRoute('governance/governance/structure/governance-registers', '../../../modules/governance/dist/governance/routes/governance/structure/governance-registers.routes');
const governance_governance_responsibilities_1Router = loadModuleRoute('governance/governance/structure/governance-responsibilities', '../../../modules/governance/dist/governance/routes/governance/structure/governance-responsibilities.routes');
const governance_governance_structure_1Router = loadModuleRoute('governance/governance/structure/governance-structure', '../../../modules/governance/dist/governance/routes/governance/structure/governance-structure.routes');
const governance_governance_board_decisionsRouter = loadModuleRoute('governance/governance-board-decisions', '../../../modules/governance/dist/governance/routes/governance-board-decisions.routes');
const governance_governance_diagnosticsRouter = loadModuleRoute('governance/governance-diagnostics', '../../../modules/governance/dist/governance/routes/governance-diagnostics.routes');
const governance_grc_lifecycle_gapsRouter = loadModuleRoute('governance/grc-lifecycle-gaps', '../../../modules/governance/dist/governance/routes/grc-lifecycle-gaps.routes');
const governance_board_decisionsRouter = loadModuleRoute('governance/misc/board-decisions', '../../../modules/governance/dist/governance/routes/misc/board-decisions.routes');
const governance_board_intelligenceRouter = loadModuleRoute('governance/misc/board-intelligence', '../../../modules/governance/dist/governance/routes/misc/board-intelligence.routes');
const governance_ethics_governanceRouter = loadModuleRoute('governance/misc/ethics-governance', '../../../modules/governance/dist/governance/routes/misc/ethics-governance.routes');
const governance_fitchRouter = loadModuleRoute('governance/misc/fitch', '../../../modules/governance/dist/governance/routes/misc/fitch.routes');
const governance_grc_raciRouter = loadModuleRoute('governance/misc/grc-raci', '../../../modules/governance/dist/governance/routes/misc/grc-raci.routes');
const governance_initiative_orchestratorRouter = loadModuleRoute('governance/misc/initiative-orchestrator', '../../../modules/governance/dist/governance/routes/misc/initiative-orchestrator.routes');
const governance_maturity_extRouter = loadModuleRoute('governance/misc/maturity-ext', '../../../modules/governance/dist/governance/routes/misc/maturity-ext.routes');
const governance_maturityRouter = loadModuleRoute('governance/misc/maturity', '../../../modules/governance/dist/governance/routes/misc/maturity.routes');
const governance_admin_governance_adminRouter = loadModuleRoute('governance/admin/governance-admin', '../../../modules/governance/dist/governance/admin/governance-admin.routes');
const governance_ai_governance_aiRouter = loadModuleRoute('governance-ai/governance-ai', '../../../modules/governance-ai/dist/governance-ai/routes/governance-ai.routes');
const governance_ai_admin_governance_ai_adminRouter = loadModuleRoute('governance-ai/admin/governance-ai-admin', '../../../modules/governance-ai/dist/governance-ai/admin/governance-ai-admin.routes');
const governance_os_contextRouter = loadModuleRoute('governance-os/context', '../../../modules/governance-os/dist/governance-os/routes/context.routes');
const governance_os_governance_os_adminRouter = loadModuleRoute('governance-os/governance-os-admin', '../../../modules/governance-os/dist/governance-os/routes/governance-os-admin.routes');
const governance_os_governance_os_diagnosticsRouter = loadModuleRoute('governance-os/governance-os-diagnostics', '../../../modules/governance-os/dist/governance-os/routes/governance-os-diagnostics.routes');
const governance_os_governance_os_frameworkRouter = loadModuleRoute('governance-os/governance-os-framework', '../../../modules/governance-os/dist/governance-os/routes/governance-os-framework.routes');
const governance_os_governance_os_initiativeRouter = loadModuleRoute('governance-os/governance-os-initiative', '../../../modules/governance-os/dist/governance-os/routes/governance-os-initiative.routes');
const governance_os_governance_os_maturityRouter = loadModuleRoute('governance-os/governance-os-maturity', '../../../modules/governance-os/dist/governance-os/routes/governance-os-maturity.routes');
const governance_os_initiativeRouter = loadModuleRoute('governance-os/initiative', '../../../modules/governance-os/dist/governance-os/routes/initiative.routes');
const governance_os_module_stateRouter = loadModuleRoute('governance-os/module-state', '../../../modules/governance-os/dist/governance-os/routes/module-state.routes');
const proactive_leadership_proactive_leadershipRouter = loadModuleRoute('proactive-leadership/proactive-leadership', '../../../modules/proactive-leadership/dist/proactive-leadership/routes/proactive-leadership.routes');
const proactive_leadership_admin_proactive_leadership_adminRouter = loadModuleRoute('proactive-leadership/admin/proactive-leadership-admin', '../../../modules/proactive-leadership/dist/proactive-leadership/admin/proactive-leadership-admin.routes');

// V2 / Governance vertical — mount every policy module route file. Local
// policy.routes remains the canonical /policy base handler; these module
// sub-routers are extracted aggregates that FE calls at /api/policy-<name>
// (lifecycle, analysis, coverage, etc.). 15 previously orphaned route files.
const policy_admin_policy_adminRouter = loadModuleRoute('policy/admin/policy-admin', '../../../modules/policy/dist/policy/admin/policy-admin.routes');
const policy_policiesRouter = loadModuleRoute('policy/policies', '../../../modules/policy/dist/policy/routes/policies.routes');
const policy_policy_adminRouter = loadModuleRoute('policy/policy-admin', '../../../modules/policy/dist/policy/routes/policy-admin.routes');
const policy_policy_analysisRouter = loadModuleRoute('policy/policy-analysis', '../../../modules/policy/dist/policy/routes/policy-analysis.routes');
const policy_policy_attestationRouter = loadModuleRoute('policy/policy-attestation', '../../../modules/policy/dist/policy/routes/policy-attestation.routes');
const policy_policy_codeRouter = loadModuleRoute('policy/policy-code', '../../../modules/policy/dist/policy/routes/policy-code.routes');
const policy_policy_coverageRouter = loadModuleRoute('policy/policy-coverage', '../../../modules/policy/dist/policy/routes/policy-coverage.routes');
const policy_policy_diagnosticsRouter = loadModuleRoute('policy/policy-diagnostics', '../../../modules/policy/dist/policy/routes/policy-diagnostics.routes');
const policy_policy_exceptionRouter = loadModuleRoute('policy/policy-exception', '../../../modules/policy/dist/policy/routes/policy-exception.routes');
const policy_policy_impactRouter = loadModuleRoute('policy/policy-impact', '../../../modules/policy/dist/policy/routes/policy-impact.routes');
const policy_policy_lifecycleRouter = loadModuleRoute('policy/policy-lifecycle', '../../../modules/policy/dist/policy/routes/policy-lifecycle.routes');
const policy_policy_overviewRouter = loadModuleRoute('policy/policy-overview', '../../../modules/policy/dist/policy/routes/policy-overview.routes');
const policy_policy_publicationRouter = loadModuleRoute('policy/policy-publication', '../../../modules/policy/dist/policy/routes/policy-publication.routes');
const policy_policy_reportsRouter = loadModuleRoute('policy/policy-reports', '../../../modules/policy/dist/policy/routes/policy-reports.routes');
const policy_policy_templateRouter = loadModuleRoute('policy/policy-template', '../../../modules/policy/dist/policy/routes/policy-template.routes');

export const routes = Router();

routes.get('/info', (_req, res) => {
  res.json({ service: 'governance-policy-service', version: '0.1.0', modules: 4 });
});

routes.use('/policy', policyRouter);

routes.use('/governance/governance-admin', governance_governance_adminRouter);
routes.use('/governance/governance-enforcement', governance_governance_enforcementRouter);
routes.use('/governance/governance-health', governance_governance_healthRouter);
routes.use('/governance/governance-hooks', governance_governance_hooksRouter);
routes.use('/governance', governance_governanceRouter);
routes.use('/governance/governance-acknowledgements', governance_governance_acknowledgementsRouter);
routes.use('/governance/governance-admin', governance_governance_admin_1Router);
routes.use('/governance/governance-ai', governance_governance_aiRouter);
routes.use('/governance/governance-board-packs', governance_governance_board_packsRouter);
routes.use('/governance/governance-charters', governance_governance_chartersRouter);
routes.use('/governance/governance-delegations', governance_governance_delegationsRouter);
routes.use('/governance/governance-enforcement', governance_governance_enforcement_1Router);
routes.use('/governance/governance-executive-summaries', governance_governance_executive_summariesRouter);
routes.use('/governance/governance-health', governance_governance_health_1Router);
routes.use('/governance/governance-hooks', governance_governance_hooks_1Router);
routes.use('/governance/governance-mandates', governance_governance_mandatesRouter);
routes.use('/governance/governance-objectives', governance_governance_objectivesRouter);
routes.use('/governance/governance-obligations', governance_governance_obligationsRouter);
routes.use('/governance/governance-os-context', governance_governance_os_contextRouter);
routes.use('/governance/governance-os-learning', governance_governance_os_learningRouter);
routes.use('/governance/governance-os', governance_governance_osRouter);
routes.use('/governance/governance-raci-templates', governance_governance_raci_templatesRouter);
routes.use('/governance/governance-raci', governance_governance_raciRouter);
routes.use('/governance/governance-registers', governance_governance_registersRouter);
routes.use('/governance/governance-responsibilities', governance_governance_responsibilitiesRouter);
routes.use('/governance/governance-reviews', governance_governance_reviewsRouter);
routes.use('/governance/governance-structure', governance_governance_structureRouter);
routes.use('/governance/governance-workload', governance_governance_workloadRouter);
routes.use('/governance', governance_governance_1Router);
routes.use('/governance/governance-ai', governance_governance_ai_1Router);
routes.use('/governance/governance-board-packs', governance_governance_board_packs_1Router);
routes.use('/governance/governance-executive-summaries', governance_governance_executive_summaries_1Router);
routes.use('/governance/governance-os-context', governance_governance_os_context_1Router);
routes.use('/governance/governance-os-learning', governance_governance_os_learning_1Router);
routes.use('/governance/governance-os', governance_governance_os_1Router);
routes.use('/governance/governance-acknowledgements', governance_governance_acknowledgements_1Router);
routes.use('/governance/governance-charters', governance_governance_charters_1Router);
routes.use('/governance/governance-mandates', governance_governance_mandates_1Router);
routes.use('/governance/governance-objectives', governance_governance_objectives_1Router);
routes.use('/governance/governance-obligations', governance_governance_obligations_1Router);
routes.use('/governance/governance-reviews', governance_governance_reviews_1Router);
routes.use('/governance/governance-workload', governance_governance_workload_1Router);
routes.use('/governance/governance-delegations', governance_governance_delegations_1Router);
routes.use('/governance/governance-raci-templates', governance_governance_raci_templates_1Router);
routes.use('/governance/governance-raci', governance_governance_raci_1Router);
routes.use('/governance/governance-registers', governance_governance_registers_1Router);
routes.use('/governance/governance-responsibilities', governance_governance_responsibilities_1Router);
routes.use('/governance/governance-structure', governance_governance_structure_1Router);
routes.use('/governance/governance-board-decisions', governance_governance_board_decisionsRouter);
routes.use('/governance/governance-diagnostics', governance_governance_diagnosticsRouter);
routes.use('/governance/grc-lifecycle-gaps', governance_grc_lifecycle_gapsRouter);
routes.use('/governance/board-decisions', governance_board_decisionsRouter);
routes.use('/governance/board-intelligence', governance_board_intelligenceRouter);
routes.use('/governance/ethics-governance', governance_ethics_governanceRouter);
routes.use('/governance/fitch', governance_fitchRouter);
routes.use('/governance/grc-raci', governance_grc_raciRouter);
routes.use('/governance/initiative-orchestrator', governance_initiative_orchestratorRouter);
routes.use('/governance/maturity-ext', governance_maturity_extRouter);
routes.use('/governance/maturity', governance_maturityRouter);
routes.use('/governance/admin', governance_admin_governance_adminRouter);
routes.use('/governance-ai', governance_ai_governance_aiRouter);
routes.use('/governance-ai/admin', governance_ai_admin_governance_ai_adminRouter);
routes.use('/governance-os/context', governance_os_contextRouter);
routes.use('/governance-os/governance-os-admin', governance_os_governance_os_adminRouter);
routes.use('/governance-os/governance-os-diagnostics', governance_os_governance_os_diagnosticsRouter);
routes.use('/governance-os/governance-os-framework', governance_os_governance_os_frameworkRouter);
routes.use('/governance-os/governance-os-initiative', governance_os_governance_os_initiativeRouter);
routes.use('/governance-os/governance-os-maturity', governance_os_governance_os_maturityRouter);
routes.use('/governance-os/initiative', governance_os_initiativeRouter);
routes.use('/governance-os/module-state', governance_os_module_stateRouter);
routes.use('/proactive-leadership', proactive_leadership_proactive_leadershipRouter);
routes.use('/proactive-leadership/admin', proactive_leadership_admin_proactive_leadership_adminRouter);

// V2 — policy module sub-routers (relative to /api/policy-*). FE-DRIFT from
// the prior audit (POST /api/policy-exceptions, GET /api/policy-overview,
// POST /api/policy-publications) is closed honestly — the module files
// implement the handlers; we mount them at the shape Shahin already emits.
routes.use('/policy/admin', policy_admin_policy_adminRouter);
routes.use('/policies', policy_policiesRouter);
routes.use('/policy-admin', policy_policy_adminRouter);
routes.use('/policy-analysis', policy_policy_analysisRouter);
routes.use('/policy-attestation', policy_policy_attestationRouter);
routes.use('/policy-code', policy_policy_codeRouter);
routes.use('/policy-coverage', policy_policy_coverageRouter);
routes.use('/policy-diagnostics', policy_policy_diagnosticsRouter);
routes.use('/policy-exception', policy_policy_exceptionRouter);
routes.use('/policy-exceptions', policy_policy_exceptionRouter);
routes.use('/policy-impact', policy_policy_impactRouter);
routes.use('/policy-lifecycle', policy_policy_lifecycleRouter);
routes.use('/policy-overview', policy_policy_overviewRouter);
routes.use('/policy-publication', policy_policy_publicationRouter);
routes.use('/policy-publications', policy_policy_publicationRouter);
routes.use('/policy-reports', policy_policy_reportsRouter);
routes.use('/policy-template', policy_policy_templateRouter);

routes.use('/modules', modulesDiagnosticRouter());
