/**
 * issues — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition } from './ports/lifecycle.port';

const ISSUES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ISSUES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'issues',
  'issues',
  ISSUES_STATES,
  ISSUES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const ISSUE_LINKS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ISSUE_LINKS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'issues',
  'issue_links',
  ISSUE_LINKS_STATES,
  ISSUE_LINKS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const ISSUE_HISTORY_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const ISSUE_HISTORY_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'issues',
  'issue_history',
  ISSUE_HISTORY_STATES,
  ISSUE_HISTORY_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);
