// ============================================
// DAuth — Role → Permission Mappings
// Data-driven security (Law 3). Owner: DAuth
// ============================================

import { CANONICAL_PERMISSIONS } from './canonical-permissions';

// ── Role → Permission mappings ─────────────────────────────────────

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  platform_super_admin: CANONICAL_PERMISSIONS.map(p => p.code),
  tenant_admin: [
    'platform.tenant.read', 'platform.tenant.update',
    'platform.user.create', 'platform.user.read', 'platform.user.update', 'platform.user.delete',
    'platform.role.manage', 'platform.permission.manage',
    'platform.settings.read', 'platform.settings.update',
    'platform.audit.read', 'platform.module.enable', 'platform.module.disable',
    'platform.agent.read', 'platform.subscription.read', 'platform.subscription.manage',
    'platform.workspace.read', 'platform.workspace.manage',
    'dauth.delegation.create', 'dauth.delegation.revoke',
    'dauth.sod.manage', 'dauth.access_profile.manage',
    'onboarding.record.read', 'onboarding.record.write', 'onboarding.manage', 'onboarding.admin',
    'reporting.dashboard.read', 'reporting.report.generate', 'reporting.record.read',
    'workspace.config.read', 'workspace.config.write',
    'profile.record.read',
    'admin.system.read', 'admin.system.write', 'admin.system.configure', 'admin.system.manage',
    'admin.record.read', 'admin.field-rbac.read', 'admin.field-rbac.write',
    'admin.security-config.read', 'admin.security-config.write',
    'users.account.manage',
    'analytics.report.read', 'analytics.report.write', 'analytics.report.configure', 'analytics.record.read',
    'control.record.read', 'control.record.write',
    'assessment.record.read', 'assessment.record.manage',
    'framework.record.read', 'framework.record.manage',
    'risk.record.read', 'risk.record.write', 'risk.record.configure', 'risk.record.delete',
    'audit.record.read', 'audit.record.manage',
    'evidence.item.read', 'evidence.item.write', 'evidence.record.read',
    'compliance.program.read', 'compliance.program.manage', 'compliance.program.write', 'compliance.record.read',
    'compliance.control.approve',
    'incident.record.read', 'incident.record.write', 'incident.record.configure',
    'vendor.record.read', 'vendor.record.write', 'vendor.record.configure', 'vendor.record.manage',
    'privacy.record.read', 'privacy.record.write', 'privacy.record.configure',
    'copilot.assistant.read',
    'ai.agent.read', 'ai.agent.manage', 'ai.record.read', 'ai-governance.record.read',
    'knowledge.base.read',
    'integrations.connector.read', 'integrations.connector.write', 'integrations.connector.configure', 'integrations.record.read',
    'report.document.read', 'report.document.write',
    'timeline.event.read',
    'task.item.read', 'action.item.read', 'action.item.configure', 'action.record.read',
    'exception.record.read', 'exception.record.configure', 'remediation.task.read', 'remediation.record.read',
    'messaging.channel.read',
    'workflow.instance.read', 'workflow.instance.write', 'workflow.record.read', 'workflow.approval.read', 'workflow.task.read',
    'governance.record.read', 'governance.record.manage', 'governance.record.write',
    'foundation.org.read', 'foundation.org.manage',
    'foundation.record.read', 'foundation.record.write', 'foundation.record.approve', 'foundation.record.delete', 'foundation.manage',
    'asset.record.read', 'asset.record.manage', 'asset.record.write',
    'position.record.read',
    'team.member.read', 'team.member.manage', 'team.record.read', 'team.record.write', 'team.manage',
    'ai.governance.read',
    'training.record.read', 'training.record.manage', 'training.record.write', 'training.record.configure',
    'bcp.plan.read', 'bcp.plan.manage', 'bcp.plan.write', 'bcp.plan.configure', 'bcp.record.read',
    'tenant.config.read', 'tenant.config.write', 'tenant.config.manage',
    'notification.config.read', 'notification.config.write', 'notification.record.read',
    'inbox.item.read', 'inbox.item.write', 'inbox.record.read',
    'dashboard.record.read', 'dashboard.record.write', 'dashboard.manage',
    'navigation.record.read', 'navigation.record.write', 'navigation.manage',
    'widgets.record.read', 'widgets.record.write', 'widgets.manage',
    'portals.record.read', 'portals.record.write',
    'records.record.read', 'records.record.write',
    'issues.record.read', 'issues.record.write',
    'bootstrap.record.read', 'bootstrap.manage',
    'provisioning.record.read', 'provisioning.manage',
    'journey.record.read', 'journey.record.write',
    'packs.record.read', 'packs.pack.manage', 'packs.manage',
    'dora.record.read', 'dora.record.write',
    'qiyas.record.read', 'qiyas.assessment.read',
    'governance_ai.record.read', 'governance_ai.manage',
    'governance_os.admin.read', 'governance_os.admin.manage', 'governance_os.framework.read',
    'ksa_regulatory.intelligence.read', 'ksa_regulatory.readiness.read',
    'local_knowledge.document.read', 'local_knowledge.search.read', 'local_knowledge.source.read',
    'proactive_leadership.config.read', 'proactive_leadership.insight.read',
    'controls.record.read', 'controls.record.write', 'controls.record.delete', 'controls.manage',
    'incident.write', 'controls.monitor', 'controls.admin',
    'remediation.write', 'exception.write', 'action.write',
    'risk.approve', 'platform.admin',
    'access.read', 'access.manage', 'agent.read', 'agent.manage',
    'action.manage', 'admin.config.manage', 'admin.content-pack.read', 'admin.content-pack.write',
    'admin.feature-table.write', 'admin.manage', 'admin.pack.write', 'admin.payment.write',
    'admin.platform.read', 'admin.platform.write', 'admin.system.shell', 'admin.tenant.manage',
    'agrc_engine.manage', 'analytics.manage', 'asset.manage',
    'ai.agent.approve', 'ai.agent.configure', 'ai.agent.execute', 'ai.agent.view', 'ai.agent.write',
    'ai.copilot.read', 'ai.copilot.write', 'ai.governance.approve', 'ai.governance.configure', 'ai.governance.write',
    'ai.personal-agent.approve', 'ai.personal-agent.write', 'ai.squad.read',
    'ai_governance.manage', 'ai_governance.read',
    'attestation.record.manage', 'attestation.record.read', 'attestation.record.write',
    'audit.finding.read', 'audit.manage', 'audit.record.configure',
    'bcp.manage', 'ccm.record.read',
    'compliance.assessment.approve', 'compliance.assessment.read', 'compliance.assessment.write',
    'compliance.dpia.write', 'compliance.manage', 'compliance.mapping.manage', 'compliance.mapping.view',
    'compliance.maturity.assess', 'compliance.maturity.view', 'compliance.program.configure',
    'compliance.read', 'compliance.regulatory.manage', 'compliance.regulatory.view', 'compliance.score.view',
    'delegation.chain.manage', 'delegation.chain.read', 'delegation.chain.write',
    'document.record.delete', 'document.record.read', 'document.record.write',
    'dora.manage', 'dora.record.delete', 'event.log.read',
    'evidence.item.admin', 'evidence.item.configure', 'evidence.manage', 'evidence.read',
    'foundation.org.write', 'framework.record.write', 'gate.record.read',
    'governance.manage', 'governance.read', 'governance.record.configure', 'governance.record.delete',
    'inbox.manage', 'incident.manage', 'integrations.connector.manage', 'integrations.manage',
    'issues.manage', 'knowledge.base.write', 'knowledge.graph.read', 'knowledge.graph.write',
    'ksa_regulatory.manage', 'local_knowledge.manage',
    'maturity.assessment.read', 'notification.manage',
    'platform.agent.manage', 'platform.agent.write',
    'policy.manage', 'portals.manage', 'privacy.manage', 'proactive_leadership.manage',
    'profile.record.write',
    'qiyas.assessment.delete', 'qiyas.assessment.write', 'qiyas.manage',
    'remediation.manage',
    'report.document.download', 'report.document.share',
    'reporting.cadence.read', 'reporting.cadence.write', 'reporting.manage',
    'reporting.monitoring.delete', 'reporting.monitoring.read', 'reporting.monitoring.write',
    'reporting.report.configure', 'reporting.report.read',
    'reports.document.generate', 'reports.document.read', 'reports.document.sign',
    'risk.manage',
    'risk.record.submit', 'risk.record.review', 'risk.record.approve', 'risk.record.close', 'risk.record.update', 'risk.treatment.assign',
    'audit.engagement.create', 'audit.finding.close', 'audit.finding.issue', 'audit.finding.respond',
    'audit.report.approve', 'audit.report.create', 'audit.workpaper.update',
    'policy.document.update', 'policy.document.review', 'policy.document.approve', 'policy.document.retire',
    'compliance.control.update', 'compliance.obligation.approve', 'compliance.obligation.update',
    'compliance.attestation.submit', 'compliance.attestation.review', 'compliance.attestation.manage',
    'compliance.score.approve', 'compliance.score.review', 'compliance.test.execute',
    'incident.record.update', 'incident.record.review', 'incident.record.approve', 'incident.record.escalate',
    'vendor.record.create', 'vendor.assessment.execute', 'vendor.assessment.approve',
    'evidence.item.upload', 'evidence.item.verify', 'evidence.item.lock', 'evidence.item.release', 'evidence.item.archive',
    'governance.body.create', 'governance.charter.update', 'governance.meeting.manage',
    'exception.request.create', 'exception.request.review', 'exception.request.approve',
    'remediation.task.update', 'remediation.task.close',
    'action.item.update', 'action.item.close',
    'asset.record.update', 'asset.classification.review',
    'bcp.plan.update', 'bcp.exercise.approve',
    'training.program.manage',
    'runbook.record.read', 'runbook.record.write',
    'shell.ui.read', 'shell.ui.write',
    'sop.document.read', 'sop.document.write',
    'telemetry.data.write', 'training.manage', 'vendor.manage',
    'workflow.agent.execute', 'workflow.agent.manage', 'workflow.agent.read',
    'workflow.approval.approve', 'workflow.autonomous.config', 'workflow.autonomous.read', 'workflow.autonomous.write',
    'workflow.instance.configure', 'workflow.instance.execute', 'workflow.manage',
    'workflow.policy.manage', 'workflow.policy.read', 'workflow.task.act',
    'admin.config.read', 'admin.system.settings',
    'ai.contextual.read', 'ai.contextual.write',
    'ai_squad.manage', 'ai_squad.read',
    'assessment.record.delete', 'assessment.record.write',
    'control.record.delete',
    'evidence.item.delete', 'evidence.item.manage',
    'exception.record.write',
    'obligation.write',
    'platform.command_palette.read',
    'platform.entity_link.delete', 'platform.entity_link.write',
    'platform.inline_edit.read', 'platform.inline_edit.write',
    'platform.messaging.write', 'platform.search.read',
    'security.config.read', 'security.config.write',
    'workflow.approve', 'workflow.delete',
    'bootstrap.record.approve',
    'compliance.assessment.finalize', 'compliance.framework.approve', 'compliance.framework.suspend',
    'compliance.obligation.waive',
    'dora.record.approve',
    'evidence.collection.complete', 'evidence.collection.manage',
  ],
  security_admin: [
    'platform.user.read', 'platform.role.manage', 'platform.permission.manage',
    'platform.audit.read', 'platform.settings.read',
    'dauth.delegation.create', 'dauth.delegation.revoke',
    'dauth.sod.manage', 'dauth.access_profile.manage',
    'workspace.config.read', 'profile.record.read',
    'admin.system.read', 'admin.field-rbac.read', 'admin.field-rbac.write',
    'admin.security-config.read', 'admin.security-config.write',
    'analytics.report.read', 'report.document.read',
    'timeline.event.read',
    'notification.config.read', 'notification.config.write',
    'access.read', 'access.manage',
    'security.config.read', 'security.config.write',
    'admin.config.read',
  ],
  compliance_officer: [
    'compliance.control.read', 'compliance.control.manage', 'compliance.control.approve',
    'compliance.evidence.submit', 'compliance.evidence.review',
    'compliance.program.read', 'compliance.program.manage', 'compliance.program.write', 'compliance.record.read',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'control.record.read', 'controls.record.read', 'assessment.record.read', 'framework.record.read',
    'evidence.item.read', 'evidence.record.read',
    'analytics.report.read', 'report.document.read',
    'risk.record.read', 'audit.record.read', 'policy.document.read', 'policy.record.read',
    'task.item.read', 'action.item.read', 'timeline.event.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read', 'asset.record.read',
    'position.record.read', 'team.member.read', 'training.record.read',
    'dora.record.read', 'qiyas.record.read', 'qiyas.assessment.read',
    'ksa_regulatory.intelligence.read', 'ksa_regulatory.readiness.read', 'ksa_regulatory.compliance_score.read',
    'controls.monitor', 'controls.test', 'controls.report',
    'exception.record.read', 'remediation.task.read',
    'issues.record.read', 'inbox.item.read', 'inbox.record.read',
    'workflow.instance.read', 'workflow.record.read',
    'attestation.record.read', 'attestation.record.write', 'attestation.record.manage',
    'compliance.assessment.read', 'compliance.assessment.write', 'compliance.assessment.approve',
    'compliance.dpia.write', 'compliance.manage', 'compliance.mapping.manage', 'compliance.mapping.view',
    'compliance.maturity.assess', 'compliance.maturity.view', 'compliance.program.configure',
    'compliance.read', 'compliance.regulatory.manage', 'compliance.regulatory.view', 'compliance.score.view',
    'ccm.record.read', 'maturity.assessment.read',
    'controls.record.write', 'controls.manage',
    'evidence.item.configure', 'evidence.manage', 'evidence.read',
    'document.record.read',
    'compliance.control.update', 'compliance.obligation.approve', 'compliance.obligation.update',
    'compliance.attestation.submit', 'compliance.attestation.review', 'compliance.attestation.manage',
    'compliance.score.approve', 'compliance.score.review', 'compliance.test.execute',
    'evidence.item.upload', 'evidence.item.verify', 'evidence.item.lock', 'evidence.item.release',
    'evidence.item.delete', 'evidence.item.manage',
    'assessment.record.write', 'assessment.record.delete',
    'control.record.delete',
    'exception.record.write', 'obligation.write',
    'compliance.assessment.finalize', 'compliance.framework.approve', 'compliance.framework.suspend',
    'compliance.obligation.waive',
    'evidence.collection.complete', 'evidence.collection.manage',
    'platform.inline_edit.read', 'platform.search.read',
  ],
  risk_manager: [
    'risk.assessment.create', 'risk.assessment.approve',
    'risk.record.read', 'risk.record.write', 'risk.record.configure', 'risk.record.delete',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'control.record.read', 'assessment.record.read', 'framework.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'action.item.read', 'timeline.event.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read', 'asset.record.read',
    'bcp.plan.read', 'bcp.record.read', 'vendor.record.read', 'incident.record.read',
    'risk.approve', 'exception.record.read', 'remediation.task.read',
    'issues.record.read', 'workflow.instance.read',
    'risk.manage', 'compliance.assessment.read', 'compliance.score.view',
    'document.record.read', 'evidence.read',
    'risk.record.submit', 'risk.record.review', 'risk.record.approve', 'risk.record.close', 'risk.record.update', 'risk.treatment.assign',
  ],
  auditor: [
    'audit.finding.create', 'audit.finding.resolve',
    'audit.record.read', 'audit.record.manage',
    'compliance.control.read', 'compliance.evidence.review',
    'compliance.program.read', 'compliance.record.read',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'control.record.read', 'controls.record.read', 'assessment.record.read', 'framework.record.read',
    'evidence.item.read', 'evidence.record.read',
    'risk.record.read', 'policy.document.read', 'policy.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'action.item.read', 'timeline.event.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read', 'asset.record.read',
    'issues.record.read', 'workflow.instance.read',
    'audit.finding.read', 'audit.manage', 'audit.record.configure',
    'attestation.record.read', 'compliance.assessment.read', 'compliance.read',
    'document.record.read', 'evidence.read', 'evidence.item.configure',
    'audit.engagement.create', 'audit.finding.close', 'audit.finding.issue', 'audit.finding.respond',
    'audit.report.approve', 'audit.report.create', 'audit.workpaper.update',
    'evidence.item.upload', 'evidence.item.verify',
  ],
  policy_owner: [
    'policy.document.read', 'policy.document.manage', 'policy.document.publish',
    'policy.document.write', 'policy.document.configure', 'policy.document.delete',
    'policy.record.read', 'policy.record.approve',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'framework.record.read', 'control.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'timeline.event.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read',
    'workflow.instance.read',
    'policy.manage', 'document.record.read', 'document.record.write', 'sop.document.read', 'sop.document.write',
    'policy.document.update', 'policy.document.review', 'policy.document.approve', 'policy.document.retire',
  ],
  incident_manager: [
    'incident.record.read', 'incident.record.write', 'incident.record.configure',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'action.item.read', 'timeline.event.read',
    'governance.record.read', 'bcp.plan.read', 'bcp.record.read', 'asset.record.read',
    'incident.write', 'incident.delete',
    'workflow.instance.read',
    'incident.manage', 'runbook.record.read',
    'incident.record.update', 'incident.record.review', 'incident.record.approve', 'incident.record.escalate',
  ],
  vendor_manager: [
    'vendor.assessment.create',
    'vendor.record.read', 'vendor.record.write', 'vendor.record.configure', 'vendor.record.manage',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'timeline.event.read',
    'governance.record.read', 'asset.record.read',
    'workflow.instance.read',
    'vendor.manage',
    'vendor.record.create', 'vendor.assessment.execute', 'vendor.assessment.approve',
  ],
  standard_user: [
    'platform.user.read', 'platform.settings.read',
    'compliance.control.read', 'compliance.program.read', 'compliance.record.read',
    'policy.document.read', 'policy.record.read',
    'workflow.definition.read', 'onboarding.record.read', 'onboarding.record.write',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'control.record.read', 'controls.record.read', 'assessment.record.read', 'framework.record.read',
    'risk.record.read', 'audit.record.read', 'evidence.item.read', 'evidence.record.read',
    'incident.record.read', 'vendor.record.read',
    'privacy.record.read', 'copilot.assistant.read',
    'knowledge.base.read', 'analytics.report.read', 'analytics.record.read',
    'report.document.read', 'integrations.connector.read', 'integrations.record.read',
    'timeline.event.read', 'task.item.read', 'action.item.read', 'action.record.read',
    'exception.record.read', 'remediation.task.read', 'remediation.record.read',
    'messaging.channel.read',
    'workflow.instance.read', 'workflow.record.read', 'workflow.task.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read', 'asset.record.read',
    'position.record.read', 'team.member.read', 'team.record.read',
    'ai.governance.read', 'ai.record.read',
    'training.record.read', 'bcp.plan.read', 'bcp.record.read',
    'notification.config.read', 'notification.record.read', 'inbox.item.read', 'inbox.record.read',
    'dashboard.record.read', 'widgets.record.read',
    'issues.record.read', 'records.record.read',
    'journey.record.read',
    'dora.record.read', 'qiyas.record.read',
    'governance_ai.record.read', 'governance_os.framework.read',
    'ksa_regulatory.intelligence.read',
    'local_knowledge.document.read', 'local_knowledge.search.read',
    'proactive_leadership.insight.read',
    'attestation.record.read', 'audit.finding.read', 'ccm.record.read',
    'compliance.assessment.read', 'compliance.mapping.view', 'compliance.maturity.view',
    'compliance.read', 'compliance.regulatory.view', 'compliance.score.view',
    'document.record.read', 'event.log.read', 'evidence.read',
    'gate.record.read', 'governance.read',
    'knowledge.graph.read', 'maturity.assessment.read',
    'reporting.cadence.read', 'reporting.monitoring.read', 'reporting.report.read',
    'reports.document.read', 'runbook.record.read',
    'shell.ui.read', 'sop.document.read',
    'ai.agent.view', 'ai.copilot.read', 'ai.squad.read', 'ai_governance.read',
    'delegation.chain.read', 'workflow.autonomous.read', 'workflow.policy.read', 'workflow.agent.read',
    'risk.record.submit', 'risk.record.update',
    'policy.document.update',
    'compliance.attestation.submit',
    'incident.record.update',
    'evidence.item.upload',
    'exception.request.create',
    'remediation.task.update',
    'action.item.update',
    'asset.record.update',
    'bcp.plan.update',
    'platform.command_palette.read', 'platform.search.read',
    'platform.inline_edit.read', 'platform.entity_link.write',
    'platform.messaging.write',
    'ai.contextual.read', 'ai_squad.read',
  ],
  viewer: [
    'platform.user.read', 'platform.settings.read',
    'compliance.control.read', 'compliance.program.read', 'compliance.record.read',
    'policy.document.read', 'policy.record.read',
    'workflow.definition.read', 'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'control.record.read', 'controls.record.read', 'assessment.record.read', 'framework.record.read',
    'risk.record.read', 'audit.record.read', 'evidence.item.read', 'evidence.record.read',
    'incident.record.read', 'vendor.record.read',
    'privacy.record.read', 'knowledge.base.read',
    'analytics.report.read', 'analytics.record.read', 'report.document.read',
    'integrations.connector.read', 'integrations.record.read',
    'timeline.event.read', 'task.item.read', 'action.item.read', 'action.record.read',
    'exception.record.read', 'remediation.task.read', 'remediation.record.read',
    'workflow.instance.read', 'workflow.record.read',
    'governance.record.read', 'foundation.org.read', 'foundation.record.read', 'asset.record.read',
    'position.record.read', 'team.member.read', 'team.record.read',
    'ai.governance.read', 'ai.record.read',
    'training.record.read', 'bcp.plan.read', 'bcp.record.read',
    'notification.config.read', 'notification.record.read', 'inbox.item.read', 'inbox.record.read',
    'dashboard.record.read', 'widgets.record.read',
    'issues.record.read', 'records.record.read',
    'dora.record.read', 'qiyas.record.read',
    'governance_ai.record.read', 'governance_os.framework.read',
    'ksa_regulatory.intelligence.read',
    'local_knowledge.document.read', 'local_knowledge.search.read',
    'proactive_leadership.insight.read',
    'attestation.record.read', 'audit.finding.read', 'ccm.record.read',
    'compliance.assessment.read', 'compliance.mapping.view', 'compliance.maturity.view',
    'compliance.read', 'compliance.regulatory.view', 'compliance.score.view',
    'document.record.read', 'event.log.read', 'evidence.read',
    'gate.record.read', 'governance.read',
    'knowledge.graph.read', 'maturity.assessment.read',
    'reporting.cadence.read', 'reporting.monitoring.read', 'reporting.report.read',
    'reports.document.read', 'runbook.record.read',
    'shell.ui.read', 'sop.document.read',
    'ai.agent.view', 'ai.copilot.read', 'ai.squad.read', 'ai_governance.read',
    'delegation.chain.read', 'workflow.autonomous.read', 'workflow.policy.read', 'workflow.agent.read',
    'platform.command_palette.read', 'platform.search.read', 'platform.inline_edit.read',
    'ai.contextual.read', 'ai_squad.read',
  ],
  workflow_admin: [
    'workflow.definition.read', 'workflow.definition.manage', 'workflow.instance.approve',
    'workflow.instance.read', 'workflow.instance.write', 'workflow.record.read', 'workflow.approval.read', 'workflow.task.read',
    'reporting.dashboard.read',
    'workspace.config.read', 'profile.record.read',
    'analytics.report.read', 'report.document.read',
    'task.item.read', 'timeline.event.read',
    'governance.record.read',
    'action.item.read', 'action.record.read',
    'workflow.agent.execute', 'workflow.agent.manage', 'workflow.agent.read',
    'workflow.approval.approve', 'workflow.autonomous.config', 'workflow.autonomous.read', 'workflow.autonomous.write',
    'workflow.instance.configure', 'workflow.instance.execute', 'workflow.manage',
    'workflow.policy.manage', 'workflow.policy.read', 'workflow.task.act',
    'gate.record.read', 'runbook.record.read', 'runbook.record.write',
    'workflow.approve', 'workflow.delete',
  ],
};
