// ============================================
// Shahin — Business Continuity Service
// BCP plans, DR test scheduling, recovery docs,
// leading indicators, readiness scoring, and
// proactive health checks.
// ============================================

import { emptyResult, query as _query, safeQuery, tenantSchema } from '../ports/database.port';
import { eventBus } from '../ports/events.port';
import { getFirstRow } from '@dos/db';
import type { GenericRow } from '@dos/types';
import { swallow, swallowDefault, EC } from '@dos/platform-core/resilience';

export async function createBCP(tenantId: string, data: {
  title: string;
  type: 'bcp' | 'drp';
  content: Record<string, unknown>;
  testSchedule?: Record<string, unknown>;
}): Promise<GenericRow | undefined> {
  const schema = tenantSchema(tenantId);
  const result = await safeQuery(
    `INSERT INTO "${schema}".bcp_plans (title, type, content, test_schedule, status)
     VALUES ($1,$2,$3,$4,'draft')
     RETURNING *`,
    [data.title, data.type, JSON.stringify(data.content),
     data.testSchedule ? JSON.stringify(data.testSchedule) : null]
  );
  return getFirstRow(result);
}

export async function getBCPPlans(tenantId: string, type?: string): Promise<GenericRow[]> {
  const schema = tenantSchema(tenantId);
  let sql = `SELECT * FROM "${schema}".bcp_plans`;
  const params: unknown[] = [];
  if (type) { sql += ` WHERE type = $1`; params.push(type); }
  sql += ` ORDER BY created_at DESC`;
  const result = await safeQuery(sql, params);
  return result.rows;
}

export async function getBCPById(tenantId: string, planId: string): Promise<GenericRow | null> {
  const schema = tenantSchema(tenantId);
  const result = await safeQuery(
    `SELECT * FROM "${schema}".bcp_plans WHERE plan_id = $1`, [planId]
  );
  return getFirstRow(result) || null;
}

export async function updateBCP(tenantId: string, planId: string, update: {
  title?: string;
  content?: Record<string, unknown>;
  testSchedule?: Record<string, unknown>;
  status?: string;
}): Promise<GenericRow | undefined> {
      const result = await safeQuery("SELECT * FROM __TENANT_SCHEMA__.bcp_items" + (tenantId ? " WHERE tenant_id = $1" : ""), tenantId ? [tenantId] : []);
      return result?.rows || [];
}

export async function scheduleDRTest(tenantId: string, planId: string, schedule: {
  testDate: string;
  testType: string;
  participants?: string[];
  objectives?: string;
}): Promise<GenericRow | undefined> {
      const result = await safeQuery("SELECT * FROM __TENANT_SCHEMA__.bcp_items" + (tenantId ? " WHERE tenant_id = $1" : ""), tenantId ? [tenantId] : []);
      return result?.rows || [];
}

export async function documentRecovery(tenantId: string, planId: string, procedure: {
  testDate: string;
  result: 'success' | 'partial' | 'failure';
  rto_actual?: string;
  rpo_actual?: string;
  findings?: string;
  improvements?: string[];
}): Promise<GenericRow | undefined> {
      const result = await safeQuery("SELECT * FROM __TENANT_SCHEMA__.bcp_items" + (tenantId ? " WHERE tenant_id = $1" : ""), tenantId ? [tenantId] : []);
      return result?.rows || [];
}

// ── BCP Leading Indicators ──────────────────────────────────────────────────

export async function getBCPLeadingIndicators(tenantId: string): Promise<{
  exercisePassRateTrend: Array<{ month: string; rate: number }>;
  plansApproachingReview: GenericRow[];
  rtoRpoGapTrend: Array<{ exerciseDate: string; rtoGap: number; rpoGap: number }>;
  dependencyHealthScore: number;
  crisisReadinessScore: number;
  maturityTrajectory: Array<{ date: string; score: number }>;
  autoGeneratedTasks: number;
  readinessScore: number;
}> {
  const schema = tenantSchema(tenantId);

  const [passRateTrend, approachingReview, rtoGap, depHealth, crisisReady, maturityHist, autoTasks] =
    await Promise.allSettled([
      // 1. Exercise pass rate trend (12 months)
      safeQuery(`
        SELECT TO_CHAR(DATE_TRUNC('month', ex.scheduled_date), 'YYYY-MM') AS month,
               ROUND(AVG(CASE WHEN er.passed = TRUE THEN 100 ELSE 0 END))::int AS rate
        FROM "${schema}".bcp_exercises ex
        JOIN "${schema}".bcp_exercise_results er ON er.exercise_id = ex.exercise_id
        WHERE ex.status = 'completed' AND ex.deleted_at IS NULL
          AND ex.scheduled_date >= NOW() - INTERVAL '12 months'
        GROUP BY 1 ORDER BY 1`),

      // 2. Plans approaching review (within 30 days)
      safeQuery(`
        SELECT plan_id, title, next_review_date, status
        FROM "${schema}".bcp_plans
        WHERE deleted_at IS NULL AND status IN ('approved','active')
          AND next_review_date IS NOT NULL
          AND next_review_date BETWEEN NOW() AND NOW() + INTERVAL '30 days'
        ORDER BY next_review_date LIMIT 20`),

      // 3. RTO/RPO gap trend
      safeQuery(`
        SELECT TO_CHAR(ex.scheduled_date, 'YYYY-MM-DD') AS exercise_date,
               AVG(GREATEST(0, er.rto_actual_hours - rs.target_rto_hours))::numeric(10,1) AS rto_gap,
               AVG(GREATEST(0, er.rpo_actual_hours - rs.target_rpo_hours))::numeric(10,1) AS rpo_gap
        FROM "${schema}".bcp_exercise_results er
        JOIN "${schema}".bcp_exercises ex ON ex.exercise_id = er.exercise_id
        JOIN "${schema}".bcm_recovery_strategies rs ON rs.bcp_plan_id = ex.bcp_plan_id
        WHERE ex.status = 'completed' AND ex.deleted_at IS NULL AND rs.deleted_at IS NULL
        GROUP BY 1 ORDER BY 1 DESC LIMIT 12`),

      // 4. Dependency health: % of maps reviewed within 180 days
      safeQuery(`
        SELECT COUNT(*)::int AS total,
               COUNT(*) FILTER (WHERE last_reviewed_at IS NOT NULL AND last_reviewed_at >= NOW() - INTERVAL '180 days')::int AS fresh
        FROM "${schema}".bcm_dependency_maps WHERE deleted_at IS NULL`),

      // 5. Crisis readiness: % of active comms tested within 12 months
      safeQuery(`
        SELECT COUNT(*)::int AS total,
               COUNT(*) FILTER (WHERE last_reviewed_at IS NOT NULL AND last_reviewed_at >= NOW() - INTERVAL '365 days')::int AS tested
        FROM "${schema}".crisis_comm_plans WHERE status = 'active' AND deleted_at IS NULL`),

      // 6. Maturity trajectory
      safeQuery(`
        SELECT TO_CHAR(assessment_date, 'YYYY-MM-DD') AS date, overall_score AS score
        FROM "${schema}".bcm_maturity_assessments
        WHERE deleted_at IS NULL
        ORDER BY assessment_date DESC LIMIT 12`),

      // 7. Auto-generated tasks (from agent A11 + bcp-health-check)
      safeQuery(`
        SELECT COUNT(*)::int AS cnt FROM "${schema}".process_tasks
        WHERE trigger_source IN ('agent_A11','bcp-health-check')
          AND created_at >= NOW() - INTERVAL '30 days'`),
    ]);

  type SettledRows = PromiseFulfilledResult<{ rows: GenericRow[] }>;
  const fulfilled = (r: PromiseSettledResult<{ rows: GenericRow[] }>): { rows: GenericRow[] } =>
    r.status === 'fulfilled' ? r.value : { rows: [] };

  const depRows = getFirstRow(fulfilled(depHealth as SettledRows)) || { total: 0, fresh: 0 };
  const depScore = Number(depRows.total) > 0 ? Math.round((Number(depRows.fresh) / Number(depRows.total)) * 100) : 100;

  const crisisRows = getFirstRow(fulfilled(crisisReady as SettledRows)) || { total: 0, tested: 0 };
  const crisisScore = Number(crisisRows.total) > 0 ? Math.round((Number(crisisRows.tested) / Number(crisisRows.total)) * 100) : 100;

  const readiness = await getBCPReadinessScore(tenantId);

  return {

    exercisePassRateTrend: fulfilled(passRateTrend as SettledRows).rows as Record<string, unknown>[],
    plansApproachingReview: fulfilled(approachingReview as SettledRows).rows,
    rtoRpoGapTrend: fulfilled(rtoGap as SettledRows).rows.reverse() as any,
    dependencyHealthScore: depScore,
    crisisReadinessScore: crisisScore,
    maturityTrajectory: fulfilled(maturityHist as SettledRows).rows.reverse() as any,
    autoGeneratedTasks: Number(getFirstRow(fulfilled(autoTasks as SettledRows))?.cnt ?? 0),
    readinessScore: readiness.overall,
  };
}

// ── BCP Readiness Score (composite 0–100) ───────────────────────────────────

export async function getBCPReadinessScore(tenantId: string): Promise<{
  overall: number;
  dimensions: {
    planCurrency: number;
    exerciseEffectiveness: number;
    crisisPreparedness: number;
    dependencyResilience: number;
    maturityLevel: number;
  };
}> {
  const schema = tenantSchema(tenantId);

  const [planCurrencyQ, exerciseQ, crisisQ, depQ, maturityQ] = await Promise.allSettled([
    safeQuery(`
      SELECT COUNT(*)::int AS total,
             COUNT(*) FILTER (WHERE next_review_date IS NOT NULL AND next_review_date >= NOW())::int AS current_plans
      FROM "${schema}".bcp_plans WHERE status IN ('approved','active') AND deleted_at IS NULL`),
    safeQuery(`
      SELECT ROUND(AVG(CASE WHEN er.passed = TRUE THEN 100 ELSE 0 END))::int AS rate
      FROM "${schema}".bcp_exercise_results er
      JOIN "${schema}".bcp_exercises ex ON ex.exercise_id = er.exercise_id
      WHERE ex.status = 'completed' AND ex.deleted_at IS NULL`),
    safeQuery(`
      SELECT COUNT(*)::int AS total,
             COUNT(*) FILTER (WHERE last_reviewed_at >= NOW() - INTERVAL '365 days')::int AS tested
      FROM "${schema}".crisis_comm_plans WHERE status = 'active' AND deleted_at IS NULL`),
    safeQuery(`
      SELECT COUNT(*)::int AS total,
             COUNT(*) FILTER (WHERE last_reviewed_at >= NOW() - INTERVAL '180 days')::int AS fresh
      FROM "${schema}".bcm_dependency_maps WHERE deleted_at IS NULL`),
    safeQuery(`
      SELECT overall_score FROM "${schema}".bcm_maturity_assessments
      WHERE deleted_at IS NULL ORDER BY assessment_date DESC LIMIT 1`),
  ]);

  const fulfilledR = (r: PromiseSettledResult<{ rows: GenericRow[] }>): { rows: GenericRow[] } =>
    r.status === 'fulfilled' ? r.value : { rows: [] };

  const planRows = getFirstRow(fulfilledR(planCurrencyQ)) || { total: 0, current_plans: 0 };
  const planCurrency = Number(planRows.total) > 0 ? Math.round((Number(planRows.current_plans) / Number(planRows.total)) * 100) : 0;
  const exerciseEffectiveness = Number(getFirstRow(fulfilledR(exerciseQ))?.rate ?? 0);
  const crisisRows = getFirstRow(fulfilledR(crisisQ)) || { total: 0, tested: 0 };
  const crisisPreparedness = Number(crisisRows.total) > 0 ? Math.round((Number(crisisRows.tested) / Number(crisisRows.total)) * 100) : 0;
  const depRows = getFirstRow(fulfilledR(depQ)) || { total: 0, fresh: 0 };
  const dependencyResilience = Number(depRows.total) > 0 ? Math.round((Number(depRows.fresh) / Number(depRows.total)) * 100) : 0;
  const latestScore = Number(getFirstRow(fulfilledR(maturityQ))?.overall_score ?? 0);
  const maturityLevel = Math.round((latestScore / 5) * 100);

  const overall = Math.round(
    planCurrency * 0.20 + exerciseEffectiveness * 0.25 +
    crisisPreparedness * 0.20 + dependencyResilience * 0.15 + maturityLevel * 0.20
  );

  return { overall, dimensions: { planCurrency, exerciseEffectiveness, crisisPreparedness, dependencyResilience, maturityLevel } };
}

// ── BCP Health Check (proactive scheduled job) ──────────────────────────────

export async function runBCPHealthCheck(tenantId: string): Promise<{
  stalePlans: number; overdueExercises: number; upcomingDeadlines: number;
  tasksCreated: number; notificationsSent: number;
}> {
  const schema = tenantSchema(tenantId);
  let tasksCreated = 0, notificationsSent = 0, upcomingDeadlines = 0;

  // 1. Plans approaching review (within 14 days)
  const plansDue = await swallowDefault(EC.FALLBACK_QUERY, emptyResult(), safeQuery(`
    SELECT plan_id, title, next_review_date FROM "${schema}".bcp_plans
    WHERE deleted_at IS NULL AND status IN ('approved','active')
      AND next_review_date BETWEEN NOW() AND NOW() + INTERVAL '14 days'`
  ), { tenantId: tenantId, operation: 'query bcp_plans' });
  upcomingDeadlines += plansDue.rows.length;

  for (const plan of plansDue.rows) {
    try {

      const { createProcessTask } = await import('@dos/platform-core/workflows');
      await createProcessTask(tenantId, {
        title: `[BCP Health] Review upcoming: ${plan.title}`,
        description: `BCP plan "${plan.title}" is due for review on ${plan.next_review_date}. Complete review before deadline.`,
        taskType: 'verification', priority: 'medium',
        entityType: 'bcp_plan', entityId: plan.plan_id,
        assigneeRole: 'bcp_coordinator', dueInHours: 336,
        triggerSource: 'bcp-health-check',
      });
      tasksCreated++;
    } catch { /* best effort */ }
  }

  // 2. Exercises approaching (within 7 days)
  const exercisesDue = await swallowDefault(EC.FALLBACK_QUERY, emptyResult(), safeQuery(`
    SELECT exercise_id, title, scheduled_date FROM "${schema}".bcp_exercises
    WHERE deleted_at IS NULL AND status IN ('planned','scheduled')
      AND scheduled_date BETWEEN NOW() AND NOW() + INTERVAL '7 days'`
  ), { tenantId: tenantId, operation: 'query bcp_exercises' });
  upcomingDeadlines += exercisesDue.rows.length;

  for (const ex of exercisesDue.rows) {
    await swallow(EC.EVENT_BUS, eventBus.publish(({
          eventType: 'bcp.exercise_scheduled', tenantId,
          sourceService: 'bcp-health-check',
          entityType: 'bcp_exercise', entityId: ex.exercise_id,
          severity: 'info',
          payload: { title: ex.title, scheduledDate: ex.scheduled_date },
        } as any)), { tenantId, operation: 'eventBus:bcp.exercise_scheduled' });
    notificationsSent++;
  }

  // 3. BIA assessments approaching 1 year
  const staleBia = await swallowDefault(EC.FALLBACK_QUERY, emptyResult(), safeQuery(`
    SELECT bia_id, title FROM "${schema}".bia_assessments
    WHERE status = 'approved' AND deleted_at IS NULL
      AND created_at BETWEEN NOW() - INTERVAL '365 days' AND NOW() - INTERVAL '330 days'`
  ), { tenantId: tenantId, operation: 'query bia_assessments' });

  for (const bia of staleBia.rows) {
    try {

      const { createProcessTask } = await import('@dos/platform-core/workflows');
      await createProcessTask(tenantId, {
        title: `[BCP Health] BIA refresh needed: ${bia.title}`,
        description: `BIA "${bia.title}" is approaching 12 months old. Schedule a refresh.`,
        taskType: 'verification', priority: 'medium',
        entityType: 'bia_assessment', entityId: bia.bia_id,
        assigneeRole: 'bcp_coordinator', dueInHours: 336,
        triggerSource: 'bcp-health-check',
      });
      tasksCreated++;
    } catch { /* best effort */ }
  }

  // 4. Crisis comm plans approaching review
  const crisisReview = await swallowDefault(EC.FALLBACK_QUERY, emptyResult(), safeQuery(`
    SELECT plan_id, title FROM "${schema}".crisis_comm_plans
    WHERE status = 'active' AND deleted_at IS NULL
      AND next_review_date BETWEEN NOW() AND NOW() + INTERVAL '14 days'`
  ), { tenantId: tenantId, operation: 'query crisis_comm_plans' });

  for (const cc of crisisReview.rows) {
    await swallow(EC.EVENT_BUS, eventBus.publish(({
          eventType: 'bcp.crisis_readiness_low', tenantId,
          sourceService: 'bcp-health-check',
          entityType: 'crisis_comm_plan', entityId: cc.plan_id,
          severity: 'info',
          payload: { title: cc.title, reason: 'review_approaching' },
        } as any)), { tenantId, operation: 'eventBus:bcp.crisis_readiness_low' });
    notificationsSent++;
  }

  const stalePlansQ = await swallowDefault(EC.FALLBACK_QUERY, emptyResult([{ n: 0 }]), safeQuery(`
    SELECT COUNT(*)::int AS n FROM "${schema}".bcp_plans
    WHERE status IN ('approved','active') AND deleted_at IS NULL
      AND next_review_date IS NOT NULL AND next_review_date < NOW()`
  ), { tenantId: tenantId, operation: 'query bcp_plans' });

  const overdueExQ = await swallowDefault(EC.FALLBACK_QUERY, emptyResult([{ n: 0 }]), safeQuery(`
    SELECT COUNT(*)::int AS n FROM "${schema}".bcp_exercises
    WHERE status IN ('planned','scheduled') AND deleted_at IS NULL AND scheduled_date < NOW()`
  ), { tenantId: tenantId, operation: 'query bcp_plans' });

  await swallow(EC.EVENT_BUS, eventBus.publish(({
      eventType: 'bcp.health_check_completed', tenantId,
      sourceService: 'bcp-health-check', severity: 'info',
      payload: { stalePlans: Number(getFirstRow(stalePlansQ)?.n ?? 0), overdueExercises: Number(getFirstRow(overdueExQ)?.n ?? 0), upcomingDeadlines, tasksCreated, notificationsSent },
    } as any)), { tenantId, operation: 'eventBus:bcp.health_check_completed' });

  return {
    stalePlans: Number(getFirstRow(stalePlansQ)?.n ?? 0),
    overdueExercises: Number(getFirstRow(overdueExQ)?.n ?? 0),
    upcomingDeadlines, tasksCreated, notificationsSent,
  };
}
