import type { ModuleRouteGroup } from '../core/routing/route-registry.types';

export const aiGovernanceModuleRouteGroup: ModuleRouteGroup = {
  shell: () => import('../core/platform/shell/shell-host.component').then(m => m.ShellHostComponent),
  defaultRedirect: 'system-registry',
  children: {
    '': { redirectTo: 'system-registry', pathMatch: 'full' },
    'system-registry': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-system-registry.component').then(m => m.AiSystemRegistryComponent) },
    models: { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-models.component').then(m => m.AiModelsComponent) },
    'risk-classification': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-regulatory/ai-risk-classification.component').then(m => m.AiRiskClassificationComponent) },
    'eu-classification': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-regulatory/ai-eu-classification.component').then(m => m.AiEuClassificationComponent) },
    'impact-assessment': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-impact-assessment.component').then(m => m.AiImpactAssessmentComponent) },
    'human-oversight': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-human-oversight.component').then(m => m.AiHumanOversightComponent) },
    'hitl-enhanced': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-hitl-enhanced.component').then(m => m.AiHitlEnhancedComponent) },
    'automated-decisions': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-automated-decisions.component').then(m => m.AiAutomatedDecisionsComponent) },
    'go-no-go': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-go-no-go.component').then(m => m.AiGoNoGoComponent) },
    fairness: { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-fairness.component').then(m => m.AiFairnessComponent) },
    'explainability-dashboard': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-explainability-dashboard.component').then(m => m.AiExplainabilityDashboardComponent) },
    'model-drift': { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-model-drift.component').then(m => m.AiModelDriftComponent) },
    'model-provenance': { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-model-provenance.component').then(m => m.AiModelProvenanceComponent) },
    'model-risk-dashboard': { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-model-risk-dashboard.component').then(m => m.AiModelRiskDashboardComponent) },
    'performance-metrics': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-performance-metrics.component').then(m => m.AiPerformanceMetricsComponent) },
    'monitoring-plans': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-monitoring-plans.component').then(m => m.AiMonitoringPlansComponent) },
    'dataset-registry': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-dataset-registry.component').then(m => m.AiDatasetRegistryComponent) },
    'training-data-registry': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-training-data-registry.component').then(m => m.AiTrainingDataRegistryComponent) },
    'data-lineage': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-data-lineage.component').then(m => m.AiDataLineageComponent) },
    'data-sovereignty': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-data-sovereignty.component').then(m => m.AiDataSovereigntyComponent) },
    'technical-docs': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-supply-chain/ai-technical-docs.component').then(m => m.AiTechnicalDocsComponent) },
    aibom: { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-aibom.component').then(m => m.AiAibomComponent) },
    'chain-of-custody': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-chain-of-custody.component').then(m => m.AiChainOfCustodyComponent) },
    'conformity-assessments': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-conformity-assessments.component').then(m => m.AiConformityAssessmentsComponent) },
    'conformity-status': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-conformity-status.component').then(m => m.AiConformityStatusComponent) },
    declarations: { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-declarations.component').then(m => m.AiDeclarationsComponent) },
    'compliance-framework-dashboard': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-compliance-framework-dashboard.component').then(m => m.AiComplianceFrameworkDashboardComponent) },
    'governance-ops': { loadComponent: () => import('../features/ai-governance/pages/governance-dashboards/ai-governance-core/ai-governance-ops.component').then(m => m.AiGovernanceOpsComponent) },
    'governance-roles': { loadComponent: () => import('../features/ai-governance/pages/ai-governance-roles.component').then(m => m.AiGovernanceRolesComponent) },
    'ethics-board': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-regulatory/ai-ethics-board.component').then(m => m.AiEthicsBoardComponent) },
    stakeholders: { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-supply-chain/ai-stakeholders.component').then(m => m.AiStakeholdersComponent) },
    'maturity-scorecard': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-maturity-scorecard.component').then(m => m.AiMaturityScorecardComponent) },
    'board-summary': { loadComponent: () => import('../features/ai-governance/pages/governance-dashboards/ai-governance-core/ai-board-summary.component').then(m => m.AiBoardSummaryComponent) },
    agents: { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-agents.component').then(m => m.AiAgentsComponent) },
    'agent-sessions': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-agent-sessions.component').then(m => m.AiAgentSessionsComponent) },
    'agent-authority': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-agent-authority.component').then(m => m.AiAgentAuthorityComponent) },
    'agent-performance-dashboard': { loadComponent: () => import('../features/ai-governance/pages/agents-squads/ai-agents/ai-agent-performance-dashboard.component').then(m => m.AiAgentPerformanceDashboardComponent) },
    assets: { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-assets-registry/ai-assets.component').then(m => m.AiAssetsComponent) },
    bindings: { loadComponent: () => import('../features/ai-governance/pages/governance-dashboards/ai-governance-core/ai-bindings.component').then(m => m.AiBindingsComponent) },
    providers: { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-providers.component').then(m => m.AiProvidersComponent) },
    prompts: { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-prompts.component').then(m => m.AiPromptsComponent) },
    'alerts-killswitch': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-alerts-killswitch.component').then(m => m.AiAlertsKillswitchComponent) },
    audit: { loadComponent: () => import('../features/ai-governance/pages/governance-dashboards/ai-governance-core/ai-audit.component').then(m => m.AiAuditComponent) },
    'corrective-actions': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-corrective-actions.component').then(m => m.AiCorrectiveActionsComponent) },
    'serious-incidents': { loadComponent: () => import('../features/ai-governance/pages/governance-dashboards/ai-governance-core/ai-serious-incidents.component').then(m => m.AiSeriousIncidentsComponent) },
    'post-market-hub': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-supply-chain/ai-post-market-hub.component').then(m => m.AiPostMarketHubComponent) },
    complaints: { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-complaints.component').then(m => m.AiComplaintsComponent) },
    modifications: { loadComponent: () => import('../features/ai-governance/pages/model-management/ai-models/ai-modifications.component').then(m => m.AiModificationsComponent) },
    mismatches: { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-compliance/ai-mismatches.component').then(m => m.AiMismatchesComponent) },
    'regulatory-changes': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-regulatory/ai-regulatory-changes.component').then(m => m.AiRegulatoryChangesComponent) },
    enforcement: { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-regulatory/ai-enforcement.component').then(m => m.AiEnforcementComponent) },
    profiling: { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-profiling.component').then(m => m.AiProfilingComponent) },
    'privacy-dashboard': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-privacy-dashboard.component').then(m => m.AiPrivacyDashboardComponent) },
    'privacy-impact': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-privacy-impact.component').then(m => m.AiPrivacyImpactComponent) },
    'privacy-incidents': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-privacy-incidents.component').then(m => m.AiPrivacyIncidentsComponent) },
    'dpia-dashboard': { loadComponent: () => import('../features/ai-governance/pages/compliance-policy/ai-privacy/ai-dpia-dashboard.component').then(m => m.AiDPIADashboardComponent) },
    'supply-chain-hub': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-supply-chain/ai-supply-chain-hub.component').then(m => m.AiSupplyChainHubComponent) },
    'supply-agreements': { loadComponent: () => import('../features/ai-governance/pages/assets-registry/ai-supply-chain/ai-supply-agreements.component').then(m => m.AiSupplyAgreementsComponent) },
    'red-team-detail': { loadComponent: () => import('../features/ai-governance/pages/operations/ai-monitoring/ai-red-team-detail.component').then(m => m.AiRedTeamDetailComponent) },
    create:   { loadComponent: () => import('../shared/components/generic-module-create-dialog.component').then(m => m.GenericModuleCreateDialogComponent), data: { moduleCode: 'ai-governance' } },
    ':id':    { loadComponent: () => import('../shared/components/generic-module-detail.component').then(m => m.GenericModuleDetailComponent), data: { moduleCode: 'ai-governance' } },
    reports:  { loadComponent: () => import('../shared/components/generic-module-reports.component').then(m => m.GenericModuleReportsComponent), data: { moduleCode: 'ai-governance' } },
    lifecycle: { loadComponent: () => import('../shared/components/generic-module-lifecycle.component').then(m => m.GenericModuleLifecycleComponent), data: { moduleCode: 'ai-governance' } },
  },
};
