-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=access
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (35):
--   * access_profiles
--   * access_profiles_public
--   * access_snapshots
--   * active_sessions
--   * actors
--   * approval_matrix_rules_template
--   * authority_scope_bindings
--   * authorization_audit_log
--   * authz_decision_log
--   * decision_authorities
--   * delegation_chains
--   * delegation_policies
--   * delegations
--   * functional_roles
--   * invitations
--   * jwt_signing_keys
--   * lifecycle_auth_log_template
--   * login_attempts
--   * permissions
--   * refresh_token_families
--   * role_permissions
--   * scim_api_tokens
--   * security_events
--   * sessions
--   * sessions_dos
--   * sign_off_authorities_template
--   * sod_conflict_audit_template
--   * sod_rules
--   * token_blacklist
--   * user_access_profiles
--   * user_access_profiles_dos
--   * user_availability
--   * user_competencies
--   * user_mfa
--   * user_role_assignments
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/public/20260422_0005_create_platform_dauth_schema.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW platform_dauth.access_profiles                   AS SELECT * FROM dos.access_profiles;

CREATE OR REPLACE VIEW platform_dauth.approval_matrix_rules_template    AS SELECT * FROM dos.approval_matrix_rules_template;

CREATE OR REPLACE VIEW platform_dauth.authority_scope_bindings          AS SELECT * FROM dos.authority_scope_bindings;

CREATE OR REPLACE VIEW platform_dauth.authz_decision_log                AS SELECT * FROM dos.authz_decision_log;

CREATE OR REPLACE VIEW platform_dauth.decision_authorities              AS SELECT * FROM dos.decision_authorities;

CREATE OR REPLACE VIEW platform_dauth.delegation_chains                 AS SELECT * FROM dos.delegation_chains;

CREATE OR REPLACE VIEW platform_dauth.delegation_policies               AS SELECT * FROM dos.delegation_policies;

CREATE OR REPLACE VIEW platform_dauth.delegations                       AS SELECT * FROM dos.delegations;

CREATE OR REPLACE VIEW platform_dauth.functional_roles                  AS SELECT * FROM dos.functional_roles;

CREATE OR REPLACE VIEW platform_dauth.lifecycle_auth_log_template       AS SELECT * FROM dos.lifecycle_auth_log_template;

CREATE OR REPLACE VIEW platform_dauth.login_attempts                    AS SELECT * FROM dos.login_attempts;

CREATE OR REPLACE VIEW platform_dauth.permissions                       AS SELECT * FROM dos.permissions;

CREATE OR REPLACE VIEW platform_dauth.role_permissions                  AS SELECT * FROM dos.role_permissions;

CREATE OR REPLACE VIEW platform_dauth.sessions_dos                      AS SELECT * FROM dos.sessions;

CREATE OR REPLACE VIEW platform_dauth.sign_off_authorities_template     AS SELECT * FROM dos.sign_off_authorities_template;

CREATE OR REPLACE VIEW platform_dauth.sod_conflict_audit_template       AS SELECT * FROM dos.sod_conflict_audit_template;

CREATE OR REPLACE VIEW platform_dauth.sod_rules                         AS SELECT * FROM dos.sod_rules;

CREATE OR REPLACE VIEW platform_dauth.user_access_profiles_dos          AS SELECT * FROM dos.user_access_profiles;

CREATE OR REPLACE VIEW platform_dauth.user_availability                 AS SELECT * FROM dos.user_availability;

CREATE OR REPLACE VIEW platform_dauth.user_competencies                 AS SELECT * FROM dos.user_competencies;

CREATE OR REPLACE VIEW platform_dauth.user_mfa                          AS SELECT * FROM dos.user_mfa;

CREATE OR REPLACE VIEW platform_dauth.user_role_assignments             AS SELECT * FROM dos.user_role_assignments;

CREATE OR REPLACE VIEW platform_dauth.access_profiles_public            AS SELECT * FROM public.access_profiles;

CREATE OR REPLACE VIEW platform_dauth.access_snapshots                  AS SELECT * FROM public.access_snapshots;

CREATE OR REPLACE VIEW platform_dauth.active_sessions                   AS SELECT * FROM public.active_sessions;

CREATE OR REPLACE VIEW platform_dauth.actors                            AS SELECT * FROM public.actors;

CREATE OR REPLACE VIEW platform_dauth.authorization_audit_log           AS SELECT * FROM public.authorization_audit_log;

CREATE OR REPLACE VIEW platform_dauth.invitations                       AS SELECT * FROM public.invitations;

CREATE OR REPLACE VIEW platform_dauth.jwt_signing_keys                  AS SELECT * FROM public.jwt_signing_keys;

CREATE OR REPLACE VIEW platform_dauth.refresh_token_families            AS SELECT * FROM public.refresh_token_families;

CREATE OR REPLACE VIEW platform_dauth.scim_api_tokens                   AS SELECT * FROM public.scim_api_tokens;

CREATE OR REPLACE VIEW platform_dauth.security_events                   AS SELECT * FROM public.security_events;

CREATE OR REPLACE VIEW platform_dauth.sessions                          AS SELECT * FROM public.sessions;

CREATE OR REPLACE VIEW platform_dauth.token_blacklist                   AS SELECT * FROM public.token_blacklist;

CREATE OR REPLACE VIEW platform_dauth.user_access_profiles              AS SELECT * FROM public.user_access_profiles;
