-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=authz
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * authz_decision_log
--
-- Source migrations (immutable, 2):
--   * platform/dauth/migrations/public/002_expand_authz_decision_log.sql
--   * platform/dauth/migrations/public/011_dauth_enterprise_ledger.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_ip      ON dos.authz_decision_log (ip_address)    WHERE ip_address   IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_session ON dos.authz_decision_log (session_id)    WHERE session_id   IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_path    ON dos.authz_decision_log (request_path)  WHERE request_path IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_authz_decision_log_decision_id
    ON dos.authz_decision_log (decision_id);

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_correlation
    ON dos.authz_decision_log (correlation_id)
    WHERE correlation_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_reason_code
    ON dos.authz_decision_log (reason_code)
    WHERE reason_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_reason_codes
    ON dos.authz_decision_log USING GIN (reason_codes);

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_policy_version
    ON dos.authz_decision_log (policy_version)
    WHERE policy_version IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_model_version
    ON dos.authz_decision_log (model_version)
    WHERE model_version IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_authz_decision_log_engine_results
    ON dos.authz_decision_log USING GIN (engine_results);
