-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=email
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * email_verification_tokens
--
-- Source migrations (immutable, 2):
--   * platform/dauth/migrations/public/006_hash_email_verification_tokens.sql
--   * platform/dauth/migrations/public/20260418_0006_email_verification_tokens_jti.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_evt_token_hash
  ON public.email_verification_tokens (token_hash);

CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_pending_expiry
  ON public.email_verification_tokens (expires_at, used_at)
  WHERE used_at IS NULL;
