-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=event
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * event_outbox
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/public/20260423_0003_event_outbox.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS platform_dos.event_outbox (
  id            BIGSERIAL PRIMARY KEY,
  event_type    TEXT        NOT NULL,
  payload       JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at  TIMESTAMPTZ NULL,
  attempts      INT         NOT NULL DEFAULT 0,
  last_error    TEXT        NULL
);

CREATE INDEX IF NOT EXISTS ix_event_outbox_unprocessed
  ON platform_dos.event_outbox (id)
  WHERE processed_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_event_outbox_type_time
  ON platform_dos.event_outbox (event_type, created_at DESC);
