-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=jwt
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * jwt_signing_keys
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/public/004_jwt_signing_keys.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.jwt_signing_keys (
  kid         VARCHAR(64)   PRIMARY KEY,
  secret      TEXT          NOT NULL,
  algorithm   VARCHAR(10)   DEFAULT 'HS256',
  status      VARCHAR(20)   DEFAULT 'active',
  created_at  TIMESTAMPTZ   DEFAULT NOW(),
  retired_at  TIMESTAMPTZ,
  expires_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_jsk_status
  ON public.jwt_signing_keys (status);
