-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dauth scope=public function=scim
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dauth/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * scim_api_tokens
--
-- Source migrations (immutable, 1):
--   * platform/dauth/migrations/public/005_scim_api_tokens.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.scim_api_tokens (
  token_id    VARCHAR(64)   PRIMARY KEY,
  tenant_id   VARCHAR(16)   NOT NULL,
  token_hash  VARCHAR(256)  NOT NULL,
  label       VARCHAR(128)  DEFAULT 'SCIM Token',
  created_by  VARCHAR(64),
  created_at  TIMESTAMPTZ   DEFAULT NOW(),
  expires_at  TIMESTAMPTZ,
  revoked_at  TIMESTAMPTZ,
  last_used   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_scim_token_tenant
  ON public.scim_api_tokens (tenant_id)
  WHERE revoked_at IS NULL;
