// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const DOMAIN_ROUTES: RouteDefinition[] = [
  {
    id: "routes_incidents_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/incident/routes/incidents.routes",
    exportName: "default",
    mountPath: "/api/incidents",
    guards: { module: "incident" },
    order: 93,
  },
  {
    id: "routes_incident_advanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/incident/routes/incident-advanced.routes",
    exportName: "default",
    mountPath: "/api/incidents-advanced",
    guards: { module: "incident" },
    order: 94,
  },
  {
    id: "routes_bcp_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/bcp.routes",
    exportName: "default",
    mountPath: "/api/bcp",
    guards: { module: "bcp" },
    order: 95,
  },
  {
    id: "routes_bcm_advanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/bcm-advanced.routes",
    exportName: "default",
    mountPath: "/api/bcm-advanced",
    guards: { module: "bcp" },
    order: 96,
  },
  {
    id: "routes_business_services_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/business-services.routes",
    exportName: "default",
    mountPath: "/api/business-services",
    guards: { module: "bcp" },
    order: 97,
  },
  {
    id: "routes_bcm_crisis_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/bcm-crisis.routes",
    exportName: "default",
    mountPath: "/api/crisis-events",
    guards: { module: "bcp" },
    order: 98,
  },
  {
    id: "routes_bcm_findings_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/bcm-findings.routes",
    exportName: "default",
    mountPath: "/api/bcm-findings",
    guards: { module: "bcp" },
    order: 99,
  },
  {
    id: "routes_bcm_metrics_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/bcp/routes/bcm-metrics.routes",
    exportName: "default",
    mountPath: "/api/bcm-metrics",
    guards: { module: "bcp" },
    order: 100,
  },
  {
    id: "routes_foundation_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    exportName: "default",
    mountPath: "/api/foundation-governance",
    guards: { module: "foundation" },
    order: 179,
  },
  {
    id: "routes_foundation_roles_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    exportName: "default",
    mountPath: "/api/foundation/roles",
    guards: { module: "foundation" },
    order: 180,
  },
  {
    id: "routes_action_item_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/action/routes/action-item.routes",
    exportName: "default",
    mountPath: "/api/action-items",
    guards: { module: "action" },
    order: 228,
  },
  {
    id: "routes_remediation_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/remediation/routes/remediation.routes",
    exportName: "default",
    mountPath: "/api/remediation",
    guards: { module: "remediation" },
    order: 229,
  },
  {
    id: "modules_qiyas_qiyas_controller",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "controller",
    sourceFile: "modules/qiyas/qiyas.controller",
    exportName: "default",
    mountPath: "/api/qiyas",
    guards: { module: "qiyas", tier: "qiyas" },
    order: 247,
  },
  {
    id: "routes_qiyas_strategy_routes",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/qiyas/routes/qiyas-strategy.routes",
    exportName: "default",
    mountPath: "/api/qiyas-strategy",
    guards: { module: "qiyas" },
    order: 248,
    notes: "Strategy direction layer: objectives, themes, priorities, risk appetite, metrics, roadmap, scorecards, executive packs",
  },
  {
    id: "routes_assets_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/assets.routes",
    exportName: "default",
    mountPath: "/api/assets",
    guards: { module: "asset" },
    order: 264,
  },
  {
    id: "routes_common_objects_routes:assetRoutes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/integration/common-objects.routes",
    exportName: "assetRoutes",
    mountPath: "/api/assets-compat",
    guards: { module: "asset" },
    order: 265,
  },
  {
    id: "routes_vulnerabilities_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/vulnerabilities.routes",
    exportName: "default",
    mountPath: "/api/vulnerabilities",
    guards: { module: "asset" },
    order: 266,
  },
  {
    id: "routes_assets_routes__alias_api_assets_standalone",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/assets.routes",
    exportName: "default",
    mountPath: "/api/assets-standalone",
    guards: { module: "asset" },
    order: 312,
  },
  {
    id: "routes_asset_home_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-home.routes",
    exportName: "default",
    mountPath: "/api/asset-home",
    guards: { module: "asset" },
    order: 313,
  },
  {
    id: "routes_asset_applications_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-applications.routes",
    exportName: "default",
    mountPath: "/api/asset-applications",
    guards: { module: "asset" },
    order: 314,
  },
  {
    id: "routes_asset_services_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-services.routes",
    exportName: "default",
    mountPath: "/api/asset-services",
    guards: { module: "asset" },
    order: 315,
  },
  {
    id: "routes_asset_service_map_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-service-map.routes",
    exportName: "default",
    mountPath: "/api/asset-service-map",
    guards: { module: "asset" },
    order: 316,
  },
  {
    id: "routes_asset_dependencies_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-dependencies.routes",
    exportName: "default",
    mountPath: "/api/asset-dependencies",
    guards: { module: "asset" },
    order: 317,
  },
  {
    id: "routes_asset_criticality_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-criticality.routes",
    exportName: "default",
    mountPath: "/api/asset-criticality",
    guards: { module: "asset" },
    order: 318,
  },
  {
    id: "routes_asset_linkage_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-linkage.routes",
    exportName: "default",
    mountPath: "/api/asset-linkage",
    guards: { module: "asset" },
    order: 319,
  },
  {
    id: "routes_asset_ownership_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-ownership.routes",
    exportName: "default",
    mountPath: "/api/asset-ownership",
    guards: { module: "asset" },
    order: 320,
  },
  {
    id: "routes_asset_classification_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-classification.routes",
    exportName: "default",
    mountPath: "/api/asset-classification",
    guards: { module: "asset" },
    order: 321,
  },
  {
    id: "routes_asset_lifecycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/asset-lifecycle",
    guards: { module: "asset" },
    order: 322,
  },
  {
    id: "routes_asset_reports_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-reports.routes",
    exportName: "default",
    mountPath: "/api/asset-reports",
    guards: { module: "asset" },
    order: 323,
  },
  {
    id: "routes_asset_admin_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/asset/routes/asset-admin.routes",
    exportName: "default",
    mountPath: "/api/asset-admin",
    guards: { module: "asset" },
    order: 324,
  },
  {
    id: "autodiscovered:routes_foundation_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    exportName: "default",
    mountPath: "/api/foundation",
    guards: { module: "foundation" },
    order: 336,
    notes: "auto-discovered; no manifest entry",
  },
  {
    id: "routes_report_stream_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/reporting/routes/report/report-stream.routes",
    exportName: "default",
    mountPath: "/api/reports",
    guards: { module: "reporting" },
    order: 357,
    notes: "Real-time report streaming, natural language generation, and drill-down navigation",
  },

  // ── Sprint 2 Activation: wiring previously-orphaned modules ──────────────

  {
    id: "routes_inbox_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/inbox/routes/inbox.routes",
    exportName: "default",
    mountPath: "/api/inbox",
    guards: { module: "notification" },
    order: 358,
    notes: "User notification inbox — items, mark-read, bulk actions, priority routing",
  },
  {
    id: "routes_issues_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/issues/routes/issues.routes",
    exportName: "default",
    mountPath: "/api/issues",
    guards: { module: "issues" },
    order: 359,
    notes: "GRC issue tracking — CRUD, resolve, escalate, SLA, root-cause analysis",
  },
  {
    id: "routes_privacy_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/privacy/routes/privacy.routes",
    exportName: "default",
    mountPath: "/api/privacy",
    guards: { module: "privacy" },
    order: 360,
    notes: "Privacy module — DSRs, DPIA, consent management, breach reporting, cross-border",
  },
  {
    id: "routes_records_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/records/routes/records.routes",
    exportName: "default",
    mountPath: "/api/records",
    guards: { module: "records" },
    order: 361,
    notes: "Records management — retention, legal-hold, classification, disposal lifecycle",
  },
  {
    id: "routes_training_data_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/training/routes/training-data.routes",
    exportName: "default",
    mountPath: "/api/training",
    guards: { module: "training" },
    order: 362,
    notes: "Training programs, enrollments, completions, gap analysis, AI-assisted questionnaires",
  },
  {
    id: "routes_training_advanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/training/routes/training-advanced.routes",
    exportName: "default",
    mountPath: "/api/training-advanced",
    guards: { module: "training" },
    order: 363,
    notes: "Advanced training analytics, AI-guided paths, maturity scoring",
  },

  // ── Sprint 3 Activation: wiring orphan modules ──────────────

  {
    id: "routes_benchmarks_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/benchmarks/routes/benchmarks.routes",
    exportName: "default",
    mountPath: "/api/benchmarks",
    guards: { module: "benchmarks" },
    order: 370,
    notes: "Industry and regulatory benchmarking — maturity scoring, peer comparison",
  },
  {
    id: "routes_executive_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/executive/routes/executive.routes",
    exportName: "default",
    mountPath: "/api/executive",
    guards: { module: "executive" },
    order: 371,
    notes: "Executive dashboards and board-level reporting surfaces",
  },
  {
    id: "routes_mcp_tool_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/mcp/routes/mcp-tool.routes",
    exportName: "default",
    mountPath: "/api/mcp/tools",
    guards: { module: "mcp" },
    order: 372,
    notes: "MCP tool registry — list, invoke, and manage model-context-protocol tools",
  },
  {
    id: "routes_mcp_agent_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/mcp/routes/mcp-agent.routes",
    exportName: "default",
    mountPath: "/api/mcp/agents",
    guards: { module: "mcp" },
    order: 373,
    notes: "MCP agent management — list, configure, and execute model-context-protocol agents",
  },
  {
    id: "routes_mcp_approval_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/mcp/routes/mcp-approval.routes",
    exportName: "default",
    mountPath: "/api/mcp/approvals",
    guards: { module: "mcp" },
    order: 374,
    notes: "MCP approval workflow — human-in-the-loop gates for agent actions",
  },
  // ── Risk Module Routes ──
  {
    id: "routes_risk_admin_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-admin.routes",
    exportName: "default",
    mountPath: "/api/risk/admin",
    guards: { module: "risk" },
    order: 500,
  },
  {
    id: "routes_risk_review_approval_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-review-approval.routes",
    exportName: "default",
    mountPath: "/api/risk/reviews",
    guards: { module: "risk" },
    order: 501,
  },
  {
    id: "routes_risk_register_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk.routes",
    exportName: "default",
    mountPath: "/api/risk/register",
    guards: { module: "risk" },
    order: 502,
  },
  {
    id: "routes_risk_workspace_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-workspace.routes",
    exportName: "default",
    mountPath: "/api/risk/workspace",
    guards: { module: "risk" },
    order: 503,
  },
  {
    id: "routes_risk_treatments_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-treatments.routes",
    exportName: "default",
    mountPath: "/api/risk/treatments",
    guards: { module: "risk" },
    order: 504,
  },
  {
    id: "routes_risk_kri_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-kri.routes",
    exportName: "default",
    mountPath: "/api/risk/kri",
    guards: { module: "risk" },
    order: 505,
  },
  {
    id: "routes_risk_scoring_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-scoring.routes",
    exportName: "default",
    mountPath: "/api/risk/scoring",
    guards: { module: "risk" },
    order: 506,
  },
  {
    id: "routes_risk_dashboard_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/services/risk-dashboard.service",
    exportName: "default",
    mountPath: "/api/risk/dashboard",
    guards: { module: "risk" },
    order: 507,
  },
  {
    id: "routes_risk_diagnostics_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/diagnostics/risk-diagnostics.service",
    exportName: "default",
    mountPath: "/api/risk/diagnostics",
    guards: { module: "risk" },
    order: 508,
  },
  // ── Config Center ──
  {
    id: "routes_config_center_resolution_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-resolution.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 900,
  },
  {
    id: "routes_config_center_settings_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-settings.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 901,
  },
  {
    id: "routes_config_center_compare_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-compare.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 902,
  },
  {
    id: "routes_config_center_export_import_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-export-import.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 903,
  },
  {
    id: "routes_config_center_audit_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-audit.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 904,
  },
  {
    id: "routes_config_center_health_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/config-center/routes/config-health.routes",
    exportName: "default",
    mountPath: "/api/config-center",
    guards: { module: "config-center" as any },
    order: 905,
  },

  // ── Workflow Module Routes (MP-02) ──────────────────────────────
  {
    id: "routes_workflow_3level",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-3level.routes",
    exportName: "default",
    mountPath: "/api/workflow",
    guards: { module: "workflow" },
    order: 910,
    notes: "Barrel route: AI, controls, drafts, instance ops, monitoring, supervisor",
  },
  {
    id: "routes_workflows_crud",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/workflows.routes",
    exportName: "default",
    mountPath: "/api/workflows",
    guards: { module: "workflow" },
    order: 911,
    notes: "Primary workflow CRUD, execution, simulation, analytics, templates",
  },
  {
    id: "routes_approval_requests",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/approval-requests.routes",
    exportName: "default",
    mountPath: "/api/approval-requests",
    guards: { module: "workflow" },
    order: 912,
  },
  {
    id: "routes_approval_routing",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/approval-routing.routes",
    exportName: "default",
    mountPath: "/api/approval-routing",
    guards: { module: "workflow" },
    order: 913,
  },
  {
    id: "routes_autonomous_workflow",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/autonomous-workflow.routes",
    exportName: "default",
    mountPath: "/api/autonomous-workflows",
    guards: { module: "workflow" },
    order: 914,
  },
  {
    id: "routes_cooperative_workflows",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/cooperative-workflows.routes",
    exportName: "default",
    mountPath: "/api/cooperative-workflows",
    guards: { module: "workflow" },
    order: 915,
  },
  {
    id: "routes_workflow_journey",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/journey.routes",
    exportName: "default",
    mountPath: "/api/journey",
    guards: { module: "workflow" },
    order: 916,
  },
  {
    id: "routes_module_workflow",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/module-workflow.routes",
    exportName: "default",
    mountPath: "/api/module-workflows",
    guards: { module: "workflow" },
    order: 917,
  },
  {
    id: "routes_process_tasks",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/process-tasks.routes",
    exportName: "default",
    mountPath: "/api/process-tasks",
    guards: { module: "workflow" },
    order: 918,
  },
  {
    id: "routes_review_cycle",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/review-cycle.routes",
    exportName: "default",
    mountPath: "/api/review-cycle",
    guards: { module: "workflow" },
    order: 919,
  },
  {
    id: "routes_task_board",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/task-board.routes",
    exportName: "default",
    mountPath: "/api/task-board",
    guards: { module: "workflow" },
    order: 920,
  },
  {
    id: "routes_work_items",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/work-items.routes",
    exportName: "default",
    mountPath: "/api/work-items",
    guards: { module: "workflow" },
    order: 921,
  },
  {
    id: "routes_bulk_tasks",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/bulk-tasks.routes",
    exportName: "default",
    mountPath: "/api/workflow-bulk-tasks",
    guards: { module: "workflow" },
    order: 922,
  },
  {
    id: "routes_module_ai_orchestrator",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/module-ai-orchestrator.routes",
    exportName: "default",
    mountPath: "/api/module-ai-orchestrator",
    guards: { module: "workflow" },
    order: 923,
  },
  {
    id: "routes_workflow_admin",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-admin.routes",
    exportName: "default",
    mountPath: "/api/workflow/admin",
    guards: { module: "workflow" },
    order: 924,
  },
  {
    id: "routes_workflow_advanced",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-advanced.routes",
    exportName: "default",
    mountPath: "/api/workflow/advanced",
    guards: { module: "workflow" },
    order: 925,
  },
  {
    id: "routes_workflow_agent",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-agent.routes",
    exportName: "default",
    mountPath: "/api/workflow/agents",
    guards: { module: "workflow" },
    order: 926,
  },
  {
    id: "routes_workflow_attachments",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-attachments.routes",
    exportName: "default",
    mountPath: "/api/workflow/attachments",
    guards: { module: "workflow" },
    order: 927,
  },
  {
    id: "routes_workflow_chain",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-chain.routes",
    exportName: "default",
    mountPath: "/api/workflow-chains",
    guards: { module: "workflow" },
    order: 928,
  },
  {
    id: "routes_workflow_comments",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-comments.routes",
    exportName: "default",
    mountPath: "/api/workflow/comments",
    guards: { module: "workflow" },
    order: 929,
  },
  {
    id: "routes_workflow_enterprise",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-enterprise.routes",
    exportName: "default",
    mountPath: "/api/workflow-enterprise",
    guards: { module: "workflow" },
    order: 930,
  },
  {
    id: "routes_workflow_ext",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-ext.routes",
    exportName: "default",
    mountPath: "/api/workflow-ext",
    guards: { module: "workflow" },
    order: 931,
  },
  {
    id: "routes_workflow_import_export",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-import-export.routes",
    exportName: "default",
    mountPath: "/api/workflow-import-export",
    guards: { module: "workflow" },
    order: 932,
  },
  {
    id: "routes_workflow_lookups",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-lookups.routes",
    exportName: "default",
    mountPath: "/api/workflow/lookups",
    guards: { module: "workflow" },
    order: 933,
  },
  {
    id: "routes_workflow_templates",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow/workflow-templates.routes",
    exportName: "default",
    mountPath: "/api/workflow-templates",
    guards: { module: "workflow" },
    order: 934,
  },
  {
    id: "routes_workflow_diagnostics",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow-diagnostics.routes",
    exportName: "default",
    mountPath: "/api/workflow/diagnostics",
    guards: { module: "workflow" },
    order: 935,
  },
  {
    id: "routes_workflow_profile",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/workflow-profile.routes",
    exportName: "default",
    mountPath: "/api/workflow-profile",
    guards: { module: "workflow" },
    order: 936,
  },
  
  // ── Sprint 4 Activation: Vendor Enterprise Module ──────────────
  {
    id: "routes_vendors_core",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendors.routes",
    exportName: "default",
    mountPath: "/api/vendors",
    guards: { module: "vendor" },
    order: 940,
    notes: "Core vendor lifecycle, SLA monitoring, assessments",
  },
  {
    id: "routes_vendor_admin",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-admin.routes",
    exportName: "default",
    mountPath: "/api/vendor/admin",
    guards: { module: "vendor" },
    order: 941,
  },
  {
    id: "routes_vendor_engagements",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-engagements.routes",
    exportName: "default",
    mountPath: "/api/vendor-engagements",
    guards: { module: "vendor" },
    order: 942,
  },
  {
    id: "routes_vendor_portal",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-portal.routes",
    exportName: "default",
    mountPath: "/api/vendor-portal",
    guards: { module: "vendor" },
    order: 943,
  },
  {
    id: 'routes_action_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/action/routes/action.routes',
    exportName: 'default',
    mountPath: '/api/action',
    guards: { module: 'action' },
    order: 950,
  },
  {
    id: 'routes_agrc_engine_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/agrc-engine/routes/agrc-engine.routes',
    exportName: 'default',
    mountPath: '/api/agrc-engine',
    guards: { module: 'agrc-engine' },
    order: 950,
  },
  {
    id: 'routes_ai_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/ai/routes/ai.routes',
    exportName: 'default',
    mountPath: '/api/ai',
    guards: { module: 'ai' },
    order: 950,
  },
  {
    id: 'routes_ai_governance_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/ai-governance/routes/ai-governance.routes',
    exportName: 'default',
    mountPath: '/api/ai-governance',
    guards: { module: 'ai-governance' },
    order: 950,
  },
  {
    id: 'routes_analytics_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/analytics/routes/analytics.routes',
    exportName: 'default',
    mountPath: '/api/analytics',
    guards: { module: 'analytics' },
    order: 950,
  },
  {
    id: 'routes_asset_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/asset/routes/asset.routes',
    exportName: 'default',
    mountPath: '/api/asset',
    guards: { module: 'asset' },
    order: 950,
  },
  {
    id: 'routes_attestation_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/attestation/routes/attestation.routes',
    exportName: 'default',
    mountPath: '/api/attestation',
    guards: { module: 'attestation' },
    order: 950,
  },
  {
    id: 'routes_audit_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/audit/routes/audit.routes',
    exportName: 'default',
    mountPath: '/api/audit',
    guards: { module: 'audit' },
    order: 950,
  },
  {
    id: 'routes_bcp_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/bcp/routes/bcp.routes',
    exportName: 'default',
    mountPath: '/api/bcp',
    guards: { module: 'bcp' },
    order: 950,
  },
  {
    id: 'routes_benchmarks_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/benchmarks/routes/benchmarks.routes',
    exportName: 'default',
    mountPath: '/api/benchmarks',
    guards: { module: 'benchmarks' },
    order: 950,
  },
  {
    id: 'routes_compliance_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/compliance/routes/compliance.routes',
    exportName: 'default',
    mountPath: '/api/compliance',
    guards: { module: 'compliance' },
    order: 950,
  },
  {
    id: 'routes_controls_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/controls/routes/controls.routes',
    exportName: 'default',
    mountPath: '/api/controls',
    guards: { module: 'controls' },
    order: 950,
  },
  {
    id: 'routes_dashboard_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/dashboard/routes/dashboard.routes',
    exportName: 'default',
    mountPath: '/api/dashboard',
    guards: { module: 'dashboard' },
    order: 950,
  },
  {
    id: 'routes_dashboard_editor_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/dashboard-editor/routes/dashboard-editor.routes',
    exportName: 'default',
    mountPath: '/api/dashboard-editor',
    guards: { module: 'dashboard-editor' },
    order: 950,
  },
  {
    id: 'routes_dora_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/dora/routes/dora.routes',
    exportName: 'default',
    mountPath: '/api/dora',
    guards: { module: 'dora' },
    order: 950,
  },
  {
    id: 'routes_evidence_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/evidence/routes/evidence.routes',
    exportName: 'default',
    mountPath: '/api/evidence',
    guards: { module: 'evidence' },
    order: 950,
  },
  {
    id: 'routes_exception_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/exception/routes/exception.routes',
    exportName: 'default',
    mountPath: '/api/exception',
    guards: { module: 'exception' },
    order: 950,
  },
  {
    id: 'routes_executive_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/executive/routes/executive.routes',
    exportName: 'default',
    mountPath: '/api/executive',
    guards: { module: 'executive' },
    order: 950,
  },
  {
    id: 'routes_fitch_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/fitch/routes/fitch.routes',
    exportName: 'default',
    mountPath: '/api/fitch',
    guards: { module: 'fitch' },
    order: 950,
  },
  {
    id: 'routes_governance_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/governance/routes/governance.routes',
    exportName: 'default',
    mountPath: '/api/governance',
    guards: { module: 'governance' },
    order: 950,
  },
  {
    id: 'routes_governance_ai_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/governance-ai/routes/governance-ai.routes',
    exportName: 'default',
    mountPath: '/api/governance-ai',
    guards: { module: 'governance-ai' },
    order: 950,
  },
  {
    id: 'routes_governance_os_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/governance-os/routes/governance-os.routes',
    exportName: 'default',
    mountPath: '/api/governance-os',
    guards: { module: 'governance-os' },
    order: 950,
  },
  {
    id: 'routes_grc_query_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/grc-query/routes/grc-query.routes',
    exportName: 'default',
    mountPath: '/api/grc-query',
    guards: { module: 'grc-query' },
    order: 950,
  },
  {
    id: 'routes_inbox_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/inbox/routes/inbox.routes',
    exportName: 'default',
    mountPath: '/api/inbox',
    guards: { module: 'inbox' },
    order: 950,
  },
  {
    id: 'routes_incident_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/incident/routes/incident.routes',
    exportName: 'default',
    mountPath: '/api/incident',
    guards: { module: 'incident' },
    order: 950,
  },
  {
    id: 'routes_integrations_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/integrations/routes/integrations.routes',
    exportName: 'default',
    mountPath: '/api/integrations',
    guards: { module: 'integrations' },
    order: 950,
  },
  {
    id: 'routes_issues_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/issues/routes/issues.routes',
    exportName: 'default',
    mountPath: '/api/issues',
    guards: { module: 'issues' },
    order: 950,
  },
  {
    id: 'routes_journey_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/journey/routes/journey.routes',
    exportName: 'default',
    mountPath: '/api/journey',
    guards: { module: 'journey' },
    order: 950,
  },
  {
    id: 'routes_knowledge_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/knowledge/routes/knowledge.routes',
    exportName: 'default',
    mountPath: '/api/knowledge',
    guards: { module: 'knowledge' },
    order: 950,
  },
  {
    id: 'routes_ksa_regulatory_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/ksa-regulatory/routes/ksa-regulatory.routes',
    exportName: 'default',
    mountPath: '/api/ksa-regulatory',
    guards: { module: 'ksa-regulatory' },
    order: 950,
  },
  {
    id: 'routes_local_knowledge_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/local-knowledge/routes/local-knowledge.routes',
    exportName: 'default',
    mountPath: '/api/local-knowledge',
    guards: { module: 'local-knowledge' },
    order: 950,
  },
  {
    id: 'routes_mcp_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/mcp/routes/mcp.routes',
    exportName: 'default',
    mountPath: '/api/mcp',
    guards: { module: 'mcp' },
    order: 950,
  },
  {
    id: 'routes_mobile_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/mobile/routes/mobile.routes',
    exportName: 'default',
    mountPath: '/api/mobile',
    guards: { module: 'mobile' },
    order: 950,
  },
  {
    id: 'routes_notification_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/notification/routes/notification.routes',
    exportName: 'default',
    mountPath: '/api/notification',
    guards: { module: 'notification' },
    order: 950,
  },
  {
    id: 'routes_onboarding_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/onboarding/routes/onboarding.routes',
    exportName: 'default',
    mountPath: '/api/onboarding',
    guards: { module: 'onboarding' },
    order: 950,
  },
  {
    id: 'routes_operating_cockpit_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/operating-cockpit/routes/operating-cockpit.routes',
    exportName: 'default',
    mountPath: '/api/operating-cockpit',
    guards: { module: 'operating-cockpit' },
    order: 950,
  },
  {
    id: 'routes_packs_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/packs/routes/packs.routes',
    exportName: 'default',
    mountPath: '/api/packs',
    guards: { module: 'packs' },
    order: 950,
  },
  {
    id: 'routes_playbooks_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/playbooks/routes/playbooks.routes',
    exportName: 'default',
    mountPath: '/api/playbooks',
    guards: { module: 'playbooks' },
    order: 950,
  },
  {
    id: 'routes_policy_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/policy/routes/policy.routes',
    exportName: 'default',
    mountPath: '/api/policy',
    guards: { module: 'policy' },
    order: 950,
  },
  {
    id: 'routes_portals_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/portals/routes/portals.routes',
    exportName: 'default',
    mountPath: '/api/portals',
    guards: { module: 'portals' },
    order: 950,
  },
  {
    id: 'routes_privacy_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/privacy/routes/privacy.routes',
    exportName: 'default',
    mountPath: '/api/privacy',
    guards: { module: 'privacy' },
    order: 950,
  },
  {
    id: 'routes_proactive_leadership_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/proactive-leadership/routes/proactive-leadership.routes',
    exportName: 'default',
    mountPath: '/api/proactive-leadership',
    guards: { module: 'proactive-leadership' },
    order: 950,
  },
  {
    id: 'routes_qiyas_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/qiyas/routes/qiyas.routes',
    exportName: 'default',
    mountPath: '/api/qiyas',
    guards: { module: 'qiyas' },
    order: 950,
  },
  {
    id: 'routes_records_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/records/routes/records.routes',
    exportName: 'default',
    mountPath: '/api/records',
    guards: { module: 'records' },
    order: 950,
  },
  {
    id: 'routes_remediation_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/remediation/routes/remediation.routes',
    exportName: 'default',
    mountPath: '/api/remediation',
    guards: { module: 'remediation' },
    order: 950,
  },
  {
    id: 'routes_reporting_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/reporting/routes/reporting.routes',
    exportName: 'default',
    mountPath: '/api/reporting',
    guards: { module: 'reporting' },
    order: 950,
  },
  {
    id: 'routes_risk_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/risk/routes/risk.routes',
    exportName: 'default',
    mountPath: '/api/risk',
    guards: { module: 'risk' },
    order: 950,
  },
  {
    id: 'routes_team_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/team/routes/team.routes',
    exportName: 'default',
    mountPath: '/api/team',
    guards: { module: 'team' },
    order: 950,
  },
  {
    id: 'routes_training_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/training/routes/training.routes',
    exportName: 'default',
    mountPath: '/api/training',
    guards: { module: 'training' },
    order: 950,
  },
  {
    id: 'routes_vendor_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/vendor/routes/vendor.routes',
    exportName: 'default',
    mountPath: '/api/vendor',
    guards: { module: 'vendor' },
    order: 950,
  },
  {
    id: 'routes_widgets_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/widgets/routes/widgets.routes',
    exportName: 'default',
    mountPath: '/api/widgets',
    guards: { module: 'widgets' },
    order: 950,
  },
  {
    id: 'routes_workflow_core',
    productKey: 'shahin-ai',
    ownerKind: 'module',
    sourceKind: 'defaultExport',
    sourceFile: 'modules/workflow/routes/workflow.routes',
    exportName: 'default',
    mountPath: '/api/workflow',
    guards: { module: 'workflow' },
    order: 950,
  },
];
