// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const RISK_ROUTES: RouteDefinition[] = [
  {
    id: "routes_risk_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk.routes",
    exportName: "default",
    mountPath: "/api/risks",
    guards: { module: "risk" },
    order: 37,
  },
  {
    id: "routes_risk_workspace_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-workspace.routes",
    exportName: "default",
    mountPath: "/api/risk-ws",
    guards: { module: "risk" },
    order: 38,
  },
  {
    id: "routes_risk_smart_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-smart.routes",
    exportName: "default",
    mountPath: "/api/risk-smart",
    guards: { module: "risk" },
    order: 39,
  },
  {
    id: "routes_risk_metrics_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-metrics.routes",
    exportName: "default",
    mountPath: "/api/risk-metrics",
    guards: { module: "risk" },
    order: 40,
  },
  {
    id: "routes_risk_scoring_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-scoring.routes",
    exportName: "default",
    mountPath: "/api/risk-scoring",
    guards: { module: "risk" },
    order: 41,
  },
  {
    id: "routes_risk_trends_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-trends.routes",
    exportName: "default",
    mountPath: "/api/risk-trends",
    guards: { module: "risk" },
    order: 42,
  },
  {
    id: "routes_risk_quantification_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/risk-quantification.routes",
    exportName: "default",
    mountPath: "/api/risk-quantification",
    guards: { module: "risk" },
    order: 43,
  },
  {
    id: "routes_monte_carlo_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/monte-carlo.routes",
    exportName: "default",
    mountPath: "/api/monte-carlo",
    guards: { module: "risk" },
    order: 44,
    apiOnly: "service-api",
  },
];
