"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tenantUserCacheKey = exports.tenantCacheKey = exports.disconnectRedis = exports.redisConnected = exports.isRedisHealthy = exports.connectRedis = exports.getRedisSubscriber = exports.getRedis = exports.resetColumnExistsCache = exports.columnExists = exports.assertHasRows = exports.getFirstRowOrThrow = exports.getFirstRow = exports.masterGetFirst = exports.masterQuery = exports.withTransactionIsolation = exports.withTransaction = exports.summarizeTenantMigrationsHealth = exports.backfillTrackerByExistence = exports.runTenantMigrationsTracked = exports.discoverTenantMigrations = exports.grantTenantSchemaPrivileges = exports.createTenantSchemaWithGrants = exports.withTenantClient = exports.getTenantClient = exports.tenantScopedQuery = exports.tenantSchema = exports.assertTenantId = exports.setDbMetricsHook = exports.emptyResult = exports.withPoolClient = exports.withClient = exports.getClient = exports.safeQueryWithClient = exports.safeQuery = exports.query = exports.closeAllServicePools = exports.closeServicePool = exports.createServicePool = exports.closePool = exports.getPool = exports.pool = exports.buildPgSslConfig = exports.buildSslFromConfig = exports.resetPlatformDbConfigCache = exports.getConnectionString = exports.getPlatformConnectionConfig = exports.toErrorMessage = exports.getDbLogger = exports.setDbLogger = void 0;
var logger_1 = require("./logger");
Object.defineProperty(exports, "setDbLogger", { enumerable: true, get: function () { return logger_1.setDbLogger; } });
Object.defineProperty(exports, "getDbLogger", { enumerable: true, get: function () { return logger_1.getDbLogger; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "toErrorMessage", { enumerable: true, get: function () { return errors_1.toErrorMessage; } });
var config_1 = require("./config");
Object.defineProperty(exports, "getPlatformConnectionConfig", { enumerable: true, get: function () { return config_1.getPlatformConnectionConfig; } });
Object.defineProperty(exports, "getConnectionString", { enumerable: true, get: function () { return config_1.getConnectionString; } });
Object.defineProperty(exports, "resetPlatformDbConfigCache", { enumerable: true, get: function () { return config_1.resetPlatformDbConfigCache; } });
Object.defineProperty(exports, "buildSslFromConfig", { enumerable: true, get: function () { return config_1.buildSslFromConfig; } });
Object.defineProperty(exports, "buildPgSslConfig", { enumerable: true, get: function () { return config_1.buildPgSslConfig; } });
var pool_1 = require("./pool");
Object.defineProperty(exports, "pool", { enumerable: true, get: function () { return pool_1.pool; } });
Object.defineProperty(exports, "getPool", { enumerable: true, get: function () { return pool_1.getPool; } });
Object.defineProperty(exports, "closePool", { enumerable: true, get: function () { return pool_1.closePool; } });
Object.defineProperty(exports, "createServicePool", { enumerable: true, get: function () { return pool_1.createServicePool; } });
Object.defineProperty(exports, "closeServicePool", { enumerable: true, get: function () { return pool_1.closeServicePool; } });
Object.defineProperty(exports, "closeAllServicePools", { enumerable: true, get: function () { return pool_1.closeAllServicePools; } });
var query_1 = require("./query");
Object.defineProperty(exports, "query", { enumerable: true, get: function () { return query_1.query; } });
Object.defineProperty(exports, "safeQuery", { enumerable: true, get: function () { return query_1.safeQuery; } });
Object.defineProperty(exports, "safeQueryWithClient", { enumerable: true, get: function () { return query_1.safeQueryWithClient; } });
Object.defineProperty(exports, "getClient", { enumerable: true, get: function () { return query_1.getClient; } });
Object.defineProperty(exports, "withClient", { enumerable: true, get: function () { return query_1.withClient; } });
Object.defineProperty(exports, "withPoolClient", { enumerable: true, get: function () { return query_1.withPoolClient; } });
Object.defineProperty(exports, "emptyResult", { enumerable: true, get: function () { return query_1.emptyResult; } });
Object.defineProperty(exports, "setDbMetricsHook", { enumerable: true, get: function () { return query_1.setDbMetricsHook; } });
var tenant_1 = require("./tenant");
Object.defineProperty(exports, "assertTenantId", { enumerable: true, get: function () { return tenant_1.assertTenantId; } });
Object.defineProperty(exports, "tenantSchema", { enumerable: true, get: function () { return tenant_1.tenantSchema; } });
Object.defineProperty(exports, "tenantScopedQuery", { enumerable: true, get: function () { return tenant_1.tenantScopedQuery; } });
Object.defineProperty(exports, "getTenantClient", { enumerable: true, get: function () { return tenant_1.getTenantClient; } });
Object.defineProperty(exports, "withTenantClient", { enumerable: true, get: function () { return tenant_1.withTenantClient; } });
Object.defineProperty(exports, "createTenantSchemaWithGrants", { enumerable: true, get: function () { return tenant_1.createTenantSchemaWithGrants; } });
Object.defineProperty(exports, "grantTenantSchemaPrivileges", { enumerable: true, get: function () { return tenant_1.grantTenantSchemaPrivileges; } });
var tenant_migrations_1 = require("./tenant-migrations");
Object.defineProperty(exports, "discoverTenantMigrations", { enumerable: true, get: function () { return tenant_migrations_1.discoverTenantMigrations; } });
Object.defineProperty(exports, "runTenantMigrationsTracked", { enumerable: true, get: function () { return tenant_migrations_1.runTenantMigrationsTracked; } });
Object.defineProperty(exports, "backfillTrackerByExistence", { enumerable: true, get: function () { return tenant_migrations_1.backfillTrackerByExistence; } });
var tenant_migrations_health_1 = require("./tenant-migrations-health");
Object.defineProperty(exports, "summarizeTenantMigrationsHealth", { enumerable: true, get: function () { return tenant_migrations_health_1.summarizeTenantMigrationsHealth; } });
var transaction_1 = require("./transaction");
Object.defineProperty(exports, "withTransaction", { enumerable: true, get: function () { return transaction_1.withTransaction; } });
Object.defineProperty(exports, "withTransactionIsolation", { enumerable: true, get: function () { return transaction_1.withTransactionIsolation; } });
var master_1 = require("./master");
Object.defineProperty(exports, "masterQuery", { enumerable: true, get: function () { return master_1.masterQuery; } });
Object.defineProperty(exports, "masterGetFirst", { enumerable: true, get: function () { return master_1.masterGetFirst; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "getFirstRow", { enumerable: true, get: function () { return utils_1.getFirstRow; } });
Object.defineProperty(exports, "getFirstRowOrThrow", { enumerable: true, get: function () { return utils_1.getFirstRowOrThrow; } });
Object.defineProperty(exports, "assertHasRows", { enumerable: true, get: function () { return utils_1.assertHasRows; } });
Object.defineProperty(exports, "columnExists", { enumerable: true, get: function () { return utils_1.columnExists; } });
Object.defineProperty(exports, "resetColumnExistsCache", { enumerable: true, get: function () { return utils_1.resetColumnExistsCache; } });
var redis_1 = require("./redis");
Object.defineProperty(exports, "getRedis", { enumerable: true, get: function () { return redis_1.getRedis; } });
Object.defineProperty(exports, "getRedisSubscriber", { enumerable: true, get: function () { return redis_1.getRedisSubscriber; } });
Object.defineProperty(exports, "connectRedis", { enumerable: true, get: function () { return redis_1.connectRedis; } });
Object.defineProperty(exports, "isRedisHealthy", { enumerable: true, get: function () { return redis_1.isRedisHealthy; } });
Object.defineProperty(exports, "redisConnected", { enumerable: true, get: function () { return redis_1.redisConnected; } });
Object.defineProperty(exports, "disconnectRedis", { enumerable: true, get: function () { return redis_1.disconnectRedis; } });
Object.defineProperty(exports, "tenantCacheKey", { enumerable: true, get: function () { return redis_1.tenantCacheKey; } });
Object.defineProperty(exports, "tenantUserCacheKey", { enumerable: true, get: function () { return redis_1.tenantUserCacheKey; } });
//# sourceMappingURL=index.js.map