import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const GOVERNANCE_WIDGETS: WidgetManifest[] = [
  // ── Reality Check ──
  {
    id: 'governance.grc_time_loop',
    key: 'grc_time_loop',
    title: 'GRC Time-Loop',
    titleAr: 'الدوران السنوي',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/lifecycle-ops/grc-time-loop.widget').then(m => m.GrcTimeLoopWidget),
    icon: '🔄',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.improvement_illusion',
    key: 'improvement_illusion',
    title: 'Improvement Illusion',
    titleAr: 'وهم التحسن',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/improvement-illusion.widget').then(m => m.ImprovementIllusionWidget),
    icon: '🪞',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'governance.silent_controls',
    key: 'silent_controls',
    title: 'Silent Controls',
    titleAr: 'ضوابط صامتة',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/control/silent-controls.widget').then(m => m.SilentControlsWidget),
    icon: '🤫',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.audit_dejavu',
    key: 'audit_dejavu',
    title: 'Audit Déjà Vu',
    titleAr: 'تدقيق متكرر',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/audit-dejavu.widget').then(m => m.AuditDejavuWidget),
    icon: '♻️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.risk_denial',
    key: 'risk_denial',
    title: 'Risk Denial',
    titleAr: 'إنكار المخاطر',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-denial.widget').then(m => m.RiskDenialWidget),
    icon: '🙈',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  // ── Organizational Memory ──
  {
    id: 'governance.org_amnesia',
    key: 'org_amnesia',
    title: 'Organizational Amnesia',
    titleAr: 'فقدان الذاكرة المؤسسي',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/org-amnesia.widget').then(m => m.OrgAmnesiaWidget),
    icon: '🧠',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.knowledge_in_people',
    key: 'knowledge_in_people',
    title: 'Knowledge-in-People',
    titleAr: 'المعرفة في الأفراد',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/knowledge-in-people.widget').then(m => m.KnowledgeInPeopleWidget),
    icon: '👤',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'governance.decision_trace',
    key: 'decision_trace',
    title: 'Decision Trace',
    titleAr: 'تتبع القرارات',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/governance/decision-trace.widget').then(m => m.DecisionTraceWidget),
    icon: '🔗',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.cultural_drift',
    key: 'cultural_drift',
    title: 'Cultural Drift',
    titleAr: 'انحراف الثقافة',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/cultural-drift.widget').then(m => m.CulturalDriftWidget),
    icon: '🌊',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  // ── Lifecycle Intelligence ──
  {
    id: 'governance.control_aging',
    key: 'control_aging',
    title: 'Control Aging',
    titleAr: 'تقادم الضوابط',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/control/control-aging.widget').then(m => m.ControlAgingWidget),
    icon: '⏳',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'governance.lifecycle_bottleneck',
    key: 'lifecycle_bottleneck',
    title: 'Lifecycle Bottleneck',
    titleAr: 'اختناق دورة الحياة',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/lifecycle-ops/lifecycle-bottleneck.widget').then(m => m.LifecycleBottleneckWidget),
    icon: '🚧',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'governance.zombie_controls',
    key: 'zombie_controls',
    title: 'Zombie Controls',
    titleAr: 'ضوابط ميتة',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/control/zombie-controls.widget').then(m => m.ZombieControlsWidget),
    icon: '🧟',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  // ── Change Enablement ──
  {
    id: 'governance.root_cause_vs_patch',
    key: 'root_cause_vs_patch',
    title: 'Root Cause vs Patch',
    titleAr: 'جذري مقابل ترقيع',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/root-cause-vs-patch.widget').then(m => m.RootCauseVsPatchWidget),
    icon: '🔧',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'governance.change_leverage',
    key: 'change_leverage',
    title: 'Change Leverage',
    titleAr: 'رافعة التغيير',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/change-leverage.widget').then(m => m.ChangeLeverageWidget),
    icon: '⚡',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'governance.momentum_indicator',
    key: 'momentum_indicator',
    title: 'Momentum Indicator',
    titleAr: 'مؤشر الزخم',
    category: 'governance',
    engine: 'angular',
    component: () => import('../../../components/executive/momentum-indicator.widget').then(m => m.MomentumIndicatorWidget),
    icon: '🚀',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
];
