import type { ModuleManifest } from '@dos/types';
import { registerModule } from '@dos/module-sdk';
import { GOVERNANCE_PERMISSIONS, GOVERNANCE_ROLES, GOVERNANCE_ACTIONS } from './security/governance.security';
import { GOVERNANCE_APPROVAL_MATRIX } from './security/governance.approval-matrix';

export const GOVERNANCE_MANIFEST: ModuleManifest = {
  code: 'governance',
  version: '2.0.0',
  aliases: [],
  nameEn: 'Governance',
  nameAr: 'الحوكمة',
  descriptionEn: 'Committee management, board packs, delegation, mandates, and governance health monitoring.',
  descriptionAr: 'إدارة اللجان وحزم مجلس الإدارة والتفويض والولايات ومراقبة صحة الحوكمة.',
  tier: 'full',
  category: 'governance',
  routeBase: '/api/governance',
  eventNamespace: 'governance',
  tablePrefix: 'governance_',
  ownedTables: [
    'governance_bodies', 'governance_charters', 'governance_action_items',
    'governance_action_updates', 'governance_agenda_items', 'governance_ai_feedback',
    'governance_ai_runs', 'governance_authority_levels', 'governance_auto_fire_log',
    'governance_ack_campaigns', 'governance_board_pack_items', 'governance_board_packs',
    'governance_body_members', 'governance_calendar_entries', 'governance_committee_meetings',
    'governance_decision_items', 'governance_delegation_rules', 'governance_digests',
    'governance_escalation_rules', 'governance_exec_summaries', 'governance_health_scores',
    'governance_initiatives', 'governance_mandates', 'governance_maturity_scores',
    'governance_meeting_attendees', 'governance_meeting_minutes', 'governance_milestones',
    'governance_objectives', 'governance_obligation_links', 'governance_policies',
    'governance_procedure_templates', 'governance_raci_templates', 'governance_recommendations',
    'governance_reporting_cycles', 'governance_responsibility_assignments',
    'governance_review_cycles', 'governance_reviews', 'governance_risk_appetite_links',
    'governance_score_dimensions', 'governance_standards', 'governance_structure_nodes',
    'governance_voting_records',
    'committee_visibility_thresholds', 'decision_record', 'delegation_policies',
    'delegation_rules', 'delegations',
  ],
  sharedTables: [],
  referencedTables: ['audit_trail', 'teams', 'workflows', 'compliance_frameworks', 'risk_assessments'],
  aggregateRoots: ['governance_bodies', 'governance_charters', 'governance_board_packs', 'governance_mandates'],
  publishedEvents: [
    'governance.charter_approved', 'governance.committee_meeting_scheduled',
    'governance.decision_recorded', 'governance.delegation_created',
    'governance.health_score_updated', 'governance.mandate_activated',
    'governance.obligation_created', 'governance.action_created',
    'governance.review_completed', 'governance.board_pack_generated',
    'governance.milestone_reached', 'governance.initiative_started',
    'governance.digest_published', 'governance.exec_summary_generated',
    'governance.structure_changed',
  ],
  consumedEvents: [
    'compliance.posture_changed', 'risk.assessment_completed',
    'policy.approved', 'audit.engagement_completed', 'workflow.status_changed',
  ],
  hardDeps: ['compliance', 'risk'],
  softDeps: ['policy', 'audit', 'evidence', 'qiyas'],
  navId: 'governance',
  navChildCount: 25,
  workflowTemplateCode: 'governance_charter_review',
  workflowSlaHours: 720,
  automationLevel: 'manual',
  agentBinding: 'A04',
  aiCapabilities: ['notes', 'recommendations', 'gate_checks'],
  aiEnabled: true,
  featureFlags: ['governance.board_packs', 'governance.exec_summaries', 'governance.ai_digests'],
  installable: true,
  provisioningOrder: 15,
  licensingTier: 'professional',
  visibility: 'both',
  adminSurfaces: ['governance-structure', 'delegation-rules', 'authority-levels', 'committee-config'],

  securityPermissions: GOVERNANCE_PERMISSIONS,
  securityRoles: GOVERNANCE_ROLES,
  securityActions: GOVERNANCE_ACTIONS,
  approvalRules: GOVERNANCE_APPROVAL_MATRIX,
  ownershipRules: [
    { entityType: 'governance_bodies', ownerField: 'chair_id', reviewerField: null, approverField: null, assigneeField: 'secretary_id', orgScopeField: 'org_id', defaultOwnerRole: 'governance.module_lead', canDelegate: true, delegateRoles: ['governance.operator'], canReassign: true, reassignRoles: ['governance.module_lead', 'governance.executive_owner'], requiresApproval: false, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'org' },
    { entityType: 'governance_charters', ownerField: 'owner_id', reviewerField: 'reviewer_id', approverField: 'approver_id', assigneeField: null, orgScopeField: 'org_id', defaultOwnerRole: 'governance.module_lead', canDelegate: true, delegateRoles: ['governance.operator'], canReassign: true, reassignRoles: ['governance.module_lead', 'governance.executive_owner'], requiresApproval: true, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'org' },
    { entityType: 'governance_board_packs', ownerField: 'created_by', reviewerField: 'reviewer_id', approverField: 'approver_id', assigneeField: null, orgScopeField: 'org_id', defaultOwnerRole: 'governance.operator', canDelegate: true, delegateRoles: ['governance.contributor'], canReassign: true, reassignRoles: ['governance.module_lead', 'governance.executive_owner'], requiresApproval: true, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'org' },
    { entityType: 'governance_mandates', ownerField: 'owner_id', reviewerField: 'reviewer_id', approverField: 'approver_id', assigneeField: null, orgScopeField: 'org_id', defaultOwnerRole: 'governance.executive_owner', canDelegate: true, delegateRoles: ['governance.module_lead'], canReassign: true, reassignRoles: ['governance.executive_owner'], requiresApproval: true, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'org' },
  ],
  sodRules: [
    { ruleCode: 'governance.sod.proposer_approver', descriptionEn: 'Decision proposer cannot approve their own proposal', descriptionAr: 'لا يمكن لمقترح القرار الموافقة على اقتراحه', conflictingRoles: [], conflictingActions: ['governance.decision.propose', 'governance.decision.approve'], conflictingTransitions: ['proposed->approved'], severity: 'critical', enforcement: 'block', temporaryWaiverAllowed: false, waiverMaxDays: null, compensatingControls: ['committee_vote'], overrideAuthority: ['governance.executive_owner'], auditObligations: ['log_sod_violation'] },
    { ruleCode: 'governance.sod.charter_drafter_signer', descriptionEn: 'Charter drafter cannot sign off on their own charter', descriptionAr: 'لا يمكن لمعد الميثاق التوقيع على ميثاقه', conflictingRoles: [], conflictingActions: ['governance.charter.draft', 'governance.charter.sign_off'], conflictingTransitions: ['draft->signed'], severity: 'high', enforcement: 'block', temporaryWaiverAllowed: false, waiverMaxDays: null, compensatingControls: ['committee_vote'], overrideAuthority: ['governance.executive_owner'], auditObligations: ['log_sod_violation'] },
  ],
    mcpServiceEntrypoint: 'modules/governance/services/governance/governance.service'
};

registerModule(GOVERNANCE_MANIFEST);
