import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const INCIDENT_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'INCIDENT.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'INCIDENT.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'INCIDENT.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'INCIDENT.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'INCIDENT.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'INCIDENT.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'INCIDENT.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'INCIDENT.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'INCIDENT.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'INCIDENT.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'INCIDENT.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'INCIDENT.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  ACTIVE_NOT_FOUND: { code: 'INCIDENT.ACTIVE_NOT_FOUND', httpStatus: 404, messageEn: 'Active not found', messageAr: 'Active غير موجود' },
  ACTIVE_ALREADY_EXISTS: { code: 'INCIDENT.ACTIVE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Active already exists', messageAr: 'Active موجود بالفعل' },
  ACTIVE_VALIDATION_FAILED: { code: 'INCIDENT.ACTIVE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Active validation failed', messageAr: 'فشل التحقق من Active' },
  REINDEX_NOT_FOUND: { code: 'INCIDENT.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'INCIDENT.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'INCIDENT.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'INCIDENT.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'INCIDENT.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'INCIDENT.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  TAXONOMY_NOT_FOUND: { code: 'INCIDENT.TAXONOMY_NOT_FOUND', httpStatus: 404, messageEn: 'Taxonomy not found', messageAr: 'Taxonomy غير موجود' },
  TAXONOMY_ALREADY_EXISTS: { code: 'INCIDENT.TAXONOMY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Taxonomy already exists', messageAr: 'Taxonomy موجود بالفعل' },
  TAXONOMY_VALIDATION_FAILED: { code: 'INCIDENT.TAXONOMY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Taxonomy validation failed', messageAr: 'فشل التحقق من Taxonomy' },
  NEAR_MISS_NOT_FOUND: { code: 'INCIDENT.NEAR_MISS_NOT_FOUND', httpStatus: 404, messageEn: 'Near Miss not found', messageAr: 'Near Miss غير موجود' },
  NEAR_MISS_ALREADY_EXISTS: { code: 'INCIDENT.NEAR_MISS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Near Miss already exists', messageAr: 'Near Miss موجود بالفعل' },
  NEAR_MISS_VALIDATION_FAILED: { code: 'INCIDENT.NEAR_MISS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Near Miss validation failed', messageAr: 'فشل التحقق من Near Miss' },
  PIR_NOT_FOUND: { code: 'INCIDENT.PIR_NOT_FOUND', httpStatus: 404, messageEn: 'Pir not found', messageAr: 'Pir غير موجود' },
  PIR_ALREADY_EXISTS: { code: 'INCIDENT.PIR_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Pir already exists', messageAr: 'Pir موجود بالفعل' },
  PIR_VALIDATION_FAILED: { code: 'INCIDENT.PIR_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Pir validation failed', messageAr: 'فشل التحقق من Pir' },
  REGULATORY_NOTIFICATION_NOT_FOUND: { code: 'INCIDENT.REGULATORY_NOTIFICATION_NOT_FOUND', httpStatus: 404, messageEn: 'Regulatory Notification not found', messageAr: 'Regulatory Notification غير موجود' },
  REGULATORY_NOTIFICATION_ALREADY_EXISTS: { code: 'INCIDENT.REGULATORY_NOTIFICATION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Regulatory Notification already exists', messageAr: 'Regulatory Notification موجود بالفعل' },
  REGULATORY_NOTIFICATION_VALIDATION_FAILED: { code: 'INCIDENT.REGULATORY_NOTIFICATION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Regulatory Notification validation failed', messageAr: 'فشل التحقق من Regulatory Notification' },
  REGULATORY_NOT_FOUND: { code: 'INCIDENT.REGULATORY_NOT_FOUND', httpStatus: 404, messageEn: 'Regulatory not found', messageAr: 'Regulatory غير موجود' },
  REGULATORY_ALREADY_EXISTS: { code: 'INCIDENT.REGULATORY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Regulatory already exists', messageAr: 'Regulatory موجود بالفعل' },
  REGULATORY_VALIDATION_FAILED: { code: 'INCIDENT.REGULATORY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Regulatory validation failed', messageAr: 'فشل التحقق من Regulatory' },
  TRENDS_NOT_FOUND: { code: 'INCIDENT.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'INCIDENT.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'INCIDENT.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  PATTERNS_NOT_FOUND: { code: 'INCIDENT.PATTERNS_NOT_FOUND', httpStatus: 404, messageEn: 'Patterns not found', messageAr: 'Patterns غير موجود' },
  PATTERNS_ALREADY_EXISTS: { code: 'INCIDENT.PATTERNS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Patterns already exists', messageAr: 'Patterns موجود بالفعل' },
  PATTERNS_VALIDATION_FAILED: { code: 'INCIDENT.PATTERNS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Patterns validation failed', messageAr: 'فشل التحقق من Patterns' },
  RISK_LINK_NOT_FOUND: { code: 'INCIDENT.RISK_LINK_NOT_FOUND', httpStatus: 404, messageEn: 'Risk Link not found', messageAr: 'Risk Link غير موجود' },
  RISK_LINK_ALREADY_EXISTS: { code: 'INCIDENT.RISK_LINK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Risk Link already exists', messageAr: 'Risk Link موجود بالفعل' },
  RISK_LINK_VALIDATION_FAILED: { code: 'INCIDENT.RISK_LINK_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Risk Link validation failed', messageAr: 'فشل التحقق من Risk Link' },

  UNAUTHORIZED: { code: 'INCIDENT.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for incident operation', messageAr: 'صلاحيات غير كافية لعملية incident' },
  INVALID_STATE_TRANSITION: { code: 'INCIDENT.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'INCIDENT.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'INCIDENT.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'INCIDENT.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'INCIDENT.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type IncidentErrorCode = keyof typeof INCIDENT_ERROR_CODES;
