/**
 * foundation — Approval Matrix
 * Defines approval rules for foundation (org hierarchy) entity lifecycle transitions.
 *
 * Entity types:
 *   - organizations: Organization record changes
 *   - business_units: Business unit creation and restructuring
 *   - departments: Department lifecycle
 *   - positions: Position definition changes
 *   - legal_entities: Legal entity governance transitions
 *
 * Foundation is a platform-core module owned by DOS. Approval rules here
 * govern structural changes to the organization hierarchy which may have
 * cascading impact on scope resolution and access control.
 *
 * Consumed by platform approval-enforcer via dynamic import.
 * @see platform/dos/workflows/orchestration/approval-enforcer.ts
 */

import type { ApprovalRule } from '@dos/types';

export const FOUNDATION_APPROVAL_MATRIX: ApprovalRule[] = [
  // ── organizations entity ──────────────────────────────────
  {
    entityType: 'organizations',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'foundation.contributor',
    requiredPermission: 'foundation.organizations.approve',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'organizations',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'foundation.approver',
    requiredPermission: 'foundation.organizations.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'organizations',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.organizations.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'organizations',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.organizations.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'organizations',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.organizations.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },

  // ── business_units entity ─────────────────────────────────
  {
    entityType: 'business_units',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'foundation.contributor',
    requiredPermission: 'foundation.business_units.approve',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'business_units',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'foundation.approver',
    requiredPermission: 'foundation.business_units.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'business_units',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.business_units.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'business_units',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.business_units.approve',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'business_units',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.business_units.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },

  // ── departments entity ────────────────────────────────────
  {
    entityType: 'departments',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'foundation.contributor',
    requiredPermission: 'foundation.departments.approve',
    authorityLevel: 'optional',
    scopeRule: 'department',
    minApprovers: 0,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'departments',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'foundation.approver',
    requiredPermission: 'foundation.departments.approve',
    authorityLevel: 'required',
    scopeRule: 'department',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'departments',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.departments.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'departments',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.departments.approve',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'departments',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.departments.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },

  // ── positions entity ──────────────────────────────────────
  {
    entityType: 'positions',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'foundation.contributor',
    requiredPermission: 'foundation.positions.approve',
    authorityLevel: 'optional',
    scopeRule: 'department',
    minApprovers: 0,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.module_lead'],
    evidenceRequired: false,
    commentsRequired: false,
  },
  {
    entityType: 'positions',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'foundation.approver',
    requiredPermission: 'foundation.positions.approve',
    authorityLevel: 'required',
    scopeRule: 'department',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.module_lead'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'positions',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.positions.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'positions',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'foundation.module_lead',
    requiredPermission: 'foundation.positions.approve',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'positions',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.positions.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },

  // ── legal_entities entity ─────────────────────────────────
  {
    entityType: 'legal_entities',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'foundation.contributor',
    requiredPermission: 'foundation.legal_entities.approve',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: true,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'legal_entities',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'foundation.approver',
    requiredPermission: 'foundation.legal_entities.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['foundation.module_lead', 'foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'legal_entities',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.legal_entities.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'legal_entities',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.legal_entities.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 72,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'legal_entities',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'foundation.executive_owner',
    requiredPermission: 'foundation.legal_entities.approve',
    authorityLevel: 'required',
    scopeRule: 'global',
    minApprovers: 1,
    escalationPath: ['foundation.executive_owner'],
    timeoutHours: 24,
    autoApproveAllowed: false,
    overrideRoles: ['foundation.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
];
