import type { ModuleRole } from '@dos/types';

export const FOUNDATION_MODULE_ROLES: ModuleRole[] = [
  { roleCode: 'foundation.executive_owner', archetype: 'executive_owner', nameEn: 'Foundation Executive Owner', nameAr: 'المالك التنفيذي للأساس', descriptionEn: 'Executive owner', descriptionAr: 'المالك التنفيذي', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read', 'foundation.record.write', 'foundation.record.delete', 'foundation.record.approve', 'foundation.manage'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'foundation.module_lead', archetype: 'module_lead', nameEn: 'Foundation Module Lead', nameAr: 'قائد وحدة الأساس', descriptionEn: 'Module lead', descriptionAr: 'قائد الوحدة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read', 'foundation.record.write', 'foundation.record.approve', 'foundation.manage'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'foundation.approver', archetype: 'approver', nameEn: 'Foundation Approver', nameAr: 'معتمد الأساس', descriptionEn: 'Approver', descriptionAr: 'المعتمد', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read', 'foundation.record.approve'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'foundation.operator', archetype: 'operator', nameEn: 'Foundation Operator', nameAr: 'مشغل الأساس', descriptionEn: 'Operator', descriptionAr: 'المشغل', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read', 'foundation.record.write'], authorityLevel: 'optional', defaultScope: 'department' },
  { roleCode: 'foundation.contributor', archetype: 'contributor', nameEn: 'Foundation Contributor', nameAr: 'مساهم الأساس', descriptionEn: 'Contributor', descriptionAr: 'المساهم', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read', 'foundation.record.write'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'foundation.reviewer', archetype: 'reviewer', nameEn: 'Foundation Reviewer', nameAr: 'مراجع الأساس', descriptionEn: 'Reviewer', descriptionAr: 'المراجع', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read'], authorityLevel: 'optional', defaultScope: 'department' },
  { roleCode: 'foundation.auditor', archetype: 'auditor', nameEn: 'Foundation Auditor', nameAr: 'مدقق الأساس', descriptionEn: 'Auditor', descriptionAr: 'المدقق', isDefault: false, isSystem: false, isGlobal: false, permissions: ['foundation.read'], authorityLevel: 'optional', defaultScope: 'org' },
  { roleCode: 'foundation.viewer', archetype: 'viewer', nameEn: 'Foundation Viewer', nameAr: 'عارض الأساس', descriptionEn: 'Viewer', descriptionAr: 'العارض', isDefault: true, isSystem: false, isGlobal: false, permissions: ['foundation.read'], authorityLevel: 'optional', defaultScope: 'own' },
];
