-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=risk scope=tenant function=entity
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/risk/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * entity_links
--   * risks
--
-- Source migrations (immutable, 1):
--   * modules/risk/db/tenant/migrations/112_ai_model_risk_register_link.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_entity_links_ai_model
      ON entity_links(source_type, source_id) WHERE source_type = 'ai_model';

CREATE INDEX IF NOT EXISTS idx_risks_category ON risks(risk_category) WHERE risk_category IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_risks_entity_links_model ON risks((entity_links->>'modelId')) WHERE risk_category = 'ai_model';
