-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=risk scope=tenant function=reviews
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/risk/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * risk_approval_requests
--   * risk_reviews
--
-- Source migrations (immutable, 1):
--   * modules/risk/db/tenant/migrations/122_risk_review_approval_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_reviews (
    review_id VARCHAR(32) PRIMARY KEY,
    tenant_id UUID,
    risk_id VARCHAR(32) NOT NULL,
    review_type VARCHAR(50) NOT NULL CHECK (review_type IN ('periodic', 'escalation', 'appetite_breach', 'treatment_completion', 'closure')),
    requested_by VARCHAR(64) NOT NULL,
    assigned_to VARCHAR(64),
    assigned_at TIMESTAMPTZ,
    assignment_type VARCHAR(50) DEFAULT 'manual',
    priority VARCHAR(20) NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    due_date TIMESTAMPTZ,
    review_notes TEXT,
    auto_escalation_days INTEGER DEFAULT 7,
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_review', 'approved', 'rejected', 'escalated', 'completed')),
    reviewed_by VARCHAR(64),
    reviewed_at TIMESTAMPTZ,
    next_review_date TIMESTAMPTZ,
    conditions JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT fk_risk_reviews_risk FOREIGN KEY (risk_id) REFERENCES __TENANT_SCHEMA__.risks(risk_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_approval_requests (
    approval_id VARCHAR(32) PRIMARY KEY,
    tenant_id UUID,
    risk_id VARCHAR(32) NOT NULL,
    approval_type VARCHAR(50) NOT NULL CHECK (approval_type IN ('risk_acceptance', 'treatment_plan', 'risk_closure', 'appetite_breach', 'escalation')),
    requested_by VARCHAR(64) NOT NULL,
    requested_role VARCHAR(100) NOT NULL,
    urgency VARCHAR(20) NOT NULL CHECK (urgency IN ('normal', 'urgent', 'critical')),
    business_justification TEXT NOT NULL,
    risk_level VARCHAR(50),
    control_effectiveness TEXT,
    mitigation_plan TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'escalated', 'delegated')),
    approved_by VARCHAR(64),
    approved_at TIMESTAMPTZ,
    approval_notes TEXT,
    conditions JSONB,
    delegated_to VARCHAR(64),
    valid_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT fk_risk_approval_requests_risk FOREIGN KEY (risk_id) REFERENCES __TENANT_SCHEMA__.risks(risk_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_risk_reviews_risk_id ON __TENANT_SCHEMA__.risk_reviews(risk_id);

CREATE INDEX IF NOT EXISTS idx_risk_reviews_status ON __TENANT_SCHEMA__.risk_reviews(status);

CREATE INDEX IF NOT EXISTS idx_risk_reviews_assigned_to ON __TENANT_SCHEMA__.risk_reviews(assigned_to) WHERE assigned_to IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_risk_reviews_priority ON __TENANT_SCHEMA__.risk_reviews(priority DESC);

CREATE INDEX IF NOT EXISTS idx_risk_reviews_due_date ON __TENANT_SCHEMA__.risk_reviews(due_date) WHERE due_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_risk_approval_requests_risk_id ON __TENANT_SCHEMA__.risk_approval_requests(risk_id);

CREATE INDEX IF NOT EXISTS idx_risk_approval_requests_status ON __TENANT_SCHEMA__.risk_approval_requests(status);

CREATE INDEX IF NOT EXISTS idx_risk_approval_requests_urgency ON __TENANT_SCHEMA__.risk_approval_requests(urgency DESC);

CREATE INDEX IF NOT EXISTS idx_risk_approval_requests_requested_role ON __TENANT_SCHEMA__.risk_approval_requests(requested_role);
