import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const EVIDENCE_WIDGETS: WidgetManifest[] = [
  {
    id: 'evidence.locker',
    key: 'evidence_locker',
    title: 'Evidence Locker',
    titleAr: 'خزنة الأدلة',
    category: 'evidence',
    engine: 'angular',
    component: () => import('../../../components/evidence/evidence-locker.widget').then(m => m.EvidenceLockerWidget),
    icon: '🔗',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'evidence.queue',
    key: 'evidence_queue',
    title: 'Evidence Queue',
    titleAr: 'قائمة الأدلة',
    category: 'evidence',
    engine: 'angular',
    component: () => import('../../../components/evidence/evidence-queue.widget').then(m => m.EvidenceQueueWidget),
    icon: '📋',
    defaultSize: { cols: 3, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'evidence.rot',
    key: 'evidence_rot',
    title: 'Evidence Rot',
    titleAr: 'فساد الأدلة',
    category: 'evidence',
    engine: 'angular',
    component: () => import('../../../components/evidence/evidence-rot.widget').then(m => m.EvidenceRotWidget),
    icon: '🧪',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'evidence.donut_echart',
    key: 'evidence_freshness',
    title: 'Evidence Donut',
    titleAr: 'دائرة الأدلة',
    category: 'evidence',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/donut/evidence-donut-echart.component').then(m => m.EvidenceDonutEchartComponent),
    icon: '🍩',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'evidence.flow_sankey',
    key: 'evidence_flow',
    title: 'Evidence Flow',
    titleAr: 'تدفق الأدلة',
    category: 'evidence',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/sankey/evidence-flow.component').then(m => m.EvidenceFlowComponent),
    icon: '🔀',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'evidence.globe_3d',
    key: 'evidence_globe_3d',
    title: 'Evidence Globe 3D',
    titleAr: 'كرة الأدلة ثلاثية الأبعاد',
    category: 'evidence',
    engine: 'plotly',
    component: () => import('../../../chart-infra/echart-components/three-d/evidence-globe-3d.component').then(m => m.EvidenceGlobe3dComponent),
    icon: '🌍',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
];
