/**
 * Compliance EN Labels — AGRC-OS
 */
export const COMPLIANCE_EN = {
  // Page
  pageTitle: 'Compliance',
  pageSubtitle: 'Compliance command workspace — frameworks, domains, obligations, gaps, remediation, and audit readiness',

  // Tabs
  overview: 'Compliance Overview',
  frameworks: 'Frameworks',
  domains: 'Domains',
  obligations: 'Obligations',
  gapAssessment: 'Gap Assessment',
  roadmap: 'Compliance Roadmap',

  // KPI
  overallScore: 'Compliance Score',
  activeFrameworks: 'Active Frameworks',
  openGaps: 'Open Gaps',
  criticalGaps: 'Critical Gaps',
  obligationsCovered: 'Obligations Covered',
  controlsMapped: 'Controls Mapped',
  evidenceCoverage: 'Evidence Coverage',
  evidenceQualityTierA: 'Evidence Tier A',
  evidenceFreshness: 'Evidence Freshness',
  auditReadiness: 'Audit Readiness',
  overdueActions: 'Overdue Actions',

  // Overview sections
  frameworkPosture: 'Framework Posture',
  domainHealth: 'Domain Health',
  priorityIssues: 'Priority Issues',
  recentAssessments: 'Recent Assessments',
  complianceTrend: 'Compliance Score Trend',

  // Table columns
  code: 'Code',
  name: 'Name',
  status: 'Status',
  owner: 'Owner',
  scope: 'Scope',
  score: 'Score',
  domain: 'Domain',
  framework: 'Framework',
  coverage: 'Coverage',
  severity: 'Severity',
  dueDate: 'Due Date',
  description: 'Description',
  obligation: 'Obligation',
  controls: 'Controls',
  evidence: 'Evidence',
  category: 'Category',
  action: 'Action',
  implemented: 'Implemented',
  lastReview: 'Last Review',
  domainsCount: 'Domains',
  obligationsCount: 'Obligations',
  mappedControls: 'Mapped Controls',

  // Framework
  comparison: 'Compare Frameworks',
  frameworkDetails: 'Framework Details',
  openFramework: 'Open Framework',
  editScope: 'Edit Scope',
  assignOwner: 'Assign Owner',
  runAssessment: 'Run Assessment',
  exportReport: 'Export Report',
  enableDisable: 'Enable/Disable',
  regulator: 'Regulator',
  version: 'Version',
  applicableScope: 'Applicable Scope',
  activeDomains: 'Active Domains',
  gapCount: 'Gap Count',
  overdueIssues: 'Overdue Issues',
  launchGap: 'Launch Gap Assessment',
  generateActionPlan: 'Generate Action Plan',

  // Domain
  domainDetails: 'Domain Details',
  heatView: 'Heat View',
  tableView: 'Table View',
  domainChain: 'Domain Chain',
  linkedObligations: 'Linked Obligations',
  linkedControls: 'Linked Controls',
  linkedEvidence: 'Linked Evidence',
  activeRemediation: 'Active Remediation',
  recentActivity: 'Recent Activity',

  // Obligation
  obligationDetails: 'Obligation Details',
  coverageMatrix: 'Coverage Matrix',
  fullText: 'Full Text',
  rationale: 'Rationale / Interpretation',
  auditNotes: 'Audit Notes',
  commentsHistory: 'Comments / History',
  mapControl: 'Map Control',
  mapEvidence: 'Map Evidence',
  createTask: 'Create Remediation Task',

  // Gap
  gapDetails: 'Gap Details',
  prioritizationBoard: 'Prioritization Board',
  assessmentHistory: 'Assessment History',
  cause: 'Cause',
  impact: 'Impact',
  sourceAssessment: 'Source Assessment',
  missingControl: 'Missing / Weak Control',
  missingEvidence: 'Missing / Stale Evidence',
  remediationPlan: 'Remediation Plan',
  targetDate: 'Target Date',
  validationEvidence: 'Validation Evidence',
  approvalTrail: 'Approval Trail',
  acceptRisk: 'Accept Risk / Exception',
  startRemediation: 'Start Remediation',
  attachEvidence: 'Attach Evidence',
  markReady: 'Mark Ready for Validation',
  closeGap: 'Close Gap',
  createRemediation: 'Create Remediation',

  // Roadmap
  currentWave: 'Current Wave',
  nextMilestone: 'Next Milestone',
  totalTasks: 'Total Tasks',
  completedTasks: 'Completed Tasks',
  completion: 'Completion',
  targetReadiness: 'Target Readiness Date',
  phase: 'Phase',
  milestone: 'Milestone',
  tasks: 'Tasks',
  dependencies: 'Dependencies',
  blockedItems: 'Blocked Items',
  forecast: 'Forecast / Impact',
  expectedScore: 'Expected Compliance Score',
  expectedReadiness: 'Expected Audit Readiness',
  keyBlockers: 'Key Blockers',
  generateRoadmap: 'Generate Roadmap',

  // Audit readiness
  readinessScore: 'Readiness Score',
  tested: 'Tested',
  withEvidence: 'With Evidence',
  fullyReady: 'Fully Ready',

  // Actions
  addFramework: 'Add / Enable Framework',
  startAssessment: 'Start Assessment',
  exportCompliance: 'Export Compliance Report',
  openAuditReadiness: 'Open Audit Readiness',
  filterByFramework: 'Filter by Framework',
  allFrameworks: 'All Frameworks',
  details: 'Details',
  close: 'Close',
  changeStatus: 'Change Status',
  exportItem: 'Export Item',

  // Empty states
  emptyFrameworks: 'No frameworks are active yet',
  emptyFrameworksCta: 'Enable frameworks from Onboarding scope',
  emptyDomains: 'Framework domains will appear after framework initialization',
  emptyDomainsCta: 'Re-run framework seed',
  emptyObligations: 'No obligation assessments yet',
  emptyObligationsCta: 'Start first compliance assessment',
  emptyGaps: 'No open gaps detected',
  emptyGapsSub: 'This can mean either strong coverage or assessment not yet run',
  emptyGapsCta: 'Review assessment coverage',
  emptyRoadmap: 'No compliance roadmap generated yet',
  emptyRoadmapCta: 'Generate roadmap from open gaps',

  // Misc
  loading: 'Loading...',
  noData: 'No data available',
  search: 'Search...',
  bySeverity: 'By Severity',
  byFramework: 'By Framework',
  byDomain: 'By Domain',
  byOwner: 'By Owner',
  byDueDate: 'By Due Date',
};

export type ComplianceLabels = typeof COMPLIANCE_EN;
