-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=incident scope=tenant function=root
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/incident/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * incident_root_causes
--
-- Source migrations (immutable, 1):
--   * modules/incident/db/tenant/migrations/102_incident_governance_pipeline.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS incident_root_causes (
  root_cause_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id         UUID NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
  category            VARCHAR(100) NOT NULL,
  description         TEXT NOT NULL,
  contributing_factors TEXT DEFAULT '',
  corrective_action   TEXT DEFAULT '',
  preventive_action   TEXT DEFAULT '',
  identified_by       VARCHAR(255),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incident_root_causes_incident ON incident_root_causes(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_root_causes_category ON incident_root_causes(category) WHERE deleted_at IS NULL;
