-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=incident scope=tenant function=severity
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/incident/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (4):
--   * incident_categories
--   * incident_notification_templates
--   * incident_response_teams
--   * incident_severity_matrix
--
-- Source migrations (immutable, 1):
--   * modules/incident/db/tenant/migrations/118_extracted_from_118_incident_vendor_bcp_config_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS incident_severity_matrix (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  severity_code VARCHAR(20) NOT NULL UNIQUE,
  severity_label VARCHAR(50) NOT NULL,
  severity_level INT NOT NULL,
  sla_response_hours INT NOT NULL DEFAULT 4,
  sla_resolution_hours INT NOT NULL DEFAULT 24,
  escalation_role VARCHAR(50) DEFAULT 'admin',
  notification_template VARCHAR(50),
  color VARCHAR(7) DEFAULT '#ff0000',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.incident_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_code VARCHAR(50) NOT NULL UNIQUE,
  category_label VARCHAR(100) NOT NULL,
  parent_category_id UUID,
  default_severity VARCHAR(20),
  playbook_id UUID,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS incident_response_teams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_name VARCHAR(100) NOT NULL,
  team_type VARCHAR(30) DEFAULT 'primary' CHECK (team_type IN ('primary','escalation','executive','external')),
  members JSONB DEFAULT '[]',
  on_call_schedule JSONB DEFAULT '{}',
  notification_channels TEXT[] DEFAULT '{}',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS incident_notification_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_code VARCHAR(50) NOT NULL UNIQUE,
  template_name VARCHAR(100) NOT NULL,
  subject_template TEXT,
  body_template TEXT,
  channels TEXT[] DEFAULT '{email}',
  trigger_event VARCHAR(50),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
