// AUTO-MAINTAINED: keep in sync with dos.dynamic_ui_component_registry.
import type { Type } from '@angular/core';

/**
 * IBM Carbon component_key resolution.
 *
 * Every component_key registered in dos.dynamic_ui_component_registry
 * (vendor=ibm-carbon, approval_status=approved) resolves here to a real
 * IBM Carbon Angular renderer (carbon-components-angular@5.69.x).
 *
 * No DynamicPageHostComponent fallback. No PrimeNG. No Material.
 * Many component_keys legitimately alias the same renderer by carbon_key.
 */

const CARBON_PRIMITIVE_COMPONENT_MAP: Record<string, () => Promise<Type<any>>> = {
  UIShell: () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  Header: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderRenderer),
  HeaderName: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNameRenderer),
  HeaderNavigation: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNavigationRenderer),
  HeaderMenu: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuRenderer),
  HeaderMenuItem: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuItemRenderer),
  HeaderGlobalBar: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalBarRenderer),
  HeaderGlobalAction: () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalActionRenderer),
  SideNav: () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavRenderer),
  SideNavItems: () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavItemsRenderer),
  SideNavMenu: () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuRenderer),
  SideNavMenuItem: () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuItemRenderer),
  SideNavLink: () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavLinkRenderer),
  Content: () => import('./carbon-primitive-renderers').then(m => m.CarbonContentRenderer),
  Grid: () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  Column: () => import('./carbon-primitive-renderers').then(m => m.CarbonColumnRenderer),
  Layer: () => import('./carbon-primitive-renderers').then(m => m.CarbonLayerRenderer),
  Breadcrumb: () => import('./carbon-primitive-renderers').then(m => m.CarbonBreadcrumbRenderer),
  Tabs: () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  Tab: () => import('./carbon-primitive-renderers').then(m => m.CarbonTabRenderer),
  Tile: () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  ClickableTile: () => import('./carbon-primitive-renderers').then(m => m.CarbonClickableTileRenderer),
  ExpandableTile: () => import('./carbon-primitive-renderers').then(m => m.CarbonExpandableTileRenderer),
  Tag: () => import('./carbon-primitive-renderers').then(m => m.CarbonTagRenderer),
  InlineNotification: () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineNotificationRenderer),
  ToastNotification: () => import('./carbon-primitive-renderers').then(m => m.CarbonToastNotificationRenderer),
  ProgressBar: () => import('./carbon-primitive-renderers').then(m => m.CarbonProgressBarRenderer),
  InlineLoading: () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineLoadingRenderer),
  SkeletonText: () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonTextRenderer),
  SkeletonPlaceholder: () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonPlaceholderRenderer),
  DataTable: () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  TableToolbar: () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarRenderer),
  TableToolbarSearch: () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarSearchRenderer),
  TableToolbarActions: () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarActionsRenderer),
  TableBatchActions: () => import('./carbon-primitive-renderers').then(m => m.CarbonTableBatchActionsRenderer),
  Pagination: () => import('./carbon-primitive-renderers').then(m => m.CarbonPaginationRenderer),
  StructuredList: () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  Search: () => import('./carbon-primitive-renderers').then(m => m.CarbonSearchRenderer),
  Dropdown: () => import('./carbon-primitive-renderers').then(m => m.CarbonDropdownRenderer),
  ComboBox: () => import('./carbon-primitive-renderers').then(m => m.CarbonComboBoxRenderer),
  MultiSelect: () => import('./carbon-primitive-renderers').then(m => m.CarbonMultiSelectRenderer),
  DatePicker: () => import('./carbon-primitive-renderers').then(m => m.CarbonDatePickerRenderer),
  TextInput: () => import('./carbon-primitive-renderers').then(m => m.CarbonTextInputRenderer),
  TextArea: () => import('./carbon-primitive-renderers').then(m => m.CarbonTextAreaRenderer),
  NumberInput: () => import('./carbon-primitive-renderers').then(m => m.CarbonNumberInputRenderer),
  Select: () => import('./carbon-primitive-renderers').then(m => m.CarbonSelectRenderer),
  Checkbox: () => import('./carbon-primitive-renderers').then(m => m.CarbonCheckboxRenderer),
  Radio: () => import('./carbon-primitive-renderers').then(m => m.CarbonRadioRenderer),
  Toggle: () => import('./carbon-primitive-renderers').then(m => m.CarbonToggleRenderer),
  Button: () => import('./carbon-primitive-renderers').then(m => m.CarbonButtonRenderer),
  IconButton: () => import('./carbon-primitive-renderers').then(m => m.CarbonIconButtonRenderer),
  OverflowMenu: () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuRenderer),
  OverflowMenuOption: () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuOptionRenderer),
  ContextMenu: () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  Modal: () => import('./carbon-primitive-renderers').then(m => m.CarbonModalRenderer),
  Tooltip: () => import('./carbon-primitive-renderers').then(m => m.CarbonTooltipRenderer),
  Toggletip: () => import('./carbon-primitive-renderers').then(m => m.CarbonToggletipRenderer),
  Popover: () => import('./carbon-primitive-renderers').then(m => m.CarbonPopoverRenderer),
  FileUploader: () => import('./carbon-primitive-renderers').then(m => m.CarbonFileUploaderRenderer),
  Accordion: () => import('./carbon-primitive-renderers').then(m => m.CarbonAccordionRenderer),
  'ui_shell': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'header': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderRenderer),
  'header_name': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNameRenderer),
  'header_navigation': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNavigationRenderer),
  'header_menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuRenderer),
  'header_menu_item': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuItemRenderer),
  'header_global_bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalBarRenderer),
  'header_global_action': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalActionRenderer),
  'side_nav': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavRenderer),
  'side_nav_items': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavItemsRenderer),
  'side_nav_menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuRenderer),
  'side_nav_menu_item': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuItemRenderer),
  'side_nav_link': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavLinkRenderer),
  'content': () => import('./carbon-primitive-renderers').then(m => m.CarbonContentRenderer),
  'grid': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'column': () => import('./carbon-primitive-renderers').then(m => m.CarbonColumnRenderer),
  'layer': () => import('./carbon-primitive-renderers').then(m => m.CarbonLayerRenderer),
  'breadcrumb': () => import('./carbon-primitive-renderers').then(m => m.CarbonBreadcrumbRenderer),
  'tabs': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'tab': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabRenderer),
  'tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'clickable_tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonClickableTileRenderer),
  'expandable_tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonExpandableTileRenderer),
  'tag': () => import('./carbon-primitive-renderers').then(m => m.CarbonTagRenderer),
  'data_table': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'table_toolbar': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarRenderer),
  'table_toolbar_search': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarSearchRenderer),
  'table_toolbar_actions': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarActionsRenderer),
  'table_batch_actions': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableBatchActionsRenderer),
  'pagination': () => import('./carbon-primitive-renderers').then(m => m.CarbonPaginationRenderer),
  'structured_list': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'search': () => import('./carbon-primitive-renderers').then(m => m.CarbonSearchRenderer),
  'dropdown': () => import('./carbon-primitive-renderers').then(m => m.CarbonDropdownRenderer),
  'combo_box': () => import('./carbon-primitive-renderers').then(m => m.CarbonComboBoxRenderer),
  'multi_select': () => import('./carbon-primitive-renderers').then(m => m.CarbonMultiSelectRenderer),
  'date_picker': () => import('./carbon-primitive-renderers').then(m => m.CarbonDatePickerRenderer),
  'text_input': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextInputRenderer),
  'text_area': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextAreaRenderer),
  'number_input': () => import('./carbon-primitive-renderers').then(m => m.CarbonNumberInputRenderer),
  'select': () => import('./carbon-primitive-renderers').then(m => m.CarbonSelectRenderer),
  'checkbox': () => import('./carbon-primitive-renderers').then(m => m.CarbonCheckboxRenderer),
  'radio': () => import('./carbon-primitive-renderers').then(m => m.CarbonRadioRenderer),
  'toggle': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggleRenderer),
  'button': () => import('./carbon-primitive-renderers').then(m => m.CarbonButtonRenderer),
  'icon_button': () => import('./carbon-primitive-renderers').then(m => m.CarbonIconButtonRenderer),
  'overflow_menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuRenderer),
  'overflow_menu_option': () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuOptionRenderer),
  'modal': () => import('./carbon-primitive-renderers').then(m => m.CarbonModalRenderer),
  'inline_notification': () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineNotificationRenderer),
  'toast_notification': () => import('./carbon-primitive-renderers').then(m => m.CarbonToastNotificationRenderer),
  'tooltip': () => import('./carbon-primitive-renderers').then(m => m.CarbonTooltipRenderer),
  'toggletip': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggletipRenderer),
  'popover': () => import('./carbon-primitive-renderers').then(m => m.CarbonPopoverRenderer),
  'progress_bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonProgressBarRenderer),
  'inline_loading': () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineLoadingRenderer),
  'skeleton_text': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonTextRenderer),
  'skeleton_placeholder': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonPlaceholderRenderer),
  'context_menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  'file_uploader': () => import('./carbon-primitive-renderers').then(m => m.CarbonFileUploaderRenderer),
  'accordion': () => import('./carbon-primitive-renderers').then(m => m.CarbonAccordionRenderer),
  Link: () => import('./carbon-extended-renderers').then(m => m.CarbonLinkRenderer),
  AspectRatio: () => import('./carbon-extended-renderers').then(m => m.CarbonAspectRatioRenderer),
  ProgressIndicator: () => import('./carbon-extended-renderers').then(m => m.CarbonProgressIndicatorRenderer),
};

const REGISTRY_COMPONENT_MAP: Record<string, () => Promise<Type<any>>> = {
  // ── Band A — Workspace Shell Frame (14) ─────────────────────────────────
  'workspace.frame.ui-shell': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'workspace.frame.header': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderRenderer),
  'workspace.frame.header-name': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNameRenderer),
  'workspace.frame.header-navigation': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderNavigationRenderer),
  'workspace.frame.header-menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuRenderer),
  'workspace.frame.header-menu-item': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderMenuItemRenderer),
  'workspace.frame.header-global-bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalBarRenderer),
  'workspace.frame.header-global-action': () => import('./carbon-primitive-renderers').then(m => m.CarbonHeaderGlobalActionRenderer),
  'workspace.frame.side-nav': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavRenderer),
  'workspace.frame.side-nav-items': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavItemsRenderer),
  'workspace.frame.side-nav-menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuRenderer),
  'workspace.frame.side-nav-menu-item': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavMenuItemRenderer),
  'workspace.frame.side-nav-link': () => import('./carbon-primitive-renderers').then(m => m.CarbonSideNavLinkRenderer),
  'workspace.frame.content': () => import('./carbon-primitive-renderers').then(m => m.CarbonContentRenderer),
  // ── Band B — Navigation / Layout (10) ───────────────────────────────────
  'workspace.nav.grid': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'workspace.nav.column': () => import('./carbon-primitive-renderers').then(m => m.CarbonColumnRenderer),
  'workspace.nav.layer': () => import('./carbon-primitive-renderers').then(m => m.CarbonLayerRenderer),
  'workspace.nav.breadcrumb': () => import('./carbon-primitive-renderers').then(m => m.CarbonBreadcrumbRenderer),
  'workspace.nav.tabs': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'workspace.nav.tab': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabRenderer),
  'workspace.nav.tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'workspace.nav.clickable-tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonClickableTileRenderer),
  'workspace.nav.expandable-tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonExpandableTileRenderer),
  'workspace.nav.tag': () => import('./carbon-primitive-renderers').then(m => m.CarbonTagRenderer),
  // ── Band C — Tables / Lists / Data (7) ─────────────────────────────────
  'workspace.data.data-table': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'workspace.data.table-toolbar': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarRenderer),
  'workspace.data.table-toolbar-search': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarSearchRenderer),
  'workspace.data.table-toolbar-actions': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableToolbarActionsRenderer),
  'workspace.data.table-batch-actions': () => import('./carbon-primitive-renderers').then(m => m.CarbonTableBatchActionsRenderer),
  'workspace.data.pagination': () => import('./carbon-primitive-renderers').then(m => m.CarbonPaginationRenderer),
  'workspace.data.structured-list': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  // ── Band D — Search / Filters / Inputs (12) ────────────────────────────
  'workspace.input.search': () => import('./carbon-primitive-renderers').then(m => m.CarbonSearchRenderer),
  'workspace.input.dropdown': () => import('./carbon-primitive-renderers').then(m => m.CarbonDropdownRenderer),
  'workspace.input.combo-box': () => import('./carbon-primitive-renderers').then(m => m.CarbonComboBoxRenderer),
  'workspace.input.multi-select': () => import('./carbon-primitive-renderers').then(m => m.CarbonMultiSelectRenderer),
  'workspace.input.date-picker': () => import('./carbon-primitive-renderers').then(m => m.CarbonDatePickerRenderer),
  'workspace.input.text-input': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextInputRenderer),
  'workspace.input.text-area': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextAreaRenderer),
  'workspace.input.number-input': () => import('./carbon-primitive-renderers').then(m => m.CarbonNumberInputRenderer),
  'workspace.input.select': () => import('./carbon-primitive-renderers').then(m => m.CarbonSelectRenderer),
  'workspace.input.checkbox': () => import('./carbon-primitive-renderers').then(m => m.CarbonCheckboxRenderer),
  'workspace.input.radio': () => import('./carbon-primitive-renderers').then(m => m.CarbonRadioRenderer),
  'workspace.input.toggle': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggleRenderer),
  // ── Band E — Actions / Feedback / Overlays (7) ─────────────────────────
  'workspace.action.button': () => import('./carbon-primitive-renderers').then(m => m.CarbonButtonRenderer),
  'workspace.action.icon-button': () => import('./carbon-primitive-renderers').then(m => m.CarbonIconButtonRenderer),
  'workspace.action.overflow-menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuRenderer),
  'workspace.action.overflow-menu-option': () => import('./carbon-primitive-renderers').then(m => m.CarbonOverflowMenuOptionRenderer),
  'workspace.action.modal': () => import('./carbon-primitive-renderers').then(m => m.CarbonModalRenderer),
  'workspace.action.inline-notification': () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineNotificationRenderer),
  'workspace.action.toast-notification': () => import('./carbon-primitive-renderers').then(m => m.CarbonToastNotificationRenderer),
  // ── Band F — Enterprise Polish (10) ────────────────────────────────────
  'workspace.polish.tooltip': () => import('./carbon-primitive-renderers').then(m => m.CarbonTooltipRenderer),
  'workspace.polish.toggletip': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggletipRenderer),
  'workspace.polish.popover': () => import('./carbon-primitive-renderers').then(m => m.CarbonPopoverRenderer),
  'workspace.polish.progress-bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonProgressBarRenderer),
  'workspace.polish.inline-loading': () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineLoadingRenderer),
  'workspace.polish.skeleton-text': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonTextRenderer),
  'workspace.polish.skeleton-placeholder': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonPlaceholderRenderer),
  'workspace.polish.context-menu': () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  'workspace.polish.file-uploader': () => import('./carbon-primitive-renderers').then(m => m.CarbonFileUploaderRenderer),
  'workspace.polish.accordion': () => import('./carbon-primitive-renderers').then(m => m.CarbonAccordionRenderer),
  'marketing.executive-kit.page': () => import('./carbon-primitive-renderers').then(m => m.CarbonModalRenderer),
  'marketing.resources.page': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'module.case_finalization.page': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'Accordion': () => import('./carbon-primitive-renderers').then(m => m.CarbonAccordionRenderer),
  'AiChatButton': () => import('./carbon-extended-renderers').then(m => m.CarbonChatButtonRenderer),
  'AiChatContainer': () => import('./carbon-extended-renderers').then(m => m.CarbonAiChatContainerRenderer),
  'AiChatCustomElement': () => import('./carbon-extended-renderers').then(m => m.CarbonAiChatElementRenderer),
  'AiLabel': () => import('./carbon-extended-renderers').then(m => m.CarbonAiLabelRenderer),
  'AiOsOverviewComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'AiSkeleton': () => import('./carbon-extended-renderers').then(m => m.CarbonAiSkeletonRenderer),
  'AspectRatio': () => import('./carbon-extended-renderers').then(m => m.CarbonAspectRatioRenderer),
  'AssertionDashboardPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'AssessmentTemplatesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'AssessmentsListPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'AuditEngagementsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'AuditFindingsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'AuditOverviewPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'AuditPlanPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'AuditReportsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'Breadcrumb': () => import('./carbon-primitive-renderers').then(m => m.CarbonBreadcrumbRenderer),
  'Button': () => import('./carbon-primitive-renderers').then(m => m.CarbonButtonRenderer),
  'ChartAlluvial': () => import('./carbon-chart-renderers').then(m => m.CarbonChartAlluvialRenderer),
  'ChartArea': () => import('./carbon-chart-renderers').then(m => m.CarbonChartAreaRenderer),
  'ChartAreaStacked': () => import('./carbon-chart-renderers').then(m => m.CarbonChartAreaStackedRenderer),
  'ChartBarGrouped': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBarGroupedRenderer),
  'ChartBarHistogram': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBarHistogramRenderer),
  'ChartBarLollipop': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBarLollipopRenderer),
  'ChartBarSimple': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBarSimpleRenderer),
  'ChartBarStacked': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBarStackedRenderer),
  'ChartBoxplot': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBoxplotRenderer),
  'ChartBubble': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBubbleRenderer),
  'ChartBullet': () => import('./carbon-chart-renderers').then(m => m.CarbonChartBulletRenderer),
  'ChartChoropleth': () => import('./carbon-chart-renderers').then(m => m.CarbonChartChoroplethRenderer),
  'ChartCirclePack': () => import('./carbon-chart-renderers').then(m => m.CarbonChartCirclePackRenderer),
  'ChartCombo': () => import('./carbon-chart-renderers').then(m => m.CarbonChartComboRenderer),
  'ChartDonut': () => import('./carbon-chart-renderers').then(m => m.CarbonChartDonutRenderer),
  'ChartGauge': () => import('./carbon-chart-renderers').then(m => m.CarbonChartGaugeRenderer),
  'ChartHeatmap': () => import('./carbon-chart-renderers').then(m => m.CarbonChartHeatmapRenderer),
  'ChartLine': () => import('./carbon-chart-renderers').then(m => m.CarbonChartLineRenderer),
  'ChartLineStacked': () => import('./carbon-chart-renderers').then(m => m.CarbonChartLineStackedRenderer),
  'ChartMeter': () => import('./carbon-chart-renderers').then(m => m.CarbonChartMeterRenderer),
  'ChartPie': () => import('./carbon-chart-renderers').then(m => m.CarbonChartPieRenderer),
  'ChartRadar': () => import('./carbon-chart-renderers').then(m => m.CarbonChartRadarRenderer),
  'ChartScatter': () => import('./carbon-chart-renderers').then(m => m.CarbonChartScatterRenderer),
  'ChartTree': () => import('./carbon-chart-renderers').then(m => m.CarbonChartTreeRenderer),
  'ChartTreemap': () => import('./carbon-chart-renderers').then(m => m.CarbonChartTreemapRenderer),
  'ChartWordCloud': () => import('./carbon-chart-renderers').then(m => m.CarbonChartWordcloudRenderer),
  'Checkbox': () => import('./carbon-primitive-renderers').then(m => m.CarbonCheckboxRenderer),
  'ClickableTile': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'CodeSnippet': () => import('./carbon-extended-renderers').then(m => m.CarbonCodeSnippetRenderer),
  'Column': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'ComboBox': () => import('./carbon-primitive-renderers').then(m => m.CarbonComboBoxRenderer),
  'ComboButton': () => import('./carbon-extended-renderers').then(m => m.CarbonComboButtonRenderer),
  'ComplianceAdminPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceAssessmentsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceAttestationsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceCalendarPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceCatchAll': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceControlDetailPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceControlsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceDiagnosticsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceEvidenceOpsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceEvidencePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceExceptionsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceFindingsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceFrameworksPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceGapsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceHeatmapPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceHome': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceKsaPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceObligationsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceOverviewPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'CompliancePosturePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceRegulatorPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceRegulatoryChangesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceReportsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceRoadmapPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceSavingsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ComplianceTemplatesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ComplianceWorkQueuePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ContainedList': () => import('./carbon-extended-renderers').then(m => m.CarbonContainedListRenderer),
  'Content': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'ContentPackPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'ContentSwitcher': () => import('./carbon-extended-renderers').then(m => m.CarbonContentSwitcherRenderer),
  'ContextMenu': () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  'ControlPosturePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ControlTestingPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ControlsHomePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ControlsLibraryPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ControlsMappingPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ControlsMonitoringPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ControlsTestingPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'DataTable': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'DatePicker': () => import('./carbon-primitive-renderers').then(m => m.CarbonDatePickerRenderer),
  'DatePickerInput': () => import('./carbon-primitive-renderers').then(m => m.CarbonDatePickerRenderer),
  'Dialog': () => import('./carbon-extended-renderers').then(m => m.CarbonDialogRenderer),
  'Dropdown': () => import('./carbon-primitive-renderers').then(m => m.CarbonDropdownRenderer),
  'EsgPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'EthicsIntegrityPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'EvidenceCatalogPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'EvidenceOverviewPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'EvidenceRequestsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'EvidenceReviewsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'EvidenceTasksPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ExceptionManagerPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ExpandableTile': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FileUploader': () => import('./carbon-primitive-renderers').then(m => m.CarbonFileUploaderRenderer),
  'FoundationAccessReviewComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationAuditComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationBusinessUnitsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationCommitteesComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationDataProcessingComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationDelegationsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationDepartmentsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationLocationsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationOperationsReadinessComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FoundationOrganizationComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FoundationOverviewComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FoundationOwnershipMappingComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationPermissionMatrixComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationPoliciesComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationPoliciesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationPositionsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationReferenceDataComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationRoleDetailComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FoundationRolesComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationSettingsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FoundationTeamsComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FoundationUsersComponent': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FrameworkHubPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'FrameworkMappingPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'FrameworkScorecardPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'GenericModuleLifecycle': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'Grid': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'Header': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderGlobalAction': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderGlobalBar': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderMenu': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderMenuItem': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderName': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'HeaderNavigation': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'Icon': () => import('./carbon-extended-renderers').then(m => m.CarbonIconRenderer),
  'IconButton': () => import('./carbon-primitive-renderers').then(m => m.CarbonButtonRenderer),
  'InlineLoading': () => import('./carbon-primitive-renderers').then(m => m.CarbonInlineLoadingRenderer),
  'InlineNotification': () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'IntelligenceHubPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'KnowledgeHubPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'KsaHubPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'Layer': () => import('./carbon-primitive-renderers').then(m => m.CarbonLayerRenderer),
  'Link': () => import('./carbon-extended-renderers').then(m => m.CarbonLinkRenderer),
  'List': () => import('./carbon-extended-renderers').then(m => m.CarbonListRenderer),
  'Loading': () => import('./carbon-extended-renderers').then(m => m.CarbonLoadingRenderer),
  'MappingPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'MaturityJourneyPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'MaturityWizardPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'MenuButton': () => import('./carbon-extended-renderers').then(m => m.CarbonMenuButtonRenderer),
  'Modal': () => import('./carbon-primitive-renderers').then(m => m.CarbonModalRenderer),
  'MultiSelect': () => import('./carbon-primitive-renderers').then(m => m.CarbonComboBoxRenderer),
  'NcaAssessmentPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'NumberInput': () => import('./carbon-primitive-renderers').then(m => m.CarbonNumberInputRenderer),
  'ObligationDetailPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ObligationWorkspacePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'OntologyCatalogPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'OpsHome': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'OverflowMenu': () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  'OverflowMenuOption': () => import('./carbon-primitive-renderers').then(m => m.CarbonContextMenuRenderer),
  'Pagination': () => import('./carbon-primitive-renderers').then(m => m.CarbonPaginationRenderer),
  'PolicyHomePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'Popover': () => import('./carbon-primitive-renderers').then(m => m.CarbonPopoverRenderer),
  'ProductWcAboutModal': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcAboutModalRenderer),
  'ProductWcActionSet': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcActionSetRenderer),
  'ProductWcBigNumber': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcBigNumberRenderer),
  'ProductWcChecklist': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcChecklistRenderer),
  'ProductWcCoachmark': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcCoachmarkRenderer),
  'ProductWcFullPageError': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcFullPageErrorRenderer),
  'ProductWcGuideBanner': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcGuideBannerRenderer),
  'ProductWcInterstitialScreen': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcInterstitialScreenRenderer),
  'ProductWcNotificationsPanel': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcNotificationsPanelRenderer),
  'ProductWcOptionsTile': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcOptionsTileRenderer),
  'ProductWcPageHeader': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcPageHeaderRenderer),
  'ProductWcSidePanel': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcSidePanelRenderer),
  'ProductWcTearsheet': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcTearsheetRenderer),
  'ProductWcTearsheetPreview': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcTearsheetPreviewRenderer),
  'ProductWcTruncatedText': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcTruncatedTextRenderer),
  'ProductWcUserAvatar': () => import('./carbon-extended-renderers').then(m => m.CarbonPwcUserAvatarRenderer),
  'ProgressBar': () => import('./carbon-primitive-renderers').then(m => m.CarbonProgressBarRenderer),
  'ProgressIndicator': () => import('./carbon-extended-renderers').then(m => m.CarbonProgressIndicatorRenderer),
  'Radio': () => import('./carbon-primitive-renderers').then(m => m.CarbonRadioRenderer),
  'RcsaCampaignsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'RegistryPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'RegulationCompilerPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'RegulatoryDeltaDashboardPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'RegulatoryFeedsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'RegulatoryReasoningStudioPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ReportsOverviewPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'RiskAssessmentsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'RiskHeatmapPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'RiskOverviewPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'RiskRegisterPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'RiskTreatmentsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'SamaAssessmentPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ScoringPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ScoringPoliciesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'ScoringPolicyDetailPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'Search': () => import('./carbon-primitive-renderers').then(m => m.CarbonSearchRenderer),
  'Select': () => import('./carbon-primitive-renderers').then(m => m.CarbonSelectRenderer),
  'ShahinProfilePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ShahinSettingsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ShahinTenantProfilePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'ShahinTenantSettingsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'SideNav': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'SideNavItems': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'SideNavLink': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'SideNavMenu': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'SideNavMenuItem': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'SkeletonPlaceholder': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonTextRenderer),
  'SkeletonText': () => import('./carbon-primitive-renderers').then(m => m.CarbonSkeletonTextRenderer),
  'Slider': () => import('./carbon-extended-renderers').then(m => m.CarbonSliderRenderer),
  'SoxCompliancePage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'StructuredList': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'Tab': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'TableBatchActions': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'TableToolbar': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'TableToolbarActions': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'TableToolbarSearch': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'Tabs': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'Tag': () => import('./carbon-primitive-renderers').then(m => m.CarbonTagRenderer),
  'TaxonomyPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'TextArea': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextInputRenderer),
  'TextInput': () => import('./carbon-primitive-renderers').then(m => m.CarbonTextInputRenderer),
  'Tile': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'TimePicker': () => import('./carbon-extended-renderers').then(m => m.CarbonTimePickerRenderer),
  'TimePickerSelect': () => import('./carbon-extended-renderers').then(m => m.CarbonTimePickerSelectRenderer),
  'ToastNotification': () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'Toggle': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggleRenderer),
  'Toggletip': () => import('./carbon-primitive-renderers').then(m => m.CarbonToggletipRenderer),
  'Tooltip': () => import('./carbon-primitive-renderers').then(m => m.CarbonTooltipRenderer),
  'TreeView': () => import('./carbon-extended-renderers').then(m => m.CarbonTreeViewRenderer),
  'UIShell': () => import('./carbon-primitive-renderers').then(m => m.CarbonUIShellRenderer),
  'UcfBrowserPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'WcBadgeIndicator': () => import('./carbon-extended-renderers').then(m => m.CarbonBadgeIndicatorRenderer),
  'WcCopy': () => import('./carbon-extended-renderers').then(m => m.CarbonCopyRenderer),
  'WcFeatureFlags': () => import('./carbon-extended-renderers').then(m => m.CarbonFeatureFlagsRenderer),
  'WcFloatingMenu': () => import('./carbon-extended-renderers').then(m => m.CarbonFloatingMenuRenderer),
  'WcFluidComboBox': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidComboBoxRenderer),
  'WcFluidDropdown': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidDropdownRenderer),
  'WcFluidMultiSelect': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidMultiSelectRenderer),
  'WcFluidNumberInput': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidNumberInputRenderer),
  'WcFluidPasswordInput': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidPasswordInputRenderer),
  'WcFluidSearch': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidSearchRenderer),
  'WcFluidSelect': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidSelectRenderer),
  'WcFluidTextInput': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidTextInputRenderer),
  'WcFluidTextarea': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidTextareaRenderer),
  'WcFluidTimePicker': () => import('./carbon-extended-renderers').then(m => m.CarbonFluidTimePickerRenderer),
  'WcFormGroup': () => import('./carbon-extended-renderers').then(m => m.CarbonFormGroupRenderer),
  'WcHeading': () => import('./carbon-extended-renderers').then(m => m.CarbonHeadingRenderer),
  'WcIconButton': () => import('./carbon-extended-renderers').then(m => m.CarbonWcIconButtonRenderer),
  'WcIconIndicator': () => import('./carbon-extended-renderers').then(m => m.CarbonIconIndicatorRenderer),
  'WcPageHeader': () => import('./carbon-extended-renderers').then(m => m.CarbonWcPageHeaderRenderer),
  'WcPaginationNav': () => import('./carbon-extended-renderers').then(m => m.CarbonPaginationNavRenderer),
  'WcShapeIndicator': () => import('./carbon-extended-renderers').then(m => m.CarbonShapeIndicatorRenderer),
  'WcSidePanel': () => import('./carbon-extended-renderers').then(m => m.CarbonSidePanelRenderer),
  'WcSkipToContent': () => import('./carbon-extended-renderers').then(m => m.CarbonSkipToContentRenderer),
  'WcStack': () => import('./carbon-extended-renderers').then(m => m.CarbonStackRenderer),
  'WcTearsheet': () => import('./carbon-extended-renderers').then(m => m.CarbonTearsheetRenderer),
  'WorkflowAnalyticsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'WorkflowDesignerPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'WorkflowExecutionsPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'WorkflowHubPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'WorkflowListPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'WorkflowTemplatesPage': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'audit-timeline.access': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'audit-timeline.ai': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.cfg': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.dauth': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.dnoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.dos': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.dsoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.fnd': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.mtm': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.runtime': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'audit-timeline.tm': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'audit-timeline.ui-system': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'command-center.ai': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.cfg': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.dnoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.dos': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.dsoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.fnd': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.identity-summary': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.mtm': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'command-center.tm': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'matrix.health': () => import('../../core/platform/shell/templates/module-heatmap.template').then(m => m.ModuleHeatmapTemplateComponent),
  'matrix.permissions': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'module.alerts_panel': () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'module.audit_trail': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'module.copilot_panel': () => import('./carbon-extended-renderers').then(m => m.CarbonAiChatContainerRenderer),
  'module.data_preview': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'module.empty_state': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'module.entry': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'module.entry.page': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'module.error_state': () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'module.filters_bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonDropdownRenderer),
  'module.health_strip': () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'module.kpi_card': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'module.kpi_grid': () => import('./carbon-primitive-renderers').then(m => m.CarbonGridRenderer),
  'module.loading_state': () => import('./carbon-extended-renderers').then(m => m.CarbonLoadingRenderer),
  'module.overview': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),
  'module.overview.page': () => import('./module-pages/module-overview-page.component').then(m => m.ModuleOverviewPageComponent),
  'module.page_header': () => import('./carbon-extended-renderers').then(m => m.CarbonWcPageHeaderRenderer),
  'module.quick_actions': () => import('./carbon-extended-renderers').then(m => m.CarbonComboButtonRenderer),
  'module.recent_activity': () => import('./carbon-primitive-renderers').then(m => m.CarbonStructuredListRenderer),
  'module.records.page': () => import('./module-pages/module-records-page.component').then(m => m.ModuleRecordsPageComponent),
  'module.records_table': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'module.reports.page': () => import('./module-pages/module-reports-page.component').then(m => m.ModuleReportsPageComponent),
  'module.search_bar': () => import('./carbon-primitive-renderers').then(m => m.CarbonSearchRenderer),
  'module.settings.page': () => import('./module-pages/module-settings-page.component').then(m => m.ModuleSettingsPageComponent),
  'module.tabs': () => import('./carbon-primitive-renderers').then(m => m.CarbonTabsRenderer),
  'module.work_queue': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'module.workflows.page': () => import('./module-pages/module-workflows-page.component').then(m => m.ModuleWorkflowsPageComponent),
  'page-masthead.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'page-masthead.settings': () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.ai-platform.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.ai-platform.engine': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.ai-platform.gateway': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.ai-platform.governance': () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.ai-platform.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'dynamic-ui.components': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'dynamic-ui.contracts': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'dynamic-ui.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'dynamic-ui.routes': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.config-center.audit': () =>
    import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.AuditTrailLedgerTemplateComponent),
  'platform.config-center.compare': () =>
    import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.config-center.flags': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.config-center.gateway': () =>
    import('../../core/platform/shell/templates/module-trend-intelligence.template').then(m => m.TrendIntelligenceTemplateComponent),
  'platform.config-center.health': () =>
    import('../../core/platform/shell/templates/module-trend-intelligence.template').then(m => m.TrendIntelligenceTemplateComponent),
  'platform.config-center.hub': () =>
    import('../../core/platform/shell/templates/module-decision-dashboard.template').then(m => m.DecisionDashboardTemplateComponent),
  'platform.config-center.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.config-center.resolve': () =>
    import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.config-center.settings': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.config-center.tokens': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.config-center.workspace': () =>
    import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.dauth.audit.list': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dauth.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.dauth.perms.list': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dauth.roles.list': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dauth.users.list': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dnoc.alerts': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dnoc.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dnoc.metrics': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.dnoc.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.dnoc.services': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dos-platform.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dos-platform.events': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dos-platform.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.dos-platform.registries': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dos-platform.schemas': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dsoc.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dsoc.detections': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dsoc.incidents': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.dsoc.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.dsoc.policies': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.foundation-admin.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.foundation-admin.lifecycle': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.foundation-admin.organizations': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.foundation-admin.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.foundation-admin.persons': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.multi-tenant-mgmt.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.multi-tenant-mgmt.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.multi-tenant-mgmt.provisioning': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.multi-tenant-mgmt.quotas': () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'platform.multi-tenant-mgmt.tenants': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.tenant-management.audit': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.tenant-management.directory': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.tenant-management.members': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'platform.tenant-management.overview': () => import('../../core/platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'platform.tenant-management.profile': () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'smart-grid.ai': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.cfg': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.components': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'smart-grid.dnoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.dos': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.dsoc': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.fnd': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.mtm': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.permissions': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'smart-grid.roles': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.services': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'smart-grid.sessions': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'smart-grid.themes': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'smart-grid.tm': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),
  'smart-grid.users': () => import('./carbon-primitive-renderers').then(m => m.CarbonDataTableRenderer),

  // ── 31-archetype roster patch (Phase F) ─────────────────────────────────
  // 24 component_keys seeded by 20260503_0019_phase_f_archetype_registry_seed.sql
  // Each maps to its canonical template export from
  // `platform/core/platform/shell/templates/`. Mirrors:
  //   • ARCHETYPE_REGISTRY in module-template.types.ts
  //   • mapComponentKeyToArchetype() in scripts/ui-registry/lib/archetype-map.mjs
  //   • LOADERS in platform/core/platform/shell/template-binding.registry.ts
  // B — Insight
  'module.posture.page': () => import('../../core/platform/shell/templates/module-posture-overview.template').then(m => m.PostureOverviewTemplateComponent),
  'module.trends.page': () => import('../../core/platform/shell/templates/module-trend-intelligence.template').then(m => m.TrendIntelligenceTemplateComponent),
  'module.dashboard.page': () => import('../../core/platform/shell/templates/module-decision-dashboard.template').then(m => m.DecisionDashboardTemplateComponent),
  'module.command_dashboard.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.CommandDashboardTemplateComponent),
  // C — Records
  'module.heatmap.page': () => import('../../core/platform/shell/templates/module-heatmap.template').then(m => m.ModuleHeatmapTemplateComponent),
  'module.record.detail.page': () => import('../../core/platform/shell/templates/module-record-story.template').then(m => m.RecordStoryTemplateComponent),
  'module.record.create.page': () => import('../../core/platform/shell/templates/module-guided-create.template').then(m => m.GuidedCreateTemplateComponent),
  // D — Work
  'module.workflow_timeline.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.WorkflowTimelineTemplateComponent),
  'module.followup_center.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.FollowUpCenterTemplateComponent),
  // E — Evidence
  'module.export.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.ExportCenterTemplateComponent),
  'module.audit_trail_ledger.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.AuditTrailLedgerTemplateComponent),
  'module.audit_evidence.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.AuditTrailEvidenceTemplateComponent),
  // F — Time / Plan
  'module.calendar.page': () => import('../../core/platform/shell/templates/module-calendar-timeline.template').then(m => m.CalendarTimelineTemplateComponent),
  'module.compliance_calendar.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.ComplianceCalendarTemplateComponent),
  'module.roadmap.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.RemediationRoadmapTemplateComponent),
  // G — Governance
  'module.org_chart.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'module.ownership_map.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.OwnershipMapTemplateComponent),
  'module.delegation_center.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.DelegationCenterTemplateComponent),
  // H — Agentic
  'module.ai.advisor.page': () => import('../../core/platform/shell/templates/module-ai-advisor.template').then(m => m.AiAdvisorTemplateComponent),
  'module.agent_flow.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.AgentFlowTemplateComponent),
  'module.agent_registry.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.AgentRegistryTemplateComponent),
  'module.user_agent_workbench.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.UserAgentWorkbenchTemplateComponent),
  // J — Onboarding
  'module.activation.page': () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleOnboardingTemplateComponent),
  // K — Operational P0
  'module.incident_response.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.IncidentResponseTemplateComponent),

  // Phase G tail (block B) — orphaned binding hygiene
  'compliance.controls.list.page': () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),

  // ── Utility-pages seed (20260503_0022) — 8 dedicated surfaces ───────────
  // User Profile + Tenant Profile reuse the 360° Record Story renderer.
  'module.user_profile.page':        () => import('../../core/platform/shell/templates/module-record-story.template').then(m => m.RecordStoryTemplateComponent),
  'module.tenant_profile.page':      () => import('../../core/platform/shell/templates/module-record-story.template').then(m => m.RecordStoryTemplateComponent),
  // Tenant Settings reuses the canonical Module Settings tabbed renderer.
  'module.tenant_settings.page':     () => import('../../core/platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  // Tenant Services is a managed list (Intelligent Register).
  'module.tenant_services.page':     () => import('../../core/platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  // Platform Settings is an executive command surface (Command Dashboard).
  'platform.platform_settings.page': () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.CommandDashboardTemplateComponent),
  // Platform consoles: DAuth = decision; DNOC + DSOC = command-room.
  'platform.dauth.console':          () => import('../../core/platform/shell/templates/module-decision-dashboard.template').then(m => m.DecisionDashboardTemplateComponent),
  'platform.dnoc.console':           () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.CommandDashboardTemplateComponent),
  'platform.dsoc.console':           () => import('../../core/platform/shell/templates/module-archetypes-extended.templates').then(m => m.CommandDashboardTemplateComponent),

  // ── Phase M0.5 — Agentic UI Interaction Layer (10 components) ───────────
  // Each agent.* component_key maps to its standalone Dos*Component from
  // @dos/ui-system/agentic. Components emit events; workflow services execute.
  // Carbon backing per row is enforced by 20260503_0024_agentic_ui_components.sql.
  'agent.status-strip':          () => import('@dos/ui-system').then(m => m.DosAgentStatusStripComponent),
  'agent.card':                  () => import('@dos/ui-system').then(m => m.DosAgentCardComponent),
  'agent.activity-flow':         () => import('@dos/ui-system').then(m => m.DosAgentActivityFlowComponent),
  'agent.task-queue':            () => import('@dos/ui-system').then(m => m.DosAgentTaskQueueComponent),
  'agent.recommendation-panel':  () => import('@dos/ui-system').then(m => m.DosAgentRecommendationPanelComponent),
  'agent.action-approval-modal': () => import('@dos/ui-system').then(m => m.DosAgentActionApprovalModalComponent),
  'agent.workbench':             () => import('@dos/ui-system').then(m => m.DosAgentWorkbenchComponent),
  'agent.evidence-drawer':       () => import('@dos/ui-system').then(m => m.DosAgentEvidenceDrawerComponent),
  'agent.followup-center':       () => import('@dos/ui-system').then(m => m.DosAgentFollowupCenterComponent),
  'agent.audit-trail':           () => import('@dos/ui-system').then(m => m.DosAgentAuditTrailComponent),

  // ── Phase M1 — Marketing-OS public landing ──────────────────────────────
  // 17-section unauthenticated landing rendered from @dos/ui-system. Carbon
  // backing: tiles. Route binding: /  → marketing.home.page.
  'marketing.home.page':         () => import('@dos/ui-system').then(m => m.DosMarketingHomePageComponent),

  // ── Phase M1.5 — Download-Kit components ────────────────────────────────
  // Card / gated modal / success states for the public download flow.
  // Carbon backing per row enforced by 20260503_0027_marketing_download_kit.sql.
  'marketing.download-kit-card':    () => import('@dos/ui-system').then(m => m.DosDownloadKitCardComponent),
  'marketing.gated-download-modal': () => import('@dos/ui-system').then(m => m.DosGatedDownloadModalComponent),
  'marketing.download-success':     () => import('@dos/ui-system').then(m => m.DosDownloadSuccessComponent),

  // ── Phase M2 — Public marketing pages (pricing/trust/security/contact/about/legal)
  // Public, tenantless, no AccessStore, no permission_key. Carbon backing: tiles.
  // Registered by 20260504_0090_marketing_public_pages.sql.
  'marketing.pricing.page':  () => import('@dos/ui-system').then(m => m.DosMarketingPricingPageComponent),
  'marketing.trust.page':    () => import('@dos/ui-system').then(m => m.DosMarketingTrustPageComponent),
  'marketing.security.page': () => import('@dos/ui-system').then(m => m.DosMarketingSecurityPageComponent),
  'marketing.contact.page':  () => import('@dos/ui-system').then(m => m.DosMarketingContactPageComponent),
  'marketing.about.page':    () => import('@dos/ui-system').then(m => m.DosMarketingAboutPageComponent),
  'marketing.legal.page':    () => import('@dos/ui-system').then(m => m.DosMarketingLegalPageComponent),

  // ── Gap-audit additions (20260504_0400_marketing_gap_registry.sql) ────────
  // platform.page: new route added Wave 4; carbon_key=tabs, aliases pricing template
  // until a dedicated MarketingPlatformTemplateComponent is built.
  'marketing.platform.page':   () => import('@dos/ui-system').then(m => m.DosMarketingPricingPageComponent),
  // Section-level registry entries — each aliases the renderer for its carbon_key.
  'marketing.logos.section':   () => import('./carbon-extended-renderers').then(m => m.CarbonContainedListRenderer),
  'marketing.trust.section':   () => import('./carbon-extended-renderers').then(m => m.CarbonNotificationRenderer),
  'marketing.agentic.section': () => import('./carbon-primitive-renderers').then(m => m.CarbonTileRenderer),


  // ── Phase M1.6 — Carbon Auth Pages Pack (5 pages + 19 primitives) ───────
  // Carbon backing per row enforced by 20260503_0028_auth_pages_pack.sql.
  'auth.shell':                  () => import('@dos/ui-system').then(m => m.DosAuthShellComponent),
  'auth.brand-panel':            () => import('@dos/ui-system').then(m => m.DosAuthBrandPanelComponent),
  'auth.login-card':             () => import('@dos/ui-system').then(m => m.DosAuthLoginCardComponent),
  'auth.register-card':          () => import('@dos/ui-system').then(m => m.DosAuthRegisterCardComponent),
  'auth.forgot-password-card':   () => import('@dos/ui-system').then(m => m.DosAuthForgotPasswordCardComponent),
  'auth.reset-password-card':    () => import('@dos/ui-system').then(m => m.DosAuthResetPasswordCardComponent),
  'auth.mfa-card':               () => import('@dos/ui-system').then(m => m.DosAuthMfaCardComponent),
  'auth.field':                  () => import('@dos/ui-system').then(m => m.DosAuthFieldComponent),
  'auth.password-field':         () => import('@dos/ui-system').then(m => m.DosAuthPasswordFieldComponent),
  'auth.dropdown':               () => import('@dos/ui-system').then(m => m.DosAuthDropdownComponent),
  'auth.checkbox':               () => import('@dos/ui-system').then(m => m.DosAuthCheckboxComponent),
  'auth.submit':                 () => import('@dos/ui-system').then(m => m.DosAuthSubmitComponent),
  'auth.sso-actions':            () => import('@dos/ui-system').then(m => m.DosAuthSsoActionsComponent),
  'auth.notification':           () => import('@dos/ui-system').then(m => m.DosAuthNotificationComponent),
  'auth.progress':               () => import('@dos/ui-system').then(m => m.DosAuthProgressComponent),
  'auth.help':                   () => import('@dos/ui-system').then(m => m.DosAuthHelpComponent),
  'auth.language-toggle':        () => import('@dos/ui-system').then(m => m.DosAuthLanguageToggleComponent),
  'auth.security-note':          () => import('@dos/ui-system').then(m => m.DosAuthSecurityNoteComponent),
  'auth.skeleton':               () => import('@dos/ui-system').then(m => m.DosAuthSkeletonComponent),
  'auth.login.page':             () => import('@dos/ui-system').then(m => m.DosAuthLoginPageComponent),
  'auth.register.page':          () => import('@dos/ui-system').then(m => m.DosAuthRegisterPageComponent),
  'auth.forgot-password.page':   () => import('@dos/ui-system').then(m => m.DosAuthForgotPasswordPageComponent),
  'auth.mfa.page':               () => import('@dos/ui-system').then(m => m.DosAuthMfaPageComponent),
  'auth.reset-password.page':    () => import('@dos/ui-system').then(m => m.DosAuthResetPasswordPageComponent),

  // ── Phase F-FOUND — Foundation pages pack (21 canonical pages) ──────────
  // Carbon backing per row enforced by 20260503_0029_foundation_pages_pack.sql.
  // Page components live in platform/foundation/ui/pages/*.component.ts and
  // are re-exported through the `@dos/module-foundation/ui` subpath
  // (declared in platform/foundation/package.json#exports). The root barrel
  // is backend-only — never import Angular components from there.
  // Template-Only Routing rule §3.1 — all `foundation.*.page` keys now
  // resolve to canonical 32-archetype templates. Migrations 0040/0050/0060
  // already rewrote dos.dynamic_ui_routes.component_key for foundation
  // URLs to `module.*.page` keys; these legacy aliases stay so any tool
  // that joins on the old foundation.*.page key still resolves to a real
  // archetype renderer instead of a bespoke Foundation*Component class.
  'foundation.overview.page':        () => import('@platform/shell/templates/module-overview.template').then(m => m.ModuleOverviewTemplateComponent),
  'foundation.organization.page':    () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'foundation.business-units.page':  () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'foundation.departments.page':     () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'foundation.positions.page':       () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.locations.page':       () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.users.page':           () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.teams.page':           () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'foundation.roles.page':           () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.permissions.page':     () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OwnershipMapTemplateComponent),
  'foundation.committees.page':      () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.delegations.page':     () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.DelegationCenterTemplateComponent),
  'foundation.access-review.page':   () => import('@platform/shell/templates/module-extra.templates').then(m => m.ModuleAssessmentsTemplateComponent),
  'foundation.policies.page':        () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.audit.page':           () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.AuditTrailLedgerTemplateComponent),
  'foundation.ownership.page':       () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OwnershipMapTemplateComponent),
  'foundation.sod.page':             () => import('@platform/shell/templates/module-extra.templates').then(m => m.ModuleSettingsTemplateComponent),
  'foundation.hierarchy-viz.page':   () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.OrgChartTemplateComponent),
  'foundation.user-lifecycle.page':  () => import('@platform/shell/templates/module-archetypes-extended.templates').then(m => m.WorkflowTimelineTemplateComponent),
  'foundation.reference-data.page':  () => import('@platform/shell/templates/module-records.template').then(m => m.ModuleRecordsTemplateComponent),
  'foundation.diagnostics.page':     () => import('@platform/shell/templates/module-posture-overview.template').then(m => m.PostureOverviewTemplateComponent),

  // Approved-template aliases — registered in dos.dynamic_ui_component_registry by
  // 20260505_1800_register_approved_template_components.sql and emitted as
  // ui_route_template_binding.template_export by the canonical publisher
  // (sql-emitter.mjs). Each maps the FE component name 1:1 to its real export
  // in @platform/shell/templates barrel.
  'ModuleOverviewTemplateComponent':       () => import('../../core/platform/shell/templates').then(m => m.ModuleOverviewTemplateComponent),
  'PostureOverviewTemplateComponent':      () => import('../../core/platform/shell/templates').then(m => m.PostureOverviewTemplateComponent),
  'TrendIntelligenceTemplateComponent':    () => import('../../core/platform/shell/templates').then(m => m.TrendIntelligenceTemplateComponent),
  'DecisionDashboardTemplateComponent':    () => import('../../core/platform/shell/templates').then(m => m.DecisionDashboardTemplateComponent),
  'CommandDashboardTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.CommandDashboardTemplateComponent),
  'ModuleRecordsTemplateComponent':        () => import('../../core/platform/shell/templates').then(m => m.ModuleRecordsTemplateComponent),
  'ModuleHeatmapTemplateComponent':        () => import('../../core/platform/shell/templates').then(m => m.ModuleHeatmapTemplateComponent),
  'RecordStoryTemplateComponent':          () => import('../../core/platform/shell/templates').then(m => m.RecordStoryTemplateComponent),
  'GuidedCreateTemplateComponent':         () => import('../../core/platform/shell/templates').then(m => m.GuidedCreateTemplateComponent),
  'ModuleWorkQueueTemplateComponent':      () => import('../../core/platform/shell/templates').then(m => m.ModuleWorkQueueTemplateComponent),
  'ModuleAssessmentsTemplateComponent':    () => import('../../core/platform/shell/templates').then(m => m.ModuleAssessmentsTemplateComponent),
  'WorkflowTimelineTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.WorkflowTimelineTemplateComponent),
  'FollowUpCenterTemplateComponent':       () => import('../../core/platform/shell/templates').then(m => m.FollowUpCenterTemplateComponent),
  'ModuleReportsTemplateComponent':        () => import('../../core/platform/shell/templates').then(m => m.ModuleReportsTemplateComponent),
  'ExportCenterTemplateComponent':         () => import('../../core/platform/shell/templates').then(m => m.ExportCenterTemplateComponent),
  'AuditTrailTemplateComponent':           () => import('../../core/platform/shell/templates').then(m => m.AuditTrailTemplateComponent),
  'AuditTrailLedgerTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.AuditTrailLedgerTemplateComponent),
  'AuditTrailEvidenceTemplateComponent':   () => import('../../core/platform/shell/templates').then(m => m.AuditTrailEvidenceTemplateComponent),
  'CalendarTimelineTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.CalendarTimelineTemplateComponent),
  'ComplianceCalendarTemplateComponent':   () => import('../../core/platform/shell/templates').then(m => m.ComplianceCalendarTemplateComponent),
  'RemediationRoadmapTemplateComponent':   () => import('../../core/platform/shell/templates').then(m => m.RemediationRoadmapTemplateComponent),
  'OrgChartTemplateComponent':             () => import('../../core/platform/shell/templates').then(m => m.OrgChartTemplateComponent),
  'OwnershipMapTemplateComponent':         () => import('../../core/platform/shell/templates').then(m => m.OwnershipMapTemplateComponent),
  'DelegationCenterTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.DelegationCenterTemplateComponent),
  'AiAdvisorTemplateComponent':            () => import('../../core/platform/shell/templates').then(m => m.AiAdvisorTemplateComponent),
  'AgentFlowTemplateComponent':            () => import('../../core/platform/shell/templates').then(m => m.AgentFlowTemplateComponent),
  'AgentRegistryTemplateComponent':        () => import('../../core/platform/shell/templates').then(m => m.AgentRegistryTemplateComponent),
  'UserAgentWorkbenchTemplateComponent':   () => import('../../core/platform/shell/templates').then(m => m.UserAgentWorkbenchTemplateComponent),
  'ModuleSettingsTemplateComponent':       () => import('../../core/platform/shell/templates').then(m => m.ModuleSettingsTemplateComponent),
  'ActivationJourneyTemplateComponent':    () => import('../../core/platform/shell/templates').then(m => m.ActivationJourneyTemplateComponent),
  'IncidentResponseTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.IncidentResponseTemplateComponent),
  'CaseFinalizationTemplateComponent':     () => import('../../core/platform/shell/templates').then(m => m.CaseFinalizationTemplateComponent),
};

const PRIMITIVE_KEYS = new Set(Object.keys(CARBON_PRIMITIVE_COMPONENT_MAP));

export const COMPONENT_MAP_DUPLICATE_PRIMITIVE_KEYS = Object.keys(REGISTRY_COMPONENT_MAP)
  .filter((key) => PRIMITIVE_KEYS.has(key));

const REGISTRY_COMPONENT_MAP_WITHOUT_PRIMITIVE_OVERRIDES: Record<string, () => Promise<Type<any>>> =
  Object.fromEntries(
    Object.entries(REGISTRY_COMPONENT_MAP).filter(([key]) => !PRIMITIVE_KEYS.has(key)),
  );

export const COMPONENT_MAP: Record<string, () => Promise<Type<any>>> = {
  ...REGISTRY_COMPONENT_MAP_WITHOUT_PRIMITIVE_OVERRIDES,
  ...CARBON_PRIMITIVE_COMPONENT_MAP,
};
