-- dos:extracted-from: ops/migrations/tenant/027_tenant_schema_tables.sql
-- dos:supersedes-checksum: b618781c42608331e3344799991235a22afbb73ab72c9789ef6478fd164416c8
-- dos:owning-module: policy
-- dos:tables: policy_acknowledgements, policy_approvals, policy_audit_trail, policy_categories, policy_distribution_lists, policy_distribution_tracking, policy_documents, policy_endorsements, policy_exceptions, policy_feedback, policy_library, policy_mappings, policy_portal_config, policy_renewals, policy_retirements, policy_review_cycles, policy_settings, policy_templates, policy_versions
-- dos:statement-count: 38
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_documents" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_documents_tenant ON "__TENANT_SCHEMA__"."policy_documents" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_versions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_versions_tenant ON "__TENANT_SCHEMA__"."policy_versions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_approvals" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_approvals_tenant ON "__TENANT_SCHEMA__"."policy_approvals" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_library" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_library_tenant ON "__TENANT_SCHEMA__"."policy_library" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_review_cycles" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_review_cycles_tenant ON "__TENANT_SCHEMA__"."policy_review_cycles" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_distribution_tracking" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_distribution_tracking_tenant ON "__TENANT_SCHEMA__"."policy_distribution_tracking" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_acknowledgements" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_acknowledgements_tenant ON "__TENANT_SCHEMA__"."policy_acknowledgements" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_templates" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_templates_tenant ON "__TENANT_SCHEMA__"."policy_templates" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_categories" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_categories_tenant ON "__TENANT_SCHEMA__"."policy_categories" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_mappings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_mappings_tenant ON "__TENANT_SCHEMA__"."policy_mappings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_settings_tenant ON "__TENANT_SCHEMA__"."policy_settings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_audit_trail" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_audit_trail_tenant ON "__TENANT_SCHEMA__"."policy_audit_trail" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_portal_config" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_portal_config_tenant ON "__TENANT_SCHEMA__"."policy_portal_config" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_distribution_lists" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_distribution_lists_tenant ON "__TENANT_SCHEMA__"."policy_distribution_lists" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_feedback" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_feedback_tenant ON "__TENANT_SCHEMA__"."policy_feedback" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_exceptions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_exceptions_tenant ON "__TENANT_SCHEMA__"."policy_exceptions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_endorsements" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_endorsements_tenant ON "__TENANT_SCHEMA__"."policy_endorsements" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_renewals" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_renewals_tenant ON "__TENANT_SCHEMA__"."policy_renewals" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."policy_retirements" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_policy_retirements_tenant ON "__TENANT_SCHEMA__"."policy_retirements" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;
