module.exports = {
  apps: [{
    name: 'gateway',
    script: 'dist/server.js',
    instances: 2,
    exec_mode: 'cluster',
    env: {
      NODE_ENV: 'production',
      PORT: 4000,
      LOG_LEVEL: 'info',
      AUTH_SERVICE_URL: 'https://127.0.0.1:4001',
      // L34 (Phase 4) — tenant-zone mTLS (separate CA from admin zone).
      TENANT_MTLS_ENFORCE: '1',
      TENANT_MTLS_CA: '/root/DOS-Platform/platform/config-center/secrets/tenant-mtls/ca.crt',
      TENANT_MTLS_GATEWAY_CERT: '/root/DOS-Platform/platform/config-center/secrets/tenant-mtls/gateway-client.crt',
      TENANT_MTLS_GATEWAY_KEY: '/root/DOS-Platform/platform/config-center/secrets/tenant-mtls/gateway-client.key',
      TENANT_MTLS_REJECT_UNAUTHORIZED: '1',
      // L37-C (Phase 4) — per-tenant Redis sliding-window rate limiter.
      // Reads dos.platform_session_policy.rate_limit_per_minute (60s window).
      TENANT_RATE_LIMIT_ENFORCE: '1',
      RATE_LIMIT_REDIS_URL: 'redis://:d57921272933f2d3a94a6f1fbf42982791b8afdd74f96f89@127.0.0.1:6379/0',
      RATE_LIMIT_PREFIX: 'dos:rl:',
      TENANT_SERVICE_URL: 'http://127.0.0.1:4002',
      USER_SERVICE_URL: 'http://127.0.0.1:4003',
      DYNAMIC_UI_SERVICE_URL: 'http://127.0.0.1:4015',
      NOTIFICATION_SERVICE_URL: 'http://127.0.0.1:4005',
      PRIVACY_SERVICE_URL: 'http://127.0.0.1:4012',
      AI_ENGINE_SERVICE_URL: 'http://127.0.0.1:4311',
      AI_GATEWAY_SERVICE_URL: 'http://127.0.0.1:4310',
      AI_GOVERNANCE_SERVICE_URL: 'http://127.0.0.1:4034',
      LANGFUSE_URL: 'http://127.0.0.1:4090',
      KEYCLOAK_ISSUER: 'https://shahin-ai.com/login/realms/dogan',
      KEYCLOAK_AUDIENCE: 'shahin-bff',
      KEYCLOAK_JWKS_URL: 'http://127.0.0.1:8180/login/realms/dogan/protocol/openid-connect/certs',
      GATEWAY_ORIGIN_HMAC_SECRET: 'edaea84ef5aac336f1a948f92a21f1d81c655bccf0c383a8d04e99c692ddbd8c',
      GATEWAY_ORIGIN_TTL_SECONDS: 60,
      DATABASE_URL: 'postgresql://dos_auth:dos_auth_pass_2026@localhost:5432/shahin_grc',
      CORS_ALLOWED_ORIGINS: 'https://shahin-ai.com,https://www.shahin-ai.com',
      // L29 (Phase 3 D2) — admin-zone mTLS (ops-approved flip 2026-05-04).
      // Agent only attaches once admin upstream URLs flip to https://.
      MTLS_ENFORCE: '1',
      ADMIN_MTLS_CA: '/root/DOS-Platform/platform/config-center/secrets/admin-mtls/ca.crt',
      ADMIN_MTLS_GATEWAY_CERT: '/root/DOS-Platform/platform/config-center/secrets/admin-mtls/gateway-client.crt',
      ADMIN_MTLS_GATEWAY_KEY: '/root/DOS-Platform/platform/config-center/secrets/admin-mtls/gateway-client.key',
      MTLS_REJECT_UNAUTHORIZED: '1',
      // L31 (Phase 3 D4) — admin upstreams flipped to HTTPS so the staged
      // HttpsAgent activates (ca.crt SAN includes IP:127.0.0.1 + DNS).
      ADMIN_CONSOLE_BFF_URL: 'https://127.0.0.1:4013',
      DOS_WORKFLOW_SERVICE_URL: 'https://127.0.0.1:4018',
    },
    node_args: '--max-old-space-size=768',
    max_memory_restart: '1G',
    wait_ready: true,
    listen_timeout: 30000,
    kill_timeout: 30000,
    autorestart: true,
    watch: false,
    merge_logs: true,
    error_file: '/var/log/dos-platform/gateway-error.log',
    out_file: '/var/log/dos-platform/gateway-out.log',
  }],
};
