import type { GenericRow } from '@dos/types/db';
export declare function logUserLifecycleEvent(tenantId: string, userId: string, eventType: string, details?: Record<string, unknown>): Promise<void>;
export declare function getUserLifecycleEvents(tenantId: string, userId: string, limit?: number): Promise<GenericRow[]>;
export declare function getUserCertifications(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function addUserCertification(tenantId: string, userId: string, data: Record<string, unknown>): Promise<GenericRow | null>;
export declare function getUserCompetencies(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function upsertUserCompetency(tenantId: string, userId: string, competencyCode: string, proficiencyLevel: number): Promise<GenericRow | null>;
export declare function getUserFavorites(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function addUserFavorite(tenantId: string, userId: string, entityType: string, entityId: string): Promise<GenericRow | null>;
export declare function removeUserFavorite(tenantId: string, userId: string, entityType: string, entityId: string): Promise<boolean>;
export declare function getUserFunctionOverrides(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getUserModulePermissions(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getUserNotificationPreferences(tenantId: string, userId: string): Promise<GenericRow | null>;
export declare function upsertNotificationPreferences(tenantId: string, userId: string, prefs: Record<string, unknown>): Promise<GenericRow | null>;
export declare function getUserPerformanceMetrics(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getUserPreferencesV2(tenantId: string, userId: string): Promise<GenericRow | null>;
export declare function upsertUserPreferencesV2(tenantId: string, userId: string, prefs: Record<string, unknown>): Promise<GenericRow | null>;
export declare function getUserResponsibilities(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getUserRoles(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getUserWorkflowPermissions(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function getActiveSessions(tenantId: string, userId: string): Promise<GenericRow[]>;
export declare function terminateSession(tenantId: string, sessionId: string): Promise<boolean>;
export declare function getPersonProfile(tenantId: string, userId: string): Promise<GenericRow | null>;
export declare function upsertPersonProfile(tenantId: string, userId: string, data: Record<string, unknown>): Promise<GenericRow | null>;
export declare function getUserProfileExtended(tenantId: string, userId: string): Promise<GenericRow | null>;
export declare function upsertUserProfileExtended(tenantId: string, userId: string, data: Record<string, unknown>): Promise<GenericRow | null>;
export declare function getFieldRbacRoleMappings(tenantId: string, roleId: string): Promise<GenericRow[]>;
export declare function upsertFieldRbacRoleMapping(tenantId: string, roleId: string, entityType: string, fieldName: string, accessLevel: string): Promise<GenericRow | null>;
