import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const AI_GOVERNANCE_ERROR_CODES = {
  AGENTS_NOT_FOUND: { code: 'AI_GOVERNANCE.AGENTS_NOT_FOUND', httpStatus: 404, messageEn: 'Agents not found', messageAr: 'Agents غير موجود' },
  AGENTS_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.AGENTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Agents already exists', messageAr: 'Agents موجود بالفعل' },
  AGENTS_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.AGENTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Agents validation failed', messageAr: 'فشل التحقق من Agents' },
  AUDIT_TRAIL_NOT_FOUND: { code: 'AI_GOVERNANCE.AUDIT_TRAIL_NOT_FOUND', httpStatus: 404, messageEn: 'Audit Trail not found', messageAr: 'Audit Trail غير موجود' },
  AUDIT_TRAIL_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.AUDIT_TRAIL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Audit Trail already exists', messageAr: 'Audit Trail موجود بالفعل' },
  AUDIT_TRAIL_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.AUDIT_TRAIL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Audit Trail validation failed', messageAr: 'فشل التحقق من Audit Trail' },
  CONFIG_NOT_FOUND: { code: 'AI_GOVERNANCE.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'AI_GOVERNANCE.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'AI_GOVERNANCE.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  REINDEX_NOT_FOUND: { code: 'AI_GOVERNANCE.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'AI_GOVERNANCE.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  ALERT_RULES_NOT_FOUND: { code: 'AI_GOVERNANCE.ALERT_RULES_NOT_FOUND', httpStatus: 404, messageEn: 'Alert Rules not found', messageAr: 'Alert Rules غير موجود' },
  ALERT_RULES_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.ALERT_RULES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Alert Rules already exists', messageAr: 'Alert Rules موجود بالفعل' },
  ALERT_RULES_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.ALERT_RULES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Alert Rules validation failed', messageAr: 'فشل التحقق من Alert Rules' },
  ALERT_HISTORY_NOT_FOUND: { code: 'AI_GOVERNANCE.ALERT_HISTORY_NOT_FOUND', httpStatus: 404, messageEn: 'Alert History not found', messageAr: 'Alert History غير موجود' },
  ALERT_HISTORY_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.ALERT_HISTORY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Alert History already exists', messageAr: 'Alert History موجود بالفعل' },
  ALERT_HISTORY_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.ALERT_HISTORY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Alert History validation failed', messageAr: 'فشل التحقق من Alert History' },
  KILL_SWITCHES_NOT_FOUND: { code: 'AI_GOVERNANCE.KILL_SWITCHES_NOT_FOUND', httpStatus: 404, messageEn: 'Kill Switches not found', messageAr: 'Kill Switches غير موجود' },
  KILL_SWITCHES_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.KILL_SWITCHES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Kill Switches already exists', messageAr: 'Kill Switches موجود بالفعل' },
  KILL_SWITCHES_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.KILL_SWITCHES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Kill Switches validation failed', messageAr: 'فشل التحقق من Kill Switches' },
  AGENT_RUNTIME_STATS_NOT_FOUND: { code: 'AI_GOVERNANCE.AGENT_RUNTIME_STATS_NOT_FOUND', httpStatus: 404, messageEn: 'Agent Runtime Stats not found', messageAr: 'Agent Runtime Stats غير موجود' },
  AGENT_RUNTIME_STATS_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.AGENT_RUNTIME_STATS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Agent Runtime Stats already exists', messageAr: 'Agent Runtime Stats موجود بالفعل' },
  AGENT_RUNTIME_STATS_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.AGENT_RUNTIME_STATS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Agent Runtime Stats validation failed', messageAr: 'فشل التحقق من Agent Runtime Stats' },
  MODEL_METRICS_NOT_FOUND: { code: 'AI_GOVERNANCE.MODEL_METRICS_NOT_FOUND', httpStatus: 404, messageEn: 'Model Metrics not found', messageAr: 'Model Metrics غير موجود' },
  MODEL_METRICS_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.MODEL_METRICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Model Metrics already exists', messageAr: 'Model Metrics موجود بالفعل' },
  MODEL_METRICS_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.MODEL_METRICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Model Metrics validation failed', messageAr: 'فشل التحقق من Model Metrics' },
  DRIFT_THRESHOLDS_NOT_FOUND: { code: 'AI_GOVERNANCE.DRIFT_THRESHOLDS_NOT_FOUND', httpStatus: 404, messageEn: 'Drift Thresholds not found', messageAr: 'Drift Thresholds غير موجود' },
  DRIFT_THRESHOLDS_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.DRIFT_THRESHOLDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Drift Thresholds already exists', messageAr: 'Drift Thresholds موجود بالفعل' },
  DRIFT_THRESHOLDS_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.DRIFT_THRESHOLDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Drift Thresholds validation failed', messageAr: 'فشل التحقق من Drift Thresholds' },
  MATURITY_SCORECARD_NOT_FOUND: { code: 'AI_GOVERNANCE.MATURITY_SCORECARD_NOT_FOUND', httpStatus: 404, messageEn: 'Maturity Scorecard not found', messageAr: 'Maturity Scorecard غير موجود' },
  MATURITY_SCORECARD_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.MATURITY_SCORECARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maturity Scorecard already exists', messageAr: 'Maturity Scorecard موجود بالفعل' },
  MATURITY_SCORECARD_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.MATURITY_SCORECARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maturity Scorecard validation failed', messageAr: 'فشل التحقق من Maturity Scorecard' },
  BOARD_SUMMARY_NOT_FOUND: { code: 'AI_GOVERNANCE.BOARD_SUMMARY_NOT_FOUND', httpStatus: 404, messageEn: 'Board Summary not found', messageAr: 'Board Summary غير موجود' },
  BOARD_SUMMARY_ALREADY_EXISTS: { code: 'AI_GOVERNANCE.BOARD_SUMMARY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Board Summary already exists', messageAr: 'Board Summary موجود بالفعل' },
  BOARD_SUMMARY_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.BOARD_SUMMARY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Board Summary validation failed', messageAr: 'فشل التحقق من Board Summary' },

  UNAUTHORIZED: { code: 'AI_GOVERNANCE.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for ai-governance operation', messageAr: 'صلاحيات غير كافية لعملية ai-governance' },
  INVALID_STATE_TRANSITION: { code: 'AI_GOVERNANCE.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'AI_GOVERNANCE.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'AI_GOVERNANCE.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'AI_GOVERNANCE.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'AI_GOVERNANCE.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type AiGovernanceErrorCode = keyof typeof AI_GOVERNANCE_ERROR_CODES;
