import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const COMPLIANCE_WIDGETS: WidgetManifest[] = [
  // ── Core Compliance ──
  {
    id: 'compliance.score',
    key: 'compliance_score',
    title: 'Compliance Score',
    titleAr: 'نسبة الامتثال',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '✅',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.trend',
    key: 'compliance_trend',
    title: 'Compliance Trend',
    titleAr: 'اتجاه الامتثال',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '📈',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.framework_coverage',
    key: 'compliance_overview',
    title: 'Framework Coverage',
    titleAr: 'تغطية الأطر',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/framework-coverage.widget').then(m => m.FrameworkCoverageWidget),
    icon: '📐',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.framework_radar',
    key: 'framework_radar',
    title: 'Framework Radar',
    titleAr: 'رادار الأطر',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/framework-radar.widget').then(m => m.FrameworkRadarWidget),
    icon: '🎯',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.control_progress',
    key: 'control_progress',
    title: 'Control Progress',
    titleAr: 'تقدم الضوابط',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/control/control-progress.widget').then(m => m.ControlProgressWidget),
    icon: '📊',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.policy_scorecard',
    key: 'policy_scorecard',
    title: 'Policy Scorecard',
    titleAr: 'بطاقة السياسات',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/evidence/policy-scorecard.widget').then(m => m.PolicyScorecardWidget),
    icon: '📄',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.control_drift',
    key: 'control_drift',
    title: 'Control Drift',
    titleAr: 'انحراف الضوابط',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/control/control-drift.widget').then(m => m.ControlDriftWidget),
    icon: '📉',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.maturity_gap',
    key: 'maturity_gauge',
    title: 'Maturity Gap',
    titleAr: 'فجوة النضج',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/executive/maturity-gap.widget').then(m => m.MaturityGapWidget),
    icon: '📐',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'viewer'],
    schemaVersion: 1,
  },
  // ── ECharts Compliance ──
  {
    id: 'compliance.gauge_echart',
    key: 'compliance_gauge',
    title: 'Compliance Gauge',
    titleAr: 'مقياس الامتثال',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../echart-components/gauge/compliance-gauge-echart.component').then(m => m.ComplianceGaugeEchartComponent),
    icon: '✅',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.heatmap_cc',
    key: 'compliance_heatmap',
    title: 'Compliance Heatmap CC',
    titleAr: 'حرارية الامتثال المستمر',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/heatmap/compliance-heatmap-cc.component').then(m => m.ComplianceHeatmapCcComponent),
    icon: '🗺️',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.coverage_treemap',
    key: 'compliance_treemap',
    title: 'Compliance Coverage Treemap',
    titleAr: 'خريطة شجرية لتغطية الامتثال',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/compliance-coverage-treemap.component').then(m => m.ComplianceCoverageTreemapComponent),
    icon: '🌳',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.control_testing_donut',
    key: 'control_testing',
    title: 'Control Testing Donut',
    titleAr: 'دائرة اختبار الضوابط',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/donut/control-testing-donut.component').then(m => m.ControlTestingDonutComponent),
    icon: '🍩',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.findings_bar',
    key: 'findings_bar',
    title: 'Findings Bar',
    titleAr: 'أعمدة النتائج',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/bar/findings-bar.component').then(m => m.FindingsBarComponent),
    icon: '📊',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.framework_radar_echart',
    key: 'framework_radar_echart',
    title: 'Framework Radar (ECharts)',
    titleAr: 'رادار الأطر المتقدم',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/radar/framework-radar.component').then(m => m.FrameworkRadarComponent),
    icon: '📡',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.framework_compliance',
    key: 'framework_compliance',
    title: 'Framework Compliance',
    titleAr: 'امتثال الأطر',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/framework-compliance.component').then(m => m.FrameworkComplianceComponent),
    icon: '✅',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.maturity_radar_echart',
    key: 'maturity_radar',
    title: 'Maturity Radar',
    titleAr: 'رادار النضج',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/radar/maturity-radar-echart.component').then(m => m.MaturityRadarEchartComponent),
    icon: '🎯',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.maturity_spider',
    key: 'maturity_spider',
    title: 'Maturity Spider',
    titleAr: 'عنكبوت النضج',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/radar/maturity-spider.component').then(m => m.MaturitySpiderComponent),
    icon: '🕷️',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.mesh_3d',
    key: 'compliance_mesh_3d',
    title: 'Compliance Mesh 3D',
    titleAr: 'شبكة الامتثال ثلاثية الأبعاد',
    category: 'compliance',
    engine: 'plotly',
    component: () => import('../../../chart-infra/echart-components/three-d/compliance-mesh-3d.component').then(m => m.ComplianceMesh3dComponent),
    icon: '🧊',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.effectiveness_boxplot',
    key: 'control_effectiveness',
    title: 'Control Effectiveness Boxplot',
    titleAr: 'صندوقي فعالية الضوابط',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/statistical/control-effectiveness-boxplot.component').then(m => m.ControlEffectivenessBoxplotComponent),
    icon: '📦',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.parallel_coordinates',
    key: 'parallel_coordinates',
    title: 'Parallel Coordinates',
    titleAr: 'إحداثيات متوازية',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/statistical/parallel-coordinates.component').then(m => m.ParallelCoordinatesComponent),
    icon: '📊',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'compliance.control_coverage_sankey',
    key: 'control_coverage_sankey',
    title: 'Control Coverage Sankey',
    titleAr: 'تغطية الضوابط سانكي',
    category: 'compliance',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/sankey/control-coverage-sankey.component').then(m => m.ControlCoverageSankeyComponent),
    icon: '🔀',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.obligation_status',
    key: 'obligation_status',
    title: 'Obligation Status',
    titleAr: 'حالة الالتزامات',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '📋',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.score_gauge',
    key: 'compliance_score_gauge',
    title: 'Compliance Score Gauge',
    titleAr: 'مقياس نسبة الامتثال',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '📊',
    defaultSize: { cols: 4, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.gap_by_framework',
    key: 'gap_by_framework',
    title: 'Gaps by Framework',
    titleAr: 'الفجوات حسب الإطار',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '⚠️',
    defaultSize: { cols: 4, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.control_coverage',
    key: 'control_coverage_widget',
    title: 'Control Coverage',
    titleAr: 'تغطية الضوابط',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '🛡️',
    defaultSize: { cols: 4, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.posture_chart',
    key: 'posture_chart',
    title: 'Compliance Posture',
    titleAr: 'وضع الامتثال',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '📈',
    defaultSize: { cols: 6, rows: 4 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.assessment_honesty',
    key: 'assessment_honesty',
    title: 'Assessment Honesty',
    titleAr: 'صدق التقييم',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/assessment-honesty.widget').then(m => m.AssessmentHonestyWidget),
    icon: '⚖️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.exceptions_aging',
    key: 'exceptions_aging',
    title: 'Exceptions Aging',
    titleAr: 'تقادم الاستثناءات',
    category: 'compliance',
    engine: 'angular',
    component: () => import('../../../components/evidence/exceptions-aging.widget').then(m => m.ExceptionsAgingWidget),
    icon: '⏰',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  // ─────────────────────────────────────────────────────────────────────────
  // Per-page signature widgets (one per compliance route).
  // Each maps a route's primary insight to a renderable widget. Until the
  // dedicated visual is built, the lazy import points at the closest existing
  // component; replace each with a tailored component as it ships.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'compliance.work_queue_strip',
    key: 'compliance_work_queue_strip',
    title: 'My Compliance Work Queue',
    titleAr: 'قائمة مهام الامتثال',
    category: 'compliance',
    engine: 'angular',
    // Strip with buckets: Overdue / Due ≤7d / In Progress / Blocked.
    // Source: UNION over obligations + assessments + gaps where assignee=current user.
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '📋',
    defaultSize: { cols: 12, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.calendar_strip',
    key: 'compliance_calendar_strip',
    title: 'Upcoming Compliance Deadlines (30d)',
    titleAr: 'المواعيد القادمة للامتثال (30 يوم)',
    category: 'compliance',
    engine: 'angular',
    // 30-day timeline with deadline pins coloured by criticality.
    // Source: compliance_calendar_events + obligations.due_date + assessments next-cadence.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '📅',
    defaultSize: { cols: 12, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.roadmap_timeline',
    key: 'compliance_roadmap_timeline',
    title: 'Compliance Roadmap',
    titleAr: 'خارطة طريق الامتثال',
    category: 'compliance',
    engine: 'angular',
    // Multi-quarter Gantt: framework rollouts, planned assessments, remediation deadlines.
    // Source: compliance_programs.due_date + compliance_assessments upcoming.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '🗺️',
    defaultSize: { cols: 12, rows: 4 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.template_coverage',
    key: 'compliance_template_coverage',
    title: 'Template Library Coverage',
    titleAr: 'تغطية مكتبة القوالب',
    category: 'compliance',
    engine: 'echarts',
    // Stacked bar: # templates Active / Draft / Deprecated by framework.
    // Source: assessment_templates grouped by framework + status.
    component: () => import('../../../chart-infra/echart-components/bar/findings-bar.component').then(m => m.FindingsBarComponent),
    icon: '📚',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.obligation_detail_card',
    key: 'obligation_detail_card',
    title: 'Obligation Detail',
    titleAr: 'تفاصيل الالتزام',
    category: 'compliance',
    engine: 'angular',
    // Object header card: title, regulator, due_date, owner, evidence count,
    // mapped controls list, history timeline.
    // Source: single obligation row + joined evidence-links + audit-trail.
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '📌',
    defaultSize: { cols: 12, rows: 4 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.obligation_kanban',
    key: 'obligation_kanban',
    title: 'Obligation Workspace (Kanban)',
    titleAr: 'مساحة عمل الالتزامات',
    category: 'compliance',
    engine: 'angular',
    // Kanban: Triage / Mapping / Evidence / Review / Done.
    // Source: obligation rows grouped by workflow state.
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '📋',
    defaultSize: { cols: 12, rows: 4 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.regulatory_change_feed',
    key: 'regulatory_change_feed',
    title: 'Regulatory Change Feed',
    titleAr: 'تغذية التغييرات التنظيمية',
    category: 'compliance',
    engine: 'angular',
    // Reverse-chrono feed cards: regulator, framework, effective date, severity badge,
    // AI draft impact note.
    // Source: compliance_regulatory_changes joined with framework.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '📰',
    defaultSize: { cols: 12, rows: 3 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.assessment_pipeline_funnel',
    key: 'assessment_pipeline_funnel',
    title: 'Assessment Pipeline',
    titleAr: 'خط أنابيب التقييمات',
    category: 'compliance',
    engine: 'echarts',
    // Funnel: Draft → In Progress → Under Review → Completed → Closed
    // (counts + median dwell time per stage).
    // Source: compliance_assessments.status aggregations.
    component: () => import('../../../chart-infra/echart-components/donut/control-testing-donut.component').then(m => m.ControlTestingDonutComponent),
    icon: '🧪',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.attestation_coverage_donut',
    key: 'attestation_coverage_donut',
    title: 'Attestation Coverage',
    titleAr: 'تغطية الإقرارات',
    category: 'compliance',
    engine: 'echarts',
    // Donut: Attested / Pending / Overdue with % by population + due-date countdown.
    // Source: compliance_attestations joined with target user population.
    component: () => import('../../../chart-infra/echart-components/donut/control-testing-donut.component').then(m => m.ControlTestingDonutComponent),
    icon: '✍️',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.evidence_freshness',
    key: 'evidence_freshness',
    title: 'Evidence Freshness',
    titleAr: 'حداثة الأدلة',
    category: 'compliance',
    engine: 'echarts',
    // Histogram: evidence count by age band (Fresh ≤30d / Stale 31-90d / Expired 90+).
    // Source: compliance_evidence_links + linked source timestamps.
    component: () => import('../../../chart-infra/echart-components/bar/findings-bar.component').then(m => m.FindingsBarComponent),
    icon: '🕒',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.report_activity_strip',
    key: 'report_activity_strip',
    title: 'Recent Report Activity',
    titleAr: 'نشاط التقارير الأخير',
    category: 'compliance',
    engine: 'angular',
    // List: last 10 generated reports — run-time, audience, status, download link.
    // Source: compliance_report_snapshots ORDER BY created_at DESC LIMIT 10.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '📄',
    defaultSize: { cols: 12, rows: 3 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.assertion_status_panel',
    key: 'assertion_status_panel',
    title: 'Continuous Attestation Status',
    titleAr: 'حالة الإقرار المستمر',
    category: 'compliance',
    engine: 'angular',
    // Live panel: per-assertion ✓/⚠/✗ with last-eval timestamp.
    // Source: compliance_assertions realtime status.
    component: () => import('../../../components/compliance-audit/compliance-score.widget').then(m => m.ComplianceScoreWidget),
    icon: '🟢',
    defaultSize: { cols: 12, rows: 3 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.rcsa_campaign_progress',
    key: 'rcsa_campaign_progress',
    title: 'RCSA Campaign Progress',
    titleAr: 'تقدم حملات التقييم الذاتي',
    category: 'compliance',
    engine: 'angular',
    // Stacked progress bars per active campaign: % responded / % completed / days remaining.
    // Source: csa_campaigns + csa_responses joined.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '🎯',
    defaultSize: { cols: 12, rows: 3 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
  {
    id: 'compliance.reasoning_studio_activity',
    key: 'reasoning_studio_activity',
    title: 'AI Regulatory Reasoning Activity',
    titleAr: 'نشاط الاستنتاج التنظيمي الذكي',
    category: 'compliance',
    engine: 'angular',
    // Recent AI interpretations feed: query, source regulation, confidence, citations.
    // Source: compliance_ai_suggestions WHERE reasoning_type='regulatory'.
    component: () => import('../../../components/compliance-audit/compliance-trend.widget').then(m => m.ComplianceTrendWidget),
    icon: '🧠',
    defaultSize: { cols: 12, rows: 3 },
    roles: ['owner', 'admin', 'compliance_officer'],
    schemaVersion: 1,
  },
];
