import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const REMEDIATION_ERROR_CODES = {
  RUN_NOT_FOUND: { code: 'REMEDIATION.RUN_NOT_FOUND', httpStatus: 404, messageEn: 'Run not found', messageAr: 'Run غير موجود' },
  RUN_ALREADY_EXISTS: { code: 'REMEDIATION.RUN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Run already exists', messageAr: 'Run موجود بالفعل' },
  RUN_VALIDATION_FAILED: { code: 'REMEDIATION.RUN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Run validation failed', messageAr: 'فشل التحقق من Run' },
  CONFIG_NOT_FOUND: { code: 'REMEDIATION.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'REMEDIATION.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'REMEDIATION.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'REMEDIATION.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'REMEDIATION.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'REMEDIATION.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'REMEDIATION.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'REMEDIATION.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'REMEDIATION.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'REMEDIATION.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'REMEDIATION.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'REMEDIATION.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  PENDING_VERIFICATION_NOT_FOUND: { code: 'REMEDIATION.PENDING_VERIFICATION_NOT_FOUND', httpStatus: 404, messageEn: 'Pending Verification not found', messageAr: 'Pending Verification غير موجود' },
  PENDING_VERIFICATION_ALREADY_EXISTS: { code: 'REMEDIATION.PENDING_VERIFICATION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Pending Verification already exists', messageAr: 'Pending Verification موجود بالفعل' },
  PENDING_VERIFICATION_VALIDATION_FAILED: { code: 'REMEDIATION.PENDING_VERIFICATION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Pending Verification validation failed', messageAr: 'فشل التحقق من Pending Verification' },
  REINDEX_NOT_FOUND: { code: 'REMEDIATION.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'REMEDIATION.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'REMEDIATION.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'REMEDIATION.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'REMEDIATION.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'REMEDIATION.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'REMEDIATION.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'REMEDIATION.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'REMEDIATION.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  CHECK_OVERDUE_NOT_FOUND: { code: 'REMEDIATION.CHECK_OVERDUE_NOT_FOUND', httpStatus: 404, messageEn: 'Check Overdue not found', messageAr: 'Check Overdue غير موجود' },
  CHECK_OVERDUE_ALREADY_EXISTS: { code: 'REMEDIATION.CHECK_OVERDUE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Check Overdue already exists', messageAr: 'Check Overdue موجود بالفعل' },
  CHECK_OVERDUE_VALIDATION_FAILED: { code: 'REMEDIATION.CHECK_OVERDUE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Check Overdue validation failed', messageAr: 'فشل التحقق من Check Overdue' },
  SEARCH_NOT_FOUND: { code: 'REMEDIATION.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'REMEDIATION.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'REMEDIATION.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  DASHBOARD_NOT_FOUND: { code: 'REMEDIATION.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'REMEDIATION.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'REMEDIATION.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  TRENDS_NOT_FOUND: { code: 'REMEDIATION.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'REMEDIATION.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'REMEDIATION.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  CROSS_MODULE_NOT_FOUND: { code: 'REMEDIATION.CROSS_MODULE_NOT_FOUND', httpStatus: 404, messageEn: 'Cross Module not found', messageAr: 'Cross Module غير موجود' },
  CROSS_MODULE_ALREADY_EXISTS: { code: 'REMEDIATION.CROSS_MODULE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Cross Module already exists', messageAr: 'Cross Module موجود بالفعل' },
  CROSS_MODULE_VALIDATION_FAILED: { code: 'REMEDIATION.CROSS_MODULE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Cross Module validation failed', messageAr: 'فشل التحقق من Cross Module' },
  EXPORT_NOT_FOUND: { code: 'REMEDIATION.EXPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Export not found', messageAr: 'Export غير موجود' },
  EXPORT_ALREADY_EXISTS: { code: 'REMEDIATION.EXPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Export already exists', messageAr: 'Export موجود بالفعل' },
  EXPORT_VALIDATION_FAILED: { code: 'REMEDIATION.EXPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Export validation failed', messageAr: 'فشل التحقق من Export' },

  UNAUTHORIZED: { code: 'REMEDIATION.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for remediation operation', messageAr: 'صلاحيات غير كافية لعملية remediation' },
  INVALID_STATE_TRANSITION: { code: 'REMEDIATION.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'REMEDIATION.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'REMEDIATION.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'REMEDIATION.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'REMEDIATION.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type RemediationErrorCode = keyof typeof REMEDIATION_ERROR_CODES;
