import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const POLICY_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'POLICY.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'POLICY.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'POLICY.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'POLICY.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'POLICY.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'POLICY.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'POLICY.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'POLICY.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'POLICY.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'POLICY.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'POLICY.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'POLICY.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  OVERDUE_NOT_FOUND: { code: 'POLICY.OVERDUE_NOT_FOUND', httpStatus: 404, messageEn: 'Overdue not found', messageAr: 'Overdue غير موجود' },
  OVERDUE_ALREADY_EXISTS: { code: 'POLICY.OVERDUE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overdue already exists', messageAr: 'Overdue موجود بالفعل' },
  OVERDUE_VALIDATION_FAILED: { code: 'POLICY.OVERDUE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overdue validation failed', messageAr: 'فشل التحقق من Overdue' },
  REINDEX_NOT_FOUND: { code: 'POLICY.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'POLICY.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'POLICY.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'POLICY.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'POLICY.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'POLICY.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  POLICY_CONFLICTS_NOT_FOUND: { code: 'POLICY.POLICY_CONFLICTS_NOT_FOUND', httpStatus: 404, messageEn: 'Policy Conflicts not found', messageAr: 'Policy Conflicts غير موجود' },
  POLICY_CONFLICTS_ALREADY_EXISTS: { code: 'POLICY.POLICY_CONFLICTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Policy Conflicts already exists', messageAr: 'Policy Conflicts موجود بالفعل' },
  POLICY_CONFLICTS_VALIDATION_FAILED: { code: 'POLICY.POLICY_CONFLICTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Policy Conflicts validation failed', messageAr: 'فشل التحقق من Policy Conflicts' },
  POLICY_REDUNDANCIES_NOT_FOUND: { code: 'POLICY.POLICY_REDUNDANCIES_NOT_FOUND', httpStatus: 404, messageEn: 'Policy Redundancies not found', messageAr: 'Policy Redundancies غير موجود' },
  POLICY_REDUNDANCIES_ALREADY_EXISTS: { code: 'POLICY.POLICY_REDUNDANCIES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Policy Redundancies already exists', messageAr: 'Policy Redundancies موجود بالفعل' },
  POLICY_REDUNDANCIES_VALIDATION_FAILED: { code: 'POLICY.POLICY_REDUNDANCIES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Policy Redundancies validation failed', messageAr: 'فشل التحقق من Policy Redundancies' },
  POLICY_ANALYSIS_REPORT_NOT_FOUND: { code: 'POLICY.POLICY_ANALYSIS_REPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Policy Analysis Report not found', messageAr: 'Policy Analysis Report غير موجود' },
  POLICY_ANALYSIS_REPORT_ALREADY_EXISTS: { code: 'POLICY.POLICY_ANALYSIS_REPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Policy Analysis Report already exists', messageAr: 'Policy Analysis Report موجود بالفعل' },
  POLICY_ANALYSIS_REPORT_VALIDATION_FAILED: { code: 'POLICY.POLICY_ANALYSIS_REPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Policy Analysis Report validation failed', messageAr: 'فشل التحقق من Policy Analysis Report' },
  SOD_NOT_FOUND: { code: 'POLICY.SOD_NOT_FOUND', httpStatus: 404, messageEn: 'Sod not found', messageAr: 'Sod غير موجود' },
  SOD_ALREADY_EXISTS: { code: 'POLICY.SOD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Sod already exists', messageAr: 'Sod موجود بالفعل' },
  SOD_VALIDATION_FAILED: { code: 'POLICY.SOD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Sod validation failed', messageAr: 'فشل التحقق من Sod' },
  CAPA_NOT_FOUND: { code: 'POLICY.CAPA_NOT_FOUND', httpStatus: 404, messageEn: 'Capa not found', messageAr: 'Capa غير موجود' },
  CAPA_ALREADY_EXISTS: { code: 'POLICY.CAPA_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Capa already exists', messageAr: 'Capa موجود بالفعل' },
  CAPA_VALIDATION_FAILED: { code: 'POLICY.CAPA_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Capa validation failed', messageAr: 'فشل التحقق من Capa' },
  CCM_NOT_FOUND: { code: 'POLICY.CCM_NOT_FOUND', httpStatus: 404, messageEn: 'Ccm not found', messageAr: 'Ccm غير موجود' },
  CCM_ALREADY_EXISTS: { code: 'POLICY.CCM_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Ccm already exists', messageAr: 'Ccm موجود بالفعل' },
  CCM_VALIDATION_FAILED: { code: 'POLICY.CCM_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Ccm validation failed', messageAr: 'فشل التحقق من Ccm' },
  PROCESS_NOT_FOUND: { code: 'POLICY.PROCESS_NOT_FOUND', httpStatus: 404, messageEn: 'Process not found', messageAr: 'Process غير موجود' },
  PROCESS_ALREADY_EXISTS: { code: 'POLICY.PROCESS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Process already exists', messageAr: 'Process موجود بالفعل' },
  PROCESS_VALIDATION_FAILED: { code: 'POLICY.PROCESS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Process validation failed', messageAr: 'فشل التحقق من Process' },
  AGENTS_NOT_FOUND: { code: 'POLICY.AGENTS_NOT_FOUND', httpStatus: 404, messageEn: 'Agents not found', messageAr: 'Agents غير موجود' },
  AGENTS_ALREADY_EXISTS: { code: 'POLICY.AGENTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Agents already exists', messageAr: 'Agents موجود بالفعل' },
  AGENTS_VALIDATION_FAILED: { code: 'POLICY.AGENTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Agents validation failed', messageAr: 'فشل التحقق من Agents' },

  UNAUTHORIZED: { code: 'POLICY.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for policy operation', messageAr: 'صلاحيات غير كافية لعملية policy' },
  INVALID_STATE_TRANSITION: { code: 'POLICY.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'POLICY.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'POLICY.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'POLICY.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'POLICY.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type PolicyErrorCode = keyof typeof POLICY_ERROR_CODES;
