-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=workflow scope=public function=scheduled
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/workflow/db/public/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * workflow_scheduled_jobs
--
-- Source migrations (immutable, 1):
--   * modules/workflow/db/public/migrations/20260419_extracted_from_20260419_0002_p95_notifications_schema_align.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dos.workflow_scheduled_jobs (
  job_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         TEXT NOT NULL,
  name              TEXT NOT NULL,
  cron_expression   TEXT NOT NULL,
  job_type          TEXT NOT NULL,
  payload           JSONB DEFAULT '{}'::jsonb,
  is_active         BOOLEAN DEFAULT TRUE,
  created_by        TEXT,
  last_triggered_at TIMESTAMPTZ,
  last_triggered_by TEXT,
  trigger_count     INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wsj_active_tenant
  ON dos.workflow_scheduled_jobs(tenant_id, is_active)
  WHERE is_active = TRUE;
