/**
 * risk — Module Security Registration
 * Permissions, roles, and actions for the risk module.
 * Follows the governance reference pattern with dot-notation permission codes.
 *
 * DO NOT EDIT permissions extracted from routes. Add new permissions below the generated block.
 */

import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const RISK_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'risk.record.read', resourceType: 'record', actionType: 'read', descriptionEn: 'View risk records', descriptionAr: 'عرض سجلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.write', resourceType: 'record', actionType: 'write', descriptionEn: 'Create and update risk records', descriptionAr: 'إنشاء وتحديث سجلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.delete', resourceType: 'record', actionType: 'delete', descriptionEn: 'Delete risk records', descriptionAr: 'حذف سجلات المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.manage', resourceType: 'record', actionType: 'manage', descriptionEn: 'Manage risk module settings', descriptionAr: 'إدارة إعدادات وحدة المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.assessment.read', resourceType: 'assessment', actionType: 'read', descriptionEn: 'View risk assessments', descriptionAr: 'عرض تقييمات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.assessment.write', resourceType: 'assessment', actionType: 'write', descriptionEn: 'Create and update risk assessments', descriptionAr: 'إنشاء وتحديث تقييمات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.assessment.approve', resourceType: 'assessment', actionType: 'approve', descriptionEn: 'Approve risk assessments', descriptionAr: 'اعتماد تقييمات المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.treatment.write', resourceType: 'treatment', actionType: 'write', descriptionEn: 'Create and manage risk treatment plans', descriptionAr: 'إنشاء وإدارة خطط معالجة المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.report.read', resourceType: 'report', actionType: 'read', descriptionEn: 'View risk reports and analytics', descriptionAr: 'عرض تقارير وتحليلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const RISK_ROLES: ModuleRole[] = [
  { roleCode: 'risk.executive_owner', archetype: 'executive_owner', nameEn: 'Risk Executive Owner', nameAr: 'المالك التنفيذي للمخاطر', descriptionEn: 'Executive owner for the risk module', descriptionAr: 'المالك التنفيذي لوحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.delete', 'risk.record.manage', 'risk.assessment.read', 'risk.assessment.write', 'risk.assessment.approve', 'risk.treatment.write', 'risk.report.read'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'risk.module_lead', archetype: 'module_lead', nameEn: 'Risk Module Lead', nameAr: 'قائد وحدة المخاطر', descriptionEn: 'Module lead for the risk module', descriptionAr: 'قائد وحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.delete', 'risk.assessment.read', 'risk.assessment.write', 'risk.assessment.approve', 'risk.treatment.write', 'risk.report.read'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'risk.approver', archetype: 'approver', nameEn: 'Risk Approver', nameAr: 'معتمد المخاطر', descriptionEn: 'Approver for risk assessments and treatments', descriptionAr: 'معتمد تقييمات ومعالجات المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.assessment.read', 'risk.assessment.approve', 'risk.report.read'], authorityLevel: 'required', defaultScope: 'own' },
  { roleCode: 'risk.operator', archetype: 'operator', nameEn: 'Risk Operator', nameAr: 'مشغل المخاطر', descriptionEn: 'Operator for the risk module', descriptionAr: 'مشغل وحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.assessment.read', 'risk.assessment.write', 'risk.treatment.write', 'risk.report.read'], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'risk.contributor', archetype: 'contributor', nameEn: 'Risk Contributor', nameAr: 'مساهم المخاطر', descriptionEn: 'Contributor for the risk module', descriptionAr: 'مساهم في وحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.assessment.read', 'risk.assessment.write', 'risk.treatment.write', 'risk.report.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.reviewer', archetype: 'reviewer', nameEn: 'Risk Reviewer', nameAr: 'مراجع المخاطر', descriptionEn: 'Reviewer for the risk module', descriptionAr: 'مراجع وحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.assessment.read', 'risk.report.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.auditor', archetype: 'auditor', nameEn: 'Risk Auditor', nameAr: 'مدقق المخاطر', descriptionEn: 'Auditor for the risk module', descriptionAr: 'مدقق وحدة المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.assessment.read', 'risk.report.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.viewer', archetype: 'viewer', nameEn: 'Risk Viewer', nameAr: 'عارض المخاطر', descriptionEn: 'Read-only viewer for the risk module', descriptionAr: 'عارض للقراءة فقط لوحدة المخاطر', isDefault: true, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.assessment.read', 'risk.report.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const RISK_ACTIONS: ModuleAction[] = [
  { actionCode: 'risk.record.read', labelEn: 'View risk record', labelAr: 'عرض سجل المخاطر', requiredPermissions: ['risk.record.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'risk.record.write', labelEn: 'Create/update risk record', labelAr: 'إنشاء/تحديث سجل المخاطر', requiredPermissions: ['risk.record.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.delete', labelEn: 'Delete risk record', labelAr: 'حذف سجل المخاطر', requiredPermissions: ['risk.record.delete'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: false, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.manage', labelEn: 'Manage risk settings', labelAr: 'إدارة إعدادات المخاطر', requiredPermissions: ['risk.record.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.assessment.read', labelEn: 'View risk assessment', labelAr: 'عرض تقييم المخاطر', requiredPermissions: ['risk.assessment.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'risk.assessment.write', labelEn: 'Create/update risk assessment', labelAr: 'إنشاء/تحديث تقييم المخاطر', requiredPermissions: ['risk.assessment.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.assessment.approve', labelEn: 'Approve risk assessment', labelAr: 'اعتماد تقييم المخاطر', requiredPermissions: ['risk.assessment.approve'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: true, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.treatment.write', labelEn: 'Manage risk treatment', labelAr: 'إدارة معالجة المخاطر', requiredPermissions: ['risk.treatment.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.report.read', labelEn: 'View risk reports', labelAr: 'عرض تقارير المخاطر', requiredPermissions: ['risk.report.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
];
