-- dos:extracted-from: ops/migrations/tenant/027_tenant_schema_tables.sql
-- dos:supersedes-checksum: b618781c42608331e3344799991235a22afbb73ab72c9789ef6478fd164416c8
-- dos:owning-module: knowledge
-- dos:tables: knowledge_ai_suggestions, knowledge_articles, knowledge_categories, knowledge_comments, knowledge_distribution, knowledge_experts, knowledge_faq_sets, knowledge_feedback, knowledge_glossary, knowledge_links, knowledge_media_library, knowledge_ratings, knowledge_search_index, knowledge_settings, knowledge_tags, knowledge_templates, knowledge_translations, knowledge_versions
-- dos:statement-count: 36
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_articles" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_articles_tenant ON "__TENANT_SCHEMA__"."knowledge_articles" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_categories" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_categories_tenant ON "__TENANT_SCHEMA__"."knowledge_categories" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_search_index" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_search_index_tenant ON "__TENANT_SCHEMA__"."knowledge_search_index" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_ai_suggestions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_ai_suggestions_tenant ON "__TENANT_SCHEMA__"."knowledge_ai_suggestions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_tags" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_tags_tenant ON "__TENANT_SCHEMA__"."knowledge_tags" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_versions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_versions_tenant ON "__TENANT_SCHEMA__"."knowledge_versions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_settings_tenant ON "__TENANT_SCHEMA__"."knowledge_settings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_feedback" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_feedback_tenant ON "__TENANT_SCHEMA__"."knowledge_feedback" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_templates" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_templates_tenant ON "__TENANT_SCHEMA__"."knowledge_templates" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_links" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_links_tenant ON "__TENANT_SCHEMA__"."knowledge_links" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_faq_sets" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_faq_sets_tenant ON "__TENANT_SCHEMA__"."knowledge_faq_sets" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_media_library" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_media_library_tenant ON "__TENANT_SCHEMA__"."knowledge_media_library" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_glossary" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_glossary_tenant ON "__TENANT_SCHEMA__"."knowledge_glossary" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_experts" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_experts_tenant ON "__TENANT_SCHEMA__"."knowledge_experts" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_comments" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_comments_tenant ON "__TENANT_SCHEMA__"."knowledge_comments" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_ratings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_ratings_tenant ON "__TENANT_SCHEMA__"."knowledge_ratings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_distribution" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_distribution_tenant ON "__TENANT_SCHEMA__"."knowledge_distribution" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."knowledge_translations" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_knowledge_translations_tenant ON "__TENANT_SCHEMA__"."knowledge_translations" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;
