import type { NavItemDef } from '@dos/contracts';

export const AGRC_NAV_ITEMS: NavItemDef[] = [
  { icon: 'dashboard', labelKey: 'nav.dashboard', route: '/workspace-home', requiredPermission: 'workspace.config.read', section: 'main', lifecyclePhase: 'plan' },
  { icon: 'home', labelKey: 'sidebar.foundationOverview', route: '/foundation', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'building', labelKey: 'sidebar.foundationOrg', route: '/foundation/organization', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'users', labelKey: 'sidebar.foundationUsers', route: '/foundation/users', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'sliders-h', labelKey: 'sidebar.foundationRoles', route: '/foundation/roles', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'briefcase', labelKey: 'sidebar.foundationBU', route: '/foundation/business-units', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'sitemap', labelKey: 'sidebar.foundationDepts', route: '/foundation/departments', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'map-marker', labelKey: 'sidebar.foundationLocs', route: '/foundation/locations', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'database', labelKey: 'sidebar.foundationRefData', route: '/foundation/reference-data', requiredPermission: 'workspace.config.read', section: 'account', lifecyclePhase: 'plan', agentId: 'A02', moduleGroup: 'foundation' },
  { icon: 'home', labelKey: 'sidebar.governanceOverview', route: '/governance/overview', requiredPermission: 'governance.record.read', section: 'grc', lifecyclePhase: 'plan', agentId: 'A08', moduleGroup: 'governance' },
  { icon: 'file', labelKey: 'sidebar.governancePolicies', route: '/governance/policies', requiredPermission: 'policy.document.read', section: 'grc', lifecyclePhase: 'plan', agentId: 'A08', moduleGroup: 'governance' },
  { icon: 'list', labelKey: 'sidebar.governanceProcedures', route: '/governance/procedures', requiredPermission: 'policy.document.read', section: 'grc', lifecyclePhase: 'plan', agentId: 'A08', moduleGroup: 'governance' },
  { icon: 'users', labelKey: 'sidebar.governanceCommittees', route: '/governance/committees', requiredPermission: 'governance.record.read', section: 'grc', lifecyclePhase: 'plan', agentId: 'A08', moduleGroup: 'governance' },
  { icon: 'exclamation-triangle', labelKey: 'sidebar.riskHub', route: '/risk-hub', requiredPermission: 'risk.record.read', section: 'grc', lifecyclePhase: 'assess', agentId: 'A07' },
  { icon: 'chart-bar', labelKey: 'sidebar.complianceOverview', route: '/compliance/overview', requiredPermission: 'control.record.read', section: 'grc', lifecyclePhase: 'implement', agentId: 'A06', moduleGroup: 'compliance' },
  { icon: 'sitemap', labelKey: 'sidebar.complianceFrameworks', route: '/compliance/frameworks', requiredPermission: 'framework.record.read', section: 'grc', lifecyclePhase: 'implement', agentId: 'A06', moduleGroup: 'compliance' },
  { icon: 'sliders-h', labelKey: 'sidebar.complianceControls', route: '/compliance/controls', requiredPermission: 'control.record.read', section: 'grc', lifecyclePhase: 'implement', agentId: 'A06', moduleGroup: 'compliance' },
  { icon: 'folder-open', labelKey: 'sidebar.evidenceOverview', route: '/evidence/overview', requiredPermission: 'evidence.item.read', section: 'grc', lifecyclePhase: 'implement', agentId: 'A05' },
  { icon: 'search', labelKey: 'sidebar.auditOverview', route: '/audit/overview', requiredPermission: 'audit.record.read', section: 'grc', lifecyclePhase: 'assure', agentId: 'A10' },
  { icon: 'truck', labelKey: 'sidebar.vendorHub', route: '/vendor-hub', requiredPermission: 'vendor.record.read', section: 'operations', lifecyclePhase: 'assess', agentId: 'A09' },
  { icon: 'shield', labelKey: 'sidebar.bcpOverview', route: '/bcp/overview', requiredPermission: 'bcp.plan.read', section: 'operations', lifecyclePhase: 'operate', agentId: 'A11' },
  { icon: 'microchip', labelKey: 'sidebar.aiGovernance', route: '/ai-governance', requiredPermission: 'ai.agent.read', section: 'grc', lifecyclePhase: 'operate', moduleGroup: 'ai-governance' },
];

const ALL_NAV_PERMS = [
  'admin.config.read', 'admin.config.write', 'admin.tenant.manage', 'admin.user.manage',
  'ai.agent.manage', 'ai.agent.read', 'analytics.report.read',
  'assessment.record.manage', 'assessment.record.read', 'assessment.record.write',
  'audit.record.manage', 'audit.record.read', 'audit.record.write',
  'bcp.plan.read', 'bcp.plan.write', 'compliance.program.read', 'compliance.program.write',
  'control.record.read', 'control.record.write', 'copilot.assistant.read',
  'evidence.item.read', 'evidence.item.write', 'framework.record.manage', 'framework.record.read',
  'governance.record.read', 'governance.record.write', 'incident.record.read', 'incident.record.write',
  'policy.document.read', 'policy.document.write', 'profile.record.read',
  'remediation.plan.write', 'remediation.task.read', 'report.document.read', 'report.document.write',
  'risk.record.read', 'risk.record.write', 'team.member.read',
  'vendor.record.read', 'vendor.record.write', 'workflow.instance.read', 'workflow.instance.write',
  'workspace.config.read',
];

export const AGRC_ROLE_NAV_CONFIGS: Record<string, string[]> = {
  owner: ALL_NAV_PERMS,
  admin: ALL_NAV_PERMS,
  tenant_admin: ALL_NAV_PERMS,
  executive_owner: [
    'workspace.config.read', 'profile.record.read', 'analytics.report.read', 'report.document.read',
    'governance.record.read', 'risk.record.read', 'compliance.program.read', 'audit.record.read',
    'evidence.item.read', 'vendor.record.read', 'bcp.plan.read', 'incident.record.read',
    'copilot.assistant.read', 'ai.agent.read', 'team.member.read',
  ],
  grc_manager: [
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read', 'workflow.instance.write',
    'policy.document.read', 'policy.document.write', 'risk.record.read', 'risk.record.write',
    'framework.record.read', 'framework.record.manage', 'control.record.read', 'control.record.write',
    'assessment.record.read', 'assessment.record.write', 'assessment.record.manage',
    'audit.record.read', 'audit.record.manage', 'analytics.report.read', 'copilot.assistant.read',
    'report.document.read', 'report.document.write', 'compliance.program.read', 'compliance.program.write',
    'evidence.item.read', 'evidence.item.write', 'governance.record.read', 'governance.record.write',
    'vendor.record.read', 'vendor.record.write', 'incident.record.read', 'incident.record.write',
    'bcp.plan.read', 'bcp.plan.write', 'remediation.task.read', 'remediation.plan.write',
    'team.member.read', 'ai.agent.read', 'ai.agent.manage',
  ],
  audit_manager: [
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read',
    'audit.record.read', 'audit.record.manage', 'audit.record.write',
    'policy.document.read', 'risk.record.read', 'framework.record.read', 'control.record.read',
    'assessment.record.read', 'assessment.record.manage', 'analytics.report.read',
    'copilot.assistant.read', 'report.document.read', 'report.document.write',
    'compliance.program.read', 'evidence.item.read', 'evidence.item.write',
    'governance.record.read', 'remediation.task.read', 'remediation.plan.write',
    'vendor.record.read', 'incident.record.read', 'bcp.plan.read', 'team.member.read', 'ai.agent.read',
  ],
  compliance_lead: [
    'policy.document.read', 'policy.document.write', 'risk.record.read', 'framework.record.read', 'framework.record.manage',
    'control.record.read', 'control.record.write', 'assessment.record.read', 'assessment.record.write', 'assessment.record.manage',
    'audit.record.read', 'analytics.report.read', 'copilot.assistant.read', 'report.document.read', 'report.document.write',
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read', 'workflow.instance.write',
    'compliance.program.read', 'compliance.program.write', 'evidence.item.read', 'evidence.item.write',
    'governance.record.read', 'governance.record.write', 'vendor.record.read', 'incident.record.read', 'incident.record.write',
    'bcp.plan.read', 'bcp.plan.write', 'team.member.read', 'ai.agent.read', 'ai.agent.manage',
  ],
  compliance_officer: [
    'policy.document.read', 'policy.document.write', 'risk.record.read', 'framework.record.read', 'framework.record.manage',
    'control.record.read', 'control.record.write', 'assessment.record.read', 'assessment.record.write', 'assessment.record.manage',
    'audit.record.read', 'analytics.report.read', 'copilot.assistant.read', 'report.document.read', 'report.document.write',
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read', 'workflow.instance.write',
    'compliance.program.read', 'compliance.program.write', 'evidence.item.read', 'evidence.item.write',
    'governance.record.read', 'governance.record.write', 'vendor.record.read', 'incident.record.read', 'incident.record.write',
    'bcp.plan.read', 'bcp.plan.write', 'team.member.read', 'ai.agent.read', 'ai.agent.manage',
  ],
  risk_manager: [
    'policy.document.read', 'risk.record.read', 'risk.record.write', 'framework.record.read',
    'control.record.read', 'control.record.write', 'assessment.record.read', 'assessment.record.manage',
    'analytics.report.read', 'copilot.assistant.read', 'report.document.read',
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read',
    'compliance.program.read', 'evidence.item.read',
    'governance.record.read', 'remediation.task.read', 'remediation.plan.write',
    'vendor.record.read', 'incident.record.read', 'incident.record.write', 'bcp.plan.read', 'bcp.plan.write', 'team.member.read',
    'ai.agent.read', 'ai.agent.manage',
  ],
  data_governance_lead: [
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read',
    'governance.record.read', 'governance.record.write', 'policy.document.read', 'policy.document.write',
    'compliance.program.read', 'evidence.item.read', 'analytics.report.read',
    'copilot.assistant.read', 'report.document.read', 'ai.agent.read', 'team.member.read',
  ],
  risk_lead: [
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read',
    'risk.record.read', 'risk.record.write', 'control.record.read',
    'assessment.record.read', 'analytics.report.read', 'copilot.assistant.read',
    'report.document.read', 'compliance.program.read', 'evidence.item.read',
    'governance.record.read', 'remediation.task.read', 'team.member.read', 'ai.agent.read',
  ],
  auditor: [
    'policy.document.read', 'risk.record.read', 'framework.record.read', 'control.record.read',
    'assessment.record.read', 'assessment.record.manage', 'audit.record.read', 'audit.record.manage',
    'analytics.report.read', 'copilot.assistant.read', 'report.document.read',
    'workspace.config.read', 'profile.record.read', 'workflow.instance.read',
    'compliance.program.read', 'evidence.item.read',
    'governance.record.read', 'remediation.task.read', 'vendor.record.read', 'incident.record.read', 'bcp.plan.read', 'team.member.read',
    'ai.agent.read',
  ],
  viewer: [
    'policy.document.read', 'risk.record.read', 'framework.record.read', 'control.record.read',
    'assessment.record.read', 'audit.record.read', 'analytics.report.read', 'copilot.assistant.read',
    'report.document.read', 'workspace.config.read', 'profile.record.read',
    'compliance.program.read', 'evidence.item.read',
    'governance.record.read', 'vendor.record.read', 'bcp.plan.read', 'team.member.read',
  ],
};
