import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const WORKFLOW_WIDGETS: WidgetManifest[] = [
  {
    id: 'workflow.sankey',
    key: 'workflow_sankey',
    title: 'Workflow Sankey',
    titleAr: 'سير العمل سانكي',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../echart-components/sankey/workflow-sankey.component').then(m => m.WorkflowSankeyComponent),
    icon: '🔀',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'workflow.timeline',
    key: 'workflow_timeline',
    title: 'Workflow Timeline',
    titleAr: 'خط زمني لسير العمل',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/timeline/workflow-timeline-cc.component').then(m => m.WorkflowTimelineCcComponent),
    icon: '📅',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'workflow.process_flow',
    key: 'process_flow',
    title: 'Process Flow',
    titleAr: 'تدفق العمليات',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/process-flow.component').then(m => m.ProcessFlowComponent),
    icon: '🔄',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'workflow.gantt_timeline',
    key: 'gantt_timeline',
    title: 'Gantt Timeline',
    titleAr: 'مخطط جانت',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/timeline/gantt-timeline.component').then(m => m.GanttTimelineComponent),
    icon: '📅',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'workflow.ninety_day_timeline',
    key: 'ninety_day_timeline',
    title: '90-Day Timeline',
    titleAr: 'خط زمني 90 يوم',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/timeline/ninety-day-timeline.component').then(m => m.NinetyDayTimelineComponent),
    icon: '📅',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'workflow.anomaly_timeline',
    key: 'anomaly_timeline',
    title: 'Anomaly Timeline',
    titleAr: 'خط زمني للشذوذ',
    category: 'workflow',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/timeline/anomaly-timeline.component').then(m => m.AnomalyTimelineComponent),
    icon: '📅',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'workflow.sla_by_role',
    key: 'sla_by_role',
    title: 'SLA by Role',
    titleAr: 'اتفاقية الخدمة حسب الدور',
    category: 'workflow',
    engine: 'angular',
    component: () => import('../../../components/executive/sla-by-role.widget').then(m => m.SlaByRoleWidgetComponent),
    icon: '⏱',
    defaultSize: { cols: 4, rows: 2 },
    schemaVersion: 1,
  },
];
