import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const COMPLIANCE_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'COMPLIANCE.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'COMPLIANCE.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'COMPLIANCE.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'COMPLIANCE.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'COMPLIANCE.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'COMPLIANCE.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'COMPLIANCE.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'COMPLIANCE.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'COMPLIANCE.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  REINDEX_NOT_FOUND: { code: 'COMPLIANCE.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'COMPLIANCE.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'COMPLIANCE.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'COMPLIANCE.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'COMPLIANCE.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'COMPLIANCE.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  TEST_DEFINITION_NOT_FOUND: { code: 'COMPLIANCE.TEST_DEFINITION_NOT_FOUND', httpStatus: 404, messageEn: 'Test Definition not found', messageAr: 'Test Definition غير موجود' },
  TEST_DEFINITION_ALREADY_EXISTS: { code: 'COMPLIANCE.TEST_DEFINITION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Test Definition already exists', messageAr: 'Test Definition موجود بالفعل' },
  TEST_DEFINITION_VALIDATION_FAILED: { code: 'COMPLIANCE.TEST_DEFINITION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Test Definition validation failed', messageAr: 'فشل التحقق من Test Definition' },
  TEST_DEFINITIONS_NOT_FOUND: { code: 'COMPLIANCE.TEST_DEFINITIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Test Definitions not found', messageAr: 'Test Definitions غير موجود' },
  TEST_DEFINITIONS_ALREADY_EXISTS: { code: 'COMPLIANCE.TEST_DEFINITIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Test Definitions already exists', messageAr: 'Test Definitions موجود بالفعل' },
  TEST_DEFINITIONS_VALIDATION_FAILED: { code: 'COMPLIANCE.TEST_DEFINITIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Test Definitions validation failed', messageAr: 'فشل التحقق من Test Definitions' },
  EXECUTE_NOT_FOUND: { code: 'COMPLIANCE.EXECUTE_NOT_FOUND', httpStatus: 404, messageEn: 'Execute not found', messageAr: 'Execute غير موجود' },
  EXECUTE_ALREADY_EXISTS: { code: 'COMPLIANCE.EXECUTE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Execute already exists', messageAr: 'Execute موجود بالفعل' },
  EXECUTE_VALIDATION_FAILED: { code: 'COMPLIANCE.EXECUTE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Execute validation failed', messageAr: 'فشل التحقق من Execute' },
  HISTORY_NOT_FOUND: { code: 'COMPLIANCE.HISTORY_NOT_FOUND', httpStatus: 404, messageEn: 'History not found', messageAr: 'History غير موجود' },
  HISTORY_ALREADY_EXISTS: { code: 'COMPLIANCE.HISTORY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'History already exists', messageAr: 'History موجود بالفعل' },
  HISTORY_VALIDATION_FAILED: { code: 'COMPLIANCE.HISTORY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'History validation failed', messageAr: 'فشل التحقق من History' },
  EVALUATE_NOT_FOUND: { code: 'COMPLIANCE.EVALUATE_NOT_FOUND', httpStatus: 404, messageEn: 'Evaluate not found', messageAr: 'Evaluate غير موجود' },
  EVALUATE_ALREADY_EXISTS: { code: 'COMPLIANCE.EVALUATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Evaluate already exists', messageAr: 'Evaluate موجود بالفعل' },
  EVALUATE_VALIDATION_FAILED: { code: 'COMPLIANCE.EVALUATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Evaluate validation failed', messageAr: 'فشل التحقق من Evaluate' },
  EVALUATE_FRAMEWORK_NOT_FOUND: { code: 'COMPLIANCE.EVALUATE_FRAMEWORK_NOT_FOUND', httpStatus: 404, messageEn: 'Evaluate Framework not found', messageAr: 'Evaluate Framework غير موجود' },
  EVALUATE_FRAMEWORK_ALREADY_EXISTS: { code: 'COMPLIANCE.EVALUATE_FRAMEWORK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Evaluate Framework already exists', messageAr: 'Evaluate Framework موجود بالفعل' },
  EVALUATE_FRAMEWORK_VALIDATION_FAILED: { code: 'COMPLIANCE.EVALUATE_FRAMEWORK_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Evaluate Framework validation failed', messageAr: 'فشل التحقق من Evaluate Framework' },
  CAMPAIGNS_NOT_FOUND: { code: 'COMPLIANCE.CAMPAIGNS_NOT_FOUND', httpStatus: 404, messageEn: 'Campaigns not found', messageAr: 'Campaigns غير موجود' },
  CAMPAIGNS_ALREADY_EXISTS: { code: 'COMPLIANCE.CAMPAIGNS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Campaigns already exists', messageAr: 'Campaigns موجود بالفعل' },
  CAMPAIGNS_VALIDATION_FAILED: { code: 'COMPLIANCE.CAMPAIGNS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Campaigns validation failed', messageAr: 'فشل التحقق من Campaigns' },
  RULES_NOT_FOUND: { code: 'COMPLIANCE.RULES_NOT_FOUND', httpStatus: 404, messageEn: 'Rules not found', messageAr: 'Rules غير موجود' },
  RULES_ALREADY_EXISTS: { code: 'COMPLIANCE.RULES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Rules already exists', messageAr: 'Rules موجود بالفعل' },
  RULES_VALIDATION_FAILED: { code: 'COMPLIANCE.RULES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Rules validation failed', messageAr: 'فشل التحقق من Rules' },
  SCAN_NOT_FOUND: { code: 'COMPLIANCE.SCAN_NOT_FOUND', httpStatus: 404, messageEn: 'Scan not found', messageAr: 'Scan غير موجود' },
  SCAN_ALREADY_EXISTS: { code: 'COMPLIANCE.SCAN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Scan already exists', messageAr: 'Scan موجود بالفعل' },
  SCAN_VALIDATION_FAILED: { code: 'COMPLIANCE.SCAN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Scan validation failed', messageAr: 'فشل التحقق من Scan' },
  DASHBOARD_NOT_FOUND: { code: 'COMPLIANCE.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'COMPLIANCE.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'COMPLIANCE.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },

  FRAMEWORK_NOT_FOUND: { code: 'COMPLIANCE.FRAMEWORK_NOT_FOUND', httpStatus: 404, messageEn: 'Framework not found', messageAr: 'الإطار غير موجود' },
  FRAMEWORK_ALREADY_EXISTS: { code: 'COMPLIANCE.FRAMEWORK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Framework already exists', messageAr: 'الإطار موجود بالفعل' },
  ASSESSMENT_NOT_FOUND: { code: 'COMPLIANCE.ASSESSMENT_NOT_FOUND', httpStatus: 404, messageEn: 'Assessment not found', messageAr: 'التقييم غير موجود' },
  ASSESSMENT_ALREADY_IN_PROGRESS: { code: 'COMPLIANCE.ASSESSMENT_ALREADY_IN_PROGRESS', httpStatus: 409, messageEn: 'Assessment already in progress', messageAr: 'التقييم قيد التنفيذ بالفعل' },
  OBLIGATION_NOT_FOUND: { code: 'COMPLIANCE.OBLIGATION_NOT_FOUND', httpStatus: 404, messageEn: 'Obligation not found', messageAr: 'الالتزام غير موجود' },
  OBLIGATION_OVERDUE: { code: 'COMPLIANCE.OBLIGATION_OVERDUE', httpStatus: 422, messageEn: 'Obligation is overdue', messageAr: 'الالتزام متأخر' },
  GAP_NOT_FOUND: { code: 'COMPLIANCE.GAP_NOT_FOUND', httpStatus: 404, messageEn: 'Gap not found', messageAr: 'الفجوة غير موجودة' },
  ATTESTATION_NOT_FOUND: { code: 'COMPLIANCE.ATTESTATION_NOT_FOUND', httpStatus: 404, messageEn: 'Attestation not found', messageAr: 'الإقرار غير موجود' },
  ATTESTATION_EXPIRED: { code: 'COMPLIANCE.ATTESTATION_EXPIRED', httpStatus: 422, messageEn: 'Attestation has expired', messageAr: 'انتهت صلاحية الإقرار' },
  CONTROL_MAPPING_NOT_FOUND: { code: 'COMPLIANCE.CONTROL_MAPPING_NOT_FOUND', httpStatus: 404, messageEn: 'Control mapping not found', messageAr: 'ربط الضابط غير موجود' },
  FINDING_NOT_FOUND: { code: 'COMPLIANCE.FINDING_NOT_FOUND', httpStatus: 404, messageEn: 'Finding not found', messageAr: 'الملاحظة غير موجودة' },
  REMEDIATION_NOT_FOUND: { code: 'COMPLIANCE.REMEDIATION_NOT_FOUND', httpStatus: 404, messageEn: 'Remediation not found', messageAr: 'المعالجة غير موجودة' },
  SELF_APPROVAL_BLOCKED: { code: 'COMPLIANCE.SELF_APPROVAL_BLOCKED', httpStatus: 403, messageEn: 'Self-approval is not allowed for this action', messageAr: 'لا يُسمح بالموافقة الذاتية لهذا الإجراء' },
  SOD_VIOLATION: { code: 'COMPLIANCE.SOD_VIOLATION', httpStatus: 403, messageEn: 'Separation of duties violation detected', messageAr: 'تم اكتشاف انتهاك لفصل المهام' },

  UNAUTHORIZED: { code: 'COMPLIANCE.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for compliance operation', messageAr: 'صلاحيات غير كافية لعملية compliance' },
  INVALID_STATE_TRANSITION: { code: 'COMPLIANCE.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'COMPLIANCE.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'COMPLIANCE.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'COMPLIANCE.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'COMPLIANCE.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type ComplianceErrorCode = keyof typeof COMPLIANCE_ERROR_CODES;
