// @ts-nocheck — module-layer imports not yet extracted
import type { RouteEntry } from '../../../platform/products/product-registry';

export const AGRC_ROUTES: RouteEntry[] = [
  { method: 'GET', path: '/api/auth', description: 'Authentication & session' },
  { method: 'GET', path: '/api/risks', permission: 'risk.record.read', description: 'Risk register' },
  { method: 'GET', path: '/api/risk-ws', permission: 'risk.record.read', description: 'Risk workspace' },
  { method: 'GET', path: '/api/risk-smart', permission: 'risk.record.read', description: 'Risk smart analysis' },
  { method: 'GET', path: '/api/risk-scoring', permission: 'risk.record.read', description: 'Risk scoring' },
  { method: 'GET', path: '/api/risk-metrics', permission: 'risk.record.read', description: 'Risk metrics' },
  { method: 'GET', path: '/api/compliance', permission: 'compliance.program.read', description: 'Compliance module' },
  { method: 'GET', path: '/api/compliance-ws', permission: 'compliance.program.read', description: 'Compliance workspace' },
  { method: 'GET', path: '/api/controls', permission: 'control.record.read', description: 'Controls management' },
  { method: 'GET', path: '/api/frameworks', permission: 'framework.record.read', description: 'Framework management' },
  { method: 'GET', path: '/api/audit', permission: 'audit.record.read', description: 'Audit module' },
  { method: 'GET', path: '/api/audit/universe', permission: 'audit.record.read', description: 'Audit universe' },
  { method: 'GET', path: '/api/audit/schedules', permission: 'audit.record.read', description: 'Audit schedules' },
  { method: 'GET', path: '/api/audit/cross-module', permission: 'audit.record.read', description: 'Audit cross-module' },
  { method: 'GET', path: '/api/evidence', permission: 'evidence.item.read', description: 'Evidence lifecycle' },
  { method: 'GET', path: '/api/evidence-catalog', permission: 'evidence.item.read', description: 'Evidence catalog' },
  { method: 'GET', path: '/api/governance', permission: 'governance.record.read', description: 'Governance module' },
  { method: 'GET', path: '/api/governance/mandates', permission: 'governance.record.read', description: 'Governance mandates' },
  { method: 'GET', path: '/api/governance/delegations', permission: 'delegation.chain.read', description: 'Governance delegations' },
  { method: 'GET', path: '/api/governance/raci', permission: 'governance.record.read', description: 'Governance RACI' },
  { method: 'GET', path: '/api/governance/board-packs', permission: 'governance.record.read', description: 'Board packs' },
  { method: 'GET', path: '/api/governance/executive-summaries', permission: 'governance.record.read', description: 'Executive summaries' },
  { method: 'GET', path: '/api/governance/reviews', permission: 'governance.record.read', description: 'Governance reviews' },
  { method: 'GET', path: '/api/governance/health', permission: 'governance.record.read', description: 'Governance health' },
  { method: 'GET', path: '/api/governance/structure', permission: 'governance.record.read', description: 'Governance structure' },
  { method: 'GET', path: '/api/governance/responsibilities', permission: 'governance.record.read', description: 'Governance responsibilities' },
  { method: 'GET', path: '/api/governance/raci-templates', permission: 'governance.record.read', description: 'RACI templates' },
  { method: 'GET', path: '/api/workflows', permission: 'workflow.instance.read', description: 'Workflow engine' },
  { method: 'GET', path: '/api/workflow-templates', permission: 'workflow.instance.read', description: 'Workflow templates' },
  { method: 'GET', path: '/api/vendors', permission: 'vendor.record.read', description: 'Vendor management' },
  { method: 'GET', path: '/api/vendors-advanced', permission: 'vendor.record.read', description: 'Vendor advanced' },
  { method: 'GET', path: '/api/vendor-risk', permission: 'vendor.record.read', description: 'Vendor risk extended' },
  { method: 'GET', path: '/api/incidents', permission: 'incident.record.read', description: 'Incident management' },
  { method: 'GET', path: '/api/incidents-advanced', permission: 'incident.record.read', description: 'Incident advanced' },
  { method: 'GET', path: '/api/bcp', permission: 'bcp.plan.read', description: 'Business continuity' },
  { method: 'GET', path: '/api/bcm-advanced', permission: 'bcp.plan.read', description: 'BCM advanced' },
  { method: 'GET', path: '/api/foundation-governance', permission: 'foundation.org.read', description: 'Foundation governance' },
  { method: 'GET', path: '/api/foundation/roles', permission: 'workspace.config.read', description: 'Foundation roles' },
  { method: 'GET', path: '/api/access-review', permission: 'workspace.config.read', description: 'Access review' },
  { method: 'GET', path: '/api/users', permission: 'users.account.manage', description: 'User management' },
  { method: 'GET', path: '/api/teams', permission: 'team.member.read', description: 'Team management' },
  { method: 'GET', path: '/api/policies', permission: 'policy.document.read', description: 'Policy management' },
  { method: 'GET', path: '/api/assessments', permission: 'assessment.record.read', description: 'Assessments' },
  { method: 'GET', path: '/api/remediation', permission: 'remediation.task.read', description: 'Remediation tracking' },
  { method: 'GET', path: '/api/assets', permission: 'asset.record.read', description: 'Asset management' },
  { method: 'GET', path: '/api/findings', permission: 'audit.record.read', description: 'Findings management' },
  { method: 'GET', path: '/api/qiyas', permission: 'analytics.report.read', description: 'Qiyas maturity' },
  { method: 'GET', path: '/api/ai-assets', permission: 'ai.agent.read', description: 'AI asset inventory' },
  { method: 'GET', path: '/api/model-registry', permission: 'ai.agent.read', description: 'AI model registry' },
  { method: 'GET', path: '/api/prompt-registry', permission: 'ai.agent.read', description: 'AI prompt registry' },
  { method: 'GET', path: '/api/agent-registry', permission: 'ai.agent.read', description: 'AI agent registry' },
  { method: 'GET', path: '/api/ai-bindings', permission: 'ai.agent.read', description: 'AI binding governance' },
  { method: 'GET', path: '/api/ai-governance-config', permission: 'ai.agent.read', description: 'AI governance config' },
  { method: 'GET', path: '/api/ai-governance-ops', permission: 'ai.agent.read', description: 'AI governance ops' },
  { method: 'GET', path: '/api/agrc-os', permission: 'platform.agent.read', description: 'AGRC-OS engine' },
  { method: 'GET', path: '/api/training', permission: 'training.record.read', description: 'Training management' },
  { method: 'GET', path: '/api/approvals', permission: 'approval.request.read', description: 'Approval routing' },
  { method: 'GET', path: '/api/dashboard', permission: 'analytics.report.read', description: 'Dashboard data' },
  { method: 'GET', path: '/api/reports', permission: 'report.document.read', description: 'Report generation' },
  { method: 'GET', path: '/api/notifications', permission: 'notification.config.read', description: 'Notifications' },
  { method: 'GET', path: '/api/onboarding', description: 'Onboarding v2' },
  { method: 'GET', path: '/api/provisioning', description: 'Provisioning' },
];
