/**
 * Foundation and organizational structure routes.
 * Covers: workspaces, tenants, users, teams, org hierarchy, departments,
 * locations, positions, roles, profiles, business units, and related
 * foundation-level endpoints.
 */
import type { RouteDefinition } from '../routing/route-definition';

export const CORE_FOUNDATION_ROUTES: RouteDefinition[] = [
  {
    id: "routes_workspace_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/workspace-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/workspaces",
    guards: { module: "foundation" },
    order: 164,
  },
  // Workspace-home route entry intentionally omitted — landing route
  // is DB-resolved via dos.tenant_landing_config + UI-OS runtime
  // (NO FRONTEND INVENTION per AGENTS.md). Reinstate only via DB
  // contract when the route catalog table emits it.
  {
    id: "routes_workspace_lifecycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/workspace-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/workspace-lifecycle",
    guards: { module: "foundation" },
    order: 166,
  },
  {
    id: "routes_workspace_lifecycle_routes__alias_api_ninety_day_plan",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/workspace-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/ninety-day-plan",
    guards: { module: "foundation" },
    order: 167,
  },
  {
    id: "routes_workspace_ignite_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/tenant/workspace-ignite.routes",
    exportName: "default",
    mountPath: "/api/workspace-ignite",
    guards: { module: "foundation" },
    order: 168,
  },
  {
    id: "routes_workspace_ignite_routes__alias_api_workspace",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/tenant/workspace-ignite.routes",
    exportName: "default",
    mountPath: "/api/workspace",
    guards: { module: "foundation" },
    order: 169,
  },
  {
    id: "routes_tenant_home_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/tenant/tenant-home.routes",
    exportName: "default",
    mountPath: "/api/tenant-home",
    guards: { module: "foundation" },
    order: 170,
  },
  {
    id: "routes_tenant_config_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/tenant/tenant-config.routes",
    exportName: "default",
    mountPath: "/api/tenant-config",
    guards: { module: "foundation" },
    order: 171,
  },
  {
    id: "routes_tenant_email_config_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/tenant/tenant-email-config.routes",
    exportName: "default",
    mountPath: "/api/tenant-email-config",
    guards: { module: "foundation" },
    order: 172,
  },
  {
    id: "routes_entitlements_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/admin/routes/entitlements.routes",
    exportName: "default",
    mountPath: "/api/tenant",
    guards: { module: "foundation" },
    order: 173,
  },
  {
    id: "routes_tier_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/admin/routes/tier.routes",
    exportName: "default",
    mountPath: "/api/tier",
    guards: { module: "foundation" },
    order: 174,
  },
  {
    id: "routes_users_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/users.routes",
    exportName: "default",
    mountPath: "/api/users",
    guards: { module: "foundation" },
    order: 177,
  },
  {
    id: "routes_locations_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/locations.routes",
    exportName: "default",
    mountPath: "/api/locations",
    guards: { module: "foundation" },
    order: 182,
  },
  {
    id: "routes_departments_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/departments.routes",
    exportName: "default",
    mountPath: "/api/departments",
    guards: { module: "foundation" },
    order: 183,
  },
  {
    id: "routes_organizations_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/organizations.routes",
    exportName: "default",
    mountPath: "/api/organizations",
    guards: { module: "foundation" },
    order: 184,
  },
  {
    id: "routes_org_hierarchy_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/org-hierarchy.routes",
    exportName: "default",
    mountPath: "/api/org-hierarchy",
    guards: { module: "foundation" },
    order: 185,
  },
  {
    id: "routes_business_units_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/business-units.routes",
    exportName: "default",
    mountPath: "/api/business-units",
    guards: { module: "foundation" },
    order: 185,
  },
  {
    id: "routes_user_lifecycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/user-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/user-lifecycle",
    guards: { module: "foundation" },
    order: 191,
  },
  {
    id: "routes_team_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/team/routes/team.routes",
    exportName: "default",
    mountPath: "/api/teams",
    guards: { module: "foundation" },
    order: 207,
  },
  // DEFERRED: routes_team_member_lifecycle_routes — no source file exists yet (consumed by admin-user-api.service.ts)
  // {
  //   id: "routes_team_member_lifecycle_routes",
  //   productKey: "shahin-ai",
  //   ownerKind: "product",
  //   sourceKind: "defaultExport",
  //   exportName: "default",
  //   mountPath: "/api/member-lifecycle",
  //   guards: { module: "foundation" },
  //   order: 209,
  // },
  // DELETED: role-profile, role-detail, profiles, role-matrix — empty stubs removed (Law 7)
  {
    id: "routes_public_content_routes:permissionsRouter",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/bootstrap/public-content.routes",
    exportName: "permissionsRouter",
    mountPath: "/api/profiles",
    guards: { module: "foundation" },
    order: 217,
    intentionalDuplicateGroup: "path:/api/profiles",
  },
  {
    id: "routes_roadmap_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/products/roadmap.routes",
    exportName: "default",
    mountPath: "/api/roadmap",
    guards: { module: "foundation" },
    order: 202,
  },
  {
    id: "routes_roadmap_builder_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/products/roadmap-builder.routes",
    exportName: "default",
    mountPath: "/api/roadmap-builder",
    guards: { module: "foundation" },
    order: 203,
  },
  {
    id: "routes_review_cycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/workflow/routes/misc/review-cycle.routes",
    exportName: "default",
    mountPath: "/api/review-cycles",
    guards: { module: "foundation" },
    order: 204,
  },
  {
    id: "routes_positions_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/positions.routes",
    exportName: "default",
    mountPath: "/api/positions",
    guards: { module: "foundation" },
    order: 349,
  },
  {
    id: "routes_ownership_mapping_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/ownership-mapping.routes",
    exportName: "default",
    mountPath: "/api/ownership-mapping",
    guards: { module: "foundation" },
    order: 350,
  },
  // DELETED: routes_org_structure_admin_routes — no source file, no frontend consumer
  {
    id: "routes_foundation_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/foundation-governance.routes",
    exportName: "default",
    mountPath: "/api/foundation-governance",
    guards: { module: "foundation" },
    order: 353,
  },
  {
    id: "routes_foundation_roles_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/foundation-roles.routes",
    exportName: "default",
    mountPath: "/api/foundation/roles",
    guards: { module: "foundation" },
    order: 354,
  },
  {
    id: "routes_foundation_core_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/foundation.routes",
    exportName: "default",
    mountPath: "/api/foundation",
    guards: { module: "foundation" },
    order: 355,
  },
  {
    id: "routes_access_review_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/access-review.routes",
    exportName: "default",
    mountPath: "/api/access-review",
    guards: { module: "foundation" },
    order: 356,
  },
  {
    id: "routes_committee_management_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/committee-management.routes",
    exportName: "default",
    mountPath: "/api/committees",
    guards: { module: "foundation" },
    order: 357,
  },
  {
    id: "routes_sod_check_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/sod-check.routes",
    exportName: "default",
    mountPath: "/api/sod-check",
    guards: { module: "foundation" },
    order: 358,
  },
  // Wave 1 backend completion — authority + sod live router lives in the
  // foundation aggregator under /api/foundation/sod and /api/foundation/authority.
  // Catalog entries below mirror the live mount paths so route-catalog
  // consumers see the same surface the express tree actually exposes.
  {
    id: "routes_authority_sod_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/foundation/routes/authority-sod.routes",
    exportName: "authoritySodRouter",
    mountPath: "/api/foundation",
    guards: { module: "foundation" },
    order: 358,
    intentionalDuplicateGroup: "path:/api/foundation/sod",
  },
  {
    id: "routes_sod_exception_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/foundation/routes/sod-exception.routes",
    exportName: "sodExceptionRouter",
    mountPath: "/api/foundation/sod/exceptions",
    guards: { module: "foundation" },
    order: 358,
  },
  {
    id: "routes_sod_review_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/foundation/routes/sod-review.routes",
    exportName: "sodReviewRouter",
    mountPath: "/api/foundation/sod/reviews",
    guards: { module: "foundation" },
    order: 358,
  },
  {
    id: "routes_delegation_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/delegation.routes",
    exportName: "default",
    mountPath: "/api/delegations",
    guards: { module: "foundation" },
    order: 359,
  },
  {
    id: "routes_bulk_invite_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/foundation/routes/bulk-invite.routes",
    exportName: "default",
    mountPath: "/api/bulk-invite",
    guards: { module: "foundation" },
    order: 360,
  },
];
