"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.logSuperAdminFieldAccess = exports.logFieldDenial = exports.PII_VALUE_PATTERNS = exports.registerModuleSensitiveFields = exports.redactPIIValues = exports.fieldPermissionCode = exports.isSensitiveField = exports.isRestrictedField = exports.classifyFieldSensitivity = exports.requireOwnership = exports.fieldRbacFilter = exports.fieldRbac = exports.clearSubscriptionCache = exports.invalidateSubscriptionCache = exports.setSubscriptionLookup = exports.subscriptionStatusGuard = exports.clearModuleCache = exports.invalidateModuleCache = exports.setModuleLookup = exports.moduleGuard = exports.perTenantIpKey = exports.perTenantKey = exports.tenantGuard = void 0;
var tenant_guard_1 = require("./tenant-guard");
Object.defineProperty(exports, "tenantGuard", { enumerable: true, get: function () { return tenant_guard_1.tenantGuard; } });
Object.defineProperty(exports, "perTenantKey", { enumerable: true, get: function () { return tenant_guard_1.perTenantKey; } });
Object.defineProperty(exports, "perTenantIpKey", { enumerable: true, get: function () { return tenant_guard_1.perTenantIpKey; } });
var module_guard_1 = require("./module-guard");
Object.defineProperty(exports, "moduleGuard", { enumerable: true, get: function () { return module_guard_1.moduleGuard; } });
Object.defineProperty(exports, "setModuleLookup", { enumerable: true, get: function () { return module_guard_1.setModuleLookup; } });
Object.defineProperty(exports, "invalidateModuleCache", { enumerable: true, get: function () { return module_guard_1.invalidateModuleCache; } });
Object.defineProperty(exports, "clearModuleCache", { enumerable: true, get: function () { return module_guard_1.clearModuleCache; } });
var subscription_status_guard_1 = require("./subscription-status-guard");
Object.defineProperty(exports, "subscriptionStatusGuard", { enumerable: true, get: function () { return subscription_status_guard_1.subscriptionStatusGuard; } });
Object.defineProperty(exports, "setSubscriptionLookup", { enumerable: true, get: function () { return subscription_status_guard_1.setSubscriptionLookup; } });
Object.defineProperty(exports, "invalidateSubscriptionCache", { enumerable: true, get: function () { return subscription_status_guard_1.invalidateSubscriptionCache; } });
Object.defineProperty(exports, "clearSubscriptionCache", { enumerable: true, get: function () { return subscription_status_guard_1.clearSubscriptionCache; } });
var field_rbac_1 = require("./field-rbac");
Object.defineProperty(exports, "fieldRbac", { enumerable: true, get: function () { return field_rbac_1.fieldRbac; } });
Object.defineProperty(exports, "fieldRbacFilter", { enumerable: true, get: function () { return field_rbac_1.fieldRbacFilter; } });
var require_ownership_1 = require("./require-ownership");
Object.defineProperty(exports, "requireOwnership", { enumerable: true, get: function () { return require_ownership_1.requireOwnership; } });
var sensitive_fields_1 = require("./sensitive-fields");
Object.defineProperty(exports, "classifyFieldSensitivity", { enumerable: true, get: function () { return sensitive_fields_1.classifyFieldSensitivity; } });
Object.defineProperty(exports, "isRestrictedField", { enumerable: true, get: function () { return sensitive_fields_1.isRestrictedField; } });
Object.defineProperty(exports, "isSensitiveField", { enumerable: true, get: function () { return sensitive_fields_1.isSensitiveField; } });
Object.defineProperty(exports, "fieldPermissionCode", { enumerable: true, get: function () { return sensitive_fields_1.fieldPermissionCode; } });
Object.defineProperty(exports, "redactPIIValues", { enumerable: true, get: function () { return sensitive_fields_1.redactPIIValues; } });
Object.defineProperty(exports, "registerModuleSensitiveFields", { enumerable: true, get: function () { return sensitive_fields_1.registerModuleSensitiveFields; } });
Object.defineProperty(exports, "PII_VALUE_PATTERNS", { enumerable: true, get: function () { return sensitive_fields_1.PII_VALUE_PATTERNS; } });
var field_denial_audit_1 = require("./field-denial-audit");
Object.defineProperty(exports, "logFieldDenial", { enumerable: true, get: function () { return field_denial_audit_1.logFieldDenial; } });
Object.defineProperty(exports, "logSuperAdminFieldAccess", { enumerable: true, get: function () { return field_denial_audit_1.logSuperAdminFieldAccess; } });
//# sourceMappingURL=index.js.map