import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const QIYAS_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'QIYAS.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'QIYAS.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'QIYAS.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'QIYAS.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'QIYAS.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'QIYAS.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'QIYAS.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'QIYAS.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'QIYAS.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  MATURITY_ANALYTICS_NOT_FOUND: { code: 'QIYAS.MATURITY_ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Maturity Analytics not found', messageAr: 'Maturity Analytics غير موجود' },
  MATURITY_ANALYTICS_ALREADY_EXISTS: { code: 'QIYAS.MATURITY_ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maturity Analytics already exists', messageAr: 'Maturity Analytics موجود بالفعل' },
  MATURITY_ANALYTICS_VALIDATION_FAILED: { code: 'QIYAS.MATURITY_ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maturity Analytics validation failed', messageAr: 'فشل التحقق من Maturity Analytics' },
  BELOW_THRESHOLD_NOT_FOUND: { code: 'QIYAS.BELOW_THRESHOLD_NOT_FOUND', httpStatus: 404, messageEn: 'Below Threshold not found', messageAr: 'Below Threshold غير موجود' },
  BELOW_THRESHOLD_ALREADY_EXISTS: { code: 'QIYAS.BELOW_THRESHOLD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Below Threshold already exists', messageAr: 'Below Threshold موجود بالفعل' },
  BELOW_THRESHOLD_VALIDATION_FAILED: { code: 'QIYAS.BELOW_THRESHOLD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Below Threshold validation failed', messageAr: 'فشل التحقق من Below Threshold' },
  RESPONSE_RATES_NOT_FOUND: { code: 'QIYAS.RESPONSE_RATES_NOT_FOUND', httpStatus: 404, messageEn: 'Response Rates not found', messageAr: 'Response Rates غير موجود' },
  RESPONSE_RATES_ALREADY_EXISTS: { code: 'QIYAS.RESPONSE_RATES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Response Rates already exists', messageAr: 'Response Rates موجود بالفعل' },
  RESPONSE_RATES_VALIDATION_FAILED: { code: 'QIYAS.RESPONSE_RATES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Response Rates validation failed', messageAr: 'فشل التحقق من Response Rates' },
  REINDEX_NOT_FOUND: { code: 'QIYAS.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'QIYAS.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'QIYAS.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'QIYAS.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'QIYAS.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'QIYAS.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'QIYAS.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'QIYAS.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'QIYAS.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  OVERVIEW_NOT_FOUND: { code: 'QIYAS.OVERVIEW_NOT_FOUND', httpStatus: 404, messageEn: 'Overview not found', messageAr: 'Overview غير موجود' },
  OVERVIEW_ALREADY_EXISTS: { code: 'QIYAS.OVERVIEW_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overview already exists', messageAr: 'Overview موجود بالفعل' },
  OVERVIEW_VALIDATION_FAILED: { code: 'QIYAS.OVERVIEW_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overview validation failed', messageAr: 'فشل التحقق من Overview' },
  OBJECTIVES_NOT_FOUND: { code: 'QIYAS.OBJECTIVES_NOT_FOUND', httpStatus: 404, messageEn: 'Objectives not found', messageAr: 'Objectives غير موجود' },
  OBJECTIVES_ALREADY_EXISTS: { code: 'QIYAS.OBJECTIVES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Objectives already exists', messageAr: 'Objectives موجود بالفعل' },
  OBJECTIVES_VALIDATION_FAILED: { code: 'QIYAS.OBJECTIVES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Objectives validation failed', messageAr: 'فشل التحقق من Objectives' },
  THEMES_NOT_FOUND: { code: 'QIYAS.THEMES_NOT_FOUND', httpStatus: 404, messageEn: 'Themes not found', messageAr: 'Themes غير موجود' },
  THEMES_ALREADY_EXISTS: { code: 'QIYAS.THEMES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Themes already exists', messageAr: 'Themes موجود بالفعل' },
  THEMES_VALIDATION_FAILED: { code: 'QIYAS.THEMES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Themes validation failed', messageAr: 'فشل التحقق من Themes' },
  PRIORITIES_NOT_FOUND: { code: 'QIYAS.PRIORITIES_NOT_FOUND', httpStatus: 404, messageEn: 'Priorities not found', messageAr: 'Priorities غير موجود' },
  PRIORITIES_ALREADY_EXISTS: { code: 'QIYAS.PRIORITIES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Priorities already exists', messageAr: 'Priorities موجود بالفعل' },
  PRIORITIES_VALIDATION_FAILED: { code: 'QIYAS.PRIORITIES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Priorities validation failed', messageAr: 'فشل التحقق من Priorities' },
  RISK_APPETITE_NOT_FOUND: { code: 'QIYAS.RISK_APPETITE_NOT_FOUND', httpStatus: 404, messageEn: 'Risk Appetite not found', messageAr: 'Risk Appetite غير موجود' },
  RISK_APPETITE_ALREADY_EXISTS: { code: 'QIYAS.RISK_APPETITE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Risk Appetite already exists', messageAr: 'Risk Appetite موجود بالفعل' },
  RISK_APPETITE_VALIDATION_FAILED: { code: 'QIYAS.RISK_APPETITE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Risk Appetite validation failed', messageAr: 'فشل التحقق من Risk Appetite' },
  METRICS_NOT_FOUND: { code: 'QIYAS.METRICS_NOT_FOUND', httpStatus: 404, messageEn: 'Metrics not found', messageAr: 'Metrics غير موجود' },
  METRICS_ALREADY_EXISTS: { code: 'QIYAS.METRICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Metrics already exists', messageAr: 'Metrics موجود بالفعل' },
  METRICS_VALIDATION_FAILED: { code: 'QIYAS.METRICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Metrics validation failed', messageAr: 'فشل التحقق من Metrics' },

  UNAUTHORIZED: { code: 'QIYAS.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for qiyas operation', messageAr: 'صلاحيات غير كافية لعملية qiyas' },
  INVALID_STATE_TRANSITION: { code: 'QIYAS.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'QIYAS.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'QIYAS.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'QIYAS.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'QIYAS.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type QiyasErrorCode = keyof typeof QIYAS_ERROR_CODES;
