/**
 * reporting — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition } from './ports/lifecycle.port';

const REPORTING_DEFINITIONS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const REPORTING_DEFINITIONS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'reporting',
  'reporting_definitions',
  REPORTING_DEFINITIONS_STATES,
  REPORTING_DEFINITIONS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const REPORTING_TEMPLATES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const REPORTING_TEMPLATES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'reporting',
  'reporting_templates',
  REPORTING_TEMPLATES_STATES,
  REPORTING_TEMPLATES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const REPORTING_SCHEDULES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const REPORTING_SCHEDULES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'reporting',
  'reporting_schedules',
  REPORTING_SCHEDULES_STATES,
  REPORTING_SCHEDULES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const REPORTING_SNAPSHOTS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const REPORTING_SNAPSHOTS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'reporting',
  'reporting_snapshots',
  REPORTING_SNAPSHOTS_STATES,
  REPORTING_SNAPSHOTS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);
