// ============================================
// DAuth — Canonical Permission Definitions
// Data-driven security (Law 3). Owner: DAuth
// ============================================

// ── Types ──────────────────────────────────────────────────────────

export interface PermDef {
  code: string;
  name: string;
  module: string;
  resource: string;
  action: string;
}

// ── Canonical permission definitions ───────────────────────────────

export const CANONICAL_PERMISSIONS: PermDef[] = [
  // Platform
  { code: 'platform.tenant.create', name: 'Create Tenant', module: 'platform', resource: 'tenant', action: 'create' },
  { code: 'platform.tenant.read', name: 'Read Tenant', module: 'platform', resource: 'tenant', action: 'read' },
  { code: 'platform.tenant.update', name: 'Update Tenant', module: 'platform', resource: 'tenant', action: 'update' },
  { code: 'platform.tenant.delete', name: 'Delete Tenant', module: 'platform', resource: 'tenant', action: 'delete' },
  { code: 'platform.user.create', name: 'Create User', module: 'platform', resource: 'user', action: 'create' },
  { code: 'platform.user.read', name: 'Read User', module: 'platform', resource: 'user', action: 'read' },
  { code: 'platform.user.update', name: 'Update User', module: 'platform', resource: 'user', action: 'update' },
  { code: 'platform.user.delete', name: 'Delete User', module: 'platform', resource: 'user', action: 'delete' },
  { code: 'platform.role.manage', name: 'Manage Roles', module: 'platform', resource: 'role', action: 'manage' },
  { code: 'platform.permission.manage', name: 'Manage Permissions', module: 'platform', resource: 'permission', action: 'manage' },
  { code: 'platform.settings.read', name: 'Read Settings', module: 'platform', resource: 'settings', action: 'read' },
  { code: 'platform.settings.update', name: 'Update Settings', module: 'platform', resource: 'settings', action: 'update' },
  { code: 'platform.audit.read', name: 'Read Audit Log', module: 'platform', resource: 'audit', action: 'read' },
  { code: 'platform.module.enable', name: 'Enable Module', module: 'platform', resource: 'module', action: 'enable' },
  { code: 'platform.module.disable', name: 'Disable Module', module: 'platform', resource: 'module', action: 'disable' },
  // Delegation / Auth
  { code: 'dauth.delegation.create', name: 'Create Delegation', module: 'dauth', resource: 'delegation', action: 'create' },
  { code: 'dauth.delegation.revoke', name: 'Revoke Delegation', module: 'dauth', resource: 'delegation', action: 'revoke' },
  { code: 'dauth.sod.manage', name: 'Manage SoD Rules', module: 'dauth', resource: 'sod', action: 'manage' },
  { code: 'dauth.access_profile.manage', name: 'Manage Access Profiles', module: 'dauth', resource: 'access_profile', action: 'manage' },
  // Compliance
  { code: 'compliance.control.read', name: 'Read Controls', module: 'compliance', resource: 'control', action: 'read' },
  { code: 'compliance.control.manage', name: 'Manage Controls', module: 'compliance', resource: 'control', action: 'manage' },
  { code: 'compliance.evidence.submit', name: 'Submit Evidence', module: 'compliance', resource: 'evidence', action: 'submit' },
  { code: 'compliance.evidence.review', name: 'Review Evidence', module: 'compliance', resource: 'evidence', action: 'review' },
  { code: 'compliance.attestation.create', name: 'Create Attestation', module: 'compliance', resource: 'attestation', action: 'create' },
  // Risk (sub-resource actions kept; register.* deprecated — use risk.record.* / risk.manage)
  { code: 'risk.register.read', name: 'Read Risk Register (deprecated: use risk.record.read)', module: 'risk', resource: 'register', action: 'read' },
  { code: 'risk.register.manage', name: 'Manage Risk Register (deprecated: use risk.manage)', module: 'risk', resource: 'register', action: 'manage' },
  { code: 'risk.assessment.create', name: 'Create Assessment', module: 'risk', resource: 'assessment', action: 'create' },
  { code: 'risk.assessment.approve', name: 'Approve Assessment', module: 'risk', resource: 'assessment', action: 'approve' },
  // Audit (sub-resource actions kept; plan.* deprecated — use audit.record.*)
  { code: 'audit.plan.read', name: 'Read Audit Plans (deprecated: use audit.record.read)', module: 'audit', resource: 'plan', action: 'read' },
  { code: 'audit.plan.manage', name: 'Manage Audit Plans (deprecated: use audit.record.manage)', module: 'audit', resource: 'plan', action: 'manage' },
  { code: 'audit.finding.create', name: 'Create Finding', module: 'audit', resource: 'finding', action: 'create' },
  { code: 'audit.finding.resolve', name: 'Resolve Finding', module: 'audit', resource: 'finding', action: 'resolve' },
  // Policy
  { code: 'policy.document.read', name: 'Read Policies', module: 'policy', resource: 'document', action: 'read' },
  { code: 'policy.document.manage', name: 'Manage Policies', module: 'policy', resource: 'document', action: 'manage' },
  { code: 'policy.document.publish', name: 'Publish Policy', module: 'policy', resource: 'document', action: 'publish' },
  // Incident (ticket.* deprecated — use incident.record.* / incident.manage; resolve kept as sub-resource action)
  { code: 'incident.ticket.read', name: 'Read Incidents (deprecated: use incident.record.read)', module: 'incident', resource: 'ticket', action: 'read' },
  { code: 'incident.ticket.manage', name: 'Manage Incidents (deprecated: use incident.manage)', module: 'incident', resource: 'ticket', action: 'manage' },
  { code: 'incident.ticket.resolve', name: 'Resolve Incident', module: 'incident', resource: 'ticket', action: 'resolve' },
  // Vendor (profile.* deprecated — use vendor.record.* / vendor.manage; assessment.create kept as sub-resource action)
  { code: 'vendor.profile.read', name: 'Read Vendors (deprecated: use vendor.record.read)', module: 'vendor', resource: 'profile', action: 'read' },
  { code: 'vendor.profile.manage', name: 'Manage Vendors (deprecated: use vendor.manage)', module: 'vendor', resource: 'profile', action: 'manage' },
  { code: 'vendor.assessment.create', name: 'Create Vendor Assessment', module: 'vendor', resource: 'assessment', action: 'create' },
  // Workflow
  { code: 'workflow.definition.read', name: 'Read Workflows', module: 'workflow', resource: 'definition', action: 'read' },
  { code: 'workflow.definition.manage', name: 'Manage Workflows', module: 'workflow', resource: 'definition', action: 'manage' },
  { code: 'workflow.instance.approve', name: 'Approve Workflow Step', module: 'workflow', resource: 'instance', action: 'approve' },
  // Onboarding
  { code: 'onboarding.record.read', name: 'Read Onboarding Records', module: 'onboarding', resource: 'record', action: 'read' },
  { code: 'onboarding.record.write', name: 'Create/Edit Onboarding Records', module: 'onboarding', resource: 'record', action: 'write' },
  { code: 'onboarding.record.delete', name: 'Delete Onboarding Records', module: 'onboarding', resource: 'record', action: 'delete' },
  { code: 'onboarding.record.approve', name: 'Approve Onboarding Records', module: 'onboarding', resource: 'record', action: 'approve' },
  { code: 'onboarding.manage', name: 'Manage Onboarding Settings', module: 'onboarding', resource: 'module', action: 'manage' },
  { code: 'onboarding.record.export', name: 'Export Onboarding Data', module: 'onboarding', resource: 'record', action: 'export' },
  { code: 'onboarding.approve', name: 'Approve Onboarding Session', module: 'onboarding', resource: 'record', action: 'approve' },
  { code: 'onboarding.provision', name: 'Provision Workspace', module: 'onboarding', resource: 'record', action: 'manage' },
  { code: 'onboarding.retry_provisioning', name: 'Retry Provisioning Job', module: 'onboarding', resource: 'record', action: 'manage' },
  { code: 'onboarding.journey.create', name: 'Create Onboarding Journey', module: 'onboarding', resource: 'record', action: 'write' },
  { code: 'onboarding.journey.read', name: 'Read Onboarding Journey', module: 'onboarding', resource: 'record', action: 'read' },
  { code: 'onboarding.journey.update', name: 'Update Onboarding Journey', module: 'onboarding', resource: 'record', action: 'write' },
  { code: 'onboarding.config.update', name: 'Update Onboarding Config', module: 'onboarding', resource: 'module', action: 'manage' },
  // Reporting / Dashboard
  { code: 'reporting.dashboard.read', name: 'Read Dashboards', module: 'reporting', resource: 'dashboard', action: 'read' },
  { code: 'reporting.report.generate', name: 'Generate Reports', module: 'reporting', resource: 'report', action: 'generate' },
  // Workspace (frontend route-level permissions — aligned with init-master-db canonical codes)
  { code: 'workspace.config.read', name: 'Read Workspace Config', module: 'workspace', resource: 'config', action: 'read' },
  { code: 'workspace.config.write', name: 'Write Workspace Config', module: 'workspace', resource: 'config', action: 'write' },
  { code: 'profile.record.read', name: 'Read Profile', module: 'profile', resource: 'record', action: 'read' },
  { code: 'admin.system.read', name: 'Read Admin System', module: 'admin', resource: 'system', action: 'read' },
  { code: 'admin.system.write', name: 'Write Admin System', module: 'admin', resource: 'system', action: 'write' },
  { code: 'users.account.manage', name: 'Manage User Accounts', module: 'users', resource: 'account', action: 'manage' },
  { code: 'platform.system.admin', name: 'Platform System Admin', module: 'platform', resource: 'system', action: 'admin' },
  { code: 'platform.agent.read', name: 'Read Platform Agents', module: 'platform', resource: 'agent', action: 'read' },
  // Module route-level permissions (frontend component-registry canonical codes)
  { code: 'analytics.report.read', name: 'Read Analytics Reports', module: 'analytics', resource: 'report', action: 'read' },
  { code: 'analytics.report.write', name: 'Write Analytics Reports', module: 'analytics', resource: 'report', action: 'write' },
  { code: 'control.record.read', name: 'Read Control Records', module: 'control', resource: 'record', action: 'read' },
  { code: 'control.record.write', name: 'Write Control Records', module: 'control', resource: 'record', action: 'write' },
  { code: 'assessment.record.read', name: 'Read Assessments', module: 'assessment', resource: 'record', action: 'read' },
  { code: 'assessment.record.manage', name: 'Manage Assessments', module: 'assessment', resource: 'record', action: 'manage' },
  { code: 'framework.record.read', name: 'Read Frameworks', module: 'framework', resource: 'record', action: 'read' },
  { code: 'framework.record.manage', name: 'Manage Frameworks', module: 'framework', resource: 'record', action: 'manage' },
  { code: 'risk.record.read', name: 'Read Risk Records', module: 'risk', resource: 'record', action: 'read' },
  { code: 'risk.record.write', name: 'Write Risk Records', module: 'risk', resource: 'record', action: 'write' },
  { code: 'audit.record.read', name: 'Read Audit Records', module: 'audit', resource: 'record', action: 'read' },
  { code: 'audit.record.manage', name: 'Manage Audit Records', module: 'audit', resource: 'record', action: 'manage' },
  { code: 'evidence.item.read', name: 'Read Evidence Items', module: 'evidence', resource: 'item', action: 'read' },
  { code: 'evidence.item.write', name: 'Write Evidence Items', module: 'evidence', resource: 'item', action: 'write' },
  { code: 'compliance.program.read', name: 'Read Compliance Programs', module: 'compliance', resource: 'program', action: 'read' },
  { code: 'incident.record.read', name: 'Read Incident Records', module: 'incident', resource: 'record', action: 'read' },
  { code: 'incident.record.write', name: 'Write Incident Records', module: 'incident', resource: 'record', action: 'write' },
  { code: 'vendor.record.read', name: 'Read Vendor Records', module: 'vendor', resource: 'record', action: 'read' },
  { code: 'vendor.record.write', name: 'Write Vendor Records', module: 'vendor', resource: 'record', action: 'write' },
  { code: 'privacy.record.read', name: 'Read Privacy Records', module: 'privacy', resource: 'record', action: 'read' },
  { code: 'copilot.assistant.read', name: 'Read AI Copilot', module: 'copilot', resource: 'assistant', action: 'read' },
  { code: 'ai.agent.read', name: 'Read AI Agents', module: 'ai', resource: 'agent', action: 'read' },
  { code: 'ai.agent.manage', name: 'Manage AI Agents', module: 'ai', resource: 'agent', action: 'manage' },
  { code: 'knowledge.base.read', name: 'Read Knowledge Base', module: 'knowledge', resource: 'base', action: 'read' },
  { code: 'integrations.connector.read', name: 'Read Integrations', module: 'integrations', resource: 'connector', action: 'read' },
  { code: 'integrations.connector.write', name: 'Write Integrations', module: 'integrations', resource: 'connector', action: 'write' },
  { code: 'report.document.read', name: 'Read Report Documents', module: 'report', resource: 'document', action: 'read' },
  { code: 'report.document.write', name: 'Write Report Documents', module: 'report', resource: 'document', action: 'write' },
  { code: 'timeline.event.read', name: 'Read Timeline Events', module: 'timeline', resource: 'event', action: 'read' },
  { code: 'task.item.read', name: 'Read Tasks', module: 'task', resource: 'item', action: 'read' },
  { code: 'action.item.read', name: 'Read Action Items', module: 'action', resource: 'item', action: 'read' },
  { code: 'exception.record.read', name: 'Read Exceptions', module: 'exception', resource: 'record', action: 'read' },
  { code: 'remediation.task.read', name: 'Read Remediation Tasks', module: 'remediation', resource: 'task', action: 'read' },
  { code: 'messaging.channel.read', name: 'Read Messaging Channels', module: 'messaging', resource: 'channel', action: 'read' },
  { code: 'workflow.instance.read', name: 'Read Workflow Instances', module: 'workflow', resource: 'instance', action: 'read' },
  { code: 'workflow.instance.write', name: 'Write Workflow Instances', module: 'workflow', resource: 'instance', action: 'write' },
  { code: 'governance.record.read', name: 'Read Governance Records', module: 'governance', resource: 'record', action: 'read' },
  { code: 'governance.record.manage', name: 'Manage Governance Records', module: 'governance', resource: 'record', action: 'manage' },
  { code: 'foundation.org.read', name: 'Read Foundation Org Structure', module: 'foundation', resource: 'org', action: 'read' },
  { code: 'foundation.org.manage', name: 'Manage Foundation Org Structure', module: 'foundation', resource: 'org', action: 'manage' },
  { code: 'asset.record.read', name: 'Read Asset Records', module: 'asset', resource: 'record', action: 'read' },
  { code: 'asset.record.manage', name: 'Manage Asset Records', module: 'asset', resource: 'record', action: 'manage' },
  { code: 'position.record.read', name: 'Read Position Records', module: 'position', resource: 'record', action: 'read' },
  { code: 'team.member.read', name: 'Read Team Members', module: 'team', resource: 'member', action: 'read' },
  { code: 'team.member.manage', name: 'Manage Team Members', module: 'team', resource: 'member', action: 'manage' },
  { code: 'ai.governance.read', name: 'Read AI Governance', module: 'ai', resource: 'governance', action: 'read' },
  { code: 'training.record.read', name: 'Read Training Records', module: 'training', resource: 'record', action: 'read' },
  { code: 'training.record.manage', name: 'Manage Training Records', module: 'training', resource: 'record', action: 'manage' },
  { code: 'bcp.plan.read', name: 'Read BCP Plans', module: 'bcp', resource: 'plan', action: 'read' },
  { code: 'bcp.plan.manage', name: 'Manage BCP Plans', module: 'bcp', resource: 'plan', action: 'manage' },
  // Backend API route permissions (full cross-module audit)
  // Foundation (backend routes use foundation.record.* family)
  { code: 'foundation.record.read', name: 'Read Foundation Records', module: 'foundation', resource: 'record', action: 'read' },
  { code: 'foundation.record.write', name: 'Write Foundation Records', module: 'foundation', resource: 'record', action: 'write' },
  { code: 'foundation.record.approve', name: 'Approve Foundation Records', module: 'foundation', resource: 'record', action: 'approve' },
  { code: 'foundation.record.delete', name: 'Delete Foundation Records', module: 'foundation', resource: 'record', action: 'delete' },
  { code: 'foundation.manage', name: 'Manage Foundation Module', module: 'foundation', resource: 'module', action: 'manage' },
  // Policy (write/configure/delete)
  { code: 'policy.document.write', name: 'Write Policies', module: 'policy', resource: 'document', action: 'write' },
  { code: 'policy.document.configure', name: 'Configure Policies', module: 'policy', resource: 'document', action: 'configure' },
  { code: 'policy.document.delete', name: 'Delete Policies', module: 'policy', resource: 'document', action: 'delete' },
  { code: 'policy.record.read', name: 'Read Policy Records', module: 'policy', resource: 'record', action: 'read' },
  { code: 'policy.record.approve', name: 'Approve Policy Records', module: 'policy', resource: 'record', action: 'approve' },
  // Risk (configure/delete)
  { code: 'risk.record.configure', name: 'Configure Risk Records', module: 'risk', resource: 'record', action: 'configure' },
  { code: 'risk.record.delete', name: 'Delete Risk Records', module: 'risk', resource: 'record', action: 'delete' },
  // Incident (configure)
  { code: 'incident.record.configure', name: 'Configure Incident Records', module: 'incident', resource: 'record', action: 'configure' },
  // Compliance (approve/write/delete)
  { code: 'compliance.control.approve', name: 'Approve Controls', module: 'compliance', resource: 'control', action: 'approve' },
  { code: 'compliance.program.manage', name: 'Manage Compliance Programs', module: 'compliance', resource: 'program', action: 'manage' },
  { code: 'compliance.program.write', name: 'Write Compliance Programs', module: 'compliance', resource: 'program', action: 'write' },
  { code: 'compliance.record.read', name: 'Read Compliance Records', module: 'compliance', resource: 'record', action: 'read' },
  // Workflow (record/approval/task)
  { code: 'workflow.record.read', name: 'Read Workflow Records', module: 'workflow', resource: 'record', action: 'read' },
  { code: 'workflow.approval.read', name: 'Read Workflow Approvals', module: 'workflow', resource: 'approval', action: 'read' },
  { code: 'workflow.task.read', name: 'Read Workflow Tasks', module: 'workflow', resource: 'task', action: 'read' },
  // Admin (configure/manage/field-rbac/security-config/record)
  { code: 'admin.system.configure', name: 'Configure Admin System', module: 'admin', resource: 'system', action: 'configure' },
  { code: 'admin.system.manage', name: 'Manage Admin System', module: 'admin', resource: 'system', action: 'manage' },
  { code: 'admin.record.read', name: 'Read Admin Records', module: 'admin', resource: 'record', action: 'read' },
  { code: 'admin.field-rbac.read', name: 'Read Field RBAC', module: 'admin', resource: 'field-rbac', action: 'read' },
  { code: 'admin.field-rbac.write', name: 'Write Field RBAC', module: 'admin', resource: 'field-rbac', action: 'write' },
  { code: 'admin.security-config.read', name: 'Read Security Config', module: 'admin', resource: 'security-config', action: 'read' },
  { code: 'admin.security-config.write', name: 'Write Security Config', module: 'admin', resource: 'security-config', action: 'write' },
  // BCP (write/configure/record)
  { code: 'bcp.plan.write', name: 'Write BCP Plans', module: 'bcp', resource: 'plan', action: 'write' },
  { code: 'bcp.plan.configure', name: 'Configure BCP Plans', module: 'bcp', resource: 'plan', action: 'configure' },
  { code: 'bcp.record.read', name: 'Read BCP Records', module: 'bcp', resource: 'record', action: 'read' },
  // Training (write/configure)
  { code: 'training.record.write', name: 'Write Training Records', module: 'training', resource: 'record', action: 'write' },
  { code: 'training.record.configure', name: 'Configure Training Records', module: 'training', resource: 'record', action: 'configure' },
  // Vendor (configure/manage)
  { code: 'vendor.record.configure', name: 'Configure Vendor Records', module: 'vendor', resource: 'record', action: 'configure' },
  { code: 'vendor.record.manage', name: 'Manage Vendor Records', module: 'vendor', resource: 'record', action: 'manage' },
  // Analytics (record/configure)
  { code: 'analytics.record.read', name: 'Read Analytics Records', module: 'analytics', resource: 'record', action: 'read' },
  { code: 'analytics.report.configure', name: 'Configure Analytics Reports', module: 'analytics', resource: 'report', action: 'configure' },
  // Asset (write)
  { code: 'asset.record.write', name: 'Write Asset Records', module: 'asset', resource: 'record', action: 'write' },
  // Evidence (record)
  { code: 'evidence.record.read', name: 'Read Evidence Records', module: 'evidence', resource: 'record', action: 'read' },
  // Privacy (write/approve/configure/delete)
  { code: 'privacy.record.write', name: 'Write Privacy Records', module: 'privacy', resource: 'record', action: 'write' },
  { code: 'privacy.record.approve', name: 'Approve Privacy Records', module: 'privacy', resource: 'record', action: 'approve' },
  { code: 'privacy.record.configure', name: 'Configure Privacy Records', module: 'privacy', resource: 'record', action: 'configure' },
  { code: 'privacy.record.delete', name: 'Delete Privacy Records', module: 'privacy', resource: 'record', action: 'delete' },
  // Exception (configure)
  { code: 'exception.record.configure', name: 'Configure Exceptions', module: 'exception', resource: 'record', action: 'configure' },
  // Remediation (record/configure/execute)
  { code: 'remediation.record.read', name: 'Read Remediation Records', module: 'remediation', resource: 'record', action: 'read' },
  { code: 'remediation.task.configure', name: 'Configure Remediation Tasks', module: 'remediation', resource: 'task', action: 'configure' },
  { code: 'remediation.task.execute', name: 'Execute Remediation Tasks', module: 'remediation', resource: 'task', action: 'execute' },
  // Controls (record)
  { code: 'controls.record.read', name: 'Read Controls Records', module: 'controls', resource: 'record', action: 'read' },
  // Reporting (record)
  { code: 'reporting.record.read', name: 'Read Reporting Records', module: 'reporting', resource: 'record', action: 'read' },
  // Governance (write)
  { code: 'governance.record.write', name: 'Write Governance Records', module: 'governance', resource: 'record', action: 'write' },
  // Team (record/manage)
  { code: 'team.record.read', name: 'Read Team Records', module: 'team', resource: 'record', action: 'read' },
  { code: 'team.record.write', name: 'Write Team Records', module: 'team', resource: 'record', action: 'write' },
  { code: 'team.record.approve', name: 'Approve Team Records', module: 'team', resource: 'record', action: 'approve' },
  { code: 'team.record.delete', name: 'Delete Team Records', module: 'team', resource: 'record', action: 'delete' },
  { code: 'team.manage', name: 'Manage Teams', module: 'team', resource: 'module', action: 'manage' },
  // Action (record/configure)
  { code: 'action.record.read', name: 'Read Action Records', module: 'action', resource: 'record', action: 'read' },
  { code: 'action.item.configure', name: 'Configure Action Items', module: 'action', resource: 'item', action: 'configure' },
  // AI / AI-Governance
  { code: 'ai.record.read', name: 'Read AI Records', module: 'ai', resource: 'record', action: 'read' },
  { code: 'ai-governance.record.read', name: 'Read AI Governance Records', module: 'ai', resource: 'governance-record', action: 'read' },
  // Notification (config/record)
  { code: 'notification.config.read', name: 'Read Notification Config', module: 'notification', resource: 'config', action: 'read' },
  { code: 'notification.config.write', name: 'Write Notification Config', module: 'notification', resource: 'config', action: 'write' },
  { code: 'notification.config.configure', name: 'Configure Notifications', module: 'notification', resource: 'config', action: 'configure' },
  { code: 'notification.record.read', name: 'Read Notification Records', module: 'notification', resource: 'record', action: 'read' },
  // Integrations (configure/delete/record)
  { code: 'integrations.connector.configure', name: 'Configure Integrations', module: 'integrations', resource: 'connector', action: 'configure' },
  { code: 'integrations.connector.delete', name: 'Delete Integrations', module: 'integrations', resource: 'connector', action: 'delete' },
  { code: 'integrations.record.read', name: 'Read Integrations Records', module: 'integrations', resource: 'record', action: 'read' },
  // Platform (subscription/workspace)
  { code: 'platform.subscription.read', name: 'Read Platform Subscription', module: 'platform', resource: 'subscription', action: 'read' },
  { code: 'platform.subscription.manage', name: 'Manage Platform Subscription', module: 'platform', resource: 'subscription', action: 'manage' },
  { code: 'platform.workspace.read', name: 'Read Platform Workspace', module: 'platform', resource: 'workspace', action: 'read' },
  { code: 'platform.workspace.manage', name: 'Manage Platform Workspace', module: 'platform', resource: 'workspace', action: 'manage' },
  // Tenant (config)
  { code: 'tenant.config.read', name: 'Read Tenant Config', module: 'platform', resource: 'tenant-config', action: 'read' },
  { code: 'tenant.config.write', name: 'Write Tenant Config', module: 'platform', resource: 'tenant-config', action: 'write' },
  { code: 'tenant.config.manage', name: 'Manage Tenant Config', module: 'platform', resource: 'tenant-config', action: 'manage' },
  // Onboarding (admin)
  { code: 'onboarding.admin', name: 'Onboarding Admin', module: 'onboarding', resource: 'module', action: 'admin' },
  // Dashboard
  { code: 'dashboard.record.read', name: 'Read Dashboard Records', module: 'analytics', resource: 'dashboard-record', action: 'read' },
  { code: 'dashboard.record.write', name: 'Write Dashboard Records', module: 'analytics', resource: 'dashboard-record', action: 'write' },
  { code: 'dashboard.record.approve', name: 'Approve Dashboard Records', module: 'analytics', resource: 'dashboard-record', action: 'approve' },
  { code: 'dashboard.record.delete', name: 'Delete Dashboard Records', module: 'analytics', resource: 'dashboard-record', action: 'delete' },
  { code: 'dashboard.manage', name: 'Manage Dashboards', module: 'analytics', resource: 'dashboard', action: 'manage' },
  // Navigation
  { code: 'navigation.record.read', name: 'Read Navigation Records', module: 'admin', resource: 'navigation', action: 'read' },
  { code: 'navigation.record.write', name: 'Write Navigation Records', module: 'admin', resource: 'navigation', action: 'write' },
  { code: 'navigation.record.approve', name: 'Approve Navigation Records', module: 'admin', resource: 'navigation', action: 'approve' },
  { code: 'navigation.record.delete', name: 'Delete Navigation Records', module: 'admin', resource: 'navigation', action: 'delete' },
  { code: 'navigation.manage', name: 'Manage Navigation', module: 'admin', resource: 'navigation', action: 'manage' },
  // Widgets
  { code: 'widgets.record.read', name: 'Read Widget Records', module: 'analytics', resource: 'widget', action: 'read' },
  { code: 'widgets.record.write', name: 'Write Widget Records', module: 'analytics', resource: 'widget', action: 'write' },
  { code: 'widgets.record.approve', name: 'Approve Widget Records', module: 'analytics', resource: 'widget', action: 'approve' },
  { code: 'widgets.record.delete', name: 'Delete Widget Records', module: 'analytics', resource: 'widget', action: 'delete' },
  { code: 'widgets.manage', name: 'Manage Widgets', module: 'analytics', resource: 'widget', action: 'manage' },
  // Inbox
  { code: 'inbox.item.read', name: 'Read Inbox Items', module: 'notification', resource: 'inbox', action: 'read' },
  { code: 'inbox.item.write', name: 'Write Inbox Items', module: 'notification', resource: 'inbox', action: 'write' },
  { code: 'inbox.item.delete', name: 'Delete Inbox Items', module: 'notification', resource: 'inbox', action: 'delete' },
  { code: 'inbox.item.bulk', name: 'Bulk Inbox Actions', module: 'notification', resource: 'inbox', action: 'bulk' },
  { code: 'inbox.item.configure', name: 'Configure Inbox', module: 'notification', resource: 'inbox', action: 'configure' },
  { code: 'inbox.record.read', name: 'Read Inbox Records', module: 'notification', resource: 'inbox-record', action: 'read' },
  // Portals
  { code: 'portals.record.read', name: 'Read Portal Records', module: 'platform', resource: 'portal', action: 'read' },
  { code: 'portals.record.write', name: 'Write Portal Records', module: 'platform', resource: 'portal', action: 'write' },
  { code: 'portals.record.approve', name: 'Approve Portal Records', module: 'platform', resource: 'portal', action: 'approve' },
  { code: 'portals.record.delete', name: 'Delete Portal Records', module: 'platform', resource: 'portal', action: 'delete' },
  { code: 'portals.record.bulk', name: 'Bulk Portal Actions', module: 'platform', resource: 'portal', action: 'bulk' },
  { code: 'portals.record.configure', name: 'Configure Portals', module: 'platform', resource: 'portal', action: 'configure' },
  // Records (generic)
  { code: 'records.record.read', name: 'Read Records', module: 'platform', resource: 'records', action: 'read' },
  { code: 'records.record.write', name: 'Write Records', module: 'platform', resource: 'records', action: 'write' },
  { code: 'records.record.approve', name: 'Approve Records', module: 'platform', resource: 'records', action: 'approve' },
  { code: 'records.record.delete', name: 'Delete Records', module: 'platform', resource: 'records', action: 'delete' },
  { code: 'records.record.bulk', name: 'Bulk Record Actions', module: 'platform', resource: 'records', action: 'bulk' },
  { code: 'records.record.configure', name: 'Configure Records', module: 'platform', resource: 'records', action: 'configure' },
  // Issues
  { code: 'issues.record.read', name: 'Read Issues', module: 'governance', resource: 'issue', action: 'read' },
  { code: 'issues.record.write', name: 'Write Issues', module: 'governance', resource: 'issue', action: 'write' },
  { code: 'issues.record.approve', name: 'Approve Issues', module: 'governance', resource: 'issue', action: 'approve' },
  { code: 'issues.record.delete', name: 'Delete Issues', module: 'governance', resource: 'issue', action: 'delete' },
  { code: 'issues.record.bulk', name: 'Bulk Issue Actions', module: 'governance', resource: 'issue', action: 'bulk' },
  { code: 'issues.record.configure', name: 'Configure Issues', module: 'governance', resource: 'issue', action: 'configure' },
  // Bootstrap/Provisioning
  { code: 'bootstrap.record.read', name: 'Read Bootstrap Records', module: 'platform', resource: 'bootstrap', action: 'read' },
  { code: 'bootstrap.record.write', name: 'Write Bootstrap Records', module: 'platform', resource: 'bootstrap', action: 'write' },
  { code: 'bootstrap.manage', name: 'Manage Bootstrap', module: 'platform', resource: 'bootstrap', action: 'manage' },
  { code: 'provisioning.record.read', name: 'Read Provisioning Records', module: 'platform', resource: 'provisioning', action: 'read' },
  { code: 'provisioning.record.write', name: 'Write Provisioning Records', module: 'platform', resource: 'provisioning', action: 'write' },
  { code: 'provisioning.record.approve', name: 'Approve Provisioning', module: 'platform', resource: 'provisioning', action: 'approve' },
  { code: 'provisioning.manage', name: 'Manage Provisioning', module: 'platform', resource: 'provisioning', action: 'manage' },
  // Journey (onboarding)
  { code: 'journey.record.read', name: 'Read Journey Records', module: 'onboarding', resource: 'journey', action: 'read' },
  { code: 'journey.record.write', name: 'Write Journey Records', module: 'onboarding', resource: 'journey', action: 'write' },
  { code: 'journey.record.delete', name: 'Delete Journey Records', module: 'onboarding', resource: 'journey', action: 'delete' },
  // Packs
  { code: 'packs.record.read', name: 'Read Pack Records', module: 'admin', resource: 'pack', action: 'read' },
  { code: 'packs.pack.manage', name: 'Manage Packs', module: 'admin', resource: 'pack', action: 'manage' },
  { code: 'packs.policy.read', name: 'Read Pack Policies', module: 'admin', resource: 'pack-policy', action: 'read' },
  { code: 'packs.policy.manage', name: 'Manage Pack Policies', module: 'admin', resource: 'pack-policy', action: 'manage' },
  { code: 'packs.manage', name: 'Manage Packs Module', module: 'admin', resource: 'pack-module', action: 'manage' },
  // DORA
  { code: 'dora.record.read', name: 'Read DORA Records', module: 'compliance', resource: 'dora', action: 'read' },
  { code: 'dora.record.write', name: 'Write DORA Records', module: 'compliance', resource: 'dora', action: 'write' },
  { code: 'dora.record.delete', name: 'Delete DORA Records', module: 'compliance', resource: 'dora', action: 'delete' },
  // Qiyas
  { code: 'qiyas.record.read', name: 'Read Qiyas Records', module: 'compliance', resource: 'qiyas', action: 'read' },
  { code: 'qiyas.assessment.read', name: 'Read Qiyas Assessments', module: 'compliance', resource: 'qiyas-assessment', action: 'read' },
  { code: 'qiyas.assessment.configure', name: 'Configure Qiyas', module: 'compliance', resource: 'qiyas-assessment', action: 'configure' },
  // Governance AI
  { code: 'governance_ai.record.read', name: 'Read Governance AI Records', module: 'ai', resource: 'gov-ai-record', action: 'read' },
  { code: 'governance_ai.record.write', name: 'Write Governance AI Records', module: 'ai', resource: 'gov-ai-record', action: 'write' },
  { code: 'governance_ai.manage', name: 'Manage Governance AI', module: 'ai', resource: 'gov-ai', action: 'manage' },
  { code: 'governance_ai.recommendation.read', name: 'Read AI Recommendations', module: 'ai', resource: 'recommendation', action: 'read' },
  { code: 'governance_ai.recommendation.execute', name: 'Execute AI Recommendations', module: 'ai', resource: 'recommendation', action: 'execute' },
  { code: 'governance_ai.recommendation.approve', name: 'Approve AI Recommendations', module: 'ai', resource: 'recommendation', action: 'approve' },
  { code: 'governance_ai.pipeline.read', name: 'Read AI Pipeline', module: 'ai', resource: 'pipeline', action: 'read' },
  { code: 'governance_ai.pipeline.execute', name: 'Execute AI Pipeline', module: 'ai', resource: 'pipeline', action: 'execute' },
  { code: 'governance_ai.signal.read', name: 'Read AI Signals', module: 'ai', resource: 'signal', action: 'read' },
  { code: 'governance_ai.signal.execute', name: 'Execute AI Signals', module: 'ai', resource: 'signal', action: 'execute' },
  { code: 'governance_ai.signal.interpret', name: 'Interpret AI Signals', module: 'ai', resource: 'signal', action: 'interpret' },
  { code: 'governance_ai.health.read', name: 'Read AI Health', module: 'ai', resource: 'health', action: 'read' },
  { code: 'governance_ai.health.execute', name: 'Execute AI Health Check', module: 'ai', resource: 'health', action: 'execute' },
  { code: 'governance_ai.escalation.read', name: 'Read AI Escalations', module: 'ai', resource: 'escalation', action: 'read' },
  { code: 'governance_ai.escalation.execute', name: 'Execute AI Escalation', module: 'ai', resource: 'escalation', action: 'execute' },
  { code: 'governance_ai.compliance_score.read', name: 'Read AI Compliance Score', module: 'ai', resource: 'compliance-score', action: 'read' },
  { code: 'governance_ai.compliance_score.execute', name: 'Execute AI Compliance Score', module: 'ai', resource: 'compliance-score', action: 'execute' },
  // Governance OS
  { code: 'governance_os.admin.read', name: 'Read GOS Admin', module: 'governance', resource: 'os-admin', action: 'read' },
  { code: 'governance_os.admin.manage', name: 'Manage GOS Admin', module: 'governance', resource: 'os-admin', action: 'manage' },
  { code: 'governance_os.diagnostics.read', name: 'Read GOS Diagnostics', module: 'governance', resource: 'diagnostics', action: 'read' },
  { code: 'governance_os.framework.read', name: 'Read GOS Frameworks', module: 'governance', resource: 'os-framework', action: 'read' },
  { code: 'governance_os.framework.write', name: 'Write GOS Frameworks', module: 'governance', resource: 'os-framework', action: 'write' },
  { code: 'governance_os.framework.delete', name: 'Delete GOS Frameworks', module: 'governance', resource: 'os-framework', action: 'delete' },
  { code: 'governance_os.initiative.read', name: 'Read GOS Initiatives', module: 'governance', resource: 'initiative', action: 'read' },
  { code: 'governance_os.initiative.write', name: 'Write GOS Initiatives', module: 'governance', resource: 'initiative', action: 'write' },
  { code: 'governance_os.maturity.read', name: 'Read GOS Maturity', module: 'governance', resource: 'maturity', action: 'read' },
  { code: 'governance_os.maturity.write', name: 'Write GOS Maturity', module: 'governance', resource: 'maturity', action: 'write' },
  // KSA Regulatory
  { code: 'ksa_regulatory.intelligence.read', name: 'Read KSA Intelligence', module: 'compliance', resource: 'ksa-intelligence', action: 'read' },
  { code: 'ksa_regulatory.readiness.read', name: 'Read KSA Readiness', module: 'compliance', resource: 'ksa-readiness', action: 'read' },
  { code: 'ksa_regulatory.compliance_score.read', name: 'Read KSA Compliance Score', module: 'compliance', resource: 'ksa-score', action: 'read' },
  { code: 'ksa_regulatory.framework_mapping.read', name: 'Read KSA Framework Mapping', module: 'compliance', resource: 'ksa-mapping', action: 'read' },
  { code: 'ksa_regulatory.sector_maturity.read', name: 'Read KSA Sector Maturity', module: 'compliance', resource: 'ksa-maturity', action: 'read' },
  // Local Knowledge
  { code: 'local_knowledge.document.read', name: 'Read Local Knowledge Docs', module: 'knowledge', resource: 'local-doc', action: 'read' },
  { code: 'local_knowledge.document.create', name: 'Create Local Knowledge Docs', module: 'knowledge', resource: 'local-doc', action: 'create' },
  { code: 'local_knowledge.search.read', name: 'Search Local Knowledge', module: 'knowledge', resource: 'local-search', action: 'read' },
  { code: 'local_knowledge.source.read', name: 'Read Local Knowledge Sources', module: 'knowledge', resource: 'local-source', action: 'read' },
  { code: 'local_knowledge.source.create', name: 'Create Local Knowledge Sources', module: 'knowledge', resource: 'local-source', action: 'create' },
  // Proactive Leadership
  { code: 'proactive_leadership.config.read', name: 'Read PL Config', module: 'governance', resource: 'pl-config', action: 'read' },
  { code: 'proactive_leadership.config.update', name: 'Update PL Config', module: 'governance', resource: 'pl-config', action: 'update' },
  { code: 'proactive_leadership.evaluation.execute', name: 'Execute PL Evaluation', module: 'governance', resource: 'pl-evaluation', action: 'execute' },
  { code: 'proactive_leadership.insight.read', name: 'Read PL Insights', module: 'governance', resource: 'pl-insight', action: 'read' },
  // Route-level permissions — full deep audit (133 codes from route middleware)
  { code: 'action.manage', name: 'Manage Actions Module', module: 'action', resource: 'module', action: 'manage' },
  { code: 'admin.config.manage', name: 'Manage Admin Config', module: 'admin', resource: 'config', action: 'manage' },
  { code: 'admin.content-pack.read', name: 'Read Content Packs', module: 'admin', resource: 'content-pack', action: 'read' },
  { code: 'admin.content-pack.write', name: 'Write Content Packs', module: 'admin', resource: 'content-pack', action: 'write' },
  { code: 'admin.feature-table.write', name: 'Write Feature Tables', module: 'admin', resource: 'feature-table', action: 'write' },
  { code: 'admin.manage', name: 'Manage Admin Module', module: 'admin', resource: 'module', action: 'manage' },
  { code: 'admin.pack.write', name: 'Write Admin Packs', module: 'admin', resource: 'pack', action: 'write' },
  { code: 'admin.payment.write', name: 'Write Payments', module: 'admin', resource: 'payment', action: 'write' },
  { code: 'admin.platform.read', name: 'Read Platform Admin', module: 'admin', resource: 'platform', action: 'read' },
  { code: 'admin.platform.write', name: 'Write Platform Admin', module: 'admin', resource: 'platform', action: 'write' },
  { code: 'admin.system.shell', name: 'Admin System Shell', module: 'admin', resource: 'system', action: 'shell' },
  { code: 'admin.tenant.manage', name: 'Manage Tenant Admin', module: 'admin', resource: 'tenant', action: 'manage' },
  { code: 'agrc_engine.manage', name: 'Manage AGRC Engine', module: 'platform', resource: 'agrc-engine', action: 'manage' },
  { code: 'ai.agent.approve', name: 'Approve AI Agent', module: 'ai', resource: 'agent', action: 'approve' },
  { code: 'ai.agent.configure', name: 'Configure AI Agent', module: 'ai', resource: 'agent', action: 'configure' },
  { code: 'ai.agent.execute', name: 'Execute AI Agent', module: 'ai', resource: 'agent', action: 'execute' },
  { code: 'ai.agent.view', name: 'View AI Agent', module: 'ai', resource: 'agent', action: 'view' },
  { code: 'ai.agent.write', name: 'Write AI Agent', module: 'ai', resource: 'agent', action: 'write' },
  { code: 'ai.copilot.read', name: 'Read AI Copilot', module: 'ai', resource: 'copilot', action: 'read' },
  { code: 'ai.copilot.write', name: 'Write AI Copilot', module: 'ai', resource: 'copilot', action: 'write' },
  { code: 'ai.governance.approve', name: 'Approve AI Governance', module: 'ai', resource: 'governance', action: 'approve' },
  { code: 'ai.governance.configure', name: 'Configure AI Governance', module: 'ai', resource: 'governance', action: 'configure' },
  { code: 'ai.governance.write', name: 'Write AI Governance', module: 'ai', resource: 'governance', action: 'write' },
  { code: 'ai.personal-agent.approve', name: 'Approve Personal Agent', module: 'ai', resource: 'personal-agent', action: 'approve' },
  { code: 'ai.personal-agent.write', name: 'Write Personal Agent', module: 'ai', resource: 'personal-agent', action: 'write' },
  { code: 'ai.squad.read', name: 'Read AI Squad', module: 'ai', resource: 'squad', action: 'read' },
  { code: 'ai_governance.manage', name: 'Manage AI Governance Module', module: 'ai', resource: 'ai-gov-module', action: 'manage' },
  { code: 'ai_governance.read', name: 'Read AI Governance Module', module: 'ai', resource: 'ai-gov-module', action: 'read' },
  { code: 'analytics.manage', name: 'Manage Analytics Module', module: 'analytics', resource: 'module', action: 'manage' },
  { code: 'asset.manage', name: 'Manage Asset Module', module: 'asset', resource: 'module', action: 'manage' },
  { code: 'attestation.record.manage', name: 'Manage Attestations', module: 'compliance', resource: 'attestation', action: 'manage' },
  { code: 'attestation.record.read', name: 'Read Attestations', module: 'compliance', resource: 'attestation', action: 'read' },
  { code: 'attestation.record.write', name: 'Write Attestations', module: 'compliance', resource: 'attestation', action: 'write' },
  { code: 'audit.finding.read', name: 'Read Audit Findings', module: 'audit', resource: 'finding', action: 'read' },
  { code: 'audit.manage', name: 'Manage Audit Module', module: 'audit', resource: 'module', action: 'manage' },
  { code: 'audit.record.configure', name: 'Configure Audit Records', module: 'audit', resource: 'record', action: 'configure' },
  { code: 'bcp.manage', name: 'Manage BCP Module', module: 'bcp', resource: 'module', action: 'manage' },
  { code: 'ccm.record.read', name: 'Read CCM Records', module: 'compliance', resource: 'ccm', action: 'read' },
  { code: 'compliance.assessment.approve', name: 'Approve Compliance Assessments', module: 'compliance', resource: 'assessment', action: 'approve' },
  { code: 'compliance.assessment.read', name: 'Read Compliance Assessments', module: 'compliance', resource: 'assessment', action: 'read' },
  { code: 'compliance.assessment.write', name: 'Write Compliance Assessments', module: 'compliance', resource: 'assessment', action: 'write' },
  { code: 'compliance.dpia.write', name: 'Write DPIA', module: 'compliance', resource: 'dpia', action: 'write' },
  { code: 'compliance.manage', name: 'Manage Compliance Module', module: 'compliance', resource: 'module', action: 'manage' },
  { code: 'compliance.mapping.manage', name: 'Manage Compliance Mappings', module: 'compliance', resource: 'mapping', action: 'manage' },
  { code: 'compliance.mapping.view', name: 'View Compliance Mappings', module: 'compliance', resource: 'mapping', action: 'view' },
  { code: 'compliance.maturity.assess', name: 'Assess Compliance Maturity', module: 'compliance', resource: 'maturity', action: 'assess' },
  { code: 'compliance.maturity.view', name: 'View Compliance Maturity', module: 'compliance', resource: 'maturity', action: 'view' },
  { code: 'compliance.program.configure', name: 'Configure Compliance Programs', module: 'compliance', resource: 'program', action: 'configure' },
  { code: 'compliance.read', name: 'Read Compliance Module', module: 'compliance', resource: 'module', action: 'read' },
  { code: 'compliance.regulatory.manage', name: 'Manage Regulatory', module: 'compliance', resource: 'regulatory', action: 'manage' },
  { code: 'compliance.regulatory.view', name: 'View Regulatory', module: 'compliance', resource: 'regulatory', action: 'view' },
  { code: 'compliance.score.view', name: 'View Compliance Score', module: 'compliance', resource: 'score', action: 'view' },
  { code: 'controls.manage', name: 'Manage Controls Module', module: 'controls', resource: 'module', action: 'manage' },
  { code: 'controls.record.delete', name: 'Delete Controls Records', module: 'controls', resource: 'record', action: 'delete' },
  { code: 'controls.record.write', name: 'Write Controls Records', module: 'controls', resource: 'record', action: 'write' },
  { code: 'delegation.chain.manage', name: 'Manage Delegation Chains', module: 'dauth', resource: 'delegation-chain', action: 'manage' },
  { code: 'delegation.chain.read', name: 'Read Delegation Chains', module: 'dauth', resource: 'delegation-chain', action: 'read' },
  { code: 'delegation.chain.write', name: 'Write Delegation Chains', module: 'dauth', resource: 'delegation-chain', action: 'write' },
  { code: 'document.record.delete', name: 'Delete Documents', module: 'governance', resource: 'document', action: 'delete' },
  { code: 'document.record.read', name: 'Read Documents', module: 'governance', resource: 'document', action: 'read' },
  { code: 'document.record.write', name: 'Write Documents', module: 'governance', resource: 'document', action: 'write' },
  { code: 'dora.manage', name: 'Manage DORA Module', module: 'compliance', resource: 'dora-module', action: 'manage' },
  { code: 'event.log.read', name: 'Read Event Logs', module: 'platform', resource: 'event-log', action: 'read' },
  { code: 'evidence.item.admin', name: 'Admin Evidence', module: 'evidence', resource: 'item', action: 'admin' },
  { code: 'evidence.item.configure', name: 'Configure Evidence', module: 'evidence', resource: 'item', action: 'configure' },
  { code: 'evidence.manage', name: 'Manage Evidence Module', module: 'evidence', resource: 'module', action: 'manage' },
  { code: 'evidence.read', name: 'Read Evidence Module', module: 'evidence', resource: 'module', action: 'read' },
  { code: 'foundation.org.write', name: 'Write Foundation Org', module: 'foundation', resource: 'org', action: 'write' },
  { code: 'framework.record.write', name: 'Write Framework Records', module: 'framework', resource: 'record', action: 'write' },
  { code: 'gate.record.read', name: 'Read Gate Records', module: 'workflow', resource: 'gate', action: 'read' },
  { code: 'governance.manage', name: 'Manage Governance Module', module: 'governance', resource: 'module', action: 'manage' },
  { code: 'governance.read', name: 'Read Governance Module', module: 'governance', resource: 'module', action: 'read' },
  { code: 'governance.record.configure', name: 'Configure Governance Records', module: 'governance', resource: 'record', action: 'configure' },
  { code: 'governance.record.delete', name: 'Delete Governance Records', module: 'governance', resource: 'record', action: 'delete' },
  { code: 'inbox.manage', name: 'Manage Inbox Module', module: 'notification', resource: 'inbox-module', action: 'manage' },
  { code: 'incident.manage', name: 'Manage Incident Module', module: 'incident', resource: 'module', action: 'manage' },
  { code: 'integrations.connector.manage', name: 'Manage Integration Connectors', module: 'integrations', resource: 'connector', action: 'manage' },
  { code: 'integrations.manage', name: 'Manage Integrations Module', module: 'integrations', resource: 'module', action: 'manage' },
  { code: 'issues.manage', name: 'Manage Issues Module', module: 'governance', resource: 'issue-module', action: 'manage' },
  { code: 'knowledge.base.write', name: 'Write Knowledge Base', module: 'knowledge', resource: 'base', action: 'write' },
  { code: 'knowledge.graph.read', name: 'Read Knowledge Graph', module: 'knowledge', resource: 'graph', action: 'read' },
  { code: 'knowledge.graph.write', name: 'Write Knowledge Graph', module: 'knowledge', resource: 'graph', action: 'write' },
  { code: 'ksa_regulatory.manage', name: 'Manage KSA Regulatory', module: 'compliance', resource: 'ksa-module', action: 'manage' },
  { code: 'local_knowledge.manage', name: 'Manage Local Knowledge', module: 'knowledge', resource: 'local-module', action: 'manage' },
  { code: 'maturity.assessment.read', name: 'Read Maturity Assessments', module: 'compliance', resource: 'maturity-assessment', action: 'read' },
  { code: 'notification.manage', name: 'Manage Notification Module', module: 'notification', resource: 'module', action: 'manage' },
  { code: 'platform.agent.manage', name: 'Manage Platform Agents', module: 'platform', resource: 'agent', action: 'manage' },
  { code: 'platform.agent.write', name: 'Write Platform Agents', module: 'platform', resource: 'agent', action: 'write' },
  { code: 'policy.manage', name: 'Manage Policy Module', module: 'policy', resource: 'module', action: 'manage' },
  { code: 'portals.manage', name: 'Manage Portals Module', module: 'platform', resource: 'portal-module', action: 'manage' },
  { code: 'privacy.manage', name: 'Manage Privacy Module', module: 'privacy', resource: 'module', action: 'manage' },
  { code: 'proactive_leadership.manage', name: 'Manage Proactive Leadership', module: 'governance', resource: 'pl-module', action: 'manage' },
  { code: 'profile.record.write', name: 'Write Profile Records', module: 'profile', resource: 'record', action: 'write' },
  { code: 'qiyas.assessment.delete', name: 'Delete Qiyas Assessments', module: 'compliance', resource: 'qiyas-assessment', action: 'delete' },
  { code: 'qiyas.assessment.write', name: 'Write Qiyas Assessments', module: 'compliance', resource: 'qiyas-assessment', action: 'write' },
  { code: 'qiyas.manage', name: 'Manage Qiyas Module', module: 'compliance', resource: 'qiyas-module', action: 'manage' },
  { code: 'remediation.manage', name: 'Manage Remediation Module', module: 'remediation', resource: 'module', action: 'manage' },
  { code: 'report.document.download', name: 'Download Reports', module: 'report', resource: 'document', action: 'download' },
  { code: 'report.document.share', name: 'Share Reports', module: 'report', resource: 'document', action: 'share' },
  { code: 'reporting.cadence.read', name: 'Read Reporting Cadence', module: 'reporting', resource: 'cadence', action: 'read' },
  { code: 'reporting.cadence.write', name: 'Write Reporting Cadence', module: 'reporting', resource: 'cadence', action: 'write' },
  { code: 'reporting.manage', name: 'Manage Reporting Module', module: 'reporting', resource: 'module', action: 'manage' },
  { code: 'reporting.monitoring.delete', name: 'Delete Monitoring', module: 'reporting', resource: 'monitoring', action: 'delete' },
  { code: 'reporting.monitoring.read', name: 'Read Monitoring', module: 'reporting', resource: 'monitoring', action: 'read' },
  { code: 'reporting.monitoring.write', name: 'Write Monitoring', module: 'reporting', resource: 'monitoring', action: 'write' },
  { code: 'reporting.report.configure', name: 'Configure Reports', module: 'reporting', resource: 'report', action: 'configure' },
  { code: 'reporting.report.read', name: 'Read Reports', module: 'reporting', resource: 'report', action: 'read' },
  { code: 'reports.document.generate', name: 'Generate Report Docs', module: 'reporting', resource: 'report-doc', action: 'generate' },
  { code: 'reports.document.read', name: 'Read Report Docs', module: 'reporting', resource: 'report-doc', action: 'read' },
  { code: 'reports.document.sign', name: 'Sign Report Docs', module: 'reporting', resource: 'report-doc', action: 'sign' },
  { code: 'risk.manage', name: 'Manage Risk Module', module: 'risk', resource: 'module', action: 'manage' },
  { code: 'runbook.record.read', name: 'Read Runbook Records', module: 'workflow', resource: 'runbook', action: 'read' },
  { code: 'runbook.record.write', name: 'Write Runbook Records', module: 'workflow', resource: 'runbook', action: 'write' },
  { code: 'shell.ui.read', name: 'Read Shell UI', module: 'platform', resource: 'shell-ui', action: 'read' },
  { code: 'shell.ui.write', name: 'Write Shell UI', module: 'platform', resource: 'shell-ui', action: 'write' },
  { code: 'sop.document.read', name: 'Read SOPs', module: 'governance', resource: 'sop', action: 'read' },
  { code: 'sop.document.write', name: 'Write SOPs', module: 'governance', resource: 'sop', action: 'write' },
  { code: 'telemetry.data.write', name: 'Write Telemetry', module: 'platform', resource: 'telemetry', action: 'write' },
  { code: 'training.manage', name: 'Manage Training Module', module: 'training', resource: 'module', action: 'manage' },
  { code: 'vendor.manage', name: 'Manage Vendor Module', module: 'vendor', resource: 'module', action: 'manage' },
  { code: 'workflow.agent.execute', name: 'Execute Workflow Agent', module: 'workflow', resource: 'agent', action: 'execute' },
  { code: 'workflow.agent.manage', name: 'Manage Workflow Agent', module: 'workflow', resource: 'agent', action: 'manage' },
  { code: 'workflow.agent.read', name: 'Read Workflow Agent', module: 'workflow', resource: 'agent', action: 'read' },
  { code: 'workflow.approval.approve', name: 'Approve Workflow', module: 'workflow', resource: 'approval', action: 'approve' },
  { code: 'workflow.autonomous.config', name: 'Configure Autonomous Workflow', module: 'workflow', resource: 'autonomous', action: 'config' },
  { code: 'workflow.autonomous.read', name: 'Read Autonomous Workflow', module: 'workflow', resource: 'autonomous', action: 'read' },
  { code: 'workflow.autonomous.write', name: 'Write Autonomous Workflow', module: 'workflow', resource: 'autonomous', action: 'write' },
  { code: 'workflow.instance.configure', name: 'Configure Workflow Instance', module: 'workflow', resource: 'instance', action: 'configure' },
  { code: 'workflow.instance.execute', name: 'Execute Workflow Instance', module: 'workflow', resource: 'instance', action: 'execute' },
  { code: 'workflow.manage', name: 'Manage Workflow Module', module: 'workflow', resource: 'module', action: 'manage' },
  { code: 'workflow.policy.manage', name: 'Manage Workflow Policies', module: 'workflow', resource: 'policy', action: 'manage' },
  { code: 'workflow.policy.read', name: 'Read Workflow Policies', module: 'workflow', resource: 'policy', action: 'read' },
  { code: 'workflow.task.act', name: 'Act on Workflow Task', module: 'workflow', resource: 'task', action: 'act' },
  // Dot-format canonical equivalents (role mappings use these)
  { code: 'incident.write', name: 'Write Incidents', module: 'incident', resource: 'ticket', action: 'write' },
  { code: 'incident.delete', name: 'Delete Incidents', module: 'incident', resource: 'ticket', action: 'delete' },
  { code: 'controls.monitor', name: 'Monitor Controls', module: 'controls', resource: 'record', action: 'monitor' },
  { code: 'controls.test', name: 'Test Controls', module: 'controls', resource: 'record', action: 'test' },
  { code: 'controls.certify', name: 'Certify Controls', module: 'controls', resource: 'record', action: 'certify' },
  { code: 'controls.report', name: 'Report Controls', module: 'controls', resource: 'record', action: 'report' },
  { code: 'controls.admin', name: 'Admin Controls', module: 'controls', resource: 'record', action: 'admin' },
  { code: 'remediation.write', name: 'Write Remediation', module: 'remediation', resource: 'task', action: 'write' },
  { code: 'remediation.delete', name: 'Delete Remediation', module: 'remediation', resource: 'task', action: 'delete' },
  { code: 'exception.write', name: 'Write Exceptions', module: 'exception', resource: 'record', action: 'write' },
  { code: 'exception.approve', name: 'Approve Exceptions', module: 'exception', resource: 'record', action: 'approve' },
  { code: 'exception.bulk', name: 'Bulk Exceptions', module: 'exception', resource: 'record', action: 'bulk' },
  { code: 'compliance.delete', name: 'Delete Compliance', module: 'compliance', resource: 'record', action: 'delete' },
  { code: 'action.write', name: 'Write Actions', module: 'action', resource: 'item', action: 'write' },
  { code: 'action.bulk', name: 'Bulk Actions', module: 'action', resource: 'item', action: 'bulk' },
  { code: 'integrations.write', name: 'Write Integrations', module: 'integrations', resource: 'connector', action: 'write' },
  { code: 'risk.approve', name: 'Approve Risk', module: 'risk', resource: 'record', action: 'approve' },
  { code: 'platform.admin', name: 'Platform Admin', module: 'platform', resource: 'system', action: 'admin' },
  { code: 'access.read', name: 'Read Access', module: 'dauth', resource: 'access', action: 'read' },
  { code: 'access.manage', name: 'Manage Access', module: 'dauth', resource: 'access', action: 'manage' },
  { code: 'agent.read', name: 'Read Agents', module: 'ai', resource: 'agent', action: 'read' },
  { code: 'agent.manage', name: 'Manage Agents', module: 'ai', resource: 'agent', action: 'manage' },
  // Legacy colon-format aliases (module *.security.ts manifests may still reference — kept for backward compat)
  { code: 'incident:write', name: 'Write Incidents (legacy)', module: 'incident', resource: 'ticket', action: 'write' },
  { code: 'incident:delete', name: 'Delete Incidents (legacy)', module: 'incident', resource: 'ticket', action: 'delete' },
  { code: 'controls:monitor', name: 'Monitor Controls (legacy)', module: 'controls', resource: 'record', action: 'monitor' },
  { code: 'controls:test', name: 'Test Controls (legacy)', module: 'controls', resource: 'record', action: 'test' },
  { code: 'controls:certify', name: 'Certify Controls (legacy)', module: 'controls', resource: 'record', action: 'certify' },
  { code: 'controls:report', name: 'Report Controls (legacy)', module: 'controls', resource: 'record', action: 'report' },
  { code: 'controls:admin', name: 'Admin Controls (legacy)', module: 'controls', resource: 'record', action: 'admin' },
  { code: 'remediation:write', name: 'Write Remediation (legacy)', module: 'remediation', resource: 'task', action: 'write' },
  { code: 'remediation:delete', name: 'Delete Remediation (legacy)', module: 'remediation', resource: 'task', action: 'delete' },
  { code: 'exception:write', name: 'Write Exceptions (legacy)', module: 'exception', resource: 'record', action: 'write' },
  { code: 'exception:approve', name: 'Approve Exceptions (legacy)', module: 'exception', resource: 'record', action: 'approve' },
  { code: 'exception:bulk', name: 'Bulk Exceptions (legacy)', module: 'exception', resource: 'record', action: 'bulk' },
  { code: 'compliance:delete', name: 'Delete Compliance (legacy)', module: 'compliance', resource: 'record', action: 'delete' },
  { code: 'action:write', name: 'Write Actions (legacy)', module: 'action', resource: 'item', action: 'write' },
  { code: 'action:bulk', name: 'Bulk Actions (legacy)', module: 'action', resource: 'item', action: 'bulk' },
  { code: 'evidence:manage', name: 'Manage Evidence (legacy)', module: 'evidence', resource: 'item', action: 'manage' },
  { code: 'integrations:write', name: 'Write Integrations (legacy)', module: 'integrations', resource: 'connector', action: 'write-legacy' },
  { code: 'risk:approve', name: 'Approve Risk (legacy)', module: 'risk', resource: 'record', action: 'approve' },
  { code: 'platform:admin', name: 'Platform Admin (legacy)', module: 'platform', resource: 'system', action: 'admin-legacy' },
  { code: 'access:read', name: 'Read Access (legacy)', module: 'dauth', resource: 'access', action: 'read' },
  { code: 'access:manage', name: 'Manage Access (legacy)', module: 'dauth', resource: 'access', action: 'manage' },
  { code: 'agent:read', name: 'Read Agents (legacy)', module: 'ai', resource: 'agent', action: 'read-legacy' },
  { code: 'agent:manage', name: 'Manage Agents (legacy)', module: 'ai', resource: 'agent', action: 'manage-legacy' },
  { code: 'risk.record.submit', name: 'Submit Risk Record', module: 'risk', resource: 'record', action: 'submit' },
  { code: 'risk.record.review', name: 'Review Risk Record', module: 'risk', resource: 'record', action: 'review' },
  { code: 'risk.record.approve', name: 'Approve Risk Record', module: 'risk', resource: 'record', action: 'approve' },
  { code: 'risk.record.close', name: 'Close Risk Record', module: 'risk', resource: 'record', action: 'close' },
  { code: 'risk.record.update', name: 'Update Risk Record', module: 'risk', resource: 'record', action: 'update' },
  { code: 'risk.treatment.assign', name: 'Assign Risk Treatment', module: 'risk', resource: 'treatment', action: 'assign' },
  { code: 'audit.engagement.create', name: 'Create Audit Engagement', module: 'audit', resource: 'engagement', action: 'create' },
  { code: 'audit.finding.close', name: 'Close Audit Finding', module: 'audit', resource: 'finding', action: 'close' },
  { code: 'audit.finding.issue', name: 'Issue Audit Finding', module: 'audit', resource: 'finding', action: 'issue' },
  { code: 'audit.finding.respond', name: 'Respond to Audit Finding', module: 'audit', resource: 'finding', action: 'respond' },
  { code: 'audit.report.approve', name: 'Approve Audit Report', module: 'audit', resource: 'report', action: 'approve' },
  { code: 'audit.report.create', name: 'Create Audit Report', module: 'audit', resource: 'report', action: 'create' },
  { code: 'audit.workpaper.update', name: 'Update Audit Workpaper', module: 'audit', resource: 'workpaper', action: 'update' },
  { code: 'policy.document.update', name: 'Update Policy Document', module: 'policy', resource: 'document', action: 'update' },
  { code: 'policy.document.review', name: 'Review Policy Document', module: 'policy', resource: 'document', action: 'review' },
  { code: 'policy.document.approve', name: 'Approve Policy Document', module: 'policy', resource: 'document', action: 'approve' },
  { code: 'policy.document.retire', name: 'Retire Policy Document', module: 'policy', resource: 'document', action: 'retire' },
  { code: 'compliance.control.update', name: 'Update Compliance Control', module: 'compliance', resource: 'control', action: 'update' },
  { code: 'compliance.obligation.approve', name: 'Approve Compliance Obligation', module: 'compliance', resource: 'obligation', action: 'approve' },
  { code: 'compliance.obligation.update', name: 'Update Compliance Obligation', module: 'compliance', resource: 'obligation', action: 'update' },
  { code: 'compliance.attestation.submit', name: 'Submit Compliance Attestation', module: 'compliance', resource: 'attestation', action: 'submit' },
  { code: 'compliance.attestation.review', name: 'Review Compliance Attestation', module: 'compliance', resource: 'attestation', action: 'review' },
  { code: 'compliance.attestation.manage', name: 'Manage Compliance Attestation', module: 'compliance', resource: 'attestation', action: 'manage' },
  { code: 'compliance.score.approve', name: 'Approve Compliance Score', module: 'compliance', resource: 'score', action: 'approve' },
  { code: 'compliance.score.review', name: 'Review Compliance Score', module: 'compliance', resource: 'score', action: 'review' },
  { code: 'compliance.test.execute', name: 'Execute Compliance Test', module: 'compliance', resource: 'test', action: 'execute' },
  { code: 'incident.record.update', name: 'Update Incident Record', module: 'incident', resource: 'record', action: 'update' },
  { code: 'incident.record.review', name: 'Review Incident Record', module: 'incident', resource: 'record', action: 'review' },
  { code: 'incident.record.approve', name: 'Approve Incident Record', module: 'incident', resource: 'record', action: 'approve' },
  { code: 'incident.record.escalate', name: 'Escalate Incident Record', module: 'incident', resource: 'record', action: 'escalate' },
  { code: 'vendor.record.create', name: 'Create Vendor Record', module: 'vendor', resource: 'record', action: 'create' },
  { code: 'vendor.assessment.execute', name: 'Execute Vendor Assessment', module: 'vendor', resource: 'assessment', action: 'execute' },
  { code: 'vendor.assessment.approve', name: 'Approve Vendor Assessment', module: 'vendor', resource: 'assessment', action: 'approve' },
  { code: 'evidence.item.upload', name: 'Upload Evidence Item', module: 'evidence', resource: 'item', action: 'upload' },
  { code: 'evidence.item.verify', name: 'Verify Evidence Item', module: 'evidence', resource: 'item', action: 'verify' },
  { code: 'evidence.item.lock', name: 'Lock Evidence Item', module: 'evidence', resource: 'item', action: 'lock' },
  { code: 'evidence.item.release', name: 'Release Evidence Item', module: 'evidence', resource: 'item', action: 'release' },
  { code: 'evidence.item.archive', name: 'Archive Evidence Item', module: 'evidence', resource: 'item', action: 'archive' },
  { code: 'governance.body.create', name: 'Create Governance Body', module: 'governance', resource: 'body', action: 'create' },
  { code: 'governance.charter.update', name: 'Update Governance Charter', module: 'governance', resource: 'charter', action: 'update' },
  { code: 'governance.meeting.manage', name: 'Manage Governance Meeting', module: 'governance', resource: 'meeting', action: 'manage' },
  { code: 'exception.request.create', name: 'Create Exception Request', module: 'exception', resource: 'request', action: 'create' },
  { code: 'exception.request.review', name: 'Review Exception Request', module: 'exception', resource: 'request', action: 'review' },
  { code: 'exception.request.approve', name: 'Approve Exception Request', module: 'exception', resource: 'request', action: 'approve' },
  { code: 'remediation.task.update', name: 'Update Remediation Task', module: 'remediation', resource: 'task', action: 'update' },
  { code: 'remediation.task.close', name: 'Close Remediation Task', module: 'remediation', resource: 'task', action: 'close' },
  { code: 'action.item.update', name: 'Update Action Item', module: 'action', resource: 'item', action: 'update' },
  { code: 'action.item.close', name: 'Close Action Item', module: 'action', resource: 'item', action: 'close' },
  { code: 'asset.record.update', name: 'Update Asset Record', module: 'asset', resource: 'record', action: 'update' },
  { code: 'asset.classification.review', name: 'Review Asset Classification', module: 'asset', resource: 'classification', action: 'review' },
  { code: 'bcp.plan.update', name: 'Update BCP Plan', module: 'bcp', resource: 'plan', action: 'update' },
  { code: 'bcp.exercise.approve', name: 'Approve BCP Exercise', module: 'bcp', resource: 'exercise', action: 'approve' },
  { code: 'training.program.manage', name: 'Manage Training Program', module: 'training', resource: 'program', action: 'manage' },
  // ── Track A: Route-referenced but previously unseeded (24 codes) ──
  { code: 'admin.config.read', name: 'Read Admin Config', module: 'admin', resource: 'config', action: 'read' },
  { code: 'admin.system.settings', name: 'Admin System Settings', module: 'admin', resource: 'system', action: 'settings' },
  { code: 'ai.contextual.read', name: 'Read AI Contextual', module: 'ai', resource: 'contextual', action: 'read' },
  { code: 'ai.contextual.write', name: 'Write AI Contextual', module: 'ai', resource: 'contextual', action: 'write' },
  { code: 'ai_squad.manage', name: 'Manage AI Squad', module: 'ai', resource: 'squad', action: 'manage' },
  { code: 'ai_squad.read', name: 'Read AI Squad (module)', module: 'ai', resource: 'squad', action: 'read' },
  { code: 'assessment.record.delete', name: 'Delete Assessment Records', module: 'assessment', resource: 'record', action: 'delete' },
  { code: 'assessment.record.write', name: 'Write Assessment Records', module: 'assessment', resource: 'record', action: 'write' },
  { code: 'control.record.delete', name: 'Delete Control Records', module: 'control', resource: 'record', action: 'delete' },
  { code: 'evidence.item.delete', name: 'Delete Evidence Items', module: 'evidence', resource: 'item', action: 'delete' },
  { code: 'evidence.item.manage', name: 'Manage Evidence Items', module: 'evidence', resource: 'item', action: 'manage' },
  { code: 'exception.record.write', name: 'Write Exception Records', module: 'exception', resource: 'record', action: 'write' },
  { code: 'obligation.write', name: 'Write Obligations', module: 'compliance', resource: 'obligation', action: 'write' },
  { code: 'platform.command_palette.read', name: 'Read Command Palette', module: 'platform', resource: 'command_palette', action: 'read' },
  { code: 'platform.entity_link.delete', name: 'Delete Entity Links', module: 'platform', resource: 'entity_link', action: 'delete' },
  { code: 'platform.entity_link.write', name: 'Write Entity Links', module: 'platform', resource: 'entity_link', action: 'write' },
  { code: 'platform.inline_edit.read', name: 'Read Inline Edit', module: 'platform', resource: 'inline_edit', action: 'read' },
  { code: 'platform.inline_edit.write', name: 'Write Inline Edit', module: 'platform', resource: 'inline_edit', action: 'write' },
  { code: 'platform.messaging.write', name: 'Write Platform Messaging', module: 'platform', resource: 'messaging', action: 'write' },
  { code: 'platform.search.read', name: 'Read Platform Search', module: 'platform', resource: 'search', action: 'read' },
  { code: 'security.config.read', name: 'Read Security Config', module: 'dauth', resource: 'security-config', action: 'read' },
  { code: 'security.config.write', name: 'Write Security Config', module: 'dauth', resource: 'security-config', action: 'write' },
  { code: 'workflow.approve', name: 'Approve Workflow', module: 'workflow', resource: 'instance', action: 'approve' },
  { code: 'workflow.delete', name: 'Delete Workflow', module: 'workflow', resource: 'instance', action: 'delete' },
  // ── Track A: Lifecycle transition permissions (8 codes) ──
  { code: 'bootstrap.record.approve', name: 'Approve Bootstrap Record', module: 'platform', resource: 'bootstrap', action: 'approve' },
  { code: 'compliance.assessment.finalize', name: 'Finalize Compliance Assessment', module: 'compliance', resource: 'assessment', action: 'finalize' },
  { code: 'compliance.framework.approve', name: 'Approve Compliance Framework', module: 'compliance', resource: 'framework', action: 'approve' },
  { code: 'compliance.framework.suspend', name: 'Suspend Compliance Framework', module: 'compliance', resource: 'framework', action: 'suspend' },
  { code: 'compliance.obligation.waive', name: 'Waive Compliance Obligation', module: 'compliance', resource: 'obligation', action: 'waive' },
  { code: 'dora.record.approve', name: 'Approve DORA Record', module: 'compliance', resource: 'dora', action: 'approve' },
  { code: 'evidence.collection.complete', name: 'Complete Evidence Collection', module: 'evidence', resource: 'collection', action: 'complete' },
  { code: 'evidence.collection.manage', name: 'Manage Evidence Collection', module: 'evidence', resource: 'collection', action: 'manage' },
  // ── Track B: Config Center (MP-58) ──
  { code: 'config.setting.read', name: 'Read Config Setting', module: 'platform', resource: 'config-setting', action: 'read' },
  { code: 'config.setting.write', name: 'Write Config Setting', module: 'platform', resource: 'config-setting', action: 'write' },
  { code: 'config.compare.read', name: 'Compare Config Across Scopes', module: 'platform', resource: 'config-compare', action: 'read' },
  { code: 'config.export.read', name: 'Export Config Bundle', module: 'platform', resource: 'config-export', action: 'read' },
  { code: 'config.import.write', name: 'Import Config Bundle', module: 'platform', resource: 'config-import', action: 'write' },
  { code: 'config.audit.read', name: 'Read Config Audit Log', module: 'platform', resource: 'config-audit', action: 'read' },
  { code: 'config.health.read', name: 'Read Config Health', module: 'platform', resource: 'config-health', action: 'read' },
  // ── Sales Room (digital sales room: marketing assets, per-prospect demo rooms, AI ingestion) ──
  { code: 'sales_room.asset.read', name: 'Read Sales Room Assets', module: 'sales-room', resource: 'asset', action: 'read' },
  { code: 'sales_room.asset.manage', name: 'Manage Sales Room Assets', module: 'sales-room', resource: 'asset', action: 'manage' },
  { code: 'sales_room.asset.publish', name: 'Publish Sales Room Asset (flip is_public)', module: 'sales-room', resource: 'asset', action: 'publish' },
  { code: 'sales_room.room.create', name: 'Create Client Room', module: 'sales-room', resource: 'room', action: 'create' },
  { code: 'sales_room.room.manage', name: 'Manage Client Room', module: 'sales-room', resource: 'room', action: 'manage' },
  { code: 'sales_room.room.share', name: 'Share Client Room (mint accessCode + email)', module: 'sales-room', resource: 'room', action: 'share' },
  { code: 'sales_room.analytics.read', name: 'Read Sales Room Engagement Analytics', module: 'sales-room', resource: 'analytics', action: 'read' },
  { code: 'sales_room.lead.read', name: 'Read Captured Visitor Leads', module: 'sales-room', resource: 'lead', action: 'read' },
  { code: 'sales_room.ai.run', name: 'Trigger Sales Room AI Re-ingestion', module: 'sales-room', resource: 'ai', action: 'run' },
];
