import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const PORTALS_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'PORTALS.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'PORTALS.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'PORTALS.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'PORTALS.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'PORTALS.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'PORTALS.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'PORTALS.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'PORTALS.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'PORTALS.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'PORTALS.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'PORTALS.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'PORTALS.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  SESSIONS_NOT_FOUND: { code: 'PORTALS.SESSIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Sessions not found', messageAr: 'Sessions غير موجود' },
  SESSIONS_ALREADY_EXISTS: { code: 'PORTALS.SESSIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Sessions already exists', messageAr: 'Sessions موجود بالفعل' },
  SESSIONS_VALIDATION_FAILED: { code: 'PORTALS.SESSIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Sessions validation failed', messageAr: 'فشل التحقق من Sessions' },
  EXPIRED_TOKENS_NOT_FOUND: { code: 'PORTALS.EXPIRED_TOKENS_NOT_FOUND', httpStatus: 404, messageEn: 'Expired Tokens not found', messageAr: 'Expired Tokens غير موجود' },
  EXPIRED_TOKENS_ALREADY_EXISTS: { code: 'PORTALS.EXPIRED_TOKENS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Expired Tokens already exists', messageAr: 'Expired Tokens موجود بالفعل' },
  EXPIRED_TOKENS_VALIDATION_FAILED: { code: 'PORTALS.EXPIRED_TOKENS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Expired Tokens validation failed', messageAr: 'فشل التحقق من Expired Tokens' },
  REINDEX_NOT_FOUND: { code: 'PORTALS.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'PORTALS.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'PORTALS.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'PORTALS.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'PORTALS.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'PORTALS.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'PORTALS.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'PORTALS.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'PORTALS.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  SEARCH_NOT_FOUND: { code: 'PORTALS.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'PORTALS.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'PORTALS.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  DASHBOARD_NOT_FOUND: { code: 'PORTALS.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'PORTALS.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'PORTALS.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  PROVISION_NOT_FOUND: { code: 'PORTALS.PROVISION_NOT_FOUND', httpStatus: 404, messageEn: 'Provision not found', messageAr: 'Provision غير موجود' },
  PROVISION_ALREADY_EXISTS: { code: 'PORTALS.PROVISION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Provision already exists', messageAr: 'Provision موجود بالفعل' },
  PROVISION_VALIDATION_FAILED: { code: 'PORTALS.PROVISION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Provision validation failed', messageAr: 'فشل التحقق من Provision' },
  TRENDS_NOT_FOUND: { code: 'PORTALS.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'PORTALS.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'PORTALS.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  CROSS_MODULE_NOT_FOUND: { code: 'PORTALS.CROSS_MODULE_NOT_FOUND', httpStatus: 404, messageEn: 'Cross Module not found', messageAr: 'Cross Module غير موجود' },
  CROSS_MODULE_ALREADY_EXISTS: { code: 'PORTALS.CROSS_MODULE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Cross Module already exists', messageAr: 'Cross Module موجود بالفعل' },
  CROSS_MODULE_VALIDATION_FAILED: { code: 'PORTALS.CROSS_MODULE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Cross Module validation failed', messageAr: 'فشل التحقق من Cross Module' },
  EXPORT_NOT_FOUND: { code: 'PORTALS.EXPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Export not found', messageAr: 'Export غير موجود' },
  EXPORT_ALREADY_EXISTS: { code: 'PORTALS.EXPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Export already exists', messageAr: 'Export موجود بالفعل' },
  EXPORT_VALIDATION_FAILED: { code: 'PORTALS.EXPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Export validation failed', messageAr: 'فشل التحقق من Export' },

  UNAUTHORIZED: { code: 'PORTALS.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for portals operation', messageAr: 'صلاحيات غير كافية لعملية portals' },
  INVALID_STATE_TRANSITION: { code: 'PORTALS.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'PORTALS.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'PORTALS.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'PORTALS.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'PORTALS.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type PortalsErrorCode = keyof typeof PORTALS_ERROR_CODES;
