import type { ModuleManifest } from '@dos/types';
import { registerModule } from '@dos/module-sdk';
import { CONTROLS_PERMISSIONS, CONTROLS_ROLES, CONTROLS_ACTIONS } from './security/controls.security';
import { CONTROLS_APPROVAL_MATRIX } from './security/controls.approval-matrix';

export const CONTROLS_MANIFEST: ModuleManifest = {
  code: 'controls',
  version: '2.0.0',
  aliases: [],
  nameEn: 'Controls',
  nameAr: 'الضوابط',
  descriptionEn: 'Control library, ownership, mapping, effectiveness testing, automation state, certification campaigns, deficiency management, and monitoring.',
  descriptionAr: 'مكتبة الضوابط والملكية والرسم الخرائطي واختبار الفعالية وحالة الأتمتة وحملات الاعتماد وإدارة الإخفاقات والمراقبة.',
  tier: 'full',
  category: 'core_grc',
  routeBase: '/api/controls',
  eventNamespace: 'controls',
  tablePrefix: 'control_',
  ownedTables: [
    'controls',
    'control_categories',
    'control_objectives',
    'control_owners',
    'control_tests',
    'control_test_templates',
    'control_failures',
    'control_issues',
    'control_remediation_actions',
    'control_effectiveness_scores',
    'control_risk_links',
    'control_obligation_mappings',
    'control_policy_links',
    'control_status_history',
    'control_evidence_requirements',
    'control_certification_campaigns',
    'control_certification_requests',
    'control_monitoring_rules',
    'control_monitoring_alerts',
    'control_automation_state',
    'control_design_metadata',
    'control_activity_log',
  ],
  sharedTables: [],
  referencedTables: [
    'tenant_preferences',
    'obligations',
    'risks',
    'policies',
    'audit_findings',
    'evidence_requests',
    'teams',
  ],
  aggregateRoots: [
    'controls',
    'control_issues',
    'control_certification_campaigns',
    'control_monitoring_rules',
  ],
  publishedEvents: [
    'controls.control_created',
    'controls.control_updated',
    'controls.control_activated',
    'controls.control_retired',
    'controls.control_deleted',
    'controls.ownership_assigned',
    'controls.test_completed',
    'controls.test_failed',
    'controls.effectiveness_scored',
    'controls.deficiency_opened',
    'controls.deficiency_closed',
    'controls.mapping_linked',
    'controls.mapping_unlinked',
    'controls.certification_campaign_created',
    'controls.certification_response_submitted',
    'controls.monitoring_alert_triggered',
    'controls.automation_state_changed',
  ],
  consumedEvents: [
    'risk.assessment_completed',
    'compliance.obligation_updated',
    'audit.finding_created',
    'evidence.collected',
    'workflow.status_changed',
  ],
  hardDeps: ['compliance'],
  softDeps: ['risk', 'audit', 'evidence', 'policy'],
  navId: 'controls',
  navChildCount: 8,
  workflowTemplateCode: 'control_approval_cycle',
  workflowSlaHours: 72,
  automationLevel: 'semi',
  agentBinding: 'A06',
  aiCapabilities: ['drafts', 'recommendations', 'gate_checks', 'scoring', 'anomaly_detection'],
  aiEnabled: true,
  featureFlags: ['controls.certification', 'controls.monitoring', 'controls.ai_mapping'],
  installable: true,
  provisioningOrder: 15,
  licensingTier: 'starter',
  visibility: 'internal',
  adminSurfaces: ['taxonomy', 'test-templates', 'monitoring-rules', 'effectiveness-policy', 'automation-policy'],

  securityPermissions: CONTROLS_PERMISSIONS,
  securityRoles: CONTROLS_ROLES,
  securityActions: CONTROLS_ACTIONS,
  approvalRules: CONTROLS_APPROVAL_MATRIX,
  ownershipRules: [
    { entityType: 'control', ownerField: 'primary_owner', reviewerField: 'testing_owner', approverField: 'design_owner', assigneeField: 'operator', orgScopeField: 'department_id', defaultOwnerRole: 'controls.module_lead', canDelegate: true, delegateRoles: ['controls.operator', 'controls.contributor'], canReassign: true, reassignRoles: ['controls.module_lead', 'controls.executive_owner'], requiresApproval: false, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'department' },
    { entityType: 'control_tests', ownerField: 'owner_id', reviewerField: 'reviewer_id', approverField: 'approver_id', assigneeField: 'assignee_id', orgScopeField: 'department_id', defaultOwnerRole: 'controls.module_lead', canDelegate: true, delegateRoles: ['controls.operator', 'controls.contributor'], canReassign: true, reassignRoles: ['controls.module_lead', 'controls.executive_owner'], requiresApproval: true, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'department' },
    { entityType: 'control_mappings', ownerField: 'owner_id', reviewerField: 'reviewer_id', approverField: 'approver_id', assigneeField: 'assignee_id', orgScopeField: 'department_id', defaultOwnerRole: 'controls.module_lead', canDelegate: true, delegateRoles: ['controls.operator', 'controls.contributor'], canReassign: true, reassignRoles: ['controls.module_lead', 'controls.executive_owner'], requiresApproval: true, creatorRights: 'full', externalVisible: false, rowLevelAccess: 'department' },
  ],
  sodRules: [
    { ruleCode: 'controls.sod.tester_approver', descriptionEn: 'Control tester cannot approve their own test results', descriptionAr: 'لا يمكن لمختبر الضابط الموافقة على نتائج اختباره', conflictingRoles: [], conflictingActions: ['controls.test.execute', 'controls.test.approve'], conflictingTransitions: [], severity: 'critical', enforcement: 'block', temporaryWaiverAllowed: false, waiverMaxDays: null, compensatingControls: ['independent_review'], overrideAuthority: ['controls.executive_owner'], auditObligations: ['log_sod_violation'] },
    { ruleCode: 'controls.sod.owner_retire', descriptionEn: 'Control owner cannot approve retirement of their own control', descriptionAr: 'لا يمكن لمالك الضابط الموافقة على إيقاف ضابطه', conflictingRoles: [], conflictingActions: ['controls.control.own', 'controls.control.retire'], conflictingTransitions: ['active->retired'], severity: 'high', enforcement: 'block', temporaryWaiverAllowed: true, waiverMaxDays: 30, compensatingControls: ['manager_review'], overrideAuthority: ['controls.executive_owner'], auditObligations: ['log_sod_violation'] },
  ],
};

registerModule(CONTROLS_MANIFEST);
