/**
 * controls — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition, EntityStateMachine } from './ports/lifecycle.port';

const CONTROLS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const CONTROLS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'controls',
  'controls',
  CONTROLS_STATES,
  CONTROLS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const CONTROL_ISSUES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const CONTROL_ISSUES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'controls',
  'control_issues',
  CONTROL_ISSUES_STATES,
  CONTROL_ISSUES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const CONTROL_CERTIFICATION_CAMPAIGNS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const CONTROL_CERTIFICATION_CAMPAIGNS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'controls',
  'control_certification_campaigns',
  CONTROL_CERTIFICATION_CAMPAIGNS_STATES,
  CONTROL_CERTIFICATION_CAMPAIGNS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

const CONTROL_MONITORING_RULES_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const CONTROL_MONITORING_RULES_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'controls',
  'control_monitoring_rules',
  CONTROL_MONITORING_RULES_STATES,
  CONTROL_MONITORING_RULES_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);

/**
 * Control Entity State Machine — module-owned (Patch 0 §5.4, Law 15)
 * Extracted from platform/dos/lifecycle/entity-state-machine.ts where it
 * was incorrectly embedded as a platform pre-built FSM.
 */
export const CONTROL_STATE_MACHINE = new EntityStateMachine<'draft' | 'active' | 'under_review' | 'retired'>({
  entityType: 'control',
  transitions: {
    draft: ['active'],
    active: ['under_review', 'retired'],
    under_review: ['active', 'retired'],
    retired: [],
  },
});
