import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const DORA_ERROR_CODES = {
  DIAGNOSTICS_NOT_FOUND: { code: 'DORA.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'DORA.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'DORA.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  OVERVIEW_NOT_FOUND: { code: 'DORA.OVERVIEW_NOT_FOUND', httpStatus: 404, messageEn: 'Overview not found', messageAr: 'Overview غير موجود' },
  OVERVIEW_ALREADY_EXISTS: { code: 'DORA.OVERVIEW_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overview already exists', messageAr: 'Overview موجود بالفعل' },
  OVERVIEW_VALIDATION_FAILED: { code: 'DORA.OVERVIEW_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overview validation failed', messageAr: 'فشل التحقق من Overview' },
  ICT_ASSETS_NOT_FOUND: { code: 'DORA.ICT_ASSETS_NOT_FOUND', httpStatus: 404, messageEn: 'Ict Assets not found', messageAr: 'Ict Assets غير موجود' },
  ICT_ASSETS_ALREADY_EXISTS: { code: 'DORA.ICT_ASSETS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Ict Assets already exists', messageAr: 'Ict Assets موجود بالفعل' },
  ICT_ASSETS_VALIDATION_FAILED: { code: 'DORA.ICT_ASSETS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Ict Assets validation failed', messageAr: 'فشل التحقق من Ict Assets' },
  RESILIENCE_TESTS_NOT_FOUND: { code: 'DORA.RESILIENCE_TESTS_NOT_FOUND', httpStatus: 404, messageEn: 'Resilience Tests not found', messageAr: 'Resilience Tests غير موجود' },
  RESILIENCE_TESTS_ALREADY_EXISTS: { code: 'DORA.RESILIENCE_TESTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Resilience Tests already exists', messageAr: 'Resilience Tests موجود بالفعل' },
  RESILIENCE_TESTS_VALIDATION_FAILED: { code: 'DORA.RESILIENCE_TESTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Resilience Tests validation failed', messageAr: 'فشل التحقق من Resilience Tests' },
  MAJOR_INCIDENTS_NOT_FOUND: { code: 'DORA.MAJOR_INCIDENTS_NOT_FOUND', httpStatus: 404, messageEn: 'Major Incidents not found', messageAr: 'Major Incidents غير موجود' },
  MAJOR_INCIDENTS_ALREADY_EXISTS: { code: 'DORA.MAJOR_INCIDENTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Major Incidents already exists', messageAr: 'Major Incidents موجود بالفعل' },
  MAJOR_INCIDENTS_VALIDATION_FAILED: { code: 'DORA.MAJOR_INCIDENTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Major Incidents validation failed', messageAr: 'فشل التحقق من Major Incidents' },
  THREAT_INTEL_NOT_FOUND: { code: 'DORA.THREAT_INTEL_NOT_FOUND', httpStatus: 404, messageEn: 'Threat Intel not found', messageAr: 'Threat Intel غير موجود' },
  THREAT_INTEL_ALREADY_EXISTS: { code: 'DORA.THREAT_INTEL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Threat Intel already exists', messageAr: 'Threat Intel موجود بالفعل' },
  THREAT_INTEL_VALIDATION_FAILED: { code: 'DORA.THREAT_INTEL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Threat Intel validation failed', messageAr: 'فشل التحقق من Threat Intel' },
  BACKUP_CONFIGS_NOT_FOUND: { code: 'DORA.BACKUP_CONFIGS_NOT_FOUND', httpStatus: 404, messageEn: 'Backup Configs not found', messageAr: 'Backup Configs غير موجود' },
  BACKUP_CONFIGS_ALREADY_EXISTS: { code: 'DORA.BACKUP_CONFIGS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backup Configs already exists', messageAr: 'Backup Configs موجود بالفعل' },
  BACKUP_CONFIGS_VALIDATION_FAILED: { code: 'DORA.BACKUP_CONFIGS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backup Configs validation failed', messageAr: 'فشل التحقق من Backup Configs' },
  THIRD_PARTY_PROVIDERS_NOT_FOUND: { code: 'DORA.THIRD_PARTY_PROVIDERS_NOT_FOUND', httpStatus: 404, messageEn: 'Third Party Providers not found', messageAr: 'Third Party Providers غير موجود' },
  THIRD_PARTY_PROVIDERS_ALREADY_EXISTS: { code: 'DORA.THIRD_PARTY_PROVIDERS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Third Party Providers already exists', messageAr: 'Third Party Providers موجود بالفعل' },
  THIRD_PARTY_PROVIDERS_VALIDATION_FAILED: { code: 'DORA.THIRD_PARTY_PROVIDERS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Third Party Providers validation failed', messageAr: 'فشل التحقق من Third Party Providers' },
  OBLIGATIONS_NOT_FOUND: { code: 'DORA.OBLIGATIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Obligations not found', messageAr: 'Obligations غير موجود' },
  OBLIGATIONS_ALREADY_EXISTS: { code: 'DORA.OBLIGATIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Obligations already exists', messageAr: 'Obligations موجود بالفعل' },
  OBLIGATIONS_VALIDATION_FAILED: { code: 'DORA.OBLIGATIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Obligations validation failed', messageAr: 'فشل التحقق من Obligations' },
  MAPPINGS_NOT_FOUND: { code: 'DORA.MAPPINGS_NOT_FOUND', httpStatus: 404, messageEn: 'Mappings not found', messageAr: 'Mappings غير موجود' },
  MAPPINGS_ALREADY_EXISTS: { code: 'DORA.MAPPINGS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Mappings already exists', messageAr: 'Mappings موجود بالفعل' },
  MAPPINGS_VALIDATION_FAILED: { code: 'DORA.MAPPINGS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Mappings validation failed', messageAr: 'فشل التحقق من Mappings' },
  DASHBOARD_NOT_FOUND: { code: 'DORA.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'DORA.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'DORA.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },

  UNAUTHORIZED: { code: 'DORA.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for dora operation', messageAr: 'صلاحيات غير كافية لعملية dora' },
  INVALID_STATE_TRANSITION: { code: 'DORA.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'DORA.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'DORA.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'DORA.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'DORA.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type DoraErrorCode = keyof typeof DORA_ERROR_CODES;
