#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# DOS Platform — local end-to-end bring-up (data plane + build + migrate + PM2)
#
# Prerequisites:
#   - Docker with Compose v2
#   - pnpm (see package.json packageManager)
#   - Node >= 24.14.0 on PATH (see ops/scripts/with-engine-node.sh)
#   - platform/config-center/env/.env.shared with JWT and other non-DB secrets (copy from .env.shared.example)
#
# Usage (from repo root):
#   bash ops/scripts/bring-up-stack.sh --with-docker-db
#   bash ops/scripts/bring-up-stack.sh                    # uses existing DATABASE_URL
#   bash ops/scripts/bring-up-stack.sh --skip-build --with-docker-db
#   SKIP_FRONTEND_HEALTH=1 bash ops/scripts/health-check-all.sh
#
# Flags:
#   --with-docker-db   Start ops/docker/compose.data-plane.yml and write platform/config-center/env/.env.local.docker
#   --skip-build       Skip pnpm build:* steps
#   --skip-migrate     Skip pnpm run migrate
#   --skip-pm2         Skip pm2 start/reload
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WITH_DOCKER_DB=0
SKIP_BUILD=0
SKIP_MIGRATE=0
SKIP_PM2=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-docker-db) WITH_DOCKER_DB=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    --skip-migrate) SKIP_MIGRATE=1 ;;
    --skip-pm2) SKIP_PM2=1 ;;
    -h|--help)
      head -n 35 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
  shift
done

# shellcheck disable=SC1091
source "$REPO_ROOT/ops/scripts/lib/load-env.sh"

COMPOSE_FILE="$REPO_ROOT/ops/docker/compose.data-plane.yml"
COMPOSE_ENV="$REPO_ROOT/ops/docker/data-plane.defaults.env"

if [[ "$WITH_DOCKER_DB" == "1" ]]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "bring-up-stack: docker not found" >&2
    exit 1
  fi
  if [[ ! -f "$COMPOSE_ENV" ]]; then
    echo "bring-up-stack: missing $COMPOSE_ENV" >&2
    exit 1
  fi
  echo "bring-up-stack: starting data plane (Postgres + Redis)..."
  docker compose --env-file "$COMPOSE_ENV" -f "$COMPOSE_FILE" up -d --wait

  # shellcheck disable=SC1090
  set -a
  # shellcheck disable=SC1091
  source "$COMPOSE_ENV"
  set +a

  LOCAL_DOCKER_ENV="$REPO_ROOT/platform/config-center/env/.env.local.docker"
  cat >"$LOCAL_DOCKER_ENV" <<EOF
# Generated by ops/scripts/bring-up-stack.sh --with-docker-db
# Local Docker only. Do not commit. Gitignored via platform/config-center/env/.env.*
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:${REDIS_PORT:-6379}/0
EOF
  echo "bring-up-stack: wrote $LOCAL_DOCKER_ENV"
fi

cd "$REPO_ROOT"
mkdir -p "$REPO_ROOT/logs/pm2"

dos_load_shared_env || true

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "bring-up-stack: DATABASE_URL is not set." >&2
  echo "  Use --with-docker-db or set DATABASE_URL in platform/config-center/env/.env.shared" >&2
  exit 1
fi

echo "bring-up-stack: pnpm install..."
pnpm install --frozen-lockfile 2>/dev/null || pnpm install

ENGINE_WRAP=(bash "$REPO_ROOT/ops/scripts/with-engine-node.sh")

if [[ "$SKIP_BUILD" != "1" ]]; then
  echo "bring-up-stack: build packages..."
  "${ENGINE_WRAP[@]}" pnpm run build:packages
  echo "bring-up-stack: build services..."
  "${ENGINE_WRAP[@]}" pnpm run build:services
  echo "bring-up-stack: build frontend (Angular)..."
  "${ENGINE_WRAP[@]}" pnpm run build:frontend
  echo "bring-up-stack: frontend bundle check (optional hard fail if over limit)..."
  pnpm run frontend:bundle-check || true
else
  echo "bring-up-stack: skipping builds (--skip-build)"
fi

if [[ "$SKIP_MIGRATE" != "1" ]]; then
  echo "bring-up-stack: migrations..."
  dos_load_shared_env || true
  pnpm run migrate
else
  echo "bring-up-stack: skipping migrate (--skip-migrate)"
fi

if [[ "$SKIP_PM2" != "1" ]]; then
  if ! command -v pm2 >/dev/null 2>&1; then
    echo "bring-up-stack: pm2 not found. Install: npm i -g pm2" >&2
    exit 1
  fi
  echo "bring-up-stack: PM2 (ecosystem.all.config.js)..."
  if pm2 describe gateway >/dev/null 2>&1; then
    pm2 reload "$REPO_ROOT/ops/ecosystem.all.config.js"
  else
    pm2 start "$REPO_ROOT/ops/ecosystem.all.config.js"
  fi
else
  echo "bring-up-stack: skipping pm2 (--skip-pm2)"
fi

echo "bring-up-stack: health checks (set SKIP_FRONTEND_HEALTH=1 for local-only)..."
SKIP_FRONTEND_HEALTH="${SKIP_FRONTEND_HEALTH:-}" bash "$REPO_ROOT/ops/scripts/health-check-all.sh" || {
  echo "bring-up-stack: health-check-all reported failures (see above). For local UI-only checks: SKIP_FRONTEND_HEALTH=1 bash ops/scripts/health-check-all.sh" >&2
  exit 1
}

echo "bring-up-stack: done. UI (product-shell): http://127.0.0.1:3000  Gateway: http://127.0.0.1:4000/health"
