import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const INTEGRATIONS_ERROR_CODES = {
  PROVIDERS_NOT_FOUND: { code: 'INTEGRATIONS.PROVIDERS_NOT_FOUND', httpStatus: 404, messageEn: 'Providers not found', messageAr: 'Providers غير موجود' },
  PROVIDERS_ALREADY_EXISTS: { code: 'INTEGRATIONS.PROVIDERS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Providers already exists', messageAr: 'Providers موجود بالفعل' },
  PROVIDERS_VALIDATION_FAILED: { code: 'INTEGRATIONS.PROVIDERS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Providers validation failed', messageAr: 'فشل التحقق من Providers' },
  HEALTH_DASHBOARD_NOT_FOUND: { code: 'INTEGRATIONS.HEALTH_DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Health Dashboard not found', messageAr: 'Health Dashboard غير موجود' },
  HEALTH_DASHBOARD_ALREADY_EXISTS: { code: 'INTEGRATIONS.HEALTH_DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health Dashboard already exists', messageAr: 'Health Dashboard موجود بالفعل' },
  HEALTH_DASHBOARD_VALIDATION_FAILED: { code: 'INTEGRATIONS.HEALTH_DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health Dashboard validation failed', messageAr: 'فشل التحقق من Health Dashboard' },
  TEST_NOT_FOUND: { code: 'INTEGRATIONS.TEST_NOT_FOUND', httpStatus: 404, messageEn: 'Test not found', messageAr: 'Test غير موجود' },
  TEST_ALREADY_EXISTS: { code: 'INTEGRATIONS.TEST_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Test already exists', messageAr: 'Test موجود بالفعل' },
  TEST_VALIDATION_FAILED: { code: 'INTEGRATIONS.TEST_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Test validation failed', messageAr: 'فشل التحقق من Test' },
  TEST_ALL_NOT_FOUND: { code: 'INTEGRATIONS.TEST_ALL_NOT_FOUND', httpStatus: 404, messageEn: 'Test All not found', messageAr: 'Test All غير موجود' },
  TEST_ALL_ALREADY_EXISTS: { code: 'INTEGRATIONS.TEST_ALL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Test All already exists', messageAr: 'Test All موجود بالفعل' },
  TEST_ALL_VALIDATION_FAILED: { code: 'INTEGRATIONS.TEST_ALL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Test All validation failed', messageAr: 'فشل التحقق من Test All' },
  CONFIG_NOT_FOUND: { code: 'INTEGRATIONS.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'INTEGRATIONS.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'INTEGRATIONS.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'INTEGRATIONS.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'INTEGRATIONS.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'INTEGRATIONS.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'INTEGRATIONS.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'INTEGRATIONS.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'INTEGRATIONS.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'INTEGRATIONS.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'INTEGRATIONS.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'INTEGRATIONS.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  DEGRADED_NOT_FOUND: { code: 'INTEGRATIONS.DEGRADED_NOT_FOUND', httpStatus: 404, messageEn: 'Degraded not found', messageAr: 'Degraded غير موجود' },
  DEGRADED_ALREADY_EXISTS: { code: 'INTEGRATIONS.DEGRADED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Degraded already exists', messageAr: 'Degraded موجود بالفعل' },
  DEGRADED_VALIDATION_FAILED: { code: 'INTEGRATIONS.DEGRADED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Degraded validation failed', messageAr: 'فشل التحقق من Degraded' },
  REINDEX_NOT_FOUND: { code: 'INTEGRATIONS.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'INTEGRATIONS.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'INTEGRATIONS.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'INTEGRATIONS.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'INTEGRATIONS.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'INTEGRATIONS.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'INTEGRATIONS.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'INTEGRATIONS.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'INTEGRATIONS.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  STATUS_NOT_FOUND: { code: 'INTEGRATIONS.STATUS_NOT_FOUND', httpStatus: 404, messageEn: 'Status not found', messageAr: 'Status غير موجود' },
  STATUS_ALREADY_EXISTS: { code: 'INTEGRATIONS.STATUS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Status already exists', messageAr: 'Status موجود بالفعل' },
  STATUS_VALIDATION_FAILED: { code: 'INTEGRATIONS.STATUS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Status validation failed', messageAr: 'فشل التحقق من Status' },
  REPORTS_NOT_FOUND: { code: 'INTEGRATIONS.REPORTS_NOT_FOUND', httpStatus: 404, messageEn: 'Reports not found', messageAr: 'Reports غير موجود' },
  REPORTS_ALREADY_EXISTS: { code: 'INTEGRATIONS.REPORTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reports already exists', messageAr: 'Reports موجود بالفعل' },
  REPORTS_VALIDATION_FAILED: { code: 'INTEGRATIONS.REPORTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reports validation failed', messageAr: 'فشل التحقق من Reports' },
  EMBED_TOKEN_NOT_FOUND: { code: 'INTEGRATIONS.EMBED_TOKEN_NOT_FOUND', httpStatus: 404, messageEn: 'Embed Token not found', messageAr: 'Embed Token غير موجود' },
  EMBED_TOKEN_ALREADY_EXISTS: { code: 'INTEGRATIONS.EMBED_TOKEN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Embed Token already exists', messageAr: 'Embed Token موجود بالفعل' },
  EMBED_TOKEN_VALIDATION_FAILED: { code: 'INTEGRATIONS.EMBED_TOKEN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Embed Token validation failed', messageAr: 'فشل التحقق من Embed Token' },

  UNAUTHORIZED: { code: 'INTEGRATIONS.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for integrations operation', messageAr: 'صلاحيات غير كافية لعملية integrations' },
  INVALID_STATE_TRANSITION: { code: 'INTEGRATIONS.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'INTEGRATIONS.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'INTEGRATIONS.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'INTEGRATIONS.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'INTEGRATIONS.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type IntegrationsErrorCode = keyof typeof INTEGRATIONS_ERROR_CODES;
