// ═══════════════════════════════════
// NCA ECC Self-Assessment — DB-driven
// ═══════════════════════════════════

import { shell, bi, esc, fetchTenantName, fetchFrameworks, fetchControls } from './sample-report-shared';

interface DomainRow { en: string; ar: string; c: number; i: number; p: number; g: number; s: number }

/** Demo NCA domain data used when no tenant context is available. */
export function getDemoNcaDoms(): DomainRow[] {
  return [
    { en: "Cybersecurity Governance", ar: "حوكمة الأمن السيبراني", c: 23, i: 18, p: 3, g: 2, s: 82 },
    { en: "Cybersecurity Defense", ar: "الدفاع السيبراني", c: 28, i: 20, p: 5, g: 3, s: 75 },
    { en: "Cybersecurity Resilience", ar: "الصمود السيبراني", c: 22, i: 15, p: 4, g: 3, s: 70 },
    { en: "Third-Party Security", ar: "أمن الأطراف الخارجية", c: 18, i: 14, p: 2, g: 2, s: 80 },
    { en: "ICS/OT Security", ar: "أمن التقنيات التشغيلية", c: 23, i: 12, p: 6, g: 5, s: 58 },
  ];
}

export async function genNcaEcc(m: { title: string; titleAr: string }, tenantId: string | null): Promise<string> {
  let orgEn = "Al-Watan Financial Group";
  let orgAr = "مجموعة الوطن المالية";
  let sectorEn = "Financial Services";
  let sectorAr = "الخدمات المالية";
  let isLive = false;

  let doms: DomainRow[];

  if (tenantId) {
    try {
      const tenantName = await fetchTenantName(tenantId);
      orgEn = tenantName;
      orgAr = tenantName;
      sectorEn = ""; sectorAr = "";

      const frameworks = await fetchFrameworks(tenantId);
      const controls = await fetchControls(tenantId);

      if (frameworks.length > 0) {
        isLive = true;
        doms = frameworks.map(fw => {
          const fwControls = controls.filter(c => c.frameworkCode === fw.code);
          const impl = fwControls.filter(c => c.status === 'active' || c.status === 'implemented').length;
          const partial = fwControls.filter(c => c.status === 'partial' || c.status === 'in_progress').length;
          const gaps = fwControls.length - impl - partial;
          const score = fwControls.length > 0
            ? Math.round(fwControls.reduce((sum, c) => sum + c.effectiveness, 0) / fwControls.length)
            : 0;
          return { en: fw.name, ar: fw.name, c: fwControls.length, i: impl, p: partial, g: gaps, s: score };
        });
      } else {
        doms = getDemoNcaDoms();
      }
    } catch {
      doms = getDemoNcaDoms();
    }
  } else {
    doms = getDemoNcaDoms();
  }

  const totalControls = doms.reduce((a, d) => a + d.c, 0);
  const avg = doms.length > 0 ? Math.round(doms.reduce((a, d) => a + d.s, 0) / doms.length) : 0;
  const impl = doms.reduce((a, d) => a + d.i, 0);
  const part = doms.reduce((a, d) => a + d.p, 0);
  const gaps = totalControls - impl - part;

  const nav = `<div class="nav-bar">
    <a class="nav-pill active" href="#summary">${bi("الملخص التنفيذي", "Executive Summary")}</a>
    <a class="nav-pill" href="#charts">${bi("الرسوم البيانية", "Charts")}</a>
    <a class="nav-pill" href="#domains">${bi("نتائج المجالات", "Domain Scores")}</a>
    <a class="nav-pill" href="#recs">${bi("التوصيات", "Recommendations")}</a>
  </div>`;

  const body = `${nav}<div class="container">
  <div class="rpt-header">
    <div style="display:flex;justify-content:space-between;align-items:start;flex-wrap:wrap;gap:12px">
      <div><h1>${bi(m.titleAr, m.title)}</h1><div class="sub">${bi(`${esc(orgAr)}${sectorAr ? ' — ' + sectorAr : ''}`, `${esc(orgEn)}${sectorEn ? ' — ' + sectorEn : ''}`)}</div></div>
      <span class="sample-badge">${bi(isLive ? "بيانات حية" : "تقرير تجريبي", isLive ? "LIVE DATA" : "SAMPLE REPORT")}</span>
    </div>
    <div class="meta"><span>${totalControls} ${bi("ضابط", "Controls")} x ${doms.length} ${bi("مجالات", "Domains")}</span><span>${bi("أُنشئ بواسطة Shahin-AI", "Generated by Shahin-AI")}</span></div>
  </div>

  <div class="card" id="summary">
    <h2>${bi("الملخص التنفيذي", "Executive Summary")}</h2>
    <div class="co-grid">
      <div><div class="lbl">${bi("المنظمة", "Organization")}</div><div class="val">${esc(orgEn)}</div></div>
      <div><div class="lbl">${bi("تاريخ التقييم", "Assessment Date")}</div><div class="val">${new Date().toISOString().split("T")[0]}</div></div>
    </div>
    <div class="kpi-row">
      <div class="kpi"><div class="n">${avg}%</div><div class="l">${bi("النتيجة الإجمالية", "Overall Score")}</div></div>
      <div class="kpi"><div class="n">${impl}</div><div class="l">${bi("مُطبّق", "Implemented")}</div></div>
      <div class="kpi"><div class="n">${part}</div><div class="l">${bi("جزئي", "Partial")}</div></div>
      <div class="kpi"><div class="n" style="color:#dc2626">${gaps}</div><div class="l">${bi("فجوات", "Gaps")}</div></div>
    </div>
  </div>

  <div class="card" id="charts">
    <h2>${bi("الرسوم البيانية", "Visual Analytics")}</h2>
    <div class="chart-row">
      <div class="chart-box"><h3>${bi("نتائج المجالات — رادار", "Domain Scores — Radar")}</h3><canvas id="radarChart"></canvas></div>
      <div class="chart-box"><h3>${bi("حالة الضوابط — دائري", "Control Status — Doughnut")}</h3><canvas id="doughnutChart"></canvas></div>
    </div>
    <div class="chart-row">
      <div class="chart-box" style="grid-column:1/-1"><h3>${bi("نتائج المجالات — أعمدة", "Domain Scores — Bar Chart")}</h3><canvas id="barChart"></canvas></div>
    </div>
  </div>

  <div class="card" id="domains">
    <h2>${bi("نتائج المجالات", "Domain Scores")}</h2>
    <table>
      <thead><tr><th>${bi("المجال", "Domain")}</th><th>${bi("الضوابط", "Controls")}</th><th>${bi("مُطبّق", "Impl.")}</th><th>${bi("جزئي", "Partial")}</th><th>${bi("فجوات", "Gaps")}</th><th>${bi("النتيجة", "Score")}</th><th>${bi("التقدم", "Progress")}</th></tr></thead>
      <tbody>${doms.map(d => `<tr><td><strong>${bi(esc(d.ar), esc(d.en))}</strong></td><td>${d.c}</td><td>${d.i}</td><td>${d.p}</td><td>${d.g}</td><td><span class="score ${d.s >= 75 ? 's-hi' : d.s >= 60 ? 's-md' : 's-lo'}">${d.s}%</span></td><td style="min-width:100px"><div class="bar-bg"><div class="bar-fg ${d.s >= 75 ? 'bg' : d.s >= 60 ? 'by' : 'br'}" style="width:${d.s}%"></div></div></td></tr>`).join("")}</tbody>
    </table>
  </div>

  <div class="card" id="recs">
    <h2>${bi("توصيات مدعومة بالذكاء الاصطناعي", "AI-Powered Recommendations")}</h2>
    <p style="font-size:13px;color:#64748b">${bi("بناءً على نتائج التقييم، نوصي بالتركيز على المجالات ذات النتائج الأدنى لتحسين وضع الامتثال العام.", "Based on the assessment results, we recommend focusing on the lowest-scoring domains to improve overall compliance posture.")}</p>
    ${doms.filter(d => d.s < 70).length > 0 ? `
    <h3 style="margin-top:14px">${bi("مجالات تحتاج تحسين", "Domains Requiring Improvement")}</h3>
    <ul style="padding:0 20px;font-size:13px;margin-bottom:14px">
      ${doms.filter(d => d.s < 70).map(d => `<li>${bi(esc(d.ar), esc(d.en))} — ${d.s}% (${d.g} ${bi("فجوات", "gaps")})</li>`).join("")}
    </ul>` : `<p style="font-size:13px;color:#16a34a;margin-top:10px">${bi("جميع المجالات فوق 70% — أداء ممتاز!", "All domains above 70% — excellent performance!")}</p>`}
  </div>
</div>`;

  const chartScript = `<script>
document.addEventListener('DOMContentLoaded',function(){
  var labels=${JSON.stringify(doms.map(d => d.en))};
  var scores=${JSON.stringify(doms.map(d => d.s))};
  new Chart(document.getElementById('radarChart'),{type:'radar',data:{labels:labels,datasets:[{label:'Score %',data:scores,backgroundColor:'rgba(14,165,233,0.2)',borderColor:'#0ea5e9',pointBackgroundColor:'#0369a1',pointRadius:5}]},options:{responsive:true,scales:{r:{min:0,max:100,ticks:{stepSize:20}}},plugins:{legend:{display:false}}}});
  new Chart(document.getElementById('doughnutChart'),{type:'doughnut',data:{labels:['Implemented','Partial','Gaps'],datasets:[{data:[${impl},${part},${gaps}],backgroundColor:['#16a34a','#f59e0b','#dc2626']}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}});
  new Chart(document.getElementById('barChart'),{type:'bar',data:{labels:labels,datasets:[{label:'Score %',data:scores,backgroundColor:scores.map(function(s){return s>=75?'#16a34a':s>=60?'#f59e0b':'#dc2626'}),borderRadius:6}]},options:{responsive:true,scales:{y:{min:0,max:100}},plugins:{legend:{display:false}}}});
});
<\/script>`;

  return shell(m.title, m.titleAr, body, chartScript, isLive);
}
