import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const NOTIFICATION_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'NOTIFICATION.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'NOTIFICATION.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'NOTIFICATION.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'NOTIFICATION.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'NOTIFICATION.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'NOTIFICATION.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'NOTIFICATION.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'NOTIFICATION.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'NOTIFICATION.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  DELIVERY_ANALYTICS_NOT_FOUND: { code: 'NOTIFICATION.DELIVERY_ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Delivery Analytics not found', messageAr: 'Delivery Analytics غير موجود' },
  DELIVERY_ANALYTICS_ALREADY_EXISTS: { code: 'NOTIFICATION.DELIVERY_ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Delivery Analytics already exists', messageAr: 'Delivery Analytics موجود بالفعل' },
  DELIVERY_ANALYTICS_VALIDATION_FAILED: { code: 'NOTIFICATION.DELIVERY_ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Delivery Analytics validation failed', messageAr: 'فشل التحقق من Delivery Analytics' },
  FAILED_NOT_FOUND: { code: 'NOTIFICATION.FAILED_NOT_FOUND', httpStatus: 404, messageEn: 'Failed not found', messageAr: 'Failed غير موجود' },
  FAILED_ALREADY_EXISTS: { code: 'NOTIFICATION.FAILED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Failed already exists', messageAr: 'Failed موجود بالفعل' },
  FAILED_VALIDATION_FAILED: { code: 'NOTIFICATION.FAILED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Failed validation failed', messageAr: 'فشل التحقق من Failed' },
  REINDEX_NOT_FOUND: { code: 'NOTIFICATION.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'NOTIFICATION.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'NOTIFICATION.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'NOTIFICATION.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'NOTIFICATION.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'NOTIFICATION.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  PREFERENCES_NOT_FOUND: { code: 'NOTIFICATION.PREFERENCES_NOT_FOUND', httpStatus: 404, messageEn: 'Preferences not found', messageAr: 'Preferences غير موجود' },
  PREFERENCES_ALREADY_EXISTS: { code: 'NOTIFICATION.PREFERENCES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Preferences already exists', messageAr: 'Preferences موجود بالفعل' },
  PREFERENCES_VALIDATION_FAILED: { code: 'NOTIFICATION.PREFERENCES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Preferences validation failed', messageAr: 'فشل التحقق من Preferences' },
  DIAGNOSTICS_NOT_FOUND: { code: 'NOTIFICATION.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'NOTIFICATION.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'NOTIFICATION.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  READ_ALL_NOT_FOUND: { code: 'NOTIFICATION.READ_ALL_NOT_FOUND', httpStatus: 404, messageEn: 'Read All not found', messageAr: 'Read All غير موجود' },
  READ_ALL_ALREADY_EXISTS: { code: 'NOTIFICATION.READ_ALL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Read All already exists', messageAr: 'Read All موجود بالفعل' },
  READ_ALL_VALIDATION_FAILED: { code: 'NOTIFICATION.READ_ALL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Read All validation failed', messageAr: 'فشل التحقق من Read All' },
  PUSH_TOKEN_NOT_FOUND: { code: 'NOTIFICATION.PUSH_TOKEN_NOT_FOUND', httpStatus: 404, messageEn: 'Push Token not found', messageAr: 'Push Token غير موجود' },
  PUSH_TOKEN_ALREADY_EXISTS: { code: 'NOTIFICATION.PUSH_TOKEN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Push Token already exists', messageAr: 'Push Token موجود بالفعل' },
  PUSH_TOKEN_VALIDATION_FAILED: { code: 'NOTIFICATION.PUSH_TOKEN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Push Token validation failed', messageAr: 'فشل التحقق من Push Token' },
  SMART_DIGEST_NOT_FOUND: { code: 'NOTIFICATION.SMART_DIGEST_NOT_FOUND', httpStatus: 404, messageEn: 'Smart Digest not found', messageAr: 'Smart Digest غير موجود' },
  SMART_DIGEST_ALREADY_EXISTS: { code: 'NOTIFICATION.SMART_DIGEST_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Smart Digest already exists', messageAr: 'Smart Digest موجود بالفعل' },
  SMART_DIGEST_VALIDATION_FAILED: { code: 'NOTIFICATION.SMART_DIGEST_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Smart Digest validation failed', messageAr: 'فشل التحقق من Smart Digest' },
  AI_PRIORITIZE_NOT_FOUND: { code: 'NOTIFICATION.AI_PRIORITIZE_NOT_FOUND', httpStatus: 404, messageEn: 'Ai Prioritize not found', messageAr: 'Ai Prioritize غير موجود' },
  AI_PRIORITIZE_ALREADY_EXISTS: { code: 'NOTIFICATION.AI_PRIORITIZE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Ai Prioritize already exists', messageAr: 'Ai Prioritize موجود بالفعل' },
  AI_PRIORITIZE_VALIDATION_FAILED: { code: 'NOTIFICATION.AI_PRIORITIZE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Ai Prioritize validation failed', messageAr: 'فشل التحقق من Ai Prioritize' },
  ANALYTICS_NOT_FOUND: { code: 'NOTIFICATION.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'NOTIFICATION.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'NOTIFICATION.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },

  UNAUTHORIZED: { code: 'NOTIFICATION.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for notification operation', messageAr: 'صلاحيات غير كافية لعملية notification' },
  INVALID_STATE_TRANSITION: { code: 'NOTIFICATION.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'NOTIFICATION.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'NOTIFICATION.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'NOTIFICATION.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'NOTIFICATION.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type NotificationErrorCode = keyof typeof NOTIFICATION_ERROR_CODES;
