/**
 * widgets — Module Security Registration
 * Auto-generated by scripts/codegen/generate-manifest-security.ts
 * Extracted from 2 route files, 0 unique permissions.
 *
 * DO NOT EDIT permissions extracted from routes. Add new permissions below the generated block.
 */

import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const WIDGETS_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'widgets.record.read', resourceType: 'record', actionType: 'read', descriptionEn: 'View widgets records', descriptionAr: 'عرض سجلات widgets', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'widgets.record.write', resourceType: 'record', actionType: 'write', descriptionEn: 'Create/edit widgets records', descriptionAr: 'إنشاء/تعديل سجلات widgets', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'widgets.record.delete', resourceType: 'record', actionType: 'delete', descriptionEn: 'Delete widgets records', descriptionAr: 'حذف سجلات widgets', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'widgets.record.approve', resourceType: 'record', actionType: 'approve', descriptionEn: 'Approve widgets records', descriptionAr: 'اعتماد سجلات widgets', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'widgets.manage', resourceType: 'module', actionType: 'manage', descriptionEn: 'Manage widgets settings', descriptionAr: 'إدارة إعدادات widgets', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'widgets.record.export', resourceType: 'record', actionType: 'export', descriptionEn: 'Export widgets data', descriptionAr: 'تصدير بيانات widgets', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const WIDGETS_ROLES: ModuleRole[] = [
  { roleCode: 'widgets.executive_owner', archetype: 'executive_owner', nameEn: 'widgets executive owner', nameAr: 'executive_owner', descriptionEn: 'executive owner for widgets', descriptionAr: 'executive_owner', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'widgets.module_lead', archetype: 'module_lead', nameEn: 'widgets module lead', nameAr: 'module_lead', descriptionEn: 'module lead for widgets', descriptionAr: 'module_lead', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'widgets.approver', archetype: 'approver', nameEn: 'widgets approver', nameAr: 'approver', descriptionEn: 'approver for widgets', descriptionAr: 'approver', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'required', defaultScope: 'own' },
  { roleCode: 'widgets.operator', archetype: 'operator', nameEn: 'widgets operator', nameAr: 'operator', descriptionEn: 'operator for widgets', descriptionAr: 'operator', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'widgets.contributor', archetype: 'contributor', nameEn: 'widgets contributor', nameAr: 'contributor', descriptionEn: 'contributor for widgets', descriptionAr: 'contributor', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'widgets.reviewer', archetype: 'reviewer', nameEn: 'widgets reviewer', nameAr: 'reviewer', descriptionEn: 'reviewer for widgets', descriptionAr: 'reviewer', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'widgets.auditor', archetype: 'auditor', nameEn: 'widgets auditor', nameAr: 'auditor', descriptionEn: 'auditor for widgets', descriptionAr: 'auditor', isDefault: false, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'widgets.viewer', archetype: 'viewer', nameEn: 'widgets viewer', nameAr: 'viewer', descriptionEn: 'viewer for widgets', descriptionAr: 'viewer', isDefault: true, isSystem: false, isGlobal: false, permissions: [], authorityLevel: 'optional', defaultScope: 'own' },
];

export const WIDGETS_ACTIONS: ModuleAction[] = [
  { actionCode: 'widgets.record.read', labelEn: 'View widgets', labelAr: 'عرض الأدوات', requiredPermissions: ['widgets.record.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'widgets.record.write', labelEn: 'Create/edit widgets', labelAr: 'إنشاء/تعديل الأدوات', requiredPermissions: ['widgets.record.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'widgets.record.delete', labelEn: 'Delete widgets', labelAr: 'حذف الأدوات', requiredPermissions: ['widgets.record.delete'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: false, bulkSafe: false, externalExposure: false },
  { actionCode: 'widgets.record.approve', labelEn: 'Approve widget publication', labelAr: 'اعتماد نشر الأداة', requiredPermissions: ['widgets.record.approve'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'widgets.manage', labelEn: 'Manage widget settings', labelAr: 'إدارة إعدادات الأدوات', requiredPermissions: ['widgets.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'widgets.record.export', labelEn: 'Export widget data', labelAr: 'تصدير بيانات الأدوات', requiredPermissions: ['widgets.record.export'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: true, bulkSafe: true, externalExposure: false },
];
