import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const ASSET_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'ASSET.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'ASSET.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'ASSET.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  CLASSIFICATIONS_NOT_FOUND: { code: 'ASSET.CLASSIFICATIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Classifications not found', messageAr: 'Classifications غير موجود' },
  CLASSIFICATIONS_ALREADY_EXISTS: { code: 'ASSET.CLASSIFICATIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Classifications already exists', messageAr: 'Classifications موجود بالفعل' },
  CLASSIFICATIONS_VALIDATION_FAILED: { code: 'ASSET.CLASSIFICATIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Classifications validation failed', messageAr: 'فشل التحقق من Classifications' },
  RECALCULATE_CRITICALITY_NOT_FOUND: { code: 'ASSET.RECALCULATE_CRITICALITY_NOT_FOUND', httpStatus: 404, messageEn: 'Recalculate Criticality not found', messageAr: 'Recalculate Criticality غير موجود' },
  RECALCULATE_CRITICALITY_ALREADY_EXISTS: { code: 'ASSET.RECALCULATE_CRITICALITY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Recalculate Criticality already exists', messageAr: 'Recalculate Criticality موجود بالفعل' },
  RECALCULATE_CRITICALITY_VALIDATION_FAILED: { code: 'ASSET.RECALCULATE_CRITICALITY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Recalculate Criticality validation failed', messageAr: 'فشل التحقق من Recalculate Criticality' },
  STATS_NOT_FOUND: { code: 'ASSET.STATS_NOT_FOUND', httpStatus: 404, messageEn: 'Stats not found', messageAr: 'Stats غير موجود' },
  STATS_ALREADY_EXISTS: { code: 'ASSET.STATS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Stats already exists', messageAr: 'Stats موجود بالفعل' },
  STATS_VALIDATION_FAILED: { code: 'ASSET.STATS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Stats validation failed', messageAr: 'فشل التحقق من Stats' },
  DISTRIBUTION_NOT_FOUND: { code: 'ASSET.DISTRIBUTION_NOT_FOUND', httpStatus: 404, messageEn: 'Distribution not found', messageAr: 'Distribution غير موجود' },
  DISTRIBUTION_ALREADY_EXISTS: { code: 'ASSET.DISTRIBUTION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Distribution already exists', messageAr: 'Distribution موجود بالفعل' },
  DISTRIBUTION_VALIDATION_FAILED: { code: 'ASSET.DISTRIBUTION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Distribution validation failed', messageAr: 'فشل التحقق من Distribution' },
  ASSIGN_NOT_FOUND: { code: 'ASSET.ASSIGN_NOT_FOUND', httpStatus: 404, messageEn: 'Assign not found', messageAr: 'Assign غير موجود' },
  ASSIGN_ALREADY_EXISTS: { code: 'ASSET.ASSIGN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Assign already exists', messageAr: 'Assign موجود بالفعل' },
  ASSIGN_VALIDATION_FAILED: { code: 'ASSET.ASSIGN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Assign validation failed', messageAr: 'فشل التحقق من Assign' },
  RECALCULATE_NOT_FOUND: { code: 'ASSET.RECALCULATE_NOT_FOUND', httpStatus: 404, messageEn: 'Recalculate not found', messageAr: 'Recalculate غير موجود' },
  RECALCULATE_ALREADY_EXISTS: { code: 'ASSET.RECALCULATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Recalculate already exists', messageAr: 'Recalculate موجود بالفعل' },
  RECALCULATE_VALIDATION_FAILED: { code: 'ASSET.RECALCULATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Recalculate validation failed', messageAr: 'فشل التحقق من Recalculate' },
  UPSTREAM_NOT_FOUND: { code: 'ASSET.UPSTREAM_NOT_FOUND', httpStatus: 404, messageEn: 'Upstream not found', messageAr: 'Upstream غير موجود' },
  UPSTREAM_ALREADY_EXISTS: { code: 'ASSET.UPSTREAM_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Upstream already exists', messageAr: 'Upstream موجود بالفعل' },
  UPSTREAM_VALIDATION_FAILED: { code: 'ASSET.UPSTREAM_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Upstream validation failed', messageAr: 'فشل التحقق من Upstream' },
  DOWNSTREAM_NOT_FOUND: { code: 'ASSET.DOWNSTREAM_NOT_FOUND', httpStatus: 404, messageEn: 'Downstream not found', messageAr: 'Downstream غير موجود' },
  DOWNSTREAM_ALREADY_EXISTS: { code: 'ASSET.DOWNSTREAM_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Downstream already exists', messageAr: 'Downstream موجود بالفعل' },
  DOWNSTREAM_VALIDATION_FAILED: { code: 'ASSET.DOWNSTREAM_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Downstream validation failed', messageAr: 'فشل التحقق من Downstream' },
  BLAST_RADIUS_NOT_FOUND: { code: 'ASSET.BLAST_RADIUS_NOT_FOUND', httpStatus: 404, messageEn: 'Blast Radius not found', messageAr: 'Blast Radius غير موجود' },
  BLAST_RADIUS_ALREADY_EXISTS: { code: 'ASSET.BLAST_RADIUS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Blast Radius already exists', messageAr: 'Blast Radius موجود بالفعل' },
  BLAST_RADIUS_VALIDATION_FAILED: { code: 'ASSET.BLAST_RADIUS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Blast Radius validation failed', messageAr: 'فشل التحقق من Blast Radius' },
  CYCLES_NOT_FOUND: { code: 'ASSET.CYCLES_NOT_FOUND', httpStatus: 404, messageEn: 'Cycles not found', messageAr: 'Cycles غير موجود' },
  CYCLES_ALREADY_EXISTS: { code: 'ASSET.CYCLES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Cycles already exists', messageAr: 'Cycles موجود بالفعل' },
  CYCLES_VALIDATION_FAILED: { code: 'ASSET.CYCLES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Cycles validation failed', messageAr: 'فشل التحقق من Cycles' },
  DIAGNOSTICS_NOT_FOUND: { code: 'ASSET.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'ASSET.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'ASSET.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  KPIS_NOT_FOUND: { code: 'ASSET.KPIS_NOT_FOUND', httpStatus: 404, messageEn: 'Kpis not found', messageAr: 'Kpis غير موجود' },
  KPIS_ALREADY_EXISTS: { code: 'ASSET.KPIS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Kpis already exists', messageAr: 'Kpis موجود بالفعل' },
  KPIS_VALIDATION_FAILED: { code: 'ASSET.KPIS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Kpis validation failed', messageAr: 'فشل التحقق من Kpis' },
  LIFECYCLE_NOT_FOUND: { code: 'ASSET.LIFECYCLE_NOT_FOUND', httpStatus: 404, messageEn: 'Lifecycle not found', messageAr: 'Lifecycle غير موجود' },
  LIFECYCLE_ALREADY_EXISTS: { code: 'ASSET.LIFECYCLE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Lifecycle already exists', messageAr: 'Lifecycle موجود بالفعل' },
  LIFECYCLE_VALIDATION_FAILED: { code: 'ASSET.LIFECYCLE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Lifecycle validation failed', messageAr: 'فشل التحقق من Lifecycle' },
  CLASSIFICATION_NOT_FOUND: { code: 'ASSET.CLASSIFICATION_NOT_FOUND', httpStatus: 404, messageEn: 'Classification not found', messageAr: 'Classification غير موجود' },
  CLASSIFICATION_ALREADY_EXISTS: { code: 'ASSET.CLASSIFICATION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Classification already exists', messageAr: 'Classification موجود بالفعل' },
  CLASSIFICATION_VALIDATION_FAILED: { code: 'ASSET.CLASSIFICATION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Classification validation failed', messageAr: 'فشل التحقق من Classification' },

  UNAUTHORIZED: { code: 'ASSET.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for asset operation', messageAr: 'صلاحيات غير كافية لعملية asset' },
  INVALID_STATE_TRANSITION: { code: 'ASSET.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'ASSET.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'ASSET.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'ASSET.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'ASSET.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type AssetErrorCode = keyof typeof ASSET_ERROR_CODES;
