import { RedisStreamEventBus } from '@dos/event-backbone';
import { logger } from '@dos/platform-core/observability';
import { ServiceClient } from '@dos/service-client';
import { recordAudit } from '../adapters/audit.adapter';
import { sendNotification } from '../adapters/notification.adapter';
import * as widgetService from '../domain/widget.service';
import { publishWidgetCreated } from './publisher';

const workflowClient = new ServiceClient({
  baseUrl: process.env.WORKFLOW_SERVICE_URL || 'http://127.0.0.1:4004',
  timeout: 5000,
  retries: 1,
});

/**
 * Wave 2C: Register module-level event handlers from modules/dashboard.
 * Wrapped in try/catch so the service starts even if the module is unavailable.
 */
export function registerModuleConsumers(eventBus: RedisStreamEventBus): void {
  try {
    const moduleSubscribers = require(
      '../../../modules/dashboard/dist/dashboard/events/dashboard.subscribers'
    );

    if (typeof moduleSubscribers.subscribeAll === 'function') {
      const busAdapter = {
        on(event: string, handler: (payload: Record<string, unknown>) => Promise<void>) {
          eventBus.subscribe(event, async (envelope) => {
            try {
              await handler(envelope as unknown as Record<string, unknown>);
            } catch (err) {
              logger.error(`[dashboard-widgets-service] Module event handler failed for ${event}`, { error: err });
            }
          });
        },
      };
      moduleSubscribers.subscribeAll(busAdapter);
      logger.info('[dashboard-widgets-service] Module event subscribers registered');
    } else if (typeof moduleSubscribers.registerDashboardSubscribers === 'function') {
      moduleSubscribers.registerDashboardSubscribers();
      logger.info('[dashboard-widgets-service] Module dashboard subscribers registered via registerDashboardSubscribers');
    }
  } catch (err) {
    logger.warn('[dashboard-widgets-service] Module event subscribers not available, skipping', { error: err });
  }
}

export function registerConsumers(eventBus: RedisStreamEventBus): void {
  eventBus.subscribe('analytics.dashboard.created', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[dashboard-widgets-service] Processing analytics.dashboard.created: Provision default widgets for new dashboard`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const created = await widgetService.create(tenantId, {
          title: (payload.title as string) || `Auto: analytics.dashboard.created - ${envelope.eventId.slice(0, 8)}`,
          type: (payload.type as string) || (payload.category as string) || 'auto-generated',
          data_source: (payload.dataSource as string) || 'auto',
          category: (payload.category as string) || 'auto-provisioned',
        });
        logger.info(`[dashboard-widgets-service] Auto-created widget`, { id: created.widget_id, tenantId });
        await publishWidgetCreated(tenantId, created.widget_id, { source: 'analytics.dashboard.created', autoGenerated: true }, envelope.userId);
        if (envelope.userId) {
          sendNotification(tenantId, envelope.userId, 'Widget Created', `A new widget was auto-created from analytics.dashboard.created`, 'info', { entityId: created.widget_id }).catch(() => {});
        }

      await recordAudit(
        tenantId,
        'provisionDefaultWidgets',
        'widget',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'analytics.dashboard.created', payload },
      );
    } catch (err) {
      logger.error(`[dashboard-widgets-service] Failed to process analytics.dashboard.created`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('risk.updated', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[dashboard-widgets-service] Processing risk.updated: Refresh risk-related widgets`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const entityId = (payload.entityId as string) || (payload.widget_id as string);
      if (entityId) {
        const existing = await widgetService.getById(tenantId, entityId);
        if (existing) {
          await widgetService.update(tenantId, entityId, {
            category: 'risk-refreshed',
          });
          logger.info(`[dashboard-widgets-service] refreshRiskWidgets: updated widget`, { entityId, tenantId });
        }
      } else {
        const items = await widgetService.list(tenantId, { pageSize: 10 });
        for (const item of items.data) {
          await widgetService.update(tenantId, (item as any).widget_id, {
            category: 'risk-refreshed',
          });
        }
        logger.info(`[dashboard-widgets-service] refreshRiskWidgets: batch-reviewed widget items`, { count: items.data.length, tenantId });
      }

      await recordAudit(
        tenantId,
        'refreshRiskWidgets',
        'widget',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'risk.updated', payload },
      );
    } catch (err) {
      logger.error(`[dashboard-widgets-service] Failed to process risk.updated`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('compliance.assessed', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[dashboard-widgets-service] Processing compliance.assessed: Refresh compliance-related widgets`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const entityId = (payload.entityId as string) || (payload.widget_id as string);
      if (entityId) {
        const existing = await widgetService.getById(tenantId, entityId);
        if (existing) {
          await widgetService.update(tenantId, entityId, {
            category: 'compliance-refreshed',
          });
          logger.info(`[dashboard-widgets-service] refreshComplianceWidgets: updated widget`, { entityId, tenantId });
        }
      } else {
        const items = await widgetService.list(tenantId, { pageSize: 10 });
        for (const item of items.data) {
          await widgetService.update(tenantId, (item as any).widget_id, {
            category: 'compliance-refreshed',
          });
        }
        logger.info(`[dashboard-widgets-service] refreshComplianceWidgets: batch-reviewed widget items`, { count: items.data.length, tenantId });
      }

      await recordAudit(
        tenantId,
        'refreshComplianceWidgets',
        'widget',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'compliance.assessed', payload },
      );
    } catch (err) {
      logger.error(`[dashboard-widgets-service] Failed to process compliance.assessed`, { eventId: envelope.eventId, error: err });
    }
  });
}
