/**
 * Compliance AR Labels — AGRC-OS
 */
import { ComplianceLabels } from './compliance.labels.en';

export const COMPLIANCE_AR: ComplianceLabels = {
  // Page
  pageTitle: 'الالتزام',
  pageSubtitle: 'مساحة عمل الالتزام — الأطر، المجالات، الالتزامات، الفجوات، المعالجة، وجاهزية التدقيق',

  // Tabs
  overview: 'نظرة عامة على الالتزام',
  frameworks: 'الأطر',
  domains: 'المجالات',
  obligations: 'الالتزامات',
  gapAssessment: 'تقييم الفجوات',
  roadmap: 'خارطة طريق الالتزام',

  // KPI
  overallScore: 'درجة الالتزام',
  activeFrameworks: 'الأطر النشطة',
  openGaps: 'الفجوات المفتوحة',
  criticalGaps: 'الفجوات الحرجة',
  obligationsCovered: 'الالتزامات المغطاة',
  controlsMapped: 'الضوابط المربوطة',
  evidenceCoverage: 'تغطية الأدلة',
  evidenceQualityTierA: 'أدلة المستوى أ',
  evidenceFreshness: 'حداثة الأدلة',
  auditReadiness: 'جاهزية التدقيق',
  overdueActions: 'الإجراءات المتأخرة',

  // Overview sections
  frameworkPosture: 'وضع الأطر',
  domainHealth: 'صحة المجالات',
  priorityIssues: 'قضايا ذات أولوية',
  recentAssessments: 'التقييمات الأخيرة',
  complianceTrend: 'اتجاه درجة الالتزام',

  // Table columns
  code: 'الكود',
  name: 'الاسم',
  status: 'الحالة',
  owner: 'المسؤول',
  scope: 'النطاق',
  score: 'الدرجة',
  domain: 'المجال',
  framework: 'الإطار',
  coverage: 'التغطية',
  severity: 'الخطورة',
  dueDate: 'تاريخ الاستحقاق',
  description: 'الوصف',
  obligation: 'الالتزام',
  controls: 'الضوابط',
  evidence: 'الأدلة',
  category: 'الفئة',
  action: 'إجراء',
  implemented: 'مطبّق',
  lastReview: 'آخر مراجعة',
  domainsCount: 'المجالات',
  obligationsCount: 'الالتزامات',
  mappedControls: 'الضوابط المربوطة',

  // Framework
  comparison: 'مقارنة الأطر',
  frameworkDetails: 'تفاصيل الإطار',
  openFramework: 'فتح الإطار',
  editScope: 'تعديل النطاق',
  assignOwner: 'تعيين المسؤول',
  runAssessment: 'تشغيل التقييم',
  exportReport: 'تصدير التقرير',
  enableDisable: 'تفعيل/تعطيل',
  regulator: 'الجهة المنظمة',
  version: 'الإصدار',
  applicableScope: 'النطاق المطبّق',
  activeDomains: 'المجالات النشطة',
  gapCount: 'عدد الفجوات',
  overdueIssues: 'القضايا المتأخرة',
  launchGap: 'بدء تقييم الفجوات',
  generateActionPlan: 'إنشاء خطة عمل',

  // Domain
  domainDetails: 'تفاصيل المجال',
  heatView: 'عرض حراري',
  tableView: 'عرض جدول',
  domainChain: 'سلسلة المجال',
  linkedObligations: 'الالتزامات المرتبطة',
  linkedControls: 'الضوابط المرتبطة',
  linkedEvidence: 'الأدلة المرتبطة',
  activeRemediation: 'المعالجات النشطة',
  recentActivity: 'النشاط الأخير',

  // Obligation
  obligationDetails: 'تفاصيل الالتزام',
  coverageMatrix: 'مصفوفة التغطية',
  fullText: 'النص الكامل',
  rationale: 'الأساس المنطقي / التفسير',
  auditNotes: 'ملاحظات التدقيق',
  commentsHistory: 'التعليقات / السجل',
  mapControl: 'ربط ضابط',
  mapEvidence: 'ربط دليل',
  createTask: 'إنشاء مهمة معالجة',

  // Gap
  gapDetails: 'تفاصيل الفجوة',
  prioritizationBoard: 'لوحة الأولويات',
  assessmentHistory: 'سجل التقييمات',
  cause: 'السبب',
  impact: 'التأثير',
  sourceAssessment: 'تقييم المصدر',
  missingControl: 'ضابط مفقود / ضعيف',
  missingEvidence: 'دليل مفقود / قديم',
  remediationPlan: 'خطة المعالجة',
  targetDate: 'التاريخ المستهدف',
  validationEvidence: 'أدلة التحقق',
  approvalTrail: 'سجل الاعتمادات',
  acceptRisk: 'قبول المخاطرة / استثناء',
  startRemediation: 'بدء المعالجة',
  attachEvidence: 'إرفاق دليل',
  markReady: 'تحديد جاهز للتحقق',
  closeGap: 'إغلاق الفجوة',
  createRemediation: 'إنشاء معالجة',

  // Roadmap
  currentWave: 'الموجة الحالية',
  nextMilestone: 'المعلم التالي',
  totalTasks: 'إجمالي المهام',
  completedTasks: 'المهام المكتملة',
  completion: 'الإنجاز',
  targetReadiness: 'تاريخ الجاهزية المستهدف',
  phase: 'المرحلة',
  milestone: 'المعلم',
  tasks: 'المهام',
  dependencies: 'الاعتمادات',
  blockedItems: 'العناصر المحجوبة',
  forecast: 'التوقع / التأثير',
  expectedScore: 'درجة الالتزام المتوقعة',
  expectedReadiness: 'جاهزية التدقيق المتوقعة',
  keyBlockers: 'العوائق الرئيسية',
  generateRoadmap: 'إنشاء خارطة الطريق',

  // Audit readiness
  readinessScore: 'درجة الجاهزية',
  tested: 'مختبرة',
  withEvidence: 'مع أدلة',
  fullyReady: 'جاهزة بالكامل',

  // Actions
  addFramework: 'إضافة / تفعيل إطار',
  startAssessment: 'بدء التقييم',
  exportCompliance: 'تصدير تقرير الالتزام',
  openAuditReadiness: 'فتح جاهزية التدقيق',
  filterByFramework: 'تصفية حسب الإطار',
  allFrameworks: 'جميع الأطر',
  details: 'التفاصيل',
  close: 'إغلاق',
  changeStatus: 'تغيير الحالة',
  exportItem: 'تصدير العنصر',

  // Empty states
  emptyFrameworks: 'لا توجد أطر نشطة بعد',
  emptyFrameworksCta: 'فعّل الأطر من نطاق الإعداد',
  emptyDomains: 'ستظهر مجالات الإطار بعد تهيئة الأطر',
  emptyDomainsCta: 'إعادة تشغيل بذرة الإطار',
  emptyObligations: 'لا توجد تقييمات التزامات بعد',
  emptyObligationsCta: 'بدء أول تقييم التزام',
  emptyGaps: 'لم يتم اكتشاف فجوات مفتوحة',
  emptyGapsSub: 'قد يعني ذلك تغطية قوية أو عدم تشغيل التقييم بعد',
  emptyGapsCta: 'مراجعة تغطية التقييم',
  emptyRoadmap: 'لم يتم إنشاء خارطة طريق الالتزام بعد',
  emptyRoadmapCta: 'إنشاء خارطة طريق من الفجوات المفتوحة',

  // Misc
  loading: 'جارٍ التحميل...',
  noData: 'لا توجد بيانات',
  search: 'بحث...',
  bySeverity: 'حسب الخطورة',
  byFramework: 'حسب الإطار',
  byDomain: 'حسب المجال',
  byOwner: 'حسب المسؤول',
  byDueDate: 'حسب تاريخ الاستحقاق',
};
