-- dos:extracted-from: ops/migrations/tenant/118_incident_vendor_bcp_config_tables.sql
-- dos:supersedes-checksum: 5409221c280b107c952fccc8259f964edc47f4ed57c77b3b0a377f7e8a5fc171
-- dos:owning-module: asset
-- dos:tables: asset_classification_scheme, asset_ownership_matrix
-- dos:statement-count: 2
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
-- ═══ ASSET MODULE CONFIG ═══

CREATE TABLE IF NOT EXISTS asset_classification_scheme (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classification_code VARCHAR(30) NOT NULL UNIQUE,
  classification_label VARCHAR(100) NOT NULL,
  classification_level INT NOT NULL,
  description TEXT,
  handling_requirements TEXT,
  access_controls TEXT,
  color VARCHAR(7) DEFAULT '#000000',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS asset_ownership_matrix (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_type VARCHAR(50) NOT NULL,
  default_owner_role VARCHAR(50),
  default_custodian_role VARCHAR(50),
  review_frequency_days INT DEFAULT 365,
  classification_required BOOLEAN DEFAULT TRUE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(asset_type)
);
