import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const ISSUES_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'ISSUES.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'ISSUES.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'ISSUES.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'ISSUES.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'ISSUES.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'ISSUES.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'ISSUES.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'ISSUES.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'ISSUES.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  REINDEX_NOT_FOUND: { code: 'ISSUES.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'ISSUES.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'ISSUES.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'ISSUES.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'ISSUES.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'ISSUES.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  ANALYTICS_NOT_FOUND: { code: 'ISSUES.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'ISSUES.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'ISSUES.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  ALERTS_NOT_FOUND: { code: 'ISSUES.ALERTS_NOT_FOUND', httpStatus: 404, messageEn: 'Alerts not found', messageAr: 'Alerts غير موجود' },
  ALERTS_ALREADY_EXISTS: { code: 'ISSUES.ALERTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Alerts already exists', messageAr: 'Alerts موجود بالفعل' },
  ALERTS_VALIDATION_FAILED: { code: 'ISSUES.ALERTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Alerts validation failed', messageAr: 'فشل التحقق من Alerts' },
  MAINTENANCE_NOT_FOUND: { code: 'ISSUES.MAINTENANCE_NOT_FOUND', httpStatus: 404, messageEn: 'Maintenance not found', messageAr: 'Maintenance غير موجود' },
  MAINTENANCE_ALREADY_EXISTS: { code: 'ISSUES.MAINTENANCE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maintenance already exists', messageAr: 'Maintenance موجود بالفعل' },
  MAINTENANCE_VALIDATION_FAILED: { code: 'ISSUES.MAINTENANCE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maintenance validation failed', messageAr: 'فشل التحقق من Maintenance' },
  DIAGNOSTICS_NOT_FOUND: { code: 'ISSUES.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'ISSUES.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'ISSUES.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  SEARCH_NOT_FOUND: { code: 'ISSUES.SEARCH_NOT_FOUND', httpStatus: 404, messageEn: 'Search not found', messageAr: 'Search غير موجود' },
  SEARCH_ALREADY_EXISTS: { code: 'ISSUES.SEARCH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Search already exists', messageAr: 'Search موجود بالفعل' },
  SEARCH_VALIDATION_FAILED: { code: 'ISSUES.SEARCH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Search validation failed', messageAr: 'فشل التحقق من Search' },
  DASHBOARD_NOT_FOUND: { code: 'ISSUES.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'ISSUES.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'ISSUES.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  TRENDS_NOT_FOUND: { code: 'ISSUES.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'ISSUES.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'ISSUES.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  SLA_COMPLIANCE_NOT_FOUND: { code: 'ISSUES.SLA_COMPLIANCE_NOT_FOUND', httpStatus: 404, messageEn: 'Sla Compliance not found', messageAr: 'Sla Compliance غير موجود' },
  SLA_COMPLIANCE_ALREADY_EXISTS: { code: 'ISSUES.SLA_COMPLIANCE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Sla Compliance already exists', messageAr: 'Sla Compliance موجود بالفعل' },
  SLA_COMPLIANCE_VALIDATION_FAILED: { code: 'ISSUES.SLA_COMPLIANCE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Sla Compliance validation failed', messageAr: 'فشل التحقق من Sla Compliance' },
  ROOT_CAUSE_DISTRIBUTION_NOT_FOUND: { code: 'ISSUES.ROOT_CAUSE_DISTRIBUTION_NOT_FOUND', httpStatus: 404, messageEn: 'Root Cause Distribution not found', messageAr: 'Root Cause Distribution غير موجود' },
  ROOT_CAUSE_DISTRIBUTION_ALREADY_EXISTS: { code: 'ISSUES.ROOT_CAUSE_DISTRIBUTION_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Root Cause Distribution already exists', messageAr: 'Root Cause Distribution موجود بالفعل' },
  ROOT_CAUSE_DISTRIBUTION_VALIDATION_FAILED: { code: 'ISSUES.ROOT_CAUSE_DISTRIBUTION_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Root Cause Distribution validation failed', messageAr: 'فشل التحقق من Root Cause Distribution' },
  MTTR_NOT_FOUND: { code: 'ISSUES.MTTR_NOT_FOUND', httpStatus: 404, messageEn: 'Mttr not found', messageAr: 'Mttr غير موجود' },
  MTTR_ALREADY_EXISTS: { code: 'ISSUES.MTTR_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Mttr already exists', messageAr: 'Mttr موجود بالفعل' },
  MTTR_VALIDATION_FAILED: { code: 'ISSUES.MTTR_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Mttr validation failed', messageAr: 'فشل التحقق من Mttr' },

  UNAUTHORIZED: { code: 'ISSUES.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for issues operation', messageAr: 'صلاحيات غير كافية لعملية issues' },
  INVALID_STATE_TRANSITION: { code: 'ISSUES.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'ISSUES.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'ISSUES.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'ISSUES.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'ISSUES.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type IssuesErrorCode = keyof typeof ISSUES_ERROR_CODES;
