/**
 * knowledge — Module Security Registration
 * Permissions, roles, and actions for the knowledge module.
 * Follows the governance reference pattern with dot-notation permission codes.
 */

import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const KNOWLEDGE_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'knowledge.article.read', resourceType: 'article', actionType: 'read', descriptionEn: 'View knowledge articles', descriptionAr: 'عرض مقالات المعرفة', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'knowledge.article.write', resourceType: 'article', actionType: 'write', descriptionEn: 'Create and update knowledge articles', descriptionAr: 'إنشاء وتحديث مقالات المعرفة', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'knowledge.article.publish', resourceType: 'article', actionType: 'approve', descriptionEn: 'Publish and approve knowledge articles', descriptionAr: 'نشر واعتماد مقالات المعرفة', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'knowledge.article.archive', resourceType: 'article', actionType: 'manage', descriptionEn: 'Archive knowledge articles', descriptionAr: 'أرشفة مقالات المعرفة', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'knowledge.article.delete', resourceType: 'article', actionType: 'delete', descriptionEn: 'Delete knowledge articles', descriptionAr: 'حذف مقالات المعرفة', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const KNOWLEDGE_ROLES: ModuleRole[] = [
  { roleCode: 'knowledge.executive_owner', archetype: 'executive_owner', nameEn: 'Knowledge Executive Owner', nameAr: 'المالك التنفيذي للمعرفة', descriptionEn: 'Executive owner for the knowledge module', descriptionAr: 'المالك التنفيذي لوحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read', 'knowledge.article.write', 'knowledge.article.publish', 'knowledge.article.archive', 'knowledge.article.delete'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'knowledge.module_lead', archetype: 'module_lead', nameEn: 'Knowledge Module Lead', nameAr: 'قائد وحدة المعرفة', descriptionEn: 'Module lead for the knowledge module', descriptionAr: 'قائد وحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read', 'knowledge.article.write', 'knowledge.article.publish', 'knowledge.article.archive', 'knowledge.article.delete'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'knowledge.approver', archetype: 'approver', nameEn: 'Knowledge Approver', nameAr: 'معتمد المعرفة', descriptionEn: 'Approver for knowledge articles', descriptionAr: 'معتمد مقالات المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read', 'knowledge.article.publish'], authorityLevel: 'required', defaultScope: 'own' },
  { roleCode: 'knowledge.operator', archetype: 'operator', nameEn: 'Knowledge Operator', nameAr: 'مشغل المعرفة', descriptionEn: 'Operator for the knowledge module', descriptionAr: 'مشغل وحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read', 'knowledge.article.write', 'knowledge.article.archive'], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'knowledge.contributor', archetype: 'contributor', nameEn: 'Knowledge Contributor', nameAr: 'مساهم المعرفة', descriptionEn: 'Contributor for the knowledge module', descriptionAr: 'مساهم في وحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read', 'knowledge.article.write'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'knowledge.reviewer', archetype: 'reviewer', nameEn: 'Knowledge Reviewer', nameAr: 'مراجع المعرفة', descriptionEn: 'Reviewer for the knowledge module', descriptionAr: 'مراجع وحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'knowledge.auditor', archetype: 'auditor', nameEn: 'Knowledge Auditor', nameAr: 'مدقق المعرفة', descriptionEn: 'Auditor for the knowledge module', descriptionAr: 'مدقق وحدة المعرفة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'knowledge.viewer', archetype: 'viewer', nameEn: 'Knowledge Viewer', nameAr: 'عارض المعرفة', descriptionEn: 'Read-only viewer for the knowledge module', descriptionAr: 'عارض للقراءة فقط لوحدة المعرفة', isDefault: true, isSystem: false, isGlobal: false, permissions: ['knowledge.article.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const KNOWLEDGE_ACTIONS: ModuleAction[] = [
  { actionCode: 'knowledge.article.read', labelEn: 'View article', labelAr: 'عرض المقال', requiredPermissions: ['knowledge.article.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'knowledge.article.write', labelEn: 'Create/update article', labelAr: 'إنشاء/تحديث المقال', requiredPermissions: ['knowledge.article.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'knowledge.article.publish', labelEn: 'Publish article', labelAr: 'نشر المقال', requiredPermissions: ['knowledge.article.publish'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: true, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'knowledge.article.archive', labelEn: 'Archive article', labelAr: 'أرشفة المقال', requiredPermissions: ['knowledge.article.archive'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'knowledge.article.delete', labelEn: 'Delete article', labelAr: 'حذف المقال', requiredPermissions: ['knowledge.article.delete'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: false, bulkSafe: false, externalExposure: false },
];
