import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const BCP_ERROR_CODES = {
  BIA_NOT_FOUND: { code: 'BCP.BIA_NOT_FOUND', httpStatus: 404, messageEn: 'Bia not found', messageAr: 'Bia غير موجود' },
  BIA_ALREADY_EXISTS: { code: 'BCP.BIA_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Bia already exists', messageAr: 'Bia موجود بالفعل' },
  BIA_VALIDATION_FAILED: { code: 'BCP.BIA_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Bia validation failed', messageAr: 'فشل التحقق من Bia' },
  EXERCISES_NOT_FOUND: { code: 'BCP.EXERCISES_NOT_FOUND', httpStatus: 404, messageEn: 'Exercises not found', messageAr: 'Exercises غير موجود' },
  EXERCISES_ALREADY_EXISTS: { code: 'BCP.EXERCISES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Exercises already exists', messageAr: 'Exercises موجود بالفعل' },
  EXERCISES_VALIDATION_FAILED: { code: 'BCP.EXERCISES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Exercises validation failed', messageAr: 'فشل التحقق من Exercises' },
  CRISIS_COMM_NOT_FOUND: { code: 'BCP.CRISIS_COMM_NOT_FOUND', httpStatus: 404, messageEn: 'Crisis Comm not found', messageAr: 'Crisis Comm غير موجود' },
  CRISIS_COMM_ALREADY_EXISTS: { code: 'BCP.CRISIS_COMM_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Crisis Comm already exists', messageAr: 'Crisis Comm موجود بالفعل' },
  CRISIS_COMM_VALIDATION_FAILED: { code: 'BCP.CRISIS_COMM_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Crisis Comm validation failed', messageAr: 'فشل التحقق من Crisis Comm' },
  RECOVERY_STRATEGIES_NOT_FOUND: { code: 'BCP.RECOVERY_STRATEGIES_NOT_FOUND', httpStatus: 404, messageEn: 'Recovery Strategies not found', messageAr: 'Recovery Strategies غير موجود' },
  RECOVERY_STRATEGIES_ALREADY_EXISTS: { code: 'BCP.RECOVERY_STRATEGIES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Recovery Strategies already exists', messageAr: 'Recovery Strategies موجود بالفعل' },
  RECOVERY_STRATEGIES_VALIDATION_FAILED: { code: 'BCP.RECOVERY_STRATEGIES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Recovery Strategies validation failed', messageAr: 'فشل التحقق من Recovery Strategies' },
  ACTIVATE_NOT_FOUND: { code: 'BCP.ACTIVATE_NOT_FOUND', httpStatus: 404, messageEn: 'Activate not found', messageAr: 'Activate غير موجود' },
  ACTIVATE_ALREADY_EXISTS: { code: 'BCP.ACTIVATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Activate already exists', messageAr: 'Activate موجود بالفعل' },
  ACTIVATE_VALIDATION_FAILED: { code: 'BCP.ACTIVATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Activate validation failed', messageAr: 'فشل التحقق من Activate' },
  ACTIVATIONS_NOT_FOUND: { code: 'BCP.ACTIVATIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Activations not found', messageAr: 'Activations غير موجود' },
  ACTIVATIONS_ALREADY_EXISTS: { code: 'BCP.ACTIVATIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Activations already exists', messageAr: 'Activations موجود بالفعل' },
  ACTIVATIONS_VALIDATION_FAILED: { code: 'BCP.ACTIVATIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Activations validation failed', messageAr: 'فشل التحقق من Activations' },
  RECOVERY_STEPS_NOT_FOUND: { code: 'BCP.RECOVERY_STEPS_NOT_FOUND', httpStatus: 404, messageEn: 'Recovery Steps not found', messageAr: 'Recovery Steps غير موجود' },
  RECOVERY_STEPS_ALREADY_EXISTS: { code: 'BCP.RECOVERY_STEPS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Recovery Steps already exists', messageAr: 'Recovery Steps موجود بالفعل' },
  RECOVERY_STEPS_VALIDATION_FAILED: { code: 'BCP.RECOVERY_STEPS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Recovery Steps validation failed', messageAr: 'فشل التحقق من Recovery Steps' },
  DEACTIVATE_NOT_FOUND: { code: 'BCP.DEACTIVATE_NOT_FOUND', httpStatus: 404, messageEn: 'Deactivate not found', messageAr: 'Deactivate غير موجود' },
  DEACTIVATE_ALREADY_EXISTS: { code: 'BCP.DEACTIVATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Deactivate already exists', messageAr: 'Deactivate موجود بالفعل' },
  DEACTIVATE_VALIDATION_FAILED: { code: 'BCP.DEACTIVATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Deactivate validation failed', messageAr: 'فشل التحقق من Deactivate' },
  DEPENDENCY_MAPS_NOT_FOUND: { code: 'BCP.DEPENDENCY_MAPS_NOT_FOUND', httpStatus: 404, messageEn: 'Dependency Maps not found', messageAr: 'Dependency Maps غير موجود' },
  DEPENDENCY_MAPS_ALREADY_EXISTS: { code: 'BCP.DEPENDENCY_MAPS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dependency Maps already exists', messageAr: 'Dependency Maps موجود بالفعل' },
  DEPENDENCY_MAPS_VALIDATION_FAILED: { code: 'BCP.DEPENDENCY_MAPS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dependency Maps validation failed', messageAr: 'فشل التحقق من Dependency Maps' },
  MATURITY_NOT_FOUND: { code: 'BCP.MATURITY_NOT_FOUND', httpStatus: 404, messageEn: 'Maturity not found', messageAr: 'Maturity غير موجود' },
  MATURITY_ALREADY_EXISTS: { code: 'BCP.MATURITY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maturity already exists', messageAr: 'Maturity موجود بالفعل' },
  MATURITY_VALIDATION_FAILED: { code: 'BCP.MATURITY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maturity validation failed', messageAr: 'فشل التحقق من Maturity' },
  SPOF_NOT_FOUND: { code: 'BCP.SPOF_NOT_FOUND', httpStatus: 404, messageEn: 'Spof not found', messageAr: 'Spof غير موجود' },
  SPOF_ALREADY_EXISTS: { code: 'BCP.SPOF_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Spof already exists', messageAr: 'Spof موجود بالفعل' },
  SPOF_VALIDATION_FAILED: { code: 'BCP.SPOF_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Spof validation failed', messageAr: 'فشل التحقق من Spof' },
  INCIDENT_LEARNING_NOT_FOUND: { code: 'BCP.INCIDENT_LEARNING_NOT_FOUND', httpStatus: 404, messageEn: 'Incident Learning not found', messageAr: 'Incident Learning غير موجود' },
  INCIDENT_LEARNING_ALREADY_EXISTS: { code: 'BCP.INCIDENT_LEARNING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Incident Learning already exists', messageAr: 'Incident Learning موجود بالفعل' },
  INCIDENT_LEARNING_VALIDATION_FAILED: { code: 'BCP.INCIDENT_LEARNING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Incident Learning validation failed', messageAr: 'فشل التحقق من Incident Learning' },
  BUSINESS_CHANGE_IMPACT_NOT_FOUND: { code: 'BCP.BUSINESS_CHANGE_IMPACT_NOT_FOUND', httpStatus: 404, messageEn: 'Business Change Impact not found', messageAr: 'Business Change Impact غير موجود' },
  BUSINESS_CHANGE_IMPACT_ALREADY_EXISTS: { code: 'BCP.BUSINESS_CHANGE_IMPACT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Business Change Impact already exists', messageAr: 'Business Change Impact موجود بالفعل' },
  BUSINESS_CHANGE_IMPACT_VALIDATION_FAILED: { code: 'BCP.BUSINESS_CHANGE_IMPACT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Business Change Impact validation failed', messageAr: 'فشل التحقق من Business Change Impact' },
  ACTIVE_NOT_FOUND: { code: 'BCP.ACTIVE_NOT_FOUND', httpStatus: 404, messageEn: 'Active not found', messageAr: 'Active غير موجود' },
  ACTIVE_ALREADY_EXISTS: { code: 'BCP.ACTIVE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Active already exists', messageAr: 'Active موجود بالفعل' },
  ACTIVE_VALIDATION_FAILED: { code: 'BCP.ACTIVE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Active validation failed', messageAr: 'فشل التحقق من Active' },
  DASHBOARD_NOT_FOUND: { code: 'BCP.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'BCP.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'BCP.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },

  UNAUTHORIZED: { code: 'BCP.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for bcp operation', messageAr: 'صلاحيات غير كافية لعملية bcp' },
  INVALID_STATE_TRANSITION: { code: 'BCP.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'BCP.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'BCP.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'BCP.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'BCP.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type BcpErrorCode = keyof typeof BCP_ERROR_CODES;
