import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const REPORTING_ERROR_CODES = {
  TEMPLATES_NOT_FOUND: { code: 'REPORTING.TEMPLATES_NOT_FOUND', httpStatus: 404, messageEn: 'Templates not found', messageAr: 'Templates غير موجود' },
  TEMPLATES_ALREADY_EXISTS: { code: 'REPORTING.TEMPLATES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Templates already exists', messageAr: 'Templates موجود بالفعل' },
  TEMPLATES_VALIDATION_FAILED: { code: 'REPORTING.TEMPLATES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Templates validation failed', messageAr: 'فشل التحقق من Templates' },
  GENERATE_NOT_FOUND: { code: 'REPORTING.GENERATE_NOT_FOUND', httpStatus: 404, messageEn: 'Generate not found', messageAr: 'Generate غير موجود' },
  GENERATE_ALREADY_EXISTS: { code: 'REPORTING.GENERATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Generate already exists', messageAr: 'Generate موجود بالفعل' },
  GENERATE_VALIDATION_FAILED: { code: 'REPORTING.GENERATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Generate validation failed', messageAr: 'فشل التحقق من Generate' },
  GENERATE_PPTX_NOT_FOUND: { code: 'REPORTING.GENERATE_PPTX_NOT_FOUND', httpStatus: 404, messageEn: 'Generate Pptx not found', messageAr: 'Generate Pptx غير موجود' },
  GENERATE_PPTX_ALREADY_EXISTS: { code: 'REPORTING.GENERATE_PPTX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Generate Pptx already exists', messageAr: 'Generate Pptx موجود بالفعل' },
  GENERATE_PPTX_VALIDATION_FAILED: { code: 'REPORTING.GENERATE_PPTX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Generate Pptx validation failed', messageAr: 'فشل التحقق من Generate Pptx' },
  SCHEDULES_NOT_FOUND: { code: 'REPORTING.SCHEDULES_NOT_FOUND', httpStatus: 404, messageEn: 'Schedules not found', messageAr: 'Schedules غير موجود' },
  SCHEDULES_ALREADY_EXISTS: { code: 'REPORTING.SCHEDULES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Schedules already exists', messageAr: 'Schedules موجود بالفعل' },
  SCHEDULES_VALIDATION_FAILED: { code: 'REPORTING.SCHEDULES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Schedules validation failed', messageAr: 'فشل التحقق من Schedules' },
  BOARD_REPORT_NOT_FOUND: { code: 'REPORTING.BOARD_REPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Board Report not found', messageAr: 'Board Report غير موجود' },
  BOARD_REPORT_ALREADY_EXISTS: { code: 'REPORTING.BOARD_REPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Board Report already exists', messageAr: 'Board Report موجود بالفعل' },
  BOARD_REPORT_VALIDATION_FAILED: { code: 'REPORTING.BOARD_REPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Board Report validation failed', messageAr: 'فشل التحقق من Board Report' },
  SCHEDULE_NOT_FOUND: { code: 'REPORTING.SCHEDULE_NOT_FOUND', httpStatus: 404, messageEn: 'Schedule not found', messageAr: 'Schedule غير موجود' },
  SCHEDULE_ALREADY_EXISTS: { code: 'REPORTING.SCHEDULE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Schedule already exists', messageAr: 'Schedule موجود بالفعل' },
  SCHEDULE_VALIDATION_FAILED: { code: 'REPORTING.SCHEDULE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Schedule validation failed', messageAr: 'فشل التحقق من Schedule' },
  MATURITY_SCORECARD_NOT_FOUND: { code: 'REPORTING.MATURITY_SCORECARD_NOT_FOUND', httpStatus: 404, messageEn: 'Maturity Scorecard not found', messageAr: 'Maturity Scorecard غير موجود' },
  MATURITY_SCORECARD_ALREADY_EXISTS: { code: 'REPORTING.MATURITY_SCORECARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Maturity Scorecard already exists', messageAr: 'Maturity Scorecard موجود بالفعل' },
  MATURITY_SCORECARD_VALIDATION_FAILED: { code: 'REPORTING.MATURITY_SCORECARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Maturity Scorecard validation failed', messageAr: 'فشل التحقق من Maturity Scorecard' },
  EVIDENCE_PACK_EXPORT_NOT_FOUND: { code: 'REPORTING.EVIDENCE_PACK_EXPORT_NOT_FOUND', httpStatus: 404, messageEn: 'Evidence Pack Export not found', messageAr: 'Evidence Pack Export غير موجود' },
  EVIDENCE_PACK_EXPORT_ALREADY_EXISTS: { code: 'REPORTING.EVIDENCE_PACK_EXPORT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Evidence Pack Export already exists', messageAr: 'Evidence Pack Export موجود بالفعل' },
  EVIDENCE_PACK_EXPORT_VALIDATION_FAILED: { code: 'REPORTING.EVIDENCE_PACK_EXPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Evidence Pack Export validation failed', messageAr: 'فشل التحقق من Evidence Pack Export' },
  BOARD_VIEW_NOT_FOUND: { code: 'REPORTING.BOARD_VIEW_NOT_FOUND', httpStatus: 404, messageEn: 'Board View not found', messageAr: 'Board View غير موجود' },
  BOARD_VIEW_ALREADY_EXISTS: { code: 'REPORTING.BOARD_VIEW_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Board View already exists', messageAr: 'Board View موجود بالفعل' },
  BOARD_VIEW_VALIDATION_FAILED: { code: 'REPORTING.BOARD_VIEW_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Board View validation failed', messageAr: 'فشل التحقق من Board View' },
  CATALOG_NOT_FOUND: { code: 'REPORTING.CATALOG_NOT_FOUND', httpStatus: 404, messageEn: 'Catalog not found', messageAr: 'Catalog غير موجود' },
  CATALOG_ALREADY_EXISTS: { code: 'REPORTING.CATALOG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Catalog already exists', messageAr: 'Catalog موجود بالفعل' },
  CATALOG_VALIDATION_FAILED: { code: 'REPORTING.CATALOG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Catalog validation failed', messageAr: 'فشل التحقق من Catalog' },
  SUMMARY_NOT_FOUND: { code: 'REPORTING.SUMMARY_NOT_FOUND', httpStatus: 404, messageEn: 'Summary not found', messageAr: 'Summary غير موجود' },
  SUMMARY_ALREADY_EXISTS: { code: 'REPORTING.SUMMARY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Summary already exists', messageAr: 'Summary موجود بالفعل' },
  SUMMARY_VALIDATION_FAILED: { code: 'REPORTING.SUMMARY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Summary validation failed', messageAr: 'فشل التحقق من Summary' },
  TRENDS_NOT_FOUND: { code: 'REPORTING.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'REPORTING.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'REPORTING.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  ANOMALIES_NOT_FOUND: { code: 'REPORTING.ANOMALIES_NOT_FOUND', httpStatus: 404, messageEn: 'Anomalies not found', messageAr: 'Anomalies غير موجود' },
  ANOMALIES_ALREADY_EXISTS: { code: 'REPORTING.ANOMALIES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Anomalies already exists', messageAr: 'Anomalies موجود بالفعل' },
  ANOMALIES_VALIDATION_FAILED: { code: 'REPORTING.ANOMALIES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Anomalies validation failed', messageAr: 'فشل التحقق من Anomalies' },
  FRAMEWORK_CARDS_NOT_FOUND: { code: 'REPORTING.FRAMEWORK_CARDS_NOT_FOUND', httpStatus: 404, messageEn: 'Framework Cards not found', messageAr: 'Framework Cards غير موجود' },
  FRAMEWORK_CARDS_ALREADY_EXISTS: { code: 'REPORTING.FRAMEWORK_CARDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Framework Cards already exists', messageAr: 'Framework Cards موجود بالفعل' },
  FRAMEWORK_CARDS_VALIDATION_FAILED: { code: 'REPORTING.FRAMEWORK_CARDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Framework Cards validation failed', messageAr: 'فشل التحقق من Framework Cards' },
  SHARES_NOT_FOUND: { code: 'REPORTING.SHARES_NOT_FOUND', httpStatus: 404, messageEn: 'Shares not found', messageAr: 'Shares غير موجود' },
  SHARES_ALREADY_EXISTS: { code: 'REPORTING.SHARES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Shares already exists', messageAr: 'Shares موجود بالفعل' },
  SHARES_VALIDATION_FAILED: { code: 'REPORTING.SHARES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Shares validation failed', messageAr: 'فشل التحقق من Shares' },

  UNAUTHORIZED: { code: 'REPORTING.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for reporting operation', messageAr: 'صلاحيات غير كافية لعملية reporting' },
  INVALID_STATE_TRANSITION: { code: 'REPORTING.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'REPORTING.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'REPORTING.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'REPORTING.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'REPORTING.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type ReportingErrorCode = keyof typeof REPORTING_ERROR_CODES;
