import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const RISK_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'risk.record.read', resourceType: 'record', actionType: 'read', descriptionEn: 'Read risk records', descriptionAr: 'قراءة سجلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.write', resourceType: 'record', actionType: 'write', descriptionEn: 'Create and update risk records', descriptionAr: 'إنشاء وتحديث سجلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.delete', resourceType: 'record', actionType: 'delete', descriptionEn: 'Delete risk records', descriptionAr: 'حذف سجلات المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.configure', resourceType: 'record', actionType: 'configure', descriptionEn: 'Configure risk module settings', descriptionAr: 'تكوين إعدادات وحدة المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.approve', resourceType: 'record', actionType: 'approve', descriptionEn: 'Approve risk records and assessments', descriptionAr: 'الموافقة على سجلات المخاطر والتقييمات', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: ['risk:approve'] },
  { permissionCode: 'risk.record.submit', resourceType: 'record', actionType: 'submit', descriptionEn: 'Submit risk records for review', descriptionAr: 'تقديم سجلات المخاطر للمراجعة', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.review', resourceType: 'record', actionType: 'review', descriptionEn: 'Review risk records', descriptionAr: 'مراجعة سجلات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.close', resourceType: 'record', actionType: 'close', descriptionEn: 'Close risk records', descriptionAr: 'إغلاق سجلات المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.update', resourceType: 'record', actionType: 'update', descriptionEn: 'Update risk record status and details', descriptionAr: 'تحديث حالة وتفاصيل سجل المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.record.delegate', resourceType: 'record', actionType: 'delegate', descriptionEn: 'Delegate risk ownership or approval', descriptionAr: 'تفويض ملكية المخاطر أو الموافقة', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.treatment.assign', resourceType: 'treatment', actionType: 'assign', descriptionEn: 'Assign treatment plans to risks', descriptionAr: 'تعيين خطط المعالجة للمخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.treatment.approve', resourceType: 'treatment', actionType: 'approve', descriptionEn: 'Approve treatment plans', descriptionAr: 'الموافقة على خطط المعالجة', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.kri.manage', resourceType: 'kri', actionType: 'manage', descriptionEn: 'Manage KRI definitions and thresholds', descriptionAr: 'إدارة تعريفات ومعايير مؤشرات المخاطر الرئيسية', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.assessment.conduct', resourceType: 'assessment', actionType: 'conduct', descriptionEn: 'Conduct risk assessments', descriptionAr: 'إجراء تقييمات المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.assessment.approve', resourceType: 'assessment', actionType: 'approve', descriptionEn: 'Approve risk assessments', descriptionAr: 'الموافقة على تقييمات المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.diagnostics.view', resourceType: 'diagnostics', actionType: 'view', descriptionEn: 'View risk diagnostics and health', descriptionAr: 'عرض تشخيصات وصحة المخاطر', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'risk.admin.manage', resourceType: 'admin', actionType: 'manage', descriptionEn: 'Manage risk module administration', descriptionAr: 'إدارة إدارة وحدة المخاطر', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const RISK_ROLES: ModuleRole[] = [
  { roleCode: 'risk.executive_owner', archetype: 'executive_owner', nameEn: 'Risk Executive Owner', nameAr: 'المالك التنفيذي للمخاطر', descriptionEn: 'Executive owner for risk module with full authority', descriptionAr: 'المالك التنفيذي لوحدة المخاطر مع صلاحية كاملة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.delete', 'risk.record.configure', 'risk.record.approve', 'risk.record.submit', 'risk.record.review', 'risk.record.close', 'risk.record.update', 'risk.record.delegate', 'risk.treatment.assign', 'risk.treatment.approve', 'risk.kri.manage', 'risk.assessment.conduct', 'risk.assessment.approve', 'risk.diagnostics.view', 'risk.admin.manage'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'risk.module_lead', archetype: 'module_lead', nameEn: 'Risk Module Lead', nameAr: 'قائد وحدة المخاطر', descriptionEn: 'Module lead managing risk operations', descriptionAr: 'قائد الوحدة يدير عمليات المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.delete', 'risk.record.approve', 'risk.record.submit', 'risk.record.review', 'risk.record.close', 'risk.record.update', 'risk.record.delegate', 'risk.treatment.assign', 'risk.treatment.approve', 'risk.kri.manage', 'risk.assessment.conduct', 'risk.assessment.approve', 'risk.diagnostics.view'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'risk.approver', archetype: 'approver', nameEn: 'Risk Approver', nameAr: 'معتمد المخاطر', descriptionEn: 'Approver for risk records and assessments', descriptionAr: 'معتمد سجلات المخاطر والتقييمات', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.approve', 'risk.record.review', 'risk.treatment.approve', 'risk.assessment.approve', 'risk.diagnostics.view'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'risk.operator', archetype: 'operator', nameEn: 'Risk Operator', nameAr: 'مشغّل المخاطر', descriptionEn: 'Operator managing day-to-day risk activities', descriptionAr: 'مشغّل يدير أنشطة المخاطر اليومية', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.submit', 'risk.record.update', 'risk.treatment.assign', 'risk.kri.manage', 'risk.assessment.conduct', 'risk.diagnostics.view'], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'risk.contributor', archetype: 'contributor', nameEn: 'Risk Contributor', nameAr: 'مساهم المخاطر', descriptionEn: 'Contributor to risk assessments and treatments', descriptionAr: 'مساهم في تقييمات ومعالجات المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.write', 'risk.record.submit', 'risk.assessment.conduct'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.reviewer', archetype: 'reviewer', nameEn: 'Risk Reviewer', nameAr: 'مراجع المخاطر', descriptionEn: 'Reviewer of risk records and assessments', descriptionAr: 'مراجع سجلات المخاطر والتقييمات', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.record.review', 'risk.diagnostics.view'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.auditor', archetype: 'auditor', nameEn: 'Risk Auditor', nameAr: 'مدقق المخاطر', descriptionEn: 'Auditor with read-only access to risk data', descriptionAr: 'مدقق مع وصول للقراءة فقط لبيانات المخاطر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['risk.record.read', 'risk.diagnostics.view'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'risk.viewer', archetype: 'viewer', nameEn: 'Risk Viewer', nameAr: 'عارض المخاطر', descriptionEn: 'Read-only viewer of risk data', descriptionAr: 'عارض بيانات المخاطر للقراءة فقط', isDefault: true, isSystem: false, isGlobal: false, permissions: ['risk.record.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const RISK_ACTIONS: ModuleAction[] = [
  { actionCode: 'risk.record.read', labelEn: 'Read risk record', labelAr: 'قراءة سجل المخاطر', requiredPermissions: ['risk.record.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: true, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'risk.record.write', labelEn: 'Create/update risk record', labelAr: 'إنشاء/تحديث سجل المخاطر', requiredPermissions: ['risk.record.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: true, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.delete', labelEn: 'Delete risk record', labelAr: 'حذف سجل المخاطر', requiredPermissions: ['risk.record.delete'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: true, requiresApproval: true, auditable: true, reversible: false, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.configure', labelEn: 'Configure risk settings', labelAr: 'تكوين إعدادات المخاطر', requiredPermissions: ['risk.record.configure'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.approve', labelEn: 'Approve risk record', labelAr: 'الموافقة على سجل المخاطر', requiredPermissions: ['risk.record.approve'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.submit', labelEn: 'Submit risk for review', labelAr: 'تقديم المخاطر للمراجعة', requiredPermissions: ['risk.record.submit'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.review', labelEn: 'Review risk record', labelAr: 'مراجعة سجل المخاطر', requiredPermissions: ['risk.record.review'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: true, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.close', labelEn: 'Close risk record', labelAr: 'إغلاق سجل المخاطر', requiredPermissions: ['risk.record.close'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: true, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.record.delegate', labelEn: 'Delegate risk ownership', labelAr: 'تفويض ملكية المخاطر', requiredPermissions: ['risk.record.delegate'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.treatment.assign', labelEn: 'Assign treatment plan', labelAr: 'تعيين خطة المعالجة', requiredPermissions: ['risk.treatment.assign'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: true, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.treatment.approve', labelEn: 'Approve treatment plan', labelAr: 'الموافقة على خطة المعالجة', requiredPermissions: ['risk.treatment.approve'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.assessment.conduct', labelEn: 'Conduct risk assessment', labelAr: 'إجراء تقييم المخاطر', requiredPermissions: ['risk.assessment.conduct'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: true, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.assessment.approve', labelEn: 'Approve risk assessment', labelAr: 'الموافقة على تقييم المخاطر', requiredPermissions: ['risk.assessment.approve'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: true, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'risk.admin.manage', labelEn: 'Manage risk administration', labelAr: 'إدارة إدارة المخاطر', requiredPermissions: ['risk.admin.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
];
