import { PolicyTemplateVar, PolicyTemplate } from './policy-template.types';
import { safeQuery } from "@dos/db";

export const V: Record<string, PolicyTemplateVar> = {
  ORG_NAME: { key: '{{ORG_NAME}}', label_en: 'Organization Name', label_ar: 'اسم المنظمة', default_value: '', source: 'tenant.org_name' },
  ORG_NAME_AR: { key: '{{ORG_NAME_AR}}', label_en: 'Organization Name (Arabic)', label_ar: 'اسم المنظمة بالعربي', default_value: '', source: 'tenant.org_name_ar' },
  INDUSTRY: { key: '{{INDUSTRY}}', label_en: 'Industry', label_ar: 'القطاع', default_value: '', source: 'tenant.industry' },
  EFFECTIVE_DATE: { key: '{{EFFECTIVE_DATE}}', label_en: 'Effective Date', label_ar: 'تاريخ السريان', default_value: '', source: 'auto.today' },
  REVIEW_DATE: { key: '{{REVIEW_DATE}}', label_en: 'Next Review Date', label_ar: 'تاريخ المراجعة القادم', default_value: '', source: 'auto.next_year' },
  CISO_NAME: { key: '{{CISO_NAME}}', label_en: 'CISO Name', label_ar: 'اسم مسؤول أمن المعلومات', default_value: '[CISO Name]', source: 'manual' },
  DPO_NAME: { key: '{{DPO_NAME}}', label_en: 'DPO Name', label_ar: 'اسم مسؤول حماية البيانات', default_value: '[DPO Name]', source: 'manual' },
  CEO_NAME: { key: '{{CEO_NAME}}', label_en: 'CEO Name', label_ar: 'اسم الرئيس التنفيذي', default_value: '[CEO Name]', source: 'manual' },
  COUNTRY: { key: '{{COUNTRY}}', label_en: 'Country', label_ar: 'الدولة', default_value: 'Kingdom of Saudi Arabia', source: 'auto.country' },
  REGULATOR: { key: '{{REGULATOR}}', label_en: 'Primary Regulator', label_ar: 'الجهة التنظيمية الرئيسية', default_value: 'NCA', source: 'tenant.regulator' },
};

export const ALL_SECTORS = ['SEC-KSA-GOV-MIN','SEC-KSA-GOV-AUTH','SEC-KSA-FIN-BANK','SEC-KSA-FIN-INS','SEC-KSA-FIN-FINTECH','SEC-KSA-HEALTH-HOSP','SEC-KSA-HEALTH-PHARMA','SEC-KSA-ENERGY-OG','SEC-KSA-TELCO-ISP','SEC-KSA-EDU-UNIV','SEC-KSA-RETAIL-ECOM','SEC-KSA-TRANSPORT-AVN','SEC-KSA-TECH-SAAS'];

export const POLICY_TEMPLATES: PolicyTemplate[] = [
  {
    template_key: 'POL-ISP-001',
    title_en: 'Information Security Policy',
    title_ar: 'سياسة أمن المعلومات',
    category: 'information_security',
    description_en: 'Master information security policy establishing the security governance framework, roles, responsibilities, and overarching principles for protecting organizational information assets.',
    description_ar: 'سياسة أمن المعلومات الرئيسية التي تؤسس إطار حوكمة الأمن والأدوار والمسؤوليات والمبادئ الشاملة لحماية أصول المعلومات.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `INFORMATION SECURITY POLICY\n\nDocument Control\nOrganization: {{ORG_NAME}}\nVersion: 1.0\nEffective Date: {{EFFECTIVE_DATE}}\nNext Review: {{REVIEW_DATE}}\nOwner: {{CISO_NAME}}\nClassification: Confidential\n\n1. PURPOSE\nThis policy establishes the information security management framework for {{ORG_NAME}} to protect the confidentiality, integrity, and availability of information assets in compliance with NCA Essential Cybersecurity Controls (ECC), SAMA Cybersecurity Framework, and ISO 27001:2022.\n\n2. SCOPE\nThis policy applies to all employees, contractors, third-party service providers, and any individual or entity that accesses, processes, stores, or transmits {{ORG_NAME}} information assets. It covers all information systems, networks, applications, and data across all locations within {{COUNTRY}}.\n\n3. POLICY STATEMENTS\n\n3.1 Information Security Governance\n- {{ORG_NAME}} shall establish an Information Security Steering Committee chaired by the CEO or delegate.\n- The CISO ({{CISO_NAME}}) is responsible for the overall information security program.\n- Security roles and responsibilities shall be clearly defined and communicated (NCA ECC 1-1).\n- Information security objectives shall be aligned with business objectives and regulatory requirements.\n\n3.2 Risk Management\n- Information security risks shall be identified, assessed, and treated using a formal risk management methodology.\n- Risk assessments shall be conducted at least annually and upon significant changes (NCA ECC 1-3).\n- Risk treatment plans shall be approved by the Information Security Steering Committee.\n- Residual risks shall be formally accepted by designated risk owners.\n\n3.3 Asset Management\n- All information assets shall be inventoried and classified according to their sensitivity and criticality.\n- Asset owners shall be assigned and held accountable for the protection of their assets.\n- Classification levels: Top Secret, Secret, Confidential, Restricted, Public (per NCA ECC 2-1).\n\n3.4 Access Control\n- Access to information systems shall follow the principle of least privilege.\n- All access shall be authorized, authenticated, and logged.\n- Privileged access shall be strictly controlled and monitored (NCA ECC 2-2).\n- Multi-factor authentication shall be implemented for critical systems and remote access.\n\n3.5 Cryptography\n- Encryption shall be used to protect sensitive data in transit and at rest.\n- Cryptographic standards shall comply with NCA and SAMA requirements.\n- Key management procedures shall be documented and followed.\n\n3.6 Physical Security\n- Physical access to data centers and critical infrastructure shall be controlled.\n- Environmental controls shall protect against natural and man-made threats.\n- Visitor access shall be logged and escorted.\n\n3.7 Operations Security\n- Change management procedures shall be followed for all system changes.\n- Capacity management shall ensure adequate resources for security operations.\n- Malware protection shall be deployed on all endpoints and servers.\n- Backup procedures shall be documented and tested regularly.\n\n3.8 Network Security\n- Network segmentation shall separate critical systems from general networks.\n- Firewalls, IDS/IPS, and network monitoring shall be implemented.\n- Wireless networks shall be secured with enterprise-grade encryption.\n\n3.9 Incident Management\n- A formal incident response plan shall be maintained and tested.\n- Security incidents shall be reported within 2 hours of detection.\n- NCA shall be notified of significant cybersecurity incidents as required (NCA ECC 3-1).\n- Post-incident reviews shall be conducted and lessons learned documented.\n\n3.10 Business Continuity\n- Business continuity plans shall be developed, maintained, and tested annually.\n- Disaster recovery procedures shall ensure RTO and RPO objectives are met.\n- Critical systems shall have redundancy and failover capabilities.\n\n3.11 Compliance\n- Compliance with this policy shall be monitored through regular audits.\n- Non-compliance shall be reported and addressed through the disciplinary process.\n- Regulatory compliance status shall be reported to the Board quarterly.\n\n4. ROLES AND RESPONSIBILITIES\n- Board of Directors: Oversight of information security governance\n- CEO ({{CEO_NAME}}): Ultimate accountability for information security\n- CISO ({{CISO_NAME}}): Day-to-day management of the security program\n- Department Heads: Implementation within their departments\n- All Employees: Compliance with this policy and reporting incidents\n\n5. ENFORCEMENT\nViolations of this policy may result in disciplinary action up to and including termination of employment or contract, and may also result in legal action where applicable.\n\n6. REVIEW\nThis policy shall be reviewed annually or upon significant changes to the business, technology, or regulatory environment.\n\nApproved by: {{CEO_NAME}}\nDate: {{EFFECTIVE_DATE}}`,
    content_ar: `سياسة أمن المعلومات\n\nالتحكم بالوثيقة\nالمنظمة: {{ORG_NAME}}\nالإصدار: 1.0\nتاريخ السريان: {{EFFECTIVE_DATE}}\nالمراجعة القادمة: {{REVIEW_DATE}}\nالمالك: {{CISO_NAME}}\nالتصنيف: سري\n\n1. الغرض\nتؤسس هذه السياسة إطار إدارة أمن المعلومات لـ {{ORG_NAME}} لحماية سرية وسلامة وتوافر أصول المعلومات وفقاً للضوابط الأساسية للأمن السيبراني (ECC) الصادرة عن الهيئة الوطنية للأمن السيبراني وإطار الأمن السيبراني لساما ومعيار ISO 27001:2022.\n\n2. النطاق\nتنطبق هذه السياسة على جميع الموظفين والمتعاقدين ومقدمي الخدمات من الأطراف الثالثة وأي فرد أو جهة تصل إلى أصول معلومات {{ORG_NAME}} أو تعالجها أو تخزنها أو تنقلها.`,
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Start by establishing the Information Security Steering Committee with representatives from IT, Legal, HR, Operations, and Finance.\n2. Map existing controls to NCA ECC domains (1-1 through 5-2) to identify gaps.\n3. Use the risk assessment methodology defined in the Risk Management Policy (POL-RM-003).\n4. Ensure alignment with SAMA CSF if operating in the financial sector.\n5. PDPL compliance requirements must be integrated for any personal data processing.\n\nREGULATORY REFERENCES:\n- NCA ECC: Controls 1-1 (Cybersecurity Governance), 1-2 (Strategy), 1-3 (Risk Management)\n- SAMA CSF: Domain 1 (Cybersecurity Leadership and Governance)\n- ISO 27001:2022: Clauses 5 (Leadership), 6 (Planning), 8 (Operation)\n- PDPL: Articles 4-9 (Data Processing Principles)',
    guidance_ar: 'إرشادات التنفيذ:\n1. ابدأ بإنشاء لجنة توجيه أمن المعلومات مع ممثلين من تقنية المعلومات والقانون والموارد البشرية والعمليات والمالية.\n2. قم بربط الضوابط الحالية بمجالات ECC للهيئة الوطنية للأمن السيبراني لتحديد الفجوات.\n3. استخدم منهجية تقييم المخاطر المحددة في سياسة إدارة المخاطر.',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.REVIEW_DATE, V.CISO_NAME, V.CEO_NAME, V.COUNTRY],
    review_frequency: 'annual',
    tags: ['cybersecurity','governance','NCA-ECC','SAMA','ISO-27001'],
    sort_order: 1,
  },
  {
    template_key: 'POL-AUP-002',
    title_en: 'Acceptable Use Policy',
    title_ar: 'سياسة الاستخدام المقبول',
    category: 'information_security',
    description_en: 'Defines acceptable and prohibited use of organizational IT resources, systems, and data by employees and contractors.',
    description_ar: 'تحدد الاستخدام المقبول والمحظور لموارد وأنظمة وبيانات تقنية المعلومات من قبل الموظفين والمتعاقدين.',
    frameworks: ['NCA-ECC','ISO-27001'],
    sectors: ALL_SECTORS,
    content_en: `ACCEPTABLE USE POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\nOwner: {{CISO_NAME}}\n\n1. PURPOSE\nTo define acceptable and unacceptable use of {{ORG_NAME}} information technology resources.\n\n2. SCOPE\nAll employees, contractors, consultants, and authorized third parties who access {{ORG_NAME}} IT resources.\n\n3. POLICY STATEMENTS\n\n3.1 General Use\n- IT resources are provided for business purposes. Limited personal use is permitted if it does not interfere with work duties or violate this policy.\n- Users must not share credentials or allow unauthorized access to systems.\n- All data created using {{ORG_NAME}} resources is the property of {{ORG_NAME}}.\n\n3.2 Email and Communication\n- Business email shall be used for official communications only.\n- Users must not send unsolicited bulk messages or phishing attempts.\n- Sensitive data must be encrypted before transmission via email.\n- Auto-forwarding to external email addresses is prohibited.\n\n3.3 Internet Use\n- Access to illegal, offensive, or malicious websites is prohibited.\n- Downloading unauthorized software is prohibited.\n- Use of anonymizing proxies or VPNs not approved by IT is prohibited.\n- Social media use must comply with the Social Media Policy.\n\n3.4 Mobile and Remote Access\n- Only approved devices may connect to {{ORG_NAME}} networks.\n- Mobile devices must have screen lock, encryption, and remote wipe capability.\n- Public Wi-Fi must not be used for accessing sensitive systems without VPN.\n\n3.5 Data Handling\n- Data must be classified and handled according to the Data Classification Policy.\n- Sensitive data must not be stored on personal devices or unauthorized cloud services.\n- Data must be disposed of securely according to retention schedules.\n\n3.6 Prohibited Activities\n- Unauthorized access attempts or vulnerability scanning\n- Installation of unauthorized hardware or software\n- Circumventing security controls\n- Sharing confidential information externally without authorization\n- Using IT resources for personal commercial activities\n\n4. MONITORING\n{{ORG_NAME}} reserves the right to monitor, log, and audit all use of IT resources. Users should have no expectation of privacy when using organizational systems.\n\n5. ENFORCEMENT\nViolations may result in disciplinary action, including termination and legal proceedings.\n\nApproved by: {{CEO_NAME}}\nDate: {{EFFECTIVE_DATE}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Distribute to all employees during onboarding.\n2. Require annual acknowledgement signature.\n3. Integrate with HR disciplinary procedures.\n4. Review and update when new technologies are adopted.\n\nREGULATORY REFERENCES:\n- NCA ECC: Control 2-2 (Identity and Access Management)\n- ISO 27001: A.5.10 (Acceptable use of information)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CISO_NAME, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['acceptable-use','employees','NCA-ECC'],
    sort_order: 2,
  },
  {
    template_key: 'POL-RM-003',
    title_en: 'Risk Management Policy',
    title_ar: 'سياسة إدارة المخاطر',
    category: 'risk_management',
    description_en: 'Establishes the risk management framework including risk identification, assessment, treatment, and monitoring processes.',
    description_ar: 'تؤسس إطار إدارة المخاطر بما في ذلك عمليات تحديد وتقييم ومعالجة ومراقبة المخاطر.',
    frameworks: ['NCA-ECC','ISO-31000','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `RISK MANAGEMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo establish a systematic approach to identifying, assessing, treating, and monitoring information security risks at {{ORG_NAME}}.\n\n2. RISK ASSESSMENT METHODOLOGY\n- Risks shall be assessed using a 5x5 Likelihood x Impact matrix.\n- Likelihood: 1 (Rare) to 5 (Almost Certain)\n- Impact: 1 (Negligible) to 5 (Catastrophic)\n- Risk Score = Likelihood x Impact\n- Risk Appetite: Scores above 12 require mandatory treatment plans.\n\n3. RISK TREATMENT OPTIONS\n- Mitigate: Implement controls to reduce risk\n- Transfer: Use insurance or outsourcing\n- Accept: Formally accept with executive approval (documented)\n- Avoid: Eliminate the risk source\n\n4. RISK REGISTER\n- A centralized risk register shall be maintained.\n- All identified risks shall be logged with owner, score, treatment plan, and status.\n- The risk register shall be reviewed quarterly by the Risk Committee.\n\n5. REGULATORY ALIGNMENT\n- NCA ECC 1-3: Cybersecurity Risk Management\n- SAMA CSF Domain 2: Cybersecurity Risk Management & Compliance\n- ISO 31000:2018: Risk Management Guidelines\n\n6. REPORTING\n- Monthly risk dashboard to CISO ({{CISO_NAME}})\n- Quarterly risk report to Board / Audit Committee\n- Immediate escalation for critical risks (score >= 20)\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Define risk categories: Cyber, Operational, Compliance, Financial, Reputational, Strategic.\n2. Conduct initial risk assessment workshop with department heads.\n3. Map risks to NCA ECC controls and SAMA CSF domains.\n4. Establish risk appetite statement approved by Board.\n5. Integrate with incident management for real-time risk updates.\n\nBEST PRACTICES:\n- Use quantitative methods (FAIR) for high-value risks.\n- Automate risk scoring where possible.\n- Link risks to controls for continuous monitoring.',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CISO_NAME, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['risk','NCA-ECC','ISO-31000','SAMA'],
    sort_order: 3,
  },
  {
    template_key: 'POL-PDPL-004',
    title_en: 'Personal Data Protection Policy (PDPL)',
    title_ar: 'سياسة حماية البيانات الشخصية',
    category: 'data_privacy',
    description_en: 'Comprehensive data protection policy aligned with Saudi PDPL, covering data processing principles, rights of data subjects, and organizational obligations.',
    description_ar: 'سياسة شاملة لحماية البيانات متوافقة مع نظام حماية البيانات الشخصية السعودي.',
    frameworks: ['PDPL','NCA-ECC','ISO-27701'],
    sectors: ALL_SECTORS,
    content_en: `PERSONAL DATA PROTECTION POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\nData Protection Officer: {{DPO_NAME}}\n\n1. PURPOSE\nTo ensure {{ORG_NAME}} processes personal data in compliance with the Saudi Personal Data Protection Law (PDPL) and its Implementing Regulations.\n\n2. DEFINITIONS\n- Personal Data: Any data relating to an identified or identifiable natural person.\n- Sensitive Personal Data: Data revealing racial/ethnic origin, religious beliefs, criminal records, health data, genetic/biometric data, credit data.\n- Data Subject: The individual to whom the personal data relates.\n- Controller: {{ORG_NAME}} when determining purposes and means of processing.\n- Processor: Any party processing personal data on behalf of {{ORG_NAME}}.\n\n3. DATA PROCESSING PRINCIPLES (PDPL Articles 4-9)\n- Lawfulness: Processing must have a legal basis.\n- Purpose Limitation: Data collected for specified, explicit, and legitimate purposes.\n- Data Minimization: Only data necessary for the stated purpose.\n- Accuracy: Personal data must be accurate and kept up to date.\n- Storage Limitation: Data retained only as long as necessary.\n- Integrity and Confidentiality: Appropriate security measures.\n- Accountability: {{ORG_NAME}} must demonstrate compliance.\n\n4. LEGAL BASES FOR PROCESSING\n- Consent of the data subject\n- Performance of a contract\n- Compliance with legal obligations\n- Protection of vital interests\n- Public interest (for government entities)\n- Legitimate interests of the controller\n\n5. DATA SUBJECT RIGHTS (PDPL Articles 10-18)\n- Right to be informed about data processing\n- Right of access to personal data\n- Right to rectification of inaccurate data\n- Right to erasure (Right to be Forgotten)\n- Right to restrict processing\n- Right to data portability\n- Right to object to processing\n- Right not to be subject to automated decision-making\n\n6. CROSS-BORDER DATA TRANSFER\n- Personal data shall not be transferred outside the Kingdom unless:\n  a) The receiving country has adequate protection\n  b) Appropriate safeguards are in place\n  c) SDAIA has approved the transfer\n- Data localization requirements for sensitive government data.\n\n7. DATA BREACH NOTIFICATION\n- Breaches must be reported to SDAIA within 72 hours.\n- Affected data subjects must be notified without undue delay.\n- A breach register shall be maintained.\n\n8. DATA PROTECTION IMPACT ASSESSMENT (DPIA)\n- Required for high-risk processing activities.\n- Must be conducted before new processing begins.\n- Results reported to DPO ({{DPO_NAME}}).\n\n9. RECORDS OF PROCESSING ACTIVITIES\n- {{ORG_NAME}} shall maintain records of all processing activities.\n- Records shall include: purpose, categories of data, recipients, retention periods, security measures.\n\n10. PENALTIES\n- PDPL violations can result in fines up to SAR 5 million.\n- Criminal penalties for disclosure of sensitive data: up to 2 years imprisonment.\n\nApproved by: {{CEO_NAME}}\nDate: {{EFFECTIVE_DATE}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Appoint a Data Protection Officer (DPO) as required by PDPL Article 30.\n2. Conduct data mapping exercise to identify all personal data flows.\n3. Create Records of Processing Activities (ROPA) for each department.\n4. Implement consent management system for customer-facing services.\n5. Establish data subject rights request handling process (30-day SLA).\n6. Conduct DPIAs for all high-risk processing.\n7. Update all contracts with data processors to include PDPL clauses.\n8. Train all employees on PDPL requirements.\n\nKEY SDAIA DEADLINES:\n- Compliance deadline for existing processing: 12 months from regulation\n- Breach notification: 72 hours\n- Data subject request response: 30 days',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.DPO_NAME, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['PDPL','privacy','data-protection','SDAIA'],
    sort_order: 4,
  },
  {
    template_key: 'POL-AC-005',
    title_en: 'Access Control Policy',
    title_ar: 'سياسة التحكم في الوصول',
    category: 'information_security',
    description_en: 'Governs user access management, authentication, authorization, and privileged access to information systems.',
    description_ar: 'تحكم إدارة وصول المستخدمين والمصادقة والتفويض والوصول المميز لأنظمة المعلومات.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `ACCESS CONTROL POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure that access to {{ORG_NAME}} information assets is authorized, controlled, and monitored.\n\n2. PRINCIPLES\n- Least Privilege: Users receive minimum access required for their role.\n- Need-to-Know: Access granted only when business need is demonstrated.\n- Separation of Duties: Critical functions require multiple approvers.\n- Zero Trust: Verify explicitly, use least privilege, assume breach.\n\n3. USER ACCESS MANAGEMENT\n- All access requests must be approved by the data/system owner.\n- Access reviews shall be conducted quarterly for critical systems.\n- Access shall be revoked within 24 hours of role change or termination.\n- Dormant accounts (90+ days inactive) shall be disabled automatically.\n\n4. AUTHENTICATION\n- Passwords: Minimum 12 characters, complexity requirements, 90-day rotation.\n- MFA: Required for all remote access, administrative accounts, and critical systems.\n- SSO: Implemented where possible to reduce credential sprawl.\n- Biometric: Permitted for physical access to data centers.\n\n5. PRIVILEGED ACCESS\n- Privileged accounts shall be inventoried and monitored.\n- Just-in-time (JIT) access for administrative tasks.\n- Privileged sessions shall be recorded and auditable.\n- Shared administrative accounts are prohibited.\n\n6. NCA ECC ALIGNMENT\n- ECC 2-2: Identity and Access Management\n- ECC 2-3: Information System and Processing Facility Protection\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Implement Identity and Access Management (IAM) solution.\n2. Deploy MFA for all users, starting with privileged and remote access.\n3. Establish access request and approval workflow in AGRC-OS.\n4. Configure automated access reviews with quarterly certification campaigns.\n5. Implement PAM solution for privileged access management.\n\nNCA ECC CONTROLS:\n- 2-2-1: User Access Management\n- 2-2-2: Privileged Access Management\n- 2-2-3: Authentication',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['access-control','IAM','NCA-ECC','zero-trust'],
    sort_order: 5,
  },
  {
    template_key: 'POL-IR-006',
    title_en: 'Incident Response Policy',
    title_ar: 'سياسة الاستجابة للحوادث',
    category: 'incident_management',
    description_en: 'Defines the incident response lifecycle including detection, containment, eradication, recovery, and lessons learned.',
    description_ar: 'تحدد دورة حياة الاستجابة للحوادث بما في ذلك الكشف والاحتواء والإزالة والاسترداد والدروس المستفادة.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `INCIDENT RESPONSE POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo establish a structured approach to detecting, responding to, and recovering from cybersecurity incidents.\n\n2. INCIDENT CLASSIFICATION\n- P1 Critical: Data breach, ransomware, system-wide compromise. Response: Immediate.\n- P2 High: Unauthorized access, malware outbreak. Response: 4 hours.\n- P3 Medium: Policy violation, suspicious activity. Response: 24 hours.\n- P4 Low: Minor anomaly, false positive. Response: 72 hours.\n\n3. INCIDENT RESPONSE PHASES\n- Preparation: Maintain IRT, tools, playbooks, and training.\n- Detection & Analysis: Monitor logs, SIEM alerts, user reports.\n- Containment: Isolate affected systems, preserve evidence.\n- Eradication: Remove threat, patch vulnerabilities.\n- Recovery: Restore systems, verify integrity.\n- Post-Incident: Conduct review, update controls, document lessons.\n\n4. NOTIFICATION REQUIREMENTS\n- NCA: Notify within 2 hours for critical cyber incidents.\n- SAMA: Notify within 4 hours for financial sector incidents.\n- SDAIA: Notify within 72 hours for personal data breaches (PDPL).\n- Management: CEO notified for P1/P2 incidents immediately.\n\n5. INCIDENT RESPONSE TEAM\n- CISO ({{CISO_NAME}}): IRT Lead\n- IT Security Team: Technical investigation\n- Legal: Regulatory notification and liability\n- HR: Employee-related incidents\n- Communications: External/media communication\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Establish 24/7 SOC capability or managed SOC service.\n2. Create incident response playbooks for top 10 scenarios.\n3. Conduct tabletop exercises quarterly.\n4. Maintain evidence collection toolkit.\n5. Establish communication templates for NCA/SAMA/SDAIA notifications.\n\nNCA NOTIFICATION TEMPLATE:\n- Incident Type, Date/Time, Systems Affected, Data Impact, Containment Status, Actions Taken.',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CISO_NAME, V.CEO_NAME],
    review_frequency: 'semi-annual',
    tags: ['incident-response','SOC','NCA-ECC','notification'],
    sort_order: 6,
  },
  {
    template_key: 'POL-BCP-007',
    title_en: 'Business Continuity Policy',
    title_ar: 'سياسة استمرارية الأعمال',
    category: 'business_continuity',
    description_en: 'Framework for maintaining critical business operations during and after disruptive events.',
    description_ar: 'إطار للحفاظ على العمليات التجارية الحرجة أثناء وبعد الأحداث التخريبية.',
    frameworks: ['NCA-ECC','ISO-22301','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `BUSINESS CONTINUITY POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure {{ORG_NAME}} can continue critical operations during disruptions and recover within acceptable timeframes.\n\n2. BUSINESS IMPACT ANALYSIS (BIA)\n- All business processes shall be assessed for criticality.\n- RTO (Recovery Time Objective) and RPO (Recovery Point Objective) shall be defined.\n- Maximum Tolerable Downtime (MTD) established for each process.\n\n3. BCP REQUIREMENTS\n- Alternate processing sites shall be maintained for critical systems.\n- Communication plans for employees, customers, and regulators.\n- Regular testing: Desktop exercises (quarterly), Full DR test (annually).\n- Supply chain continuity plans for critical vendors.\n\n4. DISASTER RECOVERY\n- DR site with capacity for critical workloads.\n- Automated failover for Tier-1 systems (RTO < 4 hours).\n- Data replication with RPO < 1 hour for critical data.\n- Annual DR test with documented results.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Conduct BIA with all department heads.\n2. Define tiered recovery: Tier-1 (< 4h), Tier-2 (< 24h), Tier-3 (< 72h).\n3. Establish crisis management team and communication tree.\n4. Test DR annually with documented results.\n\nNCA ECC ALIGNMENT: Control 4-1 (Cybersecurity Resilience)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['BCP','DR','continuity','ISO-22301'],
    sort_order: 7,
  },
  {
    template_key: 'POL-TPRM-008',
    title_en: 'Third-Party Risk Management Policy',
    title_ar: 'سياسة إدارة مخاطر الأطراف الثالثة',
    category: 'vendor_management',
    description_en: 'Governs the assessment, monitoring, and management of risks from third-party vendors and service providers.',
    description_ar: 'تحكم تقييم ومراقبة وإدارة المخاطر من الموردين ومقدمي الخدمات من الأطراف الثالثة.',
    frameworks: ['NCA-ECC','SAMA-CSF','ISO-27001'],
    sectors: ALL_SECTORS,
    content_en: `THIRD-PARTY RISK MANAGEMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo manage risks arising from {{ORG_NAME}} relationships with third-party vendors, suppliers, and service providers.\n\n2. VENDOR RISK ASSESSMENT\n- All vendors shall be risk-rated: Critical, High, Medium, Low.\n- Due diligence required before engagement.\n- Security questionnaire and evidence collection.\n- On-site audits for critical vendors.\n\n3. CONTRACTUAL REQUIREMENTS\n- Security requirements and SLAs in all contracts.\n- Data processing agreements for personal data handlers.\n- Right to audit clause.\n- Incident notification requirements (within 24 hours).\n- Data return/destruction upon termination.\n\n4. ONGOING MONITORING\n- Annual reassessment for critical and high-risk vendors.\n- Continuous monitoring of vendor security posture.\n- Performance reviews against SLAs.\n- Vendor concentration risk analysis.\n\n5. CLOUD SERVICE PROVIDERS\n- Data residency: Preference for in-Kingdom hosting.\n- Compliance with NCA Cloud Cybersecurity Controls (CCC).\n- Shared responsibility model documentation.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Create vendor inventory with risk classifications.\n2. Develop vendor security questionnaire aligned with NCA ECC.\n3. Implement vendor risk scoring in AGRC-OS.\n4. Establish vendor onboarding/offboarding procedures.\n5. Monitor NCA CCC compliance for cloud vendors.\n\nSAMA REQUIREMENT: SAMA CSF Domain 5 requires formal third-party security management for financial institutions.',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['TPRM','vendor','third-party','NCA-CCC'],
    sort_order: 8,
  },
  {
    template_key: 'POL-CM-009',
    title_en: 'Change Management Policy',
    title_ar: 'سياسة إدارة التغيير',
    category: 'operations',
    description_en: 'Controls changes to IT systems, infrastructure, and applications to minimize disruption and security risks.',
    description_ar: 'تتحكم في التغييرات على أنظمة وبنية وتطبيقات تقنية المعلومات لتقليل الاضطراب ومخاطر الأمن.',
    frameworks: ['NCA-ECC','ISO-27001','ITIL'],
    sectors: ALL_SECTORS,
    content_en: `CHANGE MANAGEMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure all changes to {{ORG_NAME}} IT environment are planned, tested, approved, and documented.\n\n2. CHANGE CATEGORIES\n- Standard: Pre-approved, low-risk, routine changes.\n- Normal: Require CAB review and approval.\n- Emergency: Bypass normal process with post-implementation review.\n\n3. CHANGE PROCESS\n- Request: Submit change request with impact assessment.\n- Review: Technical review and risk assessment.\n- Approve: CAB or delegated authority approval.\n- Implement: Execute during approved maintenance window.\n- Verify: Post-implementation testing and validation.\n- Close: Document results and update CMDB.\n\n4. CHANGE ADVISORY BOARD (CAB)\n- Meets weekly to review pending changes.\n- Members: IT Director, Security, Operations, Business Representatives.\n- Emergency CAB: CISO + IT Director can approve critical patches.\n\n5. ROLLBACK\n- All changes must have a documented rollback plan.\n- Rollback must be tested before implementation.\n- Automated rollback preferred for critical systems.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Establish Change Advisory Board with defined membership.\n2. Create change request form in AGRC-OS workflow.\n3. Define maintenance windows for each system tier.\n4. Integrate with CMDB for impact analysis.\n5. Track change success rate as KPI.\n\nNCA ECC: Control 3-2 (Cybersecurity Defense) requires change management.',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['change-management','ITIL','operations'],
    sort_order: 9,
  },
  {
    template_key: 'POL-CLS-010',
    title_en: 'Data Classification Policy',
    title_ar: 'سياسة تصنيف البيانات',
    category: 'data_governance',
    description_en: 'Defines data classification levels and handling requirements for each classification.',
    description_ar: 'تحدد مستويات تصنيف البيانات ومتطلبات التعامل مع كل تصنيف.',
    frameworks: ['NCA-ECC','PDPL','ISO-27001'],
    sectors: ALL_SECTORS,
    content_en: `DATA CLASSIFICATION POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo establish data classification levels and associated handling, storage, transmission, and disposal requirements.\n\n2. CLASSIFICATION LEVELS (per NCA ECC 2-1)\n\n- TOP SECRET: National security data, critical infrastructure details.\n  Handling: Need-to-know, encrypted storage/transit, no cloud, audited access.\n\n- SECRET: Strategic business data, financial projections, M&A details.\n  Handling: Restricted access, encrypted, approved systems only.\n\n- CONFIDENTIAL: Internal business data, employee records, customer PII.\n  Handling: Role-based access, encrypted in transit, secure disposal.\n\n- RESTRICTED: Internal-only data, operational procedures.\n  Handling: Employee access, no public sharing.\n\n- PUBLIC: Marketing materials, published reports.\n  Handling: No restrictions on distribution.\n\n3. LABELING\n- All documents must display classification label.\n- Electronic documents: Header/footer marking.\n- Email: Subject line prefix [CONFIDENTIAL] etc.\n- Physical: Stamp or printed label on each page.\n\n4. DATA HANDLING MATRIX\n| Level | Storage | Transmission | Printing | Disposal |\n|-------|---------|-------------|----------|----------|\n| Top Secret | Encrypted, on-prem only | Encrypted, approved channels | Controlled, watermarked | Shred, degauss |\n| Secret | Encrypted | Encrypted | Logged | Shred |\n| Confidential | Access-controlled | TLS/VPN | Approved printers | Shred |\n| Restricted | Internal systems | Internal network | Standard | Recycle securely |\n| Public | Any | Any | Any | Standard |\n\n5. PERSONAL DATA (PDPL)\n- Personal data is classified minimum CONFIDENTIAL.\n- Sensitive personal data is classified minimum SECRET.\n- Processing must comply with the PDPL Policy (POL-PDPL-004).\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION GUIDANCE:\n1. Conduct data inventory across all departments.\n2. Assign data owners for each data category.\n3. Implement DLP tools to enforce classification rules.\n4. Train all employees on classification and labeling.\n5. Integrate with email and document management systems.\n\nNCA ECC: Control 2-1 (Cybersecurity Defense - Asset Management)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['classification','data-governance','NCA-ECC','PDPL'],
    sort_order: 10,
  },
  {
    template_key: 'POL-CRYPTO-011',
    title_en: 'Cryptography and Key Management Policy',
    title_ar: 'سياسة التشفير وإدارة المفاتيح',
    category: 'information_security',
    description_en: 'Governs the use of cryptographic controls and key management for protecting information assets.',
    description_ar: 'تحكم استخدام ضوابط التشفير وإدارة المفاتيح لحماية أصول المعلومات.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `CRYPTOGRAPHY AND KEY MANAGEMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure appropriate use of cryptography to protect the confidentiality, integrity, and authenticity of {{ORG_NAME}} information.\n\n2. ENCRYPTION STANDARDS\n- Data at Rest: AES-256 minimum.\n- Data in Transit: TLS 1.2+ (TLS 1.3 preferred).\n- Email: S/MIME or PGP for sensitive communications.\n- Database: Transparent Data Encryption (TDE) for sensitive databases.\n- Full Disk Encryption: Required on all laptops and mobile devices.\n\n3. KEY MANAGEMENT\n- Key generation using approved random number generators.\n- Key storage in HSM or approved key vault.\n- Key rotation: Annually for data keys, per policy for master keys.\n- Key destruction: Secure deletion with verification.\n- Dual control for master key operations.\n\n4. CERTIFICATE MANAGEMENT\n- PKI certificates from approved CAs only.\n- Certificate inventory maintained and monitored.\n- 90-day renewal alerts.\n- Automated certificate lifecycle management.\n\n5. PROHIBITED\n- Custom or proprietary encryption algorithms.\n- SSL, TLS 1.0, TLS 1.1.\n- MD5, SHA-1 for security purposes.\n- Storing encryption keys alongside encrypted data.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Deploy enterprise key management solution (Azure Key Vault, HashiCorp Vault).\n2. Inventory all encryption in use across systems.\n3. Implement certificate monitoring and auto-renewal.\n4. Document key custodian responsibilities.\n\nNCA ECC: Control 2-4 (Cryptography)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['cryptography','encryption','key-management','NCA-ECC'],
    sort_order: 11,
  },
  {
    template_key: 'POL-PHYS-012',
    title_en: 'Physical and Environmental Security Policy',
    title_ar: 'سياسة الأمن المادي والبيئي',
    category: 'physical_security',
    description_en: 'Controls physical access to facilities, data centers, and equipment, including environmental protections.',
    description_ar: 'تتحكم في الوصول المادي للمرافق ومراكز البيانات والمعدات بما في ذلك الحماية البيئية.',
    frameworks: ['NCA-ECC','ISO-27001'],
    sectors: ALL_SECTORS,
    content_en: `PHYSICAL AND ENVIRONMENTAL SECURITY POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo protect {{ORG_NAME}} facilities, equipment, and information from physical and environmental threats.\n\n2. PHYSICAL ACCESS CONTROL\n- Secured perimeter with access control systems.\n- ID badge required for all personnel.\n- Visitor management: Registration, escort, badge return.\n- CCTV monitoring with 90-day retention.\n- After-hours access logging and alerting.\n\n3. DATA CENTER SECURITY\n- Multi-factor authentication for data center entry.\n- Mantrap/airlock entry systems.\n- No food, drink, or unauthorized devices.\n- Equipment removal requires authorization.\n- Clean desk policy in secure areas.\n\n4. ENVIRONMENTAL CONTROLS\n- Fire detection and suppression (gas-based for server rooms).\n- Temperature and humidity monitoring (18-27C, 40-60% RH).\n- UPS and backup generators.\n- Water leak detection.\n- Seismic considerations for critical facilities.\n\n5. EQUIPMENT SECURITY\n- Asset tagging for all IT equipment.\n- Secure disposal of storage media.\n- Cable management and protection.\n- Equipment maintenance by authorized personnel only.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Conduct physical security assessment of all facilities.\n2. Implement access control system with audit logging.\n3. Install CCTV at all entry/exit points and sensitive areas.\n4. Document data center access procedures.\n\nNCA ECC: Control 2-3 (Information System and Processing Facility Protection)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['physical-security','data-center','environmental'],
    sort_order: 12,
  },
  {
    template_key: 'POL-HR-013',
    title_en: 'Human Resources Security Policy',
    title_ar: 'سياسة أمن الموارد البشرية',
    category: 'human_resources',
    description_en: 'Security requirements throughout the employee lifecycle: before, during, and after employment.',
    description_ar: 'متطلبات الأمن خلال دورة حياة الموظف: قبل وأثناء وبعد التوظيف.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `HUMAN RESOURCES SECURITY POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure security considerations are addressed throughout the employee lifecycle at {{ORG_NAME}}.\n\n2. PRIOR TO EMPLOYMENT\n- Background checks for all employees proportional to role sensitivity.\n- Employment contracts include confidentiality and security clauses.\n- Security clearance for positions accessing classified information.\n\n3. DURING EMPLOYMENT\n- Security awareness training: Mandatory within 30 days, annual refresher.\n- Role-specific security training for IT, development, and management.\n- Phishing simulation exercises: Monthly.\n- Confidentiality agreements reviewed annually.\n- Performance reviews include security compliance.\n\n4. TERMINATION / CHANGE OF ROLE\n- Access revocation within 24 hours of termination.\n- Exit interview including security obligations reminder.\n- Return of all {{ORG_NAME}} assets.\n- Continued confidentiality obligations post-employment.\n- Knowledge transfer process for critical roles.\n\n5. DISCIPLINARY PROCESS\n- Security violations reported to HR and CISO.\n- Investigation process with documented findings.\n- Sanctions proportional to severity.\n- Appeal process available.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Integrate security requirements into HR onboarding process.\n2. Deploy security awareness platform with tracking.\n3. Establish joiner-mover-leaver (JML) process with IT.\n4. Create role-based training matrix.\n\nNCA ECC: Control 1-1-4 (Cybersecurity Awareness)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['HR','awareness','training','onboarding'],
    sort_order: 13,
  },
  {
    template_key: 'POL-NET-014',
    title_en: 'Network Security Policy',
    title_ar: 'سياسة أمن الشبكات',
    category: 'information_security',
    description_en: 'Governs network architecture, segmentation, monitoring, and protection of network infrastructure.',
    description_ar: 'تحكم بنية الشبكة والتقسيم والمراقبة وحماية البنية التحتية للشبكة.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `NETWORK SECURITY POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo protect {{ORG_NAME}} network infrastructure from unauthorized access, misuse, and cyber threats.\n\n2. NETWORK ARCHITECTURE\n- Network segmentation separating: DMZ, production, development, management, guest.\n- Micro-segmentation for critical workloads.\n- Network diagrams maintained and updated quarterly.\n\n3. PERIMETER SECURITY\n- Next-generation firewalls at all perimeter points.\n- IDS/IPS monitoring all ingress/egress traffic.\n- Web Application Firewall (WAF) for internet-facing applications.\n- DDoS protection for public services.\n\n4. INTERNAL SECURITY\n- 802.1X network access control.\n- VLAN isolation between departments.\n- East-west traffic monitoring.\n- DNS filtering and monitoring.\n\n5. WIRELESS SECURITY\n- WPA3-Enterprise for corporate wireless.\n- Guest network isolated from corporate.\n- Rogue AP detection.\n- No wireless in data center zones.\n\n6. VPN AND REMOTE ACCESS\n- Always-on VPN for remote workers.\n- Split tunneling prohibited for corporate devices.\n- VPN MFA required.\n\n7. MONITORING\n- 24/7 network monitoring via SIEM.\n- NetFlow analysis for anomaly detection.\n- Quarterly vulnerability scanning.\n- Annual penetration testing.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Deploy NGFW with unified threat management.\n2. Implement network segmentation per data classification.\n3. Establish SOC for 24/7 monitoring.\n4. Conduct annual penetration testing by accredited third party.\n\nNCA ECC: Controls 2-3, 3-1, 3-2 (Network Security)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['network','firewall','segmentation','monitoring'],
    sort_order: 14,
  },
  {
    template_key: 'POL-SDLC-015',
    title_en: 'Secure Software Development Policy',
    title_ar: 'سياسة تطوير البرمجيات الآمنة',
    category: 'application_security',
    description_en: 'Embeds security into the software development lifecycle (SDLC) including secure coding, testing, and deployment.',
    description_ar: 'تدمج الأمن في دورة حياة تطوير البرمجيات بما في ذلك الترميز الآمن والاختبار والنشر.',
    frameworks: ['NCA-ECC','ISO-27001','OWASP'],
    sectors: ['SEC-KSA-FIN-BANK','SEC-KSA-FIN-FINTECH','SEC-KSA-TECH-SAAS','SEC-KSA-GOV-MIN','SEC-KSA-GOV-AUTH'],
    content_en: `SECURE SOFTWARE DEVELOPMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo integrate security throughout the software development lifecycle at {{ORG_NAME}}.\n\n2. SECURE SDLC PHASES\n- Requirements: Security requirements and threat modeling.\n- Design: Security architecture review, STRIDE analysis.\n- Implementation: Secure coding standards (OWASP), code review.\n- Testing: SAST, DAST, SCA, penetration testing.\n- Deployment: Hardened configurations, infrastructure as code.\n- Maintenance: Patch management, vulnerability monitoring.\n\n3. SECURE CODING STANDARDS\n- OWASP Top 10 mitigation required.\n- Input validation on all user inputs.\n- Parameterized queries (no SQL injection).\n- Output encoding (no XSS).\n- Secure session management.\n- No hardcoded secrets (use vault).\n\n4. CODE REVIEW\n- Peer review required before merge.\n- Security-focused review for authentication, authorization, crypto.\n- Automated SAST scan on every pull request.\n\n5. DEPENDENCY MANAGEMENT\n- SCA scan on all dependencies.\n- No known critical/high vulnerabilities in production.\n- License compliance check.\n- SBOM maintained for all applications.\n\n6. DEPLOYMENT SECURITY\n- CI/CD pipeline with security gates.\n- Container image scanning.\n- Infrastructure as Code security scanning.\n- Immutable deployments preferred.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Adopt OWASP SAMM for SDLC maturity assessment.\n2. Integrate SAST/DAST tools in CI/CD pipeline.\n3. Train developers on secure coding (annual).\n4. Implement pre-commit hooks for secret scanning.\n\nNCA ECC: Control 3-2-3 (Application Security)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['SDLC','application-security','OWASP','DevSecOps'],
    sort_order: 15,
  },
  {
    template_key: 'POL-CLOUD-016',
    title_en: 'Cloud Security Policy',
    title_ar: 'سياسة أمن الحوسبة السحابية',
    category: 'cloud_security',
    description_en: 'Governs the secure use of cloud services including IaaS, PaaS, and SaaS, aligned with NCA CCC.',
    description_ar: 'تحكم الاستخدام الآمن للخدمات السحابية بما في ذلك IaaS وPaaS وSaaS وفقاً لضوابط الأمن السيبراني السحابي.',
    frameworks: ['NCA-CCC','NCA-ECC','ISO-27017','CSA-CCM'],
    sectors: ALL_SECTORS,
    content_en: `CLOUD SECURITY POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo establish security requirements for {{ORG_NAME}} cloud computing usage in compliance with NCA Cloud Cybersecurity Controls (CCC).\n\n2. CLOUD GOVERNANCE\n- Cloud usage requires CISO approval.\n- Cloud service inventory maintained.\n- Shared responsibility model documented per provider.\n- Cloud security architecture reviewed annually.\n\n3. DATA RESIDENCY\n- Government data: Must remain within Kingdom of Saudi Arabia.\n- Sensitive data: In-Kingdom hosting preferred; cross-border requires NCA approval.\n- Public data: No residency restrictions.\n\n4. CLOUD SECURITY CONTROLS\n- Identity federation with organizational IdP.\n- MFA for all cloud administrative access.\n- Encryption of data at rest and in transit (customer-managed keys preferred).\n- Network security groups and micro-segmentation.\n- Logging to centralized SIEM.\n- Vulnerability management and patch compliance.\n\n5. CLOUD PROVIDER REQUIREMENTS\n- SOC 2 Type II or ISO 27001 certified.\n- CSCC compliance attestation.\n- Data processing agreement.\n- Right to audit.\n- Incident notification within 4 hours.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Inventory all cloud services and classify by sensitivity.\n2. Implement CASB for shadow IT discovery.\n3. Deploy CSPM for continuous compliance monitoring.\n4. Establish cloud security baseline per NCA CCC.\n5. Review CSP compliance certificates annually.\n\nNCA CCC: Cloud Cybersecurity Controls (mandatory for government entities)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['cloud','NCA-CCC','SaaS','data-residency'],
    sort_order: 16,
  },
  {
    template_key: 'POL-AM-017',
    title_en: 'Asset Management Policy',
    title_ar: 'سياسة إدارة الأصول',
    category: 'asset_management',
    description_en: 'Governs the identification, classification, and management of information and technology assets.',
    description_ar: 'تحكم تحديد وتصنيف وإدارة أصول المعلومات والتقنية.',
    frameworks: ['NCA-ECC','ISO-27001'],
    sectors: ALL_SECTORS,
    content_en: `ASSET MANAGEMENT POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure all {{ORG_NAME}} information and technology assets are identified, classified, and protected throughout their lifecycle.\n\n2. ASSET INVENTORY\n- Comprehensive inventory of all hardware, software, data, and network assets.\n- Automated discovery tools for network-connected assets.\n- CMDB maintained with asset relationships.\n- Quarterly inventory reconciliation.\n\n3. ASSET OWNERSHIP\n- Each asset assigned a business owner and a technical custodian.\n- Owners responsible for classification, access decisions, and risk acceptance.\n- Custodians responsible for day-to-day security implementation.\n\n4. ASSET LIFECYCLE\n- Procurement: Security requirements in specifications.\n- Deployment: Hardened configuration before production.\n- Operation: Patching, monitoring, access control.\n- Decommissioning: Secure data destruction, proper disposal.\n\n5. SOFTWARE ASSET MANAGEMENT\n- Approved software list maintained.\n- License compliance tracked.\n- Unauthorized software detected and removed.\n- Open source usage governed by license policy.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Deploy asset discovery and CMDB solution.\n2. Define asset classification aligned with data classification.\n3. Establish asset lifecycle procedures.\n4. Implement software whitelisting where possible.\n\nNCA ECC: Control 2-1 (Asset Management)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['asset-management','CMDB','inventory'],
    sort_order: 17,
  },
  {
    template_key: 'POL-AUDIT-018',
    title_en: 'Internal Audit and Compliance Policy',
    title_ar: 'سياسة التدقيق الداخلي والامتثال',
    category: 'audit',
    description_en: 'Framework for conducting internal audits and monitoring compliance with policies, regulations, and standards.',
    description_ar: 'إطار لإجراء التدقيق الداخلي ومراقبة الامتثال للسياسات واللوائح والمعايير.',
    frameworks: ['NCA-ECC','ISO-27001','ISO-19011'],
    sectors: ALL_SECTORS,
    content_en: `INTERNAL AUDIT AND COMPLIANCE POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo establish a systematic approach to internal auditing and compliance monitoring at {{ORG_NAME}}.\n\n2. AUDIT PROGRAM\n- Annual audit plan approved by Audit Committee.\n- Risk-based audit prioritization.\n- Coverage of all NCA ECC domains over 3-year cycle.\n- Compliance audits for PDPL, SAMA CSF, and other applicable frameworks.\n\n3. AUDIT PROCESS\n- Planning: Define scope, objectives, criteria.\n- Fieldwork: Evidence collection, testing, interviews.\n- Reporting: Findings, risk ratings, recommendations.\n- Follow-up: Remediation tracking, closure verification.\n\n4. AUDIT INDEPENDENCE\n- Internal audit function reports to Audit Committee.\n- Auditors must not audit areas they are responsible for.\n- External audit: Annual by accredited firm.\n\n5. COMPLIANCE MONITORING\n- Continuous compliance monitoring via AGRC-OS platform.\n- Monthly compliance dashboards for management.\n- Quarterly regulatory compliance reports for Board.\n- Non-compliance escalation within 48 hours.\n\n6. FINDINGS MANAGEMENT\n- Critical findings: 30-day remediation SLA.\n- High findings: 60-day remediation SLA.\n- Medium findings: 90-day remediation SLA.\n- Low findings: Next review cycle.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Establish annual audit calendar.\n2. Define audit methodology and templates.\n3. Train internal auditors on NCA ECC and ISO 27001.\n4. Implement findings tracking in AGRC-OS.\n5. Establish Audit Committee charter.\n\nNCA ECC: Control 5-1 (Cybersecurity Audit)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['audit','compliance','internal-audit','NCA-ECC'],
    sort_order: 18,
  },
  {
    template_key: 'POL-SAT-019',
    title_en: 'Security Awareness and Training Policy',
    title_ar: 'سياسة التوعية والتدريب الأمني',
    category: 'awareness',
    description_en: 'Establishes the cybersecurity awareness and training program for all organizational personnel.',
    description_ar: 'تؤسس برنامج التوعية والتدريب على الأمن السيبراني لجميع العاملين.',
    frameworks: ['NCA-ECC','ISO-27001','SAMA-CSF'],
    sectors: ALL_SECTORS,
    content_en: `SECURITY AWARENESS AND TRAINING POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure all {{ORG_NAME}} personnel understand their cybersecurity responsibilities and can recognize and respond to threats.\n\n2. TRAINING REQUIREMENTS\n- New Hire: Complete security awareness within 30 days.\n- Annual: Mandatory refresher training for all staff.\n- Role-Based: Additional training for IT, developers, managers.\n- Executive: Board-level cybersecurity briefings quarterly.\n\n3. AWARENESS PROGRAM\n- Monthly security newsletters/communications.\n- Quarterly phishing simulations.\n- Annual Cybersecurity Awareness Month (October) activities.\n- Security champions program in each department.\n- Gamification and recognition for security behaviors.\n\n4. TRAINING TOPICS\n- Phishing and social engineering recognition.\n- Password security and MFA.\n- Data classification and handling.\n- Incident reporting procedures.\n- PDPL and data privacy.\n- Physical security awareness.\n- Remote work security.\n- Mobile device security.\n\n5. METRICS AND REPORTING\n- Training completion rates (target: 95%).\n- Phishing simulation click rates (target: < 5%).\n- Incident reporting rates.\n- Knowledge assessment scores.\n- Monthly metrics dashboard for CISO.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Select and deploy security awareness platform.\n2. Create training content in Arabic and English.\n3. Establish phishing simulation program.\n4. Track completion and report monthly.\n5. Integrate with HR performance reviews.\n\nNCA ECC: Control 1-1-4 (Cybersecurity Awareness and Training)',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'annual',
    tags: ['awareness','training','phishing','NCA-ECC'],
    sort_order: 19,
  },
  {
    template_key: 'POL-SAMA-020',
    title_en: 'SAMA Cybersecurity Framework Compliance Policy',
    title_ar: 'سياسة الامتثال لإطار الأمن السيبراني لساما',
    category: 'regulatory_compliance',
    description_en: 'Specific compliance policy for financial sector entities regulated by SAMA, covering all CSF domains.',
    description_ar: 'سياسة امتثال مخصصة للكيانات في القطاع المالي الخاضعة لتنظيم البنك المركزي السعودي.',
    frameworks: ['SAMA-CSF','NCA-ECC','PDPL'],
    sectors: ['SEC-KSA-FIN-BANK','SEC-KSA-FIN-INS','SEC-KSA-FIN-FINTECH','SEC-KSA-FIN-CAPITAL'],
    content_en: `SAMA CYBERSECURITY FRAMEWORK COMPLIANCE POLICY\n\nOrganization: {{ORG_NAME}}\nEffective Date: {{EFFECTIVE_DATE}}\n\n1. PURPOSE\nTo ensure {{ORG_NAME}} compliance with SAMA Cybersecurity Framework (CSF) as a regulated financial institution.\n\n2. SCOPE\nAll information systems, networks, and data processing activities under SAMA regulation.\n\n3. CSF DOMAIN COMPLIANCE\n\n3.1 Domain 1: Cybersecurity Leadership and Governance\n- Cybersecurity committee chaired by executive management.\n- Cybersecurity strategy approved by Board.\n- Annual cybersecurity budget allocation.\n- CISO role with direct reporting to CEO.\n\n3.2 Domain 2: Cybersecurity Risk Management and Compliance\n- Formal risk management program.\n- Regulatory compliance monitoring.\n- Third-party risk management.\n- Cybersecurity insurance evaluation.\n\n3.3 Domain 3: Cybersecurity Operations and Technology\n- SOC operations (24/7 for Tier-1 institutions).\n- Vulnerability management program.\n- Penetration testing (annual + after major changes).\n- Secure software development.\n- Network security and monitoring.\n\n3.4 Domain 4: Third-Party Cybersecurity\n- Vendor security assessment program.\n- Cloud security requirements.\n- Outsourcing risk management.\n- Fourth-party risk visibility.\n\n4. SAMA REPORTING\n- Monthly cybersecurity status reports.\n- Incident reporting within 4 hours.\n- Annual self-assessment submission.\n- Remediation plans for audit findings.\n\n5. MATURITY ASSESSMENT\n- Target maturity level: Level 4 (Managed) minimum.\n- Annual maturity assessment across all domains.\n- Gap remediation roadmap maintained.\n\nApproved by: {{CEO_NAME}}`,
    content_ar: '',
    guidance_en: 'IMPLEMENTATION:\n1. Map existing controls to SAMA CSF domains (1-4).\n2. Conduct maturity assessment using SAMA self-assessment tool.\n3. Develop remediation roadmap prioritized by gap severity.\n4. Establish SAMA reporting procedures and templates.\n5. Train compliance team on SAMA CSF requirements.\n\nSAMA DEADLINES:\n- Self-assessment: Annual submission\n- Incident notification: 4 hours\n- Remediation plans: 30 days after finding',
    guidance_ar: '',
    variables: [V.ORG_NAME, V.EFFECTIVE_DATE, V.CEO_NAME],
    review_frequency: 'semi-annual',
    tags: ['SAMA','CSF','financial','banking','compliance'],
    sort_order: 20,
  },
];

export const MOM_FORMATS: Record<string, { title_en: string; title_ar: string; agenda_template: string[]; required_sections: string[] }> = {
  policy_review: {
    title_en: 'Policy Review Meeting',
    title_ar: 'اجتماع مراجعة السياسات',
    agenda_template: [
      'Opening and Quorum Confirmation',
      'Approval of Previous Meeting Minutes',
      'Policy Review Status Update',
      'Findings from Policy Gap Analysis',
      'Proposed Policy Changes',
      'Regulatory Updates and Impact',
      'Risk Assessment of Policy Changes',
      'Action Items and Assignments',
      'Next Meeting Date',
      'Closing',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
  policy_approval: {
    title_en: 'Policy Approval Committee Meeting',
    title_ar: 'اجتماع لجنة اعتماد السياسات',
    agenda_template: [
      'Opening and Quorum Confirmation',
      'Policies Submitted for Approval',
      'Review of Policy Content and Alignment',
      'Compliance Assessment Results',
      'Stakeholder Feedback Summary',
      'Approval Decisions',
      'Implementation Timeline',
      'Communication Plan',
      'Action Items',
      'Closing',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
  risk_review: {
    title_en: 'Risk Review Committee Meeting',
    title_ar: 'اجتماع لجنة مراجعة المخاطر',
    agenda_template: [
      'Opening and Quorum',
      'Previous Action Items Review',
      'Risk Register Updates',
      'New Risks Identified',
      'Risk Treatment Plan Progress',
      'Key Risk Indicators (KRI) Dashboard',
      'Emerging Threats Assessment',
      'Escalation Items',
      'Action Items',
      'Next Meeting',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
  compliance_review: {
    title_en: 'Compliance Review Meeting',
    title_ar: 'اجتماع مراجعة الامتثال',
    agenda_template: [
      'Opening',
      'Regulatory Updates (NCA/SAMA/PDPL)',
      'Compliance Status Dashboard',
      'Audit Findings Status',
      'Remediation Progress',
      'Non-Compliance Escalations',
      'Upcoming Compliance Deadlines',
      'Action Items',
      'Closing',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
  board_meeting: {
    title_en: 'Board of Directors Meeting',
    title_ar: 'اجتماع مجلس الإدارة',
    agenda_template: [
      'Call to Order and Quorum',
      'Approval of Previous Minutes',
      'Cybersecurity and GRC Executive Summary',
      'Risk Appetite Review',
      'Compliance Status Report',
      'Budget Review and Approval',
      'Strategic Initiatives Update',
      'Incident Summary (if any)',
      'Resolutions',
      'Next Meeting Date',
      'Adjournment',
    ],
    required_sections: ['attendees','absentees','agenda_items','decisions','action_items'],
  },
  steering_committee: {
    title_en: 'Information Security Steering Committee',
    title_ar: 'اجتماع لجنة توجيه أمن المعلومات',
    agenda_template: [
      'Opening',
      'Previous Actions Review',
      'Security Program Status',
      'Incident Summary',
      'Project Updates',
      'Resource Requirements',
      'Policy Updates Required',
      'Vendor Security Updates',
      'Decisions and Approvals',
      'Action Items',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
  audit_committee: {
    title_en: 'Audit Committee Meeting',
    title_ar: 'اجتماع لجنة التدقيق',
    agenda_template: [
      'Opening and Quorum',
      'Previous Minutes Approval',
      'Internal Audit Report',
      'External Audit Status',
      'Findings and Remediation Tracker',
      'Compliance Assessment Results',
      'Regulatory Examination Updates',
      'Audit Plan Review',
      'Decisions',
      'Closed Session',
      'Adjournment',
    ],
    required_sections: ['attendees','absentees','agenda_items','decisions','action_items'],
  },
  management_review: {
    title_en: 'Management Review Meeting (ISO)',
    title_ar: 'اجتماع مراجعة الإدارة',
    agenda_template: [
      'Opening',
      'Status of Previous Actions',
      'Changes in External/Internal Issues',
      'Information Security Performance Metrics',
      'Feedback from Interested Parties',
      'Risk Assessment Results',
      'Audit Results',
      'Opportunities for Improvement',
      'Resource Needs',
      'Decisions and Actions',
    ],
    required_sections: ['attendees','agenda_items','decisions','action_items'],
  },
};

export const WORKFLOW_STEPS = [
  { step_key: 'draft', step_order: 1, assigned_role: 'policy_writer', sla_hours: 120, is_required: true },
  { step_key: 'internal_review', step_order: 2, assigned_role: 'department_head', sla_hours: 72, is_required: true },
  { step_key: 'legal_review', step_order: 3, assigned_role: 'legal_counsel', sla_hours: 120, is_required: true },
  { step_key: 'compliance_review', step_order: 4, assigned_role: 'compliance_officer', sla_hours: 72, is_required: true },
  { step_key: 'management_approval', step_order: 5, assigned_role: 'ciso', sla_hours: 48, is_required: true },
  { step_key: 'board_approval', step_order: 6, assigned_role: 'board_member', sla_hours: 168, is_required: false },
  { step_key: 'publish', step_order: 7, assigned_role: 'policy_admin', sla_hours: 24, is_required: true },
  { step_key: 'distribute', step_order: 8, assigned_role: 'policy_admin', sla_hours: 48, is_required: true },
  { step_key: 'acknowledge', step_order: 9, assigned_role: 'all_employees', sla_hours: 336, is_required: true },
  { step_key: 'monitor', step_order: 10, assigned_role: 'compliance_officer', sla_hours: 0, is_required: true },
  { step_key: 'review', step_order: 11, assigned_role: 'policy_writer', sla_hours: 0, is_required: true },
  { step_key: 'update', step_order: 12, assigned_role: 'policy_writer', sla_hours: 120, is_required: false },
  { step_key: 'archive', step_order: 13, assigned_role: 'policy_admin', sla_hours: 24, is_required: false },
];
