import type { ApprovalRule } from '@dos/types';

export const RISK_APPROVAL_MATRIX: ApprovalRule[] = [
  {
    entityType: 'risk_assessments',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'risk.contributor',
    requiredPermission: 'risk.record.submit',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_assessments',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'risk.approver',
    requiredPermission: 'risk.record.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_assessments',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_assessments',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.close',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_assessments',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'risk.executive_owner',
    requiredPermission: 'risk.admin.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_scenarios',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'risk.contributor',
    requiredPermission: 'risk.record.submit',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_scenarios',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'risk.approver',
    requiredPermission: 'risk.record.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_scenarios',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.approve',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_scenarios',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.close',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_scenarios',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'risk.executive_owner',
    requiredPermission: 'risk.admin.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_kris',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'risk.contributor',
    requiredPermission: 'risk.record.submit',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_kris',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'risk.approver',
    requiredPermission: 'risk.kri.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_kris',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.kri.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_kris',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.kri.manage',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_kris',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'risk.executive_owner',
    requiredPermission: 'risk.admin.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_appetite_config',
    fromStatus: 'draft',
    toStatus: 'in_review',
    requiredRole: 'risk.contributor',
    requiredPermission: 'risk.record.submit',
    authorityLevel: 'optional',
    scopeRule: 'org',
    minApprovers: 0,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_appetite_config',
    fromStatus: 'in_review',
    toStatus: 'approved',
    requiredRole: 'risk.approver',
    requiredPermission: 'risk.record.configure',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_appetite_config',
    fromStatus: 'approved',
    toStatus: 'published',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.configure',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: true,
    commentsRequired: true,
  },
  {
    entityType: 'risk_appetite_config',
    fromStatus: 'published',
    toStatus: 'archived',
    requiredRole: 'risk.module_lead',
    requiredPermission: 'risk.record.configure',
    authorityLevel: 'recommended',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.module_lead', 'risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: true,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
  {
    entityType: 'risk_appetite_config',
    fromStatus: 'any',
    toStatus: 'suspended',
    requiredRole: 'risk.executive_owner',
    requiredPermission: 'risk.admin.manage',
    authorityLevel: 'required',
    scopeRule: 'org',
    minApprovers: 1,
    escalationPath: ['risk.executive_owner'],
    timeoutHours: 48,
    autoApproveAllowed: false,
    overrideRoles: ['risk.executive_owner'],
    evidenceRequired: false,
    commentsRequired: true,
  },
];
