-- Counter cleanup proposals for users.login_count
-- Generated by ops/normalization/scripts/counter-cleanup-plan.ts
-- Policy options: pick ONE. Do not apply without reviewing read-volume and trigger risk.

-- ═══ Option A: DROP the counter column; provide a view for on-demand COUNT(*) ═══
-- (child table not inferred; operator must pick it manually)
-- ALTER TABLE public.users DROP COLUMN login_count;

-- ═══ Option B: maintain via trigger on child table ═══
-- (child table not inferred)

-- ═══ Option C: keep column, reconcile nightly ═══
-- Schedule a job (e.g. pg_cron or application scheduler) that runs:
-- (reconcile SQL requires the child table to be identified first)
