-- FK rebuild proposals for active_alerts
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] active_alerts.alert_id -> action_alerts.id
ALTER TABLE public.active_alerts
  ADD CONSTRAINT fk_active_alerts_alert_id
  FOREIGN KEY (alert_id)
  REFERENCES public.action_alerts(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.active_alerts VALIDATE CONSTRAINT fk_active_alerts_alert_id;

-- [MEDIUM] active_alerts.correlation_id -> risk_correlations.id
ALTER TABLE public.active_alerts
  ADD CONSTRAINT fk_active_alerts_correlation_id
  FOREIGN KEY (correlation_id)
  REFERENCES public.risk_correlations(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.active_alerts VALIDATE CONSTRAINT fk_active_alerts_correlation_id;
