-- FK rebuild proposals for action_comments
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] action_comments.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.action_comments
  ADD CONSTRAINT fk_action_comments_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.action_comments VALIDATE CONSTRAINT fk_action_comments_entity_id;

-- [LOW] action_comments.parent_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [LOW] action_comments.author_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
