-- FK rebuild proposals for actors
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] actors.actor_id -> actors.actor_id
ALTER TABLE public.actors
  ADD CONSTRAINT fk_actors_actor_id
  FOREIGN KEY (actor_id)
  REFERENCES public.actors(actor_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.actors VALIDATE CONSTRAINT fk_actors_actor_id;

-- [HIGH] actors.user_id -> users.user_id
ALTER TABLE public.actors
  ADD CONSTRAINT fk_actors_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.actors VALIDATE CONSTRAINT fk_actors_user_id;
