-- FK rebuild proposals for agent_sod_policies
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] agent_sod_policies.policy_id -> policies.policy_id
ALTER TABLE __TENANT_SCHEMA__.agent_sod_policies
  ADD CONSTRAINT fk_agent_sod_policies_policy_id
  FOREIGN KEY (policy_id)
  REFERENCES __TENANT_SCHEMA__.policies(policy_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.agent_sod_policies VALIDATE CONSTRAINT fk_agent_sod_policies_policy_id;
