-- FK rebuild proposals for agent_feedback_log
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] agent_feedback_log.feedback_id -> feedback.id
ALTER TABLE __TENANT_SCHEMA__.agent_feedback_log
  ADD CONSTRAINT fk_agent_feedback_log_feedback_id
  FOREIGN KEY (feedback_id)
  REFERENCES __TENANT_SCHEMA__.feedback(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.agent_feedback_log VALIDATE CONSTRAINT fk_agent_feedback_log_feedback_id;

-- [LOW] agent_feedback_log.agent_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [MEDIUM] agent_feedback_log.task_id -> action_tasks.id
ALTER TABLE __TENANT_SCHEMA__.agent_feedback_log
  ADD CONSTRAINT fk_agent_feedback_log_task_id
  FOREIGN KEY (task_id)
  REFERENCES __TENANT_SCHEMA__.action_tasks(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.agent_feedback_log VALIDATE CONSTRAINT fk_agent_feedback_log_task_id;
