-- FK rebuild proposals for agrc_os_cycle_log
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] agrc_os_cycle_log.cycle_id -> onboarding_workspace_handoff_cycles.id
ALTER TABLE __TENANT_SCHEMA__.agrc_os_cycle_log
  ADD CONSTRAINT fk_agrc_os_cycle_log_cycle_id
  FOREIGN KEY (cycle_id)
  REFERENCES __TENANT_SCHEMA__.onboarding_workspace_handoff_cycles(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.agrc_os_cycle_log VALIDATE CONSTRAINT fk_agrc_os_cycle_log_cycle_id;
