-- FK rebuild proposals for agrc_tasks
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] agrc_tasks.task_id -> action_tasks.id
ALTER TABLE public.agrc_tasks
  ADD CONSTRAINT fk_agrc_tasks_task_id
  FOREIGN KEY (task_id)
  REFERENCES public.action_tasks(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.agrc_tasks VALIDATE CONSTRAINT fk_agrc_tasks_task_id;
