-- FK rebuild proposals for ai_governance_logs
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] ai_governance_logs.user_id -> users.user_id
ALTER TABLE __TENANT_SCHEMA__.ai_governance_logs
  ADD CONSTRAINT fk_ai_governance_logs_user_id
  FOREIGN KEY (user_id)
  REFERENCES __TENANT_SCHEMA__.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.ai_governance_logs VALIDATE CONSTRAINT fk_ai_governance_logs_user_id;
