-- FK rebuild proposals for ai_model_lifecycle
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] ai_model_lifecycle.lifecycle_id -> ai_model_lifecycle.lifecycle_id
ALTER TABLE __TENANT_SCHEMA__.ai_model_lifecycle
  ADD CONSTRAINT fk_ai_model_lifecycle_lifecycle_id
  FOREIGN KEY (lifecycle_id)
  REFERENCES __TENANT_SCHEMA__.ai_model_lifecycle(lifecycle_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.ai_model_lifecycle VALIDATE CONSTRAINT fk_ai_model_lifecycle_lifecycle_id;

-- [LOW] ai_model_lifecycle.model_version_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [LOW] ai_model_lifecycle.system_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
