-- FK rebuild proposals for ai_risk_assessments
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] ai_risk_assessments.model_id -> analytics_prediction_models.id
ALTER TABLE __TENANT_SCHEMA__.ai_risk_assessments
  ADD CONSTRAINT fk_ai_risk_assessments_model_id
  FOREIGN KEY (model_id)
  REFERENCES __TENANT_SCHEMA__.analytics_prediction_models(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.ai_risk_assessments VALIDATE CONSTRAINT fk_ai_risk_assessments_model_id;
