-- FK rebuild proposals for assets
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] assets.asset_id -> assets.asset_id
ALTER TABLE public.assets
  ADD CONSTRAINT fk_assets_asset_id
  FOREIGN KEY (asset_id)
  REFERENCES public.assets(asset_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.assets VALIDATE CONSTRAINT fk_assets_asset_id;

-- [MEDIUM] assets.owner_id -> risk_owners.id
ALTER TABLE public.assets
  ADD CONSTRAINT fk_assets_owner_id
  FOREIGN KEY (owner_id)
  REFERENCES public.risk_owners(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.assets VALIDATE CONSTRAINT fk_assets_owner_id;
