-- FK rebuild proposals for asset_compliance_mapping
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] asset_compliance_mapping.asset_id -> assets.asset_id
ALTER TABLE __TENANT_SCHEMA__.asset_compliance_mapping
  ADD CONSTRAINT fk_asset_compliance_mapping_asset_id
  FOREIGN KEY (asset_id)
  REFERENCES __TENANT_SCHEMA__.assets(asset_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.asset_compliance_mapping VALIDATE CONSTRAINT fk_asset_compliance_mapping_asset_id;

-- [HIGH] asset_compliance_mapping.framework_id -> frameworks.framework_id
ALTER TABLE __TENANT_SCHEMA__.asset_compliance_mapping
  ADD CONSTRAINT fk_asset_compliance_mapping_framework_id
  FOREIGN KEY (framework_id)
  REFERENCES __TENANT_SCHEMA__.frameworks(framework_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.asset_compliance_mapping VALIDATE CONSTRAINT fk_asset_compliance_mapping_framework_id;
