-- FK rebuild proposals for attestation_responses
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] attestation_responses.campaign_id -> access_review_campaigns.id
ALTER TABLE __TENANT_SCHEMA__.attestation_responses
  ADD CONSTRAINT fk_attestation_responses_campaign_id
  FOREIGN KEY (campaign_id)
  REFERENCES __TENANT_SCHEMA__.access_review_campaigns(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.attestation_responses VALIDATE CONSTRAINT fk_attestation_responses_campaign_id;

-- [LOW] attestation_responses.attestor_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [HIGH] attestation_responses.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.attestation_responses
  ADD CONSTRAINT fk_attestation_responses_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.attestation_responses VALIDATE CONSTRAINT fk_attestation_responses_entity_id;
