-- FK rebuild proposals for audit_capa
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] audit_capa.finding_id -> findings.finding_id
ALTER TABLE __TENANT_SCHEMA__.audit_capa
  ADD CONSTRAINT fk_audit_capa_finding_id
  FOREIGN KEY (finding_id)
  REFERENCES __TENANT_SCHEMA__.findings(finding_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.audit_capa VALIDATE CONSTRAINT fk_audit_capa_finding_id;
