-- FK rebuild proposals for autonomous_engine_log
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] autonomous_engine_log.log_id -> action_change_log.id
ALTER TABLE __TENANT_SCHEMA__.autonomous_engine_log
  ADD CONSTRAINT fk_autonomous_engine_log_log_id
  FOREIGN KEY (log_id)
  REFERENCES __TENANT_SCHEMA__.action_change_log(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.autonomous_engine_log VALIDATE CONSTRAINT fk_autonomous_engine_log_log_id;
