-- FK rebuild proposals for bcp_impact_analysis
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] bcp_impact_analysis.department_id -> departments.id
ALTER TABLE __TENANT_SCHEMA__.bcp_impact_analysis
  ADD CONSTRAINT fk_bcp_impact_analysis_department_id
  FOREIGN KEY (department_id)
  REFERENCES __TENANT_SCHEMA__.departments(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.bcp_impact_analysis VALIDATE CONSTRAINT fk_bcp_impact_analysis_department_id;
