-- FK rebuild proposals for bcp_crisis_communications
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] bcp_crisis_communications.plan_id -> audit_plan.plan_id
ALTER TABLE __TENANT_SCHEMA__.bcp_crisis_communications
  ADD CONSTRAINT fk_bcp_crisis_communications_plan_id
  FOREIGN KEY (plan_id)
  REFERENCES __TENANT_SCHEMA__.audit_plan(plan_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.bcp_crisis_communications VALIDATE CONSTRAINT fk_bcp_crisis_communications_plan_id;
