-- FK rebuild proposals for compliance_frameworks
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] compliance_frameworks.framework_id -> frameworks.framework_id
ALTER TABLE public.compliance_frameworks
  ADD CONSTRAINT fk_compliance_frameworks_framework_id
  FOREIGN KEY (framework_id)
  REFERENCES public.frameworks(framework_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.compliance_frameworks VALIDATE CONSTRAINT fk_compliance_frameworks_framework_id;
