-- FK rebuild proposals for compliance_monitoring
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] compliance_monitoring.requirement_id -> compliance_requirements.requirement_id
ALTER TABLE __TENANT_SCHEMA__.compliance_monitoring
  ADD CONSTRAINT fk_compliance_monitoring_requirement_id
  FOREIGN KEY (requirement_id)
  REFERENCES __TENANT_SCHEMA__.compliance_requirements(requirement_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.compliance_monitoring VALIDATE CONSTRAINT fk_compliance_monitoring_requirement_id;
