-- FK rebuild proposals for control_evidence_requirements
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] control_evidence_requirements.control_id -> controls.control_id
ALTER TABLE __TENANT_SCHEMA__.control_evidence_requirements
  ADD CONSTRAINT fk_control_evidence_requirements_control_id
  FOREIGN KEY (control_id)
  REFERENCES __TENANT_SCHEMA__.controls(control_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.control_evidence_requirements VALIDATE CONSTRAINT fk_control_evidence_requirements_control_id;

-- [MEDIUM] control_evidence_requirements.requirement_id -> compliance_requirements.requirement_id
ALTER TABLE __TENANT_SCHEMA__.control_evidence_requirements
  ADD CONSTRAINT fk_control_evidence_requirements_requirement_id
  FOREIGN KEY (requirement_id)
  REFERENCES __TENANT_SCHEMA__.compliance_requirements(requirement_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.control_evidence_requirements VALIDATE CONSTRAINT fk_control_evidence_requirements_requirement_id;
