-- FK rebuild proposals for dashboards
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] dashboards.dashboard_id -> dashboards.dashboard_id
ALTER TABLE public.dashboards
  ADD CONSTRAINT fk_dashboards_dashboard_id
  FOREIGN KEY (dashboard_id)
  REFERENCES public.dashboards(dashboard_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.dashboards VALIDATE CONSTRAINT fk_dashboards_dashboard_id;

-- [MEDIUM] dashboards.owner_id -> risk_owners.id
ALTER TABLE public.dashboards
  ADD CONSTRAINT fk_dashboards_owner_id
  FOREIGN KEY (owner_id)
  REFERENCES public.risk_owners(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.dashboards VALIDATE CONSTRAINT fk_dashboards_owner_id;
