-- FK rebuild proposals for dora_resilience_tests
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] dora_resilience_tests.ict_asset_id -> dora_ict_assets.id
ALTER TABLE __TENANT_SCHEMA__.dora_resilience_tests
  ADD CONSTRAINT fk_dora_resilience_tests_ict_asset_id
  FOREIGN KEY (ict_asset_id)
  REFERENCES __TENANT_SCHEMA__.dora_ict_assets(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.dora_resilience_tests VALIDATE CONSTRAINT fk_dora_resilience_tests_ict_asset_id;
