-- FK rebuild proposals for dos_handover_risks
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] dos_handover_risks.risk_id -> risks.risk_id
ALTER TABLE public.dos_handover_risks
  ADD CONSTRAINT fk_dos_handover_risks_risk_id
  FOREIGN KEY (risk_id)
  REFERENCES public.risks(risk_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.dos_handover_risks VALIDATE CONSTRAINT fk_dos_handover_risks_risk_id;

-- [MEDIUM] dos_handover_risks.release_id -> dos_releases.release_id
ALTER TABLE public.dos_handover_risks
  ADD CONSTRAINT fk_dos_handover_risks_release_id
  FOREIGN KEY (release_id)
  REFERENCES public.dos_releases(release_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.dos_handover_risks VALIDATE CONSTRAINT fk_dos_handover_risks_release_id;
