-- FK rebuild proposals for dos_compatibility_records
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [LOW] dos_compatibility_records.compatibility_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [MEDIUM] dos_compatibility_records.release_id -> dos_releases.release_id
ALTER TABLE public.dos_compatibility_records
  ADD CONSTRAINT fk_dos_compatibility_records_release_id
  FOREIGN KEY (release_id)
  REFERENCES public.dos_releases(release_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.dos_compatibility_records VALIDATE CONSTRAINT fk_dos_compatibility_records_release_id;

-- [LOW] dos_compatibility_records.breaking_change_approval_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
