-- FK rebuild proposals for editor_widgets
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] editor_widgets.layout_id -> dashboard_layouts.id
ALTER TABLE __TENANT_SCHEMA__.editor_widgets
  ADD CONSTRAINT fk_editor_widgets_layout_id
  FOREIGN KEY (layout_id)
  REFERENCES __TENANT_SCHEMA__.dashboard_layouts(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.editor_widgets VALIDATE CONSTRAINT fk_editor_widgets_layout_id;
