-- FK rebuild proposals for enforcement_runs
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] enforcement_runs.run_id -> dos_verification_runs.run_id
ALTER TABLE public.enforcement_runs
  ADD CONSTRAINT fk_enforcement_runs_run_id
  FOREIGN KEY (run_id)
  REFERENCES public.dos_verification_runs(run_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.enforcement_runs VALIDATE CONSTRAINT fk_enforcement_runs_run_id;
