-- FK rebuild proposals for evidence_tasks
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] evidence_tasks.control_id -> controls.control_id
ALTER TABLE __TENANT_SCHEMA__.evidence_tasks
  ADD CONSTRAINT fk_evidence_tasks_control_id
  FOREIGN KEY (control_id)
  REFERENCES __TENANT_SCHEMA__.controls(control_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_tasks VALIDATE CONSTRAINT fk_evidence_tasks_control_id;

-- [MEDIUM] evidence_tasks.evidence_requirement_id -> control_evidence_requirements.id
ALTER TABLE __TENANT_SCHEMA__.evidence_tasks
  ADD CONSTRAINT fk_evidence_tasks_evidence_requirement_id
  FOREIGN KEY (evidence_requirement_id)
  REFERENCES __TENANT_SCHEMA__.control_evidence_requirements(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_tasks VALIDATE CONSTRAINT fk_evidence_tasks_evidence_requirement_id;

-- [HIGH] evidence_tasks.workspace_id -> workspaces.workspace_id
ALTER TABLE __TENANT_SCHEMA__.evidence_tasks
  ADD CONSTRAINT fk_evidence_tasks_workspace_id
  FOREIGN KEY (workspace_id)
  REFERENCES __TENANT_SCHEMA__.workspaces(workspace_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_tasks VALIDATE CONSTRAINT fk_evidence_tasks_workspace_id;
