-- FK rebuild proposals for evidence_control_links
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] evidence_control_links.evidence_id -> evidence.evidence_id
ALTER TABLE __TENANT_SCHEMA__.evidence_control_links
  ADD CONSTRAINT fk_evidence_control_links_evidence_id
  FOREIGN KEY (evidence_id)
  REFERENCES __TENANT_SCHEMA__.evidence(evidence_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_control_links VALIDATE CONSTRAINT fk_evidence_control_links_evidence_id;

-- [HIGH] evidence_control_links.control_id -> controls.control_id
ALTER TABLE __TENANT_SCHEMA__.evidence_control_links
  ADD CONSTRAINT fk_evidence_control_links_control_id
  FOREIGN KEY (control_id)
  REFERENCES __TENANT_SCHEMA__.controls(control_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_control_links VALIDATE CONSTRAINT fk_evidence_control_links_control_id;
