-- FK rebuild proposals for evidence_automated_collection
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] evidence_automated_collection.rule_id -> ai_alert_rules.id
ALTER TABLE __TENANT_SCHEMA__.evidence_automated_collection
  ADD CONSTRAINT fk_evidence_automated_collection_rule_id
  FOREIGN KEY (rule_id)
  REFERENCES __TENANT_SCHEMA__.ai_alert_rules(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.evidence_automated_collection VALIDATE CONSTRAINT fk_evidence_automated_collection_rule_id;
