-- FK rebuild proposals for findings
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] findings.finding_id -> findings.finding_id
ALTER TABLE __TENANT_SCHEMA__.findings
  ADD CONSTRAINT fk_findings_finding_id
  FOREIGN KEY (finding_id)
  REFERENCES __TENANT_SCHEMA__.findings(finding_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.findings VALIDATE CONSTRAINT fk_findings_finding_id;
