-- FK rebuild proposals for governance_reviews
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] governance_reviews.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.governance_reviews
  ADD CONSTRAINT fk_governance_reviews_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.governance_reviews VALIDATE CONSTRAINT fk_governance_reviews_entity_id;

-- [MEDIUM] governance_reviews.reviewer_id -> evidence_reviewers.id
ALTER TABLE __TENANT_SCHEMA__.governance_reviews
  ADD CONSTRAINT fk_governance_reviews_reviewer_id
  FOREIGN KEY (reviewer_id)
  REFERENCES __TENANT_SCHEMA__.evidence_reviewers(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.governance_reviews VALIDATE CONSTRAINT fk_governance_reviews_reviewer_id;
