-- FK rebuild proposals for grc_query_tags
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] grc_query_tags.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.grc_query_tags
  ADD CONSTRAINT fk_grc_query_tags_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.grc_query_tags VALIDATE CONSTRAINT fk_grc_query_tags_entity_id;
