-- FK rebuild proposals for incident_trend_cache
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] incident_trend_cache.cache_id -> dashboard_data_cache.id
ALTER TABLE __TENANT_SCHEMA__.incident_trend_cache
  ADD CONSTRAINT fk_incident_trend_cache_cache_id
  FOREIGN KEY (cache_id)
  REFERENCES __TENANT_SCHEMA__.dashboard_data_cache(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_trend_cache VALIDATE CONSTRAINT fk_incident_trend_cache_cache_id;
