-- FK rebuild proposals for incident_response_actions
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] incident_response_actions.action_id -> action_actions.id
ALTER TABLE __TENANT_SCHEMA__.incident_response_actions
  ADD CONSTRAINT fk_incident_response_actions_action_id
  FOREIGN KEY (action_id)
  REFERENCES __TENANT_SCHEMA__.action_actions(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_response_actions VALIDATE CONSTRAINT fk_incident_response_actions_action_id;

-- [HIGH] incident_response_actions.incident_id -> incidents.incident_id
ALTER TABLE __TENANT_SCHEMA__.incident_response_actions
  ADD CONSTRAINT fk_incident_response_actions_incident_id
  FOREIGN KEY (incident_id)
  REFERENCES __TENANT_SCHEMA__.incidents(incident_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_response_actions VALIDATE CONSTRAINT fk_incident_response_actions_incident_id;
