-- FK rebuild proposals for incident_assets
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] incident_assets.incident_id -> incidents.incident_id
ALTER TABLE __TENANT_SCHEMA__.incident_assets
  ADD CONSTRAINT fk_incident_assets_incident_id
  FOREIGN KEY (incident_id)
  REFERENCES __TENANT_SCHEMA__.incidents(incident_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_assets VALIDATE CONSTRAINT fk_incident_assets_incident_id;

-- [HIGH] incident_assets.asset_id -> assets.asset_id
ALTER TABLE __TENANT_SCHEMA__.incident_assets
  ADD CONSTRAINT fk_incident_assets_asset_id
  FOREIGN KEY (asset_id)
  REFERENCES __TENANT_SCHEMA__.assets(asset_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_assets VALIDATE CONSTRAINT fk_incident_assets_asset_id;
