-- FK rebuild proposals for incident_reportable_criteria
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] incident_reportable_criteria.criteria_id -> incident_reportable_criteria.criteria_id
ALTER TABLE __TENANT_SCHEMA__.incident_reportable_criteria
  ADD CONSTRAINT fk_incident_reportable_criteria_criteria_id
  FOREIGN KEY (criteria_id)
  REFERENCES __TENANT_SCHEMA__.incident_reportable_criteria(criteria_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_reportable_criteria VALIDATE CONSTRAINT fk_incident_reportable_criteria_criteria_id;
