-- FK rebuild proposals for incident_audit_log
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] incident_audit_log.log_id -> action_change_log.id
ALTER TABLE __TENANT_SCHEMA__.incident_audit_log
  ADD CONSTRAINT fk_incident_audit_log_log_id
  FOREIGN KEY (log_id)
  REFERENCES __TENANT_SCHEMA__.action_change_log(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_audit_log VALIDATE CONSTRAINT fk_incident_audit_log_log_id;

-- [HIGH] incident_audit_log.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.incident_audit_log
  ADD CONSTRAINT fk_incident_audit_log_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_audit_log VALIDATE CONSTRAINT fk_incident_audit_log_entity_id;

-- [HIGH] incident_audit_log.actor_id -> actors.actor_id
ALTER TABLE __TENANT_SCHEMA__.incident_audit_log
  ADD CONSTRAINT fk_incident_audit_log_actor_id
  FOREIGN KEY (actor_id)
  REFERENCES __TENANT_SCHEMA__.actors(actor_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_audit_log VALIDATE CONSTRAINT fk_incident_audit_log_actor_id;
