-- FK rebuild proposals for incident_regulatory_notifications
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] incident_regulatory_notifications.notification_id -> notifications.notification_id
ALTER TABLE __TENANT_SCHEMA__.incident_regulatory_notifications
  ADD CONSTRAINT fk_incident_regulatory_notifications_notification_id
  FOREIGN KEY (notification_id)
  REFERENCES __TENANT_SCHEMA__.notifications(notification_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_regulatory_notifications VALIDATE CONSTRAINT fk_incident_regulatory_notifications_notification_id;

-- [HIGH] incident_regulatory_notifications.incident_id -> incidents.incident_id
ALTER TABLE __TENANT_SCHEMA__.incident_regulatory_notifications
  ADD CONSTRAINT fk_incident_regulatory_notifications_incident_id
  FOREIGN KEY (incident_id)
  REFERENCES __TENANT_SCHEMA__.incidents(incident_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_regulatory_notifications VALIDATE CONSTRAINT fk_incident_regulatory_notifications_incident_id;
