-- FK rebuild proposals for incident_risk_links
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] incident_risk_links.link_id -> governance_policies_link.id
ALTER TABLE __TENANT_SCHEMA__.incident_risk_links
  ADD CONSTRAINT fk_incident_risk_links_link_id
  FOREIGN KEY (link_id)
  REFERENCES __TENANT_SCHEMA__.governance_policies_link(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_risk_links VALIDATE CONSTRAINT fk_incident_risk_links_link_id;

-- [HIGH] incident_risk_links.incident_id -> incidents.incident_id
ALTER TABLE __TENANT_SCHEMA__.incident_risk_links
  ADD CONSTRAINT fk_incident_risk_links_incident_id
  FOREIGN KEY (incident_id)
  REFERENCES __TENANT_SCHEMA__.incidents(incident_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_risk_links VALIDATE CONSTRAINT fk_incident_risk_links_incident_id;

-- [HIGH] incident_risk_links.risk_id -> risks.risk_id
ALTER TABLE __TENANT_SCHEMA__.incident_risk_links
  ADD CONSTRAINT fk_incident_risk_links_risk_id
  FOREIGN KEY (risk_id)
  REFERENCES __TENANT_SCHEMA__.risks(risk_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.incident_risk_links VALIDATE CONSTRAINT fk_incident_risk_links_risk_id;
