-- FK rebuild proposals for issues_register
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] issues_register.source_id -> analytics_data_sources.id
ALTER TABLE __TENANT_SCHEMA__.issues_register
  ADD CONSTRAINT fk_issues_register_source_id
  FOREIGN KEY (source_id)
  REFERENCES __TENANT_SCHEMA__.analytics_data_sources(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.issues_register VALIDATE CONSTRAINT fk_issues_register_source_id;
