-- FK rebuild proposals for knowledge_logs
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] knowledge_logs.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.knowledge_logs
  ADD CONSTRAINT fk_knowledge_logs_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.knowledge_logs VALIDATE CONSTRAINT fk_knowledge_logs_entity_id;

-- [HIGH] knowledge_logs.actor_id -> actors.actor_id
ALTER TABLE __TENANT_SCHEMA__.knowledge_logs
  ADD CONSTRAINT fk_knowledge_logs_actor_id
  FOREIGN KEY (actor_id)
  REFERENCES __TENANT_SCHEMA__.actors(actor_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.knowledge_logs VALIDATE CONSTRAINT fk_knowledge_logs_actor_id;
