-- FK rebuild proposals for lifecycle_checkpoints
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] lifecycle_checkpoints.entity_id -> entities.id
ALTER TABLE public.lifecycle_checkpoints
  ADD CONSTRAINT fk_lifecycle_checkpoints_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES public.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.lifecycle_checkpoints VALIDATE CONSTRAINT fk_lifecycle_checkpoints_entity_id;
