-- FK rebuild proposals for mcp_prompts
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] mcp_prompts.prompt_id -> mcp_prompts.prompt_id
ALTER TABLE __TENANT_SCHEMA__.mcp_prompts
  ADD CONSTRAINT fk_mcp_prompts_prompt_id
  FOREIGN KEY (prompt_id)
  REFERENCES __TENANT_SCHEMA__.mcp_prompts(prompt_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.mcp_prompts VALIDATE CONSTRAINT fk_mcp_prompts_prompt_id;

-- [MEDIUM] mcp_prompts.server_id -> mcp_servers.server_id
ALTER TABLE __TENANT_SCHEMA__.mcp_prompts
  ADD CONSTRAINT fk_mcp_prompts_server_id
  FOREIGN KEY (server_id)
  REFERENCES __TENANT_SCHEMA__.mcp_servers(server_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.mcp_prompts VALIDATE CONSTRAINT fk_mcp_prompts_server_id;
