-- FK rebuild proposals for mcp_resource_registry
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] mcp_resource_registry.resource_id -> audit_resources.id
ALTER TABLE public.mcp_resource_registry
  ADD CONSTRAINT fk_mcp_resource_registry_resource_id
  FOREIGN KEY (resource_id)
  REFERENCES public.audit_resources(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.mcp_resource_registry VALIDATE CONSTRAINT fk_mcp_resource_registry_resource_id;
