-- FK rebuild proposals for mcp_prompt_registry
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] mcp_prompt_registry.prompt_id -> mcp_prompts.prompt_id
ALTER TABLE public.mcp_prompt_registry
  ADD CONSTRAINT fk_mcp_prompt_registry_prompt_id
  FOREIGN KEY (prompt_id)
  REFERENCES public.mcp_prompts(prompt_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.mcp_prompt_registry VALIDATE CONSTRAINT fk_mcp_prompt_registry_prompt_id;

-- [LOW] mcp_prompt_registry.agent_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
