-- FK rebuild proposals for mcp_tool_registry
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] mcp_tool_registry.tool_id -> mcp_tools.tool_id
ALTER TABLE public.mcp_tool_registry
  ADD CONSTRAINT fk_mcp_tool_registry_tool_id
  FOREIGN KEY (tool_id)
  REFERENCES public.mcp_tools(tool_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.mcp_tool_registry VALIDATE CONSTRAINT fk_mcp_tool_registry_tool_id;

-- [LOW] mcp_tool_registry.agent_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
