-- FK rebuild proposals for notification_delivery_log
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] notification_delivery_log.user_id -> users.user_id
ALTER TABLE __TENANT_SCHEMA__.notification_delivery_log
  ADD CONSTRAINT fk_notification_delivery_log_user_id
  FOREIGN KEY (user_id)
  REFERENCES __TENANT_SCHEMA__.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.notification_delivery_log VALIDATE CONSTRAINT fk_notification_delivery_log_user_id;
