-- FK rebuild proposals for pdpl_consents
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] pdpl_consents.user_id -> users.user_id
ALTER TABLE public.pdpl_consents
  ADD CONSTRAINT fk_pdpl_consents_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.pdpl_consents VALIDATE CONSTRAINT fk_pdpl_consents_user_id;
