-- FK rebuild proposals for person_profiles
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] person_profiles.person_id -> person_profiles.id
ALTER TABLE __TENANT_SCHEMA__.person_profiles
  ADD CONSTRAINT fk_person_profiles_person_id
  FOREIGN KEY (person_id)
  REFERENCES __TENANT_SCHEMA__.person_profiles(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.person_profiles VALIDATE CONSTRAINT fk_person_profiles_person_id;

-- [HIGH] person_profiles.department_id -> departments.id
ALTER TABLE __TENANT_SCHEMA__.person_profiles
  ADD CONSTRAINT fk_person_profiles_department_id
  FOREIGN KEY (department_id)
  REFERENCES __TENANT_SCHEMA__.departments(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.person_profiles VALIDATE CONSTRAINT fk_person_profiles_department_id;

-- [LOW] person_profiles.manager_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [LOW] person_profiles.direct_manager_user_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
