-- FK rebuild proposals for pir_sign_offs
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] pir_sign_offs.sign_off_id -> pir_sign_offs.sign_off_id
ALTER TABLE __TENANT_SCHEMA__.pir_sign_offs
  ADD CONSTRAINT fk_pir_sign_offs_sign_off_id
  FOREIGN KEY (sign_off_id)
  REFERENCES __TENANT_SCHEMA__.pir_sign_offs(sign_off_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.pir_sign_offs VALIDATE CONSTRAINT fk_pir_sign_offs_sign_off_id;

-- [MEDIUM] pir_sign_offs.pir_id -> incident_pir.pir_id
ALTER TABLE __TENANT_SCHEMA__.pir_sign_offs
  ADD CONSTRAINT fk_pir_sign_offs_pir_id
  FOREIGN KEY (pir_id)
  REFERENCES __TENANT_SCHEMA__.incident_pir(pir_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.pir_sign_offs VALIDATE CONSTRAINT fk_pir_sign_offs_pir_id;

-- [LOW] pir_sign_offs.signer_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
