-- FK rebuild proposals for platform_outbox_archive
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [LOW] platform_outbox_archive.aggregate_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
