-- FK rebuild proposals for privacy_assessments
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] privacy_assessments.assessment_id -> assessments.assessment_id
ALTER TABLE public.privacy_assessments
  ADD CONSTRAINT fk_privacy_assessments_assessment_id
  FOREIGN KEY (assessment_id)
  REFERENCES public.assessments(assessment_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.privacy_assessments VALIDATE CONSTRAINT fk_privacy_assessments_assessment_id;

-- [MEDIUM] privacy_assessments.owner_id -> risk_owners.id
ALTER TABLE public.privacy_assessments
  ADD CONSTRAINT fk_privacy_assessments_owner_id
  FOREIGN KEY (owner_id)
  REFERENCES public.risk_owners(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.privacy_assessments VALIDATE CONSTRAINT fk_privacy_assessments_owner_id;
