-- FK rebuild proposals for privacy_dpia
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] privacy_dpia.activity_id -> action_activities.id
ALTER TABLE __TENANT_SCHEMA__.privacy_dpia
  ADD CONSTRAINT fk_privacy_dpia_activity_id
  FOREIGN KEY (activity_id)
  REFERENCES __TENANT_SCHEMA__.action_activities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.privacy_dpia VALIDATE CONSTRAINT fk_privacy_dpia_activity_id;

-- [LOW] privacy_dpia.assessor_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
