-- FK rebuild proposals for provisioning_telemetry
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] provisioning_telemetry.run_id -> dos_verification_runs.run_id
ALTER TABLE public.provisioning_telemetry
  ADD CONSTRAINT fk_provisioning_telemetry_run_id
  FOREIGN KEY (run_id)
  REFERENCES public.dos_verification_runs(run_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.provisioning_telemetry VALIDATE CONSTRAINT fk_provisioning_telemetry_run_id;
