-- FK rebuild proposals for qiyas_improvement_plans
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] qiyas_improvement_plans.assessment_id -> assessments.assessment_id
ALTER TABLE __TENANT_SCHEMA__.qiyas_improvement_plans
  ADD CONSTRAINT fk_qiyas_improvement_plans_assessment_id
  FOREIGN KEY (assessment_id)
  REFERENCES __TENANT_SCHEMA__.assessments(assessment_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.qiyas_improvement_plans VALIDATE CONSTRAINT fk_qiyas_improvement_plans_assessment_id;

-- [MEDIUM] qiyas_improvement_plans.owner_id -> risk_owners.id
ALTER TABLE __TENANT_SCHEMA__.qiyas_improvement_plans
  ADD CONSTRAINT fk_qiyas_improvement_plans_owner_id
  FOREIGN KEY (owner_id)
  REFERENCES __TENANT_SCHEMA__.risk_owners(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.qiyas_improvement_plans VALIDATE CONSTRAINT fk_qiyas_improvement_plans_owner_id;
