-- FK rebuild proposals for records
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] records.record_id -> records.record_id
ALTER TABLE public.records
  ADD CONSTRAINT fk_records_record_id
  FOREIGN KEY (record_id)
  REFERENCES public.records(record_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.records VALIDATE CONSTRAINT fk_records_record_id;

-- [MEDIUM] records.owner_id -> risk_owners.id
ALTER TABLE public.records
  ADD CONSTRAINT fk_records_owner_id
  FOREIGN KEY (owner_id)
  REFERENCES public.risk_owners(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.records VALIDATE CONSTRAINT fk_records_owner_id;
