-- FK rebuild proposals for records_lifecycle
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] records_lifecycle.record_id -> records.record_id
ALTER TABLE __TENANT_SCHEMA__.records_lifecycle
  ADD CONSTRAINT fk_records_lifecycle_record_id
  FOREIGN KEY (record_id)
  REFERENCES __TENANT_SCHEMA__.records(record_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.records_lifecycle VALIDATE CONSTRAINT fk_records_lifecycle_record_id;
