-- FK rebuild proposals for regulatory_mappings
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] regulatory_mappings.entity_id -> entities.id
ALTER TABLE __TENANT_SCHEMA__.regulatory_mappings
  ADD CONSTRAINT fk_regulatory_mappings_entity_id
  FOREIGN KEY (entity_id)
  REFERENCES __TENANT_SCHEMA__.entities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.regulatory_mappings VALIDATE CONSTRAINT fk_regulatory_mappings_entity_id;
