-- FK rebuild proposals for remediation_root_causes
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] remediation_root_causes.plan_id -> audit_plan.plan_id
ALTER TABLE __TENANT_SCHEMA__.remediation_root_causes
  ADD CONSTRAINT fk_remediation_root_causes_plan_id
  FOREIGN KEY (plan_id)
  REFERENCES __TENANT_SCHEMA__.audit_plan(plan_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.remediation_root_causes VALIDATE CONSTRAINT fk_remediation_root_causes_plan_id;
