-- FK rebuild proposals for risk_status_history
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] risk_status_history.history_id -> action_history.id
ALTER TABLE __TENANT_SCHEMA__.risk_status_history
  ADD CONSTRAINT fk_risk_status_history_history_id
  FOREIGN KEY (history_id)
  REFERENCES __TENANT_SCHEMA__.action_history(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_status_history VALIDATE CONSTRAINT fk_risk_status_history_history_id;

-- [HIGH] risk_status_history.risk_id -> risks.risk_id
ALTER TABLE __TENANT_SCHEMA__.risk_status_history
  ADD CONSTRAINT fk_risk_status_history_risk_id
  FOREIGN KEY (risk_id)
  REFERENCES __TENANT_SCHEMA__.risks(risk_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_status_history VALIDATE CONSTRAINT fk_risk_status_history_risk_id;
