-- FK rebuild proposals for risk_dependencies
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] risk_dependencies.dependency_id -> action_dependencies.id
ALTER TABLE __TENANT_SCHEMA__.risk_dependencies
  ADD CONSTRAINT fk_risk_dependencies_dependency_id
  FOREIGN KEY (dependency_id)
  REFERENCES __TENANT_SCHEMA__.action_dependencies(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_dependencies VALIDATE CONSTRAINT fk_risk_dependencies_dependency_id;

-- [HIGH] risk_dependencies.risk_id -> risks.risk_id
ALTER TABLE __TENANT_SCHEMA__.risk_dependencies
  ADD CONSTRAINT fk_risk_dependencies_risk_id
  FOREIGN KEY (risk_id)
  REFERENCES __TENANT_SCHEMA__.risks(risk_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_dependencies VALIDATE CONSTRAINT fk_risk_dependencies_risk_id;

-- [LOW] risk_dependencies.dependent_risk_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
