-- FK rebuild proposals for risk_treatment_actions
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] risk_treatment_actions.action_id -> action_actions.id
ALTER TABLE __TENANT_SCHEMA__.risk_treatment_actions
  ADD CONSTRAINT fk_risk_treatment_actions_action_id
  FOREIGN KEY (action_id)
  REFERENCES __TENANT_SCHEMA__.action_actions(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_treatment_actions VALIDATE CONSTRAINT fk_risk_treatment_actions_action_id;

-- [MEDIUM] risk_treatment_actions.treatment_id -> risk_treatments.id
ALTER TABLE __TENANT_SCHEMA__.risk_treatment_actions
  ADD CONSTRAINT fk_risk_treatment_actions_treatment_id
  FOREIGN KEY (treatment_id)
  REFERENCES __TENANT_SCHEMA__.risk_treatments(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_treatment_actions VALIDATE CONSTRAINT fk_risk_treatment_actions_treatment_id;
