-- FK rebuild proposals for risk_appetite_config
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [LOW] risk_appetite_config.appetite_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.

-- [HIGH] risk_appetite_config.workspace_id -> workspaces.workspace_id
ALTER TABLE __TENANT_SCHEMA__.risk_appetite_config
  ADD CONSTRAINT fk_risk_appetite_config_workspace_id
  FOREIGN KEY (workspace_id)
  REFERENCES __TENANT_SCHEMA__.workspaces(workspace_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_appetite_config VALIDATE CONSTRAINT fk_risk_appetite_config_workspace_id;
