-- FK rebuild proposals for risk_impact_scales
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] risk_impact_scales.scale_id -> qiyas_rating_scales.id
ALTER TABLE __TENANT_SCHEMA__.risk_impact_scales
  ADD CONSTRAINT fk_risk_impact_scales_scale_id
  FOREIGN KEY (scale_id)
  REFERENCES __TENANT_SCHEMA__.qiyas_rating_scales(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_impact_scales VALIDATE CONSTRAINT fk_risk_impact_scales_scale_id;

-- [MEDIUM] risk_impact_scales.taxonomy_id -> incident_taxonomy.node_id
ALTER TABLE __TENANT_SCHEMA__.risk_impact_scales
  ADD CONSTRAINT fk_risk_impact_scales_taxonomy_id
  FOREIGN KEY (taxonomy_id)
  REFERENCES __TENANT_SCHEMA__.incident_taxonomy(node_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.risk_impact_scales VALIDATE CONSTRAINT fk_risk_impact_scales_taxonomy_id;
