-- FK rebuild proposals for role_permissions
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] role_permissions.functional_role_id -> functional_roles.id
ALTER TABLE public.role_permissions
  ADD CONSTRAINT fk_role_permissions_functional_role_id
  FOREIGN KEY (functional_role_id)
  REFERENCES public.functional_roles(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.role_permissions VALIDATE CONSTRAINT fk_role_permissions_functional_role_id;

-- [HIGH] role_permissions.permission_id -> permissions.id
ALTER TABLE public.role_permissions
  ADD CONSTRAINT fk_role_permissions_permission_id
  FOREIGN KEY (permission_id)
  REFERENCES public.permissions(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.role_permissions VALIDATE CONSTRAINT fk_role_permissions_permission_id;
