-- FK rebuild proposals for sessions
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] sessions.session_id -> sessions.session_id
ALTER TABLE public.sessions
  ADD CONSTRAINT fk_sessions_session_id
  FOREIGN KEY (session_id)
  REFERENCES public.sessions(session_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.sessions VALIDATE CONSTRAINT fk_sessions_session_id;

-- [HIGH] sessions.user_id -> users.user_id
ALTER TABLE public.sessions
  ADD CONSTRAINT fk_sessions_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.sessions VALIDATE CONSTRAINT fk_sessions_user_id;
