-- FK rebuild proposals for startup_checklist
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] startup_checklist.session_id -> sessions.session_id
ALTER TABLE public.startup_checklist
  ADD CONSTRAINT fk_startup_checklist_session_id
  FOREIGN KEY (session_id)
  REFERENCES public.sessions(session_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.startup_checklist VALIDATE CONSTRAINT fk_startup_checklist_session_id;
