-- FK rebuild proposals for team_members
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] team_members.team_id -> teams.id
ALTER TABLE public.team_members
  ADD CONSTRAINT fk_team_members_team_id
  FOREIGN KEY (team_id)
  REFERENCES public.teams(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.team_members VALIDATE CONSTRAINT fk_team_members_team_id;

-- [HIGH] team_members.user_id -> users.user_id
ALTER TABLE public.team_members
  ADD CONSTRAINT fk_team_members_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.team_members VALIDATE CONSTRAINT fk_team_members_user_id;
