-- FK rebuild proposals for tenant_nudges
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] tenant_nudges.nudge_id -> tenant_nudges.nudge_id
ALTER TABLE __TENANT_SCHEMA__.tenant_nudges
  ADD CONSTRAINT fk_tenant_nudges_nudge_id
  FOREIGN KEY (nudge_id)
  REFERENCES __TENANT_SCHEMA__.tenant_nudges(nudge_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.tenant_nudges VALIDATE CONSTRAINT fk_tenant_nudges_nudge_id;
