-- FK rebuild proposals for tenant_migrations
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] tenant_migrations.migration_id -> dos_migrations.migration_id
ALTER TABLE public.tenant_migrations
  ADD CONSTRAINT fk_tenant_migrations_migration_id
  FOREIGN KEY (migration_id)
  REFERENCES public.dos_migrations(migration_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.tenant_migrations VALIDATE CONSTRAINT fk_tenant_migrations_migration_id;
