-- FK rebuild proposals for tenant_module_entitlements
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] tenant_module_entitlements.entitlement_id -> tenant_module_entitlements.entitlement_id
ALTER TABLE public.tenant_module_entitlements
  ADD CONSTRAINT fk_tenant_module_entitlements_entitlement_id
  FOREIGN KEY (entitlement_id)
  REFERENCES public.tenant_module_entitlements(entitlement_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.tenant_module_entitlements VALIDATE CONSTRAINT fk_tenant_module_entitlements_entitlement_id;
