-- FK rebuild proposals for training_enrollments
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] training_enrollments.enrollment_id -> training_enrollments.enrollment_id
ALTER TABLE public.training_enrollments
  ADD CONSTRAINT fk_training_enrollments_enrollment_id
  FOREIGN KEY (enrollment_id)
  REFERENCES public.training_enrollments(enrollment_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.training_enrollments VALIDATE CONSTRAINT fk_training_enrollments_enrollment_id;

-- [MEDIUM] training_enrollments.course_id -> training_courses.course_id
ALTER TABLE public.training_enrollments
  ADD CONSTRAINT fk_training_enrollments_course_id
  FOREIGN KEY (course_id)
  REFERENCES public.training_courses(course_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.training_enrollments VALIDATE CONSTRAINT fk_training_enrollments_course_id;

-- [HIGH] training_enrollments.user_id -> users.user_id
ALTER TABLE public.training_enrollments
  ADD CONSTRAINT fk_training_enrollments_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.training_enrollments VALIDATE CONSTRAINT fk_training_enrollments_user_id;
