-- FK rebuild proposals for unresolved_risks
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] unresolved_risks.risk_id -> risks.risk_id
ALTER TABLE public.unresolved_risks
  ADD CONSTRAINT fk_unresolved_risks_risk_id
  FOREIGN KEY (risk_id)
  REFERENCES public.risks(risk_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.unresolved_risks VALIDATE CONSTRAINT fk_unresolved_risks_risk_id;
