-- FK rebuild proposals for user_mfa
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] user_mfa.user_id -> users.user_id
ALTER TABLE public.user_mfa
  ADD CONSTRAINT fk_user_mfa_user_id
  FOREIGN KEY (user_id)
  REFERENCES public.users(user_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE public.user_mfa VALIDATE CONSTRAINT fk_user_mfa_user_id;
