-- FK rebuild proposals for vendor_offboarding
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] vendor_offboarding.vendor_id -> vendors.vendor_id
ALTER TABLE __TENANT_SCHEMA__.vendor_offboarding
  ADD CONSTRAINT fk_vendor_offboarding_vendor_id
  FOREIGN KEY (vendor_id)
  REFERENCES __TENANT_SCHEMA__.vendors(vendor_id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.vendor_offboarding VALIDATE CONSTRAINT fk_vendor_offboarding_vendor_id;
