-- FK rebuild proposals for vulnerabilities
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [HIGH] vulnerabilities.vulnerability_id -> vulnerabilities.id
ALTER TABLE __TENANT_SCHEMA__.vulnerabilities
  ADD CONSTRAINT fk_vulnerabilities_vulnerability_id
  FOREIGN KEY (vulnerability_id)
  REFERENCES __TENANT_SCHEMA__.vulnerabilities(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.vulnerabilities VALIDATE CONSTRAINT fk_vulnerabilities_vulnerability_id;
