-- FK rebuild proposals for workflow_notifications
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] workflow_notifications.instance_id -> plan_item_instances.id
ALTER TABLE __TENANT_SCHEMA__.workflow_notifications
  ADD CONSTRAINT fk_workflow_notifications_instance_id
  FOREIGN KEY (instance_id)
  REFERENCES __TENANT_SCHEMA__.plan_item_instances(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.workflow_notifications VALIDATE CONSTRAINT fk_workflow_notifications_instance_id;

-- [MEDIUM] workflow_notifications.step_id -> provisioning_steps.id
ALTER TABLE __TENANT_SCHEMA__.workflow_notifications
  ADD CONSTRAINT fk_workflow_notifications_step_id
  FOREIGN KEY (step_id)
  REFERENCES __TENANT_SCHEMA__.provisioning_steps(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.workflow_notifications VALIDATE CONSTRAINT fk_workflow_notifications_step_id;

-- [MEDIUM] workflow_notifications.recipient_id -> reporting_recipients.id
ALTER TABLE __TENANT_SCHEMA__.workflow_notifications
  ADD CONSTRAINT fk_workflow_notifications_recipient_id
  FOREIGN KEY (recipient_id)
  REFERENCES __TENANT_SCHEMA__.reporting_recipients(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.workflow_notifications VALIDATE CONSTRAINT fk_workflow_notifications_recipient_id;
