-- FK rebuild proposals for workflow_task_assignments
-- Generated by ops/normalization/scripts/fk-rebuild-generate.ts
-- DO NOT APPLY without review. Each FK below is a separate decision.
-- Workflow: (1) ALTER ... NOT VALID, then (2) VALIDATE during low-traffic.

-- [MEDIUM] workflow_task_assignments.instance_id -> plan_item_instances.id
ALTER TABLE __TENANT_SCHEMA__.workflow_task_assignments
  ADD CONSTRAINT fk_workflow_task_assignments_instance_id
  FOREIGN KEY (instance_id)
  REFERENCES __TENANT_SCHEMA__.plan_item_instances(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.workflow_task_assignments VALIDATE CONSTRAINT fk_workflow_task_assignments_instance_id;

-- [MEDIUM] workflow_task_assignments.step_id -> provisioning_steps.id
ALTER TABLE __TENANT_SCHEMA__.workflow_task_assignments
  ADD CONSTRAINT fk_workflow_task_assignments_step_id
  FOREIGN KEY (step_id)
  REFERENCES __TENANT_SCHEMA__.provisioning_steps(id)
  -- ON DELETE/UPDATE: choose explicitly per FK. Default left blank = NO ACTION.
  NOT VALID;
-- Then, in a separate window:
-- ALTER TABLE __TENANT_SCHEMA__.workflow_task_assignments VALIDATE CONSTRAINT fk_workflow_task_assignments_step_id;

-- [LOW] workflow_task_assignments.assignee_id -> ???.???
-- SKIPPED: no target table inferred. Decide manually before adding.
