-- ============================================================================
-- 042_shahin_agent_tools_extended_catalog.sql
--
-- Extends migration 040 with the additional MCP tool descriptors sourced from
-- the Shahin-AI agent catalog (formerly /agents/mcp/tools, now under
-- docs/agents/mcp/tools). Adds 35 read/scan/flag tools across A01..A12 that
-- were declared by the agents but absent from mcp_tool_registry.
--
-- Idempotent — uses ON CONFLICT (tool_name).
-- ============================================================================

BEGIN;

INSERT INTO public.mcp_tool_registry (
  tool_name, display_name_en, display_name_ar, description_en, description_ar,
  agent_id, owner_module_code, domain_code, category, tags, visibility_scope,
  execution_type, handler_key, provider_key, execution_config,
  input_schema, output_schema,
  risk_level, data_classification, sensitivity_level,
  required_permissions, required_roles, allowed_actor_types, allowed_platform_modes,
  requires_tenant_context, requires_user_context,
  approval_mode, approval_config,
  min_autonomy, max_autonomy, default_autonomy,
  human_review_on_error, human_review_on_sensitive_data,
  autonomous_retries_allowed, max_calls_per_min,
  status, version, effective_from,
  is_enabled, is_system, sort_order, created_by
) VALUES
  ('analyze_regulatory_impact','Analyze Regulatory Impact','Analyze Regulatory Impact',
   'Analyze impact of regulatory changes on existing policies',
   'Analyze impact of regulatory changes on existing policies',
   'A07','risk','risk','automation','{shahin-ai,risk}','all',
   'internal_service','risk.analyze_regulatory_impact','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "regulatoryChangeId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{risk:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,100,'system'),
  ('check_audit_readiness','Check Audit Readiness','Check Audit Readiness',
   'Check overall audit readiness score',
   'Check overall audit readiness score',
   'A10','audit','audit','automation','{shahin-ai,audit}','all',
   'internal_service','audit.check_audit_readiness','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{audit:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,101,'system'),
  ('check_evidence_freshness','Check Evidence Freshness','Check Evidence Freshness',
   'Check evidence freshness and flag expired items',
   'Check evidence freshness and flag expired items',
   'A05','evidence','evidence','automation','{shahin-ai,evidence}','all',
   'internal_service','evidence.check_evidence_freshness','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{evidence:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,102,'system'),
  ('check_framework_adoption','Check Framework Adoption','Check Framework Adoption',
   'Check which regulatory frameworks are adopted',
   'Check which regulatory frameworks are adopted',
   'A03','compliance','mapping','automation','{shahin-ai,compliance}','all',
   'internal_service','compliance.check_framework_adoption','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{compliance:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,103,'system'),
  ('check_risk_appetite','Check Risk Appetite','Check Risk Appetite',
   'Check risk appetite thresholds for breaches',
   'Check risk appetite thresholds for breaches',
   'A07','risk','risk','automation','{shahin-ai,risk}','all',
   'internal_service','risk.check_risk_appetite','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{risk:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,104,'system'),
  ('check_role_distribution','Check Role Distribution','Check Role Distribution',
   'Analyze role distribution across the organization',
   'Analyze role distribution across the organization',
   'A02','identity','identity','automation','{shahin-ai,identity}','all',
   'internal_service','identity.check_role_distribution','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{identity:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,105,'system'),
  ('check_workspace_health','Check Workspace Health','Check Workspace Health',
   'Check overall workspace health status',
   'Check overall workspace health status',
   'A01','onboarding','onboarding','automation','{shahin-ai,onboarding}','all',
   'internal_service','onboarding.check_workspace_health','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{onboarding:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,106,'system'),
  ('code_search','Code Search','Code Search',
   'Search the codebase using trigram, regex, or semantic search engines. Covers all platform surfaces: DOS, DAuth, modules, config, DB migrations, contracts, frontend, and infrastructure.',
   'Search the codebase using trigram, regex, or semantic search engines. Covers all platform surfaces: DOS, DAuth, modules, config, DB migrations, contracts, frontend, and infrastructure.',
   'A01','onboarding','onboarding','automation','{shahin-ai,onboarding}','all',
   'internal_service','onboarding.code_search','claude','{}'::jsonb,
   '{"type": "object", "properties": {"query": {"type": "string", "description": "Search query (code pattern, function name, class, SQL table, config key, etc.)"}, "engine": {"type": "string", "enum": ["zoekt", "hound", "seagoat", "all"], "default": "zoekt", "description": "Search engine: zoekt (trigram+symbol), hound (regex), seagoat (AI/semantic), all (parallel)"}, "fileFilter": {"type": "string", "description": "File path filter (e.g. backend/src/platform/dauth/, backend/migrations/)"}, "maxResults": {"type": "number", "default": 20, "description": "Maximum results to return"}}, "required": ["query"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{onboarding:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,107,'system'),
  ('code_search_health','Code Search Health','Code Search Health',
   'Check health status of all code search engines (Zoekt, Hound, SeaGOAT, Code-Search).',
   'Check health status of all code search engines (Zoekt, Hound, SeaGOAT, Code-Search).',
   'A01','onboarding','onboarding','automation','{shahin-ai,onboarding}','all',
   'internal_service','onboarding.code_search_health','claude','{}'::jsonb,
   '{"type": "object", "properties": {}, "required": []}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{onboarding:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,108,'system'),
  ('compare_frameworks','Compare Frameworks','Compare Frameworks',
   'Compare two regulatory frameworks for overlap and gaps',
   'Compare two regulatory frameworks for overlap and gaps',
   'A03','compliance','mapping','automation','{shahin-ai,compliance}','all',
   'internal_service','compliance.compare_frameworks','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "frameworkA": {"type": "string"}, "frameworkB": {"type": "string"}}, "required": ["tenantId", "frameworkA", "frameworkB"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{compliance:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,109,'system'),
  ('create_awareness_campaign','Create Awareness Campaign','Create Awareness Campaign',
   'Create a security awareness campaign',
   'Create a security awareness campaign',
   'A12','training','training','automation','{shahin-ai,training}','all',
   'internal_service','training.create_awareness_campaign','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "title": {"type": "string"}, "targetAudience": {"type": "string"}}, "required": ["tenantId", "title"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{training:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,110,'system'),
  ('create_bcp_task','Create Bcp Task','Create Bcp Task',
   'Create a BCP remediation or exercise task',
   'Create a BCP remediation or exercise task',
   'A11','bcp','bcp','automation','{shahin-ai,bcp}','all',
   'internal_service','bcp.create_bcp_task','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "title": {"type": "string"}, "taskType": {"type": "string"}}, "required": ["tenantId", "title"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{bcp:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,111,'system'),
  ('create_finding','Create Finding','Create Finding',
   'Create an audit finding',
   'Create an audit finding',
   'A10','audit','audit','automation','{shahin-ai,audit}','all',
   'internal_service','audit.create_finding','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "title": {"type": "string"}, "severity": {"type": "string"}}, "required": ["tenantId", "title", "severity"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{audit:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,112,'system'),
  ('create_mapping_task','Create Mapping Task','Create Mapping Task',
   'Create a framework mapping task',
   'Create a framework mapping task',
   'A03','compliance','mapping','automation','{shahin-ai,compliance}','all',
   'internal_service','compliance.create_mapping_task','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "frameworkId": {"type": "string"}}, "required": ["tenantId", "frameworkId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{compliance:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,113,'system'),
  ('create_onboarding_task','Create Onboarding Task','Create Onboarding Task',
   'Create an onboarding task for the organization',
   'Create an onboarding task for the organization',
   'A01','onboarding','onboarding','automation','{shahin-ai,onboarding}','all',
   'internal_service','onboarding.create_onboarding_task','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "title": {"type": "string"}, "assignee": {"type": "string"}}, "required": ["tenantId", "title"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{onboarding:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,114,'system'),
  ('create_remediation_task','Create Remediation Task','Create Remediation Task',
   'Create a remediation task for a specific gap',
   'Create a remediation task for a specific gap',
   'A06','remediation','remediation','automation','{shahin-ai,remediation}','all',
   'internal_service','remediation.create_remediation_task','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "gapId": {"type": "string"}, "priority": {"type": "string"}}, "required": ["tenantId", "gapId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{remediation:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,115,'system'),
  ('detect_evidence_gaps','Detect Evidence Gaps','Detect Evidence Gaps',
   'Detect controls that lack required evidence',
   'Detect controls that lack required evidence',
   'A05','evidence','evidence','automation','{shahin-ai,evidence}','all',
   'internal_service','evidence.detect_evidence_gaps','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{evidence:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,116,'system'),
  ('detect_gaps','Detect Gaps','Detect Gaps',
   'Detect gaps in framework-to-control mappings',
   'Detect gaps in framework-to-control mappings',
   'A03','compliance','mapping','automation','{shahin-ai,compliance}','all',
   'internal_service','compliance.detect_gaps','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{compliance:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,117,'system'),
  ('escalate_risk','Escalate Risk','Escalate Risk',
   'Escalate a risk for management review',
   'Escalate a risk for management review',
   'A07','risk','risk','automation','{shahin-ai,risk}','all',
   'internal_service','risk.escalate_risk','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "riskId": {"type": "string"}, "reason": {"type": "string"}}, "required": ["tenantId", "riskId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{risk:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,118,'system'),
  ('flag_access_risk','Flag Access Risk','Flag Access Risk',
   'Flag access risk for over-privileged or anomalous accounts',
   'Flag access risk for over-privileged or anomalous accounts',
   'A02','identity','identity','automation','{shahin-ai,identity}','all',
   'internal_service','identity.flag_access_risk','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "userId": {"type": "string"}, "riskType": {"type": "string"}}, "required": ["tenantId", "userId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{identity:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,119,'system'),
  ('flag_bcp_risk','Flag Bcp Risk','Flag Bcp Risk',
   'Flag a business continuity risk',
   'Flag a business continuity risk',
   'A11','bcp','bcp','automation','{shahin-ai,bcp}','all',
   'internal_service','bcp.flag_bcp_risk','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "riskType": {"type": "string"}, "description": {"type": "string"}}, "required": ["tenantId", "riskType"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{bcp:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,120,'system'),
  ('flag_policy_issue','Flag Policy Issue','Flag Policy Issue',
   'Flag a policy issue (expired, orphaned, non-compliant)',
   'Flag a policy issue (expired, orphaned, non-compliant)',
   'A08','policy','policy','automation','{shahin-ai,policy}','all',
   'internal_service','policy.flag_policy_issue','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "policyId": {"type": "string"}, "issueType": {"type": "string"}}, "required": ["tenantId", "policyId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{policy:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,121,'system'),
  ('generate_compliance_summary','Generate Compliance Summary','Generate Compliance Summary',
   'Generate a compliance summary report',
   'Generate a compliance summary report',
   'A06','remediation','remediation','automation','{shahin-ai,remediation}','all',
   'internal_service','remediation.generate_compliance_summary','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{remediation:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,122,'system'),
  ('get_control_details','Get Control Details','Get Control Details',
   'Get detailed information about a specific control',
   'Get detailed information about a specific control',
   'A04','controls','controls','automation','{shahin-ai,controls}','all',
   'internal_service','controls.get_control_details','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "controlId": {"type": "string"}}, "required": ["tenantId", "controlId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{controls:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,123,'system'),
  ('get_training_gaps','Get Training Gaps','Get Training Gaps',
   'Identify training gaps by role and department',
   'Identify training gaps by role and department',
   'A12','training','training','automation','{shahin-ai,training}','all',
   'internal_service','training.get_training_gaps','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{training:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,124,'system'),
  ('list_audit_findings','List Audit Findings','List Audit Findings',
   'List audit findings with severity and status',
   'List audit findings with severity and status',
   'A10','audit','audit','automation','{shahin-ai,audit}','all',
   'internal_service','audit.list_audit_findings','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{audit:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,125,'system'),
  ('list_controls_needing_attention','List Controls Needing Attention','List Controls Needing Attention',
   'List controls that need review or documentation',
   'List controls that need review or documentation',
   'A04','controls','controls','automation','{shahin-ai,controls}','all',
   'internal_service','controls.list_controls_needing_attention','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{controls:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,126,'system'),
  ('list_frameworks_with_coverage','List Frameworks With Coverage','List Frameworks With Coverage',
   'List adopted frameworks with coverage percentages',
   'List adopted frameworks with coverage percentages',
   'A03','compliance','mapping','automation','{shahin-ai,compliance}','all',
   'internal_service','compliance.list_frameworks_with_coverage','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{compliance:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,127,'system'),
  ('list_policies_with_health','List Policies With Health','List Policies With Health',
   'List policies with their health status and review dates',
   'List policies with their health status and review dates',
   'A08','policy','policy','automation','{shahin-ai,policy}','all',
   'internal_service','policy.list_policies_with_health','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{policy:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,128,'system'),
  ('list_users_with_access_info','List Users With Access Info','List Users With Access Info',
   'List users with their access and role information',
   'List users with their access and role information',
   'A02','identity','identity','automation','{shahin-ai,identity}','all',
   'internal_service','identity.list_users_with_access_info','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{identity:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,129,'system'),
  ('list_vendors_with_risk','List Vendors With Risk','List Vendors With Risk',
   'List vendors with their risk ratings',
   'List vendors with their risk ratings',
   'A09','vendor','vendor','automation','{shahin-ai,vendor}','all',
   'internal_service','vendor.list_vendors_with_risk','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{vendor:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,130,'system'),
  ('recommend_training','Recommend Training','Recommend Training',
   'Recommend training programs based on compliance gaps',
   'Recommend training programs based on compliance gaps',
   'A12','training','training','automation','{shahin-ai,training}','all',
   'internal_service','training.recommend_training','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{training:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,131,'system'),
  ('request_evidence_collection','Request Evidence Collection','Request Evidence Collection',
   'Request evidence collection for specific controls',
   'Request evidence collection for specific controls',
   'A05','evidence','evidence','automation','{shahin-ai,evidence}','all',
   'internal_service','evidence.request_evidence_collection','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "controlIds": {"type": "array", "items": {"type": "string"}}}, "required": ["tenantId", "controlIds"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{evidence:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,132,'system'),
  ('scan_org_profile','Scan Org Profile','Scan Org Profile',
   'Scan organization profile for onboarding assessment',
   'Scan organization profile for onboarding assessment',
   'A01','onboarding','onboarding','automation','{shahin-ai,onboarding}','all',
   'internal_service','onboarding.scan_org_profile','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}}, "required": ["tenantId"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{onboarding:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,133,'system'),
  ('update_control_notes','Update Control Notes','Update Control Notes',
   'Update implementation notes for a control',
   'Update implementation notes for a control',
   'A04','controls','controls','automation','{shahin-ai,controls}','all',
   'internal_service','controls.update_control_notes','claude','{}'::jsonb,
   '{"type": "object", "properties": {"tenantId": {"type": "string"}, "controlId": {"type": "string"}, "notes": {"type": "string"}}, "required": ["tenantId", "controlId", "notes"]}'::jsonb,
   '{"type":"object"}'::jsonb,
   'low','internal','normal','{controls:read}','{tenant_admin}','{agent,user}','{shahin-ai}',
   TRUE,FALSE,'none','{}'::jsonb,'L1','L2','L2',TRUE,FALSE,2,30,
   'active',1,NOW(),TRUE,TRUE,134,'system')
ON CONFLICT (tool_name) DO UPDATE SET
  description_en = EXCLUDED.description_en,
  description_ar = EXCLUDED.description_ar,
  input_schema   = EXCLUDED.input_schema,
  agent_id       = EXCLUDED.agent_id,
  status         = 'active',
  is_enabled     = TRUE;

COMMIT;
