import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const WORKFLOW_ERROR_CODES = {
  DASHBOARD_NOT_FOUND: { code: 'WORKFLOW.DASHBOARD_NOT_FOUND', httpStatus: 404, messageEn: 'Dashboard not found', messageAr: 'Dashboard غير موجود' },
  DASHBOARD_ALREADY_EXISTS: { code: 'WORKFLOW.DASHBOARD_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Dashboard already exists', messageAr: 'Dashboard موجود بالفعل' },
  DASHBOARD_VALIDATION_FAILED: { code: 'WORKFLOW.DASHBOARD_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Dashboard validation failed', messageAr: 'فشل التحقق من Dashboard' },
  INITIATE_NOT_FOUND: { code: 'WORKFLOW.INITIATE_NOT_FOUND', httpStatus: 404, messageEn: 'Initiate not found', messageAr: 'Initiate غير موجود' },
  INITIATE_ALREADY_EXISTS: { code: 'WORKFLOW.INITIATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Initiate already exists', messageAr: 'Initiate موجود بالفعل' },
  INITIATE_VALIDATION_FAILED: { code: 'WORKFLOW.INITIATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Initiate validation failed', messageAr: 'فشل التحقق من Initiate' },
  REQUESTS_NOT_FOUND: { code: 'WORKFLOW.REQUESTS_NOT_FOUND', httpStatus: 404, messageEn: 'Requests not found', messageAr: 'Requests غير موجود' },
  REQUESTS_ALREADY_EXISTS: { code: 'WORKFLOW.REQUESTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Requests already exists', messageAr: 'Requests موجود بالفعل' },
  REQUESTS_VALIDATION_FAILED: { code: 'WORKFLOW.REQUESTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Requests validation failed', messageAr: 'فشل التحقق من Requests' },
  PENDING_NOT_FOUND: { code: 'WORKFLOW.PENDING_NOT_FOUND', httpStatus: 404, messageEn: 'Pending not found', messageAr: 'Pending غير موجود' },
  PENDING_ALREADY_EXISTS: { code: 'WORKFLOW.PENDING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Pending already exists', messageAr: 'Pending موجود بالفعل' },
  PENDING_VALIDATION_FAILED: { code: 'WORKFLOW.PENDING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Pending validation failed', messageAr: 'فشل التحقق من Pending' },
  STATUS_NOT_FOUND: { code: 'WORKFLOW.STATUS_NOT_FOUND', httpStatus: 404, messageEn: 'Status not found', messageAr: 'Status غير موجود' },
  STATUS_ALREADY_EXISTS: { code: 'WORKFLOW.STATUS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Status already exists', messageAr: 'Status موجود بالفعل' },
  STATUS_VALIDATION_FAILED: { code: 'WORKFLOW.STATUS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Status validation failed', messageAr: 'فشل التحقق من Status' },
  REASSIGN_NOT_FOUND: { code: 'WORKFLOW.REASSIGN_NOT_FOUND', httpStatus: 404, messageEn: 'Reassign not found', messageAr: 'Reassign غير موجود' },
  REASSIGN_ALREADY_EXISTS: { code: 'WORKFLOW.REASSIGN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reassign already exists', messageAr: 'Reassign موجود بالفعل' },
  REASSIGN_VALIDATION_FAILED: { code: 'WORKFLOW.REASSIGN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reassign validation failed', messageAr: 'فشل التحقق من Reassign' },
  CANCEL_NOT_FOUND: { code: 'WORKFLOW.CANCEL_NOT_FOUND', httpStatus: 404, messageEn: 'Cancel not found', messageAr: 'Cancel غير موجود' },
  CANCEL_ALREADY_EXISTS: { code: 'WORKFLOW.CANCEL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Cancel already exists', messageAr: 'Cancel موجود بالفعل' },
  CANCEL_VALIDATION_FAILED: { code: 'WORKFLOW.CANCEL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Cancel validation failed', messageAr: 'فشل التحقق من Cancel' },
  TRIAGE_NOT_FOUND: { code: 'WORKFLOW.TRIAGE_NOT_FOUND', httpStatus: 404, messageEn: 'Triage not found', messageAr: 'Triage غير موجود' },
  TRIAGE_ALREADY_EXISTS: { code: 'WORKFLOW.TRIAGE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Triage already exists', messageAr: 'Triage موجود بالفعل' },
  TRIAGE_VALIDATION_FAILED: { code: 'WORKFLOW.TRIAGE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Triage validation failed', messageAr: 'فشل التحقق من Triage' },
  CO_DRAFT_NOT_FOUND: { code: 'WORKFLOW.CO_DRAFT_NOT_FOUND', httpStatus: 404, messageEn: 'Co Draft not found', messageAr: 'Co Draft غير موجود' },
  CO_DRAFT_ALREADY_EXISTS: { code: 'WORKFLOW.CO_DRAFT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Co Draft already exists', messageAr: 'Co Draft موجود بالفعل' },
  CO_DRAFT_VALIDATION_FAILED: { code: 'WORKFLOW.CO_DRAFT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Co Draft validation failed', messageAr: 'فشل التحقق من Co Draft' },
  EVIDENCE_RELAY_NOT_FOUND: { code: 'WORKFLOW.EVIDENCE_RELAY_NOT_FOUND', httpStatus: 404, messageEn: 'Evidence Relay not found', messageAr: 'Evidence Relay غير موجود' },
  EVIDENCE_RELAY_ALREADY_EXISTS: { code: 'WORKFLOW.EVIDENCE_RELAY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Evidence Relay already exists', messageAr: 'Evidence Relay موجود بالفعل' },
  EVIDENCE_RELAY_VALIDATION_FAILED: { code: 'WORKFLOW.EVIDENCE_RELAY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Evidence Relay validation failed', messageAr: 'فشل التحقق من Evidence Relay' },
  RISK_PAIR_NOT_FOUND: { code: 'WORKFLOW.RISK_PAIR_NOT_FOUND', httpStatus: 404, messageEn: 'Risk Pair not found', messageAr: 'Risk Pair غير موجود' },
  RISK_PAIR_ALREADY_EXISTS: { code: 'WORKFLOW.RISK_PAIR_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Risk Pair already exists', messageAr: 'Risk Pair موجود بالفعل' },
  RISK_PAIR_VALIDATION_FAILED: { code: 'WORKFLOW.RISK_PAIR_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Risk Pair validation failed', messageAr: 'فشل التحقق من Risk Pair' },
  APPROVAL_PRESCREEN_NOT_FOUND: { code: 'WORKFLOW.APPROVAL_PRESCREEN_NOT_FOUND', httpStatus: 404, messageEn: 'Approval Prescreen not found', messageAr: 'Approval Prescreen غير موجود' },
  APPROVAL_PRESCREEN_ALREADY_EXISTS: { code: 'WORKFLOW.APPROVAL_PRESCREEN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Approval Prescreen already exists', messageAr: 'Approval Prescreen موجود بالفعل' },
  APPROVAL_PRESCREEN_VALIDATION_FAILED: { code: 'WORKFLOW.APPROVAL_PRESCREEN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Approval Prescreen validation failed', messageAr: 'فشل التحقق من Approval Prescreen' },
  APPROVAL_PRESCREENS_NOT_FOUND: { code: 'WORKFLOW.APPROVAL_PRESCREENS_NOT_FOUND', httpStatus: 404, messageEn: 'Approval Prescreens not found', messageAr: 'Approval Prescreens غير موجود' },
  APPROVAL_PRESCREENS_ALREADY_EXISTS: { code: 'WORKFLOW.APPROVAL_PRESCREENS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Approval Prescreens already exists', messageAr: 'Approval Prescreens موجود بالفعل' },
  APPROVAL_PRESCREENS_VALIDATION_FAILED: { code: 'WORKFLOW.APPROVAL_PRESCREENS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Approval Prescreens validation failed', messageAr: 'فشل التحقق من Approval Prescreens' },
  WAR_ROOMS_NOT_FOUND: { code: 'WORKFLOW.WAR_ROOMS_NOT_FOUND', httpStatus: 404, messageEn: 'War Rooms not found', messageAr: 'War Rooms غير موجود' },
  WAR_ROOMS_ALREADY_EXISTS: { code: 'WORKFLOW.WAR_ROOMS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'War Rooms already exists', messageAr: 'War Rooms موجود بالفعل' },
  WAR_ROOMS_VALIDATION_FAILED: { code: 'WORKFLOW.WAR_ROOMS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'War Rooms validation failed', messageAr: 'فشل التحقق من War Rooms' },
  NUDGE_FEEDBACK_NOT_FOUND: { code: 'WORKFLOW.NUDGE_FEEDBACK_NOT_FOUND', httpStatus: 404, messageEn: 'Nudge Feedback not found', messageAr: 'Nudge Feedback غير موجود' },
  NUDGE_FEEDBACK_ALREADY_EXISTS: { code: 'WORKFLOW.NUDGE_FEEDBACK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Nudge Feedback already exists', messageAr: 'Nudge Feedback موجود بالفعل' },
  NUDGE_FEEDBACK_VALIDATION_FAILED: { code: 'WORKFLOW.NUDGE_FEEDBACK_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Nudge Feedback validation failed', messageAr: 'فشل التحقق من Nudge Feedback' },

  UNAUTHORIZED: { code: 'WORKFLOW.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for workflow operation', messageAr: 'صلاحيات غير كافية لعملية workflow' },
  INVALID_STATE_TRANSITION: { code: 'WORKFLOW.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'WORKFLOW.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'WORKFLOW.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'WORKFLOW.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'WORKFLOW.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type WorkflowErrorCode = keyof typeof WORKFLOW_ERROR_CODES;
