import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const RISK_WIDGETS: WidgetManifest[] = [
  // ── Core Risk Widgets ──
  {
    id: 'risk.heatmap',
    key: 'risk_heatmap',
    title: 'Risk Heatmap',
    titleAr: 'خريطة المخاطر الحرارية',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-heatmap.widget').then(m => m.RiskHeatmapWidget),
    icon: '🔥',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    supportsDrilldown: true,
    schemaVersion: 1,
  },
  {
    id: 'risk.summary',
    key: 'risk_summary',
    title: 'Risk Summary',
    titleAr: 'ملخص المخاطر',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-summary.widget').then(m => m.RiskSummaryWidget),
    icon: '⚠️',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'risk.distribution',
    key: 'risk_distribution',
    title: 'Risk Distribution',
    titleAr: 'توزيع المخاطر',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-distribution.widget').then(m => m.RiskDistributionWidget),
    icon: '🍩',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.predictor',
    key: 'risk_predictor',
    title: 'Risk Predictor',
    titleAr: 'توقعات المخاطر',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-predictor.widget').then(m => m.RiskPredictorWidget),
    icon: '🔮',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  // ── Assessment & Risk ──
  {
    id: 'risk.gravity',
    key: 'risk_gravity',
    title: 'Risk Gravity',
    titleAr: 'جاذبية المخاطر',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/risk/risk-gravity.widget').then(m => m.RiskGravityWidget),
    icon: '🌀',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.untested_assumptions',
    key: 'untested_assumptions',
    title: 'Untested Assumptions',
    titleAr: 'افتراضات غير مُختبرة',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/untested-assumptions.widget').then(m => m.UntestedAssumptionsWidget),
    icon: '❓',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.false_comfort',
    key: 'false_comfort',
    title: 'False Comfort',
    titleAr: 'طمأنينة كاذبة',
    category: 'risk',
    engine: 'angular',
    component: () => import('../../../components/culture-insights/false-comfort.widget').then(m => m.FalseComfortWidget),
    icon: '🟢',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  // ── ECharts Risk ──
  {
    id: 'risk.heatmap_echart',
    key: 'risk_heatmap_echart',
    title: 'Advanced Risk Heatmap',
    titleAr: 'خريطة المخاطر المتقدمة',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../echart-components/heatmap/risk-heatmap-echart.component').then(m => m.RiskHeatmapEchartComponent),
    icon: '🔥',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    supportsDrilldown: true,
    schemaVersion: 1,
  },
  {
    id: 'risk.vendor_bubble',
    key: 'vendor_bubble',
    title: 'Vendor Bubble',
    titleAr: 'فقاعات الموردين',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/scatter/vendor-bubble.component').then(m => m.VendorBubbleComponent),
    icon: '🏢',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.top_risks',
    key: 'top_risks',
    title: 'Top Risks',
    titleAr: 'أعلى المخاطر',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/top-risks-echart.component').then(m => m.TopRisksEchartComponent),
    icon: '⚠️',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.constellation',
    key: 'risk_constellation',
    title: 'Risk Constellation',
    titleAr: 'كوكبة المخاطر',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/scatter/risk-constellation.component').then(m => m.RiskConstellationComponent),
    icon: '✨',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.vendor_bubble_enhanced',
    key: 'vendor_risk_bubble',
    title: 'Vendor Risk Bubble (Enhanced)',
    titleAr: 'فقاعات مخاطر الموردين المتقدمة',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/scatter/vendor-risk-bubble-enhanced.component').then(m => m.VendorRiskBubbleEnhancedComponent),
    icon: '🏢',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'risk.bridge_waterfall',
    key: 'risk_waterfall',
    title: 'Risk Bridge Waterfall',
    titleAr: 'جسر المخاطر الشلالي',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/bar/risk-bridge-waterfall.component').then(m => m.RiskBridgeWaterfallComponent),
    icon: '🌊',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'risk.distribution_echart',
    key: 'risk_distribution_echart',
    title: 'Risk Distribution (ECharts)',
    titleAr: 'توزيع المخاطر المتقدم',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/donut/risk-distribution.component').then(m => m.RiskDistributionComponent),
    icon: '🍩',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'risk.blast_radius',
    key: 'blast_radius',
    title: 'Blast Radius',
    titleAr: 'نطاق الانفجار',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/blast-radius.component').then(m => m.BlastRadiusComponent),
    icon: '💥',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.surface_3d',
    key: 'risk_surface_3d',
    title: 'Risk Surface 3D',
    titleAr: 'سطح المخاطر ثلاثي الأبعاد',
    category: 'risk',
    engine: 'plotly',
    component: () => import('../../../chart-infra/echart-components/three-d/risk-surface-3d.component').then(m => m.RiskSurface3dComponent),
    icon: '🏔️',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  // ── Statistical Risk ──
  {
    id: 'risk.monte_carlo',
    key: 'monte_carlo',
    title: 'Monte Carlo Distribution',
    titleAr: 'توزيع مونتي كارلو',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/statistical/monte-carlo-distribution.component').then(m => m.MonteCarloDistributionComponent),
    icon: '🎲',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  {
    id: 'risk.tornado_sensitivity',
    key: 'tornado_sensitivity',
    title: 'Tornado Sensitivity',
    titleAr: 'تحليل حساسية إعصاري',
    category: 'risk',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/statistical/tornado-sensitivity.component').then(m => m.TornadoSensitivityComponent),
    icon: '🌪️',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'risk_manager'],
    schemaVersion: 1,
  },
  // ── D3 Risk ──
  {
    id: 'risk.d3_heatmap',
    key: 'd3_risk_heatmap',
    title: 'Risk Heatmap (D3)',
    titleAr: 'حرارية المخاطر D3',
    category: 'risk',
    engine: 'd3',
    component: () => import('../../../chart-infra/d3-charts/risk-heatmap-chart.component').then(m => m.RiskHeatmapChartComponent),
    icon: '🔥',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
];
