// Auto-generated from legacy event extraction
// Source: 52 events

export const COMPLIANCE_PUBLISHED_EVENTS = [
  "compliance.applicability_changed",
  "compliance.assessment_approved",
  "compliance.assessment_completed",
  "compliance.assessment_rejected",
  "compliance.assessment_started",
  "compliance.assessment.completed",
  "compliance.attestation_campaign_created",
  "compliance.attestation_campaign_started",
  "compliance.attestation_recorded",
  "compliance.attestation_submitted",
  "compliance.control_bulk_assigned",
  "compliance.control_failed",
  "compliance.control_mapped",
  "compliance.control_updated",
  "compliance.evidence_linked",
  "compliance.exception_approved",
  "compliance.exception_created",
  "compliance.exception_rejected",
  "compliance.finding_bulk_updated",
  "compliance.finding_closed",
  "compliance.finding_raised",
  "compliance.framework_gap_identified",
  "compliance.framework_mapping_updated",
  "compliance.gap_closed",
  "compliance.gap_detected",
  "compliance.gap_remediation_started",
  "compliance.gap.detected",
  "compliance.obligation_assigned",
  "compliance.obligation_created",
  "compliance.obligation_updated",
  "compliance.owner_assigned",
  "compliance.posture_changed",
  "compliance.posture_updated",
  "compliance.remediation_linked",
  "compliance.review_overdue",
  "compliance.score_recalculated",
  "compliance.status_changed",
  "compliance.vendor_finding",
  "controls.activated",
  "controls.automation_degraded",
  "controls.automation_failed",
  "controls.certification_expired",
  "controls.created",
  "controls.deficiency_detected",
  "controls.effectiveness_failed",
  "controls.effectiveness_tested",
  "controls.effectiveness_updated",
  "controls.mapping_changed",
  "controls.ownership_changed",
  "controls.retired",
  "controls.status_changed",
  "controls.test_overdue",
] as const;

export const COMPLIANCE_CONSUMED_EVENTS = [
  "compliance.framework_gap_identified",
  "compliance.gap_detected",
  "controls.effectiveness_failed",
] as const;
