// Auto-generated from legacy event extraction
// Source: 49 events

export const GOVERNANCE_PUBLISHED_EVENTS = [
  "governance.action_created",
  "governance.action_escalated",
  "governance.action_overdue",
  "governance.board_attention_item",
  "governance.board_pack_generated",
  "governance.body_updated",
  "governance.charter_approved",
  "governance.charter_expired",
  "governance.committee_decision",
  "governance.committee_meeting_scheduled",
  "governance.decision_made",
  "governance.decision_recorded",
  "governance.delegation_created",
  "governance.delegation_expired",
  "governance.delegation_expiring",
  "governance.digest_published",
  "governance.enforcement_violation",
  "governance.exec_summary_generated",
  "governance.health_score_changed",
  "governance.health_score_updated",
  "governance.initiative_started",
  "governance.mandate_activated",
  "governance.mandate_expired",
  "governance.milestone_reached",
  "governance.obligation_created",
  "governance.policy_approved",
  "governance.policy_review_overdue",
  "governance.review_completed",
  "governance.status_changed",
  "governance.structure_changed",
  "policy.acknowledgement_received",
  "policy.acknowledgement_required",
  "policy.approved",
  "policy.created",
  "policy.document.approved",
  "policy.drift_detected",
  "policy.exception_approved",
  "policy.exception_rejected",
  "policy.expired",
  "policy.published",
  "policy.record.updated",
  "policy.rejected",
  "policy.review_completed",
  "policy.review_due",
  "policy.review_started",
  "policy.revoked",
  "policy.status_changed",
  "policy.version_created",
  "policy.violated",
] as const;

export const GOVERNANCE_CONSUMED_EVENTS = [
  "governance.charter_approved",
  "policy.approved",
] as const;
