import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const EXECUTIVE_WIDGETS: WidgetManifest[] = [
  {
    id: 'executive.program_health',
    key: 'executive_summary',
    title: 'Program Health Score',
    titleAr: 'صحة البرنامج',
    category: 'executive',
    engine: 'angular',
    component: () => import('../../../components/governance/program-health.widget').then(m => m.ProgramHealthWidget),
    icon: '💚',
    defaultSize: { cols: 3, rows: 2 },
    roles: ['owner', 'admin', 'compliance_officer', 'risk_manager', 'auditor', 'viewer'],
    schemaVersion: 1,
  },
  {
    id: 'executive.kpi_card',
    key: 'kpi_card',
    title: 'KPI Card',
    titleAr: 'بطاقة مؤشر الأداء',
    category: 'executive',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/kpi-card-echart.component').then(m => m.KpiCardEchartComponent),
    icon: '📊',
    defaultSize: { cols: 3, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'executive.kpi_tiles',
    key: 'kpi_tiles',
    title: 'KPI Tiles (Animated)',
    titleAr: 'بلاطات KPI متحركة',
    category: 'executive',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/kpi-tiles.component').then(m => m.KpiTilesComponent),
    icon: '📊',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'executive.chart_carousel',
    key: 'chart_carousel',
    title: 'Chart Carousel',
    titleAr: 'عرض دوّار للرسوم',
    category: 'executive',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/specialty/chart-carousel.component').then(m => m.ChartCarouselComponent),
    icon: '🎠',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'executive.engine_exec_summary',
    key: 'executive-summary',
    title: 'Engine Executive Summary',
    titleAr: 'ملخص تنفيذي للمحرك',
    category: 'executive',
    engine: 'angular',
    component: () => import('../../../components/executive/executive-summary.widget').then(m => m.ExecutiveSummaryWidgetComponent),
    icon: '📋',
    defaultSize: { cols: 6, rows: 2 },
    schemaVersion: 1,
  },
  {
    id: 'executive.engine_trend',
    key: 'engine-trend',
    title: 'Engine Trend',
    titleAr: 'اتجاه المحرك',
    category: 'executive',
    engine: 'angular',
    component: () => import('../../../components/lifecycle-ops/engine-trend.widget').then(m => m.EngineTrendWidgetComponent),
    icon: '📈',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
];
