-- dos:extracted-from: ops/migrations/tenant/027_tenant_schema_tables.sql
-- dos:supersedes-checksum: b618781c42608331e3344799991235a22afbb73ab72c9789ef6478fd164416c8
-- dos:owning-module: dora
-- dos:tables: dora_actions, dora_activities, dora_alerts, dora_approvals, dora_assessments, dora_categories, dora_configs, dora_entities, dora_evidence, dora_feedback, dora_findings, dora_history, dora_issues, dora_kpis, dora_links, dora_logs, dora_members, dora_metrics, dora_reports, dora_reviews, dora_risks, dora_schedules, dora_settings, dora_snapshots, dora_tasks, dora_templates, dora_versions
-- dos:statement-count: 54
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_entities" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_entities_tenant ON "__TENANT_SCHEMA__"."dora_entities" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_activities" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_activities_tenant ON "__TENANT_SCHEMA__"."dora_activities" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_assessments" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_assessments_tenant ON "__TENANT_SCHEMA__"."dora_assessments" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_findings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_findings_tenant ON "__TENANT_SCHEMA__"."dora_findings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_logs" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_logs_tenant ON "__TENANT_SCHEMA__"."dora_logs" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_templates" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_templates_tenant ON "__TENANT_SCHEMA__"."dora_templates" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_configs" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_configs_tenant ON "__TENANT_SCHEMA__"."dora_configs" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_snapshots" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_snapshots_tenant ON "__TENANT_SCHEMA__"."dora_snapshots" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_schedules" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_schedules_tenant ON "__TENANT_SCHEMA__"."dora_schedules" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_reports" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  title TEXT NOT NULL,
  query_definition JSONB,
  last_run_at TIMESTAMPTZ,
  schedule TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_reports_tenant ON "__TENANT_SCHEMA__"."dora_reports" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_alerts" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_alerts_tenant ON "__TENANT_SCHEMA__"."dora_alerts" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_metrics" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_metrics_tenant ON "__TENANT_SCHEMA__"."dora_metrics" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_tasks" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_tasks_tenant ON "__TENANT_SCHEMA__"."dora_tasks" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_issues" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_issues_tenant ON "__TENANT_SCHEMA__"."dora_issues" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_risks" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_risks_tenant ON "__TENANT_SCHEMA__"."dora_risks" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_actions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_actions_tenant ON "__TENANT_SCHEMA__"."dora_actions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_approvals" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_approvals_tenant ON "__TENANT_SCHEMA__"."dora_approvals" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_history" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_history_tenant ON "__TENANT_SCHEMA__"."dora_history" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_settings_tenant ON "__TENANT_SCHEMA__"."dora_settings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_members" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_members_tenant ON "__TENANT_SCHEMA__"."dora_members" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_versions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_versions_tenant ON "__TENANT_SCHEMA__"."dora_versions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_evidence" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_evidence_tenant ON "__TENANT_SCHEMA__"."dora_evidence" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_links" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_links_tenant ON "__TENANT_SCHEMA__"."dora_links" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_reviews" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_reviews_tenant ON "__TENANT_SCHEMA__"."dora_reviews" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_categories" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_categories_tenant ON "__TENANT_SCHEMA__"."dora_categories" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_feedback" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_feedback_tenant ON "__TENANT_SCHEMA__"."dora_feedback" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."dora_kpis" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_dora_kpis_tenant ON "__TENANT_SCHEMA__"."dora_kpis" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;
