/**
 * proactive-leadership — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition } from './ports/lifecycle.port';

const PROACTIVE_LEADERSHIP_INSIGHTS_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const PROACTIVE_LEADERSHIP_INSIGHTS_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'proactive-leadership',
  'proactive_leadership_insights',
  PROACTIVE_LEADERSHIP_INSIGHTS_STATES,
  PROACTIVE_LEADERSHIP_INSIGHTS_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);
