"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tenantSchema = exports.emptyResult = exports.getFirstRow = exports.query = exports.safeQuery = void 0;
var db_1 = require("@dos/db");
Object.defineProperty(exports, "safeQuery", { enumerable: true, get: function () { return db_1.safeQuery; } });
Object.defineProperty(exports, "query", { enumerable: true, get: function () { return db_1.query; } });
Object.defineProperty(exports, "getFirstRow", { enumerable: true, get: function () { return db_1.getFirstRow; } });
Object.defineProperty(exports, "emptyResult", { enumerable: true, get: function () { return db_1.emptyResult; } });
var db_2 = require("@dos/db");
Object.defineProperty(exports, "tenantSchema", { enumerable: true, get: function () { return db_2.tenantSchema; } });
