// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const AI_ROUTES: RouteDefinition[] = [
  {
    id: "routes_inference_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/ai/inference.routes",
    exportName: "default",
    mountPath: "/api/inference",
    guards: { module: "ai" },
    order: 7,
    notes: "cast-to-any",
  },
  {
    id: "routes_ai_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/core/ai.routes",
    exportName: "default",
    mountPath: "/api/ai",
    guards: { module: "ai" },
    order: 104,
  },
  {
    id: "routes_copilot_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/copilot/copilot.routes",
    exportName: "default",
    mountPath: "/api/copilot",
    guards: { module: "ai" },
    order: 105,
  },
  {
    id: "routes_ai_enhanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/enhanced/ai-enhanced.routes",
    exportName: "default",
    mountPath: "/api/ai-enhanced",
    guards: { module: "ai" },
    order: 106,
  },
  {
    id: "routes_ai_trigger_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/triggers/ai-trigger.routes",
    exportName: "default",
    mountPath: "/api/ai-triggers",
    guards: { module: "ai" },
    order: 107,
  },
  {
    id: "routes_ai_squad_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/squad/ai-squad.routes",
    exportName: "default",
    mountPath: "/api/ai-squad",
    guards: { module: "ai" },
    order: 108,
  },
  {
    id: "routes_ai_asset_inventory_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-asset-inventory.routes",
    exportName: "default",
    mountPath: "/api/ai-assets",
    guards: { module: "ai" },
    order: 109,
  },
  {
    id: "routes_ai_binding_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-binding-governance.routes",
    exportName: "default",
    mountPath: "/api/ai-bindings",
    guards: { module: "ai" },
    order: 113,
  },
  {
    id: "routes_ai_governance_config_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-governance-config.routes",
    exportName: "default",
    mountPath: "/api/ai-governance-config",
    guards: { module: "ai" },
    order: 114,
  },
  {
    id: "routes_ai_governance_ops_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-governance-ops.routes",
    exportName: "default",
    mountPath: "/api/ai-governance-ops",
    guards: { module: "ai" },
    order: 115,
  },
  {
    id: "routes_ai_governance_wave1_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-governance-wave1.routes",
    exportName: "default",
    mountPath: "/api/ai-governance/wave1",
    guards: { module: "ai" },
    order: 116,
  },
  {
    id: "routes_ai_governance_wave2_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-governance-wave2.routes",
    exportName: "default",
    mountPath: "/api/ai-governance/wave2",
    guards: { module: "ai" },
    order: 117,
  },
  {
    id: "routes_ai_system_registry_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-system-registry.routes",
    exportName: "default",
    mountPath: "/api/ai-systems",
    guards: { module: "ai" },
    order: 118,
  },
  {
    id: "routes_ai_supply_chain_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-supply-chain.routes",
    exportName: "default",
    mountPath: "/api/ai-supply-chain",
    guards: { module: "ai" },
    order: 120,
  },
  {
    id: "routes_ai_agent_governance_phase4_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-agent-governance-phase4.routes",
    exportName: "default",
    mountPath: "/api/ai-agent-governance",
    guards: { module: "ai" },
    order: 121,
  },
  {
    id: "routes_ai_post_market_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-post-market.routes",
    exportName: "default",
    mountPath: "/api/ai-post-market",
    guards: { module: "ai" },
    order: 122,
  },
  {
    id: "routes_ai_model_experiments_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-model-experiments.routes",
    exportName: "default",
    mountPath: "/api/ai-experiments",
    guards: { module: "ai" },
    order: 126,
  },
  {
    id: "routes_contextual_ai_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/ai/contextual-ai.routes",
    exportName: "default",
    mountPath: "/api/contextual-ai",
    guards: { module: "ai" },
    order: 127,
  },
  {
    id: "modules_agrc_engine_agrc_engine_controller",
    productKey: "shahin-ai",
    ownerKind: "module",
    sourceKind: "controller",
    sourceFile: "modules/agrc-engine/agrc-engine.controller",
    exportName: "default",
    mountPath: "/api",
    rootMount: true,
    guards: { module: "ai" },
    order: 287,
    intentionalDuplicateGroup: "path:/api",
  },
  {
    id: "autodiscovered:routes_ai_agent_health_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-agent-health.routes",
    exportName: "default",
    mountPath: "/api/ai-agent-health",
    guards: { module: "ai" },
    order: 328,
    notes: "auto-discovered; no manifest entry",
  },
  {
    id: "autodiscovered:routes_ai_policy_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/core/ai-policy.routes",
    exportName: "default",
    mountPath: "/api/ai-policy",
    guards: { module: "ai" },
    order: 329,
    notes: "auto-discovered; no manifest entry",
  },
  {
    id: "routes_ai_os_cockpit_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-os/ai-os-cockpit.routes",
    exportName: "default",
    mountPath: "/api",
    guards: { module: "ai" },
    order: 348,
    rootMount: true,
    intentionalDuplicateGroup: "path:/api",
    notes: "AI OS cockpit + dry-run + replay endpoints",
  },
  {
    id: "routes_ai_os_services_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-os/ai-os-services.routes",
    exportName: "default",
    mountPath: "/api",
    guards: { module: "ai" },
    order: 351,
    rootMount: true,
    intentionalDuplicateGroup: "path:/api",
    notes: "AI OS services: decisions, recommendations, policy-rules, event-triggers, route-rules, runtime, signals",
  },
  {
    id: "routes_ai_model_risk_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-model-risk.routes",
    exportName: "default",
    mountPath: "/api/ai-model-risk",
    guards: { module: "ai" },
    order: 352,
    notes: "AI Model Risk Management: risk scoring, lifecycle, assessments",
  },
  {
    id: "routes_ai_agent_performance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-agent-performance.routes",
    exportName: "default",
    mountPath: "/api/ai-agent-performance",
    guards: { module: "ai" },
    order: 354,
    notes: "AI Agent Performance & Bias Detection",
  },
  {
    id: "routes_ai_explainability_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-explainability.routes",
    exportName: "default",
    mountPath: "/api/ai-explainability",
    guards: { module: "ai" },
    order: 355,
    notes: "AI Explainability & Transparency Tracking",
  },
  {
    id: "routes_ai_os_kernel_routes",
    productKey: "shahin-ai",
    ownerKind: "platform",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-os/kernel.routes",
    exportName: "default",
    mountPath: "/api/ai-engine",
    guards: { module: "ai" },
    order: 356,
    rootMount: false,
    notes: "AI OS Kernel: HTOP Administrative Endpoints",
  },
];
