// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const AUDIT_ROUTES: RouteDefinition[] = [
  {
    id: "routes_audit_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit.routes",
    exportName: "default",
    mountPath: "/api/audit",
    guards: { module: "audit" },
    order: 59,
  },
  {
    id: "routes_audit_packages_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-packages.routes",
    exportName: "default",
    mountPath: "/api/audit-packages",
    guards: { module: "audit" },
    order: 60,
  },
  {
    id: "routes_audit_package_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-package.routes",
    exportName: "default",
    mountPath: "/api/audit-package",
    guards: { module: "audit" },
    order: 61,
  },
  {
    id: "routes_audit_universe_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-universe.routes",
    exportName: "default",
    mountPath: "/api/audit/universe",
    guards: { module: "audit" },
    order: 62,
  },
  {
    id: "routes_audit_risk_scoring_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-risk-scoring.routes",
    exportName: "default",
    mountPath: "/api/audit/risk-scoring",
    guards: { module: "audit" },
    order: 63,
  },
  {
    id: "routes_audit_schedules_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-schedules.routes",
    exportName: "default",
    mountPath: "/api/audit/schedules",
    guards: { module: "audit" },
    order: 64,
  },
  {
    id: "routes_audit_working_papers_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-working-papers.routes",
    exportName: "default",
    mountPath: "/api/audit/working-papers",
    guards: { module: "audit" },
    order: 65,
  },
  {
    id: "routes_audit_team_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-team.routes",
    exportName: "default",
    mountPath: "/api/audit/team",
    guards: { module: "audit" },
    order: 66,
  },
  {
    id: "routes_audit_repeat_findings_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-repeat-findings.routes",
    exportName: "default",
    mountPath: "/api/audit/repeat-findings",
    guards: { module: "audit" },
    order: 67,
  },
  {
    id: "routes_audit_evidence_versions_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-evidence-versions.routes",
    exportName: "default",
    mountPath: "/api/audit/evidence-versions",
    guards: { module: "audit" },
    order: 68,
  },
  {
    id: "routes_audit_qa_reviews_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-qa-reviews.routes",
    exportName: "default",
    mountPath: "/api/audit/qa-reviews",
    guards: { module: "audit" },
    order: 69,
  },
  {
    id: "routes_audit_finding_trends_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-finding-trends.routes",
    exportName: "default",
    mountPath: "/api/audit/finding-trends",
    guards: { module: "audit" },
    order: 70,
  },
  {
    id: "routes_audit_ratings_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-ratings.routes",
    exportName: "default",
    mountPath: "/api/audit/ratings",
    guards: { module: "audit" },
    order: 71,
  },
  {
    id: "routes_audit_capa_effectiveness_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-capa-effectiveness.routes",
    exportName: "default",
    mountPath: "/api/audit/capa-effectiveness",
    guards: { module: "audit" },
    order: 72,
  },
  {
    id: "routes_audit_committee_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-committee.routes",
    exportName: "default",
    mountPath: "/api/audit/committee",
    guards: { module: "audit" },
    order: 73,
  },
  {
    id: "routes_audit_external_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-external.routes",
    exportName: "default",
    mountPath: "/api/audit/external",
    guards: { module: "audit" },
    order: 74,
  },
  {
    id: "routes_audit_regulatory_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-regulatory.routes",
    exportName: "default",
    mountPath: "/api/audit/regulatory",
    guards: { module: "audit" },
    order: 75,
  },
  {
    id: "routes_audit_test_plans_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-test-plans.routes",
    exportName: "default",
    mountPath: "/api/audit/test-plans",
    guards: { module: "audit" },
    order: 76,
  },
  {
    id: "routes_audit_finding_slas_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-finding-slas.routes",
    exportName: "default",
    mountPath: "/api/audit/finding-slas",
    guards: { module: "audit" },
    order: 77,
  },
  {
    id: "routes_audit_time_tracking_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-time-tracking.routes",
    exportName: "default",
    mountPath: "/api/audit/time-tracking",
    guards: { module: "audit" },
    order: 78,
  },
  {
    id: "routes_audit_reminders_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-reminders.routes",
    exportName: "default",
    mountPath: "/api/audit/reminders",
    guards: { module: "audit" },
    order: 79,
  },
  {
    id: "routes_audit_templates_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-templates.routes",
    exportName: "default",
    mountPath: "/api/audit/templates",
    guards: { module: "audit" },
    order: 80,
  },
  {
    id: "routes_audit_cross_module_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-cross-module.routes",
    exportName: "default",
    mountPath: "/api/audit/cross-module",
    guards: { module: "audit" },
    order: 81,
  },
  {
    id: "routes_akb_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/misc/akb.routes",
    exportName: "default",
    mountPath: "/api/akb",
    guards: { module: "audit" },
    order: 82,
  },
  {
    id: "routes_common_objects_routes:findingRoutes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/integration/common-objects.routes",
    exportName: "findingRoutes",
    mountPath: "/api/findings",
    guards: { module: "audit" },
    order: 83,
  },
  {
    id: "routes_findings_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/remediation/routes/findings.routes",
    exportName: "default",
    mountPath: "/api/findings-standalone",
    guards: { module: "audit" },
    order: 84,
  },
  {
    id: "routes_audit_advanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/audit/audit-advanced.routes",
    exportName: "default",
    mountPath: "/api/audit/advanced",
    guards: { module: "audit" },
    order: 296,
  },
  {
    id: "routes_workpaper_generator_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/audit/routes/misc/workpaper-generator.routes",
    exportName: "default",
    mountPath: "/api/workpapers",
    guards: { module: "audit" },
    order: 85,
  },
];
