// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const COMPLIANCE_ROUTES: RouteDefinition[] = [
  {
    id: "routes_compliance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance.routes",
    exportName: "default",
    mountPath: "/api/compliance",
    guards: { module: "compliance" },
    order: 45,
  },
  {
    id: "routes_compliance_extended_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance-extended.routes",
    exportName: "default",
    mountPath: "/api/compliance-ext",
    guards: { module: "compliance" },
    order: 45.5,
    notes: "Extended compliance endpoints: work-queue, regulatory-change triage, mapping analysis, reports catalog, admin settings, obligation applicability",
  },
  {
    id: "routes_compliance_workspace_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance-workspace.routes",
    exportName: "default",
    mountPath: "/api/compliance-ws",
    guards: { module: "compliance" },
    order: 46,
  },
  {
    id: "routes_controls_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/controls.routes",
    exportName: "default",
    mountPath: "/api/controls",
    guards: { module: "compliance" },
    order: 47,
  },
  {
    id: "routes_control_process_cycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/control-process-cycle.routes",
    exportName: "default",
    mountPath: "/api/controls/:id/process-cycle",
    guards: { module: "compliance" },
    order: 48,
  },
  {
    id: "routes_control_lifecycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/control-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/lifecycle",
    guards: { module: "compliance" },
    order: 49,
  },
  {
    id: "routes_ucf_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/ucf.routes",
    exportName: "default",
    mountPath: "/api/ucf",
    guards: { module: "compliance" },
    order: 50,
  },
  {
    id: "routes_frameworks_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/frameworks.routes",
    exportName: "default",
    mountPath: "/api/frameworks",
    guards: { module: "compliance" },
    order: 51,
  },
  {
    id: "routes_framework_mapping_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/framework-mapping.routes",
    exportName: "default",
    mountPath: "/api/framework-mapping",
    guards: { module: "compliance" },
    order: 52,
  },
  {
    id: "routes_mapping_routes:mappingRouter",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/integration/mapping.routes",
    exportName: "mappingRouter",
    mountPath: "/api/mappings",
    guards: { module: "compliance" },
    order: 53,
  },
  {
    id: "routes_mapping_routes:objectsRouter",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/integration/mapping.routes",
    exportName: "objectsRouter",
    mountPath: "/api/objects",
    guards: { module: "compliance" },
    order: 54,
  },
  {
    id: "routes_common_objects_routes:exceptionRoutes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/integration/common-objects.routes",
    exportName: "exceptionRoutes",
    mountPath: "/api/exceptions",
    guards: { module: "compliance" },
    order: 55,
  },
  {
    id: "routes_scoring_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/scoring.routes",
    exportName: "default",
    mountPath: "/api/scoring-policies",
    guards: { module: "compliance" },
    order: 56,
  },
  {
    id: "routes_scoring_policies_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/scoring-policies.routes",
    exportName: "default",
    mountPath: "/api/scoring-policies-standalone",
    guards: { module: "compliance" },
    order: 57,
  },
  {
    id: "routes_scoring_policy_engine_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/scoring-policy-engine.routes",
    exportName: "default",
    mountPath: "/api/scoring-policy-engine",
    guards: { module: "compliance" },
    order: 58,
  },
  {
    id: "routes_compliance_drift_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance-drift.routes",
    exportName: "default",
    mountPath: "/api/compliance-drift",
    guards: { module: "compliance" },
    order: 119,
  },
  {
    id: "routes_dora_resilience_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/dora-resilience.routes",
    exportName: "default",
    mountPath: "/api/dora-resilience",
    guards: { module: "compliance" },
    order: 123,
    apiOnly: "service-api",
  },
  {
    id: "routes_ai_privacy_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai-governance/routes/ai/ai-privacy-governance.routes",
    exportName: "default",
    mountPath: "/api/ai-privacy",
    guards: { module: "compliance" },
    order: 124,
  },
  {
    id: "routes_pdpl_consent_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/pdpl-consent.routes",
    exportName: "default",
    mountPath: "/api/pdpl-consent",
    guards: { module: "compliance" },
    order: 140,
  },
  // DELETED: consent-lifecycle.routes — empty stub removed (Law 7)
  // {
  //   id: "routes_consent_lifecycle_routes",
  //   sourceFile: "modules/platform/routes/consent-lifecycle.routes",
  //   mountPath: "/api/consent-lifecycle",
  // },
  {
    id: "routes_dpia_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/dpia.routes",
    exportName: "default",
    mountPath: "/api/dpia",
    guards: { module: "compliance" },
    order: 268,
  },
  {
    id: "routes_privacy_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/privacy.routes",
    exportName: "default",
    mountPath: "/api/privacy-ops",
    guards: { module: "compliance" },
    order: 269,
  },
  {
    id: "routes_privacy_budget_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/privacy-budget.routes",
    exportName: "default",
    mountPath: "/api/privacy-budget",
    guards: { module: "compliance" },
    order: 270,
  },
  {
    id: "routes_compliance_attestation_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance-attestation.routes",
    exportName: "default",
    mountPath: "/api/compliance-attestation",
    guards: { module: "compliance" },
    order: 297,
  },
  {
    id: "routes_continuous_attestation_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/misc/continuous-attestation.routes",
    exportName: "default",
    mountPath: "/api/continuous-attestation",
    guards: { module: "compliance" },
    order: 298,
  },
  {
    id: "routes_issues_controls_advanced_routes:controlsAdvancedRouter",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "namedExport",
    sourceFile: "modules/platform/routes/compliance-regulatory/issues-controls-advanced.routes",
    exportName: "controlsAdvancedRouter",
    mountPath: "/api/controls-advanced",
    guards: { module: "compliance" },
    order: 299,
  },
  {
    id: "routes_ai_dpia_enhanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-dpia-enhanced.routes",
    exportName: "default",
    mountPath: "/api/ai-dpia",
    guards: { module: "compliance" },
    order: 353,
    notes: "Enhanced AI DPIA and Privacy Impact assessments",
  },
  {
    id: "routes_ai_compliance_framework_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/ai/routes/ai-compliance-framework.routes",
    exportName: "default",
    mountPath: "/api/ai-compliance-framework",
    guards: { module: "compliance" },
    order: 356,
    notes: "AI Compliance Framework Mapping (NIST AI RMF, EU AI Act, SDAIA)",
  },
  {
    id: "routes_compliance_gaps_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance/compliance-gaps.routes",
    exportName: "default",
    mountPath: "/api/compliance-gaps",
    guards: { module: "compliance" },
    order: 357,
    notes: "Continuous compliance gap detection (Tier 1 #3)",
  },
  {
    id: "routes_ksa_regulatory_reports_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/ksa/ksa-regulatory-reports.routes",
    exportName: "default",
    mountPath: "/api/ksa-regulatory",
    guards: { module: "compliance" },
    order: 358,
    notes: "KSA Regulatory Reports (NCA, SAMA, PDPL) and KSA-weighted compliance scoring",
  },
  {
    id: "routes_ksa_sector_maturity_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/ksa/ksa-sector-maturity.routes",
    exportName: "default",
    mountPath: "/api/ksa-sector-maturity",
    guards: { module: "compliance" },
    order: 359,
    notes: "KSA Sector-Specific Compliance Maturity Models (Banking, Healthcare, Telecom)",
  },
  {
    id: "routes_ksa_regulatory_changes_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/ksa/ksa-regulatory-changes.routes",
    exportName: "default",
    mountPath: "/api/ksa-regulatory-changes",
    guards: { module: "compliance" },
    order: 360,
    notes: "KSA Regulatory Change Tracking and Tenant Notifications",
  },
  {
    id: "routes_compliance_diagnostics_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/compliance-diagnostics.routes",
    exportName: "default",
    mountPath: "/api/compliance-diagnostics",
    guards: { module: "compliance" },
    order: 362,
    notes: "Compliance diagnostics: overdue obligations, mapping drift, missing evidence",
  },
  {
    id: "routes_ksa_cross_framework_mapping_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/compliance/routes/ksa/ksa-cross-framework-mapping.routes",
    exportName: "default",
    mountPath: "/api/ksa-cross-framework",
    guards: { module: "compliance" },
    order: 361,
    notes: "KSA Cross-Framework Control Mapping Intelligence (NCA-ECC ↔ SAMA-CSF)",
  },
];
