// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const GOVERNANCE_ROUTES: RouteDefinition[] = [
  {
    id: "routes_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance.routes",
    exportName: "default",
    mountPath: "/api/governance",
    guards: { module: "governance" },
    order: 11,
  },
  {
    id: "routes_governance_mandates_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-mandates.routes",
    exportName: "default",
    mountPath: "/api/governance/mandates",
    guards: { module: "governance" },
    order: 12,
  },
  {
    id: "routes_governance_delegations_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-delegations.routes",
    exportName: "default",
    mountPath: "/api/governance/delegations",
    guards: { module: "governance" },
    order: 13,
  },
  {
    id: "routes_governance_obligations_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-obligations.routes",
    exportName: "default",
    mountPath: "/api/governance/obligations",
    guards: { module: "governance" },
    order: 14,
  },
  {
    id: "routes_governance_charters_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-charters.routes",
    exportName: "default",
    mountPath: "/api/governance/charters",
    guards: { module: "governance" },
    order: 15,
  },
  {
    id: "routes_governance_health_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-health.routes",
    exportName: "default",
    mountPath: "/api/governance/health",
    guards: { module: "governance" },
    order: 16,
  },
  {
    id: "routes_governance_structure_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-structure.routes",
    exportName: "default",
    mountPath: "/api/governance/structure",
    guards: { module: "governance" },
    order: 17,
  },
  {
    id: "routes_governance_board_packs_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-board-packs.routes",
    exportName: "default",
    mountPath: "/api/governance/board-packs",
    guards: { module: "governance" },
    order: 18,
  },
  {
    id: "routes_governance_responsibilities_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-responsibilities.routes",
    exportName: "default",
    mountPath: "/api/governance/responsibilities",
    guards: { module: "governance" },
    order: 19,
  },
  {
    id: "routes_governance_raci_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-raci.routes",
    exportName: "default",
    mountPath: "/api/governance/raci",
    guards: { module: "governance" },
    order: 20,
  },
  {
    id: "routes_governance_enforcement_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-enforcement.routes",
    exportName: "default",
    mountPath: "/api/governance/enforcement",
    guards: { module: "governance" },
    order: 21,
  },
  {
    id: "routes_governance_reviews_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-reviews.routes",
    exportName: "default",
    mountPath: "/api/governance/reviews",
    guards: { module: "governance" },
    order: 22,
  },
  {
    id: "routes_governance_acknowledgements_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-acknowledgements.routes",
    exportName: "default",
    mountPath: "/api/governance/acknowledgements",
    guards: { module: "governance" },
    order: 23,
  },
  {
    id: "routes_governance_objectives_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-objectives.routes",
    exportName: "default",
    mountPath: "/api/governance/objectives",
    guards: { module: "governance" },
    order: 24,
  },
  {
    id: "routes_governance_executive_summaries_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-executive-summaries.routes",
    exportName: "default",
    mountPath: "/api/governance/executive-summaries",
    guards: { module: "governance" },
    order: 25,
  },
  {
    id: "routes_governance_hooks_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-hooks.routes",
    exportName: "default",
    mountPath: "/api/governance/hooks",
    guards: { module: "governance" },
    order: 26,
  },
  {
    id: "routes_governance_reviews_routes__alias_api_governance_policy_reviews",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-reviews.routes",
    exportName: "default",
    mountPath: "/api/governance/policy-reviews",
    guards: { module: "governance" },
    order: 27,
  },
  {
    id: "routes_governance_acknowledgements_routes__alias_api_governance_policy_acks",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-acknowledgements.routes",
    exportName: "default",
    mountPath: "/api/governance/policy-acks",
    guards: { module: "governance" },
    order: 28,
  },
  {
    id: "routes_governance_registers_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-registers.routes",
    exportName: "default",
    mountPath: "/api/governance/registers",
    guards: { module: "governance" },
    order: 29,
  },
  {
    id: "routes_governance_raci_templates_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-raci-templates.routes",
    exportName: "default",
    mountPath: "/api/governance/raci-templates",
    guards: { module: "governance" },
    order: 30,
  },
  {
    id: "routes_ethics_governance_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/misc/ethics-governance.routes",
    exportName: "default",
    mountPath: "/api/governance/ethics",
    guards: { module: "governance" },
    order: 31,
  },
  {
    id: "routes_governance_workload_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-workload.routes",
    exportName: "default",
    mountPath: "/api/governance/workload",
    guards: { module: "governance" },
    order: 32,
  },
  {
    id: "routes_governance_ai_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-ai.routes",
    exportName: "default",
    mountPath: "/api/governance/ai",
    guards: { module: "governance" },
    order: 33,
  },
  {
    id: "routes_governance_os_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-os.routes",
    exportName: "default",
    mountPath: "/api/governance-os",
    guards: { module: "governance" },
    order: 34,
  },
  {
    id: "routes_grc_lifecycle_gaps_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/grc-lifecycle-gaps.routes",
    exportName: "default",
    mountPath: "/api/grc-lifecycle",
    guards: { module: "governance" },
    order: 35,
  },
  {
    id: "routes_grc_raci_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/misc/grc-raci.routes",
    exportName: "default",
    mountPath: "/api/grc-raci",
    guards: { module: "governance" },
    order: 36,
  },
  {
    id: "routes_governance_os_context_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-os-context.routes",
    exportName: "default",
    mountPath: "/api/governance-os",
    guards: { module: "governance" },
    order: 37,
  },
  {
    id: "routes_initiative_orchestrator_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/misc/initiative-orchestrator.routes",
    exportName: "default",
    mountPath: "/api/governance-os/leadership",
    guards: { module: "governance" },
    order: 38,
  },
  {
    id: "routes_governance_os_learning_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/governance/routes/governance/governance-os-learning.routes",
    exportName: "default",
    mountPath: "/api/governance-os",
    guards: { module: "governance" },
    order: 39,
  },
];
