// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const POLICY_ROUTES: RouteDefinition[] = [
  {
    id: "routes_policy_code_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-code.routes",
    exportName: "default",
    mountPath: "/api/policy-code",
    guards: { module: "policy" },
    order: 88,
  },
  {
    id: "routes_policies_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policies.routes",
    exportName: "default",
    mountPath: "/api/policies",
    guards: { module: "policy" },
    order: 89,
  },
  {
    id: "routes_policy_lifecycle_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-lifecycle.routes",
    exportName: "default",
    mountPath: "/api/policy-lifecycle",
    guards: { module: "policy" },
    order: 90,
  },
  {
    id: "routes_policy_template_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-template.routes",
    exportName: "default",
    mountPath: "/api/policy-templates",
    guards: { module: "policy" },
    order: 91,
  },
  {
    id: "routes_policy_attestation_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-attestation.routes",
    exportName: "default",
    mountPath: "/api/attestation",
    guards: { module: "policy" },
    order: 92,
  },
  {
    id: "routes_sop_library_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/platform/routes/content/sop-library.routes",
    exportName: "default",
    mountPath: "/api/sop-library",
    guards: { module: "policy" },
    order: 205,
  },
  {
    id: "routes_policy_impact_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-impact.routes",
    exportName: "default",
    mountPath: "/api/policy-impact",
    guards: { module: "policy" },
    order: 93,
  },
  {
    id: "routes_policy_overview_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-overview.routes",
    exportName: "default",
    mountPath: "/api/policy-overview",
    guards: { module: "policy" },
    order: 94,
  },
  {
    id: "routes_policy_exception_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-exception.routes",
    exportName: "default",
    mountPath: "/api/policy-exceptions",
    guards: { module: "policy" },
    order: 95,
  },
  {
    id: "routes_policy_publication_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-publication.routes",
    exportName: "default",
    mountPath: "/api/policy-publications",
    guards: { module: "policy" },
    order: 96,
  },
  {
    id: "routes_policy_coverage_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-coverage.routes",
    exportName: "default",
    mountPath: "/api/policy-coverage",
    guards: { module: "policy" },
    order: 97,
  },
  {
    id: "routes_policy_reports_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/policy/routes/policy-reports.routes",
    exportName: "default",
    mountPath: "/api/policy-reports",
    guards: { module: "policy" },
    order: 98,
  },
];
