// @ts-nocheck — module-layer imports not yet extracted
import type { RouteDefinition } from '../../../platform/routing/route-definition';

export const VENDOR_ROUTES: RouteDefinition[] = [
  {
    id: "routes_vendors_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendors.routes",
    exportName: "default",
    mountPath: "/api/vendors",
    guards: { module: "vendor" },
    order: 97,
  },
  {
    id: "routes_vendor_advanced_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-advanced.routes",
    exportName: "default",
    mountPath: "/api/vendors-advanced",
    guards: { module: "vendor" },
    order: 98,
  },
  {
    id: "routes_vendor_risk_ext_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-risk-ext.routes",
    exportName: "default",
    mountPath: "/api/vendor-risk",
    guards: { module: "vendor", tier: "vendor_automation" },
    order: 99,
  },
  {
    id: "routes_vendor_cyber_rating_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-cyber-rating.routes",
    exportName: "default",
    mountPath: "/api/vendor-cyber-rating",
    guards: { module: "vendor" },
    order: 100,
  },
  {
    id: "routes_vendor_compliance_sync_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-compliance-sync.routes",
    exportName: "default",
    mountPath: "/api/vendor-compliance-sync",
    guards: { module: "vendor" },
    order: 101,
  },
  {
    id: "routes_score_calibration_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/risk/routes/score-calibration.routes",
    exportName: "default",
    mountPath: "/api/score-calibration",
    guards: { module: "vendor" },
    order: 102,
  },
  {
    id: "routes_vendor_scoring_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-scoring.routes",
    exportName: "default",
    mountPath: "/api/vendor-scoring",
    guards: { module: "vendor" },
    order: 103,
  },
  {
    id: "routes_vendor_engagements_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-engagements.routes",
    exportName: "default",
    mountPath: "/api/vendor-engagements",
    guards: { module: "vendor" },
    order: 104,
  },
  {
    id: "routes_vendor_issues_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-issues.routes",
    exportName: "default",
    mountPath: "/api/vendor-issues",
    guards: { module: "vendor" },
    order: 105,
  },
  {
    id: "routes_vendor_dashboard_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-dashboard.routes",
    exportName: "default",
    mountPath: "/api/vendor-dashboard",
    guards: { module: "vendor" },
    order: 106,
  },
  {
    id: "routes_vendor_reports_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-reports.routes",
    exportName: "default",
    mountPath: "/api/vendor-reports",
    guards: { module: "vendor" },
    order: 107,
  },
  {
    id: "routes_vendor_admin_routes",
    productKey: "shahin-ai",
    ownerKind: "product",
    sourceKind: "defaultExport",
    sourceFile: "modules/vendor/routes/vendor-admin.routes",
    exportName: "default",
    mountPath: "/api/vendor-admin",
    guards: { module: "vendor" },
    order: 108,
  },
];
