-- dos:extracted-from: ops/migrations/tenant/027_tenant_schema_tables.sql
-- dos:supersedes-checksum: b618781c42608331e3344799991235a22afbb73ab72c9789ef6478fd164416c8
-- dos:owning-module: risk
-- dos:tables: risk_aggregation, risk_ai_suggestions, risk_appetite_statements, risk_assessments, risk_categories, risk_change_log, risk_control_mappings, risk_correlations, risk_events, risk_external_mappings, risk_heat_map_config, risk_indicators, risk_indicators_history, risk_kris, risk_models, risk_owners, risk_registry, risk_reporting_snapshots, risk_risks, risk_scenarios, risk_scenarios_impact, risk_settings, risk_simulations, risk_taxonomy, risk_tolerance, risk_treatment_plans, risk_treatment_progress, risk_treatments, risk_versions, risk_watchers
-- dos:statement-count: 60
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_risks" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_risks_tenant ON "__TENANT_SCHEMA__"."risk_risks" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_assessments" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_assessments_tenant ON "__TENANT_SCHEMA__"."risk_assessments" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_treatments" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_treatments_tenant ON "__TENANT_SCHEMA__"."risk_treatments" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_categories" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_categories_tenant ON "__TENANT_SCHEMA__"."risk_categories" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_appetite_statements" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_appetite_statements_tenant ON "__TENANT_SCHEMA__"."risk_appetite_statements" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_scenarios" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_scenarios_tenant ON "__TENANT_SCHEMA__"."risk_scenarios" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_indicators" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_indicators_tenant ON "__TENANT_SCHEMA__"."risk_indicators" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_indicators_history" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_indicators_history_tenant ON "__TENANT_SCHEMA__"."risk_indicators_history" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_control_mappings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_control_mappings_tenant ON "__TENANT_SCHEMA__"."risk_control_mappings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_reporting_snapshots" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  title TEXT NOT NULL,
  query_definition JSONB,
  last_run_at TIMESTAMPTZ,
  schedule TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_reporting_snapshots_tenant ON "__TENANT_SCHEMA__"."risk_reporting_snapshots" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_ai_suggestions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_ai_suggestions_tenant ON "__TENANT_SCHEMA__"."risk_ai_suggestions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_heat_map_config" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_heat_map_config_tenant ON "__TENANT_SCHEMA__"."risk_heat_map_config" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_treatment_plans" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_treatment_plans_tenant ON "__TENANT_SCHEMA__"."risk_treatment_plans" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_treatment_progress" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_treatment_progress_tenant ON "__TENANT_SCHEMA__"."risk_treatment_progress" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_external_mappings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_external_mappings_tenant ON "__TENANT_SCHEMA__"."risk_external_mappings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_versions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_versions_tenant ON "__TENANT_SCHEMA__"."risk_versions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_change_log" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_change_log_tenant ON "__TENANT_SCHEMA__"."risk_change_log" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_settings_tenant ON "__TENANT_SCHEMA__"."risk_settings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_kris" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_kris_tenant ON "__TENANT_SCHEMA__"."risk_kris" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_scenarios_impact" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_scenarios_impact_tenant ON "__TENANT_SCHEMA__"."risk_scenarios_impact" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_taxonomy" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_taxonomy_tenant ON "__TENANT_SCHEMA__"."risk_taxonomy" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_owners" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_owners_tenant ON "__TENANT_SCHEMA__"."risk_owners" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_watchers" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_watchers_tenant ON "__TENANT_SCHEMA__"."risk_watchers" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_registry" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_registry_tenant ON "__TENANT_SCHEMA__"."risk_registry" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_events" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_events_tenant ON "__TENANT_SCHEMA__"."risk_events" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_correlations" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_correlations_tenant ON "__TENANT_SCHEMA__"."risk_correlations" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_models" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_models_tenant ON "__TENANT_SCHEMA__"."risk_models" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_simulations" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_simulations_tenant ON "__TENANT_SCHEMA__"."risk_simulations" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_aggregation" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_aggregation_tenant ON "__TENANT_SCHEMA__"."risk_aggregation" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."risk_tolerance" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_risk_tolerance_tenant ON "__TENANT_SCHEMA__"."risk_tolerance" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;
