import { RedisStreamEventBus } from '@dos/event-backbone';
import { logger } from '@dos/platform-core/observability';
import { ServiceClient } from '@dos/service-client';
import { recordAudit } from '../adapters/audit.adapter';
import { sendNotification } from '../adapters/notification.adapter';
import * as evidenceService from '../domain/evidence.service';
import * as findingService from '../domain/finding.service';
import { publishAuditFindingCreated } from './publisher';

const workflowClient = new ServiceClient({
  baseUrl: process.env.WORKFLOW_SERVICE_URL || 'http://127.0.0.1:4004',
  timeout: 5000,
  retries: 1,
});

/**
 * Wave 2C: Register module-level event handlers from modules/evidence and modules/audit.
 */
export function registerModuleConsumers(eventBus: RedisStreamEventBus): void {
  const moduleConfigs = [
    { name: 'evidence', path: '../../../modules/evidence/dist/backend/evidence/events/evidence.subscribers' },
    { name: 'audit', path: '../../../modules/audit/dist/audit/events/audit.subscribers' },
  ];

  for (const cfg of moduleConfigs) {
    try {
      const moduleSubscribers = require(cfg.path);

      if (typeof moduleSubscribers.subscribeAll === 'function') {
        const busAdapter = {
          on(event: string, handler: (payload: Record<string, unknown>) => Promise<void>) {
            eventBus.subscribe(event, async (envelope) => {
              try {
                await handler(envelope as unknown as Record<string, unknown>);
              } catch (err) {
                logger.error(`[evidence-audit-reporting-service] Module ${cfg.name} event handler failed for ${event}`, { error: err });
              }
            });
          },
        };
        moduleSubscribers.subscribeAll(busAdapter);
        logger.info(`[evidence-audit-reporting-service] Module ${cfg.name} event subscribers registered`);
      } else if (typeof moduleSubscribers.getSubscriptionHandlers === 'function') {
        const handlers = moduleSubscribers.getSubscriptionHandlers() as Map<string, (payload: Record<string, unknown>) => Promise<void>>;
        for (const [eventName, handler] of handlers) {
          eventBus.subscribe(eventName, async (envelope) => {
            try {
              await handler(envelope as unknown as Record<string, unknown>);
            } catch (err) {
              logger.error(`[evidence-audit-reporting-service] Module ${cfg.name} handler failed for ${eventName}`, { error: err });
            }
          });
        }
        logger.info(`[evidence-audit-reporting-service] Registered ${handlers.size} module ${cfg.name} event handlers`);
      }
    } catch (err) {
      logger.warn(`[evidence-audit-reporting-service] Module ${cfg.name} event subscribers not available, skipping`, { error: err });
    }
  }
}

export function registerConsumers(eventBus: RedisStreamEventBus): void {
  eventBus.subscribe('compliance.assessed', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[evidence-audit-reporting-service] Processing compliance.assessed: Create audit finding when compliance gap detected in assessment`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const created = await findingService.create(tenantId, {
          title: (payload.title as string) || `Auto: compliance.assessed - ${envelope.eventId.slice(0, 8)}`,
          severity: (payload.severity as string) || 'medium',
          status: 'open',
          description: `Auto-generated from compliance.assessed event (ID: ${envelope.eventId})`,
        });
        logger.info(`[evidence-audit-reporting-service] Auto-created finding`, { id: created.finding_id, tenantId });
        await publishAuditFindingCreated(tenantId, created.finding_id, { source: 'compliance.assessed', autoGenerated: true }, envelope.userId);
        if (envelope.userId) {
          sendNotification(tenantId, envelope.userId, 'Finding Created', `A new finding was auto-created from compliance.assessed`, 'info', { entityId: created.finding_id }).catch(() => {});
        }

      await recordAudit(
        tenantId,
        'createFindingFromAssessment',
        'finding',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'compliance.assessed', payload },
      );
    } catch (err) {
      logger.error(`[evidence-audit-reporting-service] Failed to process compliance.assessed`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('control.tested', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[evidence-audit-reporting-service] Processing control.tested: Update evidence validity when control is tested`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const entityId = (payload.entityId as string) || (payload.evidence_id as string);
      if (entityId) {
        const existing = await evidenceService.getById(tenantId, entityId);
        if (existing) {
          await evidenceService.update(tenantId, entityId, {
            status: 'under-review',
          });
          logger.info(`[evidence-audit-reporting-service] updateEvidenceValidity: updated evidence`, { entityId, tenantId });
        }
      } else {
        const items = await evidenceService.list(tenantId, { pageSize: 10, status: 'active' });
        for (const item of items.data) {
          await evidenceService.update(tenantId, (item as any).evidence_id, {
            status: 'under-review',
          });
        }
        logger.info(`[evidence-audit-reporting-service] updateEvidenceValidity: batch-reviewed evidence items`, { count: items.data.length, tenantId });
      }

      await recordAudit(
        tenantId,
        'updateEvidenceValidity',
        'evidence',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'control.tested', payload },
      );
    } catch (err) {
      logger.error(`[evidence-audit-reporting-service] Failed to process control.tested`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('risk.mitigated', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[evidence-audit-reporting-service] Processing risk.mitigated: Resolve related findings when risk is mitigated`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const entityId = (payload.entityId as string) || (payload.finding_id as string);
      if (entityId) {
        const existing = await findingService.getById(tenantId, entityId);
        if (existing) {
          await findingService.update(tenantId, entityId, {
            status: 'resolved',
          });
          logger.info(`[evidence-audit-reporting-service] resolveFindingsForRisk: updated finding`, { entityId, tenantId });
        }
      } else {
        const items = await findingService.list(tenantId, { pageSize: 10, status: 'active' });
        for (const item of items.data) {
          await findingService.update(tenantId, (item as any).finding_id, {
            status: 'under-review',
          });
        }
        logger.info(`[evidence-audit-reporting-service] resolveFindingsForRisk: batch-reviewed finding items`, { count: items.data.length, tenantId });
      }

      await recordAudit(
        tenantId,
        'resolveFindingsForRisk',
        'finding',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'risk.mitigated', payload },
      );
    } catch (err) {
      logger.error(`[evidence-audit-reporting-service] Failed to process risk.mitigated`, { eventId: envelope.eventId, error: err });
    }
  });
}
