import { RedisStreamEventBus } from '@dos/event-backbone';
import { logger } from '@dos/platform-core/observability';
import { ServiceClient } from '@dos/service-client';
import { recordAudit } from '../adapters/audit.adapter';
import { sendNotification } from '../adapters/notification.adapter';
import * as riskService from '../domain/risk.service';
import * as incidentService from '../domain/incident.service';
import { publishRiskCreated, publishIncidentCreated } from './publisher';

const workflowClient = new ServiceClient({
  baseUrl: process.env.WORKFLOW_SERVICE_URL || 'http://127.0.0.1:4004',
  timeout: 5000,
  retries: 1,
});

/**
 * Wave 2C: Register module-level event handlers from modules/risk.
 * These are the rich domain event subscribers extracted from the monolith.
 * Wrapped in try/catch so the service starts even if the module is unavailable.
 */
export function registerModuleConsumers(eventBus: RedisStreamEventBus): void {
  try {
    // Import the module's subscriber registry which has handlers for:
    // compliance.gap_detected, vendor.risk_changed, asset.classified,
    // incident.classified, audit.finding_created, control.effectiveness_low,
    // evidence.coverage_low, bcp.rto_rpo_drift, workflow.status_changed
    const moduleSubscribers = require(
      '../../../modules/risk/dist/risk/events/risk.subscribers'
    );

    if (typeof moduleSubscribers.subscribeAll === 'function') {
      // The module exposes subscribeAll(bus) which registers all domain handlers
      const busAdapter = {
        on(event: string, handler: (payload: Record<string, unknown>) => Promise<void>) {
          eventBus.subscribe(event, async (envelope) => {
            try {
              await handler(envelope as unknown as Record<string, unknown>);
            } catch (err) {
              logger.error(`[risk-incident-service] Module event handler failed for ${event}`, { error: err });
            }
          });
        },
      };
      moduleSubscribers.subscribeAll(busAdapter);
      logger.info('[risk-incident-service] Module event subscribers registered');
    } else if (typeof moduleSubscribers.getSubscriptionHandlers === 'function') {
      const handlers = moduleSubscribers.getSubscriptionHandlers() as Map<string, (payload: Record<string, unknown>) => Promise<void>>;
      for (const [eventName, handler] of handlers) {
        eventBus.subscribe(eventName, async (envelope) => {
          try {
            await handler(envelope as unknown as Record<string, unknown>);
          } catch (err) {
            logger.error(`[risk-incident-service] Module handler failed for ${eventName}`, { error: err });
          }
        });
      }
      logger.info(`[risk-incident-service] Registered ${handlers.size} module event handlers`);
    }
  } catch (err) {
    logger.warn('[risk-incident-service] Module event subscribers not available, skipping', { error: err });
  }
}

export function registerConsumers(eventBus: RedisStreamEventBus): void {
  eventBus.subscribe('compliance.control.failed', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[risk-incident-service] Processing compliance.control.failed: Auto-create risk when compliance control fails`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const created = await riskService.create(tenantId, {
          title: (payload.title as string) || `Auto: compliance.control.failed - ${envelope.eventId.slice(0, 8)}`,
          category: (payload.category as string) || (payload.category as string) || 'auto-generated',
          status: 'open',
          description: `Auto-generated from compliance.control.failed event (ID: ${envelope.eventId})`,
        });
        logger.info(`[risk-incident-service] Auto-created risk`, { id: created.risk_id, tenantId });
        await publishRiskCreated(tenantId, created.risk_id, { source: 'compliance.control.failed', autoGenerated: true }, envelope.userId);
        if (envelope.userId) {
          sendNotification(tenantId, envelope.userId, 'Risk Created', `A new risk was auto-created from compliance.control.failed`, 'info', { entityId: created.risk_id }).catch(() => {});
        }

      await recordAudit(
        tenantId,
        'createRiskFromComplianceFailure',
        'risk',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'compliance.control.failed', payload },
      );
    } catch (err) {
      logger.error(`[risk-incident-service] Failed to process compliance.control.failed`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('asset.vulnerability.detected', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[risk-incident-service] Processing asset.vulnerability.detected: Auto-create incident when asset vulnerability detected`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const created = await incidentService.create(tenantId, {
          title: (payload.title as string) || `Auto: asset.vulnerability.detected - ${envelope.eventId.slice(0, 8)}`,
          severity: (payload.severity as string) || 'medium',
          status: 'open',
          description: `Auto-generated from asset.vulnerability.detected event (ID: ${envelope.eventId})`,
        });
        logger.info(`[risk-incident-service] Auto-created incident`, { id: created.incident_id, tenantId });
        await publishIncidentCreated(tenantId, created.incident_id, { source: 'asset.vulnerability.detected', autoGenerated: true }, envelope.userId);
        if (envelope.userId) {
          sendNotification(tenantId, envelope.userId, 'Incident Created', `A new incident was auto-created from asset.vulnerability.detected`, 'info', { entityId: created.incident_id }).catch(() => {});
        }

      await recordAudit(
        tenantId,
        'createIncidentFromVulnerability',
        'incident',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'asset.vulnerability.detected', payload },
      );
    } catch (err) {
      logger.error(`[risk-incident-service] Failed to process asset.vulnerability.detected`, { eventId: envelope.eventId, error: err });
    }
  });

  eventBus.subscribe('vendor.risk.elevated', async (envelope) => {
    const tenantId = envelope.tenantId;
    const payload = envelope.payload as Record<string, unknown>;
    try {
      logger.info(`[risk-incident-service] Processing vendor.risk.elevated: Auto-create risk when vendor risk is elevated`, {
        eventId: envelope.eventId,
        tenantId,
      });

      const created = await riskService.create(tenantId, {
          title: (payload.title as string) || `Auto: vendor.risk.elevated - ${envelope.eventId.slice(0, 8)}`,
          category: (payload.category as string) || (payload.category as string) || 'auto-generated',
          status: 'open',
          description: `Auto-generated from vendor.risk.elevated event (ID: ${envelope.eventId})`,
        });
        logger.info(`[risk-incident-service] Auto-created risk`, { id: created.risk_id, tenantId });
        await publishRiskCreated(tenantId, created.risk_id, { source: 'vendor.risk.elevated', autoGenerated: true }, envelope.userId);
        if (envelope.userId) {
          sendNotification(tenantId, envelope.userId, 'Risk Created', `A new risk was auto-created from vendor.risk.elevated`, 'info', { entityId: created.risk_id }).catch(() => {});
        }

      await recordAudit(
        tenantId,
        'createRiskFromVendorElevation',
        'risk',
        envelope.eventId,
        envelope.userId,
        { source: envelope.source, event: 'vendor.risk.elevated', payload },
      );
    } catch (err) {
      logger.error(`[risk-incident-service] Failed to process vendor.risk.elevated`, { eventId: envelope.eventId, error: err });
    }
  });
}
