-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=risk scope=tenant function=anti
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/risk/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (3):
--   * anti
--   * risk_score_history
--   * risk_scoring_models
--
-- Source migrations (immutable, 4):
--   * modules/risk/db/tenant/migrations/113_risk_scoring_tables_v1.sql
--   * modules/risk/db/tenant/migrations/114_risk_scoring_tables_v2.sql
--   * modules/risk/db/tenant/migrations/115_risk_scoring_tables_v3.sql
--   * modules/risk/db/tenant/migrations/119_risk_scoring_tables_v4.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS anti-pattern in risk-scoring.service.ts

-- Risk scoring models (configurable scoring formulas, dimensions, thresholds)
CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_scoring_models (
  model_id VARCHAR(100) PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  dimensions JSONB NOT NULL DEFAULT '[]',
  thresholds JSONB NOT NULL DEFAULT '{}',
  formula VARCHAR(20) NOT NULL DEFAULT 'weighted',
  zone_definitions JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_scoring_models_created_at ON __TENANT_SCHEMA__.risk_scoring_models (created_at DESC);

CREATE TABLE IF NOT EXISTS risk_score_history (
  history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  risk_id VARCHAR(16) NOT NULL,
  model_id VARCHAR(100) NOT NULL,
  dimension_scores JSONB NOT NULL,
  composite_score DECIMAL(6,2) NOT NULL,
  zone VARCHAR(20) NOT NULL,
  scored_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_risk_model ON risk_score_history (risk_id, model_id, scored_at DESC);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_scored_at ON risk_score_history (scored_at DESC);

CREATE TABLE IF NOT EXISTS anti-pattern in risk-scoring.service.ts

-- Risk scoring models (configurable scoring formulas, dimensions, thresholds)
CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_scoring_models (
  model_id VARCHAR(100) PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  dimensions JSONB NOT NULL DEFAULT '[]',
  thresholds JSONB NOT NULL DEFAULT '{}',
  formula VARCHAR(20) NOT NULL DEFAULT 'weighted',
  zone_definitions JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_scoring_models_created_at ON __TENANT_SCHEMA__.risk_scoring_models (created_at DESC);

CREATE TABLE IF NOT EXISTS risk_score_history (
  history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  risk_id VARCHAR(16) NOT NULL,
  model_id VARCHAR(100) NOT NULL,
  dimension_scores JSONB NOT NULL,
  composite_score DECIMAL(6,2) NOT NULL,
  zone VARCHAR(20) NOT NULL,
  scored_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_risk_model ON risk_score_history (risk_id, model_id, scored_at DESC);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_scored_at ON risk_score_history (scored_at DESC);

CREATE TABLE IF NOT EXISTS anti-pattern in risk-scoring.service.ts

-- Risk scoring models (configurable scoring formulas, dimensions, thresholds)
CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_scoring_models (
  model_id VARCHAR(100) PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  dimensions JSONB NOT NULL DEFAULT '[]',
  thresholds JSONB NOT NULL DEFAULT '{}',
  formula VARCHAR(20) NOT NULL DEFAULT 'weighted',
  zone_definitions JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_scoring_models_created_at ON __TENANT_SCHEMA__.risk_scoring_models (created_at DESC);

CREATE TABLE IF NOT EXISTS risk_score_history (
  history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  risk_id VARCHAR(16) NOT NULL,
  model_id VARCHAR(100) NOT NULL,
  dimension_scores JSONB NOT NULL,
  composite_score DECIMAL(6,2) NOT NULL,
  zone VARCHAR(20) NOT NULL,
  scored_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_risk_model ON risk_score_history (risk_id, model_id, scored_at DESC);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_scored_at ON risk_score_history (scored_at DESC);

CREATE TABLE IF NOT EXISTS anti-pattern in risk-scoring.service.ts

-- Risk scoring models (configurable scoring formulas, dimensions, thresholds)
CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.risk_scoring_models (
  model_id VARCHAR(100) PRIMARY KEY,
  name_en VARCHAR(200) NOT NULL,
  name_ar VARCHAR(200) NOT NULL,
  dimensions JSONB NOT NULL DEFAULT '[]',
  thresholds JSONB NOT NULL DEFAULT '{}',
  formula VARCHAR(20) NOT NULL DEFAULT 'weighted',
  zone_definitions JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_scoring_models_created_at ON __TENANT_SCHEMA__.risk_scoring_models (created_at DESC);

CREATE TABLE IF NOT EXISTS risk_score_history (
  history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  risk_id VARCHAR(16) NOT NULL,
  model_id VARCHAR(100) NOT NULL,
  dimension_scores JSONB NOT NULL,
  composite_score DECIMAL(6,2) NOT NULL,
  zone VARCHAR(20) NOT NULL,
  scored_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_risk_model ON risk_score_history (risk_id, model_id, scored_at DESC);

CREATE INDEX IF NOT EXISTS idx_risk_score_history_scored_at ON risk_score_history (scored_at DESC);
