-- Project role + role_permissions for module=governance
BEGIN;
INSERT INTO roles (code, module_code, template) VALUES ('governance.executive_owner','governance','executive_owner') ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (code, module_code, template) VALUES ('governance.module_lead','governance','module_lead') ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (code, module_code, template) VALUES ('governance.approver','governance','approver') ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (code, module_code, template) VALUES ('governance.contributor','governance','contributor') ON CONFLICT (code) DO NOTHING;
INSERT INTO roles (code, module_code, template) VALUES ('governance.viewer','governance','viewer') ON CONFLICT (code) DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.approve') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.manage') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.delete') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.record.configure') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.evidence.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.evidence.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.report.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.executive_owner','governance.export') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.record.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.record.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.record.approve') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.record.manage') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.record.configure') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.evidence.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.evidence.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.report.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.module_lead','governance.export') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.approver','governance.record.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.approver','governance.record.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.approver','governance.record.approve') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.approver','governance.evidence.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.approver','governance.report.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.contributor','governance.record.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.contributor','governance.record.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.contributor','governance.evidence.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.contributor','governance.evidence.write') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.contributor','governance.report.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.viewer','governance.record.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.viewer','governance.evidence.read') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_code, permission_code) VALUES ('governance.viewer','governance.report.read') ON CONFLICT DO NOTHING;
COMMIT;
