-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL PACK - module=dos scope=public pack=seed
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This pack consolidates non-table runtime-required statements (RLS policies,
-- GRANT/REVOKE, role/user, function/procedure, trigger, or seed inserts)
-- emitted by the source migrations listed below.
--
-- Statement count: 1
-- Source migrations (immutable, 1):
--   * platform/dos/migrations/public/20260425_0001_dos_users_tenant_scope.sql
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO dos.users (
    user_id, email, display_name, status, created_at,
    tenant_id, role, updated_at,
    onboarding_complete, member_onboarded, platform_role, last_login,
    full_name, first_name, last_name
)
SELECT
    u.user_id,
    u.email,
    COALESCE(u.display_name, u.name, u.full_name, u.email) AS display_name,
    COALESCE(u.status, 'active'),
    COALESCE(u.created_at, NOW()),
    u.tenant_id,
    u.role,
    COALESCE(u.updated_at, NOW()),
    COALESCE(u.onboarding_complete, FALSE),
    COALESCE(u.member_onboarded, FALSE),
    COALESCE(u.platform_role, 'member'),
    u.last_login,
    u.full_name,
    u.first_name,
    u.last_name
FROM public.users u
ON CONFLICT (user_id) DO UPDATE
   SET email                = EXCLUDED.email,
       display_name         = EXCLUDED.display_name,
       status               = EXCLUDED.status,
       tenant_id            = EXCLUDED.tenant_id,
       role                 = EXCLUDED.role,
       updated_at           = EXCLUDED.updated_at,
       onboarding_complete  = EXCLUDED.onboarding_complete,
       member_onboarded     = EXCLUDED.member_onboarded,
       platform_role        = EXCLUDED.platform_role,
       last_login           = EXCLUDED.last_login,
       full_name            = EXCLUDED.full_name,
       first_name           = EXCLUDED.first_name,
       last_name            = EXCLUDED.last_name;
