-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dos scope=public function=ai
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dos/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * ai_workflow_trigger_log
--   * ai_workflow_triggers
--
-- Source migrations (immutable, 1):
--   * platform/dos/migrations/public/20260425_0012_ai_workflow_triggers.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dos.ai_workflow_triggers (
  trigger_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         VARCHAR(64) NOT NULL,
  module            TEXT NOT NULL,
  signal            TEXT,
  rule              JSONB NOT NULL DEFAULT '{}'::jsonb,
  workflow_code     TEXT,
  enabled           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dos_ai_workflow_triggers_match
  ON dos.ai_workflow_triggers(tenant_id, module, enabled, signal);

CREATE TABLE IF NOT EXISTS dos.ai_workflow_trigger_log (
  log_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         VARCHAR(64) NOT NULL,
  trigger_id        UUID NOT NULL REFERENCES dos.ai_workflow_triggers(trigger_id) ON DELETE CASCADE,
  module            TEXT,
  signal            TEXT,
  payload           JSONB NOT NULL DEFAULT '{}'::jsonb,
  emitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dos_ai_workflow_trigger_log_tenant
  ON dos.ai_workflow_trigger_log(tenant_id, trigger_id, emitted_at DESC);
