-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dos scope=public function=dashboard
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dos/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * dashboard_widgets
--   * tenant_dashboard_widget_pins
--
-- Source migrations (immutable, 1):
--   * platform/dos/migrations/public/20260425_0014_dashboard_widget_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dos.dashboard_widgets (
  widget_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code                  VARCHAR(128) NOT NULL UNIQUE,
  title                 TEXT NOT NULL,
  description           TEXT,
  category              TEXT NOT NULL DEFAULT 'general',
  module                TEXT,
  default_layout        JSONB NOT NULL DEFAULT '{}'::jsonb,
  permissions_required  TEXT[] NOT NULL DEFAULT '{}',
  published_at          TIMESTAMPTZ,
  deleted_at            TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dos_dashboard_widgets_category
  ON dos.dashboard_widgets(category) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS dos.tenant_dashboard_widget_pins (
  pin_id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             VARCHAR(64) NOT NULL,
  widget_code           VARCHAR(128) NOT NULL,
  position              INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dos_tenant_dashboard_widget_pins_tenant_widget
  ON dos.tenant_dashboard_widget_pins(tenant_id, widget_code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_dos_tenant_dashboard_widget_pins_order
  ON dos.tenant_dashboard_widget_pins(tenant_id, position);
