-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dos scope=public function=tenants
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dos/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (5):
--   * modules_registry
--   * platform_events_log
--   * products_registry
--   * scheduled_jobs
--   * tenants_registry
--
-- Source migrations (immutable, 1):
--   * platform/dos/migrations/public/20260423_0100_create_platform_dos_schema.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS platform_dos.tenants_registry (
  tenant_id        TEXT        PRIMARY KEY,
  product_code     TEXT,
  status           TEXT        NOT NULL DEFAULT 'provisioning'
                   CHECK (status IN ('active', 'suspended', 'provisioning', 'decommissioned')),
  display_name     TEXT,
  registered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attributes       JSONB       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_tenants_status
  ON platform_dos.tenants_registry (status, registered_at DESC);

CREATE INDEX IF NOT EXISTS idx_tenants_product
  ON platform_dos.tenants_registry (product_code) WHERE product_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS platform_dos.modules_registry (
  module_code      TEXT        PRIMARY KEY,
  version          TEXT        NOT NULL,
  layer            TEXT        NOT NULL CHECK (layer IN ('platform', 'product')),
  owner_team       TEXT        NOT NULL,
  status           TEXT        NOT NULL DEFAULT 'registered'
                   CHECK (status IN ('registered', 'deregistered')),
  registered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deregistered_at  TIMESTAMPTZ,
  attributes       JSONB       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_modules_layer
  ON platform_dos.modules_registry (layer, status);

CREATE TABLE IF NOT EXISTS platform_dos.products_registry (
  product_code     TEXT        PRIMARY KEY,
  version          TEXT        NOT NULL,
  enabled          BOOLEAN     NOT NULL DEFAULT TRUE,
  display_name     TEXT,
  registered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attributes       JSONB       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_products_enabled
  ON platform_dos.products_registry (enabled, registered_at DESC);

CREATE TABLE IF NOT EXISTS platform_dos.platform_events_log (
  id               BIGSERIAL PRIMARY KEY,
  event_id         TEXT,
  event_type       TEXT        NOT NULL,
  tenant_id        TEXT        NOT NULL,
  payload          JSONB       NOT NULL DEFAULT '{}'::jsonb,
  correlation_id   TEXT,
  occurred_at      TIMESTAMPTZ NOT NULL,
  recorded_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_type_time
  ON platform_dos.platform_events_log (event_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_events_tenant_time
  ON platform_dos.platform_events_log (tenant_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_events_correlation
  ON platform_dos.platform_events_log (correlation_id) WHERE correlation_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS platform_dos.scheduled_jobs (
  job_id           TEXT        PRIMARY KEY,
  tenant_id        TEXT        NOT NULL,
  name             TEXT        NOT NULL,
  cron_expression  TEXT        NOT NULL,
  status           TEXT        NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'paused', 'completed', 'failed')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_triggered_at TIMESTAMPTZ,
  last_triggered_by TEXT,
  trigger_count    INTEGER     NOT NULL DEFAULT 0,
  attributes       JSONB       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_jobs_tenant_status
  ON platform_dos.scheduled_jobs (tenant_id, status);
