-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=dos scope=public function=vendor
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- platform/dos/migrations/public/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (2):
--   * notifications
--   * vendor_engagement_scores
--
-- Source migrations (immutable, 1):
--   * platform/dos/migrations/public/20260425_0016_vendor_notification_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dos.vendor_engagement_scores (
  point_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          VARCHAR(64) NOT NULL,
  vendor_id          VARCHAR(128) NOT NULL,
  score              DOUBLE PRECISION NOT NULL,
  source             TEXT,
  metadata           JSONB NOT NULL DEFAULT '{}'::jsonb,
  recorded_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dos_vendor_engagement_scores_vendor
  ON dos.vendor_engagement_scores(tenant_id, vendor_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS dos.notifications (
  notification_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          VARCHAR(64) NOT NULL,
  user_id            VARCHAR(64) NOT NULL,
  title              TEXT NOT NULL,
  body               TEXT,
  severity           TEXT NOT NULL DEFAULT 'info',
  module             TEXT,
  entity_type        TEXT,
  entity_id          VARCHAR(128),
  data               JSONB NOT NULL DEFAULT '{}'::jsonb,
  read               BOOLEAN NOT NULL DEFAULT FALSE,
  read_at            TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dos_notifications_unread
  ON dos.notifications(tenant_id, user_id, created_at DESC)
  WHERE read = FALSE;

CREATE INDEX IF NOT EXISTS idx_dos_notifications_user_recent
  ON dos.notifications(tenant_id, user_id, created_at DESC);
