export const NAV_ICON_MAP: Record<string, string> = {
  'dashboard': 'pi-chart-bar',
  'governance': 'pi-file-edit',
  'risks': 'pi-exclamation-triangle',
  'compliance': 'pi-check-circle',
  'frameworks': 'pi-sitemap',
  'controls': 'pi-lock',
  'policies': 'pi-file',
  'evidence': 'pi-folder-open',
  'audit': 'pi-search',
  'incidents': 'pi-bell',
  'vendors': 'pi-building',
  'bcp': 'pi-sync',
  'registry': 'pi-database',
  'ai-hub': 'pi-microchip-ai',
  'workflows': 'pi-cog',
  'digital-twin': 'pi-clone',
  'red-team': 'pi-shield',
  'profile': 'pi-user',
  'nca-assessment': 'pi-shield',
  'building-columns': 'pi-building',
  'balance-scale': 'pi-sliders-h',
  'exchange-alt': 'pi-sync',
  'regulator-heatmap': 'pi-th-large',
  'framework-mapping': 'pi-share-alt',
  'dpia': 'pi-file-edit',
  'report-center': 'pi-download',
  'exceptions': 'pi-ban',
  'findings': 'pi-flag',
  'assets': 'pi-server',
  'maturity': 'pi-gauge',
  'automation': 'pi-bolt',
  'team': 'pi-users',
  // GRC OS pages
  'ucf-browser': 'pi-book',
  'control-lifecycle': 'pi-replay',
  'evidence-catalog': 'pi-list',
  'connector-health': 'pi-link',
  'exception-manager': 'pi-ban',
  'cadence-calendar': 'pi-calendar',
  'foundation': 'pi-building',
  'team-management': 'pi-users',
  'assessment-templates': 'pi-clipboard',
  'risk-scoring': 'pi-chart-line',
  'report-builder': 'pi-file-export',
  'privacy-ops': 'pi-eye-slash',
  'vendor-risk': 'pi-building',
  'tenant-config': 'pi-sliders-h',
  'tier-management': 'pi-star',
  // Frontend Integration
  'role-profiles': 'pi-id-card',
  'workflow-templates': 'pi-sitemap',
  'admin': 'pi-cog',
  // Gap Closure pages
  'integrations': 'pi-link',
  'remediation': 'pi-wrench',
  'notifications': 'pi-bell',
  'audit-trail': 'pi-history',
  'scoring-policies': 'pi-calculator',
  // Backend API pages
  'activity-feed': 'pi-history',
  'ai-trigger': 'pi-bolt',
  'autonomy': 'pi-android',
  'content-pack': 'pi-box',
  'contract-tests': 'pi-check-square',
  'entity-link': 'pi-link',
  'explainability': 'pi-info-circle',
  'global-search': 'pi-search',
  'ksa-hub': 'pi-globe',
  'mapping': 'pi-sitemap',
  'privacy-budget': 'pi-shield',
  'report-scenario': 'pi-file-export',
  'public-explorer': 'pi-globe',
  'comment': 'pi-comments',
  'sample-reports': 'pi-file',
  'scoring': 'pi-chart-bar',
  'widgets': 'pi-th-large',
  'jobs': 'pi-clock',
  'platform-config': 'pi-cog',
  // Competitive Edge
  'timeline': 'pi-clock',
  'task-board': 'pi-list-check',
  'messaging': 'pi-envelope',
  'action-items': 'pi-check-circle',
  'training-data': 'pi-database',
  'ai-squad': 'pi-users',
  'ai-queue': 'pi-list-check',
  'autonomous-config': 'pi-sliders-h',
  // New API UI pages
  'analytics-dashboard': 'pi-chart-line',
  'connector-manager': 'pi-link',
  'content-manager': 'pi-database',
  'bulk-actions': 'pi-list-check',
  'workflow-ext': 'pi-sitemap',
  'assessments': 'pi-clipboard',
  'policy-code': 'pi-code',
  'risk-metrics': 'pi-chart-bar',
  'vendor-risk-ext': 'pi-truck',
  'autonomous-workflows': 'pi-bolt',
  'report-generator': 'pi-file-export',
  'report-ext': 'pi-file-pdf',
  'copilot': 'pi-comments',
  'activity-stream': 'pi-history',
  'regulation-compiler': 'pi-book',
  'notification-preferences': 'pi-bell',
  'agrc-os': 'pi-microchip-ai',
  // ── Direct icon-name keys (used by ALL_NAV_ITEMS icon field) ──────────
  'calendar': 'pi-calendar',
  'building': 'pi-building',
  'sitemap': 'pi-sitemap',
  'exclamation-triangle': 'pi-exclamation-triangle',
  'truck': 'pi-truck',
  'shield': 'pi-shield',
  'folder-open': 'pi-folder-open',
  'book': 'pi-book',
  'link': 'pi-link',
  'bolt': 'pi-bolt',
  'eye-slash': 'pi-eye-slash',
  'history': 'pi-history',
  'verified': 'pi-verified',
  'globe': 'pi-globe',
  'file-pdf': 'pi-file-pdf',
  'microchip-ai': 'pi-microchip-ai',
  'chart-line': 'pi-chart-line',
  'play-circle': 'pi-play',
  'objects-column': 'pi-objects-column',
  'users': 'pi-users',
  'sliders-h': 'pi-sliders-h',
  'bell': 'pi-bell',
  'bell-slash': 'pi-bell-slash',
  'home': 'pi-home',
  'database': 'pi-database',
  'map-marker': 'pi-map-marker',
  'cog': 'pi-cog',
  'inbox': 'pi-inbox',
  'id-card': 'pi-id-card',
  'envelope': 'pi-envelope',
  'check-square': 'pi-check-square',
  'chart-bar': 'pi-chart-bar',
  'eye': 'pi-eye',
  'star': 'pi-star',
  'briefcase': 'pi-briefcase',
  'file': 'pi-file',
  'file-edit': 'pi-file-edit',
  'list': 'pi-list',
  'check-circle': 'pi-check-circle',
  'dollar': 'pi-dollar',
  'table': 'pi-table',
  'th-large': 'pi-th-large',
  'clipboard': 'pi-clipboard',
  'lock': 'pi-lock',
  'search': 'pi-search',
  'share-alt': 'pi-share-alt',
};

/** Resolve an icon key to its PrimeIcons class. Falls back to pi-<key> for forward compat. */
export function getNavIcon(route: string): string {
  return NAV_ICON_MAP[route] || `pi-${route}`;
}

/** Resolve an optional icon name to a full PrimeIcons class string (e.g. "pi pi-home"). */
export function resolveIconClass(name?: string): string {
  if (!name) return 'pi pi-circle-fill';
  if (name.startsWith('pi ') || name.startsWith('pi-')) {
    return name.startsWith('pi ') ? name : `pi ${name}`;
  }
  const mapped = NAV_ICON_MAP[name];
  return mapped ? `pi ${mapped}` : `pi pi-${name}`;
}
