import type { AgentDef } from '@dos/types';

export const AGRC_AGENTS: AgentDef[] = [
  {
    id: 'A01', name: 'Onboarding Agent', nameAr: 'وكيل الإعداد',
    domain: 'Onboarding', domainAr: 'الإعداد',
    icon: 'pi-home', color: '#6366f1',
    moduleCode: 'foundation',
    routePatterns: ['/integrations/overview', '/onboarding', '/welcome', '/bootstrap', '/connector-hub'],
    delegationScope: 'onboarding',
    quickPrompts: [
      { en: 'Check workspace health', ar: 'فحص صحة مساحة العمل' },
      { en: 'What frameworks should we adopt?', ar: 'ما الأطر التي يجب اعتمادها؟' },
      { en: 'Show onboarding progress', ar: 'عرض تقدم الإعداد' },
    ],
    governance: {
      rolePurpose: 'Guide workspace setup, validate org profile, recommend frameworks',
      allowedInputTypes: ['org_profile', 'sector_code', 'onboarding_answers'],
      allowedOutputTypes: ['recommendation', 'validation_result', 'workspace_config'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'low',
      escalationPolicy: { escalateTo: 'A02', afterMinutes: 30 },
      auditLevel: 'standard',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A02', name: 'Identity Provisioning Agent', nameAr: 'وكيل توفير الهويات',
    domain: 'Identity & RBAC', domainAr: 'الهوية والصلاحيات',
    icon: 'pi-id-card', color: '#8b5cf6',
    moduleCode: 'admin',
    routePatterns: ['/admin/users', '/admin/roles', '/admin/teams', '/admin/overview'],
    delegationScope: 'workspace_setup',
    quickPrompts: [
      { en: 'Show users without MFA', ar: 'عرض المستخدمين بدون مصادقة ثنائية' },
      { en: 'Check role distribution', ar: 'فحص توزيع الأدوار' },
      { en: 'Flag over-privileged accounts', ar: 'تحديد الحسابات ذات الصلاحيات المفرطة' },
    ],
    governance: {
      rolePurpose: 'Manage user provisioning, detect access anomalies, enforce RBAC',
      allowedInputTypes: ['user_profile', 'role_assignment', 'access_review'],
      allowedOutputTypes: ['flag_risk', 'recommendation', 'access_report'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'high',
      escalationPolicy: { escalateTo: 'human', afterMinutes: 15 },
      auditLevel: 'full',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 3,
    },
  },
  {
    id: 'A03', name: 'Framework Mapping Agent', nameAr: 'وكيل رسم الأطر',
    domain: 'Frameworks', domainAr: 'الأطر',
    icon: 'pi-th-large', color: '#3b82f6',
    moduleCode: 'compliance',
    routePatterns: ['/compliance/frameworks', '/compliance/controls', '/ai-governance/overview', '/knowledge/overview'],
    delegationScope: 'control_mapping',
    quickPrompts: [
      { en: 'Show framework coverage gaps', ar: 'عرض فجوات تغطية الأطر' },
      { en: 'Compare NCA-ECC vs SAMA-CSF', ar: 'مقارنة NCA-ECC مع SAMA-CSF' },
      { en: 'List unmapped controls', ar: 'عرض الضوابط غير المربوطة' },
    ],
    governance: {
      rolePurpose: 'Map regulatory frameworks, detect coverage gaps, recommend control mappings',
      allowedInputTypes: ['framework_data', 'control_catalog', 'regulatory_update'],
      allowedOutputTypes: ['gap_analysis', 'mapping_recommendation', 'coverage_report'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'medium',
      escalationPolicy: { escalateTo: 'A04', afterMinutes: 30 },
      auditLevel: 'standard',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A04', name: 'Control Authoring Agent', nameAr: 'وكيل تأليف الضوابط',
    domain: 'Controls', domainAr: 'الضوابط',
    icon: 'pi-check-circle', color: '#10b981',
    moduleCode: 'compliance',
    routePatterns: ['/ai/overview', '/ai-hub', '/compliance/controls'],
    delegationScope: 'control_mapping',
    quickPrompts: [
      { en: 'Draft missing control documentation', ar: 'صياغة توثيق الضوابط المفقودة' },
      { en: 'Show controls needing test procedures', ar: 'عرض الضوابط التي تحتاج إجراءات اختبار' },
      { en: 'Generate implementation guidance', ar: 'إنشاء دليل التنفيذ' },
    ],
    governance: {
      rolePurpose: 'Author control documentation, generate test procedures, monitor control status',
      allowedInputTypes: ['control_data', 'framework_mapping', 'test_results'],
      allowedOutputTypes: ['control_draft', 'test_procedure', 'implementation_guide', 'status_update'],
      memoryScope: ['task', 'working', 'tool'],
      approvalBoundary: 'medium',
      escalationPolicy: { escalateTo: 'A03', afterMinutes: 30 },
      auditLevel: 'full',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A05', name: 'Evidence Collection Agent', nameAr: 'وكيل جمع الأدلة',
    domain: 'Evidence', domainAr: 'الأدلة',
    icon: 'pi-folder-open', color: '#14b8a6',
    moduleCode: 'evidence',
    routePatterns: ['/evidence/overview', '/evidence'],
    delegationScope: 'evidence_upload',
    quickPrompts: [
      { en: 'Show expired evidence items', ar: 'عرض الأدلة المنتهية' },
      { en: 'Which controls lack evidence?', ar: 'ما الضوابط التي تفتقر إلى أدلة؟' },
      { en: 'Check evidence freshness', ar: 'فحص حداثة الأدلة' },
    ],
    governance: {
      rolePurpose: 'Collect evidence, check freshness, detect gaps in evidence coverage',
      allowedInputTypes: ['evidence_schedule', 'control_mapping', 'evidence_artifact'],
      allowedOutputTypes: ['evidence_request', 'gap_report', 'freshness_alert'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'low',
      escalationPolicy: { escalateTo: 'A06', afterMinutes: 60 },
      auditLevel: 'standard',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A06', name: 'Gap Remediation Agent', nameAr: 'وكيل معالجة الثغرات',
    domain: 'Roadmaps', domainAr: 'خرائط الطريق',
    icon: 'pi-map', color: '#ef4444',
    moduleCode: 'remediation',
    routePatterns: ['/compliance/overview', '/incidents/overview', '/workflow/overview', '/compliance', '/incidents'],
    delegationScope: 'assessment',
    quickPrompts: [
      { en: 'Show overdue remediations', ar: 'عرض المعالجات المتأخرة' },
      { en: 'Analyze open compliance gaps', ar: 'تحليل ثغرات الامتثال المفتوحة' },
      { en: 'Generate remediation roadmap', ar: 'إنشاء خريطة طريق المعالجة' },
    ],
    governance: {
      rolePurpose: 'Analyze compliance gaps, generate remediation roadmaps, track remediation progress',
      allowedInputTypes: ['gap_analysis', 'compliance_assessment', 'remediation_plan'],
      allowedOutputTypes: ['remediation_roadmap', 'task_assignment', 'progress_report'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'medium',
      escalationPolicy: { escalateTo: 'A08', afterMinutes: 30 },
      auditLevel: 'standard',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A07', name: 'Risk Register Agent', nameAr: 'وكيل سجل المخاطر',
    domain: 'Risk Scoring', domainAr: 'تقييم المخاطر',
    icon: 'pi-exclamation-triangle', color: '#06b6d4',
    moduleCode: 'risk',
    routePatterns: ['/risk', '/risk/overview', '/risk/register', '/risk/heatmap', '/risk/treatments', '/risk/kris', '/risk/acceptance', '/risk/appetite', '/risk/scoring', '/risk/metrics', '/risk/assessments'],
    delegationScope: 'risk_seeding',
    quickPrompts: [
      { en: 'Show top risks by score', ar: 'عرض أعلى المخاطر حسب الدرجة' },
      { en: 'Score unscored risks', ar: 'تقييم المخاطر غير المسجلة' },
      { en: 'Check risk appetite breaches', ar: 'فحص تجاوزات شهية المخاطر' },
      { en: 'Generate risk heatmap', ar: 'إنشاء خريطة حرارية للمخاطر' },
    ],
    governance: {
      rolePurpose: 'Score risks, detect appetite breaches, manage risk register, generate heatmaps',
      allowedInputTypes: ['risk_data', 'risk_assessment', 'appetite_threshold'],
      allowedOutputTypes: ['risk_score', 'appetite_breach_alert', 'heatmap', 'flag_risk'],
      memoryScope: ['task', 'working', 'tool'],
      approvalBoundary: 'high',
      escalationPolicy: { escalateTo: 'human', afterMinutes: 15 },
      auditLevel: 'full',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A08', name: 'Policy Lifecycle Agent', nameAr: 'وكيل دورة حياة السياسات',
    domain: 'Governance', domainAr: 'الحوكمة',
    icon: 'pi-book', color: '#f97316',
    moduleCode: 'governance',
    routePatterns: ['/governance/overview', '/governance/policies', '/governance/committees', '/governance/charters', '/governance/delegations', '/workflow/overview'],
    delegationScope: 'policy_drafting',
    quickPrompts: [
      { en: 'Show policies overdue for review', ar: 'عرض السياسات المتأخرة للمراجعة' },
      { en: 'List pending policy approvals', ar: 'عرض الموافقات المعلقة' },
      { en: 'Check policy expiry dates', ar: 'فحص تواريخ انتهاء السياسات' },
    ],
    governance: {
      rolePurpose: 'Manage policy lifecycle, draft policies, track review cycles, enforce governance',
      allowedInputTypes: ['policy_data', 'governance_framework', 'approval_status'],
      allowedOutputTypes: ['policy_draft', 'review_reminder', 'approval_request', 'expiry_alert'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'high',
      escalationPolicy: { escalateTo: 'human', afterMinutes: 20 },
      auditLevel: 'full',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 3,
    },
  },
  {
    id: 'A09', name: 'Third-Party Risk Agent', nameAr: 'وكيل مخاطر الأطراف الثالثة',
    domain: 'Third-Party', domainAr: 'الأطراف الثالثة',
    icon: 'pi-truck', color: '#a855f7',
    moduleCode: 'vendor',
    routePatterns: ['/vendor-risk/overview', '/vendor-risk/vendors', '/vendor-risk/assessments', '/vendor-risk/contracts'],
    delegationScope: 'assessment',
    quickPrompts: [
      { en: 'Show high-risk vendors', ar: 'عرض الموردين عاليي الخطورة' },
      { en: 'Vendors due for assessment', ar: 'الموردين المستحقين للتقييم' },
      { en: 'Check vendor SLA compliance', ar: 'فحص امتثال الموردين لاتفاقيات الخدمة' },
    ],
    governance: {
      rolePurpose: 'Assess vendor risk, monitor SLA compliance, propagate vendor findings',
      allowedInputTypes: ['vendor_profile', 'questionnaire_response', 'sla_data'],
      allowedOutputTypes: ['risk_assessment', 'sla_alert', 'vendor_finding', 'propagation_action'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'medium',
      escalationPolicy: { escalateTo: 'A07', afterMinutes: 30 },
      auditLevel: 'standard',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A10', name: 'Audit Reporting Agent', nameAr: 'وكيل التقارير التدقيقية',
    domain: 'Audit Reports', domainAr: 'تقارير التدقيق',
    icon: 'pi-file-pdf', color: '#64748b',
    moduleCode: 'audit',
    routePatterns: ['/audit/overview', '/audit/findings', '/audit/engagements', '/reports/overview', '/analytics/overview'],
    delegationScope: 'assessment',
    quickPrompts: [
      { en: 'Show open audit findings', ar: 'عرض نتائج التدقيق المفتوحة' },
      { en: 'Check audit readiness score', ar: 'فحص درجة جاهزية التدقيق' },
      { en: 'Generate compliance summary', ar: 'إنشاء ملخص الامتثال' },
    ],
    governance: {
      rolePurpose: 'Track audit findings, assess readiness, generate compliance and audit reports',
      allowedInputTypes: ['audit_data', 'finding_data', 'compliance_status'],
      allowedOutputTypes: ['audit_report', 'readiness_score', 'finding_summary', 'compliance_summary'],
      memoryScope: ['task', 'working', 'tool'],
      approvalBoundary: 'medium',
      escalationPolicy: { escalateTo: 'human', afterMinutes: 30 },
      auditLevel: 'full',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A11', name: 'BCP Continuity Agent', nameAr: 'وكيل استمرارية الأعمال',
    domain: 'Business Continuity', domainAr: 'استمرارية الأعمال',
    icon: 'pi-shield', color: '#059669',
    moduleCode: 'bcp',
    routePatterns: ['/bcp', '/bcp/overview', '/bcp/plans', '/bcp/bia', '/bcp/exercises', '/bcp/crisis-comm', '/bcp/recovery', '/bcp/activation', '/bcp/dependencies', '/bcp/maturity'],
    delegationScope: 'assessment',
    quickPrompts: [
      { en: 'Show BCP readiness score', ar: 'عرض درجة جاهزية استمرارية الأعمال' },
      { en: 'Check overdue exercises', ar: 'فحص التمارين المتأخرة' },
      { en: 'Detect single points of failure', ar: 'كشف نقاط الفشل الأحادية' },
      { en: 'Show RTO/RPO drift', ar: 'عرض انحراف RTO/RPO' },
    ],
    governance: {
      rolePurpose: 'Monitor BCP readiness, detect failures, track exercises, assess continuity',
      allowedInputTypes: ['bcp_plan', 'bia_data', 'exercise_result', 'dependency_map'],
      allowedOutputTypes: ['readiness_score', 'exercise_reminder', 'failure_alert', 'drift_report'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'low',
      escalationPolicy: { escalateTo: 'A08', afterMinutes: 60 },
      auditLevel: 'minimal',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A12', name: 'Security Awareness & Training Agent', nameAr: 'وكيل التوعية والتدريب الأمني',
    domain: 'Training & Awareness', domainAr: 'التدريب والتوعية',
    icon: 'pi-graduation-cap', color: '#d946ef', moduleCode: 'training',
    routePatterns: ['/training-awareness', '/training-awareness/programs', '/training-awareness/campaigns', '/training-awareness/completion', '/training-awareness/gaps'],
    delegationScope: 'assessment',
    quickPrompts: [
      { en: 'Show overdue training assignments', ar: 'عرض تعيينات التدريب المتأخرة' },
      { en: 'Check training completion rate', ar: 'فحص معدل إتمام التدريب' },
      { en: 'Identify training gaps', ar: 'تحديد فجوات التدريب' },
      { en: 'Recommend training programs', ar: 'اقتراح برامج تدريبية' },
    ],
    governance: {
      rolePurpose: 'Track training compliance, identify skill gaps, recommend programs, send reminders',
      allowedInputTypes: ['training_data', 'completion_record', 'gap_analysis'],
      allowedOutputTypes: ['training_recommendation', 'completion_report', 'gap_alert', 'reminder'],
      memoryScope: ['task', 'working'],
      approvalBoundary: 'low',
      escalationPolicy: { escalateTo: 'A08', afterMinutes: 60 },
      auditLevel: 'minimal',
      tenantConstraints: 'single_tenant_only',
      maxActionsPerCycle: 5,
    },
  },
  {
    id: 'A13', name: 'Landing Copilot Agent', nameAr: 'وكيل المساعد في الصفحة الرئيسية',
    domain: 'Public Copilot', domainAr: 'المساعد العام',
    icon: 'pi-comments', color: '#0ea5e9', moduleCode: 'landing',
    routePatterns: ['/', '/landing', '/copilot/public-chat'],
    delegationScope: 'public_qna',
    quickPrompts: [
      { en: 'What is Shahin-AI?', ar: 'ما هو شاهين الذكي؟' },
      { en: 'How do you handle GRC for banks?', ar: 'كيف تتعاملون مع الحوكمة للبنوك؟' },
      { en: 'Show me a sample compliance dashboard', ar: 'أظهر لي لوحة امتثال نموذجية' },
      { en: 'Book a demo', ar: 'احجز عرضاً تجريبياً' },
    ],
    governance: {
      rolePurpose: 'Anonymous public-facing Q&A on the marketing landing page; guides visitors to product features and books demos. No tenant context, no write actions, no PII access.',
      allowedInputTypes: ['public_question', 'visitor_intent'],
      allowedOutputTypes: ['answer', 'doc_link', 'demo_cta'],
      memoryScope: ['task'],
      approvalBoundary: 'low',
      escalationPolicy: { escalateTo: 'A01', afterMinutes: 0 },
      auditLevel: 'minimal',
      tenantConstraints: 'public_anonymous',
      maxActionsPerCycle: 1,
    },
  },
];
