import type { JobDef } from '@dos/contracts';

export const AGRC_JOBS: JobDef[] = [
  { name: 'evidence-expiry-check', cronExpression: '0 0 * * *', description: 'Check for expiring evidence items — daily at midnight' },
  { name: 'kpi-aggregation', cronExpression: '0 1 * * *', description: 'KPI aggregation across tenants — daily at 1 AM' },
  { name: 'deadline-notification-check', cronExpression: '0 6 * * *', description: 'Check for approaching deadlines — daily at 6 AM' },
  { name: 'report-schedule-execution', cronExpression: '* * * * *', description: 'Evaluate and execute scheduled reports — every minute' },
  { name: 'autonomous-step-processor', cronExpression: '*/5 * * * *', description: 'Process autonomous workflow steps — every 5 minutes' },
  { name: 'break-glass-expiry', cronExpression: '*/5 * * * *', description: 'Expire break-glass entries — every 5 minutes' },
  { name: 'escalation-check', cronExpression: '*/30 * * * *', description: 'Check approval escalations — every 30 minutes' },
  { name: 'connector-health-check', cronExpression: '*/15 * * * *', description: 'Connector health monitoring — every 15 minutes' },
  { name: 'ccm-worker', cronExpression: '*/10 * * * *', description: 'Continuous Control Monitoring cycle — every 10 minutes' },
  { name: 'regulatory-delta-scanner', cronExpression: '0 */12 * * *', description: 'Regulatory delta scanning — every 12 hours' },
  { name: 'agrc-os-orchestrator', cronExpression: '*/15 * * * *', description: 'AGRC-OS autonomous orchestration cycle — every 15 minutes' },
  { name: 'review-cycle-engine', cronExpression: '0 2 * * *', description: 'Review cycle engine — daily at 2 AM' },
  { name: 'training-overdue-check', cronExpression: '0 3 * * *', description: 'Check overdue training assignments — daily at 3 AM' },
  { name: 'training-expiring-certs', cronExpression: '0 4 * * *', description: 'Check expiring certifications — daily at 4 AM' },
  { name: 'agrc-metrics-snapshot', cronExpression: '0 */6 * * *', description: 'AGRC metrics snapshot — every 6 hours' },
  { name: 'agrc-data-retention', cronExpression: '0 3 * * *', description: 'AGRC data retention cleanup — daily at 3 AM' },
  { name: 'autonomous-grc-engine', cronExpression: '*/30 * * * *', description: 'Autonomous GRC engine — every 30 minutes' },
  { name: 'agrc-os-integration-cycle', cronExpression: '*/10 * * * *', description: 'AGRC-OS integration cycle — every 10 minutes' },
  { name: 'agrc-dlq-retry', cronExpression: '*/30 * * * *', description: 'Dead letter queue retry — every 30 minutes' },
  { name: 'policy-review-check', cronExpression: '0 7 * * *', description: 'Policy review date check — daily at 7 AM' },
  { name: 'vendor-reassessment-check', cronExpression: '0 8 * * *', description: 'Vendor reassessment check — daily at 8 AM' },
  { name: 'vendor-sla-breach-check', cronExpression: '0 * * * *', description: 'Vendor SLA metrics monitoring and breach escalation — hourly' },
  { name: 'compliance-overdue-check', cronExpression: '0 5 * * *', description: 'Compliance overdue obligations/assessments check — daily at 5 AM' },
  { name: 'compliance-reassessment-trigger', cronExpression: '0 9 * * 1', description: 'Compliance periodic reassessment trigger — weekly Monday 9 AM' },
  { name: 'compliance-gap-stale-check', cronExpression: '0 6 * * *', description: 'Compliance stale gap detection — daily at 6 AM' },
  { name: 'compliance-attestation-reminder', cronExpression: '0 7 * * *', description: 'Compliance attestation due date reminder — daily at 7 AM' },
  { name: 'delegation-expiry-warning', cronExpression: '0 3 * * *', description: 'Foundation delegation expiry warning — daily at 3 AM' },
  { name: 'delegation-auto-expire', cronExpression: '0 4 * * *', description: 'Foundation delegation auto-expire — daily at 4 AM' },
  { name: 'compliance-obligation-deadline-check', cronExpression: '0 6 * * *', description: 'Compliance obligation deadline check — daily at 6 AM' },
  { name: 'compliance-scoring-recalc', cronExpression: '0 2 * * *', description: 'Compliance scoring recalculation — daily at 2 AM' },
  { name: 'compliance-assessment-sla-check', cronExpression: '0 7 * * *', description: 'Compliance assessment SLA check — daily at 7 AM' },
  { name: 'onboarding-cleanup', cronExpression: '0 */6 * * *', description: 'Onboarding stale session cleanup — every 6 hours' },
  { name: 'onboarding-orphaned-job-check', cronExpression: '0 5 * * *', description: 'Onboarding orphaned provisioning job check — daily at 5 AM' },
];
