-- dos:extracted-from: ops/migrations/20260419_0002_p95_notifications_schema_align.sql
-- dos:supersedes-checksum: 2980f9694b96666b7b42270508a080d1d67481207e2a39fc8484d93f6dddc2f5
-- dos:owning-module: workflow
-- dos:tables: workflow_scheduled_jobs
-- dos:statement-count: 2
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
-- ── workflow-service cron executor: dos.workflow_scheduled_jobs ──
-- Same class of drift as above: the cron-executor
-- (services/workflow-service/src/domain/cron-executor.ts:47) polls
-- `dos.workflow_scheduled_jobs` every minute to fan out scheduled
-- workflow triggers across tenants, but the platform-scope
-- aggregation table was never created. Creating it as an empty
-- canonical shape stops the `[cron] Check cycle failed` error from
-- firing 20+ times per shift.
CREATE TABLE IF NOT EXISTS dos.workflow_scheduled_jobs (
  job_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         TEXT NOT NULL,
  name              TEXT NOT NULL,
  cron_expression   TEXT NOT NULL,
  job_type          TEXT NOT NULL,
  payload           JSONB DEFAULT '{}'::jsonb,
  is_active         BOOLEAN DEFAULT TRUE,
  created_by        TEXT,
  last_triggered_at TIMESTAMPTZ,
  last_triggered_by TEXT,
  trigger_count     INTEGER DEFAULT 0,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wsj_active_tenant
  ON dos.workflow_scheduled_jobs(tenant_id, is_active)
  WHERE is_active = TRUE;
