#!/usr/bin/env node
/**
 * pnpm ui-registry:import — Phase F seed importer.
 *
 * Reads every active row in dos.dynamic_ui_routes (parsed from
 * platform/dos/migrations/public/*.sql), maps each component_key to a
 * canonical 13-archetype template via lib/archetype-map.mjs, and emits a
 * single forward-only SQL migration:
 *
 *   platform/dos/migrations/public/<TS>_phase_f_ui_route_template_binding_seed.sql
 *
 * The migration is idempotent (ON CONFLICT (route) DO UPDATE) so re-running
 * the importer after route additions converges. Routes whose component_key
 * does not resolve to an archetype are listed in the file header as TODOs;
 * they are intentionally NOT inserted (they keep the default component-map
 * resolution).
 *
 * Flags:
 *   --dry        Print the SQL to stdout without writing.
 *   --stamp=…    Override migration filename timestamp (for tests).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadActiveRoutes, loadExistingBindings } from './lib/parse-routes.mjs';
import { mapComponentKeyToArchetype } from './lib/archetype-map.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const MIG_DIR = join(REPO, 'platform/dos/migrations/public');
const args = new Set(process.argv.slice(2));
const dry = args.has('--dry');
const stampArg = [...args].find(a => a.startsWith('--stamp='));
const stamp = stampArg
  ? stampArg.split('=')[1]
  : new Date().toISOString().replace(/[-:T]/g, '').slice(0, 12);

if (!existsSync(MIG_DIR)) { console.error('[ui-registry:import] no migrations dir'); process.exit(2); }
const routes = loadActiveRoutes(MIG_DIR);
const existing = loadExistingBindings(MIG_DIR);

const rows = [];
const skipped = [];
for (const [route, ck] of routes) {
  const map = mapComponentKeyToArchetype(ck, route);
  if (!map) { skipped.push({ route, component_key: ck }); continue; }
  rows.push({ route, component_key: ck, ...map });
}

const novel = rows.filter(r => {
  const e = existing.get(r.route);
  return !e || e.archetype !== r.archetype || e.template_export !== r.template_export;
});

const header = [
  '-- Auto-generated by `pnpm ui-registry:import`. Do not edit by hand;',
  '-- re-run the importer after dynamic_ui_routes changes. Idempotent.',
  `-- Active routes scanned : ${routes.size}`,
  `-- Bindings emitted      : ${rows.length}`,
  `-- Net new/changed rows  : ${novel.length}`,
  `-- Skipped (no archetype): ${skipped.length}`,
  ...skipped.slice(0, 30).map(s => `--   ✗ ${s.route} ← ${s.component_key}`),
  skipped.length > 30 ? `--   … (${skipped.length - 30} more)` : '',
].filter(Boolean).join('\n');

const values = rows
  .sort((a, b) => a.route.localeCompare(b.route))
  .map(r => `  ('${r.route.replace(/'/g, "''")}', '${r.archetype}', '${r.template_export}', '{}'::jsonb)`)
  .join(',\n');

const sql = `${header}

BEGIN;

INSERT INTO dos.ui_route_template_binding (route, archetype, template_export, props) VALUES
${values}
ON CONFLICT (route) DO UPDATE
  SET archetype = EXCLUDED.archetype,
      template_export = EXCLUDED.template_export,
      props = COALESCE(dos.ui_route_template_binding.props, '{}'::jsonb) || EXCLUDED.props;

COMMIT;
`;

if (dry) {
  process.stdout.write(sql);
  console.error(`[ui-registry:import] dry — ${rows.length} bindings, ${novel.length} novel, ${skipped.length} skipped`);
  process.exit(0);
}

const file = join(MIG_DIR, `${stamp}_phase_f_ui_route_template_binding_seed.sql`);
writeFileSync(file, sql, 'utf8');
console.log(`[ui-registry:import] wrote ${file}`);
console.log(`  bindings=${rows.length} novel=${novel.length} skipped=${skipped.length}`);
