-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=compliance scope=public function=maturity
-- ledger: dos.schema_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/compliance/db/public/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (1):
--   * maturity_assessments
--
-- Source migrations (immutable, 1):
--   * modules/compliance/db/public/migrations/001_qiyas_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dos.maturity_assessments (
  assessment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id VARCHAR(16) NOT NULL,
  title TEXT NOT NULL,
  framework VARCHAR(100),
  overall_score NUMERIC(5,2),
  status VARCHAR(50) NOT NULL DEFAULT 'in_progress',
  dimensions JSONB DEFAULT '{}',
  created_by VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_maturity_tenant ON dos.maturity_assessments (tenant_id);
