import { WidgetManifest } from '../../core/models/widget-manifest.model';

export const AUDIT_WIDGETS: WidgetManifest[] = [
  {
    id: 'audit.readiness',
    key: 'audit_readiness',
    title: 'Audit Readiness',
    titleAr: 'جاهزية التدقيق',
    category: 'audit',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/audit-readiness.widget').then(m => m.AuditReadinessWidget),
    icon: '🔍',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'compliance_officer', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'audit.pack_status',
    key: 'audit_pack_status',
    title: 'Audit Pack Status',
    titleAr: 'حالة حزمة التدقيق',
    category: 'audit',
    engine: 'angular',
    component: () => import('../../../components/compliance-audit/audit-pack-status.widget').then(m => m.AuditPackStatusWidget),
    icon: '📦',
    defaultSize: { cols: 6, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'audit.readiness_gauge',
    key: 'audit_readiness_gauge',
    title: 'Audit Readiness Gauge',
    titleAr: 'مقياس جاهزية التدقيق',
    category: 'audit',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/gauge/audit-readiness-gauge.component').then(m => m.AuditReadinessGaugeComponent),
    icon: '🎯',
    defaultSize: { cols: 3, rows: 1 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'audit.findings_heatmap',
    key: 'audit_findings_heatmap',
    title: 'Audit Findings Heatmap',
    titleAr: 'حرارية نتائج التدقيق',
    category: 'audit',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/heatmap/audit-findings-heatmap.component').then(m => m.AuditFindingsHeatmapComponent),
    icon: '🗺️',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'audit.findings_funnel',
    key: 'findings_funnel',
    title: 'Findings Funnel',
    titleAr: 'قمع النتائج',
    category: 'audit',
    engine: 'echarts',
    component: () => import('../../../chart-infra/echart-components/funnel/findings-funnel.component').then(m => m.FindingsFunnelComponent),
    icon: '🔻',
    defaultSize: { cols: 6, rows: 2 },
    roles: ['owner', 'admin', 'auditor'],
    schemaVersion: 1,
  },
  {
    id: 'audit.top_breached_kris',
    key: 'top-breached-kris',
    title: 'Top Breached KRIs',
    titleAr: 'أعلى مؤشرات المخاطر المخترقة',
    category: 'audit',
    engine: 'angular',
    component: () => import('../../../components/executive/top-breached-kris.widget').then(m => m.TopBreachedKrisWidgetComponent),
    icon: '⚠️',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
  {
    id: 'audit.policy_review_debt',
    key: 'policy-review-debt',
    title: 'Policy Review Debt',
    titleAr: 'ديون مراجعة السياسات',
    category: 'audit',
    engine: 'angular',
    component: () => import('../../../components/evidence/policy-review-debt.widget').then(m => m.PolicyReviewDebtWidgetComponent),
    icon: '📋',
    defaultSize: { cols: 6, rows: 1 },
    schemaVersion: 1,
  },
];
