import { RECORDS_MANIFEST } from '../records.module';
export { RECORDS_MANIFEST };
export declare const RECORDS_MANIFEST_META: {
    readonly code: string;
    readonly version: string;
    readonly tier: string;
    readonly category: string;
    readonly routeBase: string;
    readonly eventNamespace: string;
    readonly tablePrefix: string;
    readonly ownedTables: string[];
    readonly publishedEvents: string[];
    readonly consumedEvents: string[];
    readonly hardDeps: string[];
    readonly softDeps: string[];
    readonly provisioningOrder: number | undefined;
    readonly lifecycleParticipation: true;
    readonly uiSurfaces: readonly ["records-hub", "record-detail", "retention-policies", "legal-holds", "classification-views", "disposal-management", "diagnostics"];
    readonly adminSurfaces: string[] | undefined;
    readonly healthSignals: readonly ["schema_exists", "tables_exist", "overdue_disposals", "active_holds", "retention_policy_coverage", "unclassified_records"];
};
