-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=incident scope=tenant function=every
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/incident/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (3):
--   * every
--   * findings
--   * incidents
--
-- Source migrations (immutable, 1):
--   * modules/incident/db/tenant/migrations/099_extracted_from_099_bootstrap_tenant_domain_tables.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE statements. Every subsequent migration that
--   references them therefore fails validate:migrations on a fresh tenant
--   schema.
--
--   The canonical shapes in two different worlds disagree on PK column
--   name:
--     - tenant chain 101-123 FKs to incidents(incident_id), risks(risk_id),
--       teams(team_id), vulnerabilities(vulnerability_id),
--       findings(finding_id), ai_model_registry(model_version_id).
--     - modules/* FKs to incidents(id), risks(id), ai_model_registry(id).
--
--   Providing both columns as UNIQUE on each bootstrap table lets either
--   FK target resolve. PK stays `id` (matches the module canonical shape);

CREATE TABLE IF NOT EXISTS __TENANT_SCHEMA__.incidents (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id   UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  tenant_id     UUID,
  title         TEXT,
  description   TEXT,
  severity      VARCHAR(30),
  status        VARCHAR(30) DEFAULT 'open',
  reported_by   VARCHAR(64),
  assigned_to   VARCHAR(64),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incidents_tenant_bootstrap ON __TENANT_SCHEMA__.incidents (tenant_id);

CREATE TABLE IF NOT EXISTS findings (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  finding_id    UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  tenant_id     UUID,
  title         TEXT,
  severity      VARCHAR(30),
  status        VARCHAR(30) DEFAULT 'open',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_findings_tenant_bootstrap ON findings (tenant_id);
