-- ═══════════════════════════════════════════════════════════════════
-- CANONICAL SQL — module=incident scope=tenant function=updates
-- ledger: dos.tenant_migrations
-- Generated by ops/scripts/generate-canonical-sql.mjs from immutable history.
-- This file is the consolidated CREATE TABLE/INDEX/VIEW shape for the function.
-- Future schema changes MUST be applied as numbered delta migrations under
-- modules/incident/db/tenant/migrations/ and back-merged here when applied. Do not edit by hand.
--
-- Tables covered (3):
--   * incident_response_actions
--   * incident_updates
--   * vulnerability_findings_map
--
-- Source migrations (immutable, 2):
--   * modules/incident/db/tenant/migrations/101_incidents_ops_additions.sql
--   * modules/incident/db/tenant/migrations/130_incidents_unique_for_fk.sql
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS incident_updates (
  update_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id        UUID NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
  update_type        VARCHAR(50) NOT NULL,
  update_text        TEXT,
  updated_by         VARCHAR(64),
  status_change_from VARCHAR(30),
  status_change_to   VARCHAR(30),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incident_updates_incident ON incident_updates(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_updates_type     ON incident_updates(update_type)  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_updates_by       ON incident_updates(updated_by)   WHERE updated_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_incident_updates_created  ON incident_updates(created_at DESC);

CREATE TABLE IF NOT EXISTS incident_response_actions (
  action_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id  UUID NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
  action_type  VARCHAR(50) NOT NULL,
  title        VARCHAR(500) NOT NULL,
  description  TEXT,
  assigned_to  VARCHAR(64),
  due_date     DATE,
  status       VARCHAR(30) NOT NULL DEFAULT 'pending',
  priority     VARCHAR(20),
  outcome      TEXT,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incident_actions_incident  ON incident_response_actions(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_actions_status    ON incident_response_actions(status)     WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_assigned  ON incident_response_actions(assigned_to) WHERE assigned_to IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_due       ON incident_response_actions(due_date)    WHERE due_date IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_priority  ON incident_response_actions(priority)    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS vulnerability_findings_map (
  map_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vulnerability_id UUID NOT NULL REFERENCES vulnerabilities(vulnerability_id) ON DELETE CASCADE,
  finding_id       UUID NOT NULL REFERENCES findings(finding_id) ON DELETE CASCADE,
  mapping_type     VARCHAR(30),
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_vuln_findings_vuln    ON vulnerability_findings_map(vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vuln_findings_finding ON vulnerability_findings_map(finding_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vuln_finding_pair
  ON vulnerability_findings_map(vulnerability_id, finding_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS incident_updates (
  update_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id        UUID NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
  update_type        VARCHAR(50) NOT NULL,
  update_text        TEXT,
  updated_by         VARCHAR(64),
  status_change_from VARCHAR(30),
  status_change_to   VARCHAR(30),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incident_updates_incident ON incident_updates(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_updates_type     ON incident_updates(update_type)  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_updates_by       ON incident_updates(updated_by)   WHERE updated_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_incident_updates_created  ON incident_updates(created_at DESC);

CREATE TABLE IF NOT EXISTS incident_response_actions (
  action_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id  UUID NOT NULL REFERENCES incidents(incident_id) ON DELETE CASCADE,
  action_type  VARCHAR(50) NOT NULL,
  title        VARCHAR(500) NOT NULL,
  description  TEXT,
  assigned_to  VARCHAR(64),
  due_date     DATE,
  status       VARCHAR(30) NOT NULL DEFAULT 'pending',
  priority     VARCHAR(20),
  outcome      TEXT,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_incident_actions_incident  ON incident_response_actions(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_actions_status    ON incident_response_actions(status)     WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_assigned  ON incident_response_actions(assigned_to) WHERE assigned_to IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_due       ON incident_response_actions(due_date)    WHERE due_date IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_incident_actions_priority  ON incident_response_actions(priority)    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS vulnerability_findings_map (
        map_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        vulnerability_id UUID NOT NULL REFERENCES vulnerabilities(vulnerability_id) ON DELETE CASCADE,
        finding_id       UUID NOT NULL REFERENCES findings(finding_id) ON DELETE CASCADE,
        mapping_type     VARCHAR(30),
        notes            TEXT,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at       TIMESTAMPTZ
      );

CREATE INDEX IF NOT EXISTS idx_vuln_findings_vuln    ON vulnerability_findings_map(vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vuln_findings_finding ON vulnerability_findings_map(finding_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vuln_finding_pair
        ON vulnerability_findings_map(vulnerability_id, finding_id) WHERE deleted_at IS NULL;
