import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const EVIDENCE_ERROR_CODES = {
  RUN_ALL_NOT_FOUND: { code: 'EVIDENCE.RUN_ALL_NOT_FOUND', httpStatus: 404, messageEn: 'Run All not found', messageAr: 'Run All غير موجود' },
  RUN_ALL_ALREADY_EXISTS: { code: 'EVIDENCE.RUN_ALL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Run All already exists', messageAr: 'Run All موجود بالفعل' },
  RUN_ALL_VALIDATION_FAILED: { code: 'EVIDENCE.RUN_ALL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Run All validation failed', messageAr: 'فشل التحقق من Run All' },
  EXPIRING_NOT_FOUND: { code: 'EVIDENCE.EXPIRING_NOT_FOUND', httpStatus: 404, messageEn: 'Expiring not found', messageAr: 'Expiring غير موجود' },
  EXPIRING_ALREADY_EXISTS: { code: 'EVIDENCE.EXPIRING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Expiring already exists', messageAr: 'Expiring موجود بالفعل' },
  EXPIRING_VALIDATION_FAILED: { code: 'EVIDENCE.EXPIRING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Expiring validation failed', messageAr: 'فشل التحقق من Expiring' },
  STALE_NOT_FOUND: { code: 'EVIDENCE.STALE_NOT_FOUND', httpStatus: 404, messageEn: 'Stale not found', messageAr: 'Stale غير موجود' },
  STALE_ALREADY_EXISTS: { code: 'EVIDENCE.STALE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Stale already exists', messageAr: 'Stale موجود بالفعل' },
  STALE_VALIDATION_FAILED: { code: 'EVIDENCE.STALE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Stale validation failed', messageAr: 'فشل التحقق من Stale' },
  BULK_STALE_NOT_FOUND: { code: 'EVIDENCE.BULK_STALE_NOT_FOUND', httpStatus: 404, messageEn: 'Bulk Stale not found', messageAr: 'Bulk Stale غير موجود' },
  BULK_STALE_ALREADY_EXISTS: { code: 'EVIDENCE.BULK_STALE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Bulk Stale already exists', messageAr: 'Bulk Stale موجود بالفعل' },
  BULK_STALE_VALIDATION_FAILED: { code: 'EVIDENCE.BULK_STALE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Bulk Stale validation failed', messageAr: 'فشل التحقق من Bulk Stale' },
  BULK_EXTEND_NOT_FOUND: { code: 'EVIDENCE.BULK_EXTEND_NOT_FOUND', httpStatus: 404, messageEn: 'Bulk Extend not found', messageAr: 'Bulk Extend غير موجود' },
  BULK_EXTEND_ALREADY_EXISTS: { code: 'EVIDENCE.BULK_EXTEND_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Bulk Extend already exists', messageAr: 'Bulk Extend موجود بالفعل' },
  BULK_EXTEND_VALIDATION_FAILED: { code: 'EVIDENCE.BULK_EXTEND_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Bulk Extend validation failed', messageAr: 'فشل التحقق من Bulk Extend' },
  BULK_REFRESH_NOT_FOUND: { code: 'EVIDENCE.BULK_REFRESH_NOT_FOUND', httpStatus: 404, messageEn: 'Bulk Refresh not found', messageAr: 'Bulk Refresh غير موجود' },
  BULK_REFRESH_ALREADY_EXISTS: { code: 'EVIDENCE.BULK_REFRESH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Bulk Refresh already exists', messageAr: 'Bulk Refresh موجود بالفعل' },
  BULK_REFRESH_VALIDATION_FAILED: { code: 'EVIDENCE.BULK_REFRESH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Bulk Refresh validation failed', messageAr: 'فشل التحقق من Bulk Refresh' },
  WEBHOOKS_NOT_FOUND: { code: 'EVIDENCE.WEBHOOKS_NOT_FOUND', httpStatus: 404, messageEn: 'Webhooks not found', messageAr: 'Webhooks غير موجود' },
  WEBHOOKS_ALREADY_EXISTS: { code: 'EVIDENCE.WEBHOOKS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Webhooks already exists', messageAr: 'Webhooks موجود بالفعل' },
  WEBHOOKS_VALIDATION_FAILED: { code: 'EVIDENCE.WEBHOOKS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Webhooks validation failed', messageAr: 'فشل التحقق من Webhooks' },
  PIPELINE_WEBHOOKS_NOT_FOUND: { code: 'EVIDENCE.PIPELINE_WEBHOOKS_NOT_FOUND', httpStatus: 404, messageEn: 'Pipeline Webhooks not found', messageAr: 'Pipeline Webhooks غير موجود' },
  PIPELINE_WEBHOOKS_ALREADY_EXISTS: { code: 'EVIDENCE.PIPELINE_WEBHOOKS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Pipeline Webhooks already exists', messageAr: 'Pipeline Webhooks موجود بالفعل' },
  PIPELINE_WEBHOOKS_VALIDATION_FAILED: { code: 'EVIDENCE.PIPELINE_WEBHOOKS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Pipeline Webhooks validation failed', messageAr: 'فشل التحقق من Pipeline Webhooks' },
  BATCH_ANALYZE_NOT_FOUND: { code: 'EVIDENCE.BATCH_ANALYZE_NOT_FOUND', httpStatus: 404, messageEn: 'Batch Analyze not found', messageAr: 'Batch Analyze غير موجود' },
  BATCH_ANALYZE_ALREADY_EXISTS: { code: 'EVIDENCE.BATCH_ANALYZE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Batch Analyze already exists', messageAr: 'Batch Analyze موجود بالفعل' },
  BATCH_ANALYZE_VALIDATION_FAILED: { code: 'EVIDENCE.BATCH_ANALYZE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Batch Analyze validation failed', messageAr: 'فشل التحقق من Batch Analyze' },
  CATALOG_NOT_FOUND: { code: 'EVIDENCE.CATALOG_NOT_FOUND', httpStatus: 404, messageEn: 'Catalog not found', messageAr: 'Catalog غير موجود' },
  CATALOG_ALREADY_EXISTS: { code: 'EVIDENCE.CATALOG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Catalog already exists', messageAr: 'Catalog موجود بالفعل' },
  CATALOG_VALIDATION_FAILED: { code: 'EVIDENCE.CATALOG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Catalog validation failed', messageAr: 'فشل التحقق من Catalog' },
  EVIDENCE_NOT_FOUND: { code: 'EVIDENCE.EVIDENCE_NOT_FOUND', httpStatus: 404, messageEn: 'Evidence not found', messageAr: 'Evidence غير موجود' },
  EVIDENCE_ALREADY_EXISTS: { code: 'EVIDENCE.EVIDENCE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Evidence already exists', messageAr: 'Evidence موجود بالفعل' },
  EVIDENCE_VALIDATION_FAILED: { code: 'EVIDENCE.EVIDENCE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Evidence validation failed', messageAr: 'فشل التحقق من Evidence' },
  CONTROL_NOT_FOUND: { code: 'EVIDENCE.CONTROL_NOT_FOUND', httpStatus: 404, messageEn: 'Control not found', messageAr: 'Control غير موجود' },
  CONTROL_ALREADY_EXISTS: { code: 'EVIDENCE.CONTROL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Control already exists', messageAr: 'Control موجود بالفعل' },
  CONTROL_VALIDATION_FAILED: { code: 'EVIDENCE.CONTROL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Control validation failed', messageAr: 'فشل التحقق من Control' },
  SUGGEST_REUSE_NOT_FOUND: { code: 'EVIDENCE.SUGGEST_REUSE_NOT_FOUND', httpStatus: 404, messageEn: 'Suggest Reuse not found', messageAr: 'Suggest Reuse غير موجود' },
  SUGGEST_REUSE_ALREADY_EXISTS: { code: 'EVIDENCE.SUGGEST_REUSE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Suggest Reuse already exists', messageAr: 'Suggest Reuse موجود بالفعل' },
  SUGGEST_REUSE_VALIDATION_FAILED: { code: 'EVIDENCE.SUGGEST_REUSE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Suggest Reuse validation failed', messageAr: 'فشل التحقق من Suggest Reuse' },
  VERIFY_NOT_FOUND: { code: 'EVIDENCE.VERIFY_NOT_FOUND', httpStatus: 404, messageEn: 'Verify not found', messageAr: 'Verify غير موجود' },
  VERIFY_ALREADY_EXISTS: { code: 'EVIDENCE.VERIFY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Verify already exists', messageAr: 'Verify موجود بالفعل' },
  VERIFY_VALIDATION_FAILED: { code: 'EVIDENCE.VERIFY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Verify validation failed', messageAr: 'فشل التحقق من Verify' },
  COLLECT_NOT_FOUND: { code: 'EVIDENCE.COLLECT_NOT_FOUND', httpStatus: 404, messageEn: 'Collect not found', messageAr: 'Collect غير موجود' },
  COLLECT_ALREADY_EXISTS: { code: 'EVIDENCE.COLLECT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Collect already exists', messageAr: 'Collect موجود بالفعل' },
  COLLECT_VALIDATION_FAILED: { code: 'EVIDENCE.COLLECT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Collect validation failed', messageAr: 'فشل التحقق من Collect' },

  UNAUTHORIZED: { code: 'EVIDENCE.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for evidence operation', messageAr: 'صلاحيات غير كافية لعملية evidence' },
  INVALID_STATE_TRANSITION: { code: 'EVIDENCE.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'EVIDENCE.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'EVIDENCE.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'EVIDENCE.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'EVIDENCE.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type EvidenceErrorCode = keyof typeof EVIDENCE_ERROR_CODES;
