import type { ModuleRouteGroup } from '../core/routing/route-registry.types';

export const qiyasModuleRouteGroup: ModuleRouteGroup = {
  shell: () => import('../core/platform/shell/shell-host.component').then(m => m.ShellHostComponent),
  defaultRedirect: 'assessments',
  children: {
    '': { redirectTo: 'assessments', pathMatch: 'full' },
    create:      { loadComponent: () => import('../shared/components/generic-module-create-dialog.component').then(m => m.GenericModuleCreateDialogComponent), data: { moduleCode: 'qiyas' } },
    reports:     { loadComponent: () => import('../shared/components/generic-module-reports.component').then(m => m.GenericModuleReportsComponent), data: { moduleCode: 'qiyas' } },
    assessments: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-assessments.component').then(m => m.QiyasAssessmentsComponent) },
    'assessments/:id': { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-assessment-detail.component').then(m => m.QiyasAssessmentDetailComponent) },
    models: { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-models.component').then(m => m.QiyasModelsComponent) },
    'models/:id': { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-model-detail.component').then(m => m.QiyasModelDetailComponent) },
    benchmarks: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-benchmarks.component').then(m => m.QiyasBenchmarksComponent) },
    calibration: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-calibration.component').then(m => m.QiyasCalibrationComponent) },
    certification: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-certification.component').then(m => m.QiyasCertificationComponent) },
    'evidence-scoring': { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-evidence-scoring.component').then(m => m.QiyasEvidenceScoringComponent) },
    'maturity-heatmap': { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-maturity-heatmap.component').then(m => m.QiyasMaturityHeatmapComponent) },
    'maturity-trends': { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-maturity-trends.component').then(m => m.QiyasMaturityTrendsComponent) },
    'question-bank': { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-question-bank.component').then(m => m.QiyasQuestionBankComponent) },
    recommendations: { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-recommendations.component').then(m => m.QiyasRecommendationsComponent) },
    respondents: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-respondents.component').then(m => m.QiyasRespondentsComponent) },
    roadmap: { loadComponent: () => import('../features/qiyas/pages/qiyas-maturity/qiyas-roadmap.component').then(m => m.QiyasImprovementRoadmapComponent) },
    scoping: { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-scoping.component').then(m => m.QiyasScopingComponent) },
    'strategy': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-home.component').then(m => m.StrategyHomeComponent) },
    'strategy/objectives': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-objectives.component').then(m => m.StrategyObjectivesComponent) },
    'strategy/objectives/:id': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-objectives.component').then(m => m.StrategyObjectivesComponent) },
    'strategy/kpi-kri': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-kpi-kri.component').then(m => m.StrategyKpiKriComponent) },
    'strategy/risk-appetite': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-risk-appetite.component').then(m => m.StrategyRiskAppetiteComponent) },
    'strategy/scorecards': { loadComponent: () => import('../features/qiyas/pages/qiyas-assessments/qiyas-assessments.component').then(m => m.QiyasAssessmentsComponent) },
    'strategy/roadmap': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-improvement-roadmap.component').then(m => m.StrategyImprovementRoadmapComponent) },
    'strategy/executive-packs': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-executive-packs.component').then(m => m.StrategyExecutivePacksComponent) },
    'strategy/admin': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-admin.component').then(m => m.StrategyAdminComponent) },
    'strategy/themes': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-objectives.component').then(m => m.StrategyObjectivesComponent) },
    'strategy/priorities': { loadComponent: () => import('../features/qiyas/pages/strategy/strategy-objectives.component').then(m => m.StrategyObjectivesComponent) },
    ':id': { loadComponent: () => import('../shared/components/generic-module-detail.component').then(m => m.GenericModuleDetailComponent), data: { moduleCode: 'qiyas' } },
    lifecycle: { loadComponent: () => import('../shared/components/generic-module-lifecycle.component').then(m => m.GenericModuleLifecycleComponent), data: { moduleCode: 'qiyas' } },
  },
};
