-- dos:extracted-from: services/risk-incident-service/migrations/001_risk_incident_tables.sql
-- dos:supersedes-checksum: 1da503501c269fc64a16021904aa868cd309d78cdac1fdce4f616fcf9a15ca04
-- dos:owning-module: risk
-- dos:tables: risks
-- dos:statement-count: 3
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS dos.risks (
  risk_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id VARCHAR(16) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category VARCHAR(100),
  likelihood INTEGER CHECK (likelihood BETWEEN 1 AND 5),
  impact INTEGER CHECK (impact BETWEEN 1 AND 5),
  risk_score INTEGER GENERATED ALWAYS AS (likelihood * impact) STORED,
  status VARCHAR(50) NOT NULL DEFAULT 'open',
  treatment_plan TEXT,
  owner_user_id VARCHAR(64),
  created_by VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_risks_tenant ON dos.risks (tenant_id);

CREATE INDEX IF NOT EXISTS idx_risks_status ON dos.risks (tenant_id, status);
