import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const CONFIG_CENTER_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'config.setting.read', resourceType: 'setting', actionType: 'read', descriptionEn: 'Read config settings', descriptionAr: 'قراءة إعدادات التكوين', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.setting.write', resourceType: 'setting', actionType: 'write', descriptionEn: 'Write config settings', descriptionAr: 'كتابة إعدادات التكوين', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.compare.read', resourceType: 'compare', actionType: 'read', descriptionEn: 'Compare tenant configs', descriptionAr: 'مقارنة إعدادات المستأجرين', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.export.read', resourceType: 'export', actionType: 'read', descriptionEn: 'Export config snapshot', descriptionAr: 'تصدير لقطة الإعدادات', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.import.write', resourceType: 'import', actionType: 'write', descriptionEn: 'Import config snapshot', descriptionAr: 'استيراد لقطة الإعدادات', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.audit.read', resourceType: 'audit', actionType: 'read', descriptionEn: 'Read config audit trail', descriptionAr: 'قراءة سجل تدقيق الإعدادات', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'config.health.read', resourceType: 'health', actionType: 'read', descriptionEn: 'Read config health', descriptionAr: 'قراءة صحة الإعدادات', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const CONFIG_CENTER_ROLES: ModuleRole[] = [
  { roleCode: 'config.platform_admin', archetype: 'executive_owner', nameEn: 'Config Platform Admin', nameAr: 'مدير إعدادات المنصة', descriptionEn: 'Full config management access', descriptionAr: 'وصول كامل لإدارة الإعدادات', isDefault: false, isSystem: false, isGlobal: false, permissions: ['config.setting.read', 'config.setting.write', 'config.compare.read', 'config.export.read', 'config.import.write', 'config.audit.read', 'config.health.read'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'config.tenant_admin', archetype: 'module_lead', nameEn: 'Config Tenant Admin', nameAr: 'مدير إعدادات المستأجر', descriptionEn: 'Tenant-scoped config management', descriptionAr: 'إدارة إعدادات المستأجر', isDefault: false, isSystem: false, isGlobal: false, permissions: ['config.setting.read', 'config.setting.write', 'config.audit.read', 'config.health.read'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'config.viewer', archetype: 'viewer', nameEn: 'Config Viewer', nameAr: 'عارض الإعدادات', descriptionEn: 'Read-only config access', descriptionAr: 'وصول قراءة فقط للإعدادات', isDefault: true, isSystem: false, isGlobal: false, permissions: ['config.setting.read', 'config.audit.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'config.auditor', archetype: 'auditor', nameEn: 'Config Auditor', nameAr: 'مدقق الإعدادات', descriptionEn: 'Read-only config + export + health', descriptionAr: 'قراءة الإعدادات + تصدير + صحة', isDefault: false, isSystem: false, isGlobal: false, permissions: ['config.setting.read', 'config.audit.read', 'config.health.read', 'config.export.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const CONFIG_CENTER_ACTIONS: ModuleAction[] = [
  { actionCode: 'config.setting.read', labelEn: 'Read config setting', labelAr: 'قراءة إعداد', requiredPermissions: ['config.setting.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'config.setting.write', labelEn: 'Write config setting', labelAr: 'كتابة إعداد', requiredPermissions: ['config.setting.write'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'config.compare.read', labelEn: 'Compare configs', labelAr: 'مقارنة الإعدادات', requiredPermissions: ['config.compare.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'config.export.read', labelEn: 'Export config', labelAr: 'تصدير الإعدادات', requiredPermissions: ['config.export.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'config.import.write', labelEn: 'Import config', labelAr: 'استيراد الإعدادات', requiredPermissions: ['config.import.write'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'config.audit.read', labelEn: 'Read audit trail', labelAr: 'قراءة سجل التدقيق', requiredPermissions: ['config.audit.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'config.health.read', labelEn: 'Read health status', labelAr: 'قراءة حالة الصحة', requiredPermissions: ['config.health.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
];
