import type { ModuleErrorCode } from './error-catalog.types';

export const RISK_ERROR_CODES = {
  CALCULATE_NOT_FOUND: { code: 'RISK.CALCULATE_NOT_FOUND', httpStatus: 404, messageEn: 'Calculate not found', messageAr: 'Calculate غير موجود' },
  CALCULATE_ALREADY_EXISTS: { code: 'RISK.CALCULATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Calculate already exists', messageAr: 'Calculate موجود بالفعل' },
  CALCULATE_VALIDATION_FAILED: { code: 'RISK.CALCULATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Calculate validation failed', messageAr: 'فشل التحقق من Calculate' },
  EXPOSURE_NOT_FOUND: { code: 'RISK.EXPOSURE_NOT_FOUND', httpStatus: 404, messageEn: 'Exposure not found', messageAr: 'Exposure غير موجود' },
  EXPOSURE_ALREADY_EXISTS: { code: 'RISK.EXPOSURE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Exposure already exists', messageAr: 'Exposure موجود بالفعل' },
  EXPOSURE_VALIDATION_FAILED: { code: 'RISK.EXPOSURE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Exposure validation failed', messageAr: 'فشل التحقق من Exposure' },
  EXPOSURES_NOT_FOUND: { code: 'RISK.EXPOSURES_NOT_FOUND', httpStatus: 404, messageEn: 'Exposures not found', messageAr: 'Exposures غير موجود' },
  EXPOSURES_ALREADY_EXISTS: { code: 'RISK.EXPOSURES_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Exposures already exists', messageAr: 'Exposures موجود بالفعل' },
  EXPOSURES_VALIDATION_FAILED: { code: 'RISK.EXPOSURES_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Exposures validation failed', messageAr: 'فشل التحقق من Exposures' },
  ESTIMATE_MAGNITUDE_NOT_FOUND: { code: 'RISK.ESTIMATE_MAGNITUDE_NOT_FOUND', httpStatus: 404, messageEn: 'Estimate Magnitude not found', messageAr: 'Estimate Magnitude غير موجود' },
  ESTIMATE_MAGNITUDE_ALREADY_EXISTS: { code: 'RISK.ESTIMATE_MAGNITUDE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Estimate Magnitude already exists', messageAr: 'Estimate Magnitude موجود بالفعل' },
  ESTIMATE_MAGNITUDE_VALIDATION_FAILED: { code: 'RISK.ESTIMATE_MAGNITUDE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Estimate Magnitude validation failed', messageAr: 'فشل التحقق من Estimate Magnitude' },
  CONFIG_NOT_FOUND: { code: 'RISK.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'RISK.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'RISK.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'RISK.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'RISK.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'RISK.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'RISK.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'RISK.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'RISK.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'RISK.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'RISK.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'RISK.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  CRITICAL_RISKS_NOT_FOUND: { code: 'RISK.CRITICAL_RISKS_NOT_FOUND', httpStatus: 404, messageEn: 'Critical Risks not found', messageAr: 'Critical Risks غير موجود' },
  CRITICAL_RISKS_ALREADY_EXISTS: { code: 'RISK.CRITICAL_RISKS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Critical Risks already exists', messageAr: 'Critical Risks موجود بالفعل' },
  CRITICAL_RISKS_VALIDATION_FAILED: { code: 'RISK.CRITICAL_RISKS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Critical Risks validation failed', messageAr: 'فشل التحقق من Critical Risks' },
  REINDEX_NOT_FOUND: { code: 'RISK.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'RISK.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'RISK.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'RISK.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'RISK.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'RISK.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  DIAGNOSTICS_NOT_FOUND: { code: 'RISK.DIAGNOSTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Diagnostics not found', messageAr: 'Diagnostics غير موجود' },
  DIAGNOSTICS_ALREADY_EXISTS: { code: 'RISK.DIAGNOSTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Diagnostics already exists', messageAr: 'Diagnostics موجود بالفعل' },
  DIAGNOSTICS_VALIDATION_FAILED: { code: 'RISK.DIAGNOSTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Diagnostics validation failed', messageAr: 'فشل التحقق من Diagnostics' },
  KPIS_NOT_FOUND: { code: 'RISK.KPIS_NOT_FOUND', httpStatus: 404, messageEn: 'Kpis not found', messageAr: 'Kpis غير موجود' },
  KPIS_ALREADY_EXISTS: { code: 'RISK.KPIS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Kpis already exists', messageAr: 'Kpis موجود بالفعل' },
  KPIS_VALIDATION_FAILED: { code: 'RISK.KPIS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Kpis validation failed', messageAr: 'فشل التحقق من Kpis' },
  TRENDS_NOT_FOUND: { code: 'RISK.TRENDS_NOT_FOUND', httpStatus: 404, messageEn: 'Trends not found', messageAr: 'Trends غير موجود' },
  TRENDS_ALREADY_EXISTS: { code: 'RISK.TRENDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trends already exists', messageAr: 'Trends موجود بالفعل' },
  TRENDS_VALIDATION_FAILED: { code: 'RISK.TRENDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trends validation failed', messageAr: 'فشل التحقق من Trends' },
  SCENARIOS_NOT_FOUND: { code: 'RISK.SCENARIOS_NOT_FOUND', httpStatus: 404, messageEn: 'Scenarios not found', messageAr: 'Scenarios غير موجود' },
  SCENARIOS_ALREADY_EXISTS: { code: 'RISK.SCENARIOS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Scenarios already exists', messageAr: 'Scenarios موجود بالفعل' },
  SCENARIOS_VALIDATION_FAILED: { code: 'RISK.SCENARIOS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Scenarios validation failed', messageAr: 'فشل التحقق من Scenarios' },

  UNAUTHORIZED: { code: 'RISK.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for risk operation', messageAr: 'صلاحيات غير كافية لعملية risk' },
  INVALID_STATE_TRANSITION: { code: 'RISK.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'RISK.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'RISK.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'RISK.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'RISK.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type RiskErrorCode = keyof typeof RISK_ERROR_CODES;
