/**
 * agrc-engine — Lifecycle Registry Registration
 * Auto-generated by scripts/codegen/generate-lifecycle-registrations.ts
 *
 * Registers entity lifecycles with the central LifecycleRegistry (DOS-owned).
 * DAuth evaluateLifecycleTransition() consumes these definitions.
 */

import { registerLifecycleDefinition } from './ports/lifecycle.port';

const RECORD_STATES = [
  'draft',
  'in_review',
  'approved',
  'active',
  'suspended',
  'archived',
] as const;

const RECORD_TRANSITIONS: Record<string, string[]> = {
  draft           : ['in_review'],
  in_review       : ['approved', 'draft'],
  approved        : ['active'],
  active          : ['suspended', 'archived'],
  suspended       : ['active', 'archived'],
  archived        : [],
};

registerLifecycleDefinition(
  'agrc-engine',
  'record',
  RECORD_STATES,
  RECORD_TRANSITIONS,
  {
    initialState: 'draft',
    terminalStates: ['archived'],
  },
);
