import type { ModuleTableViewDefinition } from './module-shell-definition';

const col = (field: string, en: string, ar: string, sortable = true, width?: string) =>
  ({ field, headerEn: en, headerAr: ar, sortable, width });

export const MODULE_TABLE_VIEWS: Record<string, ModuleTableViewDefinition[]> = {
  risk: [
    { id: 'risk-default', labelEn: 'All Risks', labelAr: 'جميع المخاطر', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Risk Title', 'عنوان المخاطر'),
      col('category', 'Category', 'الفئة'),
      col('severity', 'Severity', 'الخطورة', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('inherentScore', 'Inherent', 'المتأصل', true, '90px'),
      col('residualScore', 'Residual', 'المتبقي', true, '90px'),
      col('updatedAt', 'Updated', 'التحديث', true, '130px'),
    ]},
    { id: 'risk-treatment', labelEn: 'Treatment View', labelAr: 'عرض المعالجات', columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Risk Title', 'عنوان المخاطر'),
      col('treatmentPlan', 'Treatment', 'المعالجة'),
      col('treatmentStatus', 'Treatment Status', 'حالة المعالجة'),
      col('treatmentOwner', 'Assignee', 'المسؤول'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  compliance: [
    { id: 'comp-default', labelEn: 'Obligations', labelAr: 'الالتزامات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Obligation', 'الالتزام'),
      col('framework', 'Framework', 'الإطار'),
      col('domain', 'Domain', 'المجال'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('coverage', 'Coverage %', '% التغطية', true, '100px'),
      col('owner', 'Owner', 'المالك'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  policy: [
    { id: 'pol-default', labelEn: 'All Policies', labelAr: 'جميع السياسات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Policy Name', 'اسم السياسة'),
      col('category', 'Category', 'الفئة'),
      col('version', 'Version', 'الإصدار', true, '80px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('effectiveDate', 'Effective', 'السريان', true, '130px'),
      col('reviewDate', 'Next Review', 'المراجعة القادمة', true, '130px'),
    ]},
  ],
  evidence: [
    { id: 'evi-default', labelEn: 'Evidence Vault', labelAr: 'خزنة الأدلة', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Evidence Title', 'عنوان الدليل'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('quality', 'Quality', 'الجودة', true, '90px'),
      col('linkedControl', 'Control', 'الضابط'),
      col('collectedAt', 'Collected', 'تاريخ الجمع', true, '130px'),
      col('expiresAt', 'Expires', 'ينتهي', true, '130px'),
    ]},
  ],
  audit: [
    { id: 'aud-default', labelEn: 'Audit Engagements', labelAr: 'عمليات التدقيق', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Audit Title', 'عنوان التدقيق'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('leadAuditor', 'Lead Auditor', 'المدقق الرئيسي'),
      col('startDate', 'Start', 'البداية', true, '110px'),
      col('endDate', 'End', 'النهاية', true, '110px'),
      col('findingsCount', 'Findings', 'النتائج', true, '90px'),
    ]},
  ],
  incident: [
    { id: 'inc-default', labelEn: 'All Incidents', labelAr: 'جميع الحوادث', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Incident Title', 'عنوان الحادث'),
      col('severity', 'Severity', 'الخطورة', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('category', 'Category', 'الفئة'),
      col('reporter', 'Reporter', 'المبلغ'),
      col('assignee', 'Assignee', 'المسؤول'),
      col('reportedAt', 'Reported', 'تاريخ البلاغ', true, '130px'),
    ]},
  ],
  exception: [
    { id: 'exc-default', labelEn: 'All Exceptions', labelAr: 'جميع الاستثناءات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Exception Title', 'عنوان الاستثناء'),
      col('policy', 'Policy', 'السياسة'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('riskLevel', 'Risk Level', 'مستوى المخاطر', true, '110px'),
      col('owner', 'Owner', 'المالك'),
      col('expiryDate', 'Expires', 'ينتهي', true, '130px'),
    ]},
  ],
  governance: [
    { id: 'gov-default', labelEn: 'Governance Records', labelAr: 'سجلات الحوكمة', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Title', 'العنوان'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('committee', 'Committee', 'اللجنة'),
      col('decisionDate', 'Decision Date', 'تاريخ القرار', true, '130px'),
      col('owner', 'Owner', 'المالك'),
    ]},
  ],
  vendor: [
    { id: 'ven-default', labelEn: 'All Vendors', labelAr: 'جميع الموردين', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('name', 'Vendor Name', 'اسم المورد'),
      col('category', 'Category', 'الفئة'),
      col('riskTier', 'Risk Tier', 'مستوى المخاطر', true, '110px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('lastAssessment', 'Last Assessment', 'آخر تقييم', true, '130px'),
      col('contractExpiry', 'Contract Expiry', 'انتهاء العقد', true, '130px'),
    ]},
  ],
  bcp: [
    { id: 'bcp-default', labelEn: 'BCP Plans', labelAr: 'خطط الاستمرارية', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Plan Title', 'عنوان الخطة'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('rto', 'RTO', 'هدف الاسترداد', true, '80px'),
      col('rpo', 'RPO', 'هدف نقطة الاسترداد', true, '80px'),
      col('owner', 'Owner', 'المالك'),
      col('lastTested', 'Last Tested', 'آخر اختبار', true, '130px'),
    ]},
  ],
  asset: [
    { id: 'ast-default', labelEn: 'Asset Inventory', labelAr: 'جرد الأصول', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('name', 'Asset Name', 'اسم الأصل'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('classification', 'Classification', 'التصنيف', true, '120px'),
      col('criticality', 'Criticality', 'الأهمية', true, '100px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('location', 'Location', 'الموقع'),
    ]},
  ],
  remediation: [
    { id: 'rem-default', labelEn: 'Remediation Plans', labelAr: 'خطط المعالجة', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Plan Title', 'عنوان الخطة'),
      col('source', 'Source', 'المصدر'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('priority', 'Priority', 'الأولوية', true, '100px'),
      col('owner', 'Owner', 'المالك'),
      col('progress', 'Progress %', '% التقدم', true, '90px'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  action: [
    { id: 'act-default', labelEn: 'Action Items', labelAr: 'بنود العمل', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Action Title', 'عنوان الإجراء'),
      col('source', 'Source', 'المصدر'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('priority', 'Priority', 'الأولوية', true, '100px'),
      col('assignee', 'Assignee', 'المسؤول'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  training: [
    { id: 'trn-default', labelEn: 'Training Courses', labelAr: 'الدورات التدريبية', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Course Title', 'عنوان الدورة'),
      col('category', 'Category', 'الفئة'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('enrolled', 'Enrolled', 'المسجلون', true, '90px'),
      col('completion', 'Completion %', '% الإتمام', true, '100px'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  qiyas: [
    { id: 'qiy-default', labelEn: 'Assessments', labelAr: 'التقييمات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Assessment Title', 'عنوان التقييم'),
      col('framework', 'Framework', 'الإطار'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('maturityLevel', 'Maturity', 'النضج', true, '100px'),
      col('score', 'Score', 'الدرجة', true, '80px'),
      col('assessor', 'Assessor', 'المقيم'),
      col('completedAt', 'Completed', 'الإنجاز', true, '130px'),
    ]},
  ],
  'ai-governance': [
    { id: 'aig-default', labelEn: 'AI Models', labelAr: 'نماذج الذكاء الاصطناعي', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('modelName', 'Model Name', 'اسم النموذج'),
      col('riskTier', 'Risk Tier', 'مستوى المخاطر', true, '110px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('lastAudit', 'Last Audit', 'آخر تدقيق', true, '130px'),
      col('biasScore', 'Bias Score', 'درجة التحيز', true, '100px'),
    ]},
  ],
  foundation: [
    { id: 'fnd-default', labelEn: 'Foundation Items', labelAr: 'عناصر الأساس', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('name', 'Name', 'الاسم'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('scope', 'Scope', 'النطاق'),
      col('owner', 'Owner', 'المالك'),
      col('updatedAt', 'Updated', 'التحديث', true, '130px'),
    ]},
  ],
  reporting: [
    { id: 'rpt-default', labelEn: 'Reports', labelAr: 'التقارير', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Report Title', 'عنوان التقرير'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('generatedBy', 'Generated By', 'أنشئ بواسطة'),
      col('createdAt', 'Created', 'تاريخ الإنشاء', true, '130px'),
    ]},
  ],
  ai: [
    { id: 'ai-default', labelEn: 'AI Agents', labelAr: 'وكلاء الذكاء الاصطناعي', default: true, columns: [
      col('agentId', 'Agent ID', 'معرف الوكيل', true, '100px'),
      col('name', 'Agent Name', 'اسم الوكيل'),
      col('domain', 'Domain', 'المجال'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('autonomyLevel', 'Autonomy', 'الاستقلالية', true, '110px'),
      col('lastRun', 'Last Run', 'آخر تشغيل', true, '130px'),
      col('accuracy', 'Accuracy %', '% الدقة', true, '90px'),
    ]},
  ],
  integrations: [
    { id: 'int-default', labelEn: 'Connectors', labelAr: 'الموصلات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('name', 'Connector Name', 'اسم الموصل'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('lastSync', 'Last Sync', 'آخر مزامنة', true, '130px'),
      col('health', 'Health', 'الصحة', true, '90px'),
    ]},
  ],
  admin: [
    { id: 'adm-default', labelEn: 'Tenants', labelAr: 'المستأجرون', default: true, columns: [
      col('tenantId', 'Tenant ID', 'معرف المستأجر', true, '120px'),
      col('name', 'Tenant Name', 'اسم المستأجر'),
      col('plan', 'Plan', 'الخطة', true, '100px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('usersCount', 'Users', 'المستخدمون', true, '80px'),
      col('createdAt', 'Created', 'تاريخ الإنشاء', true, '130px'),
    ]},
  ],
  workflow: [
    { id: 'wf-default', labelEn: 'Workflow Instances', labelAr: 'مسارات العمل', default: true, columns: [
      col('instanceId', 'Instance ID', 'معرف المسار', true, '120px'),
      col('templateName', 'Template', 'القالب'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('currentStep', 'Current Step', 'الخطوة الحالية'),
      col('assignee', 'Assignee', 'المسؤول'),
      col('startedAt', 'Started', 'البداية', true, '130px'),
      col('slaStatus', 'SLA', 'مستوى الخدمة', true, '90px'),
    ]},
  ],
  notification: [
    { id: 'ntf-default', labelEn: 'Notification Log', labelAr: 'سجل الإشعارات', default: true, columns: [
      col('id', 'ID', 'المعرف', true, '80px'),
      col('channel', 'Channel', 'القناة', true, '100px'),
      col('subject', 'Subject', 'الموضوع'),
      col('recipient', 'Recipient', 'المستلم'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('sentAt', 'Sent At', 'تاريخ الإرسال', true, '130px'),
    ]},
  ],
  analytics: [
    { id: 'anl-default', labelEn: 'Dashboards', labelAr: 'لوحات المعلومات', default: true, columns: [
      col('id', 'ID', 'المعرف', true, '80px'),
      col('title', 'Dashboard Title', 'عنوان اللوحة'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('lastViewed', 'Last Viewed', 'آخر عرض', true, '130px'),
    ]},
  ],
  team: [
    { id: 'tm-default', labelEn: 'Team Members', labelAr: 'أعضاء الفريق', default: true, columns: [
      col('name', 'Name', 'الاسم'),
      col('email', 'Email', 'البريد الإلكتروني'),
      col('role', 'Role', 'الدور', true, '120px'),
      col('department', 'Department', 'القسم'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('workload', 'Workload', 'عبء العمل', true, '100px'),
      col('lastActive', 'Last Active', 'آخر نشاط', true, '130px'),
    ]},
  ],
  controls: [
    { id: 'ctrl-default', labelEn: 'Control Library', labelAr: 'مكتبة الضوابط', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Control Title', 'عنوان الضابط'),
      col('domain', 'Domain', 'المجال'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('effectiveness', 'Effectiveness', 'الفعالية', true, '110px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('owner', 'Owner', 'المالك'),
      col('lastTested', 'Last Tested', 'آخر اختبار', true, '130px'),
    ]},
  ],
  privacy: [
    { id: 'prv-default', labelEn: 'Privacy Records', labelAr: 'سجلات الخصوصية', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Title', 'العنوان'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('regulation', 'Regulation', 'التنظيم', true, '110px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
      col('assignee', 'Assignee', 'المسؤول'),
    ]},
  ],
  dora: [
    { id: 'dora-default', labelEn: 'DORA Records', labelAr: 'سجلات DORA', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Title', 'العنوان'),
      col('category', 'Category', 'الفئة'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('riskLevel', 'Risk Level', 'مستوى المخاطر', true, '110px'),
      col('owner', 'Owner', 'المالك'),
      col('updatedAt', 'Updated', 'التحديث', true, '130px'),
    ]},
  ],
  journey: [
    { id: 'jrn-default', labelEn: 'Journey Records', labelAr: 'سجلات الرحلة', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Title', 'العنوان'),
      col('phase', 'Phase', 'المرحلة'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('maturity', 'Maturity', 'النضج', true, '100px'),
      col('owner', 'Owner', 'المالك'),
      col('updatedAt', 'Updated', 'التحديث', true, '130px'),
    ]},
  ],
  issues: [
    { id: 'iss-default', labelEn: 'All Issues', labelAr: 'جميع المشكلات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Issue Title', 'عنوان المشكلة'),
      col('source', 'Source', 'المصدر'),
      col('severity', 'Severity', 'الخطورة', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('assignee', 'Assignee', 'المسؤول'),
      col('dueDate', 'Due Date', 'تاريخ الاستحقاق', true, '130px'),
    ]},
  ],
  inbox: [
    { id: 'ibx-default', labelEn: 'Inbox Items', labelAr: 'عناصر البريد', default: true, columns: [
      col('id', 'ID', 'المعرف', true, '80px'),
      col('subject', 'Subject', 'الموضوع'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('from', 'From', 'من'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('receivedAt', 'Received', 'تاريخ الاستلام', true, '130px'),
    ]},
  ],
  portals: [
    { id: 'ptl-default', labelEn: 'Portals', labelAr: 'البوابات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('name', 'Portal Name', 'اسم البوابة'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('usersCount', 'Users', 'المستخدمون', true, '80px'),
      col('expiresAt', 'Expires', 'ينتهي', true, '130px'),
    ]},
  ],
  records: [
    { id: 'rec-default', labelEn: 'All Records', labelAr: 'جميع السجلات', default: true, columns: [
      col('code', 'ID', 'المعرف', true, '100px'),
      col('title', 'Record Title', 'عنوان السجل'),
      col('type', 'Type', 'النوع', true, '120px'),
      col('classification', 'Classification', 'التصنيف', true, '120px'),
      col('status', 'Status', 'الحالة', true, '120px'),
      col('retentionDate', 'Retention', 'الاحتفاظ', true, '130px'),
      col('owner', 'Owner', 'المالك'),
    ]},
  ],
};
