import type { ModuleFormFieldDefinition, ModuleReportDefinition } from './module-shell-definition';

const f = (id: string, en: string, ar: string, type: ModuleFormFieldDefinition['type'], opts?: Partial<ModuleFormFieldDefinition>): ModuleFormFieldDefinition =>
  ({ id, labelEn: en, labelAr: ar, type, ...opts });

const statusOpts = (statuses: string[][]) => statuses.map(([v, en, ar]) => ({ value: v, labelEn: en, labelAr: ar }));
const severityOpts = statusOpts([['critical', 'Critical', 'حرج'], ['high', 'High', 'عالي'], ['medium', 'Medium', 'متوسط'], ['low', 'Low', 'منخفض']]);

export const MODULE_CREATE_FORM_FIELDS: Record<string, ModuleFormFieldDefinition[]> = {
  risk: [
    f('title', 'Risk Title', 'عنوان المخاطر', 'text', { required: true, span: 2 }),
    f('category', 'Category', 'الفئة', 'select', { options: statusOpts([['strategic', 'Strategic', 'استراتيجي'], ['operational', 'Operational', 'تشغيلي'], ['financial', 'Financial', 'مالي'], ['compliance', 'Compliance', 'امتثال'], ['technology', 'Technology', 'تقنية'], ['reputational', 'Reputational', 'سمعة']]) }),
    f('severity', 'Severity', 'الخطورة', 'select', { required: true, options: severityOpts }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Risk Owner', 'مالك المخاطر', 'text', { required: true }),
    f('inherentLikelihood', 'Inherent Likelihood', 'الاحتمالية المتأصلة', 'number'),
    f('inherentImpact', 'Inherent Impact', 'الأثر المتأصل', 'number'),
    f('treatmentStrategy', 'Treatment Strategy', 'استراتيجية المعالجة', 'select', { options: statusOpts([['mitigate', 'Mitigate', 'تخفيف'], ['accept', 'Accept', 'قبول'], ['transfer', 'Transfer', 'نقل'], ['avoid', 'Avoid', 'تجنب']]) }),
  ],
  compliance: [
    f('title', 'Obligation Title', 'عنوان الالتزام', 'text', { required: true, span: 2 }),
    f('framework', 'Framework', 'الإطار', 'select', { required: true, options: statusOpts([['nca-ecc', 'NCA ECC', 'NCA ECC'], ['sama-csf', 'SAMA CSF', 'SAMA CSF'], ['pdpl', 'PDPL', 'PDPL'], ['iso27001', 'ISO 27001', 'ISO 27001'], ['nist-csf', 'NIST CSF', 'NIST CSF']]) }),
    f('domain', 'Domain', 'المجال', 'text'),
    f('controlRef', 'Control Reference', 'مرجع الضابط', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  policy: [
    f('title', 'Policy Name', 'اسم السياسة', 'text', { required: true, span: 2 }),
    f('category', 'Category', 'الفئة', 'select', { options: statusOpts([['security', 'Security', 'أمني'], ['privacy', 'Privacy', 'خصوصية'], ['hr', 'HR', 'موارد بشرية'], ['it', 'IT', 'تقنية المعلومات'], ['financial', 'Financial', 'مالي'], ['operational', 'Operational', 'تشغيلي']]) }),
    f('version', 'Version', 'الإصدار', 'text'),
    f('body', 'Policy Content', 'محتوى السياسة', 'rich-text', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('effectiveDate', 'Effective Date', 'تاريخ السريان', 'date'),
    f('reviewDate', 'Review Date', 'تاريخ المراجعة', 'date'),
  ],
  evidence: [
    f('title', 'Evidence Title', 'عنوان الدليل', 'text', { required: true, span: 2 }),
    f('type', 'Evidence Type', 'نوع الدليل', 'select', { required: true, options: statusOpts([['document', 'Document', 'مستند'], ['screenshot', 'Screenshot', 'لقطة شاشة'], ['log', 'System Log', 'سجل نظام'], ['attestation', 'Attestation', 'إقرار'], ['config', 'Configuration', 'إعداد'], ['report', 'Report', 'تقرير']]) }),
    f('linkedControl', 'Linked Control', 'الضابط المرتبط', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('collector', 'Collector', 'الجامع', 'text'),
    f('expiresAt', 'Expires At', 'ينتهي في', 'date'),
  ],
  audit: [
    f('title', 'Audit Title', 'عنوان التدقيق', 'text', { required: true, span: 2 }),
    f('type', 'Audit Type', 'نوع التدقيق', 'select', { required: true, options: statusOpts([['internal', 'Internal', 'داخلي'], ['external', 'External', 'خارجي'], ['regulatory', 'Regulatory', 'تنظيمي'], ['certification', 'Certification', 'شهادة']]) }),
    f('scope', 'Scope', 'النطاق', 'textarea', { span: 2 }),
    f('leadAuditor', 'Lead Auditor', 'المدقق الرئيسي', 'text', { required: true }),
    f('startDate', 'Start Date', 'تاريخ البداية', 'date', { required: true }),
    f('endDate', 'End Date', 'تاريخ النهاية', 'date'),
    f('methodology', 'Methodology', 'المنهجية', 'select', { options: statusOpts([['risk-based', 'Risk-Based', 'قائم على المخاطر'], ['compliance', 'Compliance', 'امتثال'], ['performance', 'Performance', 'أداء'], ['follow-up', 'Follow-Up', 'متابعة']]) }),
  ],
  incident: [
    f('title', 'Incident Title', 'عنوان الحادث', 'text', { required: true, span: 2 }),
    f('severity', 'Severity', 'الخطورة', 'select', { required: true, options: severityOpts }),
    f('category', 'Category', 'الفئة', 'select', { options: statusOpts([['security', 'Security', 'أمني'], ['privacy', 'Privacy', 'خصوصية'], ['operational', 'Operational', 'تشغيلي'], ['compliance', 'Compliance', 'امتثال'], ['physical', 'Physical', 'مادي']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { required: true, span: 2 }),
    f('reporter', 'Reporter', 'المبلغ', 'text', { required: true }),
    f('assignee', 'Assignee', 'المسؤول', 'text'),
    f('reportedAt', 'Reported At', 'تاريخ البلاغ', 'date', { required: true }),
    f('impactDescription', 'Impact Description', 'وصف الأثر', 'textarea', { span: 2 }),
  ],
  exception: [
    f('title', 'Exception Title', 'عنوان الاستثناء', 'text', { required: true, span: 2 }),
    f('policyId', 'Related Policy', 'السياسة المرتبطة', 'select'),
    f('riskLevel', 'Risk Level', 'مستوى المخاطر', 'select', { required: true, options: severityOpts }),
    f('justification', 'Justification', 'المبرر', 'textarea', { required: true, span: 2 }),
    f('compensatingControls', 'Compensating Controls', 'الضوابط التعويضية', 'textarea', { span: 2 }),
    f('expiryDate', 'Expiry Date', 'تاريخ الانتهاء', 'date', { required: true }),
  ],
  governance: [
    f('title', 'Governance Item', 'عنصر الحوكمة', 'text', { required: true, span: 2 }),
    f('type', 'Type', 'النوع', 'select', { required: true, options: statusOpts([['decision', 'Decision', 'قرار'], ['charter', 'Charter', 'ميثاق'], ['mandate', 'Mandate', 'تكليف'], ['initiative', 'Initiative', 'مبادرة'], ['review', 'Review', 'مراجعة']]) }),
    f('committee', 'Committee', 'اللجنة', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  controls: [
    f('title', 'Control Title', 'عنوان الضابط', 'text', { required: true, span: 2 }),
    f('type', 'Control Type', 'نوع الضابط', 'select', { required: true, options: statusOpts([['preventive', 'Preventive', 'وقائي'], ['detective', 'Detective', 'كشفي'], ['corrective', 'Corrective', 'تصحيحي'], ['directive', 'Directive', 'توجيهي']]) }),
    f('category', 'Category', 'الفئة', 'select', { options: statusOpts([['technical', 'Technical', 'تقني'], ['administrative', 'Administrative', 'إداري'], ['physical', 'Physical', 'مادي']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('frequency', 'Testing Frequency', 'تكرار الاختبار', 'select', { options: statusOpts([['continuous', 'Continuous', 'مستمر'], ['monthly', 'Monthly', 'شهري'], ['quarterly', 'Quarterly', 'ربع سنوي'], ['annually', 'Annually', 'سنوي']]) }),
  ],
  vendor: [
    f('name', 'Vendor Name', 'اسم المورد', 'text', { required: true, span: 2 }),
    f('category', 'Category', 'الفئة', 'select', { options: statusOpts([['technology', 'Technology', 'تقنية'], ['consulting', 'Consulting', 'استشارات'], ['outsourcing', 'Outsourcing', 'تعهيد'], ['cloud', 'Cloud', 'سحابة'], ['saas', 'SaaS', 'SaaS']]) }),
    f('riskTier', 'Risk Tier', 'مستوى المخاطر', 'select', { required: true, options: statusOpts([['critical', 'Critical', 'حرج'], ['high', 'High', 'عالي'], ['medium', 'Medium', 'متوسط'], ['low', 'Low', 'منخفض']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('contactName', 'Contact Name', 'اسم جهة الاتصال', 'text'),
    f('contactEmail', 'Contact Email', 'البريد الإلكتروني', 'text'),
    f('contractStart', 'Contract Start', 'بداية العقد', 'date'),
    f('contractEnd', 'Contract End', 'نهاية العقد', 'date'),
  ],
  bcp: [
    f('title', 'Plan Title', 'عنوان الخطة', 'text', { required: true, span: 2 }),
    f('type', 'Plan Type', 'نوع الخطة', 'select', { required: true, options: statusOpts([['bcp', 'BCP', 'BCP'], ['drp', 'DRP', 'DRP'], ['crisis', 'Crisis Management', 'إدارة أزمات'], ['pandemic', 'Pandemic', 'جائحة']]) }),
    f('scope', 'Scope', 'النطاق', 'textarea', { span: 2 }),
    f('owner', 'Plan Owner', 'مالك الخطة', 'text', { required: true }),
    f('rto', 'RTO (hours)', 'هدف وقت الاستعادة (ساعات)', 'number'),
    f('rpo', 'RPO (hours)', 'هدف نقطة الاستعادة (ساعات)', 'number'),
    f('nextTestDate', 'Next Test Date', 'تاريخ الاختبار القادم', 'date'),
  ],
  asset: [
    f('name', 'Asset Name', 'اسم الأصل', 'text', { required: true, span: 2 }),
    f('type', 'Asset Type', 'نوع الأصل', 'select', { required: true, options: statusOpts([['hardware', 'Hardware', 'أجهزة'], ['software', 'Software', 'برمجيات'], ['data', 'Data', 'بيانات'], ['service', 'Service', 'خدمة'], ['people', 'People', 'أفراد'], ['facility', 'Facility', 'منشأة']]) }),
    f('criticality', 'Criticality', 'الأهمية', 'select', { required: true, options: severityOpts }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Asset Owner', 'مالك الأصل', 'text', { required: true }),
    f('location', 'Location', 'الموقع', 'text'),
    f('classification', 'Classification', 'التصنيف', 'select', { options: statusOpts([['public', 'Public', 'عام'], ['internal', 'Internal', 'داخلي'], ['confidential', 'Confidential', 'سري'], ['restricted', 'Restricted', 'مقيد']]) }),
  ],
  remediation: [
    f('title', 'Remediation Title', 'عنوان الإصلاح', 'text', { required: true, span: 2 }),
    f('sourceType', 'Source Type', 'نوع المصدر', 'select', { required: true, options: statusOpts([['audit', 'Audit Finding', 'نتيجة تدقيق'], ['risk', 'Risk Treatment', 'معالجة مخاطر'], ['incident', 'Incident', 'حادث'], ['compliance', 'Compliance Gap', 'فجوة امتثال']]) }),
    f('priority', 'Priority', 'الأولوية', 'select', { required: true, options: severityOpts }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('assignee', 'Assignee', 'المسؤول', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date', { required: true }),
  ],
  action: [
    f('title', 'Action Title', 'عنوان الإجراء', 'text', { required: true, span: 2 }),
    f('type', 'Action Type', 'نوع الإجراء', 'select', { options: statusOpts([['corrective', 'Corrective', 'تصحيحي'], ['preventive', 'Preventive', 'وقائي'], ['improvement', 'Improvement', 'تحسيني']]) }),
    f('priority', 'Priority', 'الأولوية', 'select', { required: true, options: severityOpts }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('assignee', 'Assignee', 'المسؤول', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date', { required: true }),
  ],
  training: [
    f('title', 'Training Title', 'عنوان التدريب', 'text', { required: true, span: 2 }),
    f('type', 'Training Type', 'نوع التدريب', 'select', { required: true, options: statusOpts([['awareness', 'Awareness', 'توعية'], ['technical', 'Technical', 'تقني'], ['compliance', 'Compliance', 'امتثال'], ['certification', 'Certification', 'شهادة']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('instructor', 'Instructor', 'المدرب', 'text'),
    f('targetAudience', 'Target Audience', 'الجمهور المستهدف', 'text'),
    f('startDate', 'Start Date', 'تاريخ البداية', 'date'),
    f('endDate', 'End Date', 'تاريخ النهاية', 'date'),
    f('passingScore', 'Passing Score (%)', 'درجة النجاح (%)', 'number'),
  ],
  privacy: [
    f('title', 'Request Title', 'عنوان الطلب', 'text', { required: true, span: 2 }),
    f('type', 'Request Type', 'نوع الطلب', 'select', { required: true, options: statusOpts([['dsar', 'DSAR', 'طلب حق الوصول'], ['consent', 'Consent', 'موافقة'], ['breach', 'Breach Notification', 'إخطار خرق'], ['dpia', 'DPIA', 'تقييم أثر الخصوصية'], ['ropa', 'ROPA', 'سجل الأنشطة']]) }),
    f('dataSubject', 'Data Subject', 'صاحب البيانات', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('assignee', 'Assignee', 'المسؤول', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date', { required: true }),
  ],
  dora: [
    f('title', 'DORA Item Title', 'عنوان عنصر DORA', 'text', { required: true, span: 2 }),
    f('type', 'Item Type', 'نوع العنصر', 'select', { required: true, options: statusOpts([['ict-risk', 'ICT Risk', 'مخاطر ICT'], ['resilience-test', 'Resilience Test', 'اختبار مرونة'], ['third-party', 'Third Party', 'طرف ثالث'], ['incident-report', 'Incident Report', 'تقرير حادث'], ['threat-intel', 'Threat Intelligence', 'استخبارات التهديد']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  journey: [
    f('title', 'Journey Title', 'عنوان الرحلة', 'text', { required: true, span: 2 }),
    f('type', 'Journey Type', 'نوع الرحلة', 'select', { options: statusOpts([['onboarding', 'Onboarding', 'إعداد'], ['certification', 'Certification Path', 'مسار شهادة'], ['compliance', 'Compliance Journey', 'رحلة امتثال'], ['maturity', 'Maturity Assessment', 'تقييم نضج']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text'),
    f('targetDate', 'Target Date', 'التاريخ المستهدف', 'date'),
  ],
  notification: [
    f('title', 'Notification Title', 'عنوان الإشعار', 'text', { required: true, span: 2 }),
    f('type', 'Type', 'النوع', 'select', { options: statusOpts([['alert', 'Alert', 'تنبيه'], ['reminder', 'Reminder', 'تذكير'], ['digest', 'Digest', 'ملخص'], ['announcement', 'Announcement', 'إعلان']]) }),
    f('message', 'Message', 'الرسالة', 'textarea', { required: true, span: 2 }),
    f('channel', 'Channel', 'القناة', 'select', { options: statusOpts([['email', 'Email', 'بريد إلكتروني'], ['inapp', 'In-App', 'داخل التطبيق'], ['sms', 'SMS', 'رسالة نصية']]) }),
    f('scheduledAt', 'Scheduled At', 'الموعد المحدد', 'date'),
  ],
  'ai-governance': [
    f('title', 'AI Governance Item', 'عنصر حوكمة الذكاء الاصطناعي', 'text', { required: true, span: 2 }),
    f('type', 'Item Type', 'نوع العنصر', 'select', { required: true, options: statusOpts([['model-card', 'Model Card', 'بطاقة نموذج'], ['bias-assessment', 'Bias Assessment', 'تقييم التحيز'], ['impact', 'Impact Assessment', 'تقييم الأثر'], ['policy', 'AI Policy', 'سياسة ذكاء اصطناعي']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
    f('riskLevel', 'Risk Level', 'مستوى المخاطر', 'select', { options: severityOpts }),
  ],
  qiyas: [
    f('title', 'Assessment Title', 'عنوان التقييم', 'text', { required: true, span: 2 }),
    f('framework', 'Framework', 'الإطار', 'select', { required: true }),
    f('scope', 'Scope', 'النطاق', 'textarea', { span: 2 }),
    f('assessor', 'Assessor', 'المقيّم', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  foundation: [
    f('name', 'Entity Name', 'اسم الكيان', 'text', { required: true, span: 2 }),
    f('type', 'Entity Type', 'نوع الكيان', 'select', { required: true, options: statusOpts([['department', 'Department', 'إدارة'], ['division', 'Division', 'قسم'], ['team', 'Team', 'فريق'], ['business-unit', 'Business Unit', 'وحدة أعمال']]) }),
    f('parent', 'Parent Entity', 'الكيان الأب', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
  ],
  reporting: [
    f('title', 'Report Title', 'عنوان التقرير', 'text', { required: true, span: 2 }),
    f('type', 'Report Type', 'نوع التقرير', 'select', { required: true, options: statusOpts([['executive', 'Executive', 'تنفيذي'], ['operational', 'Operational', 'تشغيلي'], ['compliance', 'Compliance', 'امتثال'], ['risk', 'Risk', 'مخاطر'], ['audit', 'Audit', 'تدقيق'], ['custom', 'Custom', 'مخصص']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('schedule', 'Schedule', 'الجدولة', 'select', { options: statusOpts([['once', 'One-Time', 'مرة واحدة'], ['daily', 'Daily', 'يومي'], ['weekly', 'Weekly', 'أسبوعي'], ['monthly', 'Monthly', 'شهري'], ['quarterly', 'Quarterly', 'ربع سنوي']]) }),
    f('format', 'Output Format', 'صيغة الإخراج', 'select', { options: statusOpts([['pdf', 'PDF', 'PDF'], ['excel', 'Excel', 'Excel'], ['csv', 'CSV', 'CSV'], ['html', 'HTML', 'HTML']]) }),
  ],
  ai: [
    f('name', 'Agent Name', 'اسم الوكيل', 'text', { required: true, span: 2 }),
    f('domain', 'Domain', 'المجال', 'select', { required: true, options: statusOpts([['risk', 'Risk', 'مخاطر'], ['compliance', 'Compliance', 'امتثال'], ['audit', 'Audit', 'تدقيق'], ['incident', 'Incident', 'حوادث'], ['general', 'General', 'عام']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('autonomyLevel', 'Autonomy Level', 'مستوى الاستقلالية', 'select', { required: true, options: statusOpts([['full', 'Full Autonomy', 'استقلالية كاملة'], ['hybrid', 'Hybrid', 'هجين'], ['shadow_agent', 'Shadow Agent', 'وكيل ظل']]) }),
    f('modelProvider', 'Model Provider', 'مزود النموذج', 'select', { options: statusOpts([['azure-openai', 'Azure OpenAI', 'Azure OpenAI'], ['anthropic', 'Anthropic', 'Anthropic'], ['ollama', 'Ollama', 'Ollama']]) }),
  ],
  integrations: [
    f('name', 'Connector Name', 'اسم الموصل', 'text', { required: true, span: 2 }),
    f('type', 'Connector Type', 'نوع الموصل', 'select', { required: true, options: statusOpts([['api', 'REST API', 'REST API'], ['webhook', 'Webhook', 'Webhook'], ['database', 'Database', 'قاعدة بيانات'], ['file', 'File Import', 'استيراد ملفات'], ['saas', 'SaaS', 'SaaS'], ['ldap', 'LDAP/AD', 'LDAP/AD']]) }),
    f('endpoint', 'Endpoint URL', 'عنوان URL', 'text'),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('authType', 'Auth Type', 'نوع المصادقة', 'select', { options: statusOpts([['api-key', 'API Key', 'مفتاح API'], ['oauth2', 'OAuth 2.0', 'OAuth 2.0'], ['basic', 'Basic Auth', 'مصادقة أساسية'], ['certificate', 'Certificate', 'شهادة']]) }),
    f('syncFrequency', 'Sync Frequency', 'تكرار المزامنة', 'select', { options: statusOpts([['realtime', 'Real-time', 'فوري'], ['hourly', 'Hourly', 'كل ساعة'], ['daily', 'Daily', 'يومي'], ['manual', 'Manual', 'يدوي']]) }),
  ],
  admin: [
    f('name', 'Tenant Name', 'اسم المستأجر', 'text', { required: true, span: 2 }),
    f('plan', 'Plan', 'الخطة', 'select', { required: true, options: statusOpts([['starter', 'Starter', 'مبتدئ'], ['professional', 'Professional', 'احترافي'], ['enterprise', 'Enterprise', 'مؤسسي']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('adminEmail', 'Admin Email', 'بريد المسؤول', 'text', { required: true }),
    f('maxUsers', 'Max Users', 'أقصى عدد مستخدمين', 'number'),
  ],
  workflow: [
    f('title', 'Workflow Title', 'عنوان مسار العمل', 'text', { required: true, span: 2 }),
    f('templateCode', 'Template', 'القالب', 'select', { required: true }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('assignee', 'Assignee', 'المسؤول', 'text', { required: true }),
    f('priority', 'Priority', 'الأولوية', 'select', { options: severityOpts }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  analytics: [
    f('title', 'Dashboard Title', 'عنوان لوحة المعلومات', 'text', { required: true, span: 2 }),
    f('type', 'Dashboard Type', 'نوع اللوحة', 'select', { required: true, options: statusOpts([['executive', 'Executive', 'تنفيذي'], ['operational', 'Operational', 'تشغيلي'], ['compliance', 'Compliance', 'امتثال'], ['risk', 'Risk', 'مخاطر'], ['custom', 'Custom', 'مخصص']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('refreshInterval', 'Refresh Interval', 'فترة التحديث', 'select', { options: statusOpts([['realtime', 'Real-time', 'فوري'], ['5min', '5 Minutes', '5 دقائق'], ['15min', '15 Minutes', '15 دقيقة'], ['hourly', 'Hourly', 'كل ساعة']]) }),
  ],
  team: [
    f('name', 'Member Name', 'اسم العضو', 'text', { required: true, span: 2 }),
    f('email', 'Email', 'البريد الإلكتروني', 'text', { required: true }),
    f('role', 'Role', 'الدور', 'select', { required: true, options: statusOpts([['admin', 'Admin', 'مسؤول'], ['manager', 'Manager', 'مدير'], ['analyst', 'Analyst', 'محلل'], ['auditor', 'Auditor', 'مدقق'], ['viewer', 'Viewer', 'مشاهد']]) }),
    f('department', 'Department', 'القسم', 'text'),
    f('title', 'Job Title', 'المسمى الوظيفي', 'text'),
  ],
  issues: [
    f('title', 'Issue Title', 'عنوان المشكلة', 'text', { required: true, span: 2 }),
    f('source', 'Source', 'المصدر', 'select', { required: true, options: statusOpts([['audit', 'Audit Finding', 'نتيجة تدقيق'], ['incident', 'Incident', 'حادث'], ['compliance', 'Compliance Gap', 'فجوة امتثال'], ['risk', 'Risk Treatment', 'معالجة مخاطر'], ['manual', 'Manual Entry', 'إدخال يدوي']]) }),
    f('severity', 'Severity', 'الخطورة', 'select', { required: true, options: severityOpts }),
    f('description', 'Description', 'الوصف', 'textarea', { required: true, span: 2 }),
    f('assignee', 'Assignee', 'المسؤول', 'text', { required: true }),
    f('dueDate', 'Due Date', 'تاريخ الاستحقاق', 'date'),
  ],
  inbox: [
    f('subject', 'Subject', 'الموضوع', 'text', { required: true, span: 2 }),
    f('type', 'Type', 'النوع', 'select', { options: statusOpts([['task', 'Task', 'مهمة'], ['approval', 'Approval', 'موافقة'], ['notification', 'Notification', 'إشعار'], ['alert', 'Alert', 'تنبيه']]) }),
    f('message', 'Message', 'الرسالة', 'textarea', { required: true, span: 2 }),
    f('priority', 'Priority', 'الأولوية', 'select', { options: severityOpts }),
  ],
  portals: [
    f('name', 'Portal Name', 'اسم البوابة', 'text', { required: true, span: 2 }),
    f('type', 'Portal Type', 'نوع البوابة', 'select', { required: true, options: statusOpts([['vendor', 'Vendor Portal', 'بوابة الموردين'], ['client', 'Client Portal', 'بوابة العملاء'], ['regulatory', 'Regulatory Portal', 'بوابة تنظيمية'], ['internal', 'Internal Portal', 'بوابة داخلية']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('expiresAt', 'Expiry Date', 'تاريخ الانتهاء', 'date'),
    f('accessControl', 'Access Control', 'التحكم بالوصول', 'select', { options: statusOpts([['public', 'Public', 'عام'], ['authenticated', 'Authenticated', 'مصادق'], ['invitation', 'Invitation Only', 'دعوة فقط']]) }),
  ],
  records: [
    f('title', 'Record Title', 'عنوان السجل', 'text', { required: true, span: 2 }),
    f('type', 'Record Type', 'نوع السجل', 'select', { required: true, options: statusOpts([['document', 'Document', 'مستند'], ['contract', 'Contract', 'عقد'], ['correspondence', 'Correspondence', 'مراسلات'], ['certificate', 'Certificate', 'شهادة'], ['report', 'Report', 'تقرير']]) }),
    f('classification', 'Classification', 'التصنيف', 'select', { required: true, options: statusOpts([['public', 'Public', 'عام'], ['internal', 'Internal', 'داخلي'], ['confidential', 'Confidential', 'سري'], ['restricted', 'Restricted', 'مقيد']]) }),
    f('description', 'Description', 'الوصف', 'textarea', { span: 2 }),
    f('retentionPeriod', 'Retention Period', 'فترة الاحتفاظ', 'select', { options: statusOpts([['1y', '1 Year', 'سنة'], ['3y', '3 Years', '3 سنوات'], ['5y', '5 Years', '5 سنوات'], ['7y', '7 Years', '7 سنوات'], ['permanent', 'Permanent', 'دائم']]) }),
    f('owner', 'Owner', 'المالك', 'text', { required: true }),
  ],
};

export const MODULE_REPORT_DEFINITIONS: Record<string, ModuleReportDefinition[]> = {
  risk: [
    { id: 'rpt-risk-heatmap', labelEn: 'Risk Heatmap', labelAr: 'خريطة حرارة المخاطر', icon: 'pi-th-large', type: 'heatmap' },
    { id: 'rpt-risk-trend', labelEn: 'Risk Trend Analysis', labelAr: 'تحليل اتجاه المخاطر', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-risk-summary', labelEn: 'Risk Summary', labelAr: 'ملخص المخاطر', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-risk-treatment', labelEn: 'Treatment Status', labelAr: 'حالة المعالجات', icon: 'pi-list', type: 'table' },
  ],
  compliance: [
    { id: 'rpt-comp-score', labelEn: 'Compliance Score Trend', labelAr: 'اتجاه درجة الامتثال', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-comp-gaps', labelEn: 'Gap Analysis', labelAr: 'تحليل الفجوات', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-comp-summary', labelEn: 'Framework Summary', labelAr: 'ملخص الأطر', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-comp-control', labelEn: 'Control Coverage', labelAr: 'تغطية الضوابط', icon: 'pi-percentage', type: 'table' },
  ],
  policy: [
    { id: 'rpt-pol-lifecycle', labelEn: 'Policy Lifecycle', labelAr: 'دورة حياة السياسات', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-pol-attestation', labelEn: 'Attestation Status', labelAr: 'حالة الإقرارات', icon: 'pi-users', type: 'table' },
    { id: 'rpt-pol-expiry', labelEn: 'Expiring Policies', labelAr: 'السياسات المنتهية', icon: 'pi-clock', type: 'table' },
  ],
  evidence: [
    { id: 'rpt-evi-freshness', labelEn: 'Evidence Freshness', labelAr: 'حداثة الأدلة', icon: 'pi-clock', type: 'chart' },
    { id: 'rpt-evi-quality', labelEn: 'Quality Scores', labelAr: 'درجات الجودة', icon: 'pi-star', type: 'trend' },
    { id: 'rpt-evi-coverage', labelEn: 'Control Coverage', labelAr: 'تغطية الضوابط', icon: 'pi-th-large', type: 'heatmap' },
  ],
  audit: [
    { id: 'rpt-aud-findings', labelEn: 'Findings Trend', labelAr: 'اتجاه النتائج', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-aud-status', labelEn: 'Engagement Status', labelAr: 'حالة عمليات التدقيق', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-aud-capa', labelEn: 'CAPA Tracking', labelAr: 'تتبع الإجراءات التصحيحية', icon: 'pi-list', type: 'table' },
  ],
  incident: [
    { id: 'rpt-inc-trend', labelEn: 'Incident Trend', labelAr: 'اتجاه الحوادث', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-inc-severity', labelEn: 'By Severity', labelAr: 'حسب الخطورة', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-inc-mttr', labelEn: 'MTTR Analysis', labelAr: 'تحليل وقت الاستجابة', icon: 'pi-clock', type: 'kpi-summary' },
  ],
  exception: [
    { id: 'rpt-exc-status', labelEn: 'Exception Status', labelAr: 'حالة الاستثناءات', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-exc-expiry', labelEn: 'Expiring Exceptions', labelAr: 'الاستثناءات المنتهية', icon: 'pi-clock', type: 'table' },
  ],
  vendor: [
    { id: 'rpt-ven-risk', labelEn: 'Vendor Risk Distribution', labelAr: 'توزيع مخاطر الموردين', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-ven-score', labelEn: 'Vendor Scores', labelAr: 'درجات الموردين', icon: 'pi-chart-bar', type: 'table' },
    { id: 'rpt-ven-contract', labelEn: 'Contract Expiry', labelAr: 'انتهاء العقود', icon: 'pi-clock', type: 'table' },
  ],
  bcp: [
    { id: 'rpt-bcp-readiness', labelEn: 'Readiness Score', labelAr: 'درجة الاستعداد', icon: 'pi-chart-bar', type: 'kpi-summary' },
    { id: 'rpt-bcp-test', labelEn: 'Test Results', labelAr: 'نتائج الاختبارات', icon: 'pi-check-circle', type: 'table' },
  ],
  remediation: [
    { id: 'rpt-rem-status', labelEn: 'Remediation Status', labelAr: 'حالة الإصلاحات', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-rem-aging', labelEn: 'Aging Analysis', labelAr: 'تحليل التقادم', icon: 'pi-clock', type: 'trend' },
  ],
  action: [
    { id: 'rpt-act-status', labelEn: 'Action Status', labelAr: 'حالة الإجراءات', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-act-overdue', labelEn: 'Overdue Actions', labelAr: 'الإجراءات المتأخرة', icon: 'pi-clock', type: 'table' },
  ],
  training: [
    { id: 'rpt-trn-completion', labelEn: 'Completion Rate', labelAr: 'معدل الإكمال', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-trn-scores', labelEn: 'Score Distribution', labelAr: 'توزيع الدرجات', icon: 'pi-chart-line', type: 'trend' },
  ],
  qiyas: [
    { id: 'rpt-qiy-maturity', labelEn: 'Maturity Trend', labelAr: 'اتجاه النضج', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-qiy-benchmark', labelEn: 'Benchmark Comparison', labelAr: 'مقارنة مرجعية', icon: 'pi-chart-bar', type: 'chart' },
  ],
  controls: [
    { id: 'rpt-ctl-effectiveness', labelEn: 'Control Effectiveness', labelAr: 'فعالية الضوابط', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-ctl-coverage', labelEn: 'Control Coverage', labelAr: 'تغطية الضوابط', icon: 'pi-th-large', type: 'heatmap' },
    { id: 'rpt-ctl-test', labelEn: 'Test Results', labelAr: 'نتائج الاختبار', icon: 'pi-check-circle', type: 'table' },
  ],
  governance: [
    { id: 'rpt-gov-decisions', labelEn: 'Decision Tracking', labelAr: 'تتبع القرارات', icon: 'pi-list', type: 'table' },
    { id: 'rpt-gov-health', labelEn: 'Governance Health', labelAr: 'صحة الحوكمة', icon: 'pi-chart-pie', type: 'kpi-summary' },
  ],
  dora: [
    { id: 'rpt-dora-resilience', labelEn: 'Resilience Score', labelAr: 'درجة المرونة', icon: 'pi-chart-bar', type: 'kpi-summary' },
    { id: 'rpt-dora-incidents', labelEn: 'ICT Incidents', labelAr: 'حوادث ICT', icon: 'pi-chart-line', type: 'trend' },
  ],
  journey: [
    { id: 'rpt-jrn-progress', labelEn: 'Journey Progress', labelAr: 'تقدم الرحلة', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-jrn-completion', labelEn: 'Completion Rate', labelAr: 'معدل الإكمال', icon: 'pi-percentage', type: 'kpi-summary' },
  ],
  privacy: [
    { id: 'rpt-prv-dsars', labelEn: 'DSAR Tracking', labelAr: 'تتبع طلبات الوصول', icon: 'pi-list', type: 'table' },
    { id: 'rpt-prv-breaches', labelEn: 'Breach History', labelAr: 'سجل الخروقات', icon: 'pi-chart-line', type: 'trend' },
  ],
  'ai-governance': [
    { id: 'rpt-aig-models', labelEn: 'Model Registry Status', labelAr: 'حالة سجل النماذج', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-aig-bias', labelEn: 'Bias Assessment Trend', labelAr: 'اتجاه تقييم التحيز', icon: 'pi-chart-line', type: 'trend' },
  ],
  foundation: [
    { id: 'rpt-fnd-hierarchy', labelEn: 'Org Hierarchy', labelAr: 'التسلسل التنظيمي', icon: 'pi-sitemap', type: 'chart' },
  ],
  reporting: [
    { id: 'rpt-rpt-catalog', labelEn: 'Report Catalog', labelAr: 'فهرس التقارير', icon: 'pi-list', type: 'table' },
    { id: 'rpt-rpt-schedule', labelEn: 'Schedule Overview', labelAr: 'نظرة عامة على الجدولة', icon: 'pi-calendar', type: 'kpi-summary' },
    { id: 'rpt-rpt-usage', labelEn: 'Report Usage', labelAr: 'استخدام التقارير', icon: 'pi-chart-bar', type: 'trend' },
  ],
  ai: [
    { id: 'rpt-ai-runs', labelEn: 'AI Run History', labelAr: 'سجل تشغيل الذكاء الاصطناعي', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-ai-accuracy', labelEn: 'Agent Accuracy', labelAr: 'دقة الوكلاء', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-ai-guardrails', labelEn: 'Guardrail Blocks', labelAr: 'حالات الحظر', icon: 'pi-exclamation-triangle', type: 'table' },
    { id: 'rpt-ai-usage', labelEn: 'Token Usage', labelAr: 'استهلاك الرموز', icon: 'pi-chart-pie', type: 'kpi-summary' },
  ],
  integrations: [
    { id: 'rpt-int-health', labelEn: 'Connector Health', labelAr: 'صحة الموصلات', icon: 'pi-heart', type: 'kpi-summary' },
    { id: 'rpt-int-sync', labelEn: 'Sync History', labelAr: 'سجل المزامنة', icon: 'pi-refresh', type: 'trend' },
    { id: 'rpt-int-errors', labelEn: 'Error Log', labelAr: 'سجل الأخطاء', icon: 'pi-exclamation-circle', type: 'table' },
  ],
  admin: [
    { id: 'rpt-adm-tenants', labelEn: 'Tenant Overview', labelAr: 'نظرة عامة على المستأجرين', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-adm-usage', labelEn: 'Platform Usage', labelAr: 'استخدام المنصة', icon: 'pi-chart-bar', type: 'trend' },
    { id: 'rpt-adm-audit', labelEn: 'Admin Audit Log', labelAr: 'سجل تدقيق المسؤولين', icon: 'pi-list', type: 'table' },
  ],
  workflow: [
    { id: 'rpt-wf-throughput', labelEn: 'Workflow Throughput', labelAr: 'إنتاجية مسارات العمل', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-wf-sla', labelEn: 'SLA Compliance', labelAr: 'التزام مستوى الخدمة', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-wf-bottlenecks', labelEn: 'Bottleneck Analysis', labelAr: 'تحليل الاختناقات', icon: 'pi-chart-pie', type: 'kpi-summary' },
  ],
  notification: [
    { id: 'rpt-ntf-volume', labelEn: 'Notification Volume', labelAr: 'حجم الإشعارات', icon: 'pi-chart-bar', type: 'trend' },
    { id: 'rpt-ntf-delivery', labelEn: 'Delivery Status', labelAr: 'حالة التسليم', icon: 'pi-chart-pie', type: 'chart' },
  ],
  analytics: [
    { id: 'rpt-anl-overview', labelEn: 'Analytics Overview', labelAr: 'نظرة عامة على التحليلات', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-anl-trends', labelEn: 'KPI Trends', labelAr: 'اتجاهات مؤشرات الأداء', icon: 'pi-chart-line', type: 'trend' },
  ],
  team: [
    { id: 'rpt-tm-workload', labelEn: 'Workload Distribution', labelAr: 'توزيع عبء العمل', icon: 'pi-chart-bar', type: 'chart' },
    { id: 'rpt-tm-capacity', labelEn: 'Team Capacity', labelAr: 'قدرة الفريق', icon: 'pi-chart-pie', type: 'kpi-summary' },
    { id: 'rpt-tm-activity', labelEn: 'Activity Report', labelAr: 'تقرير النشاط', icon: 'pi-chart-line', type: 'trend' },
  ],
  issues: [
    { id: 'rpt-iss-status', labelEn: 'Issue Status', labelAr: 'حالة المشكلات', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-iss-trend', labelEn: 'Issue Trend', labelAr: 'اتجاه المشكلات', icon: 'pi-chart-line', type: 'trend' },
    { id: 'rpt-iss-aging', labelEn: 'Aging Analysis', labelAr: 'تحليل التقادم', icon: 'pi-clock', type: 'table' },
  ],
  inbox: [
    { id: 'rpt-ibx-volume', labelEn: 'Inbox Volume', labelAr: 'حجم البريد الوارد', icon: 'pi-chart-bar', type: 'trend' },
    { id: 'rpt-ibx-response', labelEn: 'Response Time', labelAr: 'وقت الاستجابة', icon: 'pi-clock', type: 'kpi-summary' },
  ],
  portals: [
    { id: 'rpt-ptl-usage', labelEn: 'Portal Usage', labelAr: 'استخدام البوابات', icon: 'pi-chart-bar', type: 'trend' },
    { id: 'rpt-ptl-access', labelEn: 'Access Logs', labelAr: 'سجلات الوصول', icon: 'pi-list', type: 'table' },
  ],
  records: [
    { id: 'rpt-rec-inventory', labelEn: 'Records Inventory', labelAr: 'جرد السجلات', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-rec-retention', labelEn: 'Retention Status', labelAr: 'حالة الاحتفاظ', icon: 'pi-clock', type: 'table' },
    { id: 'rpt-rec-classification', labelEn: 'Classification Summary', labelAr: 'ملخص التصنيف', icon: 'pi-chart-bar', type: 'kpi-summary' },
  ],
  asset: [
    { id: 'rpt-ast-inventory', labelEn: 'Asset Inventory', labelAr: 'جرد الأصول', icon: 'pi-chart-pie', type: 'chart' },
    { id: 'rpt-ast-criticality', labelEn: 'Criticality Distribution', labelAr: 'توزيع الأهمية', icon: 'pi-chart-bar', type: 'kpi-summary' },
    { id: 'rpt-ast-lifecycle', labelEn: 'Lifecycle Status', labelAr: 'حالة دورة الحياة', icon: 'pi-chart-line', type: 'trend' },
  ],
};
