/**
 * evidence — Module Security Registration
 * Auto-generated by scripts/codegen/generate-manifest-security.ts
 * Extracted from 23 route files, 7 unique permissions.
 *
 * DO NOT EDIT permissions extracted from routes. Add new permissions below the generated block.
 */

import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const EVIDENCE_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'evidence.item.read', resourceType: 'item', actionType: 'read', descriptionEn: 'read item', descriptionAr: 'read item', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'evidence.item.write', resourceType: 'item', actionType: 'write', descriptionEn: 'write item', descriptionAr: 'write item', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'evidence.item.delete', resourceType: 'item', actionType: 'delete', descriptionEn: 'delete item', descriptionAr: 'delete item', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'evidence.item.configure', resourceType: 'item', actionType: 'configure', descriptionEn: 'configure item', descriptionAr: 'configure item', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'admin.system.manage', resourceType: 'system', actionType: 'manage', descriptionEn: 'manage system', descriptionAr: 'manage system', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'evidence.item.admin', resourceType: 'item', actionType: 'manage', descriptionEn: 'manage item', descriptionAr: 'manage item', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'evidence.item.manage', resourceType: 'item', actionType: 'manage', descriptionEn: 'manage item', descriptionAr: 'manage item', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const EVIDENCE_ROLES: ModuleRole[] = [
  { roleCode: 'evidence.executive_owner', archetype: 'executive_owner', nameEn: 'evidence executive owner', nameAr: 'executive_owner', descriptionEn: 'executive owner for evidence', descriptionAr: 'executive_owner', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read', 'evidence.item.write', 'evidence.item.delete', 'evidence.item.configure', 'admin.system.manage', 'evidence.item.admin', 'evidence.item.manage'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'evidence.module_lead', archetype: 'module_lead', nameEn: 'evidence module lead', nameAr: 'module_lead', descriptionEn: 'module lead for evidence', descriptionAr: 'module_lead', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read', 'evidence.item.write', 'evidence.item.delete'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'evidence.approver', archetype: 'approver', nameEn: 'evidence approver', nameAr: 'approver', descriptionEn: 'approver for evidence', descriptionAr: 'approver', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read'], authorityLevel: 'required', defaultScope: 'own' },
  { roleCode: 'evidence.operator', archetype: 'operator', nameEn: 'evidence operator', nameAr: 'operator', descriptionEn: 'operator for evidence', descriptionAr: 'operator', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read', 'evidence.item.write'], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'evidence.contributor', archetype: 'contributor', nameEn: 'evidence contributor', nameAr: 'contributor', descriptionEn: 'contributor for evidence', descriptionAr: 'contributor', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read', 'evidence.item.write'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'evidence.reviewer', archetype: 'reviewer', nameEn: 'evidence reviewer', nameAr: 'reviewer', descriptionEn: 'reviewer for evidence', descriptionAr: 'reviewer', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'evidence.auditor', archetype: 'auditor', nameEn: 'evidence auditor', nameAr: 'auditor', descriptionEn: 'auditor for evidence', descriptionAr: 'auditor', isDefault: false, isSystem: false, isGlobal: false, permissions: ['evidence.item.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'evidence.viewer', archetype: 'viewer', nameEn: 'evidence viewer', nameAr: 'viewer', descriptionEn: 'viewer for evidence', descriptionAr: 'viewer', isDefault: true, isSystem: false, isGlobal: false, permissions: ['evidence.item.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const EVIDENCE_ACTIONS: ModuleAction[] = [
  { actionCode: 'evidence.item.read', labelEn: 'read item', labelAr: 'read item', requiredPermissions: ['evidence.item.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'evidence.item.write', labelEn: 'write item', labelAr: 'write item', requiredPermissions: ['evidence.item.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'evidence.item.delete', labelEn: 'delete item', labelAr: 'delete item', requiredPermissions: ['evidence.item.delete'], requiredAuthorityLevel: 'required', sodSensitive: true, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: true, auditable: true, reversible: false, bulkSafe: false, externalExposure: false },
  { actionCode: 'evidence.item.configure', labelEn: 'configure item', labelAr: 'configure item', requiredPermissions: ['evidence.item.configure'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'admin.system.manage', labelEn: 'manage system', labelAr: 'manage system', requiredPermissions: ['admin.system.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'evidence.item.admin', labelEn: 'admin item', labelAr: 'admin item', requiredPermissions: ['evidence.item.admin'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'evidence.item.manage', labelEn: 'manage item', labelAr: 'manage item', requiredPermissions: ['evidence.item.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
];
