import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const TRAINING_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'TRAINING.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'TRAINING.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'TRAINING.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'TRAINING.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'TRAINING.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'TRAINING.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'TRAINING.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'TRAINING.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'TRAINING.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  ANALYTICS_NOT_FOUND: { code: 'TRAINING.ANALYTICS_NOT_FOUND', httpStatus: 404, messageEn: 'Analytics not found', messageAr: 'Analytics غير موجود' },
  ANALYTICS_ALREADY_EXISTS: { code: 'TRAINING.ANALYTICS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Analytics already exists', messageAr: 'Analytics موجود بالفعل' },
  ANALYTICS_VALIDATION_FAILED: { code: 'TRAINING.ANALYTICS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Analytics validation failed', messageAr: 'فشل التحقق من Analytics' },
  OVERDUE_NOT_FOUND: { code: 'TRAINING.OVERDUE_NOT_FOUND', httpStatus: 404, messageEn: 'Overdue not found', messageAr: 'Overdue غير موجود' },
  OVERDUE_ALREADY_EXISTS: { code: 'TRAINING.OVERDUE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Overdue already exists', messageAr: 'Overdue موجود بالفعل' },
  OVERDUE_VALIDATION_FAILED: { code: 'TRAINING.OVERDUE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Overdue validation failed', messageAr: 'فشل التحقق من Overdue' },
  REINDEX_NOT_FOUND: { code: 'TRAINING.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'TRAINING.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'TRAINING.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'TRAINING.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'TRAINING.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'TRAINING.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  PROGRAMS_NOT_FOUND: { code: 'TRAINING.PROGRAMS_NOT_FOUND', httpStatus: 404, messageEn: 'Programs not found', messageAr: 'Programs غير موجود' },
  PROGRAMS_ALREADY_EXISTS: { code: 'TRAINING.PROGRAMS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Programs already exists', messageAr: 'Programs موجود بالفعل' },
  PROGRAMS_VALIDATION_FAILED: { code: 'TRAINING.PROGRAMS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Programs validation failed', messageAr: 'فشل التحقق من Programs' },
  CONTENT_NOT_FOUND: { code: 'TRAINING.CONTENT_NOT_FOUND', httpStatus: 404, messageEn: 'Content not found', messageAr: 'Content غير موجود' },
  CONTENT_ALREADY_EXISTS: { code: 'TRAINING.CONTENT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Content already exists', messageAr: 'Content موجود بالفعل' },
  CONTENT_VALIDATION_FAILED: { code: 'TRAINING.CONTENT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Content validation failed', messageAr: 'فشل التحقق من Content' },
  CAMPAIGNS_NOT_FOUND: { code: 'TRAINING.CAMPAIGNS_NOT_FOUND', httpStatus: 404, messageEn: 'Campaigns not found', messageAr: 'Campaigns غير موجود' },
  CAMPAIGNS_ALREADY_EXISTS: { code: 'TRAINING.CAMPAIGNS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Campaigns already exists', messageAr: 'Campaigns موجود بالفعل' },
  CAMPAIGNS_VALIDATION_FAILED: { code: 'TRAINING.CAMPAIGNS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Campaigns validation failed', messageAr: 'فشل التحقق من Campaigns' },
  ASSIGNMENTS_NOT_FOUND: { code: 'TRAINING.ASSIGNMENTS_NOT_FOUND', httpStatus: 404, messageEn: 'Assignments not found', messageAr: 'Assignments غير موجود' },
  ASSIGNMENTS_ALREADY_EXISTS: { code: 'TRAINING.ASSIGNMENTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Assignments already exists', messageAr: 'Assignments موجود بالفعل' },
  ASSIGNMENTS_VALIDATION_FAILED: { code: 'TRAINING.ASSIGNMENTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Assignments validation failed', messageAr: 'فشل التحقق من Assignments' },
  CERTIFICATIONS_NOT_FOUND: { code: 'TRAINING.CERTIFICATIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Certifications not found', messageAr: 'Certifications غير موجود' },
  CERTIFICATIONS_ALREADY_EXISTS: { code: 'TRAINING.CERTIFICATIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Certifications already exists', messageAr: 'Certifications موجود بالفعل' },
  CERTIFICATIONS_VALIDATION_FAILED: { code: 'TRAINING.CERTIFICATIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Certifications validation failed', messageAr: 'فشل التحقق من Certifications' },
  PHISHING_NOT_FOUND: { code: 'TRAINING.PHISHING_NOT_FOUND', httpStatus: 404, messageEn: 'Phishing not found', messageAr: 'Phishing غير موجود' },
  PHISHING_ALREADY_EXISTS: { code: 'TRAINING.PHISHING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Phishing already exists', messageAr: 'Phishing موجود بالفعل' },
  PHISHING_VALIDATION_FAILED: { code: 'TRAINING.PHISHING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Phishing validation failed', messageAr: 'فشل التحقق من Phishing' },
  COMPLIANCE_SNAPSHOT_NOT_FOUND: { code: 'TRAINING.COMPLIANCE_SNAPSHOT_NOT_FOUND', httpStatus: 404, messageEn: 'Compliance Snapshot not found', messageAr: 'Compliance Snapshot غير موجود' },
  COMPLIANCE_SNAPSHOT_ALREADY_EXISTS: { code: 'TRAINING.COMPLIANCE_SNAPSHOT_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Compliance Snapshot already exists', messageAr: 'Compliance Snapshot موجود بالفعل' },
  COMPLIANCE_SNAPSHOT_VALIDATION_FAILED: { code: 'TRAINING.COMPLIANCE_SNAPSHOT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Compliance Snapshot validation failed', messageAr: 'فشل التحقق من Compliance Snapshot' },
  EXPIRING_CERTS_NOT_FOUND: { code: 'TRAINING.EXPIRING_CERTS_NOT_FOUND', httpStatus: 404, messageEn: 'Expiring Certs not found', messageAr: 'Expiring Certs غير موجود' },
  EXPIRING_CERTS_ALREADY_EXISTS: { code: 'TRAINING.EXPIRING_CERTS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Expiring Certs already exists', messageAr: 'Expiring Certs موجود بالفعل' },
  EXPIRING_CERTS_VALIDATION_FAILED: { code: 'TRAINING.EXPIRING_CERTS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Expiring Certs validation failed', messageAr: 'فشل التحقق من Expiring Certs' },

  UNAUTHORIZED: { code: 'TRAINING.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for training operation', messageAr: 'صلاحيات غير كافية لعملية training' },
  INVALID_STATE_TRANSITION: { code: 'TRAINING.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'TRAINING.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'TRAINING.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'TRAINING.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'TRAINING.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type TrainingErrorCode = keyof typeof TRAINING_ERROR_CODES;
