import type { ModuleErrorCode } from '../../../shared/error-catalog.types';

export const GOVERNANCE_ERROR_CODES = {
  CONFIG_NOT_FOUND: { code: 'GOVERNANCE.CONFIG_NOT_FOUND', httpStatus: 404, messageEn: 'Config not found', messageAr: 'Config غير موجود' },
  CONFIG_ALREADY_EXISTS: { code: 'GOVERNANCE.CONFIG_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Config already exists', messageAr: 'Config موجود بالفعل' },
  CONFIG_VALIDATION_FAILED: { code: 'GOVERNANCE.CONFIG_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Config validation failed', messageAr: 'فشل التحقق من Config' },
  RESEED_NOT_FOUND: { code: 'GOVERNANCE.RESEED_NOT_FOUND', httpStatus: 404, messageEn: 'Reseed not found', messageAr: 'Reseed غير موجود' },
  RESEED_ALREADY_EXISTS: { code: 'GOVERNANCE.RESEED_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reseed already exists', messageAr: 'Reseed موجود بالفعل' },
  RESEED_VALIDATION_FAILED: { code: 'GOVERNANCE.RESEED_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reseed validation failed', messageAr: 'فشل التحقق من Reseed' },
  HEALTH_NOT_FOUND: { code: 'GOVERNANCE.HEALTH_NOT_FOUND', httpStatus: 404, messageEn: 'Health not found', messageAr: 'Health غير موجود' },
  HEALTH_ALREADY_EXISTS: { code: 'GOVERNANCE.HEALTH_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Health already exists', messageAr: 'Health موجود بالفعل' },
  HEALTH_VALIDATION_FAILED: { code: 'GOVERNANCE.HEALTH_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Health validation failed', messageAr: 'فشل التحقق من Health' },
  REINDEX_NOT_FOUND: { code: 'GOVERNANCE.REINDEX_NOT_FOUND', httpStatus: 404, messageEn: 'Reindex not found', messageAr: 'Reindex غير موجود' },
  REINDEX_ALREADY_EXISTS: { code: 'GOVERNANCE.REINDEX_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Reindex already exists', messageAr: 'Reindex موجود بالفعل' },
  REINDEX_VALIDATION_FAILED: { code: 'GOVERNANCE.REINDEX_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Reindex validation failed', messageAr: 'فشل التحقق من Reindex' },
  BACKFILL_NOT_FOUND: { code: 'GOVERNANCE.BACKFILL_NOT_FOUND', httpStatus: 404, messageEn: 'Backfill not found', messageAr: 'Backfill غير موجود' },
  BACKFILL_ALREADY_EXISTS: { code: 'GOVERNANCE.BACKFILL_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Backfill already exists', messageAr: 'Backfill موجود بالفعل' },
  BACKFILL_VALIDATION_FAILED: { code: 'GOVERNANCE.BACKFILL_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Backfill validation failed', messageAr: 'فشل التحقق من Backfill' },
  SCAN_NOT_FOUND: { code: 'GOVERNANCE.SCAN_NOT_FOUND', httpStatus: 404, messageEn: 'Scan not found', messageAr: 'Scan غير موجود' },
  SCAN_ALREADY_EXISTS: { code: 'GOVERNANCE.SCAN_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Scan already exists', messageAr: 'Scan موجود بالفعل' },
  SCAN_VALIDATION_FAILED: { code: 'GOVERNANCE.SCAN_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Scan validation failed', messageAr: 'فشل التحقق من Scan' },
  VIOLATIONS_NOT_FOUND: { code: 'GOVERNANCE.VIOLATIONS_NOT_FOUND', httpStatus: 404, messageEn: 'Violations not found', messageAr: 'Violations غير موجود' },
  VIOLATIONS_ALREADY_EXISTS: { code: 'GOVERNANCE.VIOLATIONS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Violations already exists', messageAr: 'Violations موجود بالفعل' },
  VIOLATIONS_VALIDATION_FAILED: { code: 'GOVERNANCE.VIOLATIONS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Violations validation failed', messageAr: 'فشل التحقق من Violations' },
  SUMMARY_NOT_FOUND: { code: 'GOVERNANCE.SUMMARY_NOT_FOUND', httpStatus: 404, messageEn: 'Summary not found', messageAr: 'Summary غير موجود' },
  SUMMARY_ALREADY_EXISTS: { code: 'GOVERNANCE.SUMMARY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Summary already exists', messageAr: 'Summary موجود بالفعل' },
  SUMMARY_VALIDATION_FAILED: { code: 'GOVERNANCE.SUMMARY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Summary validation failed', messageAr: 'فشل التحقق من Summary' },
  TREND_NOT_FOUND: { code: 'GOVERNANCE.TREND_NOT_FOUND', httpStatus: 404, messageEn: 'Trend not found', messageAr: 'Trend غير موجود' },
  TREND_ALREADY_EXISTS: { code: 'GOVERNANCE.TREND_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Trend already exists', messageAr: 'Trend موجود بالفعل' },
  TREND_VALIDATION_FAILED: { code: 'GOVERNANCE.TREND_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Trend validation failed', messageAr: 'فشل التحقق من Trend' },
  HISTORY_NOT_FOUND: { code: 'GOVERNANCE.HISTORY_NOT_FOUND', httpStatus: 404, messageEn: 'History not found', messageAr: 'History غير موجود' },
  HISTORY_ALREADY_EXISTS: { code: 'GOVERNANCE.HISTORY_ALREADY_EXISTS', httpStatus: 409, messageEn: 'History already exists', messageAr: 'History موجود بالفعل' },
  HISTORY_VALIDATION_FAILED: { code: 'GOVERNANCE.HISTORY_VALIDATION_FAILED', httpStatus: 400, messageEn: 'History validation failed', messageAr: 'فشل التحقق من History' },
  RECALCULATE_NOT_FOUND: { code: 'GOVERNANCE.RECALCULATE_NOT_FOUND', httpStatus: 404, messageEn: 'Recalculate not found', messageAr: 'Recalculate غير موجود' },
  RECALCULATE_ALREADY_EXISTS: { code: 'GOVERNANCE.RECALCULATE_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Recalculate already exists', messageAr: 'Recalculate موجود بالفعل' },
  RECALCULATE_VALIDATION_FAILED: { code: 'GOVERNANCE.RECALCULATE_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Recalculate validation failed', messageAr: 'فشل التحقق من Recalculate' },
  THRESHOLDS_NOT_FOUND: { code: 'GOVERNANCE.THRESHOLDS_NOT_FOUND', httpStatus: 404, messageEn: 'Thresholds not found', messageAr: 'Thresholds غير موجود' },
  THRESHOLDS_ALREADY_EXISTS: { code: 'GOVERNANCE.THRESHOLDS_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Thresholds already exists', messageAr: 'Thresholds موجود بالفعل' },
  THRESHOLDS_VALIDATION_FAILED: { code: 'GOVERNANCE.THRESHOLDS_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Thresholds validation failed', messageAr: 'فشل التحقق من Thresholds' },
  BOARD_WATCHLIST_NOT_FOUND: { code: 'GOVERNANCE.BOARD_WATCHLIST_NOT_FOUND', httpStatus: 404, messageEn: 'Board Watchlist not found', messageAr: 'Board Watchlist غير موجود' },
  BOARD_WATCHLIST_ALREADY_EXISTS: { code: 'GOVERNANCE.BOARD_WATCHLIST_ALREADY_EXISTS', httpStatus: 409, messageEn: 'Board Watchlist already exists', messageAr: 'Board Watchlist موجود بالفعل' },
  BOARD_WATCHLIST_VALIDATION_FAILED: { code: 'GOVERNANCE.BOARD_WATCHLIST_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Board Watchlist validation failed', messageAr: 'فشل التحقق من Board Watchlist' },
  FROM_RISK_NOT_FOUND: { code: 'GOVERNANCE.FROM_RISK_NOT_FOUND', httpStatus: 404, messageEn: 'From Risk not found', messageAr: 'From Risk غير موجود' },
  FROM_RISK_ALREADY_EXISTS: { code: 'GOVERNANCE.FROM_RISK_ALREADY_EXISTS', httpStatus: 409, messageEn: 'From Risk already exists', messageAr: 'From Risk موجود بالفعل' },
  FROM_RISK_VALIDATION_FAILED: { code: 'GOVERNANCE.FROM_RISK_VALIDATION_FAILED', httpStatus: 400, messageEn: 'From Risk validation failed', messageAr: 'فشل التحقق من From Risk' },
  FROM_AUDIT_FINDING_NOT_FOUND: { code: 'GOVERNANCE.FROM_AUDIT_FINDING_NOT_FOUND', httpStatus: 404, messageEn: 'From Audit Finding not found', messageAr: 'From Audit Finding غير موجود' },
  FROM_AUDIT_FINDING_ALREADY_EXISTS: { code: 'GOVERNANCE.FROM_AUDIT_FINDING_ALREADY_EXISTS', httpStatus: 409, messageEn: 'From Audit Finding already exists', messageAr: 'From Audit Finding موجود بالفعل' },
  FROM_AUDIT_FINDING_VALIDATION_FAILED: { code: 'GOVERNANCE.FROM_AUDIT_FINDING_VALIDATION_FAILED', httpStatus: 400, messageEn: 'From Audit Finding validation failed', messageAr: 'فشل التحقق من From Audit Finding' },

  UNAUTHORIZED: { code: 'GOVERNANCE.UNAUTHORIZED', httpStatus: 403, messageEn: 'Insufficient permissions for governance operation', messageAr: 'صلاحيات غير كافية لعملية governance' },
  INVALID_STATE_TRANSITION: { code: 'GOVERNANCE.INVALID_STATE_TRANSITION', httpStatus: 422, messageEn: 'Invalid state transition', messageAr: 'انتقال حالة غير صالح' },
  DEPENDENCY_CONFLICT: { code: 'GOVERNANCE.DEPENDENCY_CONFLICT', httpStatus: 409, messageEn: 'Cannot modify due to dependent records', messageAr: 'لا يمكن التعديل بسبب سجلات تابعة' },
  BULK_OPERATION_PARTIAL: { code: 'GOVERNANCE.BULK_OPERATION_PARTIAL', httpStatus: 207, messageEn: 'Bulk operation completed with partial failures', messageAr: 'اكتملت العملية المجمعة مع إخفاقات جزئية' },
  EXPORT_FAILED: { code: 'GOVERNANCE.EXPORT_FAILED', httpStatus: 500, messageEn: 'Export operation failed', messageAr: 'فشلت عملية التصدير' },
  IMPORT_VALIDATION_FAILED: { code: 'GOVERNANCE.IMPORT_VALIDATION_FAILED', httpStatus: 400, messageEn: 'Import data validation failed', messageAr: 'فشل التحقق من بيانات الاستيراد' },
} as const satisfies Record<string, ModuleErrorCode>;

export type GovernanceErrorCode = keyof typeof GOVERNANCE_ERROR_CODES;
