-- DKNF ENUM promotions for alert_definitions
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── alert_definitions.severity (5 values) ───
-- CREATE TYPE public.alert_definitions_severity_enum AS ENUM ('critical', 'high', 'medium', 'low', 'info');
-- ALTER TABLE public.alert_definitions
--   ALTER COLUMN severity TYPE public.alert_definitions_severity_enum
--   USING severity::public.alert_definitions_severity_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.alert_definitions'::regclass AND contype='c';

-- ─── alert_definitions.alert_class (3 values) ───
-- CREATE TYPE public.alert_definitions_alert_class_enum AS ENUM ('page', 'warn', 'info');
-- ALTER TABLE public.alert_definitions
--   ALTER COLUMN alert_class TYPE public.alert_definitions_alert_class_enum
--   USING alert_class::public.alert_definitions_alert_class_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.alert_definitions'::regclass AND contype='c';

-- ─── alert_definitions.comparison_operator (4 values) ───
-- CREATE TYPE public.alert_definitions_comparison_operator_enum AS ENUM ('lt', 'lte', 'gt', 'gte');
-- ALTER TABLE public.alert_definitions
--   ALTER COLUMN comparison_operator TYPE public.alert_definitions_comparison_operator_enum
--   USING comparison_operator::public.alert_definitions_comparison_operator_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.alert_definitions'::regclass AND contype='c';
