-- DKNF ENUM promotions for as_built_ledger
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── as_built_ledger.category (8 values) ───
-- CREATE TYPE public.as_built_ledger_category_enum AS ENUM ('service', 'migration', 'config', 'contract', 'schema', 'integration', 'deployment', 'other');
-- ALTER TABLE public.as_built_ledger
--   ALTER COLUMN category TYPE public.as_built_ledger_category_enum
--   USING category::public.as_built_ledger_category_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.as_built_ledger'::regclass AND contype='c';

-- ─── as_built_ledger.owner_layer (5 values) ───
-- CREATE TYPE public.as_built_ledger_owner_layer_enum AS ENUM ('DOS', 'DAuth', 'Product', 'Module', 'AI');
-- ALTER TABLE public.as_built_ledger
--   ALTER COLUMN owner_layer TYPE public.as_built_ledger_owner_layer_enum
--   USING owner_layer::public.as_built_ledger_owner_layer_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.as_built_ledger'::regclass AND contype='c';
