-- DKNF ENUM promotions for attestation_drafts
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── attestation_drafts.entity_type (2 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.attestation_drafts_entity_type_enum AS ENUM ('framework', 'control');
-- ALTER TABLE __TENANT_SCHEMA__.attestation_drafts
--   ALTER COLUMN entity_type TYPE __TENANT_SCHEMA__.attestation_drafts_entity_type_enum
--   USING entity_type::__TENANT_SCHEMA__.attestation_drafts_entity_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.attestation_drafts'::regclass AND contype='c';

-- ─── attestation_drafts.status (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.attestation_drafts_status_enum AS ENUM ('draft', 'pending_review', 'approved', 'rejected');
-- ALTER TABLE __TENANT_SCHEMA__.attestation_drafts
--   ALTER COLUMN status TYPE __TENANT_SCHEMA__.attestation_drafts_status_enum
--   USING status::__TENANT_SCHEMA__.attestation_drafts_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.attestation_drafts'::regclass AND contype='c';
