-- DKNF ENUM promotions for attestation_responses
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── attestation_responses.decision (3 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.attestation_responses_decision_enum AS ENUM ('confirmed', 'exception', 'delegated');
-- ALTER TABLE __TENANT_SCHEMA__.attestation_responses
--   ALTER COLUMN decision TYPE __TENANT_SCHEMA__.attestation_responses_decision_enum
--   USING decision::__TENANT_SCHEMA__.attestation_responses_decision_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.attestation_responses'::regclass AND contype='c';

-- ─── attestation_responses.status (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.attestation_responses_status_enum AS ENUM ('pending', 'submitted', 'overdue', 'escalated');
-- ALTER TABLE __TENANT_SCHEMA__.attestation_responses
--   ALTER COLUMN status TYPE __TENANT_SCHEMA__.attestation_responses_status_enum
--   USING status::__TENANT_SCHEMA__.attestation_responses_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.attestation_responses'::regclass AND contype='c';
