-- DKNF ENUM promotions for control_test_schedules
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── control_test_schedules.frequency (5 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.control_test_schedules_frequency_enum AS ENUM ('daily', 'weekly', 'monthly', 'quarterly', 'annually');
-- ALTER TABLE __TENANT_SCHEMA__.control_test_schedules
--   ALTER COLUMN frequency TYPE __TENANT_SCHEMA__.control_test_schedules_frequency_enum
--   USING frequency::__TENANT_SCHEMA__.control_test_schedules_frequency_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.control_test_schedules'::regclass AND contype='c';

-- ─── control_test_schedules.last_result (3 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.control_test_schedules_last_result_enum AS ENUM ('pass', 'fail', 'error');
-- ALTER TABLE __TENANT_SCHEMA__.control_test_schedules
--   ALTER COLUMN last_result TYPE __TENANT_SCHEMA__.control_test_schedules_last_result_enum
--   USING last_result::__TENANT_SCHEMA__.control_test_schedules_last_result_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.control_test_schedules'::regclass AND contype='c';
