-- DKNF ENUM promotions for incident_risk_links
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── incident_risk_links.link_type (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.incident_risk_links_link_type_enum AS ENUM ('materialized', 'contributing', 'affected', 'mitigated_by');
-- ALTER TABLE __TENANT_SCHEMA__.incident_risk_links
--   ALTER COLUMN link_type TYPE __TENANT_SCHEMA__.incident_risk_links_link_type_enum
--   USING link_type::__TENANT_SCHEMA__.incident_risk_links_link_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.incident_risk_links'::regclass AND contype='c';

-- ─── incident_risk_links.impact_on_risk (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.incident_risk_links_impact_on_risk_enum AS ENUM ('increase', 'decrease', 'neutral', 'reassess');
-- ALTER TABLE __TENANT_SCHEMA__.incident_risk_links
--   ALTER COLUMN impact_on_risk TYPE __TENANT_SCHEMA__.incident_risk_links_impact_on_risk_enum
--   USING impact_on_risk::__TENANT_SCHEMA__.incident_risk_links_impact_on_risk_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.incident_risk_links'::regclass AND contype='c';
