-- DKNF ENUM promotions for mcp_servers
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── mcp_servers.transport (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.mcp_servers_transport_enum AS ENUM ('stdio', 'http', 'sse', 'streamable-http');
-- ALTER TABLE __TENANT_SCHEMA__.mcp_servers
--   ALTER COLUMN transport TYPE __TENANT_SCHEMA__.mcp_servers_transport_enum
--   USING transport::__TENANT_SCHEMA__.mcp_servers_transport_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.mcp_servers'::regclass AND contype='c';

-- ─── mcp_servers.status (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.mcp_servers_status_enum AS ENUM ('registered', 'active', 'inactive', 'error');
-- ALTER TABLE __TENANT_SCHEMA__.mcp_servers
--   ALTER COLUMN status TYPE __TENANT_SCHEMA__.mcp_servers_status_enum
--   USING status::__TENANT_SCHEMA__.mcp_servers_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.mcp_servers'::regclass AND contype='c';
