-- DKNF ENUM promotions for module_sod_rules
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── module_sod_rules.conflict_type (2 values) ───
-- CREATE TYPE public.module_sod_rules_conflict_type_enum AS ENUM ('hard', 'soft');
-- ALTER TABLE public.module_sod_rules
--   ALTER COLUMN conflict_type TYPE public.module_sod_rules_conflict_type_enum
--   USING conflict_type::public.module_sod_rules_conflict_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.module_sod_rules'::regclass AND contype='c';

-- ─── module_sod_rules.resolution_strategy (4 values) ───
-- CREATE TYPE public.module_sod_rules_resolution_strategy_enum AS ENUM ('block', 'warn', 'escalate', 'allow');
-- ALTER TABLE public.module_sod_rules
--   ALTER COLUMN resolution_strategy TYPE public.module_sod_rules_resolution_strategy_enum
--   USING resolution_strategy::public.module_sod_rules_resolution_strategy_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.module_sod_rules'::regclass AND contype='c';
