-- DKNF ENUM promotions for org_pack_templates
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── org_pack_templates.size (3 values) ───
-- CREATE TYPE public.org_pack_templates_size_enum AS ENUM ('small', 'standard', 'enterprise');
-- ALTER TABLE public.org_pack_templates
--   ALTER COLUMN size TYPE public.org_pack_templates_size_enum
--   USING size::public.org_pack_templates_size_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.org_pack_templates'::regclass AND contype='c';

-- ─── org_pack_templates.org_type (2 values) ───
-- CREATE TYPE public.org_pack_templates_org_type_enum AS ENUM ('standard', 'matrix');
-- ALTER TABLE public.org_pack_templates
--   ALTER COLUMN org_type TYPE public.org_pack_templates_org_type_enum
--   USING org_type::public.org_pack_templates_org_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.org_pack_templates'::regclass AND contype='c';
