-- DKNF ENUM promotions for recovery_actions
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── recovery_actions.action_type (6 values) ───
-- CREATE TYPE public.recovery_actions_action_type_enum AS ENUM ('rollback', 'restart', 'disable', 'replay', 'manual_intervention', 'containment');
-- ALTER TABLE public.recovery_actions
--   ALTER COLUMN action_type TYPE public.recovery_actions_action_type_enum
--   USING action_type::public.recovery_actions_action_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.recovery_actions'::regclass AND contype='c';

-- ─── recovery_actions.status (6 values) ───
-- CREATE TYPE public.recovery_actions_status_enum AS ENUM ('pending_approval', 'approved', 'executing', 'completed', 'failed', 'cancelled');
-- ALTER TABLE public.recovery_actions
--   ALTER COLUMN status TYPE public.recovery_actions_status_enum
--   USING status::public.recovery_actions_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = 'public.recovery_actions'::regclass AND contype='c';
