-- DKNF ENUM promotions for risk_campaigns
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── risk_campaigns.campaign_type (3 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.risk_campaigns_campaign_type_enum AS ENUM ('rcsa', 'targeted', 'adhoc');
-- ALTER TABLE __TENANT_SCHEMA__.risk_campaigns
--   ALTER COLUMN campaign_type TYPE __TENANT_SCHEMA__.risk_campaigns_campaign_type_enum
--   USING campaign_type::__TENANT_SCHEMA__.risk_campaigns_campaign_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.risk_campaigns'::regclass AND contype='c';

-- ─── risk_campaigns.status (4 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.risk_campaigns_status_enum AS ENUM ('draft', 'active', 'completed', 'cancelled');
-- ALTER TABLE __TENANT_SCHEMA__.risk_campaigns
--   ALTER COLUMN status TYPE __TENANT_SCHEMA__.risk_campaigns_status_enum
--   USING status::__TENANT_SCHEMA__.risk_campaigns_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.risk_campaigns'::regclass AND contype='c';
