-- DKNF ENUM promotions for risk_approval_requests
-- Generated by dknf-fix-plan.ts. All statements commented out.
-- Per column: create a dedicated ENUM type, then ALTER the column
-- TYPE to use it (implicit cast via USING), then drop the CHECK constraint.

-- ─── risk_approval_requests.approval_type (5 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.risk_approval_requests_approval_type_enum AS ENUM ('risk_acceptance', 'treatment_plan', 'risk_closure', 'appetite_breach', 'escalation');
-- ALTER TABLE __TENANT_SCHEMA__.risk_approval_requests
--   ALTER COLUMN approval_type TYPE __TENANT_SCHEMA__.risk_approval_requests_approval_type_enum
--   USING approval_type::__TENANT_SCHEMA__.risk_approval_requests_approval_type_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.risk_approval_requests'::regclass AND contype='c';

-- ─── risk_approval_requests.urgency (3 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.risk_approval_requests_urgency_enum AS ENUM ('normal', 'urgent', 'critical');
-- ALTER TABLE __TENANT_SCHEMA__.risk_approval_requests
--   ALTER COLUMN urgency TYPE __TENANT_SCHEMA__.risk_approval_requests_urgency_enum
--   USING urgency::__TENANT_SCHEMA__.risk_approval_requests_urgency_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.risk_approval_requests'::regclass AND contype='c';

-- ─── risk_approval_requests.status (5 values) ───
-- CREATE TYPE __TENANT_SCHEMA__.risk_approval_requests_status_enum AS ENUM ('pending', 'approved', 'rejected', 'escalated', 'delegated');
-- ALTER TABLE __TENANT_SCHEMA__.risk_approval_requests
--   ALTER COLUMN status TYPE __TENANT_SCHEMA__.risk_approval_requests_status_enum
--   USING status::__TENANT_SCHEMA__.risk_approval_requests_status_enum;
-- -- drop the now-redundant CHECK constraint; name is Postgres-auto unless you renamed it:
-- -- SELECT conname FROM pg_constraint WHERE conrelid = '__TENANT_SCHEMA__.risk_approval_requests'::regclass AND contype='c';
