/**
 * asset — Module Security Registration
 * Auto-generated by scripts/codegen/generate-manifest-security.ts
 * Extracted from 14 route files, 3 unique permissions.
 *
 * DO NOT EDIT permissions extracted from routes. Add new permissions below the generated block.
 */

import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';

export const ASSET_PERMISSIONS: ModulePermission[] = [
  { permissionCode: 'asset.record.manage', resourceType: 'record', actionType: 'manage', descriptionEn: 'manage record', descriptionAr: 'manage record', sensitive: true, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'asset.record.read', resourceType: 'record', actionType: 'read', descriptionEn: 'read record', descriptionAr: 'read record', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
  { permissionCode: 'asset.record.write', resourceType: 'record', actionType: 'write', descriptionEn: 'write record', descriptionAr: 'write record', sensitive: false, fieldLevel: false, aiOnly: false, externalParty: false, deprecated: false, legacyAliases: [] },
];

export const ASSET_ROLES: ModuleRole[] = [
  { roleCode: 'asset.executive_owner', archetype: 'executive_owner', nameEn: 'asset executive owner', nameAr: 'executive_owner', descriptionEn: 'executive owner for asset', descriptionAr: 'executive_owner', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.manage', 'asset.record.read', 'asset.record.write'], authorityLevel: 'required', defaultScope: 'org' },
  { roleCode: 'asset.module_lead', archetype: 'module_lead', nameEn: 'asset module lead', nameAr: 'module_lead', descriptionEn: 'module lead for asset', descriptionAr: 'module_lead', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read', 'asset.record.write'], authorityLevel: 'required', defaultScope: 'department' },
  { roleCode: 'asset.approver', archetype: 'approver', nameEn: 'asset approver', nameAr: 'approver', descriptionEn: 'approver for asset', descriptionAr: 'approver', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read'], authorityLevel: 'required', defaultScope: 'own' },
  { roleCode: 'asset.operator', archetype: 'operator', nameEn: 'asset operator', nameAr: 'operator', descriptionEn: 'operator for asset', descriptionAr: 'operator', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read', 'asset.record.write'], authorityLevel: 'recommended', defaultScope: 'own' },
  { roleCode: 'asset.contributor', archetype: 'contributor', nameEn: 'asset contributor', nameAr: 'contributor', descriptionEn: 'contributor for asset', descriptionAr: 'contributor', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read', 'asset.record.write'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'asset.reviewer', archetype: 'reviewer', nameEn: 'asset reviewer', nameAr: 'reviewer', descriptionEn: 'reviewer for asset', descriptionAr: 'reviewer', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'asset.auditor', archetype: 'auditor', nameEn: 'asset auditor', nameAr: 'auditor', descriptionEn: 'auditor for asset', descriptionAr: 'auditor', isDefault: false, isSystem: false, isGlobal: false, permissions: ['asset.record.read'], authorityLevel: 'optional', defaultScope: 'own' },
  { roleCode: 'asset.viewer', archetype: 'viewer', nameEn: 'asset viewer', nameAr: 'viewer', descriptionEn: 'viewer for asset', descriptionAr: 'viewer', isDefault: true, isSystem: false, isGlobal: false, permissions: ['asset.record.read'], authorityLevel: 'optional', defaultScope: 'own' },
];

export const ASSET_ACTIONS: ModuleAction[] = [
  { actionCode: 'asset.record.manage', labelEn: 'manage record', labelAr: 'manage record', requiredPermissions: ['asset.record.manage'], requiredAuthorityLevel: 'required', sodSensitive: false, aiEnabled: false, aiBlocked: true, dangerLevel: 'destructive', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
  { actionCode: 'asset.record.read', labelEn: 'read record', labelAr: 'read record', requiredPermissions: ['asset.record.read'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'safe', requiresWorkflow: false, requiresApproval: false, auditable: false, reversible: true, bulkSafe: true, externalExposure: false },
  { actionCode: 'asset.record.write', labelEn: 'write record', labelAr: 'write record', requiredPermissions: ['asset.record.write'], requiredAuthorityLevel: 'optional', sodSensitive: false, aiEnabled: false, aiBlocked: false, dangerLevel: 'moderate', requiresWorkflow: false, requiresApproval: false, auditable: true, reversible: true, bulkSafe: false, externalExposure: false },
];
