/**
 * asset — Module Security Registration
 * Auto-generated by scripts/codegen/generate-manifest-security.ts
 * Extracted from 14 route files, 3 unique permissions.
 *
 * DO NOT EDIT permissions extracted from routes. Add new permissions below the generated block.
 */
import type { ModulePermission, ModuleRole, ModuleAction } from '@dos/types';
export declare const ASSET_PERMISSIONS: ModulePermission[];
export declare const ASSET_ROLES: ModuleRole[];
export declare const ASSET_ACTIONS: ModuleAction[];
