-- dos:extracted-from: ops/migrations/tenant/027_tenant_schema_tables.sql
-- dos:supersedes-checksum: b618781c42608331e3344799991235a22afbb73ab72c9789ef6478fd164416c8
-- dos:owning-module: ai
-- dos:tables: ai_actions, ai_activities, ai_alerts, ai_approvals, ai_assessments, ai_categories, ai_configs, ai_entities, ai_evidence, ai_feedback, ai_findings, ai_history, ai_issues, ai_kpis, ai_links, ai_logs, ai_members, ai_metrics, ai_reports, ai_reviews, ai_risks, ai_schedules, ai_settings, ai_snapshots, ai_tasks, ai_templates, ai_versions
-- dos:statement-count: 54
-- Generated by ops/normalization/scripts/split-megafile.ts
--
-- The migration runner treats this file as already applied whenever
-- the parent file's checksum is recorded in dos.platform_migrations.
-- Fresh databases re-run the parent first, then skip this shard.
CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_entities" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_entities_tenant ON "__TENANT_SCHEMA__"."ai_entities" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_activities" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_activities_tenant ON "__TENANT_SCHEMA__"."ai_activities" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_assessments" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_assessments_tenant ON "__TENANT_SCHEMA__"."ai_assessments" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_findings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_findings_tenant ON "__TENANT_SCHEMA__"."ai_findings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_logs" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_logs_tenant ON "__TENANT_SCHEMA__"."ai_logs" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_templates" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  version INTEGER DEFAULT 1,
  content JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_templates_tenant ON "__TENANT_SCHEMA__"."ai_templates" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_configs" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_configs_tenant ON "__TENANT_SCHEMA__"."ai_configs" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_snapshots" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_snapshots_tenant ON "__TENANT_SCHEMA__"."ai_snapshots" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_schedules" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_schedules_tenant ON "__TENANT_SCHEMA__"."ai_schedules" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_reports" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  title TEXT NOT NULL,
  query_definition JSONB,
  last_run_at TIMESTAMPTZ,
  schedule TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_reports_tenant ON "__TENANT_SCHEMA__"."ai_reports" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_alerts" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_alerts_tenant ON "__TENANT_SCHEMA__"."ai_alerts" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_metrics" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_metrics_tenant ON "__TENANT_SCHEMA__"."ai_metrics" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_tasks" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_tasks_tenant ON "__TENANT_SCHEMA__"."ai_tasks" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_issues" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_issues_tenant ON "__TENANT_SCHEMA__"."ai_issues" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_risks" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  code TEXT,
  severity TEXT,
  priority TEXT,
  status TEXT,
  assigned_to TEXT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_risks_tenant ON "__TENANT_SCHEMA__"."ai_risks" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_actions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_actions_tenant ON "__TENANT_SCHEMA__"."ai_actions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_approvals" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_approvals_tenant ON "__TENANT_SCHEMA__"."ai_approvals" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_history" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  event_type TEXT,
  payload JSONB,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_history_tenant ON "__TENANT_SCHEMA__"."ai_history" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_settings" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  config_key TEXT,
  config_value JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_settings_tenant ON "__TENANT_SCHEMA__"."ai_settings" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_members" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_members_tenant ON "__TENANT_SCHEMA__"."ai_members" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_versions" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_versions_tenant ON "__TENANT_SCHEMA__"."ai_versions" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_evidence" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_evidence_tenant ON "__TENANT_SCHEMA__"."ai_evidence" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_links" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_links_tenant ON "__TENANT_SCHEMA__"."ai_links" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_reviews" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_reviews_tenant ON "__TENANT_SCHEMA__"."ai_reviews" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_categories" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_categories_tenant ON "__TENANT_SCHEMA__"."ai_categories" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_feedback" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_feedback_tenant ON "__TENANT_SCHEMA__"."ai_feedback" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "__TENANT_SCHEMA__"."ai_kpis" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  status TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT,
  updated_by TEXT
);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_ai_kpis_tenant ON "__TENANT_SCHEMA__"."ai_kpis" (tenant_id);
EXCEPTION WHEN undefined_column OR insufficient_privilege THEN NULL; END $$;
